#ifndef ____BDCUINM5_H__
#define ____BDCUINM5_H__


#include "cstdint"






struct BDCUINM5 {
public:
	std::uint8_t UINM_PADS_1_CRC;
	std::uint8_t UINM_PADS_1_Counter;
	std::uint8_t UINM_PADS_ResponseErr;
	std::uint8_t UINM_PADS_IDC_ViewSWSt;
	std::uint8_t UINM_PADS_IDC_ViewSWVD;
	std::uint8_t UINM_PADS_IDC_ViewSWStuckSt;
	std::uint8_t UINM_PADS_IDC_VrSWSt;
	std::uint8_t UINM_PADS_IDC_VrSWStVD;
	std::uint8_t UINM_PADS_IDC_VrSWStuckSt;
	std::uint8_t UINM_PADS_IDC_PhoneSWSt;
	std::uint8_t UINM_PADS_IDC_PhoneSWStVD;
	std::uint8_t UINM_PADS_IDC_PhoneStuckSt;
	std::uint8_t UINM_PADS_CustomSWSt;
	std::uint8_t UINM_PADS_CustomSWStVD;
	std::uint8_t UINM_PADS_CustomSWstuck;
	std::uint8_t UINM_PADS_VolRollerRotatedDir;
	std::uint8_t UINM_PADS_IDC_SkipIncSWSt;
	std::uint8_t UINM_PADS_IDC_SkipIncSWStVD;
	std::uint8_t UINM_PADS_VolRollerSt;
	std::uint8_t UINM_PADS_IDC_SkipIncSWStuckSt;
	std::uint8_t UINM_PADS_IDC_SkipDecSWSt;
	std::uint8_t UINM_PADS_IDC_SkipDecSWStVD;
	std::uint8_t UINM_PADS_IDC_SkipDecSWStuckSt;
	std::uint8_t UINM_PADS_IDC_PlaySWSt;
	std::uint8_t UINM_PADS_IDC_PlaySWStVD;
	std::uint8_t UINM_PADS_IDC_PlaySWStuckSt;
	std::uint8_t UINM_PADS_CruSetSpeedRollerRotatedDir;
	std::uint8_t UINM_PADS_FolDistIncSWSt;
	std::uint8_t UINM_PADS_CruSetSpeedRollerSt;
	std::uint8_t UINM_PADS_FolDistIncSWStVD;
	std::uint8_t UINM_PADS_FolDistIncSWStuckSt;
	std::uint8_t UINM_PADS_FolDistDecSWSt;
	std::uint8_t UINM_PADS_FolDistDecSWStVD;
	std::uint8_t UINM_PADS_FolDistDecSWStuckSt;
	std::uint8_t UINM_PADS_OKSWSt;
	std::uint8_t UINM_PADS_OKSWStVD;
	std::uint8_t UINM_PADS_OKSWStuckSt;
	std::uint8_t UINM_PADS_VolRollerVD;
	std::uint8_t UINM_PADS_CruSetSpeedRollerVD;
	std::uint8_t UINM_PADS_IDC_ModeSWSt;
	std::uint8_t UINM_PADS_IDC_ModeSWStVD;
	std::uint8_t UINM_PADS_IDC_ModeSWStuckSt;
	std::uint8_t UINM_PADS_IDC_VolIncSWSt;
	std::uint8_t UINM_PADS_IDC_VolIncSWStVD;
	std::uint8_t UINM_PADS_IDC_VolIncSWStuckSt;
	std::uint8_t UINM_PADS_IDC_VolDecSWSt;
	std::uint8_t UINM_PADS_IDC_VolDecSWStVD;
	std::uint8_t UINM_PADS_IDC_VolDecSWStuckSt;
	std::uint8_t UINM_PADS_ICM_UPSWSt;
	std::uint8_t UINM_PADS_ICM_UPSWStVD;
	std::uint8_t UINM_PADS_ICM_UPSWStuckSt;
	std::uint8_t UINM_PADS_ICM_DownSWSt;
	std::uint8_t UINM_PADS_ICM_DownSWStVD;
	std::uint8_t UINM_PADS_ICM_DownSWStuckSt;
	std::uint8_t UINM_PADS_CruSWSt;
	std::uint8_t UINM_PADS_CruSWStVD;
	std::uint8_t UINM_PADS_CruSWStuckSt;
	std::uint8_t UINM_PADS_CruSpeedDecSWSt;
	std::uint8_t UINM_PADS_CruSpeedDecSWStVD;
	std::uint8_t UINM_PADS_CruSpeedDecSWStuckSt;
	std::uint8_t UINM_PADS_CruResumeSpeedIncSWSt;
	std::uint8_t UINM_PADS_CruResumeSpeedIncSWStVD;
	std::uint8_t UINM_PADS_CruResumeSpeedIncSWStuckSt;
	std::uint8_t UINM_PADS_CruTauGapSWSt;
	std::uint8_t UINM_PADS_CruTauGapSWStVD;
	std::uint8_t UINM_PADS_CruTauGapSWStcukSt;
	std::uint8_t UINM_PADS_CruTJAICASWSt;
	std::uint8_t UINM_PADS_CruTJAICASWStVD;
	std::uint8_t UINM_PADS_CruTJAICASWStuckSt;
	std::uint8_t UINM_PADS_IpadelSWSt;
	std::uint8_t UINM_PADS_IpadelSWStVD;
	std::uint8_t UINM_PADS_IpadelSWStuckSt;
	std::uint8_t UINM_PADS_Custom2SWSt;
	std::uint8_t UINM_PADS_Custom2SWStVD;
	std::uint8_t UINM_PADS_Custom2SWStuckSt;
	std::uint8_t UINM_PADS_ACCSWSt;
	std::uint8_t UINM_PADS_VoltageFaultSt;
	std::uint8_t UINM_PADS_L_UpSWSt;
	std::uint8_t UINM_PADS_L_UpSWStVD;
	std::uint8_t UINM_PADS_L_DownSWSt;
	std::uint8_t UINM_PADS_L_DownSWStVD;
	std::uint8_t UINM_PADS_L_leftSWSt;
	std::uint8_t UINM_PADS_L_LeftSWStVD;
	std::uint8_t UINM_PADS_L_RightSWSt;
	std::uint8_t UINM_PADS_L_RightSWStVD;
	std::uint8_t UINM_PADS_L_UDRollerRotatedDir;
	std::uint8_t UINM_PADS_L_UDRollerRSt;
	std::uint8_t UINM_PADS_L_UDRollerVD;
	std::uint8_t UINM_PADS_L_LRRollerRotatedDir;
	std::uint8_t UINM_PADS_L_LRRollerRSt;
	std::uint8_t UINM_PADS_L_LRRollerVD;
	std::uint8_t UINM_PADS_R_UpSWSt;
	std::uint8_t UINM_PADS_R_UpSWStVD;
	std::uint8_t UINM_PADS_R_DownSWSt;
	std::uint8_t UINM_PADS_R_DownSWStVD;
	std::uint8_t UINM_PADS_R_leftSWSt;
	std::uint8_t UINM_PADS_R_LeftSWStVD;
	std::uint8_t UINM_PADS_R_RightSWSt;
	std::uint8_t UINM_PADS_R_RightSWStVD;
	std::uint8_t UINM_PADS_R_UDRollerRotatedDir;
	std::uint8_t UINM_PADS_R_UDRollerRSt;
	std::uint8_t UINM_PADS_R_UDRollerVD;
	std::uint8_t UINM_PADS_R_LRRollerRotatedDir;
	std::uint8_t UINM_PADS_R_LRRollerRSt;
	std::uint8_t UINM_PADS_R_LRRollerVD;
/*
	BDCUINM5() {}
	~BDCUINM5() {}
	BDCUINM5(const std::uint8_t _UINM_PADS_1_CRC,const std::uint8_t _UINM_PADS_1_Counter,const std::uint8_t _UINM_PADS_ResponseErr,const std::uint8_t _UINM_PADS_IDC_ViewSWSt,const std::uint8_t _UINM_PADS_IDC_ViewSWVD,const std::uint8_t _UINM_PADS_IDC_ViewSWStuckSt,const std::uint8_t _UINM_PADS_IDC_VrSWSt,const std::uint8_t _UINM_PADS_IDC_VrSWStVD,const std::uint8_t _UINM_PADS_IDC_VrSWStuckSt,const std::uint8_t _UINM_PADS_IDC_PhoneSWSt,const std::uint8_t _UINM_PADS_IDC_PhoneSWStVD,const std::uint8_t _UINM_PADS_IDC_PhoneStuckSt,const std::uint8_t _UINM_PADS_CustomSWSt,const std::uint8_t _UINM_PADS_CustomSWStVD,const std::uint8_t _UINM_PADS_CustomSWstuck,const std::uint8_t _UINM_PADS_VolRollerRotatedDir,const std::uint8_t _UINM_PADS_IDC_SkipIncSWSt,const std::uint8_t _UINM_PADS_IDC_SkipIncSWStVD,const std::uint8_t _UINM_PADS_VolRollerSt,const std::uint8_t _UINM_PADS_IDC_SkipIncSWStuckSt,const std::uint8_t _UINM_PADS_IDC_SkipDecSWSt,const std::uint8_t _UINM_PADS_IDC_SkipDecSWStVD,const std::uint8_t _UINM_PADS_IDC_SkipDecSWStuckSt,const std::uint8_t _UINM_PADS_IDC_PlaySWSt,const std::uint8_t _UINM_PADS_IDC_PlaySWStVD,const std::uint8_t _UINM_PADS_IDC_PlaySWStuckSt,const std::uint8_t _UINM_PADS_CruSetSpeedRollerRotatedDir,const std::uint8_t _UINM_PADS_FolDistIncSWSt,const std::uint8_t _UINM_PADS_CruSetSpeedRollerSt,const std::uint8_t _UINM_PADS_FolDistIncSWStVD,const std::uint8_t _UINM_PADS_FolDistIncSWStuckSt,const std::uint8_t _UINM_PADS_FolDistDecSWSt,const std::uint8_t _UINM_PADS_FolDistDecSWStVD,const std::uint8_t _UINM_PADS_FolDistDecSWStuckSt,const std::uint8_t _UINM_PADS_OKSWSt,const std::uint8_t _UINM_PADS_OKSWStVD,const std::uint8_t _UINM_PADS_OKSWStuckSt,const std::uint8_t _UINM_PADS_VolRollerVD,const std::uint8_t _UINM_PADS_CruSetSpeedRollerVD,const std::uint8_t _UINM_PADS_IDC_ModeSWSt,const std::uint8_t _UINM_PADS_IDC_ModeSWStVD,const std::uint8_t _UINM_PADS_IDC_ModeSWStuckSt,const std::uint8_t _UINM_PADS_IDC_VolIncSWSt,const std::uint8_t _UINM_PADS_IDC_VolIncSWStVD,const std::uint8_t _UINM_PADS_IDC_VolIncSWStuckSt,const std::uint8_t _UINM_PADS_IDC_VolDecSWSt,const std::uint8_t _UINM_PADS_IDC_VolDecSWStVD,const std::uint8_t _UINM_PADS_IDC_VolDecSWStuckSt,const std::uint8_t _UINM_PADS_ICM_UPSWSt,const std::uint8_t _UINM_PADS_ICM_UPSWStVD,const std::uint8_t _UINM_PADS_ICM_UPSWStuckSt,const std::uint8_t _UINM_PADS_ICM_DownSWSt,const std::uint8_t _UINM_PADS_ICM_DownSWStVD,const std::uint8_t _UINM_PADS_ICM_DownSWStuckSt,const std::uint8_t _UINM_PADS_CruSWSt,const std::uint8_t _UINM_PADS_CruSWStVD,const std::uint8_t _UINM_PADS_CruSWStuckSt,const std::uint8_t _UINM_PADS_CruSpeedDecSWSt,const std::uint8_t _UINM_PADS_CruSpeedDecSWStVD,const std::uint8_t _UINM_PADS_CruSpeedDecSWStuckSt,const std::uint8_t _UINM_PADS_CruResumeSpeedIncSWSt,const std::uint8_t _UINM_PADS_CruResumeSpeedIncSWStVD,const std::uint8_t _UINM_PADS_CruResumeSpeedIncSWStuckSt,const std::uint8_t _UINM_PADS_CruTauGapSWSt,const std::uint8_t _UINM_PADS_CruTauGapSWStVD,const std::uint8_t _UINM_PADS_CruTauGapSWStcukSt,const std::uint8_t _UINM_PADS_CruTJAICASWSt,const std::uint8_t _UINM_PADS_CruTJAICASWStVD,const std::uint8_t _UINM_PADS_CruTJAICASWStuckSt,const std::uint8_t _UINM_PADS_IpadelSWSt,const std::uint8_t _UINM_PADS_IpadelSWStVD,const std::uint8_t _UINM_PADS_IpadelSWStuckSt,const std::uint8_t _UINM_PADS_Custom2SWSt,const std::uint8_t _UINM_PADS_Custom2SWStVD,const std::uint8_t _UINM_PADS_Custom2SWStuckSt,const std::uint8_t _UINM_PADS_ACCSWSt,const std::uint8_t _UINM_PADS_VoltageFaultSt,const std::uint8_t _UINM_PADS_L_UpSWSt,const std::uint8_t _UINM_PADS_L_UpSWStVD,const std::uint8_t _UINM_PADS_L_DownSWSt,const std::uint8_t _UINM_PADS_L_DownSWStVD,const std::uint8_t _UINM_PADS_L_leftSWSt,const std::uint8_t _UINM_PADS_L_LeftSWStVD,const std::uint8_t _UINM_PADS_L_RightSWSt,const std::uint8_t _UINM_PADS_L_RightSWStVD,const std::uint8_t _UINM_PADS_L_UDRollerRotatedDir,const std::uint8_t _UINM_PADS_L_UDRollerRSt,const std::uint8_t _UINM_PADS_L_UDRollerVD,const std::uint8_t _UINM_PADS_L_LRRollerRotatedDir,const std::uint8_t _UINM_PADS_L_LRRollerRSt,const std::uint8_t _UINM_PADS_L_LRRollerVD,const std::uint8_t _UINM_PADS_R_UpSWSt,const std::uint8_t _UINM_PADS_R_UpSWStVD,const std::uint8_t _UINM_PADS_R_DownSWSt,const std::uint8_t _UINM_PADS_R_DownSWStVD,const std::uint8_t _UINM_PADS_R_leftSWSt,const std::uint8_t _UINM_PADS_R_LeftSWStVD,const std::uint8_t _UINM_PADS_R_RightSWSt,const std::uint8_t _UINM_PADS_R_RightSWStVD,const std::uint8_t _UINM_PADS_R_UDRollerRotatedDir,const std::uint8_t _UINM_PADS_R_UDRollerRSt,const std::uint8_t _UINM_PADS_R_UDRollerVD,const std::uint8_t _UINM_PADS_R_LRRollerRotatedDir,const std::uint8_t _UINM_PADS_R_LRRollerRSt,const std::uint8_t _UINM_PADS_R_LRRollerVD):UINM_PADS_1_CRC(_UINM_PADS_1_CRC),UINM_PADS_1_Counter(_UINM_PADS_1_Counter),UINM_PADS_ResponseErr(_UINM_PADS_ResponseErr),UINM_PADS_IDC_ViewSWSt(_UINM_PADS_IDC_ViewSWSt),UINM_PADS_IDC_ViewSWVD(_UINM_PADS_IDC_ViewSWVD),UINM_PADS_IDC_ViewSWStuckSt(_UINM_PADS_IDC_ViewSWStuckSt),UINM_PADS_IDC_VrSWSt(_UINM_PADS_IDC_VrSWSt),UINM_PADS_IDC_VrSWStVD(_UINM_PADS_IDC_VrSWStVD),UINM_PADS_IDC_VrSWStuckSt(_UINM_PADS_IDC_VrSWStuckSt),UINM_PADS_IDC_PhoneSWSt(_UINM_PADS_IDC_PhoneSWSt),UINM_PADS_IDC_PhoneSWStVD(_UINM_PADS_IDC_PhoneSWStVD),UINM_PADS_IDC_PhoneStuckSt(_UINM_PADS_IDC_PhoneStuckSt),UINM_PADS_CustomSWSt(_UINM_PADS_CustomSWSt),UINM_PADS_CustomSWStVD(_UINM_PADS_CustomSWStVD),UINM_PADS_CustomSWstuck(_UINM_PADS_CustomSWstuck),UINM_PADS_VolRollerRotatedDir(_UINM_PADS_VolRollerRotatedDir),UINM_PADS_IDC_SkipIncSWSt(_UINM_PADS_IDC_SkipIncSWSt),UINM_PADS_IDC_SkipIncSWStVD(_UINM_PADS_IDC_SkipIncSWStVD),UINM_PADS_VolRollerSt(_UINM_PADS_VolRollerSt),UINM_PADS_IDC_SkipIncSWStuckSt(_UINM_PADS_IDC_SkipIncSWStuckSt),UINM_PADS_IDC_SkipDecSWSt(_UINM_PADS_IDC_SkipDecSWSt),UINM_PADS_IDC_SkipDecSWStVD(_UINM_PADS_IDC_SkipDecSWStVD),UINM_PADS_IDC_SkipDecSWStuckSt(_UINM_PADS_IDC_SkipDecSWStuckSt),UINM_PADS_IDC_PlaySWSt(_UINM_PADS_IDC_PlaySWSt),UINM_PADS_IDC_PlaySWStVD(_UINM_PADS_IDC_PlaySWStVD),UINM_PADS_IDC_PlaySWStuckSt(_UINM_PADS_IDC_PlaySWStuckSt),UINM_PADS_CruSetSpeedRollerRotatedDir(_UINM_PADS_CruSetSpeedRollerRotatedDir),UINM_PADS_FolDistIncSWSt(_UINM_PADS_FolDistIncSWSt),UINM_PADS_CruSetSpeedRollerSt(_UINM_PADS_CruSetSpeedRollerSt),UINM_PADS_FolDistIncSWStVD(_UINM_PADS_FolDistIncSWStVD),UINM_PADS_FolDistIncSWStuckSt(_UINM_PADS_FolDistIncSWStuckSt),UINM_PADS_FolDistDecSWSt(_UINM_PADS_FolDistDecSWSt),UINM_PADS_FolDistDecSWStVD(_UINM_PADS_FolDistDecSWStVD),UINM_PADS_FolDistDecSWStuckSt(_UINM_PADS_FolDistDecSWStuckSt),UINM_PADS_OKSWSt(_UINM_PADS_OKSWSt),UINM_PADS_OKSWStVD(_UINM_PADS_OKSWStVD),UINM_PADS_OKSWStuckSt(_UINM_PADS_OKSWStuckSt),UINM_PADS_VolRollerVD(_UINM_PADS_VolRollerVD),UINM_PADS_CruSetSpeedRollerVD(_UINM_PADS_CruSetSpeedRollerVD),UINM_PADS_IDC_ModeSWSt(_UINM_PADS_IDC_ModeSWSt),UINM_PADS_IDC_ModeSWStVD(_UINM_PADS_IDC_ModeSWStVD),UINM_PADS_IDC_ModeSWStuckSt(_UINM_PADS_IDC_ModeSWStuckSt),UINM_PADS_IDC_VolIncSWSt(_UINM_PADS_IDC_VolIncSWSt),UINM_PADS_IDC_VolIncSWStVD(_UINM_PADS_IDC_VolIncSWStVD),UINM_PADS_IDC_VolIncSWStuckSt(_UINM_PADS_IDC_VolIncSWStuckSt),UINM_PADS_IDC_VolDecSWSt(_UINM_PADS_IDC_VolDecSWSt),UINM_PADS_IDC_VolDecSWStVD(_UINM_PADS_IDC_VolDecSWStVD),UINM_PADS_IDC_VolDecSWStuckSt(_UINM_PADS_IDC_VolDecSWStuckSt),UINM_PADS_ICM_UPSWSt(_UINM_PADS_ICM_UPSWSt),UINM_PADS_ICM_UPSWStVD(_UINM_PADS_ICM_UPSWStVD),UINM_PADS_ICM_UPSWStuckSt(_UINM_PADS_ICM_UPSWStuckSt),UINM_PADS_ICM_DownSWSt(_UINM_PADS_ICM_DownSWSt),UINM_PADS_ICM_DownSWStVD(_UINM_PADS_ICM_DownSWStVD),UINM_PADS_ICM_DownSWStuckSt(_UINM_PADS_ICM_DownSWStuckSt),UINM_PADS_CruSWSt(_UINM_PADS_CruSWSt),UINM_PADS_CruSWStVD(_UINM_PADS_CruSWStVD),UINM_PADS_CruSWStuckSt(_UINM_PADS_CruSWStuckSt),UINM_PADS_CruSpeedDecSWSt(_UINM_PADS_CruSpeedDecSWSt),UINM_PADS_CruSpeedDecSWStVD(_UINM_PADS_CruSpeedDecSWStVD),UINM_PADS_CruSpeedDecSWStuckSt(_UINM_PADS_CruSpeedDecSWStuckSt),UINM_PADS_CruResumeSpeedIncSWSt(_UINM_PADS_CruResumeSpeedIncSWSt),UINM_PADS_CruResumeSpeedIncSWStVD(_UINM_PADS_CruResumeSpeedIncSWStVD),UINM_PADS_CruResumeSpeedIncSWStuckSt(_UINM_PADS_CruResumeSpeedIncSWStuckSt),UINM_PADS_CruTauGapSWSt(_UINM_PADS_CruTauGapSWSt),UINM_PADS_CruTauGapSWStVD(_UINM_PADS_CruTauGapSWStVD),UINM_PADS_CruTauGapSWStcukSt(_UINM_PADS_CruTauGapSWStcukSt),UINM_PADS_CruTJAICASWSt(_UINM_PADS_CruTJAICASWSt),UINM_PADS_CruTJAICASWStVD(_UINM_PADS_CruTJAICASWStVD),UINM_PADS_CruTJAICASWStuckSt(_UINM_PADS_CruTJAICASWStuckSt),UINM_PADS_IpadelSWSt(_UINM_PADS_IpadelSWSt),UINM_PADS_IpadelSWStVD(_UINM_PADS_IpadelSWStVD),UINM_PADS_IpadelSWStuckSt(_UINM_PADS_IpadelSWStuckSt),UINM_PADS_Custom2SWSt(_UINM_PADS_Custom2SWSt),UINM_PADS_Custom2SWStVD(_UINM_PADS_Custom2SWStVD),UINM_PADS_Custom2SWStuckSt(_UINM_PADS_Custom2SWStuckSt),UINM_PADS_ACCSWSt(_UINM_PADS_ACCSWSt),UINM_PADS_VoltageFaultSt(_UINM_PADS_VoltageFaultSt),UINM_PADS_L_UpSWSt(_UINM_PADS_L_UpSWSt),UINM_PADS_L_UpSWStVD(_UINM_PADS_L_UpSWStVD),UINM_PADS_L_DownSWSt(_UINM_PADS_L_DownSWSt),UINM_PADS_L_DownSWStVD(_UINM_PADS_L_DownSWStVD),UINM_PADS_L_leftSWSt(_UINM_PADS_L_leftSWSt),UINM_PADS_L_LeftSWStVD(_UINM_PADS_L_LeftSWStVD),UINM_PADS_L_RightSWSt(_UINM_PADS_L_RightSWSt),UINM_PADS_L_RightSWStVD(_UINM_PADS_L_RightSWStVD),UINM_PADS_L_UDRollerRotatedDir(_UINM_PADS_L_UDRollerRotatedDir),UINM_PADS_L_UDRollerRSt(_UINM_PADS_L_UDRollerRSt),UINM_PADS_L_UDRollerVD(_UINM_PADS_L_UDRollerVD),UINM_PADS_L_LRRollerRotatedDir(_UINM_PADS_L_LRRollerRotatedDir),UINM_PADS_L_LRRollerRSt(_UINM_PADS_L_LRRollerRSt),UINM_PADS_L_LRRollerVD(_UINM_PADS_L_LRRollerVD),UINM_PADS_R_UpSWSt(_UINM_PADS_R_UpSWSt),UINM_PADS_R_UpSWStVD(_UINM_PADS_R_UpSWStVD),UINM_PADS_R_DownSWSt(_UINM_PADS_R_DownSWSt),UINM_PADS_R_DownSWStVD(_UINM_PADS_R_DownSWStVD),UINM_PADS_R_leftSWSt(_UINM_PADS_R_leftSWSt),UINM_PADS_R_LeftSWStVD(_UINM_PADS_R_LeftSWStVD),UINM_PADS_R_RightSWSt(_UINM_PADS_R_RightSWSt),UINM_PADS_R_RightSWStVD(_UINM_PADS_R_RightSWStVD),UINM_PADS_R_UDRollerRotatedDir(_UINM_PADS_R_UDRollerRotatedDir),UINM_PADS_R_UDRollerRSt(_UINM_PADS_R_UDRollerRSt),UINM_PADS_R_UDRollerVD(_UINM_PADS_R_UDRollerVD),UINM_PADS_R_LRRollerRotatedDir(_UINM_PADS_R_LRRollerRotatedDir),UINM_PADS_R_LRRollerRSt(_UINM_PADS_R_LRRollerRSt),UINM_PADS_R_LRRollerVD(_UINM_PADS_R_LRRollerVD) {}
	BDCUINM5(const BDCUINM5 &_x){
		UINM_PADS_1_CRC = _x.UINM_PADS_1_CRC;
		UINM_PADS_1_Counter = _x.UINM_PADS_1_Counter;
		UINM_PADS_ResponseErr = _x.UINM_PADS_ResponseErr;
		UINM_PADS_IDC_ViewSWSt = _x.UINM_PADS_IDC_ViewSWSt;
		UINM_PADS_IDC_ViewSWVD = _x.UINM_PADS_IDC_ViewSWVD;
		UINM_PADS_IDC_ViewSWStuckSt = _x.UINM_PADS_IDC_ViewSWStuckSt;
		UINM_PADS_IDC_VrSWSt = _x.UINM_PADS_IDC_VrSWSt;
		UINM_PADS_IDC_VrSWStVD = _x.UINM_PADS_IDC_VrSWStVD;
		UINM_PADS_IDC_VrSWStuckSt = _x.UINM_PADS_IDC_VrSWStuckSt;
		UINM_PADS_IDC_PhoneSWSt = _x.UINM_PADS_IDC_PhoneSWSt;
		UINM_PADS_IDC_PhoneSWStVD = _x.UINM_PADS_IDC_PhoneSWStVD;
		UINM_PADS_IDC_PhoneStuckSt = _x.UINM_PADS_IDC_PhoneStuckSt;
		UINM_PADS_CustomSWSt = _x.UINM_PADS_CustomSWSt;
		UINM_PADS_CustomSWStVD = _x.UINM_PADS_CustomSWStVD;
		UINM_PADS_CustomSWstuck = _x.UINM_PADS_CustomSWstuck;
		UINM_PADS_VolRollerRotatedDir = _x.UINM_PADS_VolRollerRotatedDir;
		UINM_PADS_IDC_SkipIncSWSt = _x.UINM_PADS_IDC_SkipIncSWSt;
		UINM_PADS_IDC_SkipIncSWStVD = _x.UINM_PADS_IDC_SkipIncSWStVD;
		UINM_PADS_VolRollerSt = _x.UINM_PADS_VolRollerSt;
		UINM_PADS_IDC_SkipIncSWStuckSt = _x.UINM_PADS_IDC_SkipIncSWStuckSt;
		UINM_PADS_IDC_SkipDecSWSt = _x.UINM_PADS_IDC_SkipDecSWSt;
		UINM_PADS_IDC_SkipDecSWStVD = _x.UINM_PADS_IDC_SkipDecSWStVD;
		UINM_PADS_IDC_SkipDecSWStuckSt = _x.UINM_PADS_IDC_SkipDecSWStuckSt;
		UINM_PADS_IDC_PlaySWSt = _x.UINM_PADS_IDC_PlaySWSt;
		UINM_PADS_IDC_PlaySWStVD = _x.UINM_PADS_IDC_PlaySWStVD;
		UINM_PADS_IDC_PlaySWStuckSt = _x.UINM_PADS_IDC_PlaySWStuckSt;
		UINM_PADS_CruSetSpeedRollerRotatedDir = _x.UINM_PADS_CruSetSpeedRollerRotatedDir;
		UINM_PADS_FolDistIncSWSt = _x.UINM_PADS_FolDistIncSWSt;
		UINM_PADS_CruSetSpeedRollerSt = _x.UINM_PADS_CruSetSpeedRollerSt;
		UINM_PADS_FolDistIncSWStVD = _x.UINM_PADS_FolDistIncSWStVD;
		UINM_PADS_FolDistIncSWStuckSt = _x.UINM_PADS_FolDistIncSWStuckSt;
		UINM_PADS_FolDistDecSWSt = _x.UINM_PADS_FolDistDecSWSt;
		UINM_PADS_FolDistDecSWStVD = _x.UINM_PADS_FolDistDecSWStVD;
		UINM_PADS_FolDistDecSWStuckSt = _x.UINM_PADS_FolDistDecSWStuckSt;
		UINM_PADS_OKSWSt = _x.UINM_PADS_OKSWSt;
		UINM_PADS_OKSWStVD = _x.UINM_PADS_OKSWStVD;
		UINM_PADS_OKSWStuckSt = _x.UINM_PADS_OKSWStuckSt;
		UINM_PADS_VolRollerVD = _x.UINM_PADS_VolRollerVD;
		UINM_PADS_CruSetSpeedRollerVD = _x.UINM_PADS_CruSetSpeedRollerVD;
		UINM_PADS_IDC_ModeSWSt = _x.UINM_PADS_IDC_ModeSWSt;
		UINM_PADS_IDC_ModeSWStVD = _x.UINM_PADS_IDC_ModeSWStVD;
		UINM_PADS_IDC_ModeSWStuckSt = _x.UINM_PADS_IDC_ModeSWStuckSt;
		UINM_PADS_IDC_VolIncSWSt = _x.UINM_PADS_IDC_VolIncSWSt;
		UINM_PADS_IDC_VolIncSWStVD = _x.UINM_PADS_IDC_VolIncSWStVD;
		UINM_PADS_IDC_VolIncSWStuckSt = _x.UINM_PADS_IDC_VolIncSWStuckSt;
		UINM_PADS_IDC_VolDecSWSt = _x.UINM_PADS_IDC_VolDecSWSt;
		UINM_PADS_IDC_VolDecSWStVD = _x.UINM_PADS_IDC_VolDecSWStVD;
		UINM_PADS_IDC_VolDecSWStuckSt = _x.UINM_PADS_IDC_VolDecSWStuckSt;
		UINM_PADS_ICM_UPSWSt = _x.UINM_PADS_ICM_UPSWSt;
		UINM_PADS_ICM_UPSWStVD = _x.UINM_PADS_ICM_UPSWStVD;
		UINM_PADS_ICM_UPSWStuckSt = _x.UINM_PADS_ICM_UPSWStuckSt;
		UINM_PADS_ICM_DownSWSt = _x.UINM_PADS_ICM_DownSWSt;
		UINM_PADS_ICM_DownSWStVD = _x.UINM_PADS_ICM_DownSWStVD;
		UINM_PADS_ICM_DownSWStuckSt = _x.UINM_PADS_ICM_DownSWStuckSt;
		UINM_PADS_CruSWSt = _x.UINM_PADS_CruSWSt;
		UINM_PADS_CruSWStVD = _x.UINM_PADS_CruSWStVD;
		UINM_PADS_CruSWStuckSt = _x.UINM_PADS_CruSWStuckSt;
		UINM_PADS_CruSpeedDecSWSt = _x.UINM_PADS_CruSpeedDecSWSt;
		UINM_PADS_CruSpeedDecSWStVD = _x.UINM_PADS_CruSpeedDecSWStVD;
		UINM_PADS_CruSpeedDecSWStuckSt = _x.UINM_PADS_CruSpeedDecSWStuckSt;
		UINM_PADS_CruResumeSpeedIncSWSt = _x.UINM_PADS_CruResumeSpeedIncSWSt;
		UINM_PADS_CruResumeSpeedIncSWStVD = _x.UINM_PADS_CruResumeSpeedIncSWStVD;
		UINM_PADS_CruResumeSpeedIncSWStuckSt = _x.UINM_PADS_CruResumeSpeedIncSWStuckSt;
		UINM_PADS_CruTauGapSWSt = _x.UINM_PADS_CruTauGapSWSt;
		UINM_PADS_CruTauGapSWStVD = _x.UINM_PADS_CruTauGapSWStVD;
		UINM_PADS_CruTauGapSWStcukSt = _x.UINM_PADS_CruTauGapSWStcukSt;
		UINM_PADS_CruTJAICASWSt = _x.UINM_PADS_CruTJAICASWSt;
		UINM_PADS_CruTJAICASWStVD = _x.UINM_PADS_CruTJAICASWStVD;
		UINM_PADS_CruTJAICASWStuckSt = _x.UINM_PADS_CruTJAICASWStuckSt;
		UINM_PADS_IpadelSWSt = _x.UINM_PADS_IpadelSWSt;
		UINM_PADS_IpadelSWStVD = _x.UINM_PADS_IpadelSWStVD;
		UINM_PADS_IpadelSWStuckSt = _x.UINM_PADS_IpadelSWStuckSt;
		UINM_PADS_Custom2SWSt = _x.UINM_PADS_Custom2SWSt;
		UINM_PADS_Custom2SWStVD = _x.UINM_PADS_Custom2SWStVD;
		UINM_PADS_Custom2SWStuckSt = _x.UINM_PADS_Custom2SWStuckSt;
		UINM_PADS_ACCSWSt = _x.UINM_PADS_ACCSWSt;
		UINM_PADS_VoltageFaultSt = _x.UINM_PADS_VoltageFaultSt;
		UINM_PADS_L_UpSWSt = _x.UINM_PADS_L_UpSWSt;
		UINM_PADS_L_UpSWStVD = _x.UINM_PADS_L_UpSWStVD;
		UINM_PADS_L_DownSWSt = _x.UINM_PADS_L_DownSWSt;
		UINM_PADS_L_DownSWStVD = _x.UINM_PADS_L_DownSWStVD;
		UINM_PADS_L_leftSWSt = _x.UINM_PADS_L_leftSWSt;
		UINM_PADS_L_LeftSWStVD = _x.UINM_PADS_L_LeftSWStVD;
		UINM_PADS_L_RightSWSt = _x.UINM_PADS_L_RightSWSt;
		UINM_PADS_L_RightSWStVD = _x.UINM_PADS_L_RightSWStVD;
		UINM_PADS_L_UDRollerRotatedDir = _x.UINM_PADS_L_UDRollerRotatedDir;
		UINM_PADS_L_UDRollerRSt = _x.UINM_PADS_L_UDRollerRSt;
		UINM_PADS_L_UDRollerVD = _x.UINM_PADS_L_UDRollerVD;
		UINM_PADS_L_LRRollerRotatedDir = _x.UINM_PADS_L_LRRollerRotatedDir;
		UINM_PADS_L_LRRollerRSt = _x.UINM_PADS_L_LRRollerRSt;
		UINM_PADS_L_LRRollerVD = _x.UINM_PADS_L_LRRollerVD;
		UINM_PADS_R_UpSWSt = _x.UINM_PADS_R_UpSWSt;
		UINM_PADS_R_UpSWStVD = _x.UINM_PADS_R_UpSWStVD;
		UINM_PADS_R_DownSWSt = _x.UINM_PADS_R_DownSWSt;
		UINM_PADS_R_DownSWStVD = _x.UINM_PADS_R_DownSWStVD;
		UINM_PADS_R_leftSWSt = _x.UINM_PADS_R_leftSWSt;
		UINM_PADS_R_LeftSWStVD = _x.UINM_PADS_R_LeftSWStVD;
		UINM_PADS_R_RightSWSt = _x.UINM_PADS_R_RightSWSt;
		UINM_PADS_R_RightSWStVD = _x.UINM_PADS_R_RightSWStVD;
		UINM_PADS_R_UDRollerRotatedDir = _x.UINM_PADS_R_UDRollerRotatedDir;
		UINM_PADS_R_UDRollerRSt = _x.UINM_PADS_R_UDRollerRSt;
		UINM_PADS_R_UDRollerVD = _x.UINM_PADS_R_UDRollerVD;
		UINM_PADS_R_LRRollerRotatedDir = _x.UINM_PADS_R_LRRollerRotatedDir;
		UINM_PADS_R_LRRollerRSt = _x.UINM_PADS_R_LRRollerRSt;
		UINM_PADS_R_LRRollerVD = _x.UINM_PADS_R_LRRollerVD;
	}
	BDCUINM5(BDCUINM5 &&_x){
		UINM_PADS_1_CRC = std::move(_x.UINM_PADS_1_CRC);
		UINM_PADS_1_Counter = std::move(_x.UINM_PADS_1_Counter);
		UINM_PADS_ResponseErr = std::move(_x.UINM_PADS_ResponseErr);
		UINM_PADS_IDC_ViewSWSt = std::move(_x.UINM_PADS_IDC_ViewSWSt);
		UINM_PADS_IDC_ViewSWVD = std::move(_x.UINM_PADS_IDC_ViewSWVD);
		UINM_PADS_IDC_ViewSWStuckSt = std::move(_x.UINM_PADS_IDC_ViewSWStuckSt);
		UINM_PADS_IDC_VrSWSt = std::move(_x.UINM_PADS_IDC_VrSWSt);
		UINM_PADS_IDC_VrSWStVD = std::move(_x.UINM_PADS_IDC_VrSWStVD);
		UINM_PADS_IDC_VrSWStuckSt = std::move(_x.UINM_PADS_IDC_VrSWStuckSt);
		UINM_PADS_IDC_PhoneSWSt = std::move(_x.UINM_PADS_IDC_PhoneSWSt);
		UINM_PADS_IDC_PhoneSWStVD = std::move(_x.UINM_PADS_IDC_PhoneSWStVD);
		UINM_PADS_IDC_PhoneStuckSt = std::move(_x.UINM_PADS_IDC_PhoneStuckSt);
		UINM_PADS_CustomSWSt = std::move(_x.UINM_PADS_CustomSWSt);
		UINM_PADS_CustomSWStVD = std::move(_x.UINM_PADS_CustomSWStVD);
		UINM_PADS_CustomSWstuck = std::move(_x.UINM_PADS_CustomSWstuck);
		UINM_PADS_VolRollerRotatedDir = std::move(_x.UINM_PADS_VolRollerRotatedDir);
		UINM_PADS_IDC_SkipIncSWSt = std::move(_x.UINM_PADS_IDC_SkipIncSWSt);
		UINM_PADS_IDC_SkipIncSWStVD = std::move(_x.UINM_PADS_IDC_SkipIncSWStVD);
		UINM_PADS_VolRollerSt = std::move(_x.UINM_PADS_VolRollerSt);
		UINM_PADS_IDC_SkipIncSWStuckSt = std::move(_x.UINM_PADS_IDC_SkipIncSWStuckSt);
		UINM_PADS_IDC_SkipDecSWSt = std::move(_x.UINM_PADS_IDC_SkipDecSWSt);
		UINM_PADS_IDC_SkipDecSWStVD = std::move(_x.UINM_PADS_IDC_SkipDecSWStVD);
		UINM_PADS_IDC_SkipDecSWStuckSt = std::move(_x.UINM_PADS_IDC_SkipDecSWStuckSt);
		UINM_PADS_IDC_PlaySWSt = std::move(_x.UINM_PADS_IDC_PlaySWSt);
		UINM_PADS_IDC_PlaySWStVD = std::move(_x.UINM_PADS_IDC_PlaySWStVD);
		UINM_PADS_IDC_PlaySWStuckSt = std::move(_x.UINM_PADS_IDC_PlaySWStuckSt);
		UINM_PADS_CruSetSpeedRollerRotatedDir = std::move(_x.UINM_PADS_CruSetSpeedRollerRotatedDir);
		UINM_PADS_FolDistIncSWSt = std::move(_x.UINM_PADS_FolDistIncSWSt);
		UINM_PADS_CruSetSpeedRollerSt = std::move(_x.UINM_PADS_CruSetSpeedRollerSt);
		UINM_PADS_FolDistIncSWStVD = std::move(_x.UINM_PADS_FolDistIncSWStVD);
		UINM_PADS_FolDistIncSWStuckSt = std::move(_x.UINM_PADS_FolDistIncSWStuckSt);
		UINM_PADS_FolDistDecSWSt = std::move(_x.UINM_PADS_FolDistDecSWSt);
		UINM_PADS_FolDistDecSWStVD = std::move(_x.UINM_PADS_FolDistDecSWStVD);
		UINM_PADS_FolDistDecSWStuckSt = std::move(_x.UINM_PADS_FolDistDecSWStuckSt);
		UINM_PADS_OKSWSt = std::move(_x.UINM_PADS_OKSWSt);
		UINM_PADS_OKSWStVD = std::move(_x.UINM_PADS_OKSWStVD);
		UINM_PADS_OKSWStuckSt = std::move(_x.UINM_PADS_OKSWStuckSt);
		UINM_PADS_VolRollerVD = std::move(_x.UINM_PADS_VolRollerVD);
		UINM_PADS_CruSetSpeedRollerVD = std::move(_x.UINM_PADS_CruSetSpeedRollerVD);
		UINM_PADS_IDC_ModeSWSt = std::move(_x.UINM_PADS_IDC_ModeSWSt);
		UINM_PADS_IDC_ModeSWStVD = std::move(_x.UINM_PADS_IDC_ModeSWStVD);
		UINM_PADS_IDC_ModeSWStuckSt = std::move(_x.UINM_PADS_IDC_ModeSWStuckSt);
		UINM_PADS_IDC_VolIncSWSt = std::move(_x.UINM_PADS_IDC_VolIncSWSt);
		UINM_PADS_IDC_VolIncSWStVD = std::move(_x.UINM_PADS_IDC_VolIncSWStVD);
		UINM_PADS_IDC_VolIncSWStuckSt = std::move(_x.UINM_PADS_IDC_VolIncSWStuckSt);
		UINM_PADS_IDC_VolDecSWSt = std::move(_x.UINM_PADS_IDC_VolDecSWSt);
		UINM_PADS_IDC_VolDecSWStVD = std::move(_x.UINM_PADS_IDC_VolDecSWStVD);
		UINM_PADS_IDC_VolDecSWStuckSt = std::move(_x.UINM_PADS_IDC_VolDecSWStuckSt);
		UINM_PADS_ICM_UPSWSt = std::move(_x.UINM_PADS_ICM_UPSWSt);
		UINM_PADS_ICM_UPSWStVD = std::move(_x.UINM_PADS_ICM_UPSWStVD);
		UINM_PADS_ICM_UPSWStuckSt = std::move(_x.UINM_PADS_ICM_UPSWStuckSt);
		UINM_PADS_ICM_DownSWSt = std::move(_x.UINM_PADS_ICM_DownSWSt);
		UINM_PADS_ICM_DownSWStVD = std::move(_x.UINM_PADS_ICM_DownSWStVD);
		UINM_PADS_ICM_DownSWStuckSt = std::move(_x.UINM_PADS_ICM_DownSWStuckSt);
		UINM_PADS_CruSWSt = std::move(_x.UINM_PADS_CruSWSt);
		UINM_PADS_CruSWStVD = std::move(_x.UINM_PADS_CruSWStVD);
		UINM_PADS_CruSWStuckSt = std::move(_x.UINM_PADS_CruSWStuckSt);
		UINM_PADS_CruSpeedDecSWSt = std::move(_x.UINM_PADS_CruSpeedDecSWSt);
		UINM_PADS_CruSpeedDecSWStVD = std::move(_x.UINM_PADS_CruSpeedDecSWStVD);
		UINM_PADS_CruSpeedDecSWStuckSt = std::move(_x.UINM_PADS_CruSpeedDecSWStuckSt);
		UINM_PADS_CruResumeSpeedIncSWSt = std::move(_x.UINM_PADS_CruResumeSpeedIncSWSt);
		UINM_PADS_CruResumeSpeedIncSWStVD = std::move(_x.UINM_PADS_CruResumeSpeedIncSWStVD);
		UINM_PADS_CruResumeSpeedIncSWStuckSt = std::move(_x.UINM_PADS_CruResumeSpeedIncSWStuckSt);
		UINM_PADS_CruTauGapSWSt = std::move(_x.UINM_PADS_CruTauGapSWSt);
		UINM_PADS_CruTauGapSWStVD = std::move(_x.UINM_PADS_CruTauGapSWStVD);
		UINM_PADS_CruTauGapSWStcukSt = std::move(_x.UINM_PADS_CruTauGapSWStcukSt);
		UINM_PADS_CruTJAICASWSt = std::move(_x.UINM_PADS_CruTJAICASWSt);
		UINM_PADS_CruTJAICASWStVD = std::move(_x.UINM_PADS_CruTJAICASWStVD);
		UINM_PADS_CruTJAICASWStuckSt = std::move(_x.UINM_PADS_CruTJAICASWStuckSt);
		UINM_PADS_IpadelSWSt = std::move(_x.UINM_PADS_IpadelSWSt);
		UINM_PADS_IpadelSWStVD = std::move(_x.UINM_PADS_IpadelSWStVD);
		UINM_PADS_IpadelSWStuckSt = std::move(_x.UINM_PADS_IpadelSWStuckSt);
		UINM_PADS_Custom2SWSt = std::move(_x.UINM_PADS_Custom2SWSt);
		UINM_PADS_Custom2SWStVD = std::move(_x.UINM_PADS_Custom2SWStVD);
		UINM_PADS_Custom2SWStuckSt = std::move(_x.UINM_PADS_Custom2SWStuckSt);
		UINM_PADS_ACCSWSt = std::move(_x.UINM_PADS_ACCSWSt);
		UINM_PADS_VoltageFaultSt = std::move(_x.UINM_PADS_VoltageFaultSt);
		UINM_PADS_L_UpSWSt = std::move(_x.UINM_PADS_L_UpSWSt);
		UINM_PADS_L_UpSWStVD = std::move(_x.UINM_PADS_L_UpSWStVD);
		UINM_PADS_L_DownSWSt = std::move(_x.UINM_PADS_L_DownSWSt);
		UINM_PADS_L_DownSWStVD = std::move(_x.UINM_PADS_L_DownSWStVD);
		UINM_PADS_L_leftSWSt = std::move(_x.UINM_PADS_L_leftSWSt);
		UINM_PADS_L_LeftSWStVD = std::move(_x.UINM_PADS_L_LeftSWStVD);
		UINM_PADS_L_RightSWSt = std::move(_x.UINM_PADS_L_RightSWSt);
		UINM_PADS_L_RightSWStVD = std::move(_x.UINM_PADS_L_RightSWStVD);
		UINM_PADS_L_UDRollerRotatedDir = std::move(_x.UINM_PADS_L_UDRollerRotatedDir);
		UINM_PADS_L_UDRollerRSt = std::move(_x.UINM_PADS_L_UDRollerRSt);
		UINM_PADS_L_UDRollerVD = std::move(_x.UINM_PADS_L_UDRollerVD);
		UINM_PADS_L_LRRollerRotatedDir = std::move(_x.UINM_PADS_L_LRRollerRotatedDir);
		UINM_PADS_L_LRRollerRSt = std::move(_x.UINM_PADS_L_LRRollerRSt);
		UINM_PADS_L_LRRollerVD = std::move(_x.UINM_PADS_L_LRRollerVD);
		UINM_PADS_R_UpSWSt = std::move(_x.UINM_PADS_R_UpSWSt);
		UINM_PADS_R_UpSWStVD = std::move(_x.UINM_PADS_R_UpSWStVD);
		UINM_PADS_R_DownSWSt = std::move(_x.UINM_PADS_R_DownSWSt);
		UINM_PADS_R_DownSWStVD = std::move(_x.UINM_PADS_R_DownSWStVD);
		UINM_PADS_R_leftSWSt = std::move(_x.UINM_PADS_R_leftSWSt);
		UINM_PADS_R_LeftSWStVD = std::move(_x.UINM_PADS_R_LeftSWStVD);
		UINM_PADS_R_RightSWSt = std::move(_x.UINM_PADS_R_RightSWSt);
		UINM_PADS_R_RightSWStVD = std::move(_x.UINM_PADS_R_RightSWStVD);
		UINM_PADS_R_UDRollerRotatedDir = std::move(_x.UINM_PADS_R_UDRollerRotatedDir);
		UINM_PADS_R_UDRollerRSt = std::move(_x.UINM_PADS_R_UDRollerRSt);
		UINM_PADS_R_UDRollerVD = std::move(_x.UINM_PADS_R_UDRollerVD);
		UINM_PADS_R_LRRollerRotatedDir = std::move(_x.UINM_PADS_R_LRRollerRotatedDir);
		UINM_PADS_R_LRRollerRSt = std::move(_x.UINM_PADS_R_LRRollerRSt);
		UINM_PADS_R_LRRollerVD = std::move(_x.UINM_PADS_R_LRRollerVD);
	}
	BDCUINM5& operator=(const BDCUINM5 &_x){
		UINM_PADS_1_CRC = _x.UINM_PADS_1_CRC;
		UINM_PADS_1_Counter = _x.UINM_PADS_1_Counter;
		UINM_PADS_ResponseErr = _x.UINM_PADS_ResponseErr;
		UINM_PADS_IDC_ViewSWSt = _x.UINM_PADS_IDC_ViewSWSt;
		UINM_PADS_IDC_ViewSWVD = _x.UINM_PADS_IDC_ViewSWVD;
		UINM_PADS_IDC_ViewSWStuckSt = _x.UINM_PADS_IDC_ViewSWStuckSt;
		UINM_PADS_IDC_VrSWSt = _x.UINM_PADS_IDC_VrSWSt;
		UINM_PADS_IDC_VrSWStVD = _x.UINM_PADS_IDC_VrSWStVD;
		UINM_PADS_IDC_VrSWStuckSt = _x.UINM_PADS_IDC_VrSWStuckSt;
		UINM_PADS_IDC_PhoneSWSt = _x.UINM_PADS_IDC_PhoneSWSt;
		UINM_PADS_IDC_PhoneSWStVD = _x.UINM_PADS_IDC_PhoneSWStVD;
		UINM_PADS_IDC_PhoneStuckSt = _x.UINM_PADS_IDC_PhoneStuckSt;
		UINM_PADS_CustomSWSt = _x.UINM_PADS_CustomSWSt;
		UINM_PADS_CustomSWStVD = _x.UINM_PADS_CustomSWStVD;
		UINM_PADS_CustomSWstuck = _x.UINM_PADS_CustomSWstuck;
		UINM_PADS_VolRollerRotatedDir = _x.UINM_PADS_VolRollerRotatedDir;
		UINM_PADS_IDC_SkipIncSWSt = _x.UINM_PADS_IDC_SkipIncSWSt;
		UINM_PADS_IDC_SkipIncSWStVD = _x.UINM_PADS_IDC_SkipIncSWStVD;
		UINM_PADS_VolRollerSt = _x.UINM_PADS_VolRollerSt;
		UINM_PADS_IDC_SkipIncSWStuckSt = _x.UINM_PADS_IDC_SkipIncSWStuckSt;
		UINM_PADS_IDC_SkipDecSWSt = _x.UINM_PADS_IDC_SkipDecSWSt;
		UINM_PADS_IDC_SkipDecSWStVD = _x.UINM_PADS_IDC_SkipDecSWStVD;
		UINM_PADS_IDC_SkipDecSWStuckSt = _x.UINM_PADS_IDC_SkipDecSWStuckSt;
		UINM_PADS_IDC_PlaySWSt = _x.UINM_PADS_IDC_PlaySWSt;
		UINM_PADS_IDC_PlaySWStVD = _x.UINM_PADS_IDC_PlaySWStVD;
		UINM_PADS_IDC_PlaySWStuckSt = _x.UINM_PADS_IDC_PlaySWStuckSt;
		UINM_PADS_CruSetSpeedRollerRotatedDir = _x.UINM_PADS_CruSetSpeedRollerRotatedDir;
		UINM_PADS_FolDistIncSWSt = _x.UINM_PADS_FolDistIncSWSt;
		UINM_PADS_CruSetSpeedRollerSt = _x.UINM_PADS_CruSetSpeedRollerSt;
		UINM_PADS_FolDistIncSWStVD = _x.UINM_PADS_FolDistIncSWStVD;
		UINM_PADS_FolDistIncSWStuckSt = _x.UINM_PADS_FolDistIncSWStuckSt;
		UINM_PADS_FolDistDecSWSt = _x.UINM_PADS_FolDistDecSWSt;
		UINM_PADS_FolDistDecSWStVD = _x.UINM_PADS_FolDistDecSWStVD;
		UINM_PADS_FolDistDecSWStuckSt = _x.UINM_PADS_FolDistDecSWStuckSt;
		UINM_PADS_OKSWSt = _x.UINM_PADS_OKSWSt;
		UINM_PADS_OKSWStVD = _x.UINM_PADS_OKSWStVD;
		UINM_PADS_OKSWStuckSt = _x.UINM_PADS_OKSWStuckSt;
		UINM_PADS_VolRollerVD = _x.UINM_PADS_VolRollerVD;
		UINM_PADS_CruSetSpeedRollerVD = _x.UINM_PADS_CruSetSpeedRollerVD;
		UINM_PADS_IDC_ModeSWSt = _x.UINM_PADS_IDC_ModeSWSt;
		UINM_PADS_IDC_ModeSWStVD = _x.UINM_PADS_IDC_ModeSWStVD;
		UINM_PADS_IDC_ModeSWStuckSt = _x.UINM_PADS_IDC_ModeSWStuckSt;
		UINM_PADS_IDC_VolIncSWSt = _x.UINM_PADS_IDC_VolIncSWSt;
		UINM_PADS_IDC_VolIncSWStVD = _x.UINM_PADS_IDC_VolIncSWStVD;
		UINM_PADS_IDC_VolIncSWStuckSt = _x.UINM_PADS_IDC_VolIncSWStuckSt;
		UINM_PADS_IDC_VolDecSWSt = _x.UINM_PADS_IDC_VolDecSWSt;
		UINM_PADS_IDC_VolDecSWStVD = _x.UINM_PADS_IDC_VolDecSWStVD;
		UINM_PADS_IDC_VolDecSWStuckSt = _x.UINM_PADS_IDC_VolDecSWStuckSt;
		UINM_PADS_ICM_UPSWSt = _x.UINM_PADS_ICM_UPSWSt;
		UINM_PADS_ICM_UPSWStVD = _x.UINM_PADS_ICM_UPSWStVD;
		UINM_PADS_ICM_UPSWStuckSt = _x.UINM_PADS_ICM_UPSWStuckSt;
		UINM_PADS_ICM_DownSWSt = _x.UINM_PADS_ICM_DownSWSt;
		UINM_PADS_ICM_DownSWStVD = _x.UINM_PADS_ICM_DownSWStVD;
		UINM_PADS_ICM_DownSWStuckSt = _x.UINM_PADS_ICM_DownSWStuckSt;
		UINM_PADS_CruSWSt = _x.UINM_PADS_CruSWSt;
		UINM_PADS_CruSWStVD = _x.UINM_PADS_CruSWStVD;
		UINM_PADS_CruSWStuckSt = _x.UINM_PADS_CruSWStuckSt;
		UINM_PADS_CruSpeedDecSWSt = _x.UINM_PADS_CruSpeedDecSWSt;
		UINM_PADS_CruSpeedDecSWStVD = _x.UINM_PADS_CruSpeedDecSWStVD;
		UINM_PADS_CruSpeedDecSWStuckSt = _x.UINM_PADS_CruSpeedDecSWStuckSt;
		UINM_PADS_CruResumeSpeedIncSWSt = _x.UINM_PADS_CruResumeSpeedIncSWSt;
		UINM_PADS_CruResumeSpeedIncSWStVD = _x.UINM_PADS_CruResumeSpeedIncSWStVD;
		UINM_PADS_CruResumeSpeedIncSWStuckSt = _x.UINM_PADS_CruResumeSpeedIncSWStuckSt;
		UINM_PADS_CruTauGapSWSt = _x.UINM_PADS_CruTauGapSWSt;
		UINM_PADS_CruTauGapSWStVD = _x.UINM_PADS_CruTauGapSWStVD;
		UINM_PADS_CruTauGapSWStcukSt = _x.UINM_PADS_CruTauGapSWStcukSt;
		UINM_PADS_CruTJAICASWSt = _x.UINM_PADS_CruTJAICASWSt;
		UINM_PADS_CruTJAICASWStVD = _x.UINM_PADS_CruTJAICASWStVD;
		UINM_PADS_CruTJAICASWStuckSt = _x.UINM_PADS_CruTJAICASWStuckSt;
		UINM_PADS_IpadelSWSt = _x.UINM_PADS_IpadelSWSt;
		UINM_PADS_IpadelSWStVD = _x.UINM_PADS_IpadelSWStVD;
		UINM_PADS_IpadelSWStuckSt = _x.UINM_PADS_IpadelSWStuckSt;
		UINM_PADS_Custom2SWSt = _x.UINM_PADS_Custom2SWSt;
		UINM_PADS_Custom2SWStVD = _x.UINM_PADS_Custom2SWStVD;
		UINM_PADS_Custom2SWStuckSt = _x.UINM_PADS_Custom2SWStuckSt;
		UINM_PADS_ACCSWSt = _x.UINM_PADS_ACCSWSt;
		UINM_PADS_VoltageFaultSt = _x.UINM_PADS_VoltageFaultSt;
		UINM_PADS_L_UpSWSt = _x.UINM_PADS_L_UpSWSt;
		UINM_PADS_L_UpSWStVD = _x.UINM_PADS_L_UpSWStVD;
		UINM_PADS_L_DownSWSt = _x.UINM_PADS_L_DownSWSt;
		UINM_PADS_L_DownSWStVD = _x.UINM_PADS_L_DownSWStVD;
		UINM_PADS_L_leftSWSt = _x.UINM_PADS_L_leftSWSt;
		UINM_PADS_L_LeftSWStVD = _x.UINM_PADS_L_LeftSWStVD;
		UINM_PADS_L_RightSWSt = _x.UINM_PADS_L_RightSWSt;
		UINM_PADS_L_RightSWStVD = _x.UINM_PADS_L_RightSWStVD;
		UINM_PADS_L_UDRollerRotatedDir = _x.UINM_PADS_L_UDRollerRotatedDir;
		UINM_PADS_L_UDRollerRSt = _x.UINM_PADS_L_UDRollerRSt;
		UINM_PADS_L_UDRollerVD = _x.UINM_PADS_L_UDRollerVD;
		UINM_PADS_L_LRRollerRotatedDir = _x.UINM_PADS_L_LRRollerRotatedDir;
		UINM_PADS_L_LRRollerRSt = _x.UINM_PADS_L_LRRollerRSt;
		UINM_PADS_L_LRRollerVD = _x.UINM_PADS_L_LRRollerVD;
		UINM_PADS_R_UpSWSt = _x.UINM_PADS_R_UpSWSt;
		UINM_PADS_R_UpSWStVD = _x.UINM_PADS_R_UpSWStVD;
		UINM_PADS_R_DownSWSt = _x.UINM_PADS_R_DownSWSt;
		UINM_PADS_R_DownSWStVD = _x.UINM_PADS_R_DownSWStVD;
		UINM_PADS_R_leftSWSt = _x.UINM_PADS_R_leftSWSt;
		UINM_PADS_R_LeftSWStVD = _x.UINM_PADS_R_LeftSWStVD;
		UINM_PADS_R_RightSWSt = _x.UINM_PADS_R_RightSWSt;
		UINM_PADS_R_RightSWStVD = _x.UINM_PADS_R_RightSWStVD;
		UINM_PADS_R_UDRollerRotatedDir = _x.UINM_PADS_R_UDRollerRotatedDir;
		UINM_PADS_R_UDRollerRSt = _x.UINM_PADS_R_UDRollerRSt;
		UINM_PADS_R_UDRollerVD = _x.UINM_PADS_R_UDRollerVD;
		UINM_PADS_R_LRRollerRotatedDir = _x.UINM_PADS_R_LRRollerRotatedDir;
		UINM_PADS_R_LRRollerRSt = _x.UINM_PADS_R_LRRollerRSt;
		UINM_PADS_R_LRRollerVD = _x.UINM_PADS_R_LRRollerVD;
		return *this;
	}
	BDCUINM5& operator=(BDCUINM5 &&_x){
		UINM_PADS_1_CRC = std::move(_x.UINM_PADS_1_CRC);
		UINM_PADS_1_Counter = std::move(_x.UINM_PADS_1_Counter);
		UINM_PADS_ResponseErr = std::move(_x.UINM_PADS_ResponseErr);
		UINM_PADS_IDC_ViewSWSt = std::move(_x.UINM_PADS_IDC_ViewSWSt);
		UINM_PADS_IDC_ViewSWVD = std::move(_x.UINM_PADS_IDC_ViewSWVD);
		UINM_PADS_IDC_ViewSWStuckSt = std::move(_x.UINM_PADS_IDC_ViewSWStuckSt);
		UINM_PADS_IDC_VrSWSt = std::move(_x.UINM_PADS_IDC_VrSWSt);
		UINM_PADS_IDC_VrSWStVD = std::move(_x.UINM_PADS_IDC_VrSWStVD);
		UINM_PADS_IDC_VrSWStuckSt = std::move(_x.UINM_PADS_IDC_VrSWStuckSt);
		UINM_PADS_IDC_PhoneSWSt = std::move(_x.UINM_PADS_IDC_PhoneSWSt);
		UINM_PADS_IDC_PhoneSWStVD = std::move(_x.UINM_PADS_IDC_PhoneSWStVD);
		UINM_PADS_IDC_PhoneStuckSt = std::move(_x.UINM_PADS_IDC_PhoneStuckSt);
		UINM_PADS_CustomSWSt = std::move(_x.UINM_PADS_CustomSWSt);
		UINM_PADS_CustomSWStVD = std::move(_x.UINM_PADS_CustomSWStVD);
		UINM_PADS_CustomSWstuck = std::move(_x.UINM_PADS_CustomSWstuck);
		UINM_PADS_VolRollerRotatedDir = std::move(_x.UINM_PADS_VolRollerRotatedDir);
		UINM_PADS_IDC_SkipIncSWSt = std::move(_x.UINM_PADS_IDC_SkipIncSWSt);
		UINM_PADS_IDC_SkipIncSWStVD = std::move(_x.UINM_PADS_IDC_SkipIncSWStVD);
		UINM_PADS_VolRollerSt = std::move(_x.UINM_PADS_VolRollerSt);
		UINM_PADS_IDC_SkipIncSWStuckSt = std::move(_x.UINM_PADS_IDC_SkipIncSWStuckSt);
		UINM_PADS_IDC_SkipDecSWSt = std::move(_x.UINM_PADS_IDC_SkipDecSWSt);
		UINM_PADS_IDC_SkipDecSWStVD = std::move(_x.UINM_PADS_IDC_SkipDecSWStVD);
		UINM_PADS_IDC_SkipDecSWStuckSt = std::move(_x.UINM_PADS_IDC_SkipDecSWStuckSt);
		UINM_PADS_IDC_PlaySWSt = std::move(_x.UINM_PADS_IDC_PlaySWSt);
		UINM_PADS_IDC_PlaySWStVD = std::move(_x.UINM_PADS_IDC_PlaySWStVD);
		UINM_PADS_IDC_PlaySWStuckSt = std::move(_x.UINM_PADS_IDC_PlaySWStuckSt);
		UINM_PADS_CruSetSpeedRollerRotatedDir = std::move(_x.UINM_PADS_CruSetSpeedRollerRotatedDir);
		UINM_PADS_FolDistIncSWSt = std::move(_x.UINM_PADS_FolDistIncSWSt);
		UINM_PADS_CruSetSpeedRollerSt = std::move(_x.UINM_PADS_CruSetSpeedRollerSt);
		UINM_PADS_FolDistIncSWStVD = std::move(_x.UINM_PADS_FolDistIncSWStVD);
		UINM_PADS_FolDistIncSWStuckSt = std::move(_x.UINM_PADS_FolDistIncSWStuckSt);
		UINM_PADS_FolDistDecSWSt = std::move(_x.UINM_PADS_FolDistDecSWSt);
		UINM_PADS_FolDistDecSWStVD = std::move(_x.UINM_PADS_FolDistDecSWStVD);
		UINM_PADS_FolDistDecSWStuckSt = std::move(_x.UINM_PADS_FolDistDecSWStuckSt);
		UINM_PADS_OKSWSt = std::move(_x.UINM_PADS_OKSWSt);
		UINM_PADS_OKSWStVD = std::move(_x.UINM_PADS_OKSWStVD);
		UINM_PADS_OKSWStuckSt = std::move(_x.UINM_PADS_OKSWStuckSt);
		UINM_PADS_VolRollerVD = std::move(_x.UINM_PADS_VolRollerVD);
		UINM_PADS_CruSetSpeedRollerVD = std::move(_x.UINM_PADS_CruSetSpeedRollerVD);
		UINM_PADS_IDC_ModeSWSt = std::move(_x.UINM_PADS_IDC_ModeSWSt);
		UINM_PADS_IDC_ModeSWStVD = std::move(_x.UINM_PADS_IDC_ModeSWStVD);
		UINM_PADS_IDC_ModeSWStuckSt = std::move(_x.UINM_PADS_IDC_ModeSWStuckSt);
		UINM_PADS_IDC_VolIncSWSt = std::move(_x.UINM_PADS_IDC_VolIncSWSt);
		UINM_PADS_IDC_VolIncSWStVD = std::move(_x.UINM_PADS_IDC_VolIncSWStVD);
		UINM_PADS_IDC_VolIncSWStuckSt = std::move(_x.UINM_PADS_IDC_VolIncSWStuckSt);
		UINM_PADS_IDC_VolDecSWSt = std::move(_x.UINM_PADS_IDC_VolDecSWSt);
		UINM_PADS_IDC_VolDecSWStVD = std::move(_x.UINM_PADS_IDC_VolDecSWStVD);
		UINM_PADS_IDC_VolDecSWStuckSt = std::move(_x.UINM_PADS_IDC_VolDecSWStuckSt);
		UINM_PADS_ICM_UPSWSt = std::move(_x.UINM_PADS_ICM_UPSWSt);
		UINM_PADS_ICM_UPSWStVD = std::move(_x.UINM_PADS_ICM_UPSWStVD);
		UINM_PADS_ICM_UPSWStuckSt = std::move(_x.UINM_PADS_ICM_UPSWStuckSt);
		UINM_PADS_ICM_DownSWSt = std::move(_x.UINM_PADS_ICM_DownSWSt);
		UINM_PADS_ICM_DownSWStVD = std::move(_x.UINM_PADS_ICM_DownSWStVD);
		UINM_PADS_ICM_DownSWStuckSt = std::move(_x.UINM_PADS_ICM_DownSWStuckSt);
		UINM_PADS_CruSWSt = std::move(_x.UINM_PADS_CruSWSt);
		UINM_PADS_CruSWStVD = std::move(_x.UINM_PADS_CruSWStVD);
		UINM_PADS_CruSWStuckSt = std::move(_x.UINM_PADS_CruSWStuckSt);
		UINM_PADS_CruSpeedDecSWSt = std::move(_x.UINM_PADS_CruSpeedDecSWSt);
		UINM_PADS_CruSpeedDecSWStVD = std::move(_x.UINM_PADS_CruSpeedDecSWStVD);
		UINM_PADS_CruSpeedDecSWStuckSt = std::move(_x.UINM_PADS_CruSpeedDecSWStuckSt);
		UINM_PADS_CruResumeSpeedIncSWSt = std::move(_x.UINM_PADS_CruResumeSpeedIncSWSt);
		UINM_PADS_CruResumeSpeedIncSWStVD = std::move(_x.UINM_PADS_CruResumeSpeedIncSWStVD);
		UINM_PADS_CruResumeSpeedIncSWStuckSt = std::move(_x.UINM_PADS_CruResumeSpeedIncSWStuckSt);
		UINM_PADS_CruTauGapSWSt = std::move(_x.UINM_PADS_CruTauGapSWSt);
		UINM_PADS_CruTauGapSWStVD = std::move(_x.UINM_PADS_CruTauGapSWStVD);
		UINM_PADS_CruTauGapSWStcukSt = std::move(_x.UINM_PADS_CruTauGapSWStcukSt);
		UINM_PADS_CruTJAICASWSt = std::move(_x.UINM_PADS_CruTJAICASWSt);
		UINM_PADS_CruTJAICASWStVD = std::move(_x.UINM_PADS_CruTJAICASWStVD);
		UINM_PADS_CruTJAICASWStuckSt = std::move(_x.UINM_PADS_CruTJAICASWStuckSt);
		UINM_PADS_IpadelSWSt = std::move(_x.UINM_PADS_IpadelSWSt);
		UINM_PADS_IpadelSWStVD = std::move(_x.UINM_PADS_IpadelSWStVD);
		UINM_PADS_IpadelSWStuckSt = std::move(_x.UINM_PADS_IpadelSWStuckSt);
		UINM_PADS_Custom2SWSt = std::move(_x.UINM_PADS_Custom2SWSt);
		UINM_PADS_Custom2SWStVD = std::move(_x.UINM_PADS_Custom2SWStVD);
		UINM_PADS_Custom2SWStuckSt = std::move(_x.UINM_PADS_Custom2SWStuckSt);
		UINM_PADS_ACCSWSt = std::move(_x.UINM_PADS_ACCSWSt);
		UINM_PADS_VoltageFaultSt = std::move(_x.UINM_PADS_VoltageFaultSt);
		UINM_PADS_L_UpSWSt = std::move(_x.UINM_PADS_L_UpSWSt);
		UINM_PADS_L_UpSWStVD = std::move(_x.UINM_PADS_L_UpSWStVD);
		UINM_PADS_L_DownSWSt = std::move(_x.UINM_PADS_L_DownSWSt);
		UINM_PADS_L_DownSWStVD = std::move(_x.UINM_PADS_L_DownSWStVD);
		UINM_PADS_L_leftSWSt = std::move(_x.UINM_PADS_L_leftSWSt);
		UINM_PADS_L_LeftSWStVD = std::move(_x.UINM_PADS_L_LeftSWStVD);
		UINM_PADS_L_RightSWSt = std::move(_x.UINM_PADS_L_RightSWSt);
		UINM_PADS_L_RightSWStVD = std::move(_x.UINM_PADS_L_RightSWStVD);
		UINM_PADS_L_UDRollerRotatedDir = std::move(_x.UINM_PADS_L_UDRollerRotatedDir);
		UINM_PADS_L_UDRollerRSt = std::move(_x.UINM_PADS_L_UDRollerRSt);
		UINM_PADS_L_UDRollerVD = std::move(_x.UINM_PADS_L_UDRollerVD);
		UINM_PADS_L_LRRollerRotatedDir = std::move(_x.UINM_PADS_L_LRRollerRotatedDir);
		UINM_PADS_L_LRRollerRSt = std::move(_x.UINM_PADS_L_LRRollerRSt);
		UINM_PADS_L_LRRollerVD = std::move(_x.UINM_PADS_L_LRRollerVD);
		UINM_PADS_R_UpSWSt = std::move(_x.UINM_PADS_R_UpSWSt);
		UINM_PADS_R_UpSWStVD = std::move(_x.UINM_PADS_R_UpSWStVD);
		UINM_PADS_R_DownSWSt = std::move(_x.UINM_PADS_R_DownSWSt);
		UINM_PADS_R_DownSWStVD = std::move(_x.UINM_PADS_R_DownSWStVD);
		UINM_PADS_R_leftSWSt = std::move(_x.UINM_PADS_R_leftSWSt);
		UINM_PADS_R_LeftSWStVD = std::move(_x.UINM_PADS_R_LeftSWStVD);
		UINM_PADS_R_RightSWSt = std::move(_x.UINM_PADS_R_RightSWSt);
		UINM_PADS_R_RightSWStVD = std::move(_x.UINM_PADS_R_RightSWStVD);
		UINM_PADS_R_UDRollerRotatedDir = std::move(_x.UINM_PADS_R_UDRollerRotatedDir);
		UINM_PADS_R_UDRollerRSt = std::move(_x.UINM_PADS_R_UDRollerRSt);
		UINM_PADS_R_UDRollerVD = std::move(_x.UINM_PADS_R_UDRollerVD);
		UINM_PADS_R_LRRollerRotatedDir = std::move(_x.UINM_PADS_R_LRRollerRotatedDir);
		UINM_PADS_R_LRRollerRSt = std::move(_x.UINM_PADS_R_LRRollerRSt);
		UINM_PADS_R_LRRollerVD = std::move(_x.UINM_PADS_R_LRRollerVD);
		return *this;
	}
*/

	using IsEnumerableTag = void;
	template<typename F>
	void enumerate(F& fun) {
		fun(UINM_PADS_1_CRC);
		fun(UINM_PADS_1_Counter);
		fun(UINM_PADS_ResponseErr);
		fun(UINM_PADS_IDC_ViewSWSt);
		fun(UINM_PADS_IDC_ViewSWVD);
		fun(UINM_PADS_IDC_ViewSWStuckSt);
		fun(UINM_PADS_IDC_VrSWSt);
		fun(UINM_PADS_IDC_VrSWStVD);
		fun(UINM_PADS_IDC_VrSWStuckSt);
		fun(UINM_PADS_IDC_PhoneSWSt);
		fun(UINM_PADS_IDC_PhoneSWStVD);
		fun(UINM_PADS_IDC_PhoneStuckSt);
		fun(UINM_PADS_CustomSWSt);
		fun(UINM_PADS_CustomSWStVD);
		fun(UINM_PADS_CustomSWstuck);
		fun(UINM_PADS_VolRollerRotatedDir);
		fun(UINM_PADS_IDC_SkipIncSWSt);
		fun(UINM_PADS_IDC_SkipIncSWStVD);
		fun(UINM_PADS_VolRollerSt);
		fun(UINM_PADS_IDC_SkipIncSWStuckSt);
		fun(UINM_PADS_IDC_SkipDecSWSt);
		fun(UINM_PADS_IDC_SkipDecSWStVD);
		fun(UINM_PADS_IDC_SkipDecSWStuckSt);
		fun(UINM_PADS_IDC_PlaySWSt);
		fun(UINM_PADS_IDC_PlaySWStVD);
		fun(UINM_PADS_IDC_PlaySWStuckSt);
		fun(UINM_PADS_CruSetSpeedRollerRotatedDir);
		fun(UINM_PADS_FolDistIncSWSt);
		fun(UINM_PADS_CruSetSpeedRollerSt);
		fun(UINM_PADS_FolDistIncSWStVD);
		fun(UINM_PADS_FolDistIncSWStuckSt);
		fun(UINM_PADS_FolDistDecSWSt);
		fun(UINM_PADS_FolDistDecSWStVD);
		fun(UINM_PADS_FolDistDecSWStuckSt);
		fun(UINM_PADS_OKSWSt);
		fun(UINM_PADS_OKSWStVD);
		fun(UINM_PADS_OKSWStuckSt);
		fun(UINM_PADS_VolRollerVD);
		fun(UINM_PADS_CruSetSpeedRollerVD);
		fun(UINM_PADS_IDC_ModeSWSt);
		fun(UINM_PADS_IDC_ModeSWStVD);
		fun(UINM_PADS_IDC_ModeSWStuckSt);
		fun(UINM_PADS_IDC_VolIncSWSt);
		fun(UINM_PADS_IDC_VolIncSWStVD);
		fun(UINM_PADS_IDC_VolIncSWStuckSt);
		fun(UINM_PADS_IDC_VolDecSWSt);
		fun(UINM_PADS_IDC_VolDecSWStVD);
		fun(UINM_PADS_IDC_VolDecSWStuckSt);
		fun(UINM_PADS_ICM_UPSWSt);
		fun(UINM_PADS_ICM_UPSWStVD);
		fun(UINM_PADS_ICM_UPSWStuckSt);
		fun(UINM_PADS_ICM_DownSWSt);
		fun(UINM_PADS_ICM_DownSWStVD);
		fun(UINM_PADS_ICM_DownSWStuckSt);
		fun(UINM_PADS_CruSWSt);
		fun(UINM_PADS_CruSWStVD);
		fun(UINM_PADS_CruSWStuckSt);
		fun(UINM_PADS_CruSpeedDecSWSt);
		fun(UINM_PADS_CruSpeedDecSWStVD);
		fun(UINM_PADS_CruSpeedDecSWStuckSt);
		fun(UINM_PADS_CruResumeSpeedIncSWSt);
		fun(UINM_PADS_CruResumeSpeedIncSWStVD);
		fun(UINM_PADS_CruResumeSpeedIncSWStuckSt);
		fun(UINM_PADS_CruTauGapSWSt);
		fun(UINM_PADS_CruTauGapSWStVD);
		fun(UINM_PADS_CruTauGapSWStcukSt);
		fun(UINM_PADS_CruTJAICASWSt);
		fun(UINM_PADS_CruTJAICASWStVD);
		fun(UINM_PADS_CruTJAICASWStuckSt);
		fun(UINM_PADS_IpadelSWSt);
		fun(UINM_PADS_IpadelSWStVD);
		fun(UINM_PADS_IpadelSWStuckSt);
		fun(UINM_PADS_Custom2SWSt);
		fun(UINM_PADS_Custom2SWStVD);
		fun(UINM_PADS_Custom2SWStuckSt);
		fun(UINM_PADS_ACCSWSt);
		fun(UINM_PADS_VoltageFaultSt);
		fun(UINM_PADS_L_UpSWSt);
		fun(UINM_PADS_L_UpSWStVD);
		fun(UINM_PADS_L_DownSWSt);
		fun(UINM_PADS_L_DownSWStVD);
		fun(UINM_PADS_L_leftSWSt);
		fun(UINM_PADS_L_LeftSWStVD);
		fun(UINM_PADS_L_RightSWSt);
		fun(UINM_PADS_L_RightSWStVD);
		fun(UINM_PADS_L_UDRollerRotatedDir);
		fun(UINM_PADS_L_UDRollerRSt);
		fun(UINM_PADS_L_UDRollerVD);
		fun(UINM_PADS_L_LRRollerRotatedDir);
		fun(UINM_PADS_L_LRRollerRSt);
		fun(UINM_PADS_L_LRRollerVD);
		fun(UINM_PADS_R_UpSWSt);
		fun(UINM_PADS_R_UpSWStVD);
		fun(UINM_PADS_R_DownSWSt);
		fun(UINM_PADS_R_DownSWStVD);
		fun(UINM_PADS_R_leftSWSt);
		fun(UINM_PADS_R_LeftSWStVD);
		fun(UINM_PADS_R_RightSWSt);
		fun(UINM_PADS_R_RightSWStVD);
		fun(UINM_PADS_R_UDRollerRotatedDir);
		fun(UINM_PADS_R_UDRollerRSt);
		fun(UINM_PADS_R_UDRollerVD);
		fun(UINM_PADS_R_LRRollerRotatedDir);
		fun(UINM_PADS_R_LRRollerRSt);
		fun(UINM_PADS_R_LRRollerVD);
	}

	template<typename F>
	void GetSize(F& fun) const{
		fun(UINM_PADS_1_CRC);
		fun(UINM_PADS_1_Counter);
		fun(UINM_PADS_ResponseErr);
		fun(UINM_PADS_IDC_ViewSWSt);
		fun(UINM_PADS_IDC_ViewSWVD);
		fun(UINM_PADS_IDC_ViewSWStuckSt);
		fun(UINM_PADS_IDC_VrSWSt);
		fun(UINM_PADS_IDC_VrSWStVD);
		fun(UINM_PADS_IDC_VrSWStuckSt);
		fun(UINM_PADS_IDC_PhoneSWSt);
		fun(UINM_PADS_IDC_PhoneSWStVD);
		fun(UINM_PADS_IDC_PhoneStuckSt);
		fun(UINM_PADS_CustomSWSt);
		fun(UINM_PADS_CustomSWStVD);
		fun(UINM_PADS_CustomSWstuck);
		fun(UINM_PADS_VolRollerRotatedDir);
		fun(UINM_PADS_IDC_SkipIncSWSt);
		fun(UINM_PADS_IDC_SkipIncSWStVD);
		fun(UINM_PADS_VolRollerSt);
		fun(UINM_PADS_IDC_SkipIncSWStuckSt);
		fun(UINM_PADS_IDC_SkipDecSWSt);
		fun(UINM_PADS_IDC_SkipDecSWStVD);
		fun(UINM_PADS_IDC_SkipDecSWStuckSt);
		fun(UINM_PADS_IDC_PlaySWSt);
		fun(UINM_PADS_IDC_PlaySWStVD);
		fun(UINM_PADS_IDC_PlaySWStuckSt);
		fun(UINM_PADS_CruSetSpeedRollerRotatedDir);
		fun(UINM_PADS_FolDistIncSWSt);
		fun(UINM_PADS_CruSetSpeedRollerSt);
		fun(UINM_PADS_FolDistIncSWStVD);
		fun(UINM_PADS_FolDistIncSWStuckSt);
		fun(UINM_PADS_FolDistDecSWSt);
		fun(UINM_PADS_FolDistDecSWStVD);
		fun(UINM_PADS_FolDistDecSWStuckSt);
		fun(UINM_PADS_OKSWSt);
		fun(UINM_PADS_OKSWStVD);
		fun(UINM_PADS_OKSWStuckSt);
		fun(UINM_PADS_VolRollerVD);
		fun(UINM_PADS_CruSetSpeedRollerVD);
		fun(UINM_PADS_IDC_ModeSWSt);
		fun(UINM_PADS_IDC_ModeSWStVD);
		fun(UINM_PADS_IDC_ModeSWStuckSt);
		fun(UINM_PADS_IDC_VolIncSWSt);
		fun(UINM_PADS_IDC_VolIncSWStVD);
		fun(UINM_PADS_IDC_VolIncSWStuckSt);
		fun(UINM_PADS_IDC_VolDecSWSt);
		fun(UINM_PADS_IDC_VolDecSWStVD);
		fun(UINM_PADS_IDC_VolDecSWStuckSt);
		fun(UINM_PADS_ICM_UPSWSt);
		fun(UINM_PADS_ICM_UPSWStVD);
		fun(UINM_PADS_ICM_UPSWStuckSt);
		fun(UINM_PADS_ICM_DownSWSt);
		fun(UINM_PADS_ICM_DownSWStVD);
		fun(UINM_PADS_ICM_DownSWStuckSt);
		fun(UINM_PADS_CruSWSt);
		fun(UINM_PADS_CruSWStVD);
		fun(UINM_PADS_CruSWStuckSt);
		fun(UINM_PADS_CruSpeedDecSWSt);
		fun(UINM_PADS_CruSpeedDecSWStVD);
		fun(UINM_PADS_CruSpeedDecSWStuckSt);
		fun(UINM_PADS_CruResumeSpeedIncSWSt);
		fun(UINM_PADS_CruResumeSpeedIncSWStVD);
		fun(UINM_PADS_CruResumeSpeedIncSWStuckSt);
		fun(UINM_PADS_CruTauGapSWSt);
		fun(UINM_PADS_CruTauGapSWStVD);
		fun(UINM_PADS_CruTauGapSWStcukSt);
		fun(UINM_PADS_CruTJAICASWSt);
		fun(UINM_PADS_CruTJAICASWStVD);
		fun(UINM_PADS_CruTJAICASWStuckSt);
		fun(UINM_PADS_IpadelSWSt);
		fun(UINM_PADS_IpadelSWStVD);
		fun(UINM_PADS_IpadelSWStuckSt);
		fun(UINM_PADS_Custom2SWSt);
		fun(UINM_PADS_Custom2SWStVD);
		fun(UINM_PADS_Custom2SWStuckSt);
		fun(UINM_PADS_ACCSWSt);
		fun(UINM_PADS_VoltageFaultSt);
		fun(UINM_PADS_L_UpSWSt);
		fun(UINM_PADS_L_UpSWStVD);
		fun(UINM_PADS_L_DownSWSt);
		fun(UINM_PADS_L_DownSWStVD);
		fun(UINM_PADS_L_leftSWSt);
		fun(UINM_PADS_L_LeftSWStVD);
		fun(UINM_PADS_L_RightSWSt);
		fun(UINM_PADS_L_RightSWStVD);
		fun(UINM_PADS_L_UDRollerRotatedDir);
		fun(UINM_PADS_L_UDRollerRSt);
		fun(UINM_PADS_L_UDRollerVD);
		fun(UINM_PADS_L_LRRollerRotatedDir);
		fun(UINM_PADS_L_LRRollerRSt);
		fun(UINM_PADS_L_LRRollerVD);
		fun(UINM_PADS_R_UpSWSt);
		fun(UINM_PADS_R_UpSWStVD);
		fun(UINM_PADS_R_DownSWSt);
		fun(UINM_PADS_R_DownSWStVD);
		fun(UINM_PADS_R_leftSWSt);
		fun(UINM_PADS_R_LeftSWStVD);
		fun(UINM_PADS_R_RightSWSt);
		fun(UINM_PADS_R_RightSWStVD);
		fun(UINM_PADS_R_UDRollerRotatedDir);
		fun(UINM_PADS_R_UDRollerRSt);
		fun(UINM_PADS_R_UDRollerVD);
		fun(UINM_PADS_R_LRRollerRotatedDir);
		fun(UINM_PADS_R_LRRollerRSt);
		fun(UINM_PADS_R_LRRollerVD);
	}
	template<typename F>
	void serialize(F& fun) const{
		fun << (UINM_PADS_1_CRC);
		fun << (UINM_PADS_1_Counter);
		fun << (UINM_PADS_ResponseErr);
		fun << (UINM_PADS_IDC_ViewSWSt);
		fun << (UINM_PADS_IDC_ViewSWVD);
		fun << (UINM_PADS_IDC_ViewSWStuckSt);
		fun << (UINM_PADS_IDC_VrSWSt);
		fun << (UINM_PADS_IDC_VrSWStVD);
		fun << (UINM_PADS_IDC_VrSWStuckSt);
		fun << (UINM_PADS_IDC_PhoneSWSt);
		fun << (UINM_PADS_IDC_PhoneSWStVD);
		fun << (UINM_PADS_IDC_PhoneStuckSt);
		fun << (UINM_PADS_CustomSWSt);
		fun << (UINM_PADS_CustomSWStVD);
		fun << (UINM_PADS_CustomSWstuck);
		fun << (UINM_PADS_VolRollerRotatedDir);
		fun << (UINM_PADS_IDC_SkipIncSWSt);
		fun << (UINM_PADS_IDC_SkipIncSWStVD);
		fun << (UINM_PADS_VolRollerSt);
		fun << (UINM_PADS_IDC_SkipIncSWStuckSt);
		fun << (UINM_PADS_IDC_SkipDecSWSt);
		fun << (UINM_PADS_IDC_SkipDecSWStVD);
		fun << (UINM_PADS_IDC_SkipDecSWStuckSt);
		fun << (UINM_PADS_IDC_PlaySWSt);
		fun << (UINM_PADS_IDC_PlaySWStVD);
		fun << (UINM_PADS_IDC_PlaySWStuckSt);
		fun << (UINM_PADS_CruSetSpeedRollerRotatedDir);
		fun << (UINM_PADS_FolDistIncSWSt);
		fun << (UINM_PADS_CruSetSpeedRollerSt);
		fun << (UINM_PADS_FolDistIncSWStVD);
		fun << (UINM_PADS_FolDistIncSWStuckSt);
		fun << (UINM_PADS_FolDistDecSWSt);
		fun << (UINM_PADS_FolDistDecSWStVD);
		fun << (UINM_PADS_FolDistDecSWStuckSt);
		fun << (UINM_PADS_OKSWSt);
		fun << (UINM_PADS_OKSWStVD);
		fun << (UINM_PADS_OKSWStuckSt);
		fun << (UINM_PADS_VolRollerVD);
		fun << (UINM_PADS_CruSetSpeedRollerVD);
		fun << (UINM_PADS_IDC_ModeSWSt);
		fun << (UINM_PADS_IDC_ModeSWStVD);
		fun << (UINM_PADS_IDC_ModeSWStuckSt);
		fun << (UINM_PADS_IDC_VolIncSWSt);
		fun << (UINM_PADS_IDC_VolIncSWStVD);
		fun << (UINM_PADS_IDC_VolIncSWStuckSt);
		fun << (UINM_PADS_IDC_VolDecSWSt);
		fun << (UINM_PADS_IDC_VolDecSWStVD);
		fun << (UINM_PADS_IDC_VolDecSWStuckSt);
		fun << (UINM_PADS_ICM_UPSWSt);
		fun << (UINM_PADS_ICM_UPSWStVD);
		fun << (UINM_PADS_ICM_UPSWStuckSt);
		fun << (UINM_PADS_ICM_DownSWSt);
		fun << (UINM_PADS_ICM_DownSWStVD);
		fun << (UINM_PADS_ICM_DownSWStuckSt);
		fun << (UINM_PADS_CruSWSt);
		fun << (UINM_PADS_CruSWStVD);
		fun << (UINM_PADS_CruSWStuckSt);
		fun << (UINM_PADS_CruSpeedDecSWSt);
		fun << (UINM_PADS_CruSpeedDecSWStVD);
		fun << (UINM_PADS_CruSpeedDecSWStuckSt);
		fun << (UINM_PADS_CruResumeSpeedIncSWSt);
		fun << (UINM_PADS_CruResumeSpeedIncSWStVD);
		fun << (UINM_PADS_CruResumeSpeedIncSWStuckSt);
		fun << (UINM_PADS_CruTauGapSWSt);
		fun << (UINM_PADS_CruTauGapSWStVD);
		fun << (UINM_PADS_CruTauGapSWStcukSt);
		fun << (UINM_PADS_CruTJAICASWSt);
		fun << (UINM_PADS_CruTJAICASWStVD);
		fun << (UINM_PADS_CruTJAICASWStuckSt);
		fun << (UINM_PADS_IpadelSWSt);
		fun << (UINM_PADS_IpadelSWStVD);
		fun << (UINM_PADS_IpadelSWStuckSt);
		fun << (UINM_PADS_Custom2SWSt);
		fun << (UINM_PADS_Custom2SWStVD);
		fun << (UINM_PADS_Custom2SWStuckSt);
		fun << (UINM_PADS_ACCSWSt);
		fun << (UINM_PADS_VoltageFaultSt);
		fun << (UINM_PADS_L_UpSWSt);
		fun << (UINM_PADS_L_UpSWStVD);
		fun << (UINM_PADS_L_DownSWSt);
		fun << (UINM_PADS_L_DownSWStVD);
		fun << (UINM_PADS_L_leftSWSt);
		fun << (UINM_PADS_L_LeftSWStVD);
		fun << (UINM_PADS_L_RightSWSt);
		fun << (UINM_PADS_L_RightSWStVD);
		fun << (UINM_PADS_L_UDRollerRotatedDir);
		fun << (UINM_PADS_L_UDRollerRSt);
		fun << (UINM_PADS_L_UDRollerVD);
		fun << (UINM_PADS_L_LRRollerRotatedDir);
		fun << (UINM_PADS_L_LRRollerRSt);
		fun << (UINM_PADS_L_LRRollerVD);
		fun << (UINM_PADS_R_UpSWSt);
		fun << (UINM_PADS_R_UpSWStVD);
		fun << (UINM_PADS_R_DownSWSt);
		fun << (UINM_PADS_R_DownSWStVD);
		fun << (UINM_PADS_R_leftSWSt);
		fun << (UINM_PADS_R_LeftSWStVD);
		fun << (UINM_PADS_R_RightSWSt);
		fun << (UINM_PADS_R_RightSWStVD);
		fun << (UINM_PADS_R_UDRollerRotatedDir);
		fun << (UINM_PADS_R_UDRollerRSt);
		fun << (UINM_PADS_R_UDRollerVD);
		fun << (UINM_PADS_R_LRRollerRotatedDir);
		fun << (UINM_PADS_R_LRRollerRSt);
		fun << (UINM_PADS_R_LRRollerVD);
	}
	template<typename F>
	void deserialize(F& fun){
		fun >> (UINM_PADS_1_CRC);
		fun >> (UINM_PADS_1_Counter);
		fun >> (UINM_PADS_ResponseErr);
		fun >> (UINM_PADS_IDC_ViewSWSt);
		fun >> (UINM_PADS_IDC_ViewSWVD);
		fun >> (UINM_PADS_IDC_ViewSWStuckSt);
		fun >> (UINM_PADS_IDC_VrSWSt);
		fun >> (UINM_PADS_IDC_VrSWStVD);
		fun >> (UINM_PADS_IDC_VrSWStuckSt);
		fun >> (UINM_PADS_IDC_PhoneSWSt);
		fun >> (UINM_PADS_IDC_PhoneSWStVD);
		fun >> (UINM_PADS_IDC_PhoneStuckSt);
		fun >> (UINM_PADS_CustomSWSt);
		fun >> (UINM_PADS_CustomSWStVD);
		fun >> (UINM_PADS_CustomSWstuck);
		fun >> (UINM_PADS_VolRollerRotatedDir);
		fun >> (UINM_PADS_IDC_SkipIncSWSt);
		fun >> (UINM_PADS_IDC_SkipIncSWStVD);
		fun >> (UINM_PADS_VolRollerSt);
		fun >> (UINM_PADS_IDC_SkipIncSWStuckSt);
		fun >> (UINM_PADS_IDC_SkipDecSWSt);
		fun >> (UINM_PADS_IDC_SkipDecSWStVD);
		fun >> (UINM_PADS_IDC_SkipDecSWStuckSt);
		fun >> (UINM_PADS_IDC_PlaySWSt);
		fun >> (UINM_PADS_IDC_PlaySWStVD);
		fun >> (UINM_PADS_IDC_PlaySWStuckSt);
		fun >> (UINM_PADS_CruSetSpeedRollerRotatedDir);
		fun >> (UINM_PADS_FolDistIncSWSt);
		fun >> (UINM_PADS_CruSetSpeedRollerSt);
		fun >> (UINM_PADS_FolDistIncSWStVD);
		fun >> (UINM_PADS_FolDistIncSWStuckSt);
		fun >> (UINM_PADS_FolDistDecSWSt);
		fun >> (UINM_PADS_FolDistDecSWStVD);
		fun >> (UINM_PADS_FolDistDecSWStuckSt);
		fun >> (UINM_PADS_OKSWSt);
		fun >> (UINM_PADS_OKSWStVD);
		fun >> (UINM_PADS_OKSWStuckSt);
		fun >> (UINM_PADS_VolRollerVD);
		fun >> (UINM_PADS_CruSetSpeedRollerVD);
		fun >> (UINM_PADS_IDC_ModeSWSt);
		fun >> (UINM_PADS_IDC_ModeSWStVD);
		fun >> (UINM_PADS_IDC_ModeSWStuckSt);
		fun >> (UINM_PADS_IDC_VolIncSWSt);
		fun >> (UINM_PADS_IDC_VolIncSWStVD);
		fun >> (UINM_PADS_IDC_VolIncSWStuckSt);
		fun >> (UINM_PADS_IDC_VolDecSWSt);
		fun >> (UINM_PADS_IDC_VolDecSWStVD);
		fun >> (UINM_PADS_IDC_VolDecSWStuckSt);
		fun >> (UINM_PADS_ICM_UPSWSt);
		fun >> (UINM_PADS_ICM_UPSWStVD);
		fun >> (UINM_PADS_ICM_UPSWStuckSt);
		fun >> (UINM_PADS_ICM_DownSWSt);
		fun >> (UINM_PADS_ICM_DownSWStVD);
		fun >> (UINM_PADS_ICM_DownSWStuckSt);
		fun >> (UINM_PADS_CruSWSt);
		fun >> (UINM_PADS_CruSWStVD);
		fun >> (UINM_PADS_CruSWStuckSt);
		fun >> (UINM_PADS_CruSpeedDecSWSt);
		fun >> (UINM_PADS_CruSpeedDecSWStVD);
		fun >> (UINM_PADS_CruSpeedDecSWStuckSt);
		fun >> (UINM_PADS_CruResumeSpeedIncSWSt);
		fun >> (UINM_PADS_CruResumeSpeedIncSWStVD);
		fun >> (UINM_PADS_CruResumeSpeedIncSWStuckSt);
		fun >> (UINM_PADS_CruTauGapSWSt);
		fun >> (UINM_PADS_CruTauGapSWStVD);
		fun >> (UINM_PADS_CruTauGapSWStcukSt);
		fun >> (UINM_PADS_CruTJAICASWSt);
		fun >> (UINM_PADS_CruTJAICASWStVD);
		fun >> (UINM_PADS_CruTJAICASWStuckSt);
		fun >> (UINM_PADS_IpadelSWSt);
		fun >> (UINM_PADS_IpadelSWStVD);
		fun >> (UINM_PADS_IpadelSWStuckSt);
		fun >> (UINM_PADS_Custom2SWSt);
		fun >> (UINM_PADS_Custom2SWStVD);
		fun >> (UINM_PADS_Custom2SWStuckSt);
		fun >> (UINM_PADS_ACCSWSt);
		fun >> (UINM_PADS_VoltageFaultSt);
		fun >> (UINM_PADS_L_UpSWSt);
		fun >> (UINM_PADS_L_UpSWStVD);
		fun >> (UINM_PADS_L_DownSWSt);
		fun >> (UINM_PADS_L_DownSWStVD);
		fun >> (UINM_PADS_L_leftSWSt);
		fun >> (UINM_PADS_L_LeftSWStVD);
		fun >> (UINM_PADS_L_RightSWSt);
		fun >> (UINM_PADS_L_RightSWStVD);
		fun >> (UINM_PADS_L_UDRollerRotatedDir);
		fun >> (UINM_PADS_L_UDRollerRSt);
		fun >> (UINM_PADS_L_UDRollerVD);
		fun >> (UINM_PADS_L_LRRollerRotatedDir);
		fun >> (UINM_PADS_L_LRRollerRSt);
		fun >> (UINM_PADS_L_LRRollerVD);
		fun >> (UINM_PADS_R_UpSWSt);
		fun >> (UINM_PADS_R_UpSWStVD);
		fun >> (UINM_PADS_R_DownSWSt);
		fun >> (UINM_PADS_R_DownSWStVD);
		fun >> (UINM_PADS_R_leftSWSt);
		fun >> (UINM_PADS_R_LeftSWStVD);
		fun >> (UINM_PADS_R_RightSWSt);
		fun >> (UINM_PADS_R_RightSWStVD);
		fun >> (UINM_PADS_R_UDRollerRotatedDir);
		fun >> (UINM_PADS_R_UDRollerRSt);
		fun >> (UINM_PADS_R_UDRollerVD);
		fun >> (UINM_PADS_R_LRRollerRotatedDir);
		fun >> (UINM_PADS_R_LRRollerRSt);
		fun >> (UINM_PADS_R_LRRollerVD);
	}
};

#endif //____BDCUINM5_H__
