#ifndef ____BDCTESTBMS5_H__
#define ____BDCTESTBMS5_H__


#include "cstdint"






struct BDCTestBMS5 {
public:
	std::uint16_t BMS_BusBarIns1;
	std::uint16_t BMS_BusBarIns2;
	std::uint16_t BMS_BusBarIns3;
	std::uint8_t BMS_ProbeTempNo1;
	std::uint8_t BMS_ProbeTempNo2;
	std::uint8_t BMS_ProbeTempNo3;
	std::uint8_t BMS_ProbeTempNo4;
	std::uint8_t BMS_ProbeTempNo5;
	std::uint8_t BMS_ProbeTempNo6;
	std::uint8_t BMS_ProbeTempNo7;
	std::uint8_t BMS_ProbeTempNo8;
	std::uint8_t BMS_CellBalaStNo1;
	std::uint8_t BMS_CellBalaStNo2;
	std::uint8_t BMS_CellBalaStNo3;
	std::uint8_t BMS_CellBalaStNo4;
	std::uint8_t BMS_CellBalaStNo5;
	std::uint8_t BMS_CellBalaStNo6;
	std::uint8_t BMS_CellBalaStNo7;
	std::uint8_t BMS_CellBalaStNo8;
	std::uint8_t BMS_CellBalaStNo9;
	std::uint8_t BMS_CellBalaStNo10;
	std::uint8_t BMS_CellBalaStNo11;
	std::uint8_t BMS_CellBalaStNo12;
	std::uint8_t BMS_CellBalaStNo13;
	std::uint8_t BMS_CellBalaStNo14;
	std::uint8_t BMS_CellBalaStNo15;
	std::uint8_t BMS_CellBalaStNo16;
	std::uint8_t BMS_CellBalaStNo17;
	std::uint8_t BMS_CellBalaStNo18;
	std::uint8_t BMS_CellBalaStNo19;
	std::uint8_t BMS_CellBalaStNo20;
	std::uint8_t BMS_CellBalaStNo21;
	std::uint8_t BMS_CellBalaStNo22;
	std::uint8_t BMS_CellBalaStNo23;
	std::uint8_t BMS_CellBalaStNo24;
	std::uint8_t BMS_CellBalaStNo25;
	std::uint8_t BMS_CellBalaStNo26;
	std::uint8_t BMS_CellBalaStNo27;
	std::uint8_t BMS_CellBalaStNo28;
	std::uint8_t BMS_CellBalaStNo29;
	std::uint8_t BMS_CellBalaStNo30;
	std::uint8_t BMS_CellBalaStNo31;
	std::uint8_t BMS_CellBalaStNo32;
	std::uint8_t BMS_CellBalaStNo33;
	std::uint8_t BMS_CellBalaStNo34;
	std::uint8_t BMS_CellBalaStNo35;
	std::uint8_t BMS_CellBalaStNo36;
	std::uint8_t BMS_CellBalaStNo37;
	std::uint8_t BMS_CellBalaStNo38;
	std::uint8_t BMS_CellBalaStNo39;
	std::uint8_t BMS_CellBalaStNo40;
	std::uint8_t BMS_CellBalaStNo41;
	std::uint8_t BMS_CellBalaStNo42;
	std::uint8_t BMS_CellBalaStNo43;
	std::uint8_t BMS_CellBalaStNo44;
	std::uint8_t BMS_CellBalaStNo45;
	std::uint8_t BMS_CellBalaStNo46;
	std::uint8_t BMS_CellBalaStNo47;
	std::uint8_t BMS_CellBalaStNo48;
	std::uint8_t BMS_CellBalaStNo49;
	std::uint8_t BMS_CellBalaStNo50;
	std::uint8_t BMS_CellBalaStNo51;
	std::uint8_t BMS_CellBalaStNo52;
	std::uint8_t BMS_CellBalaStNo53;
	std::uint8_t BMS_CellBalaStNo54;
	std::uint8_t BMS_CellBalaStNo55;
	std::uint8_t BMS_CellBalaStNo56;
	std::uint8_t BMS_CellBalaStNo57;
	std::uint8_t BMS_CellBalaStNo58;
	std::uint8_t BMS_CellBalaStNo59;
	std::uint8_t BMS_CellBalaStNo60;
	std::uint8_t BMS_CellBalaStNo61;
	std::uint8_t BMS_CellBalaStNo62;
	std::uint8_t BMS_CellBalaStNo63;
	std::uint8_t BMS_CellBalaStNo64;
	std::uint8_t BMS_CellBalaStNo65;
	std::uint8_t BMS_CellBalaStNo66;
	std::uint8_t BMS_CellBalaStNo67;
	std::uint8_t BMS_CellBalaStNo68;
	std::uint8_t BMS_CellBalaStNo69;
	std::uint8_t BMS_CellBalaStNo70;
	std::uint8_t BMS_CellBalaStNo71;
	std::uint8_t BMS_CellBalaStNo72;
	std::uint8_t BMS_CellBalaStNo73;
	std::uint8_t BMS_CellBalaStNo74;
	std::uint8_t BMS_CellBalaStNo75;
	std::uint8_t BMS_CellBalaStNo76;
	std::uint8_t BMS_CellBalaStNo77;
	std::uint8_t BMS_CellBalaStNo78;
	std::uint8_t BMS_CellBalaStNo79;
	std::uint8_t BMS_CellBalaStNo80;
	std::uint8_t BMS_CellBalaStNo81;
	std::uint8_t BMS_CellBalaStNo82;
	std::uint8_t BMS_CellBalaStNo83;
	std::uint8_t BMS_CellBalaStNo84;
	std::uint8_t BMS_CellBalaStNo85;
	std::uint8_t BMS_CellBalaStNo86;
	std::uint8_t BMS_CellBalaStNo87;
	std::uint8_t BMS_CellBalaStNo88;
	std::uint8_t BMS_CellBalaStNo89;
	std::uint8_t BMS_CellBalaStNo90;
	std::uint8_t BMS_CellBalaStNo91;
	std::uint8_t BMS_CellBalaStNo92;
	std::uint8_t BMS_CellBalaStNo93;
	std::uint8_t BMS_CellBalaStNo94;
	std::uint8_t BMS_CellBalaStNo95;
	std::uint8_t BMS_CellBalaStNo96;
/*
	BDCTestBMS5() {}
	~BDCTestBMS5() {}
	BDCTestBMS5(const std::uint16_t _BMS_BusBarIns1,const std::uint16_t _BMS_BusBarIns2,const std::uint16_t _BMS_BusBarIns3,const std::uint8_t _BMS_ProbeTempNo1,const std::uint8_t _BMS_ProbeTempNo2,const std::uint8_t _BMS_ProbeTempNo3,const std::uint8_t _BMS_ProbeTempNo4,const std::uint8_t _BMS_ProbeTempNo5,const std::uint8_t _BMS_ProbeTempNo6,const std::uint8_t _BMS_ProbeTempNo7,const std::uint8_t _BMS_ProbeTempNo8,const std::uint8_t _BMS_CellBalaStNo1,const std::uint8_t _BMS_CellBalaStNo2,const std::uint8_t _BMS_CellBalaStNo3,const std::uint8_t _BMS_CellBalaStNo4,const std::uint8_t _BMS_CellBalaStNo5,const std::uint8_t _BMS_CellBalaStNo6,const std::uint8_t _BMS_CellBalaStNo7,const std::uint8_t _BMS_CellBalaStNo8,const std::uint8_t _BMS_CellBalaStNo9,const std::uint8_t _BMS_CellBalaStNo10,const std::uint8_t _BMS_CellBalaStNo11,const std::uint8_t _BMS_CellBalaStNo12,const std::uint8_t _BMS_CellBalaStNo13,const std::uint8_t _BMS_CellBalaStNo14,const std::uint8_t _BMS_CellBalaStNo15,const std::uint8_t _BMS_CellBalaStNo16,const std::uint8_t _BMS_CellBalaStNo17,const std::uint8_t _BMS_CellBalaStNo18,const std::uint8_t _BMS_CellBalaStNo19,const std::uint8_t _BMS_CellBalaStNo20,const std::uint8_t _BMS_CellBalaStNo21,const std::uint8_t _BMS_CellBalaStNo22,const std::uint8_t _BMS_CellBalaStNo23,const std::uint8_t _BMS_CellBalaStNo24,const std::uint8_t _BMS_CellBalaStNo25,const std::uint8_t _BMS_CellBalaStNo26,const std::uint8_t _BMS_CellBalaStNo27,const std::uint8_t _BMS_CellBalaStNo28,const std::uint8_t _BMS_CellBalaStNo29,const std::uint8_t _BMS_CellBalaStNo30,const std::uint8_t _BMS_CellBalaStNo31,const std::uint8_t _BMS_CellBalaStNo32,const std::uint8_t _BMS_CellBalaStNo33,const std::uint8_t _BMS_CellBalaStNo34,const std::uint8_t _BMS_CellBalaStNo35,const std::uint8_t _BMS_CellBalaStNo36,const std::uint8_t _BMS_CellBalaStNo37,const std::uint8_t _BMS_CellBalaStNo38,const std::uint8_t _BMS_CellBalaStNo39,const std::uint8_t _BMS_CellBalaStNo40,const std::uint8_t _BMS_CellBalaStNo41,const std::uint8_t _BMS_CellBalaStNo42,const std::uint8_t _BMS_CellBalaStNo43,const std::uint8_t _BMS_CellBalaStNo44,const std::uint8_t _BMS_CellBalaStNo45,const std::uint8_t _BMS_CellBalaStNo46,const std::uint8_t _BMS_CellBalaStNo47,const std::uint8_t _BMS_CellBalaStNo48,const std::uint8_t _BMS_CellBalaStNo49,const std::uint8_t _BMS_CellBalaStNo50,const std::uint8_t _BMS_CellBalaStNo51,const std::uint8_t _BMS_CellBalaStNo52,const std::uint8_t _BMS_CellBalaStNo53,const std::uint8_t _BMS_CellBalaStNo54,const std::uint8_t _BMS_CellBalaStNo55,const std::uint8_t _BMS_CellBalaStNo56,const std::uint8_t _BMS_CellBalaStNo57,const std::uint8_t _BMS_CellBalaStNo58,const std::uint8_t _BMS_CellBalaStNo59,const std::uint8_t _BMS_CellBalaStNo60,const std::uint8_t _BMS_CellBalaStNo61,const std::uint8_t _BMS_CellBalaStNo62,const std::uint8_t _BMS_CellBalaStNo63,const std::uint8_t _BMS_CellBalaStNo64,const std::uint8_t _BMS_CellBalaStNo65,const std::uint8_t _BMS_CellBalaStNo66,const std::uint8_t _BMS_CellBalaStNo67,const std::uint8_t _BMS_CellBalaStNo68,const std::uint8_t _BMS_CellBalaStNo69,const std::uint8_t _BMS_CellBalaStNo70,const std::uint8_t _BMS_CellBalaStNo71,const std::uint8_t _BMS_CellBalaStNo72,const std::uint8_t _BMS_CellBalaStNo73,const std::uint8_t _BMS_CellBalaStNo74,const std::uint8_t _BMS_CellBalaStNo75,const std::uint8_t _BMS_CellBalaStNo76,const std::uint8_t _BMS_CellBalaStNo77,const std::uint8_t _BMS_CellBalaStNo78,const std::uint8_t _BMS_CellBalaStNo79,const std::uint8_t _BMS_CellBalaStNo80,const std::uint8_t _BMS_CellBalaStNo81,const std::uint8_t _BMS_CellBalaStNo82,const std::uint8_t _BMS_CellBalaStNo83,const std::uint8_t _BMS_CellBalaStNo84,const std::uint8_t _BMS_CellBalaStNo85,const std::uint8_t _BMS_CellBalaStNo86,const std::uint8_t _BMS_CellBalaStNo87,const std::uint8_t _BMS_CellBalaStNo88,const std::uint8_t _BMS_CellBalaStNo89,const std::uint8_t _BMS_CellBalaStNo90,const std::uint8_t _BMS_CellBalaStNo91,const std::uint8_t _BMS_CellBalaStNo92,const std::uint8_t _BMS_CellBalaStNo93,const std::uint8_t _BMS_CellBalaStNo94,const std::uint8_t _BMS_CellBalaStNo95,const std::uint8_t _BMS_CellBalaStNo96):BMS_BusBarIns1(_BMS_BusBarIns1),BMS_BusBarIns2(_BMS_BusBarIns2),BMS_BusBarIns3(_BMS_BusBarIns3),BMS_ProbeTempNo1(_BMS_ProbeTempNo1),BMS_ProbeTempNo2(_BMS_ProbeTempNo2),BMS_ProbeTempNo3(_BMS_ProbeTempNo3),BMS_ProbeTempNo4(_BMS_ProbeTempNo4),BMS_ProbeTempNo5(_BMS_ProbeTempNo5),BMS_ProbeTempNo6(_BMS_ProbeTempNo6),BMS_ProbeTempNo7(_BMS_ProbeTempNo7),BMS_ProbeTempNo8(_BMS_ProbeTempNo8),BMS_CellBalaStNo1(_BMS_CellBalaStNo1),BMS_CellBalaStNo2(_BMS_CellBalaStNo2),BMS_CellBalaStNo3(_BMS_CellBalaStNo3),BMS_CellBalaStNo4(_BMS_CellBalaStNo4),BMS_CellBalaStNo5(_BMS_CellBalaStNo5),BMS_CellBalaStNo6(_BMS_CellBalaStNo6),BMS_CellBalaStNo7(_BMS_CellBalaStNo7),BMS_CellBalaStNo8(_BMS_CellBalaStNo8),BMS_CellBalaStNo9(_BMS_CellBalaStNo9),BMS_CellBalaStNo10(_BMS_CellBalaStNo10),BMS_CellBalaStNo11(_BMS_CellBalaStNo11),BMS_CellBalaStNo12(_BMS_CellBalaStNo12),BMS_CellBalaStNo13(_BMS_CellBalaStNo13),BMS_CellBalaStNo14(_BMS_CellBalaStNo14),BMS_CellBalaStNo15(_BMS_CellBalaStNo15),BMS_CellBalaStNo16(_BMS_CellBalaStNo16),BMS_CellBalaStNo17(_BMS_CellBalaStNo17),BMS_CellBalaStNo18(_BMS_CellBalaStNo18),BMS_CellBalaStNo19(_BMS_CellBalaStNo19),BMS_CellBalaStNo20(_BMS_CellBalaStNo20),BMS_CellBalaStNo21(_BMS_CellBalaStNo21),BMS_CellBalaStNo22(_BMS_CellBalaStNo22),BMS_CellBalaStNo23(_BMS_CellBalaStNo23),BMS_CellBalaStNo24(_BMS_CellBalaStNo24),BMS_CellBalaStNo25(_BMS_CellBalaStNo25),BMS_CellBalaStNo26(_BMS_CellBalaStNo26),BMS_CellBalaStNo27(_BMS_CellBalaStNo27),BMS_CellBalaStNo28(_BMS_CellBalaStNo28),BMS_CellBalaStNo29(_BMS_CellBalaStNo29),BMS_CellBalaStNo30(_BMS_CellBalaStNo30),BMS_CellBalaStNo31(_BMS_CellBalaStNo31),BMS_CellBalaStNo32(_BMS_CellBalaStNo32),BMS_CellBalaStNo33(_BMS_CellBalaStNo33),BMS_CellBalaStNo34(_BMS_CellBalaStNo34),BMS_CellBalaStNo35(_BMS_CellBalaStNo35),BMS_CellBalaStNo36(_BMS_CellBalaStNo36),BMS_CellBalaStNo37(_BMS_CellBalaStNo37),BMS_CellBalaStNo38(_BMS_CellBalaStNo38),BMS_CellBalaStNo39(_BMS_CellBalaStNo39),BMS_CellBalaStNo40(_BMS_CellBalaStNo40),BMS_CellBalaStNo41(_BMS_CellBalaStNo41),BMS_CellBalaStNo42(_BMS_CellBalaStNo42),BMS_CellBalaStNo43(_BMS_CellBalaStNo43),BMS_CellBalaStNo44(_BMS_CellBalaStNo44),BMS_CellBalaStNo45(_BMS_CellBalaStNo45),BMS_CellBalaStNo46(_BMS_CellBalaStNo46),BMS_CellBalaStNo47(_BMS_CellBalaStNo47),BMS_CellBalaStNo48(_BMS_CellBalaStNo48),BMS_CellBalaStNo49(_BMS_CellBalaStNo49),BMS_CellBalaStNo50(_BMS_CellBalaStNo50),BMS_CellBalaStNo51(_BMS_CellBalaStNo51),BMS_CellBalaStNo52(_BMS_CellBalaStNo52),BMS_CellBalaStNo53(_BMS_CellBalaStNo53),BMS_CellBalaStNo54(_BMS_CellBalaStNo54),BMS_CellBalaStNo55(_BMS_CellBalaStNo55),BMS_CellBalaStNo56(_BMS_CellBalaStNo56),BMS_CellBalaStNo57(_BMS_CellBalaStNo57),BMS_CellBalaStNo58(_BMS_CellBalaStNo58),BMS_CellBalaStNo59(_BMS_CellBalaStNo59),BMS_CellBalaStNo60(_BMS_CellBalaStNo60),BMS_CellBalaStNo61(_BMS_CellBalaStNo61),BMS_CellBalaStNo62(_BMS_CellBalaStNo62),BMS_CellBalaStNo63(_BMS_CellBalaStNo63),BMS_CellBalaStNo64(_BMS_CellBalaStNo64),BMS_CellBalaStNo65(_BMS_CellBalaStNo65),BMS_CellBalaStNo66(_BMS_CellBalaStNo66),BMS_CellBalaStNo67(_BMS_CellBalaStNo67),BMS_CellBalaStNo68(_BMS_CellBalaStNo68),BMS_CellBalaStNo69(_BMS_CellBalaStNo69),BMS_CellBalaStNo70(_BMS_CellBalaStNo70),BMS_CellBalaStNo71(_BMS_CellBalaStNo71),BMS_CellBalaStNo72(_BMS_CellBalaStNo72),BMS_CellBalaStNo73(_BMS_CellBalaStNo73),BMS_CellBalaStNo74(_BMS_CellBalaStNo74),BMS_CellBalaStNo75(_BMS_CellBalaStNo75),BMS_CellBalaStNo76(_BMS_CellBalaStNo76),BMS_CellBalaStNo77(_BMS_CellBalaStNo77),BMS_CellBalaStNo78(_BMS_CellBalaStNo78),BMS_CellBalaStNo79(_BMS_CellBalaStNo79),BMS_CellBalaStNo80(_BMS_CellBalaStNo80),BMS_CellBalaStNo81(_BMS_CellBalaStNo81),BMS_CellBalaStNo82(_BMS_CellBalaStNo82),BMS_CellBalaStNo83(_BMS_CellBalaStNo83),BMS_CellBalaStNo84(_BMS_CellBalaStNo84),BMS_CellBalaStNo85(_BMS_CellBalaStNo85),BMS_CellBalaStNo86(_BMS_CellBalaStNo86),BMS_CellBalaStNo87(_BMS_CellBalaStNo87),BMS_CellBalaStNo88(_BMS_CellBalaStNo88),BMS_CellBalaStNo89(_BMS_CellBalaStNo89),BMS_CellBalaStNo90(_BMS_CellBalaStNo90),BMS_CellBalaStNo91(_BMS_CellBalaStNo91),BMS_CellBalaStNo92(_BMS_CellBalaStNo92),BMS_CellBalaStNo93(_BMS_CellBalaStNo93),BMS_CellBalaStNo94(_BMS_CellBalaStNo94),BMS_CellBalaStNo95(_BMS_CellBalaStNo95),BMS_CellBalaStNo96(_BMS_CellBalaStNo96) {}
	BDCTestBMS5(const BDCTestBMS5 &_x){
		BMS_BusBarIns1 = _x.BMS_BusBarIns1;
		BMS_BusBarIns2 = _x.BMS_BusBarIns2;
		BMS_BusBarIns3 = _x.BMS_BusBarIns3;
		BMS_ProbeTempNo1 = _x.BMS_ProbeTempNo1;
		BMS_ProbeTempNo2 = _x.BMS_ProbeTempNo2;
		BMS_ProbeTempNo3 = _x.BMS_ProbeTempNo3;
		BMS_ProbeTempNo4 = _x.BMS_ProbeTempNo4;
		BMS_ProbeTempNo5 = _x.BMS_ProbeTempNo5;
		BMS_ProbeTempNo6 = _x.BMS_ProbeTempNo6;
		BMS_ProbeTempNo7 = _x.BMS_ProbeTempNo7;
		BMS_ProbeTempNo8 = _x.BMS_ProbeTempNo8;
		BMS_CellBalaStNo1 = _x.BMS_CellBalaStNo1;
		BMS_CellBalaStNo2 = _x.BMS_CellBalaStNo2;
		BMS_CellBalaStNo3 = _x.BMS_CellBalaStNo3;
		BMS_CellBalaStNo4 = _x.BMS_CellBalaStNo4;
		BMS_CellBalaStNo5 = _x.BMS_CellBalaStNo5;
		BMS_CellBalaStNo6 = _x.BMS_CellBalaStNo6;
		BMS_CellBalaStNo7 = _x.BMS_CellBalaStNo7;
		BMS_CellBalaStNo8 = _x.BMS_CellBalaStNo8;
		BMS_CellBalaStNo9 = _x.BMS_CellBalaStNo9;
		BMS_CellBalaStNo10 = _x.BMS_CellBalaStNo10;
		BMS_CellBalaStNo11 = _x.BMS_CellBalaStNo11;
		BMS_CellBalaStNo12 = _x.BMS_CellBalaStNo12;
		BMS_CellBalaStNo13 = _x.BMS_CellBalaStNo13;
		BMS_CellBalaStNo14 = _x.BMS_CellBalaStNo14;
		BMS_CellBalaStNo15 = _x.BMS_CellBalaStNo15;
		BMS_CellBalaStNo16 = _x.BMS_CellBalaStNo16;
		BMS_CellBalaStNo17 = _x.BMS_CellBalaStNo17;
		BMS_CellBalaStNo18 = _x.BMS_CellBalaStNo18;
		BMS_CellBalaStNo19 = _x.BMS_CellBalaStNo19;
		BMS_CellBalaStNo20 = _x.BMS_CellBalaStNo20;
		BMS_CellBalaStNo21 = _x.BMS_CellBalaStNo21;
		BMS_CellBalaStNo22 = _x.BMS_CellBalaStNo22;
		BMS_CellBalaStNo23 = _x.BMS_CellBalaStNo23;
		BMS_CellBalaStNo24 = _x.BMS_CellBalaStNo24;
		BMS_CellBalaStNo25 = _x.BMS_CellBalaStNo25;
		BMS_CellBalaStNo26 = _x.BMS_CellBalaStNo26;
		BMS_CellBalaStNo27 = _x.BMS_CellBalaStNo27;
		BMS_CellBalaStNo28 = _x.BMS_CellBalaStNo28;
		BMS_CellBalaStNo29 = _x.BMS_CellBalaStNo29;
		BMS_CellBalaStNo30 = _x.BMS_CellBalaStNo30;
		BMS_CellBalaStNo31 = _x.BMS_CellBalaStNo31;
		BMS_CellBalaStNo32 = _x.BMS_CellBalaStNo32;
		BMS_CellBalaStNo33 = _x.BMS_CellBalaStNo33;
		BMS_CellBalaStNo34 = _x.BMS_CellBalaStNo34;
		BMS_CellBalaStNo35 = _x.BMS_CellBalaStNo35;
		BMS_CellBalaStNo36 = _x.BMS_CellBalaStNo36;
		BMS_CellBalaStNo37 = _x.BMS_CellBalaStNo37;
		BMS_CellBalaStNo38 = _x.BMS_CellBalaStNo38;
		BMS_CellBalaStNo39 = _x.BMS_CellBalaStNo39;
		BMS_CellBalaStNo40 = _x.BMS_CellBalaStNo40;
		BMS_CellBalaStNo41 = _x.BMS_CellBalaStNo41;
		BMS_CellBalaStNo42 = _x.BMS_CellBalaStNo42;
		BMS_CellBalaStNo43 = _x.BMS_CellBalaStNo43;
		BMS_CellBalaStNo44 = _x.BMS_CellBalaStNo44;
		BMS_CellBalaStNo45 = _x.BMS_CellBalaStNo45;
		BMS_CellBalaStNo46 = _x.BMS_CellBalaStNo46;
		BMS_CellBalaStNo47 = _x.BMS_CellBalaStNo47;
		BMS_CellBalaStNo48 = _x.BMS_CellBalaStNo48;
		BMS_CellBalaStNo49 = _x.BMS_CellBalaStNo49;
		BMS_CellBalaStNo50 = _x.BMS_CellBalaStNo50;
		BMS_CellBalaStNo51 = _x.BMS_CellBalaStNo51;
		BMS_CellBalaStNo52 = _x.BMS_CellBalaStNo52;
		BMS_CellBalaStNo53 = _x.BMS_CellBalaStNo53;
		BMS_CellBalaStNo54 = _x.BMS_CellBalaStNo54;
		BMS_CellBalaStNo55 = _x.BMS_CellBalaStNo55;
		BMS_CellBalaStNo56 = _x.BMS_CellBalaStNo56;
		BMS_CellBalaStNo57 = _x.BMS_CellBalaStNo57;
		BMS_CellBalaStNo58 = _x.BMS_CellBalaStNo58;
		BMS_CellBalaStNo59 = _x.BMS_CellBalaStNo59;
		BMS_CellBalaStNo60 = _x.BMS_CellBalaStNo60;
		BMS_CellBalaStNo61 = _x.BMS_CellBalaStNo61;
		BMS_CellBalaStNo62 = _x.BMS_CellBalaStNo62;
		BMS_CellBalaStNo63 = _x.BMS_CellBalaStNo63;
		BMS_CellBalaStNo64 = _x.BMS_CellBalaStNo64;
		BMS_CellBalaStNo65 = _x.BMS_CellBalaStNo65;
		BMS_CellBalaStNo66 = _x.BMS_CellBalaStNo66;
		BMS_CellBalaStNo67 = _x.BMS_CellBalaStNo67;
		BMS_CellBalaStNo68 = _x.BMS_CellBalaStNo68;
		BMS_CellBalaStNo69 = _x.BMS_CellBalaStNo69;
		BMS_CellBalaStNo70 = _x.BMS_CellBalaStNo70;
		BMS_CellBalaStNo71 = _x.BMS_CellBalaStNo71;
		BMS_CellBalaStNo72 = _x.BMS_CellBalaStNo72;
		BMS_CellBalaStNo73 = _x.BMS_CellBalaStNo73;
		BMS_CellBalaStNo74 = _x.BMS_CellBalaStNo74;
		BMS_CellBalaStNo75 = _x.BMS_CellBalaStNo75;
		BMS_CellBalaStNo76 = _x.BMS_CellBalaStNo76;
		BMS_CellBalaStNo77 = _x.BMS_CellBalaStNo77;
		BMS_CellBalaStNo78 = _x.BMS_CellBalaStNo78;
		BMS_CellBalaStNo79 = _x.BMS_CellBalaStNo79;
		BMS_CellBalaStNo80 = _x.BMS_CellBalaStNo80;
		BMS_CellBalaStNo81 = _x.BMS_CellBalaStNo81;
		BMS_CellBalaStNo82 = _x.BMS_CellBalaStNo82;
		BMS_CellBalaStNo83 = _x.BMS_CellBalaStNo83;
		BMS_CellBalaStNo84 = _x.BMS_CellBalaStNo84;
		BMS_CellBalaStNo85 = _x.BMS_CellBalaStNo85;
		BMS_CellBalaStNo86 = _x.BMS_CellBalaStNo86;
		BMS_CellBalaStNo87 = _x.BMS_CellBalaStNo87;
		BMS_CellBalaStNo88 = _x.BMS_CellBalaStNo88;
		BMS_CellBalaStNo89 = _x.BMS_CellBalaStNo89;
		BMS_CellBalaStNo90 = _x.BMS_CellBalaStNo90;
		BMS_CellBalaStNo91 = _x.BMS_CellBalaStNo91;
		BMS_CellBalaStNo92 = _x.BMS_CellBalaStNo92;
		BMS_CellBalaStNo93 = _x.BMS_CellBalaStNo93;
		BMS_CellBalaStNo94 = _x.BMS_CellBalaStNo94;
		BMS_CellBalaStNo95 = _x.BMS_CellBalaStNo95;
		BMS_CellBalaStNo96 = _x.BMS_CellBalaStNo96;
	}
	BDCTestBMS5(BDCTestBMS5 &&_x){
		BMS_BusBarIns1 = std::move(_x.BMS_BusBarIns1);
		BMS_BusBarIns2 = std::move(_x.BMS_BusBarIns2);
		BMS_BusBarIns3 = std::move(_x.BMS_BusBarIns3);
		BMS_ProbeTempNo1 = std::move(_x.BMS_ProbeTempNo1);
		BMS_ProbeTempNo2 = std::move(_x.BMS_ProbeTempNo2);
		BMS_ProbeTempNo3 = std::move(_x.BMS_ProbeTempNo3);
		BMS_ProbeTempNo4 = std::move(_x.BMS_ProbeTempNo4);
		BMS_ProbeTempNo5 = std::move(_x.BMS_ProbeTempNo5);
		BMS_ProbeTempNo6 = std::move(_x.BMS_ProbeTempNo6);
		BMS_ProbeTempNo7 = std::move(_x.BMS_ProbeTempNo7);
		BMS_ProbeTempNo8 = std::move(_x.BMS_ProbeTempNo8);
		BMS_CellBalaStNo1 = std::move(_x.BMS_CellBalaStNo1);
		BMS_CellBalaStNo2 = std::move(_x.BMS_CellBalaStNo2);
		BMS_CellBalaStNo3 = std::move(_x.BMS_CellBalaStNo3);
		BMS_CellBalaStNo4 = std::move(_x.BMS_CellBalaStNo4);
		BMS_CellBalaStNo5 = std::move(_x.BMS_CellBalaStNo5);
		BMS_CellBalaStNo6 = std::move(_x.BMS_CellBalaStNo6);
		BMS_CellBalaStNo7 = std::move(_x.BMS_CellBalaStNo7);
		BMS_CellBalaStNo8 = std::move(_x.BMS_CellBalaStNo8);
		BMS_CellBalaStNo9 = std::move(_x.BMS_CellBalaStNo9);
		BMS_CellBalaStNo10 = std::move(_x.BMS_CellBalaStNo10);
		BMS_CellBalaStNo11 = std::move(_x.BMS_CellBalaStNo11);
		BMS_CellBalaStNo12 = std::move(_x.BMS_CellBalaStNo12);
		BMS_CellBalaStNo13 = std::move(_x.BMS_CellBalaStNo13);
		BMS_CellBalaStNo14 = std::move(_x.BMS_CellBalaStNo14);
		BMS_CellBalaStNo15 = std::move(_x.BMS_CellBalaStNo15);
		BMS_CellBalaStNo16 = std::move(_x.BMS_CellBalaStNo16);
		BMS_CellBalaStNo17 = std::move(_x.BMS_CellBalaStNo17);
		BMS_CellBalaStNo18 = std::move(_x.BMS_CellBalaStNo18);
		BMS_CellBalaStNo19 = std::move(_x.BMS_CellBalaStNo19);
		BMS_CellBalaStNo20 = std::move(_x.BMS_CellBalaStNo20);
		BMS_CellBalaStNo21 = std::move(_x.BMS_CellBalaStNo21);
		BMS_CellBalaStNo22 = std::move(_x.BMS_CellBalaStNo22);
		BMS_CellBalaStNo23 = std::move(_x.BMS_CellBalaStNo23);
		BMS_CellBalaStNo24 = std::move(_x.BMS_CellBalaStNo24);
		BMS_CellBalaStNo25 = std::move(_x.BMS_CellBalaStNo25);
		BMS_CellBalaStNo26 = std::move(_x.BMS_CellBalaStNo26);
		BMS_CellBalaStNo27 = std::move(_x.BMS_CellBalaStNo27);
		BMS_CellBalaStNo28 = std::move(_x.BMS_CellBalaStNo28);
		BMS_CellBalaStNo29 = std::move(_x.BMS_CellBalaStNo29);
		BMS_CellBalaStNo30 = std::move(_x.BMS_CellBalaStNo30);
		BMS_CellBalaStNo31 = std::move(_x.BMS_CellBalaStNo31);
		BMS_CellBalaStNo32 = std::move(_x.BMS_CellBalaStNo32);
		BMS_CellBalaStNo33 = std::move(_x.BMS_CellBalaStNo33);
		BMS_CellBalaStNo34 = std::move(_x.BMS_CellBalaStNo34);
		BMS_CellBalaStNo35 = std::move(_x.BMS_CellBalaStNo35);
		BMS_CellBalaStNo36 = std::move(_x.BMS_CellBalaStNo36);
		BMS_CellBalaStNo37 = std::move(_x.BMS_CellBalaStNo37);
		BMS_CellBalaStNo38 = std::move(_x.BMS_CellBalaStNo38);
		BMS_CellBalaStNo39 = std::move(_x.BMS_CellBalaStNo39);
		BMS_CellBalaStNo40 = std::move(_x.BMS_CellBalaStNo40);
		BMS_CellBalaStNo41 = std::move(_x.BMS_CellBalaStNo41);
		BMS_CellBalaStNo42 = std::move(_x.BMS_CellBalaStNo42);
		BMS_CellBalaStNo43 = std::move(_x.BMS_CellBalaStNo43);
		BMS_CellBalaStNo44 = std::move(_x.BMS_CellBalaStNo44);
		BMS_CellBalaStNo45 = std::move(_x.BMS_CellBalaStNo45);
		BMS_CellBalaStNo46 = std::move(_x.BMS_CellBalaStNo46);
		BMS_CellBalaStNo47 = std::move(_x.BMS_CellBalaStNo47);
		BMS_CellBalaStNo48 = std::move(_x.BMS_CellBalaStNo48);
		BMS_CellBalaStNo49 = std::move(_x.BMS_CellBalaStNo49);
		BMS_CellBalaStNo50 = std::move(_x.BMS_CellBalaStNo50);
		BMS_CellBalaStNo51 = std::move(_x.BMS_CellBalaStNo51);
		BMS_CellBalaStNo52 = std::move(_x.BMS_CellBalaStNo52);
		BMS_CellBalaStNo53 = std::move(_x.BMS_CellBalaStNo53);
		BMS_CellBalaStNo54 = std::move(_x.BMS_CellBalaStNo54);
		BMS_CellBalaStNo55 = std::move(_x.BMS_CellBalaStNo55);
		BMS_CellBalaStNo56 = std::move(_x.BMS_CellBalaStNo56);
		BMS_CellBalaStNo57 = std::move(_x.BMS_CellBalaStNo57);
		BMS_CellBalaStNo58 = std::move(_x.BMS_CellBalaStNo58);
		BMS_CellBalaStNo59 = std::move(_x.BMS_CellBalaStNo59);
		BMS_CellBalaStNo60 = std::move(_x.BMS_CellBalaStNo60);
		BMS_CellBalaStNo61 = std::move(_x.BMS_CellBalaStNo61);
		BMS_CellBalaStNo62 = std::move(_x.BMS_CellBalaStNo62);
		BMS_CellBalaStNo63 = std::move(_x.BMS_CellBalaStNo63);
		BMS_CellBalaStNo64 = std::move(_x.BMS_CellBalaStNo64);
		BMS_CellBalaStNo65 = std::move(_x.BMS_CellBalaStNo65);
		BMS_CellBalaStNo66 = std::move(_x.BMS_CellBalaStNo66);
		BMS_CellBalaStNo67 = std::move(_x.BMS_CellBalaStNo67);
		BMS_CellBalaStNo68 = std::move(_x.BMS_CellBalaStNo68);
		BMS_CellBalaStNo69 = std::move(_x.BMS_CellBalaStNo69);
		BMS_CellBalaStNo70 = std::move(_x.BMS_CellBalaStNo70);
		BMS_CellBalaStNo71 = std::move(_x.BMS_CellBalaStNo71);
		BMS_CellBalaStNo72 = std::move(_x.BMS_CellBalaStNo72);
		BMS_CellBalaStNo73 = std::move(_x.BMS_CellBalaStNo73);
		BMS_CellBalaStNo74 = std::move(_x.BMS_CellBalaStNo74);
		BMS_CellBalaStNo75 = std::move(_x.BMS_CellBalaStNo75);
		BMS_CellBalaStNo76 = std::move(_x.BMS_CellBalaStNo76);
		BMS_CellBalaStNo77 = std::move(_x.BMS_CellBalaStNo77);
		BMS_CellBalaStNo78 = std::move(_x.BMS_CellBalaStNo78);
		BMS_CellBalaStNo79 = std::move(_x.BMS_CellBalaStNo79);
		BMS_CellBalaStNo80 = std::move(_x.BMS_CellBalaStNo80);
		BMS_CellBalaStNo81 = std::move(_x.BMS_CellBalaStNo81);
		BMS_CellBalaStNo82 = std::move(_x.BMS_CellBalaStNo82);
		BMS_CellBalaStNo83 = std::move(_x.BMS_CellBalaStNo83);
		BMS_CellBalaStNo84 = std::move(_x.BMS_CellBalaStNo84);
		BMS_CellBalaStNo85 = std::move(_x.BMS_CellBalaStNo85);
		BMS_CellBalaStNo86 = std::move(_x.BMS_CellBalaStNo86);
		BMS_CellBalaStNo87 = std::move(_x.BMS_CellBalaStNo87);
		BMS_CellBalaStNo88 = std::move(_x.BMS_CellBalaStNo88);
		BMS_CellBalaStNo89 = std::move(_x.BMS_CellBalaStNo89);
		BMS_CellBalaStNo90 = std::move(_x.BMS_CellBalaStNo90);
		BMS_CellBalaStNo91 = std::move(_x.BMS_CellBalaStNo91);
		BMS_CellBalaStNo92 = std::move(_x.BMS_CellBalaStNo92);
		BMS_CellBalaStNo93 = std::move(_x.BMS_CellBalaStNo93);
		BMS_CellBalaStNo94 = std::move(_x.BMS_CellBalaStNo94);
		BMS_CellBalaStNo95 = std::move(_x.BMS_CellBalaStNo95);
		BMS_CellBalaStNo96 = std::move(_x.BMS_CellBalaStNo96);
	}
	BDCTestBMS5& operator=(const BDCTestBMS5 &_x){
		BMS_BusBarIns1 = _x.BMS_BusBarIns1;
		BMS_BusBarIns2 = _x.BMS_BusBarIns2;
		BMS_BusBarIns3 = _x.BMS_BusBarIns3;
		BMS_ProbeTempNo1 = _x.BMS_ProbeTempNo1;
		BMS_ProbeTempNo2 = _x.BMS_ProbeTempNo2;
		BMS_ProbeTempNo3 = _x.BMS_ProbeTempNo3;
		BMS_ProbeTempNo4 = _x.BMS_ProbeTempNo4;
		BMS_ProbeTempNo5 = _x.BMS_ProbeTempNo5;
		BMS_ProbeTempNo6 = _x.BMS_ProbeTempNo6;
		BMS_ProbeTempNo7 = _x.BMS_ProbeTempNo7;
		BMS_ProbeTempNo8 = _x.BMS_ProbeTempNo8;
		BMS_CellBalaStNo1 = _x.BMS_CellBalaStNo1;
		BMS_CellBalaStNo2 = _x.BMS_CellBalaStNo2;
		BMS_CellBalaStNo3 = _x.BMS_CellBalaStNo3;
		BMS_CellBalaStNo4 = _x.BMS_CellBalaStNo4;
		BMS_CellBalaStNo5 = _x.BMS_CellBalaStNo5;
		BMS_CellBalaStNo6 = _x.BMS_CellBalaStNo6;
		BMS_CellBalaStNo7 = _x.BMS_CellBalaStNo7;
		BMS_CellBalaStNo8 = _x.BMS_CellBalaStNo8;
		BMS_CellBalaStNo9 = _x.BMS_CellBalaStNo9;
		BMS_CellBalaStNo10 = _x.BMS_CellBalaStNo10;
		BMS_CellBalaStNo11 = _x.BMS_CellBalaStNo11;
		BMS_CellBalaStNo12 = _x.BMS_CellBalaStNo12;
		BMS_CellBalaStNo13 = _x.BMS_CellBalaStNo13;
		BMS_CellBalaStNo14 = _x.BMS_CellBalaStNo14;
		BMS_CellBalaStNo15 = _x.BMS_CellBalaStNo15;
		BMS_CellBalaStNo16 = _x.BMS_CellBalaStNo16;
		BMS_CellBalaStNo17 = _x.BMS_CellBalaStNo17;
		BMS_CellBalaStNo18 = _x.BMS_CellBalaStNo18;
		BMS_CellBalaStNo19 = _x.BMS_CellBalaStNo19;
		BMS_CellBalaStNo20 = _x.BMS_CellBalaStNo20;
		BMS_CellBalaStNo21 = _x.BMS_CellBalaStNo21;
		BMS_CellBalaStNo22 = _x.BMS_CellBalaStNo22;
		BMS_CellBalaStNo23 = _x.BMS_CellBalaStNo23;
		BMS_CellBalaStNo24 = _x.BMS_CellBalaStNo24;
		BMS_CellBalaStNo25 = _x.BMS_CellBalaStNo25;
		BMS_CellBalaStNo26 = _x.BMS_CellBalaStNo26;
		BMS_CellBalaStNo27 = _x.BMS_CellBalaStNo27;
		BMS_CellBalaStNo28 = _x.BMS_CellBalaStNo28;
		BMS_CellBalaStNo29 = _x.BMS_CellBalaStNo29;
		BMS_CellBalaStNo30 = _x.BMS_CellBalaStNo30;
		BMS_CellBalaStNo31 = _x.BMS_CellBalaStNo31;
		BMS_CellBalaStNo32 = _x.BMS_CellBalaStNo32;
		BMS_CellBalaStNo33 = _x.BMS_CellBalaStNo33;
		BMS_CellBalaStNo34 = _x.BMS_CellBalaStNo34;
		BMS_CellBalaStNo35 = _x.BMS_CellBalaStNo35;
		BMS_CellBalaStNo36 = _x.BMS_CellBalaStNo36;
		BMS_CellBalaStNo37 = _x.BMS_CellBalaStNo37;
		BMS_CellBalaStNo38 = _x.BMS_CellBalaStNo38;
		BMS_CellBalaStNo39 = _x.BMS_CellBalaStNo39;
		BMS_CellBalaStNo40 = _x.BMS_CellBalaStNo40;
		BMS_CellBalaStNo41 = _x.BMS_CellBalaStNo41;
		BMS_CellBalaStNo42 = _x.BMS_CellBalaStNo42;
		BMS_CellBalaStNo43 = _x.BMS_CellBalaStNo43;
		BMS_CellBalaStNo44 = _x.BMS_CellBalaStNo44;
		BMS_CellBalaStNo45 = _x.BMS_CellBalaStNo45;
		BMS_CellBalaStNo46 = _x.BMS_CellBalaStNo46;
		BMS_CellBalaStNo47 = _x.BMS_CellBalaStNo47;
		BMS_CellBalaStNo48 = _x.BMS_CellBalaStNo48;
		BMS_CellBalaStNo49 = _x.BMS_CellBalaStNo49;
		BMS_CellBalaStNo50 = _x.BMS_CellBalaStNo50;
		BMS_CellBalaStNo51 = _x.BMS_CellBalaStNo51;
		BMS_CellBalaStNo52 = _x.BMS_CellBalaStNo52;
		BMS_CellBalaStNo53 = _x.BMS_CellBalaStNo53;
		BMS_CellBalaStNo54 = _x.BMS_CellBalaStNo54;
		BMS_CellBalaStNo55 = _x.BMS_CellBalaStNo55;
		BMS_CellBalaStNo56 = _x.BMS_CellBalaStNo56;
		BMS_CellBalaStNo57 = _x.BMS_CellBalaStNo57;
		BMS_CellBalaStNo58 = _x.BMS_CellBalaStNo58;
		BMS_CellBalaStNo59 = _x.BMS_CellBalaStNo59;
		BMS_CellBalaStNo60 = _x.BMS_CellBalaStNo60;
		BMS_CellBalaStNo61 = _x.BMS_CellBalaStNo61;
		BMS_CellBalaStNo62 = _x.BMS_CellBalaStNo62;
		BMS_CellBalaStNo63 = _x.BMS_CellBalaStNo63;
		BMS_CellBalaStNo64 = _x.BMS_CellBalaStNo64;
		BMS_CellBalaStNo65 = _x.BMS_CellBalaStNo65;
		BMS_CellBalaStNo66 = _x.BMS_CellBalaStNo66;
		BMS_CellBalaStNo67 = _x.BMS_CellBalaStNo67;
		BMS_CellBalaStNo68 = _x.BMS_CellBalaStNo68;
		BMS_CellBalaStNo69 = _x.BMS_CellBalaStNo69;
		BMS_CellBalaStNo70 = _x.BMS_CellBalaStNo70;
		BMS_CellBalaStNo71 = _x.BMS_CellBalaStNo71;
		BMS_CellBalaStNo72 = _x.BMS_CellBalaStNo72;
		BMS_CellBalaStNo73 = _x.BMS_CellBalaStNo73;
		BMS_CellBalaStNo74 = _x.BMS_CellBalaStNo74;
		BMS_CellBalaStNo75 = _x.BMS_CellBalaStNo75;
		BMS_CellBalaStNo76 = _x.BMS_CellBalaStNo76;
		BMS_CellBalaStNo77 = _x.BMS_CellBalaStNo77;
		BMS_CellBalaStNo78 = _x.BMS_CellBalaStNo78;
		BMS_CellBalaStNo79 = _x.BMS_CellBalaStNo79;
		BMS_CellBalaStNo80 = _x.BMS_CellBalaStNo80;
		BMS_CellBalaStNo81 = _x.BMS_CellBalaStNo81;
		BMS_CellBalaStNo82 = _x.BMS_CellBalaStNo82;
		BMS_CellBalaStNo83 = _x.BMS_CellBalaStNo83;
		BMS_CellBalaStNo84 = _x.BMS_CellBalaStNo84;
		BMS_CellBalaStNo85 = _x.BMS_CellBalaStNo85;
		BMS_CellBalaStNo86 = _x.BMS_CellBalaStNo86;
		BMS_CellBalaStNo87 = _x.BMS_CellBalaStNo87;
		BMS_CellBalaStNo88 = _x.BMS_CellBalaStNo88;
		BMS_CellBalaStNo89 = _x.BMS_CellBalaStNo89;
		BMS_CellBalaStNo90 = _x.BMS_CellBalaStNo90;
		BMS_CellBalaStNo91 = _x.BMS_CellBalaStNo91;
		BMS_CellBalaStNo92 = _x.BMS_CellBalaStNo92;
		BMS_CellBalaStNo93 = _x.BMS_CellBalaStNo93;
		BMS_CellBalaStNo94 = _x.BMS_CellBalaStNo94;
		BMS_CellBalaStNo95 = _x.BMS_CellBalaStNo95;
		BMS_CellBalaStNo96 = _x.BMS_CellBalaStNo96;
		return *this;
	}
	BDCTestBMS5& operator=(BDCTestBMS5 &&_x){
		BMS_BusBarIns1 = std::move(_x.BMS_BusBarIns1);
		BMS_BusBarIns2 = std::move(_x.BMS_BusBarIns2);
		BMS_BusBarIns3 = std::move(_x.BMS_BusBarIns3);
		BMS_ProbeTempNo1 = std::move(_x.BMS_ProbeTempNo1);
		BMS_ProbeTempNo2 = std::move(_x.BMS_ProbeTempNo2);
		BMS_ProbeTempNo3 = std::move(_x.BMS_ProbeTempNo3);
		BMS_ProbeTempNo4 = std::move(_x.BMS_ProbeTempNo4);
		BMS_ProbeTempNo5 = std::move(_x.BMS_ProbeTempNo5);
		BMS_ProbeTempNo6 = std::move(_x.BMS_ProbeTempNo6);
		BMS_ProbeTempNo7 = std::move(_x.BMS_ProbeTempNo7);
		BMS_ProbeTempNo8 = std::move(_x.BMS_ProbeTempNo8);
		BMS_CellBalaStNo1 = std::move(_x.BMS_CellBalaStNo1);
		BMS_CellBalaStNo2 = std::move(_x.BMS_CellBalaStNo2);
		BMS_CellBalaStNo3 = std::move(_x.BMS_CellBalaStNo3);
		BMS_CellBalaStNo4 = std::move(_x.BMS_CellBalaStNo4);
		BMS_CellBalaStNo5 = std::move(_x.BMS_CellBalaStNo5);
		BMS_CellBalaStNo6 = std::move(_x.BMS_CellBalaStNo6);
		BMS_CellBalaStNo7 = std::move(_x.BMS_CellBalaStNo7);
		BMS_CellBalaStNo8 = std::move(_x.BMS_CellBalaStNo8);
		BMS_CellBalaStNo9 = std::move(_x.BMS_CellBalaStNo9);
		BMS_CellBalaStNo10 = std::move(_x.BMS_CellBalaStNo10);
		BMS_CellBalaStNo11 = std::move(_x.BMS_CellBalaStNo11);
		BMS_CellBalaStNo12 = std::move(_x.BMS_CellBalaStNo12);
		BMS_CellBalaStNo13 = std::move(_x.BMS_CellBalaStNo13);
		BMS_CellBalaStNo14 = std::move(_x.BMS_CellBalaStNo14);
		BMS_CellBalaStNo15 = std::move(_x.BMS_CellBalaStNo15);
		BMS_CellBalaStNo16 = std::move(_x.BMS_CellBalaStNo16);
		BMS_CellBalaStNo17 = std::move(_x.BMS_CellBalaStNo17);
		BMS_CellBalaStNo18 = std::move(_x.BMS_CellBalaStNo18);
		BMS_CellBalaStNo19 = std::move(_x.BMS_CellBalaStNo19);
		BMS_CellBalaStNo20 = std::move(_x.BMS_CellBalaStNo20);
		BMS_CellBalaStNo21 = std::move(_x.BMS_CellBalaStNo21);
		BMS_CellBalaStNo22 = std::move(_x.BMS_CellBalaStNo22);
		BMS_CellBalaStNo23 = std::move(_x.BMS_CellBalaStNo23);
		BMS_CellBalaStNo24 = std::move(_x.BMS_CellBalaStNo24);
		BMS_CellBalaStNo25 = std::move(_x.BMS_CellBalaStNo25);
		BMS_CellBalaStNo26 = std::move(_x.BMS_CellBalaStNo26);
		BMS_CellBalaStNo27 = std::move(_x.BMS_CellBalaStNo27);
		BMS_CellBalaStNo28 = std::move(_x.BMS_CellBalaStNo28);
		BMS_CellBalaStNo29 = std::move(_x.BMS_CellBalaStNo29);
		BMS_CellBalaStNo30 = std::move(_x.BMS_CellBalaStNo30);
		BMS_CellBalaStNo31 = std::move(_x.BMS_CellBalaStNo31);
		BMS_CellBalaStNo32 = std::move(_x.BMS_CellBalaStNo32);
		BMS_CellBalaStNo33 = std::move(_x.BMS_CellBalaStNo33);
		BMS_CellBalaStNo34 = std::move(_x.BMS_CellBalaStNo34);
		BMS_CellBalaStNo35 = std::move(_x.BMS_CellBalaStNo35);
		BMS_CellBalaStNo36 = std::move(_x.BMS_CellBalaStNo36);
		BMS_CellBalaStNo37 = std::move(_x.BMS_CellBalaStNo37);
		BMS_CellBalaStNo38 = std::move(_x.BMS_CellBalaStNo38);
		BMS_CellBalaStNo39 = std::move(_x.BMS_CellBalaStNo39);
		BMS_CellBalaStNo40 = std::move(_x.BMS_CellBalaStNo40);
		BMS_CellBalaStNo41 = std::move(_x.BMS_CellBalaStNo41);
		BMS_CellBalaStNo42 = std::move(_x.BMS_CellBalaStNo42);
		BMS_CellBalaStNo43 = std::move(_x.BMS_CellBalaStNo43);
		BMS_CellBalaStNo44 = std::move(_x.BMS_CellBalaStNo44);
		BMS_CellBalaStNo45 = std::move(_x.BMS_CellBalaStNo45);
		BMS_CellBalaStNo46 = std::move(_x.BMS_CellBalaStNo46);
		BMS_CellBalaStNo47 = std::move(_x.BMS_CellBalaStNo47);
		BMS_CellBalaStNo48 = std::move(_x.BMS_CellBalaStNo48);
		BMS_CellBalaStNo49 = std::move(_x.BMS_CellBalaStNo49);
		BMS_CellBalaStNo50 = std::move(_x.BMS_CellBalaStNo50);
		BMS_CellBalaStNo51 = std::move(_x.BMS_CellBalaStNo51);
		BMS_CellBalaStNo52 = std::move(_x.BMS_CellBalaStNo52);
		BMS_CellBalaStNo53 = std::move(_x.BMS_CellBalaStNo53);
		BMS_CellBalaStNo54 = std::move(_x.BMS_CellBalaStNo54);
		BMS_CellBalaStNo55 = std::move(_x.BMS_CellBalaStNo55);
		BMS_CellBalaStNo56 = std::move(_x.BMS_CellBalaStNo56);
		BMS_CellBalaStNo57 = std::move(_x.BMS_CellBalaStNo57);
		BMS_CellBalaStNo58 = std::move(_x.BMS_CellBalaStNo58);
		BMS_CellBalaStNo59 = std::move(_x.BMS_CellBalaStNo59);
		BMS_CellBalaStNo60 = std::move(_x.BMS_CellBalaStNo60);
		BMS_CellBalaStNo61 = std::move(_x.BMS_CellBalaStNo61);
		BMS_CellBalaStNo62 = std::move(_x.BMS_CellBalaStNo62);
		BMS_CellBalaStNo63 = std::move(_x.BMS_CellBalaStNo63);
		BMS_CellBalaStNo64 = std::move(_x.BMS_CellBalaStNo64);
		BMS_CellBalaStNo65 = std::move(_x.BMS_CellBalaStNo65);
		BMS_CellBalaStNo66 = std::move(_x.BMS_CellBalaStNo66);
		BMS_CellBalaStNo67 = std::move(_x.BMS_CellBalaStNo67);
		BMS_CellBalaStNo68 = std::move(_x.BMS_CellBalaStNo68);
		BMS_CellBalaStNo69 = std::move(_x.BMS_CellBalaStNo69);
		BMS_CellBalaStNo70 = std::move(_x.BMS_CellBalaStNo70);
		BMS_CellBalaStNo71 = std::move(_x.BMS_CellBalaStNo71);
		BMS_CellBalaStNo72 = std::move(_x.BMS_CellBalaStNo72);
		BMS_CellBalaStNo73 = std::move(_x.BMS_CellBalaStNo73);
		BMS_CellBalaStNo74 = std::move(_x.BMS_CellBalaStNo74);
		BMS_CellBalaStNo75 = std::move(_x.BMS_CellBalaStNo75);
		BMS_CellBalaStNo76 = std::move(_x.BMS_CellBalaStNo76);
		BMS_CellBalaStNo77 = std::move(_x.BMS_CellBalaStNo77);
		BMS_CellBalaStNo78 = std::move(_x.BMS_CellBalaStNo78);
		BMS_CellBalaStNo79 = std::move(_x.BMS_CellBalaStNo79);
		BMS_CellBalaStNo80 = std::move(_x.BMS_CellBalaStNo80);
		BMS_CellBalaStNo81 = std::move(_x.BMS_CellBalaStNo81);
		BMS_CellBalaStNo82 = std::move(_x.BMS_CellBalaStNo82);
		BMS_CellBalaStNo83 = std::move(_x.BMS_CellBalaStNo83);
		BMS_CellBalaStNo84 = std::move(_x.BMS_CellBalaStNo84);
		BMS_CellBalaStNo85 = std::move(_x.BMS_CellBalaStNo85);
		BMS_CellBalaStNo86 = std::move(_x.BMS_CellBalaStNo86);
		BMS_CellBalaStNo87 = std::move(_x.BMS_CellBalaStNo87);
		BMS_CellBalaStNo88 = std::move(_x.BMS_CellBalaStNo88);
		BMS_CellBalaStNo89 = std::move(_x.BMS_CellBalaStNo89);
		BMS_CellBalaStNo90 = std::move(_x.BMS_CellBalaStNo90);
		BMS_CellBalaStNo91 = std::move(_x.BMS_CellBalaStNo91);
		BMS_CellBalaStNo92 = std::move(_x.BMS_CellBalaStNo92);
		BMS_CellBalaStNo93 = std::move(_x.BMS_CellBalaStNo93);
		BMS_CellBalaStNo94 = std::move(_x.BMS_CellBalaStNo94);
		BMS_CellBalaStNo95 = std::move(_x.BMS_CellBalaStNo95);
		BMS_CellBalaStNo96 = std::move(_x.BMS_CellBalaStNo96);
		return *this;
	}
*/

	using IsEnumerableTag = void;
	template<typename F>
	void enumerate(F& fun) {
		fun(BMS_BusBarIns1);
		fun(BMS_BusBarIns2);
		fun(BMS_BusBarIns3);
		fun(BMS_ProbeTempNo1);
		fun(BMS_ProbeTempNo2);
		fun(BMS_ProbeTempNo3);
		fun(BMS_ProbeTempNo4);
		fun(BMS_ProbeTempNo5);
		fun(BMS_ProbeTempNo6);
		fun(BMS_ProbeTempNo7);
		fun(BMS_ProbeTempNo8);
		fun(BMS_CellBalaStNo1);
		fun(BMS_CellBalaStNo2);
		fun(BMS_CellBalaStNo3);
		fun(BMS_CellBalaStNo4);
		fun(BMS_CellBalaStNo5);
		fun(BMS_CellBalaStNo6);
		fun(BMS_CellBalaStNo7);
		fun(BMS_CellBalaStNo8);
		fun(BMS_CellBalaStNo9);
		fun(BMS_CellBalaStNo10);
		fun(BMS_CellBalaStNo11);
		fun(BMS_CellBalaStNo12);
		fun(BMS_CellBalaStNo13);
		fun(BMS_CellBalaStNo14);
		fun(BMS_CellBalaStNo15);
		fun(BMS_CellBalaStNo16);
		fun(BMS_CellBalaStNo17);
		fun(BMS_CellBalaStNo18);
		fun(BMS_CellBalaStNo19);
		fun(BMS_CellBalaStNo20);
		fun(BMS_CellBalaStNo21);
		fun(BMS_CellBalaStNo22);
		fun(BMS_CellBalaStNo23);
		fun(BMS_CellBalaStNo24);
		fun(BMS_CellBalaStNo25);
		fun(BMS_CellBalaStNo26);
		fun(BMS_CellBalaStNo27);
		fun(BMS_CellBalaStNo28);
		fun(BMS_CellBalaStNo29);
		fun(BMS_CellBalaStNo30);
		fun(BMS_CellBalaStNo31);
		fun(BMS_CellBalaStNo32);
		fun(BMS_CellBalaStNo33);
		fun(BMS_CellBalaStNo34);
		fun(BMS_CellBalaStNo35);
		fun(BMS_CellBalaStNo36);
		fun(BMS_CellBalaStNo37);
		fun(BMS_CellBalaStNo38);
		fun(BMS_CellBalaStNo39);
		fun(BMS_CellBalaStNo40);
		fun(BMS_CellBalaStNo41);
		fun(BMS_CellBalaStNo42);
		fun(BMS_CellBalaStNo43);
		fun(BMS_CellBalaStNo44);
		fun(BMS_CellBalaStNo45);
		fun(BMS_CellBalaStNo46);
		fun(BMS_CellBalaStNo47);
		fun(BMS_CellBalaStNo48);
		fun(BMS_CellBalaStNo49);
		fun(BMS_CellBalaStNo50);
		fun(BMS_CellBalaStNo51);
		fun(BMS_CellBalaStNo52);
		fun(BMS_CellBalaStNo53);
		fun(BMS_CellBalaStNo54);
		fun(BMS_CellBalaStNo55);
		fun(BMS_CellBalaStNo56);
		fun(BMS_CellBalaStNo57);
		fun(BMS_CellBalaStNo58);
		fun(BMS_CellBalaStNo59);
		fun(BMS_CellBalaStNo60);
		fun(BMS_CellBalaStNo61);
		fun(BMS_CellBalaStNo62);
		fun(BMS_CellBalaStNo63);
		fun(BMS_CellBalaStNo64);
		fun(BMS_CellBalaStNo65);
		fun(BMS_CellBalaStNo66);
		fun(BMS_CellBalaStNo67);
		fun(BMS_CellBalaStNo68);
		fun(BMS_CellBalaStNo69);
		fun(BMS_CellBalaStNo70);
		fun(BMS_CellBalaStNo71);
		fun(BMS_CellBalaStNo72);
		fun(BMS_CellBalaStNo73);
		fun(BMS_CellBalaStNo74);
		fun(BMS_CellBalaStNo75);
		fun(BMS_CellBalaStNo76);
		fun(BMS_CellBalaStNo77);
		fun(BMS_CellBalaStNo78);
		fun(BMS_CellBalaStNo79);
		fun(BMS_CellBalaStNo80);
		fun(BMS_CellBalaStNo81);
		fun(BMS_CellBalaStNo82);
		fun(BMS_CellBalaStNo83);
		fun(BMS_CellBalaStNo84);
		fun(BMS_CellBalaStNo85);
		fun(BMS_CellBalaStNo86);
		fun(BMS_CellBalaStNo87);
		fun(BMS_CellBalaStNo88);
		fun(BMS_CellBalaStNo89);
		fun(BMS_CellBalaStNo90);
		fun(BMS_CellBalaStNo91);
		fun(BMS_CellBalaStNo92);
		fun(BMS_CellBalaStNo93);
		fun(BMS_CellBalaStNo94);
		fun(BMS_CellBalaStNo95);
		fun(BMS_CellBalaStNo96);
	}

	template<typename F>
	void GetSize(F& fun) const{
		fun(BMS_BusBarIns1);
		fun(BMS_BusBarIns2);
		fun(BMS_BusBarIns3);
		fun(BMS_ProbeTempNo1);
		fun(BMS_ProbeTempNo2);
		fun(BMS_ProbeTempNo3);
		fun(BMS_ProbeTempNo4);
		fun(BMS_ProbeTempNo5);
		fun(BMS_ProbeTempNo6);
		fun(BMS_ProbeTempNo7);
		fun(BMS_ProbeTempNo8);
		fun(BMS_CellBalaStNo1);
		fun(BMS_CellBalaStNo2);
		fun(BMS_CellBalaStNo3);
		fun(BMS_CellBalaStNo4);
		fun(BMS_CellBalaStNo5);
		fun(BMS_CellBalaStNo6);
		fun(BMS_CellBalaStNo7);
		fun(BMS_CellBalaStNo8);
		fun(BMS_CellBalaStNo9);
		fun(BMS_CellBalaStNo10);
		fun(BMS_CellBalaStNo11);
		fun(BMS_CellBalaStNo12);
		fun(BMS_CellBalaStNo13);
		fun(BMS_CellBalaStNo14);
		fun(BMS_CellBalaStNo15);
		fun(BMS_CellBalaStNo16);
		fun(BMS_CellBalaStNo17);
		fun(BMS_CellBalaStNo18);
		fun(BMS_CellBalaStNo19);
		fun(BMS_CellBalaStNo20);
		fun(BMS_CellBalaStNo21);
		fun(BMS_CellBalaStNo22);
		fun(BMS_CellBalaStNo23);
		fun(BMS_CellBalaStNo24);
		fun(BMS_CellBalaStNo25);
		fun(BMS_CellBalaStNo26);
		fun(BMS_CellBalaStNo27);
		fun(BMS_CellBalaStNo28);
		fun(BMS_CellBalaStNo29);
		fun(BMS_CellBalaStNo30);
		fun(BMS_CellBalaStNo31);
		fun(BMS_CellBalaStNo32);
		fun(BMS_CellBalaStNo33);
		fun(BMS_CellBalaStNo34);
		fun(BMS_CellBalaStNo35);
		fun(BMS_CellBalaStNo36);
		fun(BMS_CellBalaStNo37);
		fun(BMS_CellBalaStNo38);
		fun(BMS_CellBalaStNo39);
		fun(BMS_CellBalaStNo40);
		fun(BMS_CellBalaStNo41);
		fun(BMS_CellBalaStNo42);
		fun(BMS_CellBalaStNo43);
		fun(BMS_CellBalaStNo44);
		fun(BMS_CellBalaStNo45);
		fun(BMS_CellBalaStNo46);
		fun(BMS_CellBalaStNo47);
		fun(BMS_CellBalaStNo48);
		fun(BMS_CellBalaStNo49);
		fun(BMS_CellBalaStNo50);
		fun(BMS_CellBalaStNo51);
		fun(BMS_CellBalaStNo52);
		fun(BMS_CellBalaStNo53);
		fun(BMS_CellBalaStNo54);
		fun(BMS_CellBalaStNo55);
		fun(BMS_CellBalaStNo56);
		fun(BMS_CellBalaStNo57);
		fun(BMS_CellBalaStNo58);
		fun(BMS_CellBalaStNo59);
		fun(BMS_CellBalaStNo60);
		fun(BMS_CellBalaStNo61);
		fun(BMS_CellBalaStNo62);
		fun(BMS_CellBalaStNo63);
		fun(BMS_CellBalaStNo64);
		fun(BMS_CellBalaStNo65);
		fun(BMS_CellBalaStNo66);
		fun(BMS_CellBalaStNo67);
		fun(BMS_CellBalaStNo68);
		fun(BMS_CellBalaStNo69);
		fun(BMS_CellBalaStNo70);
		fun(BMS_CellBalaStNo71);
		fun(BMS_CellBalaStNo72);
		fun(BMS_CellBalaStNo73);
		fun(BMS_CellBalaStNo74);
		fun(BMS_CellBalaStNo75);
		fun(BMS_CellBalaStNo76);
		fun(BMS_CellBalaStNo77);
		fun(BMS_CellBalaStNo78);
		fun(BMS_CellBalaStNo79);
		fun(BMS_CellBalaStNo80);
		fun(BMS_CellBalaStNo81);
		fun(BMS_CellBalaStNo82);
		fun(BMS_CellBalaStNo83);
		fun(BMS_CellBalaStNo84);
		fun(BMS_CellBalaStNo85);
		fun(BMS_CellBalaStNo86);
		fun(BMS_CellBalaStNo87);
		fun(BMS_CellBalaStNo88);
		fun(BMS_CellBalaStNo89);
		fun(BMS_CellBalaStNo90);
		fun(BMS_CellBalaStNo91);
		fun(BMS_CellBalaStNo92);
		fun(BMS_CellBalaStNo93);
		fun(BMS_CellBalaStNo94);
		fun(BMS_CellBalaStNo95);
		fun(BMS_CellBalaStNo96);
	}
	template<typename F>
	void serialize(F& fun) const{
		fun << (BMS_BusBarIns1);
		fun << (BMS_BusBarIns2);
		fun << (BMS_BusBarIns3);
		fun << (BMS_ProbeTempNo1);
		fun << (BMS_ProbeTempNo2);
		fun << (BMS_ProbeTempNo3);
		fun << (BMS_ProbeTempNo4);
		fun << (BMS_ProbeTempNo5);
		fun << (BMS_ProbeTempNo6);
		fun << (BMS_ProbeTempNo7);
		fun << (BMS_ProbeTempNo8);
		fun << (BMS_CellBalaStNo1);
		fun << (BMS_CellBalaStNo2);
		fun << (BMS_CellBalaStNo3);
		fun << (BMS_CellBalaStNo4);
		fun << (BMS_CellBalaStNo5);
		fun << (BMS_CellBalaStNo6);
		fun << (BMS_CellBalaStNo7);
		fun << (BMS_CellBalaStNo8);
		fun << (BMS_CellBalaStNo9);
		fun << (BMS_CellBalaStNo10);
		fun << (BMS_CellBalaStNo11);
		fun << (BMS_CellBalaStNo12);
		fun << (BMS_CellBalaStNo13);
		fun << (BMS_CellBalaStNo14);
		fun << (BMS_CellBalaStNo15);
		fun << (BMS_CellBalaStNo16);
		fun << (BMS_CellBalaStNo17);
		fun << (BMS_CellBalaStNo18);
		fun << (BMS_CellBalaStNo19);
		fun << (BMS_CellBalaStNo20);
		fun << (BMS_CellBalaStNo21);
		fun << (BMS_CellBalaStNo22);
		fun << (BMS_CellBalaStNo23);
		fun << (BMS_CellBalaStNo24);
		fun << (BMS_CellBalaStNo25);
		fun << (BMS_CellBalaStNo26);
		fun << (BMS_CellBalaStNo27);
		fun << (BMS_CellBalaStNo28);
		fun << (BMS_CellBalaStNo29);
		fun << (BMS_CellBalaStNo30);
		fun << (BMS_CellBalaStNo31);
		fun << (BMS_CellBalaStNo32);
		fun << (BMS_CellBalaStNo33);
		fun << (BMS_CellBalaStNo34);
		fun << (BMS_CellBalaStNo35);
		fun << (BMS_CellBalaStNo36);
		fun << (BMS_CellBalaStNo37);
		fun << (BMS_CellBalaStNo38);
		fun << (BMS_CellBalaStNo39);
		fun << (BMS_CellBalaStNo40);
		fun << (BMS_CellBalaStNo41);
		fun << (BMS_CellBalaStNo42);
		fun << (BMS_CellBalaStNo43);
		fun << (BMS_CellBalaStNo44);
		fun << (BMS_CellBalaStNo45);
		fun << (BMS_CellBalaStNo46);
		fun << (BMS_CellBalaStNo47);
		fun << (BMS_CellBalaStNo48);
		fun << (BMS_CellBalaStNo49);
		fun << (BMS_CellBalaStNo50);
		fun << (BMS_CellBalaStNo51);
		fun << (BMS_CellBalaStNo52);
		fun << (BMS_CellBalaStNo53);
		fun << (BMS_CellBalaStNo54);
		fun << (BMS_CellBalaStNo55);
		fun << (BMS_CellBalaStNo56);
		fun << (BMS_CellBalaStNo57);
		fun << (BMS_CellBalaStNo58);
		fun << (BMS_CellBalaStNo59);
		fun << (BMS_CellBalaStNo60);
		fun << (BMS_CellBalaStNo61);
		fun << (BMS_CellBalaStNo62);
		fun << (BMS_CellBalaStNo63);
		fun << (BMS_CellBalaStNo64);
		fun << (BMS_CellBalaStNo65);
		fun << (BMS_CellBalaStNo66);
		fun << (BMS_CellBalaStNo67);
		fun << (BMS_CellBalaStNo68);
		fun << (BMS_CellBalaStNo69);
		fun << (BMS_CellBalaStNo70);
		fun << (BMS_CellBalaStNo71);
		fun << (BMS_CellBalaStNo72);
		fun << (BMS_CellBalaStNo73);
		fun << (BMS_CellBalaStNo74);
		fun << (BMS_CellBalaStNo75);
		fun << (BMS_CellBalaStNo76);
		fun << (BMS_CellBalaStNo77);
		fun << (BMS_CellBalaStNo78);
		fun << (BMS_CellBalaStNo79);
		fun << (BMS_CellBalaStNo80);
		fun << (BMS_CellBalaStNo81);
		fun << (BMS_CellBalaStNo82);
		fun << (BMS_CellBalaStNo83);
		fun << (BMS_CellBalaStNo84);
		fun << (BMS_CellBalaStNo85);
		fun << (BMS_CellBalaStNo86);
		fun << (BMS_CellBalaStNo87);
		fun << (BMS_CellBalaStNo88);
		fun << (BMS_CellBalaStNo89);
		fun << (BMS_CellBalaStNo90);
		fun << (BMS_CellBalaStNo91);
		fun << (BMS_CellBalaStNo92);
		fun << (BMS_CellBalaStNo93);
		fun << (BMS_CellBalaStNo94);
		fun << (BMS_CellBalaStNo95);
		fun << (BMS_CellBalaStNo96);
	}
	template<typename F>
	void deserialize(F& fun){
		fun >> (BMS_BusBarIns1);
		fun >> (BMS_BusBarIns2);
		fun >> (BMS_BusBarIns3);
		fun >> (BMS_ProbeTempNo1);
		fun >> (BMS_ProbeTempNo2);
		fun >> (BMS_ProbeTempNo3);
		fun >> (BMS_ProbeTempNo4);
		fun >> (BMS_ProbeTempNo5);
		fun >> (BMS_ProbeTempNo6);
		fun >> (BMS_ProbeTempNo7);
		fun >> (BMS_ProbeTempNo8);
		fun >> (BMS_CellBalaStNo1);
		fun >> (BMS_CellBalaStNo2);
		fun >> (BMS_CellBalaStNo3);
		fun >> (BMS_CellBalaStNo4);
		fun >> (BMS_CellBalaStNo5);
		fun >> (BMS_CellBalaStNo6);
		fun >> (BMS_CellBalaStNo7);
		fun >> (BMS_CellBalaStNo8);
		fun >> (BMS_CellBalaStNo9);
		fun >> (BMS_CellBalaStNo10);
		fun >> (BMS_CellBalaStNo11);
		fun >> (BMS_CellBalaStNo12);
		fun >> (BMS_CellBalaStNo13);
		fun >> (BMS_CellBalaStNo14);
		fun >> (BMS_CellBalaStNo15);
		fun >> (BMS_CellBalaStNo16);
		fun >> (BMS_CellBalaStNo17);
		fun >> (BMS_CellBalaStNo18);
		fun >> (BMS_CellBalaStNo19);
		fun >> (BMS_CellBalaStNo20);
		fun >> (BMS_CellBalaStNo21);
		fun >> (BMS_CellBalaStNo22);
		fun >> (BMS_CellBalaStNo23);
		fun >> (BMS_CellBalaStNo24);
		fun >> (BMS_CellBalaStNo25);
		fun >> (BMS_CellBalaStNo26);
		fun >> (BMS_CellBalaStNo27);
		fun >> (BMS_CellBalaStNo28);
		fun >> (BMS_CellBalaStNo29);
		fun >> (BMS_CellBalaStNo30);
		fun >> (BMS_CellBalaStNo31);
		fun >> (BMS_CellBalaStNo32);
		fun >> (BMS_CellBalaStNo33);
		fun >> (BMS_CellBalaStNo34);
		fun >> (BMS_CellBalaStNo35);
		fun >> (BMS_CellBalaStNo36);
		fun >> (BMS_CellBalaStNo37);
		fun >> (BMS_CellBalaStNo38);
		fun >> (BMS_CellBalaStNo39);
		fun >> (BMS_CellBalaStNo40);
		fun >> (BMS_CellBalaStNo41);
		fun >> (BMS_CellBalaStNo42);
		fun >> (BMS_CellBalaStNo43);
		fun >> (BMS_CellBalaStNo44);
		fun >> (BMS_CellBalaStNo45);
		fun >> (BMS_CellBalaStNo46);
		fun >> (BMS_CellBalaStNo47);
		fun >> (BMS_CellBalaStNo48);
		fun >> (BMS_CellBalaStNo49);
		fun >> (BMS_CellBalaStNo50);
		fun >> (BMS_CellBalaStNo51);
		fun >> (BMS_CellBalaStNo52);
		fun >> (BMS_CellBalaStNo53);
		fun >> (BMS_CellBalaStNo54);
		fun >> (BMS_CellBalaStNo55);
		fun >> (BMS_CellBalaStNo56);
		fun >> (BMS_CellBalaStNo57);
		fun >> (BMS_CellBalaStNo58);
		fun >> (BMS_CellBalaStNo59);
		fun >> (BMS_CellBalaStNo60);
		fun >> (BMS_CellBalaStNo61);
		fun >> (BMS_CellBalaStNo62);
		fun >> (BMS_CellBalaStNo63);
		fun >> (BMS_CellBalaStNo64);
		fun >> (BMS_CellBalaStNo65);
		fun >> (BMS_CellBalaStNo66);
		fun >> (BMS_CellBalaStNo67);
		fun >> (BMS_CellBalaStNo68);
		fun >> (BMS_CellBalaStNo69);
		fun >> (BMS_CellBalaStNo70);
		fun >> (BMS_CellBalaStNo71);
		fun >> (BMS_CellBalaStNo72);
		fun >> (BMS_CellBalaStNo73);
		fun >> (BMS_CellBalaStNo74);
		fun >> (BMS_CellBalaStNo75);
		fun >> (BMS_CellBalaStNo76);
		fun >> (BMS_CellBalaStNo77);
		fun >> (BMS_CellBalaStNo78);
		fun >> (BMS_CellBalaStNo79);
		fun >> (BMS_CellBalaStNo80);
		fun >> (BMS_CellBalaStNo81);
		fun >> (BMS_CellBalaStNo82);
		fun >> (BMS_CellBalaStNo83);
		fun >> (BMS_CellBalaStNo84);
		fun >> (BMS_CellBalaStNo85);
		fun >> (BMS_CellBalaStNo86);
		fun >> (BMS_CellBalaStNo87);
		fun >> (BMS_CellBalaStNo88);
		fun >> (BMS_CellBalaStNo89);
		fun >> (BMS_CellBalaStNo90);
		fun >> (BMS_CellBalaStNo91);
		fun >> (BMS_CellBalaStNo92);
		fun >> (BMS_CellBalaStNo93);
		fun >> (BMS_CellBalaStNo94);
		fun >> (BMS_CellBalaStNo95);
		fun >> (BMS_CellBalaStNo96);
	}
};

#endif //____BDCTESTBMS5_H__
