#ifndef ____BDCCLOUD1_H__
#define ____BDCCLOUD1_H__


#include "cstdint"






struct BDCCLOUD1 {
public:
	std::uint8_t LCK_FrontLeftDoorAjarSt;
	std::uint8_t LCK_FrontRightDoorAjarSt;
	std::uint8_t LCK_RearLeftDoorAjarSt;
	std::uint8_t LCK_RearRightDoorAjarSt;
	std::uint8_t LCK_TrunkAjarSt;
	std::uint8_t LCK_HoodAjarSt;
	std::uint8_t LCK_DriverDoorLockSt;
	std::uint8_t LCK_PassengerDoorLockSt;
	std::uint8_t LCK_RearLeftDoorLockSt;
	std::uint8_t LCK_RearRightDoorLockSt;
	std::uint8_t PWL_FLWinCurrentPst;
	std::uint8_t PWL_FRWinCurrentPst;
	std::uint8_t PWL_RLWinCurrentPst;
	std::uint8_t PWL_RRWinCurrentPst;
	std::uint64_t RC_SunroofOperationSt;
	std::uint8_t TPMS_FrontLeftTirePressure;
	std::uint8_t TPMS_FrontRightTirePressure;
	std::uint8_t TPMS_RearLeftTirePressure;
	std::uint8_t TPMS_RearRightTirePressure;
	std::uint8_t TPMS_FrontLeftTireTemperature;
	std::uint8_t TPMS_FrontRightTireTemperature;
	std::uint8_t TPMS_RearRightTireTemperature;
	std::uint8_t TPMS_RearLeftTireTemperature;
	std::uint8_t TPMS_FrontLeftTireLowPressure;
	std::uint8_t TPMS_FrontRightTireLowPressure;
	std::uint8_t TPMS_RearRightTireLowPressure;
	std::uint8_t TPMS_RearLeftTireLowPressure;
	std::uint8_t TPMS_FrontLeftTireHighPressure;
	std::uint8_t TPMS_FrontRightTireHighPressure;
	std::uint8_t TPMS_RearRightTireHighPressure;
	std::uint8_t TPMS_RearLeftTireHighPressure;
	std::uint8_t TPMS_FrontLeftTireHighTemperature;
	std::uint8_t TPMS_FrontRightTireHighTemperature;
	std::uint8_t TPMS_RearRightTireHighTemperature;
	std::uint8_t TPMS_RearLeftTireHighTemperature;
	std::uint16_t EBSF_BattVolt;
	std::uint8_t EBSF_SOC;
	std::uint8_t EBSF_VoltSt;
	std::uint8_t ICM_BFLWarning;
	std::uint16_t VCU_DspChgCurr;
	std::uint16_t VCU_DspChgVolt;
	std::uint8_t BMS_ChgComplRemHour;
	std::uint8_t BMS_ChgComplRemMinute;
	std::uint32_t ICM_TotalOdometer;
	std::uint16_t BMS_BattSocDisp;
	std::uint32_t ICM_TotalOdometer_accurate;
	std::uint16_t VCU_VehRng;
	std::uint16_t VCU_EVRng;
	std::uint16_t HVAC_RAWCabinTemp;
	std::uint16_t AQM_PM25Data;
	std::uint8_t HVAC_DriverTempSelect;
	std::uint8_t HVAC_PsnTempSelect;
	std::uint8_t HVAC_WindExitSpd;
	std::uint8_t HVAC_ACSt;
	std::uint8_t UMM_UsageModeSt;
	std::uint8_t SSW_FLSeatVentSt;
	std::uint8_t SSW_FRSeatVentSt;
	std::uint8_t SSW_RLSeatVentSt;
	std::uint8_t SSW_RRSeatVentSt;
	std::uint8_t SSW_FLSeatHeatingSt;
	std::uint8_t SSW_FRSeatHeatingSt;
	std::uint64_t SSW_RLSeatHeatingSt;
	std::uint64_t SSW_RRSeatHeatingSt;
	std::uint8_t HRN_HornRunningSt;
	std::uint8_t IL_HazardIndLightOutputSt;
	std::uint16_t BCS_VehSpd;
	std::uint16_t VCU_DspDischgCurr;
	std::uint16_t VCU_DspDischgVolt;
	std::uint8_t PWL_WinCurrentPos_FLWinPst;
	std::uint8_t PWL_WinOpeationSt_FLWinSt;
	std::uint8_t PWL_WinCurrentPos_RLWinPst;
	std::uint8_t PWL_WinCurrentPos_RRWinPst;
	std::uint8_t PWL_WinOpeationSt_RLWinSt;
	std::uint8_t PWL_WinOpeationSt_RRWinSt;
	std::uint8_t PWL_WinCurrentPos_FRWinPst;
	std::uint8_t PWL_WinOpeationSt_FRWinSt;
/*
	BDCCLOUD1() {}
	~BDCCLOUD1() {}
	BDCCLOUD1(const std::uint8_t _LCK_FrontLeftDoorAjarSt,const std::uint8_t _LCK_FrontRightDoorAjarSt,const std::uint8_t _LCK_RearLeftDoorAjarSt,const std::uint8_t _LCK_RearRightDoorAjarSt,const std::uint8_t _LCK_TrunkAjarSt,const std::uint8_t _LCK_HoodAjarSt,const std::uint8_t _LCK_DriverDoorLockSt,const std::uint8_t _LCK_PassengerDoorLockSt,const std::uint8_t _LCK_RearLeftDoorLockSt,const std::uint8_t _LCK_RearRightDoorLockSt,const std::uint8_t _PWL_FLWinCurrentPst,const std::uint8_t _PWL_FRWinCurrentPst,const std::uint8_t _PWL_RLWinCurrentPst,const std::uint8_t _PWL_RRWinCurrentPst,const std::uint64_t _RC_SunroofOperationSt,const std::uint8_t _TPMS_FrontLeftTirePressure,const std::uint8_t _TPMS_FrontRightTirePressure,const std::uint8_t _TPMS_RearLeftTirePressure,const std::uint8_t _TPMS_RearRightTirePressure,const std::uint8_t _TPMS_FrontLeftTireTemperature,const std::uint8_t _TPMS_FrontRightTireTemperature,const std::uint8_t _TPMS_RearRightTireTemperature,const std::uint8_t _TPMS_RearLeftTireTemperature,const std::uint8_t _TPMS_FrontLeftTireLowPressure,const std::uint8_t _TPMS_FrontRightTireLowPressure,const std::uint8_t _TPMS_RearRightTireLowPressure,const std::uint8_t _TPMS_RearLeftTireLowPressure,const std::uint8_t _TPMS_FrontLeftTireHighPressure,const std::uint8_t _TPMS_FrontRightTireHighPressure,const std::uint8_t _TPMS_RearRightTireHighPressure,const std::uint8_t _TPMS_RearLeftTireHighPressure,const std::uint8_t _TPMS_FrontLeftTireHighTemperature,const std::uint8_t _TPMS_FrontRightTireHighTemperature,const std::uint8_t _TPMS_RearRightTireHighTemperature,const std::uint8_t _TPMS_RearLeftTireHighTemperature,const std::uint16_t _EBSF_BattVolt,const std::uint8_t _EBSF_SOC,const std::uint8_t _EBSF_VoltSt,const std::uint8_t _ICM_BFLWarning,const std::uint16_t _VCU_DspChgCurr,const std::uint16_t _VCU_DspChgVolt,const std::uint8_t _BMS_ChgComplRemHour,const std::uint8_t _BMS_ChgComplRemMinute,const std::uint32_t _ICM_TotalOdometer,const std::uint16_t _BMS_BattSocDisp,const std::uint32_t _ICM_TotalOdometer_accurate,const std::uint16_t _VCU_VehRng,const std::uint16_t _VCU_EVRng,const std::uint16_t _HVAC_RAWCabinTemp,const std::uint16_t _AQM_PM25Data,const std::uint8_t _HVAC_DriverTempSelect,const std::uint8_t _HVAC_PsnTempSelect,const std::uint8_t _HVAC_WindExitSpd,const std::uint8_t _HVAC_ACSt,const std::uint8_t _UMM_UsageModeSt,const std::uint8_t _SSW_FLSeatVentSt,const std::uint8_t _SSW_FRSeatVentSt,const std::uint8_t _SSW_RLSeatVentSt,const std::uint8_t _SSW_RRSeatVentSt,const std::uint8_t _SSW_FLSeatHeatingSt,const std::uint8_t _SSW_FRSeatHeatingSt,const std::uint64_t _SSW_RLSeatHeatingSt,const std::uint64_t _SSW_RRSeatHeatingSt,const std::uint8_t _HRN_HornRunningSt,const std::uint8_t _IL_HazardIndLightOutputSt,const std::uint16_t _BCS_VehSpd,const std::uint16_t _VCU_DspDischgCurr,const std::uint16_t _VCU_DspDischgVolt,const std::uint8_t _PWL_WinCurrentPos_FLWinPst,const std::uint8_t _PWL_WinOpeationSt_FLWinSt,const std::uint8_t _PWL_WinCurrentPos_RLWinPst,const std::uint8_t _PWL_WinCurrentPos_RRWinPst,const std::uint8_t _PWL_WinOpeationSt_RLWinSt,const std::uint8_t _PWL_WinOpeationSt_RRWinSt,const std::uint8_t _PWL_WinCurrentPos_FRWinPst,const std::uint8_t _PWL_WinOpeationSt_FRWinSt):LCK_FrontLeftDoorAjarSt(_LCK_FrontLeftDoorAjarSt),LCK_FrontRightDoorAjarSt(_LCK_FrontRightDoorAjarSt),LCK_RearLeftDoorAjarSt(_LCK_RearLeftDoorAjarSt),LCK_RearRightDoorAjarSt(_LCK_RearRightDoorAjarSt),LCK_TrunkAjarSt(_LCK_TrunkAjarSt),LCK_HoodAjarSt(_LCK_HoodAjarSt),LCK_DriverDoorLockSt(_LCK_DriverDoorLockSt),LCK_PassengerDoorLockSt(_LCK_PassengerDoorLockSt),LCK_RearLeftDoorLockSt(_LCK_RearLeftDoorLockSt),LCK_RearRightDoorLockSt(_LCK_RearRightDoorLockSt),PWL_FLWinCurrentPst(_PWL_FLWinCurrentPst),PWL_FRWinCurrentPst(_PWL_FRWinCurrentPst),PWL_RLWinCurrentPst(_PWL_RLWinCurrentPst),PWL_RRWinCurrentPst(_PWL_RRWinCurrentPst),RC_SunroofOperationSt(_RC_SunroofOperationSt),TPMS_FrontLeftTirePressure(_TPMS_FrontLeftTirePressure),TPMS_FrontRightTirePressure(_TPMS_FrontRightTirePressure),TPMS_RearLeftTirePressure(_TPMS_RearLeftTirePressure),TPMS_RearRightTirePressure(_TPMS_RearRightTirePressure),TPMS_FrontLeftTireTemperature(_TPMS_FrontLeftTireTemperature),TPMS_FrontRightTireTemperature(_TPMS_FrontRightTireTemperature),TPMS_RearRightTireTemperature(_TPMS_RearRightTireTemperature),TPMS_RearLeftTireTemperature(_TPMS_RearLeftTireTemperature),TPMS_FrontLeftTireLowPressure(_TPMS_FrontLeftTireLowPressure),TPMS_FrontRightTireLowPressure(_TPMS_FrontRightTireLowPressure),TPMS_RearRightTireLowPressure(_TPMS_RearRightTireLowPressure),TPMS_RearLeftTireLowPressure(_TPMS_RearLeftTireLowPressure),TPMS_FrontLeftTireHighPressure(_TPMS_FrontLeftTireHighPressure),TPMS_FrontRightTireHighPressure(_TPMS_FrontRightTireHighPressure),TPMS_RearRightTireHighPressure(_TPMS_RearRightTireHighPressure),TPMS_RearLeftTireHighPressure(_TPMS_RearLeftTireHighPressure),TPMS_FrontLeftTireHighTemperature(_TPMS_FrontLeftTireHighTemperature),TPMS_FrontRightTireHighTemperature(_TPMS_FrontRightTireHighTemperature),TPMS_RearRightTireHighTemperature(_TPMS_RearRightTireHighTemperature),TPMS_RearLeftTireHighTemperature(_TPMS_RearLeftTireHighTemperature),EBSF_BattVolt(_EBSF_BattVolt),EBSF_SOC(_EBSF_SOC),EBSF_VoltSt(_EBSF_VoltSt),ICM_BFLWarning(_ICM_BFLWarning),VCU_DspChgCurr(_VCU_DspChgCurr),VCU_DspChgVolt(_VCU_DspChgVolt),BMS_ChgComplRemHour(_BMS_ChgComplRemHour),BMS_ChgComplRemMinute(_BMS_ChgComplRemMinute),ICM_TotalOdometer(_ICM_TotalOdometer),BMS_BattSocDisp(_BMS_BattSocDisp),ICM_TotalOdometer_accurate(_ICM_TotalOdometer_accurate),VCU_VehRng(_VCU_VehRng),VCU_EVRng(_VCU_EVRng),HVAC_RAWCabinTemp(_HVAC_RAWCabinTemp),AQM_PM25Data(_AQM_PM25Data),HVAC_DriverTempSelect(_HVAC_DriverTempSelect),HVAC_PsnTempSelect(_HVAC_PsnTempSelect),HVAC_WindExitSpd(_HVAC_WindExitSpd),HVAC_ACSt(_HVAC_ACSt),UMM_UsageModeSt(_UMM_UsageModeSt),SSW_FLSeatVentSt(_SSW_FLSeatVentSt),SSW_FRSeatVentSt(_SSW_FRSeatVentSt),SSW_RLSeatVentSt(_SSW_RLSeatVentSt),SSW_RRSeatVentSt(_SSW_RRSeatVentSt),SSW_FLSeatHeatingSt(_SSW_FLSeatHeatingSt),SSW_FRSeatHeatingSt(_SSW_FRSeatHeatingSt),SSW_RLSeatHeatingSt(_SSW_RLSeatHeatingSt),SSW_RRSeatHeatingSt(_SSW_RRSeatHeatingSt),HRN_HornRunningSt(_HRN_HornRunningSt),IL_HazardIndLightOutputSt(_IL_HazardIndLightOutputSt),BCS_VehSpd(_BCS_VehSpd),VCU_DspDischgCurr(_VCU_DspDischgCurr),VCU_DspDischgVolt(_VCU_DspDischgVolt),PWL_WinCurrentPos_FLWinPst(_PWL_WinCurrentPos_FLWinPst),PWL_WinOpeationSt_FLWinSt(_PWL_WinOpeationSt_FLWinSt),PWL_WinCurrentPos_RLWinPst(_PWL_WinCurrentPos_RLWinPst),PWL_WinCurrentPos_RRWinPst(_PWL_WinCurrentPos_RRWinPst),PWL_WinOpeationSt_RLWinSt(_PWL_WinOpeationSt_RLWinSt),PWL_WinOpeationSt_RRWinSt(_PWL_WinOpeationSt_RRWinSt),PWL_WinCurrentPos_FRWinPst(_PWL_WinCurrentPos_FRWinPst),PWL_WinOpeationSt_FRWinSt(_PWL_WinOpeationSt_FRWinSt) {}
	BDCCLOUD1(const BDCCLOUD1 &_x){
		LCK_FrontLeftDoorAjarSt = _x.LCK_FrontLeftDoorAjarSt;
		LCK_FrontRightDoorAjarSt = _x.LCK_FrontRightDoorAjarSt;
		LCK_RearLeftDoorAjarSt = _x.LCK_RearLeftDoorAjarSt;
		LCK_RearRightDoorAjarSt = _x.LCK_RearRightDoorAjarSt;
		LCK_TrunkAjarSt = _x.LCK_TrunkAjarSt;
		LCK_HoodAjarSt = _x.LCK_HoodAjarSt;
		LCK_DriverDoorLockSt = _x.LCK_DriverDoorLockSt;
		LCK_PassengerDoorLockSt = _x.LCK_PassengerDoorLockSt;
		LCK_RearLeftDoorLockSt = _x.LCK_RearLeftDoorLockSt;
		LCK_RearRightDoorLockSt = _x.LCK_RearRightDoorLockSt;
		PWL_FLWinCurrentPst = _x.PWL_FLWinCurrentPst;
		PWL_FRWinCurrentPst = _x.PWL_FRWinCurrentPst;
		PWL_RLWinCurrentPst = _x.PWL_RLWinCurrentPst;
		PWL_RRWinCurrentPst = _x.PWL_RRWinCurrentPst;
		RC_SunroofOperationSt = _x.RC_SunroofOperationSt;
		TPMS_FrontLeftTirePressure = _x.TPMS_FrontLeftTirePressure;
		TPMS_FrontRightTirePressure = _x.TPMS_FrontRightTirePressure;
		TPMS_RearLeftTirePressure = _x.TPMS_RearLeftTirePressure;
		TPMS_RearRightTirePressure = _x.TPMS_RearRightTirePressure;
		TPMS_FrontLeftTireTemperature = _x.TPMS_FrontLeftTireTemperature;
		TPMS_FrontRightTireTemperature = _x.TPMS_FrontRightTireTemperature;
		TPMS_RearRightTireTemperature = _x.TPMS_RearRightTireTemperature;
		TPMS_RearLeftTireTemperature = _x.TPMS_RearLeftTireTemperature;
		TPMS_FrontLeftTireLowPressure = _x.TPMS_FrontLeftTireLowPressure;
		TPMS_FrontRightTireLowPressure = _x.TPMS_FrontRightTireLowPressure;
		TPMS_RearRightTireLowPressure = _x.TPMS_RearRightTireLowPressure;
		TPMS_RearLeftTireLowPressure = _x.TPMS_RearLeftTireLowPressure;
		TPMS_FrontLeftTireHighPressure = _x.TPMS_FrontLeftTireHighPressure;
		TPMS_FrontRightTireHighPressure = _x.TPMS_FrontRightTireHighPressure;
		TPMS_RearRightTireHighPressure = _x.TPMS_RearRightTireHighPressure;
		TPMS_RearLeftTireHighPressure = _x.TPMS_RearLeftTireHighPressure;
		TPMS_FrontLeftTireHighTemperature = _x.TPMS_FrontLeftTireHighTemperature;
		TPMS_FrontRightTireHighTemperature = _x.TPMS_FrontRightTireHighTemperature;
		TPMS_RearRightTireHighTemperature = _x.TPMS_RearRightTireHighTemperature;
		TPMS_RearLeftTireHighTemperature = _x.TPMS_RearLeftTireHighTemperature;
		EBSF_BattVolt = _x.EBSF_BattVolt;
		EBSF_SOC = _x.EBSF_SOC;
		EBSF_VoltSt = _x.EBSF_VoltSt;
		ICM_BFLWarning = _x.ICM_BFLWarning;
		VCU_DspChgCurr = _x.VCU_DspChgCurr;
		VCU_DspChgVolt = _x.VCU_DspChgVolt;
		BMS_ChgComplRemHour = _x.BMS_ChgComplRemHour;
		BMS_ChgComplRemMinute = _x.BMS_ChgComplRemMinute;
		ICM_TotalOdometer = _x.ICM_TotalOdometer;
		BMS_BattSocDisp = _x.BMS_BattSocDisp;
		ICM_TotalOdometer_accurate = _x.ICM_TotalOdometer_accurate;
		VCU_VehRng = _x.VCU_VehRng;
		VCU_EVRng = _x.VCU_EVRng;
		HVAC_RAWCabinTemp = _x.HVAC_RAWCabinTemp;
		AQM_PM25Data = _x.AQM_PM25Data;
		HVAC_DriverTempSelect = _x.HVAC_DriverTempSelect;
		HVAC_PsnTempSelect = _x.HVAC_PsnTempSelect;
		HVAC_WindExitSpd = _x.HVAC_WindExitSpd;
		HVAC_ACSt = _x.HVAC_ACSt;
		UMM_UsageModeSt = _x.UMM_UsageModeSt;
		SSW_FLSeatVentSt = _x.SSW_FLSeatVentSt;
		SSW_FRSeatVentSt = _x.SSW_FRSeatVentSt;
		SSW_RLSeatVentSt = _x.SSW_RLSeatVentSt;
		SSW_RRSeatVentSt = _x.SSW_RRSeatVentSt;
		SSW_FLSeatHeatingSt = _x.SSW_FLSeatHeatingSt;
		SSW_FRSeatHeatingSt = _x.SSW_FRSeatHeatingSt;
		SSW_RLSeatHeatingSt = _x.SSW_RLSeatHeatingSt;
		SSW_RRSeatHeatingSt = _x.SSW_RRSeatHeatingSt;
		HRN_HornRunningSt = _x.HRN_HornRunningSt;
		IL_HazardIndLightOutputSt = _x.IL_HazardIndLightOutputSt;
		BCS_VehSpd = _x.BCS_VehSpd;
		VCU_DspDischgCurr = _x.VCU_DspDischgCurr;
		VCU_DspDischgVolt = _x.VCU_DspDischgVolt;
		PWL_WinCurrentPos_FLWinPst = _x.PWL_WinCurrentPos_FLWinPst;
		PWL_WinOpeationSt_FLWinSt = _x.PWL_WinOpeationSt_FLWinSt;
		PWL_WinCurrentPos_RLWinPst = _x.PWL_WinCurrentPos_RLWinPst;
		PWL_WinCurrentPos_RRWinPst = _x.PWL_WinCurrentPos_RRWinPst;
		PWL_WinOpeationSt_RLWinSt = _x.PWL_WinOpeationSt_RLWinSt;
		PWL_WinOpeationSt_RRWinSt = _x.PWL_WinOpeationSt_RRWinSt;
		PWL_WinCurrentPos_FRWinPst = _x.PWL_WinCurrentPos_FRWinPst;
		PWL_WinOpeationSt_FRWinSt = _x.PWL_WinOpeationSt_FRWinSt;
	}
	BDCCLOUD1(BDCCLOUD1 &&_x){
		LCK_FrontLeftDoorAjarSt = std::move(_x.LCK_FrontLeftDoorAjarSt);
		LCK_FrontRightDoorAjarSt = std::move(_x.LCK_FrontRightDoorAjarSt);
		LCK_RearLeftDoorAjarSt = std::move(_x.LCK_RearLeftDoorAjarSt);
		LCK_RearRightDoorAjarSt = std::move(_x.LCK_RearRightDoorAjarSt);
		LCK_TrunkAjarSt = std::move(_x.LCK_TrunkAjarSt);
		LCK_HoodAjarSt = std::move(_x.LCK_HoodAjarSt);
		LCK_DriverDoorLockSt = std::move(_x.LCK_DriverDoorLockSt);
		LCK_PassengerDoorLockSt = std::move(_x.LCK_PassengerDoorLockSt);
		LCK_RearLeftDoorLockSt = std::move(_x.LCK_RearLeftDoorLockSt);
		LCK_RearRightDoorLockSt = std::move(_x.LCK_RearRightDoorLockSt);
		PWL_FLWinCurrentPst = std::move(_x.PWL_FLWinCurrentPst);
		PWL_FRWinCurrentPst = std::move(_x.PWL_FRWinCurrentPst);
		PWL_RLWinCurrentPst = std::move(_x.PWL_RLWinCurrentPst);
		PWL_RRWinCurrentPst = std::move(_x.PWL_RRWinCurrentPst);
		RC_SunroofOperationSt = std::move(_x.RC_SunroofOperationSt);
		TPMS_FrontLeftTirePressure = std::move(_x.TPMS_FrontLeftTirePressure);
		TPMS_FrontRightTirePressure = std::move(_x.TPMS_FrontRightTirePressure);
		TPMS_RearLeftTirePressure = std::move(_x.TPMS_RearLeftTirePressure);
		TPMS_RearRightTirePressure = std::move(_x.TPMS_RearRightTirePressure);
		TPMS_FrontLeftTireTemperature = std::move(_x.TPMS_FrontLeftTireTemperature);
		TPMS_FrontRightTireTemperature = std::move(_x.TPMS_FrontRightTireTemperature);
		TPMS_RearRightTireTemperature = std::move(_x.TPMS_RearRightTireTemperature);
		TPMS_RearLeftTireTemperature = std::move(_x.TPMS_RearLeftTireTemperature);
		TPMS_FrontLeftTireLowPressure = std::move(_x.TPMS_FrontLeftTireLowPressure);
		TPMS_FrontRightTireLowPressure = std::move(_x.TPMS_FrontRightTireLowPressure);
		TPMS_RearRightTireLowPressure = std::move(_x.TPMS_RearRightTireLowPressure);
		TPMS_RearLeftTireLowPressure = std::move(_x.TPMS_RearLeftTireLowPressure);
		TPMS_FrontLeftTireHighPressure = std::move(_x.TPMS_FrontLeftTireHighPressure);
		TPMS_FrontRightTireHighPressure = std::move(_x.TPMS_FrontRightTireHighPressure);
		TPMS_RearRightTireHighPressure = std::move(_x.TPMS_RearRightTireHighPressure);
		TPMS_RearLeftTireHighPressure = std::move(_x.TPMS_RearLeftTireHighPressure);
		TPMS_FrontLeftTireHighTemperature = std::move(_x.TPMS_FrontLeftTireHighTemperature);
		TPMS_FrontRightTireHighTemperature = std::move(_x.TPMS_FrontRightTireHighTemperature);
		TPMS_RearRightTireHighTemperature = std::move(_x.TPMS_RearRightTireHighTemperature);
		TPMS_RearLeftTireHighTemperature = std::move(_x.TPMS_RearLeftTireHighTemperature);
		EBSF_BattVolt = std::move(_x.EBSF_BattVolt);
		EBSF_SOC = std::move(_x.EBSF_SOC);
		EBSF_VoltSt = std::move(_x.EBSF_VoltSt);
		ICM_BFLWarning = std::move(_x.ICM_BFLWarning);
		VCU_DspChgCurr = std::move(_x.VCU_DspChgCurr);
		VCU_DspChgVolt = std::move(_x.VCU_DspChgVolt);
		BMS_ChgComplRemHour = std::move(_x.BMS_ChgComplRemHour);
		BMS_ChgComplRemMinute = std::move(_x.BMS_ChgComplRemMinute);
		ICM_TotalOdometer = std::move(_x.ICM_TotalOdometer);
		BMS_BattSocDisp = std::move(_x.BMS_BattSocDisp);
		ICM_TotalOdometer_accurate = std::move(_x.ICM_TotalOdometer_accurate);
		VCU_VehRng = std::move(_x.VCU_VehRng);
		VCU_EVRng = std::move(_x.VCU_EVRng);
		HVAC_RAWCabinTemp = std::move(_x.HVAC_RAWCabinTemp);
		AQM_PM25Data = std::move(_x.AQM_PM25Data);
		HVAC_DriverTempSelect = std::move(_x.HVAC_DriverTempSelect);
		HVAC_PsnTempSelect = std::move(_x.HVAC_PsnTempSelect);
		HVAC_WindExitSpd = std::move(_x.HVAC_WindExitSpd);
		HVAC_ACSt = std::move(_x.HVAC_ACSt);
		UMM_UsageModeSt = std::move(_x.UMM_UsageModeSt);
		SSW_FLSeatVentSt = std::move(_x.SSW_FLSeatVentSt);
		SSW_FRSeatVentSt = std::move(_x.SSW_FRSeatVentSt);
		SSW_RLSeatVentSt = std::move(_x.SSW_RLSeatVentSt);
		SSW_RRSeatVentSt = std::move(_x.SSW_RRSeatVentSt);
		SSW_FLSeatHeatingSt = std::move(_x.SSW_FLSeatHeatingSt);
		SSW_FRSeatHeatingSt = std::move(_x.SSW_FRSeatHeatingSt);
		SSW_RLSeatHeatingSt = std::move(_x.SSW_RLSeatHeatingSt);
		SSW_RRSeatHeatingSt = std::move(_x.SSW_RRSeatHeatingSt);
		HRN_HornRunningSt = std::move(_x.HRN_HornRunningSt);
		IL_HazardIndLightOutputSt = std::move(_x.IL_HazardIndLightOutputSt);
		BCS_VehSpd = std::move(_x.BCS_VehSpd);
		VCU_DspDischgCurr = std::move(_x.VCU_DspDischgCurr);
		VCU_DspDischgVolt = std::move(_x.VCU_DspDischgVolt);
		PWL_WinCurrentPos_FLWinPst = std::move(_x.PWL_WinCurrentPos_FLWinPst);
		PWL_WinOpeationSt_FLWinSt = std::move(_x.PWL_WinOpeationSt_FLWinSt);
		PWL_WinCurrentPos_RLWinPst = std::move(_x.PWL_WinCurrentPos_RLWinPst);
		PWL_WinCurrentPos_RRWinPst = std::move(_x.PWL_WinCurrentPos_RRWinPst);
		PWL_WinOpeationSt_RLWinSt = std::move(_x.PWL_WinOpeationSt_RLWinSt);
		PWL_WinOpeationSt_RRWinSt = std::move(_x.PWL_WinOpeationSt_RRWinSt);
		PWL_WinCurrentPos_FRWinPst = std::move(_x.PWL_WinCurrentPos_FRWinPst);
		PWL_WinOpeationSt_FRWinSt = std::move(_x.PWL_WinOpeationSt_FRWinSt);
	}
	BDCCLOUD1& operator=(const BDCCLOUD1 &_x){
		LCK_FrontLeftDoorAjarSt = _x.LCK_FrontLeftDoorAjarSt;
		LCK_FrontRightDoorAjarSt = _x.LCK_FrontRightDoorAjarSt;
		LCK_RearLeftDoorAjarSt = _x.LCK_RearLeftDoorAjarSt;
		LCK_RearRightDoorAjarSt = _x.LCK_RearRightDoorAjarSt;
		LCK_TrunkAjarSt = _x.LCK_TrunkAjarSt;
		LCK_HoodAjarSt = _x.LCK_HoodAjarSt;
		LCK_DriverDoorLockSt = _x.LCK_DriverDoorLockSt;
		LCK_PassengerDoorLockSt = _x.LCK_PassengerDoorLockSt;
		LCK_RearLeftDoorLockSt = _x.LCK_RearLeftDoorLockSt;
		LCK_RearRightDoorLockSt = _x.LCK_RearRightDoorLockSt;
		PWL_FLWinCurrentPst = _x.PWL_FLWinCurrentPst;
		PWL_FRWinCurrentPst = _x.PWL_FRWinCurrentPst;
		PWL_RLWinCurrentPst = _x.PWL_RLWinCurrentPst;
		PWL_RRWinCurrentPst = _x.PWL_RRWinCurrentPst;
		RC_SunroofOperationSt = _x.RC_SunroofOperationSt;
		TPMS_FrontLeftTirePressure = _x.TPMS_FrontLeftTirePressure;
		TPMS_FrontRightTirePressure = _x.TPMS_FrontRightTirePressure;
		TPMS_RearLeftTirePressure = _x.TPMS_RearLeftTirePressure;
		TPMS_RearRightTirePressure = _x.TPMS_RearRightTirePressure;
		TPMS_FrontLeftTireTemperature = _x.TPMS_FrontLeftTireTemperature;
		TPMS_FrontRightTireTemperature = _x.TPMS_FrontRightTireTemperature;
		TPMS_RearRightTireTemperature = _x.TPMS_RearRightTireTemperature;
		TPMS_RearLeftTireTemperature = _x.TPMS_RearLeftTireTemperature;
		TPMS_FrontLeftTireLowPressure = _x.TPMS_FrontLeftTireLowPressure;
		TPMS_FrontRightTireLowPressure = _x.TPMS_FrontRightTireLowPressure;
		TPMS_RearRightTireLowPressure = _x.TPMS_RearRightTireLowPressure;
		TPMS_RearLeftTireLowPressure = _x.TPMS_RearLeftTireLowPressure;
		TPMS_FrontLeftTireHighPressure = _x.TPMS_FrontLeftTireHighPressure;
		TPMS_FrontRightTireHighPressure = _x.TPMS_FrontRightTireHighPressure;
		TPMS_RearRightTireHighPressure = _x.TPMS_RearRightTireHighPressure;
		TPMS_RearLeftTireHighPressure = _x.TPMS_RearLeftTireHighPressure;
		TPMS_FrontLeftTireHighTemperature = _x.TPMS_FrontLeftTireHighTemperature;
		TPMS_FrontRightTireHighTemperature = _x.TPMS_FrontRightTireHighTemperature;
		TPMS_RearRightTireHighTemperature = _x.TPMS_RearRightTireHighTemperature;
		TPMS_RearLeftTireHighTemperature = _x.TPMS_RearLeftTireHighTemperature;
		EBSF_BattVolt = _x.EBSF_BattVolt;
		EBSF_SOC = _x.EBSF_SOC;
		EBSF_VoltSt = _x.EBSF_VoltSt;
		ICM_BFLWarning = _x.ICM_BFLWarning;
		VCU_DspChgCurr = _x.VCU_DspChgCurr;
		VCU_DspChgVolt = _x.VCU_DspChgVolt;
		BMS_ChgComplRemHour = _x.BMS_ChgComplRemHour;
		BMS_ChgComplRemMinute = _x.BMS_ChgComplRemMinute;
		ICM_TotalOdometer = _x.ICM_TotalOdometer;
		BMS_BattSocDisp = _x.BMS_BattSocDisp;
		ICM_TotalOdometer_accurate = _x.ICM_TotalOdometer_accurate;
		VCU_VehRng = _x.VCU_VehRng;
		VCU_EVRng = _x.VCU_EVRng;
		HVAC_RAWCabinTemp = _x.HVAC_RAWCabinTemp;
		AQM_PM25Data = _x.AQM_PM25Data;
		HVAC_DriverTempSelect = _x.HVAC_DriverTempSelect;
		HVAC_PsnTempSelect = _x.HVAC_PsnTempSelect;
		HVAC_WindExitSpd = _x.HVAC_WindExitSpd;
		HVAC_ACSt = _x.HVAC_ACSt;
		UMM_UsageModeSt = _x.UMM_UsageModeSt;
		SSW_FLSeatVentSt = _x.SSW_FLSeatVentSt;
		SSW_FRSeatVentSt = _x.SSW_FRSeatVentSt;
		SSW_RLSeatVentSt = _x.SSW_RLSeatVentSt;
		SSW_RRSeatVentSt = _x.SSW_RRSeatVentSt;
		SSW_FLSeatHeatingSt = _x.SSW_FLSeatHeatingSt;
		SSW_FRSeatHeatingSt = _x.SSW_FRSeatHeatingSt;
		SSW_RLSeatHeatingSt = _x.SSW_RLSeatHeatingSt;
		SSW_RRSeatHeatingSt = _x.SSW_RRSeatHeatingSt;
		HRN_HornRunningSt = _x.HRN_HornRunningSt;
		IL_HazardIndLightOutputSt = _x.IL_HazardIndLightOutputSt;
		BCS_VehSpd = _x.BCS_VehSpd;
		VCU_DspDischgCurr = _x.VCU_DspDischgCurr;
		VCU_DspDischgVolt = _x.VCU_DspDischgVolt;
		PWL_WinCurrentPos_FLWinPst = _x.PWL_WinCurrentPos_FLWinPst;
		PWL_WinOpeationSt_FLWinSt = _x.PWL_WinOpeationSt_FLWinSt;
		PWL_WinCurrentPos_RLWinPst = _x.PWL_WinCurrentPos_RLWinPst;
		PWL_WinCurrentPos_RRWinPst = _x.PWL_WinCurrentPos_RRWinPst;
		PWL_WinOpeationSt_RLWinSt = _x.PWL_WinOpeationSt_RLWinSt;
		PWL_WinOpeationSt_RRWinSt = _x.PWL_WinOpeationSt_RRWinSt;
		PWL_WinCurrentPos_FRWinPst = _x.PWL_WinCurrentPos_FRWinPst;
		PWL_WinOpeationSt_FRWinSt = _x.PWL_WinOpeationSt_FRWinSt;
		return *this;
	}
	BDCCLOUD1& operator=(BDCCLOUD1 &&_x){
		LCK_FrontLeftDoorAjarSt = std::move(_x.LCK_FrontLeftDoorAjarSt);
		LCK_FrontRightDoorAjarSt = std::move(_x.LCK_FrontRightDoorAjarSt);
		LCK_RearLeftDoorAjarSt = std::move(_x.LCK_RearLeftDoorAjarSt);
		LCK_RearRightDoorAjarSt = std::move(_x.LCK_RearRightDoorAjarSt);
		LCK_TrunkAjarSt = std::move(_x.LCK_TrunkAjarSt);
		LCK_HoodAjarSt = std::move(_x.LCK_HoodAjarSt);
		LCK_DriverDoorLockSt = std::move(_x.LCK_DriverDoorLockSt);
		LCK_PassengerDoorLockSt = std::move(_x.LCK_PassengerDoorLockSt);
		LCK_RearLeftDoorLockSt = std::move(_x.LCK_RearLeftDoorLockSt);
		LCK_RearRightDoorLockSt = std::move(_x.LCK_RearRightDoorLockSt);
		PWL_FLWinCurrentPst = std::move(_x.PWL_FLWinCurrentPst);
		PWL_FRWinCurrentPst = std::move(_x.PWL_FRWinCurrentPst);
		PWL_RLWinCurrentPst = std::move(_x.PWL_RLWinCurrentPst);
		PWL_RRWinCurrentPst = std::move(_x.PWL_RRWinCurrentPst);
		RC_SunroofOperationSt = std::move(_x.RC_SunroofOperationSt);
		TPMS_FrontLeftTirePressure = std::move(_x.TPMS_FrontLeftTirePressure);
		TPMS_FrontRightTirePressure = std::move(_x.TPMS_FrontRightTirePressure);
		TPMS_RearLeftTirePressure = std::move(_x.TPMS_RearLeftTirePressure);
		TPMS_RearRightTirePressure = std::move(_x.TPMS_RearRightTirePressure);
		TPMS_FrontLeftTireTemperature = std::move(_x.TPMS_FrontLeftTireTemperature);
		TPMS_FrontRightTireTemperature = std::move(_x.TPMS_FrontRightTireTemperature);
		TPMS_RearRightTireTemperature = std::move(_x.TPMS_RearRightTireTemperature);
		TPMS_RearLeftTireTemperature = std::move(_x.TPMS_RearLeftTireTemperature);
		TPMS_FrontLeftTireLowPressure = std::move(_x.TPMS_FrontLeftTireLowPressure);
		TPMS_FrontRightTireLowPressure = std::move(_x.TPMS_FrontRightTireLowPressure);
		TPMS_RearRightTireLowPressure = std::move(_x.TPMS_RearRightTireLowPressure);
		TPMS_RearLeftTireLowPressure = std::move(_x.TPMS_RearLeftTireLowPressure);
		TPMS_FrontLeftTireHighPressure = std::move(_x.TPMS_FrontLeftTireHighPressure);
		TPMS_FrontRightTireHighPressure = std::move(_x.TPMS_FrontRightTireHighPressure);
		TPMS_RearRightTireHighPressure = std::move(_x.TPMS_RearRightTireHighPressure);
		TPMS_RearLeftTireHighPressure = std::move(_x.TPMS_RearLeftTireHighPressure);
		TPMS_FrontLeftTireHighTemperature = std::move(_x.TPMS_FrontLeftTireHighTemperature);
		TPMS_FrontRightTireHighTemperature = std::move(_x.TPMS_FrontRightTireHighTemperature);
		TPMS_RearRightTireHighTemperature = std::move(_x.TPMS_RearRightTireHighTemperature);
		TPMS_RearLeftTireHighTemperature = std::move(_x.TPMS_RearLeftTireHighTemperature);
		EBSF_BattVolt = std::move(_x.EBSF_BattVolt);
		EBSF_SOC = std::move(_x.EBSF_SOC);
		EBSF_VoltSt = std::move(_x.EBSF_VoltSt);
		ICM_BFLWarning = std::move(_x.ICM_BFLWarning);
		VCU_DspChgCurr = std::move(_x.VCU_DspChgCurr);
		VCU_DspChgVolt = std::move(_x.VCU_DspChgVolt);
		BMS_ChgComplRemHour = std::move(_x.BMS_ChgComplRemHour);
		BMS_ChgComplRemMinute = std::move(_x.BMS_ChgComplRemMinute);
		ICM_TotalOdometer = std::move(_x.ICM_TotalOdometer);
		BMS_BattSocDisp = std::move(_x.BMS_BattSocDisp);
		ICM_TotalOdometer_accurate = std::move(_x.ICM_TotalOdometer_accurate);
		VCU_VehRng = std::move(_x.VCU_VehRng);
		VCU_EVRng = std::move(_x.VCU_EVRng);
		HVAC_RAWCabinTemp = std::move(_x.HVAC_RAWCabinTemp);
		AQM_PM25Data = std::move(_x.AQM_PM25Data);
		HVAC_DriverTempSelect = std::move(_x.HVAC_DriverTempSelect);
		HVAC_PsnTempSelect = std::move(_x.HVAC_PsnTempSelect);
		HVAC_WindExitSpd = std::move(_x.HVAC_WindExitSpd);
		HVAC_ACSt = std::move(_x.HVAC_ACSt);
		UMM_UsageModeSt = std::move(_x.UMM_UsageModeSt);
		SSW_FLSeatVentSt = std::move(_x.SSW_FLSeatVentSt);
		SSW_FRSeatVentSt = std::move(_x.SSW_FRSeatVentSt);
		SSW_RLSeatVentSt = std::move(_x.SSW_RLSeatVentSt);
		SSW_RRSeatVentSt = std::move(_x.SSW_RRSeatVentSt);
		SSW_FLSeatHeatingSt = std::move(_x.SSW_FLSeatHeatingSt);
		SSW_FRSeatHeatingSt = std::move(_x.SSW_FRSeatHeatingSt);
		SSW_RLSeatHeatingSt = std::move(_x.SSW_RLSeatHeatingSt);
		SSW_RRSeatHeatingSt = std::move(_x.SSW_RRSeatHeatingSt);
		HRN_HornRunningSt = std::move(_x.HRN_HornRunningSt);
		IL_HazardIndLightOutputSt = std::move(_x.IL_HazardIndLightOutputSt);
		BCS_VehSpd = std::move(_x.BCS_VehSpd);
		VCU_DspDischgCurr = std::move(_x.VCU_DspDischgCurr);
		VCU_DspDischgVolt = std::move(_x.VCU_DspDischgVolt);
		PWL_WinCurrentPos_FLWinPst = std::move(_x.PWL_WinCurrentPos_FLWinPst);
		PWL_WinOpeationSt_FLWinSt = std::move(_x.PWL_WinOpeationSt_FLWinSt);
		PWL_WinCurrentPos_RLWinPst = std::move(_x.PWL_WinCurrentPos_RLWinPst);
		PWL_WinCurrentPos_RRWinPst = std::move(_x.PWL_WinCurrentPos_RRWinPst);
		PWL_WinOpeationSt_RLWinSt = std::move(_x.PWL_WinOpeationSt_RLWinSt);
		PWL_WinOpeationSt_RRWinSt = std::move(_x.PWL_WinOpeationSt_RRWinSt);
		PWL_WinCurrentPos_FRWinPst = std::move(_x.PWL_WinCurrentPos_FRWinPst);
		PWL_WinOpeationSt_FRWinSt = std::move(_x.PWL_WinOpeationSt_FRWinSt);
		return *this;
	}
*/

	using IsEnumerableTag = void;
	template<typename F>
	void enumerate(F& fun) {
		fun(LCK_FrontLeftDoorAjarSt);
		fun(LCK_FrontRightDoorAjarSt);
		fun(LCK_RearLeftDoorAjarSt);
		fun(LCK_RearRightDoorAjarSt);
		fun(LCK_TrunkAjarSt);
		fun(LCK_HoodAjarSt);
		fun(LCK_DriverDoorLockSt);
		fun(LCK_PassengerDoorLockSt);
		fun(LCK_RearLeftDoorLockSt);
		fun(LCK_RearRightDoorLockSt);
		fun(PWL_FLWinCurrentPst);
		fun(PWL_FRWinCurrentPst);
		fun(PWL_RLWinCurrentPst);
		fun(PWL_RRWinCurrentPst);
		fun(RC_SunroofOperationSt);
		fun(TPMS_FrontLeftTirePressure);
		fun(TPMS_FrontRightTirePressure);
		fun(TPMS_RearLeftTirePressure);
		fun(TPMS_RearRightTirePressure);
		fun(TPMS_FrontLeftTireTemperature);
		fun(TPMS_FrontRightTireTemperature);
		fun(TPMS_RearRightTireTemperature);
		fun(TPMS_RearLeftTireTemperature);
		fun(TPMS_FrontLeftTireLowPressure);
		fun(TPMS_FrontRightTireLowPressure);
		fun(TPMS_RearRightTireLowPressure);
		fun(TPMS_RearLeftTireLowPressure);
		fun(TPMS_FrontLeftTireHighPressure);
		fun(TPMS_FrontRightTireHighPressure);
		fun(TPMS_RearRightTireHighPressure);
		fun(TPMS_RearLeftTireHighPressure);
		fun(TPMS_FrontLeftTireHighTemperature);
		fun(TPMS_FrontRightTireHighTemperature);
		fun(TPMS_RearRightTireHighTemperature);
		fun(TPMS_RearLeftTireHighTemperature);
		fun(EBSF_BattVolt);
		fun(EBSF_SOC);
		fun(EBSF_VoltSt);
		fun(ICM_BFLWarning);
		fun(VCU_DspChgCurr);
		fun(VCU_DspChgVolt);
		fun(BMS_ChgComplRemHour);
		fun(BMS_ChgComplRemMinute);
		fun(ICM_TotalOdometer);
		fun(BMS_BattSocDisp);
		fun(ICM_TotalOdometer_accurate);
		fun(VCU_VehRng);
		fun(VCU_EVRng);
		fun(HVAC_RAWCabinTemp);
		fun(AQM_PM25Data);
		fun(HVAC_DriverTempSelect);
		fun(HVAC_PsnTempSelect);
		fun(HVAC_WindExitSpd);
		fun(HVAC_ACSt);
		fun(UMM_UsageModeSt);
		fun(SSW_FLSeatVentSt);
		fun(SSW_FRSeatVentSt);
		fun(SSW_RLSeatVentSt);
		fun(SSW_RRSeatVentSt);
		fun(SSW_FLSeatHeatingSt);
		fun(SSW_FRSeatHeatingSt);
		fun(SSW_RLSeatHeatingSt);
		fun(SSW_RRSeatHeatingSt);
		fun(HRN_HornRunningSt);
		fun(IL_HazardIndLightOutputSt);
		fun(BCS_VehSpd);
		fun(VCU_DspDischgCurr);
		fun(VCU_DspDischgVolt);
		fun(PWL_WinCurrentPos_FLWinPst);
		fun(PWL_WinOpeationSt_FLWinSt);
		fun(PWL_WinCurrentPos_RLWinPst);
		fun(PWL_WinCurrentPos_RRWinPst);
		fun(PWL_WinOpeationSt_RLWinSt);
		fun(PWL_WinOpeationSt_RRWinSt);
		fun(PWL_WinCurrentPos_FRWinPst);
		fun(PWL_WinOpeationSt_FRWinSt);
	}

	template<typename F>
	void GetSize(F& fun) const{
		fun(LCK_FrontLeftDoorAjarSt);
		fun(LCK_FrontRightDoorAjarSt);
		fun(LCK_RearLeftDoorAjarSt);
		fun(LCK_RearRightDoorAjarSt);
		fun(LCK_TrunkAjarSt);
		fun(LCK_HoodAjarSt);
		fun(LCK_DriverDoorLockSt);
		fun(LCK_PassengerDoorLockSt);
		fun(LCK_RearLeftDoorLockSt);
		fun(LCK_RearRightDoorLockSt);
		fun(PWL_FLWinCurrentPst);
		fun(PWL_FRWinCurrentPst);
		fun(PWL_RLWinCurrentPst);
		fun(PWL_RRWinCurrentPst);
		fun(RC_SunroofOperationSt);
		fun(TPMS_FrontLeftTirePressure);
		fun(TPMS_FrontRightTirePressure);
		fun(TPMS_RearLeftTirePressure);
		fun(TPMS_RearRightTirePressure);
		fun(TPMS_FrontLeftTireTemperature);
		fun(TPMS_FrontRightTireTemperature);
		fun(TPMS_RearRightTireTemperature);
		fun(TPMS_RearLeftTireTemperature);
		fun(TPMS_FrontLeftTireLowPressure);
		fun(TPMS_FrontRightTireLowPressure);
		fun(TPMS_RearRightTireLowPressure);
		fun(TPMS_RearLeftTireLowPressure);
		fun(TPMS_FrontLeftTireHighPressure);
		fun(TPMS_FrontRightTireHighPressure);
		fun(TPMS_RearRightTireHighPressure);
		fun(TPMS_RearLeftTireHighPressure);
		fun(TPMS_FrontLeftTireHighTemperature);
		fun(TPMS_FrontRightTireHighTemperature);
		fun(TPMS_RearRightTireHighTemperature);
		fun(TPMS_RearLeftTireHighTemperature);
		fun(EBSF_BattVolt);
		fun(EBSF_SOC);
		fun(EBSF_VoltSt);
		fun(ICM_BFLWarning);
		fun(VCU_DspChgCurr);
		fun(VCU_DspChgVolt);
		fun(BMS_ChgComplRemHour);
		fun(BMS_ChgComplRemMinute);
		fun(ICM_TotalOdometer);
		fun(BMS_BattSocDisp);
		fun(ICM_TotalOdometer_accurate);
		fun(VCU_VehRng);
		fun(VCU_EVRng);
		fun(HVAC_RAWCabinTemp);
		fun(AQM_PM25Data);
		fun(HVAC_DriverTempSelect);
		fun(HVAC_PsnTempSelect);
		fun(HVAC_WindExitSpd);
		fun(HVAC_ACSt);
		fun(UMM_UsageModeSt);
		fun(SSW_FLSeatVentSt);
		fun(SSW_FRSeatVentSt);
		fun(SSW_RLSeatVentSt);
		fun(SSW_RRSeatVentSt);
		fun(SSW_FLSeatHeatingSt);
		fun(SSW_FRSeatHeatingSt);
		fun(SSW_RLSeatHeatingSt);
		fun(SSW_RRSeatHeatingSt);
		fun(HRN_HornRunningSt);
		fun(IL_HazardIndLightOutputSt);
		fun(BCS_VehSpd);
		fun(VCU_DspDischgCurr);
		fun(VCU_DspDischgVolt);
		fun(PWL_WinCurrentPos_FLWinPst);
		fun(PWL_WinOpeationSt_FLWinSt);
		fun(PWL_WinCurrentPos_RLWinPst);
		fun(PWL_WinCurrentPos_RRWinPst);
		fun(PWL_WinOpeationSt_RLWinSt);
		fun(PWL_WinOpeationSt_RRWinSt);
		fun(PWL_WinCurrentPos_FRWinPst);
		fun(PWL_WinOpeationSt_FRWinSt);
	}
	template<typename F>
	void serialize(F& fun) const{
		fun << (LCK_FrontLeftDoorAjarSt);
		fun << (LCK_FrontRightDoorAjarSt);
		fun << (LCK_RearLeftDoorAjarSt);
		fun << (LCK_RearRightDoorAjarSt);
		fun << (LCK_TrunkAjarSt);
		fun << (LCK_HoodAjarSt);
		fun << (LCK_DriverDoorLockSt);
		fun << (LCK_PassengerDoorLockSt);
		fun << (LCK_RearLeftDoorLockSt);
		fun << (LCK_RearRightDoorLockSt);
		fun << (PWL_FLWinCurrentPst);
		fun << (PWL_FRWinCurrentPst);
		fun << (PWL_RLWinCurrentPst);
		fun << (PWL_RRWinCurrentPst);
		fun << (RC_SunroofOperationSt);
		fun << (TPMS_FrontLeftTirePressure);
		fun << (TPMS_FrontRightTirePressure);
		fun << (TPMS_RearLeftTirePressure);
		fun << (TPMS_RearRightTirePressure);
		fun << (TPMS_FrontLeftTireTemperature);
		fun << (TPMS_FrontRightTireTemperature);
		fun << (TPMS_RearRightTireTemperature);
		fun << (TPMS_RearLeftTireTemperature);
		fun << (TPMS_FrontLeftTireLowPressure);
		fun << (TPMS_FrontRightTireLowPressure);
		fun << (TPMS_RearRightTireLowPressure);
		fun << (TPMS_RearLeftTireLowPressure);
		fun << (TPMS_FrontLeftTireHighPressure);
		fun << (TPMS_FrontRightTireHighPressure);
		fun << (TPMS_RearRightTireHighPressure);
		fun << (TPMS_RearLeftTireHighPressure);
		fun << (TPMS_FrontLeftTireHighTemperature);
		fun << (TPMS_FrontRightTireHighTemperature);
		fun << (TPMS_RearRightTireHighTemperature);
		fun << (TPMS_RearLeftTireHighTemperature);
		fun << (EBSF_BattVolt);
		fun << (EBSF_SOC);
		fun << (EBSF_VoltSt);
		fun << (ICM_BFLWarning);
		fun << (VCU_DspChgCurr);
		fun << (VCU_DspChgVolt);
		fun << (BMS_ChgComplRemHour);
		fun << (BMS_ChgComplRemMinute);
		fun << (ICM_TotalOdometer);
		fun << (BMS_BattSocDisp);
		fun << (ICM_TotalOdometer_accurate);
		fun << (VCU_VehRng);
		fun << (VCU_EVRng);
		fun << (HVAC_RAWCabinTemp);
		fun << (AQM_PM25Data);
		fun << (HVAC_DriverTempSelect);
		fun << (HVAC_PsnTempSelect);
		fun << (HVAC_WindExitSpd);
		fun << (HVAC_ACSt);
		fun << (UMM_UsageModeSt);
		fun << (SSW_FLSeatVentSt);
		fun << (SSW_FRSeatVentSt);
		fun << (SSW_RLSeatVentSt);
		fun << (SSW_RRSeatVentSt);
		fun << (SSW_FLSeatHeatingSt);
		fun << (SSW_FRSeatHeatingSt);
		fun << (SSW_RLSeatHeatingSt);
		fun << (SSW_RRSeatHeatingSt);
		fun << (HRN_HornRunningSt);
		fun << (IL_HazardIndLightOutputSt);
		fun << (BCS_VehSpd);
		fun << (VCU_DspDischgCurr);
		fun << (VCU_DspDischgVolt);
		fun << (PWL_WinCurrentPos_FLWinPst);
		fun << (PWL_WinOpeationSt_FLWinSt);
		fun << (PWL_WinCurrentPos_RLWinPst);
		fun << (PWL_WinCurrentPos_RRWinPst);
		fun << (PWL_WinOpeationSt_RLWinSt);
		fun << (PWL_WinOpeationSt_RRWinSt);
		fun << (PWL_WinCurrentPos_FRWinPst);
		fun << (PWL_WinOpeationSt_FRWinSt);
	}
	template<typename F>
	void deserialize(F& fun){
		fun >> (LCK_FrontLeftDoorAjarSt);
		fun >> (LCK_FrontRightDoorAjarSt);
		fun >> (LCK_RearLeftDoorAjarSt);
		fun >> (LCK_RearRightDoorAjarSt);
		fun >> (LCK_TrunkAjarSt);
		fun >> (LCK_HoodAjarSt);
		fun >> (LCK_DriverDoorLockSt);
		fun >> (LCK_PassengerDoorLockSt);
		fun >> (LCK_RearLeftDoorLockSt);
		fun >> (LCK_RearRightDoorLockSt);
		fun >> (PWL_FLWinCurrentPst);
		fun >> (PWL_FRWinCurrentPst);
		fun >> (PWL_RLWinCurrentPst);
		fun >> (PWL_RRWinCurrentPst);
		fun >> (RC_SunroofOperationSt);
		fun >> (TPMS_FrontLeftTirePressure);
		fun >> (TPMS_FrontRightTirePressure);
		fun >> (TPMS_RearLeftTirePressure);
		fun >> (TPMS_RearRightTirePressure);
		fun >> (TPMS_FrontLeftTireTemperature);
		fun >> (TPMS_FrontRightTireTemperature);
		fun >> (TPMS_RearRightTireTemperature);
		fun >> (TPMS_RearLeftTireTemperature);
		fun >> (TPMS_FrontLeftTireLowPressure);
		fun >> (TPMS_FrontRightTireLowPressure);
		fun >> (TPMS_RearRightTireLowPressure);
		fun >> (TPMS_RearLeftTireLowPressure);
		fun >> (TPMS_FrontLeftTireHighPressure);
		fun >> (TPMS_FrontRightTireHighPressure);
		fun >> (TPMS_RearRightTireHighPressure);
		fun >> (TPMS_RearLeftTireHighPressure);
		fun >> (TPMS_FrontLeftTireHighTemperature);
		fun >> (TPMS_FrontRightTireHighTemperature);
		fun >> (TPMS_RearRightTireHighTemperature);
		fun >> (TPMS_RearLeftTireHighTemperature);
		fun >> (EBSF_BattVolt);
		fun >> (EBSF_SOC);
		fun >> (EBSF_VoltSt);
		fun >> (ICM_BFLWarning);
		fun >> (VCU_DspChgCurr);
		fun >> (VCU_DspChgVolt);
		fun >> (BMS_ChgComplRemHour);
		fun >> (BMS_ChgComplRemMinute);
		fun >> (ICM_TotalOdometer);
		fun >> (BMS_BattSocDisp);
		fun >> (ICM_TotalOdometer_accurate);
		fun >> (VCU_VehRng);
		fun >> (VCU_EVRng);
		fun >> (HVAC_RAWCabinTemp);
		fun >> (AQM_PM25Data);
		fun >> (HVAC_DriverTempSelect);
		fun >> (HVAC_PsnTempSelect);
		fun >> (HVAC_WindExitSpd);
		fun >> (HVAC_ACSt);
		fun >> (UMM_UsageModeSt);
		fun >> (SSW_FLSeatVentSt);
		fun >> (SSW_FRSeatVentSt);
		fun >> (SSW_RLSeatVentSt);
		fun >> (SSW_RRSeatVentSt);
		fun >> (SSW_FLSeatHeatingSt);
		fun >> (SSW_FRSeatHeatingSt);
		fun >> (SSW_RLSeatHeatingSt);
		fun >> (SSW_RRSeatHeatingSt);
		fun >> (HRN_HornRunningSt);
		fun >> (IL_HazardIndLightOutputSt);
		fun >> (BCS_VehSpd);
		fun >> (VCU_DspDischgCurr);
		fun >> (VCU_DspDischgVolt);
		fun >> (PWL_WinCurrentPos_FLWinPst);
		fun >> (PWL_WinOpeationSt_FLWinSt);
		fun >> (PWL_WinCurrentPos_RLWinPst);
		fun >> (PWL_WinCurrentPos_RRWinPst);
		fun >> (PWL_WinOpeationSt_RLWinSt);
		fun >> (PWL_WinOpeationSt_RRWinSt);
		fun >> (PWL_WinCurrentPos_FRWinPst);
		fun >> (PWL_WinOpeationSt_FRWinSt);
	}
};

#endif //____BDCCLOUD1_H__
