#ifndef ____BDCHVAC3_H__
#define ____BDCHVAC3_H__


#include "cstdint"






struct BDCHVAC3 {
public:
	std::uint16_t HVAC_CompHPtemp;
	std::uint16_t HVAC_CompLPtemp;
	std::uint16_t HVAC_IconOutTemp;
	std::uint8_t HVAC_CompLP;
	std::uint16_t HVAC_OHXoutTemp;
	std::uint8_t HVAC_OHXoutPressure;
	std::uint16_t HVAC_RefrigerantPr;
	std::uint16_t HVAC_EVAoutTemp;
	std::uint8_t HVAC_EVAvalveSt;
	std::uint8_t HVAC_DehumidifyValveSt;
	std::uint8_t HVAC_CoolingValveSt;
	std::uint8_t HVAC_IconInletValveSt;
	std::uint8_t HVAC_HeatValveSt;
	std::uint16_t HVAC_OHX_EXVCurrentPosition;
	std::uint16_t HVAC_CHI_EXVCurrentPosition;
	std::uint16_t HVAC_EVA_EXVCurrentPosition;
	std::uint8_t HVAC_ECV_PosnSet;
	std::uint8_t HVAC_ECPInputVolt;
	std::uint8_t HVAC_ECPInputCurr;
	std::uint8_t HVAC_ECPPhaseCurr;
	std::uint8_t HVAC_ECPSpdDuty;
	std::uint8_t HVAC_PTCHVDCCurrent;
	std::uint8_t HVAC_PTCHVVoltage;
	std::uint8_t HVAC_PTCInterWaterTemp1;
	std::uint8_t HVAC_PTCActDutyCycle;
	std::uint8_t AQM_AirQualitySnsLevel;
	std::uint8_t AQM_CO2CleanReq;
	std::uint8_t AQM_FreshPopReq;
	std::uint8_t AQM_CO2WorkCmd;
	std::uint8_t AQM_PM25CleanReq;
	std::uint8_t AQM_IonModeReq;
	std::uint8_t AQM_IonMode;
	std::uint8_t AQM_FraganceTaste;
	std::uint8_t AQM_FraganceConcentration;
	std::uint8_t AQM_FraganceBoxID;
	std::uint8_t AQM_FraganceBoxLoad;
	std::uint8_t AQM_UVCSwitch;
	std::uint8_t AQM_BlowerSt;
	std::uint8_t AQM_FraganceSwitchSt;
	std::uint8_t HVAC_SceneDisplayReq;
	std::uint8_t HVAC_UnlockVentilationSt;
	std::uint8_t HVAC_DrAirCirculationReq;
	std::uint8_t HVAC_PaAirCirculationReq;
	std::uint8_t HVAC_RearDefrostSt;
	std::uint8_t HVAC_ACSt;
	std::uint8_t HVAC_AutoDefCfgSt;
	std::uint8_t HVAC_DualSyncSt;
	std::uint8_t HVAC_AutoSt;
	std::uint8_t HVAC_WindExitMode;
	std::uint8_t HVAC_AirCirculationSt;
	std::uint8_t HVAC_ECOSt;
	std::uint8_t HVAC_WindExitSpd;
	std::uint8_t HVAC_WindExitSpdPercent;
	std::uint16_t HVAC_PTCPwrConsmp;
	std::uint8_t HVAC_DriverTempSelect;
	std::uint8_t HVAC_PsnTempSelect;
	std::uint8_t HVAC_EvapratorSelfCleanSt;
	std::uint8_t HVAC_CorrectedExterTemp;
	std::uint8_t HVAC_PTCHeatingReq;
	std::uint8_t HVAC_DrAMDoorPostion;
	std::uint8_t HVAC_PaAMDoorPostion;
	std::uint8_t HVAC_HeaterPumpSpdSet;
	std::uint8_t HVAC_DualCircuSt;
	std::uint8_t HVAC_AirCompressorReq;
	std::uint8_t HVAC_ECPTargetDuty;
	std::uint8_t HVAC_ECPwrLimit;
	std::uint8_t HVAC_CoolFanDutyCycleReq;
	std::uint8_t HVAC_CondDefSt;
	std::uint8_t HVAC_StsCabinCoolPrioReq;
	std::uint8_t HVAC_StsCabinHeatPrioReq;
	std::uint8_t HVAC_ActGrillDutyCycleReq;
	std::uint8_t HVAC_CorrectedCabinTemp;
	std::uint8_t HVAC_HeatPumpMode;
	std::uint8_t HVAC_CabinHeatReq;
	std::uint8_t HVAC_AirCirculationReq;
/*
	BDCHVAC3() {}
	~BDCHVAC3() {}
	BDCHVAC3(const std::uint16_t _HVAC_CompHPtemp,const std::uint16_t _HVAC_CompLPtemp,const std::uint16_t _HVAC_IconOutTemp,const std::uint8_t _HVAC_CompLP,const std::uint16_t _HVAC_OHXoutTemp,const std::uint8_t _HVAC_OHXoutPressure,const std::uint16_t _HVAC_RefrigerantPr,const std::uint16_t _HVAC_EVAoutTemp,const std::uint8_t _HVAC_EVAvalveSt,const std::uint8_t _HVAC_DehumidifyValveSt,const std::uint8_t _HVAC_CoolingValveSt,const std::uint8_t _HVAC_IconInletValveSt,const std::uint8_t _HVAC_HeatValveSt,const std::uint16_t _HVAC_OHX_EXVCurrentPosition,const std::uint16_t _HVAC_CHI_EXVCurrentPosition,const std::uint16_t _HVAC_EVA_EXVCurrentPosition,const std::uint8_t _HVAC_ECV_PosnSet,const std::uint8_t _HVAC_ECPInputVolt,const std::uint8_t _HVAC_ECPInputCurr,const std::uint8_t _HVAC_ECPPhaseCurr,const std::uint8_t _HVAC_ECPSpdDuty,const std::uint8_t _HVAC_PTCHVDCCurrent,const std::uint8_t _HVAC_PTCHVVoltage,const std::uint8_t _HVAC_PTCInterWaterTemp1,const std::uint8_t _HVAC_PTCActDutyCycle,const std::uint8_t _AQM_AirQualitySnsLevel,const std::uint8_t _AQM_CO2CleanReq,const std::uint8_t _AQM_FreshPopReq,const std::uint8_t _AQM_CO2WorkCmd,const std::uint8_t _AQM_PM25CleanReq,const std::uint8_t _AQM_IonModeReq,const std::uint8_t _AQM_IonMode,const std::uint8_t _AQM_FraganceTaste,const std::uint8_t _AQM_FraganceConcentration,const std::uint8_t _AQM_FraganceBoxID,const std::uint8_t _AQM_FraganceBoxLoad,const std::uint8_t _AQM_UVCSwitch,const std::uint8_t _AQM_BlowerSt,const std::uint8_t _AQM_FraganceSwitchSt,const std::uint8_t _HVAC_SceneDisplayReq,const std::uint8_t _HVAC_UnlockVentilationSt,const std::uint8_t _HVAC_DrAirCirculationReq,const std::uint8_t _HVAC_PaAirCirculationReq,const std::uint8_t _HVAC_RearDefrostSt,const std::uint8_t _HVAC_ACSt,const std::uint8_t _HVAC_AutoDefCfgSt,const std::uint8_t _HVAC_DualSyncSt,const std::uint8_t _HVAC_AutoSt,const std::uint8_t _HVAC_WindExitMode,const std::uint8_t _HVAC_AirCirculationSt,const std::uint8_t _HVAC_ECOSt,const std::uint8_t _HVAC_WindExitSpd,const std::uint8_t _HVAC_WindExitSpdPercent,const std::uint16_t _HVAC_PTCPwrConsmp,const std::uint8_t _HVAC_DriverTempSelect,const std::uint8_t _HVAC_PsnTempSelect,const std::uint8_t _HVAC_EvapratorSelfCleanSt,const std::uint8_t _HVAC_CorrectedExterTemp,const std::uint8_t _HVAC_PTCHeatingReq,const std::uint8_t _HVAC_DrAMDoorPostion,const std::uint8_t _HVAC_PaAMDoorPostion,const std::uint8_t _HVAC_HeaterPumpSpdSet,const std::uint8_t _HVAC_DualCircuSt,const std::uint8_t _HVAC_AirCompressorReq,const std::uint8_t _HVAC_ECPTargetDuty,const std::uint8_t _HVAC_ECPwrLimit,const std::uint8_t _HVAC_CoolFanDutyCycleReq,const std::uint8_t _HVAC_CondDefSt,const std::uint8_t _HVAC_StsCabinCoolPrioReq,const std::uint8_t _HVAC_StsCabinHeatPrioReq,const std::uint8_t _HVAC_ActGrillDutyCycleReq,const std::uint8_t _HVAC_CorrectedCabinTemp,const std::uint8_t _HVAC_HeatPumpMode,const std::uint8_t _HVAC_CabinHeatReq,const std::uint8_t _HVAC_AirCirculationReq):HVAC_CompHPtemp(_HVAC_CompHPtemp),HVAC_CompLPtemp(_HVAC_CompLPtemp),HVAC_IconOutTemp(_HVAC_IconOutTemp),HVAC_CompLP(_HVAC_CompLP),HVAC_OHXoutTemp(_HVAC_OHXoutTemp),HVAC_OHXoutPressure(_HVAC_OHXoutPressure),HVAC_RefrigerantPr(_HVAC_RefrigerantPr),HVAC_EVAoutTemp(_HVAC_EVAoutTemp),HVAC_EVAvalveSt(_HVAC_EVAvalveSt),HVAC_DehumidifyValveSt(_HVAC_DehumidifyValveSt),HVAC_CoolingValveSt(_HVAC_CoolingValveSt),HVAC_IconInletValveSt(_HVAC_IconInletValveSt),HVAC_HeatValveSt(_HVAC_HeatValveSt),HVAC_OHX_EXVCurrentPosition(_HVAC_OHX_EXVCurrentPosition),HVAC_CHI_EXVCurrentPosition(_HVAC_CHI_EXVCurrentPosition),HVAC_EVA_EXVCurrentPosition(_HVAC_EVA_EXVCurrentPosition),HVAC_ECV_PosnSet(_HVAC_ECV_PosnSet),HVAC_ECPInputVolt(_HVAC_ECPInputVolt),HVAC_ECPInputCurr(_HVAC_ECPInputCurr),HVAC_ECPPhaseCurr(_HVAC_ECPPhaseCurr),HVAC_ECPSpdDuty(_HVAC_ECPSpdDuty),HVAC_PTCHVDCCurrent(_HVAC_PTCHVDCCurrent),HVAC_PTCHVVoltage(_HVAC_PTCHVVoltage),HVAC_PTCInterWaterTemp1(_HVAC_PTCInterWaterTemp1),HVAC_PTCActDutyCycle(_HVAC_PTCActDutyCycle),AQM_AirQualitySnsLevel(_AQM_AirQualitySnsLevel),AQM_CO2CleanReq(_AQM_CO2CleanReq),AQM_FreshPopReq(_AQM_FreshPopReq),AQM_CO2WorkCmd(_AQM_CO2WorkCmd),AQM_PM25CleanReq(_AQM_PM25CleanReq),AQM_IonModeReq(_AQM_IonModeReq),AQM_IonMode(_AQM_IonMode),AQM_FraganceTaste(_AQM_FraganceTaste),AQM_FraganceConcentration(_AQM_FraganceConcentration),AQM_FraganceBoxID(_AQM_FraganceBoxID),AQM_FraganceBoxLoad(_AQM_FraganceBoxLoad),AQM_UVCSwitch(_AQM_UVCSwitch),AQM_BlowerSt(_AQM_BlowerSt),AQM_FraganceSwitchSt(_AQM_FraganceSwitchSt),HVAC_SceneDisplayReq(_HVAC_SceneDisplayReq),HVAC_UnlockVentilationSt(_HVAC_UnlockVentilationSt),HVAC_DrAirCirculationReq(_HVAC_DrAirCirculationReq),HVAC_PaAirCirculationReq(_HVAC_PaAirCirculationReq),HVAC_RearDefrostSt(_HVAC_RearDefrostSt),HVAC_ACSt(_HVAC_ACSt),HVAC_AutoDefCfgSt(_HVAC_AutoDefCfgSt),HVAC_DualSyncSt(_HVAC_DualSyncSt),HVAC_AutoSt(_HVAC_AutoSt),HVAC_WindExitMode(_HVAC_WindExitMode),HVAC_AirCirculationSt(_HVAC_AirCirculationSt),HVAC_ECOSt(_HVAC_ECOSt),HVAC_WindExitSpd(_HVAC_WindExitSpd),HVAC_WindExitSpdPercent(_HVAC_WindExitSpdPercent),HVAC_PTCPwrConsmp(_HVAC_PTCPwrConsmp),HVAC_DriverTempSelect(_HVAC_DriverTempSelect),HVAC_PsnTempSelect(_HVAC_PsnTempSelect),HVAC_EvapratorSelfCleanSt(_HVAC_EvapratorSelfCleanSt),HVAC_CorrectedExterTemp(_HVAC_CorrectedExterTemp),HVAC_PTCHeatingReq(_HVAC_PTCHeatingReq),HVAC_DrAMDoorPostion(_HVAC_DrAMDoorPostion),HVAC_PaAMDoorPostion(_HVAC_PaAMDoorPostion),HVAC_HeaterPumpSpdSet(_HVAC_HeaterPumpSpdSet),HVAC_DualCircuSt(_HVAC_DualCircuSt),HVAC_AirCompressorReq(_HVAC_AirCompressorReq),HVAC_ECPTargetDuty(_HVAC_ECPTargetDuty),HVAC_ECPwrLimit(_HVAC_ECPwrLimit),HVAC_CoolFanDutyCycleReq(_HVAC_CoolFanDutyCycleReq),HVAC_CondDefSt(_HVAC_CondDefSt),HVAC_StsCabinCoolPrioReq(_HVAC_StsCabinCoolPrioReq),HVAC_StsCabinHeatPrioReq(_HVAC_StsCabinHeatPrioReq),HVAC_ActGrillDutyCycleReq(_HVAC_ActGrillDutyCycleReq),HVAC_CorrectedCabinTemp(_HVAC_CorrectedCabinTemp),HVAC_HeatPumpMode(_HVAC_HeatPumpMode),HVAC_CabinHeatReq(_HVAC_CabinHeatReq),HVAC_AirCirculationReq(_HVAC_AirCirculationReq) {}
	BDCHVAC3(const BDCHVAC3 &_x){
		HVAC_CompHPtemp = _x.HVAC_CompHPtemp;
		HVAC_CompLPtemp = _x.HVAC_CompLPtemp;
		HVAC_IconOutTemp = _x.HVAC_IconOutTemp;
		HVAC_CompLP = _x.HVAC_CompLP;
		HVAC_OHXoutTemp = _x.HVAC_OHXoutTemp;
		HVAC_OHXoutPressure = _x.HVAC_OHXoutPressure;
		HVAC_RefrigerantPr = _x.HVAC_RefrigerantPr;
		HVAC_EVAoutTemp = _x.HVAC_EVAoutTemp;
		HVAC_EVAvalveSt = _x.HVAC_EVAvalveSt;
		HVAC_DehumidifyValveSt = _x.HVAC_DehumidifyValveSt;
		HVAC_CoolingValveSt = _x.HVAC_CoolingValveSt;
		HVAC_IconInletValveSt = _x.HVAC_IconInletValveSt;
		HVAC_HeatValveSt = _x.HVAC_HeatValveSt;
		HVAC_OHX_EXVCurrentPosition = _x.HVAC_OHX_EXVCurrentPosition;
		HVAC_CHI_EXVCurrentPosition = _x.HVAC_CHI_EXVCurrentPosition;
		HVAC_EVA_EXVCurrentPosition = _x.HVAC_EVA_EXVCurrentPosition;
		HVAC_ECV_PosnSet = _x.HVAC_ECV_PosnSet;
		HVAC_ECPInputVolt = _x.HVAC_ECPInputVolt;
		HVAC_ECPInputCurr = _x.HVAC_ECPInputCurr;
		HVAC_ECPPhaseCurr = _x.HVAC_ECPPhaseCurr;
		HVAC_ECPSpdDuty = _x.HVAC_ECPSpdDuty;
		HVAC_PTCHVDCCurrent = _x.HVAC_PTCHVDCCurrent;
		HVAC_PTCHVVoltage = _x.HVAC_PTCHVVoltage;
		HVAC_PTCInterWaterTemp1 = _x.HVAC_PTCInterWaterTemp1;
		HVAC_PTCActDutyCycle = _x.HVAC_PTCActDutyCycle;
		AQM_AirQualitySnsLevel = _x.AQM_AirQualitySnsLevel;
		AQM_CO2CleanReq = _x.AQM_CO2CleanReq;
		AQM_FreshPopReq = _x.AQM_FreshPopReq;
		AQM_CO2WorkCmd = _x.AQM_CO2WorkCmd;
		AQM_PM25CleanReq = _x.AQM_PM25CleanReq;
		AQM_IonModeReq = _x.AQM_IonModeReq;
		AQM_IonMode = _x.AQM_IonMode;
		AQM_FraganceTaste = _x.AQM_FraganceTaste;
		AQM_FraganceConcentration = _x.AQM_FraganceConcentration;
		AQM_FraganceBoxID = _x.AQM_FraganceBoxID;
		AQM_FraganceBoxLoad = _x.AQM_FraganceBoxLoad;
		AQM_UVCSwitch = _x.AQM_UVCSwitch;
		AQM_BlowerSt = _x.AQM_BlowerSt;
		AQM_FraganceSwitchSt = _x.AQM_FraganceSwitchSt;
		HVAC_SceneDisplayReq = _x.HVAC_SceneDisplayReq;
		HVAC_UnlockVentilationSt = _x.HVAC_UnlockVentilationSt;
		HVAC_DrAirCirculationReq = _x.HVAC_DrAirCirculationReq;
		HVAC_PaAirCirculationReq = _x.HVAC_PaAirCirculationReq;
		HVAC_RearDefrostSt = _x.HVAC_RearDefrostSt;
		HVAC_ACSt = _x.HVAC_ACSt;
		HVAC_AutoDefCfgSt = _x.HVAC_AutoDefCfgSt;
		HVAC_DualSyncSt = _x.HVAC_DualSyncSt;
		HVAC_AutoSt = _x.HVAC_AutoSt;
		HVAC_WindExitMode = _x.HVAC_WindExitMode;
		HVAC_AirCirculationSt = _x.HVAC_AirCirculationSt;
		HVAC_ECOSt = _x.HVAC_ECOSt;
		HVAC_WindExitSpd = _x.HVAC_WindExitSpd;
		HVAC_WindExitSpdPercent = _x.HVAC_WindExitSpdPercent;
		HVAC_PTCPwrConsmp = _x.HVAC_PTCPwrConsmp;
		HVAC_DriverTempSelect = _x.HVAC_DriverTempSelect;
		HVAC_PsnTempSelect = _x.HVAC_PsnTempSelect;
		HVAC_EvapratorSelfCleanSt = _x.HVAC_EvapratorSelfCleanSt;
		HVAC_CorrectedExterTemp = _x.HVAC_CorrectedExterTemp;
		HVAC_PTCHeatingReq = _x.HVAC_PTCHeatingReq;
		HVAC_DrAMDoorPostion = _x.HVAC_DrAMDoorPostion;
		HVAC_PaAMDoorPostion = _x.HVAC_PaAMDoorPostion;
		HVAC_HeaterPumpSpdSet = _x.HVAC_HeaterPumpSpdSet;
		HVAC_DualCircuSt = _x.HVAC_DualCircuSt;
		HVAC_AirCompressorReq = _x.HVAC_AirCompressorReq;
		HVAC_ECPTargetDuty = _x.HVAC_ECPTargetDuty;
		HVAC_ECPwrLimit = _x.HVAC_ECPwrLimit;
		HVAC_CoolFanDutyCycleReq = _x.HVAC_CoolFanDutyCycleReq;
		HVAC_CondDefSt = _x.HVAC_CondDefSt;
		HVAC_StsCabinCoolPrioReq = _x.HVAC_StsCabinCoolPrioReq;
		HVAC_StsCabinHeatPrioReq = _x.HVAC_StsCabinHeatPrioReq;
		HVAC_ActGrillDutyCycleReq = _x.HVAC_ActGrillDutyCycleReq;
		HVAC_CorrectedCabinTemp = _x.HVAC_CorrectedCabinTemp;
		HVAC_HeatPumpMode = _x.HVAC_HeatPumpMode;
		HVAC_CabinHeatReq = _x.HVAC_CabinHeatReq;
		HVAC_AirCirculationReq = _x.HVAC_AirCirculationReq;
	}
	BDCHVAC3(BDCHVAC3 &&_x){
		HVAC_CompHPtemp = std::move(_x.HVAC_CompHPtemp);
		HVAC_CompLPtemp = std::move(_x.HVAC_CompLPtemp);
		HVAC_IconOutTemp = std::move(_x.HVAC_IconOutTemp);
		HVAC_CompLP = std::move(_x.HVAC_CompLP);
		HVAC_OHXoutTemp = std::move(_x.HVAC_OHXoutTemp);
		HVAC_OHXoutPressure = std::move(_x.HVAC_OHXoutPressure);
		HVAC_RefrigerantPr = std::move(_x.HVAC_RefrigerantPr);
		HVAC_EVAoutTemp = std::move(_x.HVAC_EVAoutTemp);
		HVAC_EVAvalveSt = std::move(_x.HVAC_EVAvalveSt);
		HVAC_DehumidifyValveSt = std::move(_x.HVAC_DehumidifyValveSt);
		HVAC_CoolingValveSt = std::move(_x.HVAC_CoolingValveSt);
		HVAC_IconInletValveSt = std::move(_x.HVAC_IconInletValveSt);
		HVAC_HeatValveSt = std::move(_x.HVAC_HeatValveSt);
		HVAC_OHX_EXVCurrentPosition = std::move(_x.HVAC_OHX_EXVCurrentPosition);
		HVAC_CHI_EXVCurrentPosition = std::move(_x.HVAC_CHI_EXVCurrentPosition);
		HVAC_EVA_EXVCurrentPosition = std::move(_x.HVAC_EVA_EXVCurrentPosition);
		HVAC_ECV_PosnSet = std::move(_x.HVAC_ECV_PosnSet);
		HVAC_ECPInputVolt = std::move(_x.HVAC_ECPInputVolt);
		HVAC_ECPInputCurr = std::move(_x.HVAC_ECPInputCurr);
		HVAC_ECPPhaseCurr = std::move(_x.HVAC_ECPPhaseCurr);
		HVAC_ECPSpdDuty = std::move(_x.HVAC_ECPSpdDuty);
		HVAC_PTCHVDCCurrent = std::move(_x.HVAC_PTCHVDCCurrent);
		HVAC_PTCHVVoltage = std::move(_x.HVAC_PTCHVVoltage);
		HVAC_PTCInterWaterTemp1 = std::move(_x.HVAC_PTCInterWaterTemp1);
		HVAC_PTCActDutyCycle = std::move(_x.HVAC_PTCActDutyCycle);
		AQM_AirQualitySnsLevel = std::move(_x.AQM_AirQualitySnsLevel);
		AQM_CO2CleanReq = std::move(_x.AQM_CO2CleanReq);
		AQM_FreshPopReq = std::move(_x.AQM_FreshPopReq);
		AQM_CO2WorkCmd = std::move(_x.AQM_CO2WorkCmd);
		AQM_PM25CleanReq = std::move(_x.AQM_PM25CleanReq);
		AQM_IonModeReq = std::move(_x.AQM_IonModeReq);
		AQM_IonMode = std::move(_x.AQM_IonMode);
		AQM_FraganceTaste = std::move(_x.AQM_FraganceTaste);
		AQM_FraganceConcentration = std::move(_x.AQM_FraganceConcentration);
		AQM_FraganceBoxID = std::move(_x.AQM_FraganceBoxID);
		AQM_FraganceBoxLoad = std::move(_x.AQM_FraganceBoxLoad);
		AQM_UVCSwitch = std::move(_x.AQM_UVCSwitch);
		AQM_BlowerSt = std::move(_x.AQM_BlowerSt);
		AQM_FraganceSwitchSt = std::move(_x.AQM_FraganceSwitchSt);
		HVAC_SceneDisplayReq = std::move(_x.HVAC_SceneDisplayReq);
		HVAC_UnlockVentilationSt = std::move(_x.HVAC_UnlockVentilationSt);
		HVAC_DrAirCirculationReq = std::move(_x.HVAC_DrAirCirculationReq);
		HVAC_PaAirCirculationReq = std::move(_x.HVAC_PaAirCirculationReq);
		HVAC_RearDefrostSt = std::move(_x.HVAC_RearDefrostSt);
		HVAC_ACSt = std::move(_x.HVAC_ACSt);
		HVAC_AutoDefCfgSt = std::move(_x.HVAC_AutoDefCfgSt);
		HVAC_DualSyncSt = std::move(_x.HVAC_DualSyncSt);
		HVAC_AutoSt = std::move(_x.HVAC_AutoSt);
		HVAC_WindExitMode = std::move(_x.HVAC_WindExitMode);
		HVAC_AirCirculationSt = std::move(_x.HVAC_AirCirculationSt);
		HVAC_ECOSt = std::move(_x.HVAC_ECOSt);
		HVAC_WindExitSpd = std::move(_x.HVAC_WindExitSpd);
		HVAC_WindExitSpdPercent = std::move(_x.HVAC_WindExitSpdPercent);
		HVAC_PTCPwrConsmp = std::move(_x.HVAC_PTCPwrConsmp);
		HVAC_DriverTempSelect = std::move(_x.HVAC_DriverTempSelect);
		HVAC_PsnTempSelect = std::move(_x.HVAC_PsnTempSelect);
		HVAC_EvapratorSelfCleanSt = std::move(_x.HVAC_EvapratorSelfCleanSt);
		HVAC_CorrectedExterTemp = std::move(_x.HVAC_CorrectedExterTemp);
		HVAC_PTCHeatingReq = std::move(_x.HVAC_PTCHeatingReq);
		HVAC_DrAMDoorPostion = std::move(_x.HVAC_DrAMDoorPostion);
		HVAC_PaAMDoorPostion = std::move(_x.HVAC_PaAMDoorPostion);
		HVAC_HeaterPumpSpdSet = std::move(_x.HVAC_HeaterPumpSpdSet);
		HVAC_DualCircuSt = std::move(_x.HVAC_DualCircuSt);
		HVAC_AirCompressorReq = std::move(_x.HVAC_AirCompressorReq);
		HVAC_ECPTargetDuty = std::move(_x.HVAC_ECPTargetDuty);
		HVAC_ECPwrLimit = std::move(_x.HVAC_ECPwrLimit);
		HVAC_CoolFanDutyCycleReq = std::move(_x.HVAC_CoolFanDutyCycleReq);
		HVAC_CondDefSt = std::move(_x.HVAC_CondDefSt);
		HVAC_StsCabinCoolPrioReq = std::move(_x.HVAC_StsCabinCoolPrioReq);
		HVAC_StsCabinHeatPrioReq = std::move(_x.HVAC_StsCabinHeatPrioReq);
		HVAC_ActGrillDutyCycleReq = std::move(_x.HVAC_ActGrillDutyCycleReq);
		HVAC_CorrectedCabinTemp = std::move(_x.HVAC_CorrectedCabinTemp);
		HVAC_HeatPumpMode = std::move(_x.HVAC_HeatPumpMode);
		HVAC_CabinHeatReq = std::move(_x.HVAC_CabinHeatReq);
		HVAC_AirCirculationReq = std::move(_x.HVAC_AirCirculationReq);
	}
	BDCHVAC3& operator=(const BDCHVAC3 &_x){
		HVAC_CompHPtemp = _x.HVAC_CompHPtemp;
		HVAC_CompLPtemp = _x.HVAC_CompLPtemp;
		HVAC_IconOutTemp = _x.HVAC_IconOutTemp;
		HVAC_CompLP = _x.HVAC_CompLP;
		HVAC_OHXoutTemp = _x.HVAC_OHXoutTemp;
		HVAC_OHXoutPressure = _x.HVAC_OHXoutPressure;
		HVAC_RefrigerantPr = _x.HVAC_RefrigerantPr;
		HVAC_EVAoutTemp = _x.HVAC_EVAoutTemp;
		HVAC_EVAvalveSt = _x.HVAC_EVAvalveSt;
		HVAC_DehumidifyValveSt = _x.HVAC_DehumidifyValveSt;
		HVAC_CoolingValveSt = _x.HVAC_CoolingValveSt;
		HVAC_IconInletValveSt = _x.HVAC_IconInletValveSt;
		HVAC_HeatValveSt = _x.HVAC_HeatValveSt;
		HVAC_OHX_EXVCurrentPosition = _x.HVAC_OHX_EXVCurrentPosition;
		HVAC_CHI_EXVCurrentPosition = _x.HVAC_CHI_EXVCurrentPosition;
		HVAC_EVA_EXVCurrentPosition = _x.HVAC_EVA_EXVCurrentPosition;
		HVAC_ECV_PosnSet = _x.HVAC_ECV_PosnSet;
		HVAC_ECPInputVolt = _x.HVAC_ECPInputVolt;
		HVAC_ECPInputCurr = _x.HVAC_ECPInputCurr;
		HVAC_ECPPhaseCurr = _x.HVAC_ECPPhaseCurr;
		HVAC_ECPSpdDuty = _x.HVAC_ECPSpdDuty;
		HVAC_PTCHVDCCurrent = _x.HVAC_PTCHVDCCurrent;
		HVAC_PTCHVVoltage = _x.HVAC_PTCHVVoltage;
		HVAC_PTCInterWaterTemp1 = _x.HVAC_PTCInterWaterTemp1;
		HVAC_PTCActDutyCycle = _x.HVAC_PTCActDutyCycle;
		AQM_AirQualitySnsLevel = _x.AQM_AirQualitySnsLevel;
		AQM_CO2CleanReq = _x.AQM_CO2CleanReq;
		AQM_FreshPopReq = _x.AQM_FreshPopReq;
		AQM_CO2WorkCmd = _x.AQM_CO2WorkCmd;
		AQM_PM25CleanReq = _x.AQM_PM25CleanReq;
		AQM_IonModeReq = _x.AQM_IonModeReq;
		AQM_IonMode = _x.AQM_IonMode;
		AQM_FraganceTaste = _x.AQM_FraganceTaste;
		AQM_FraganceConcentration = _x.AQM_FraganceConcentration;
		AQM_FraganceBoxID = _x.AQM_FraganceBoxID;
		AQM_FraganceBoxLoad = _x.AQM_FraganceBoxLoad;
		AQM_UVCSwitch = _x.AQM_UVCSwitch;
		AQM_BlowerSt = _x.AQM_BlowerSt;
		AQM_FraganceSwitchSt = _x.AQM_FraganceSwitchSt;
		HVAC_SceneDisplayReq = _x.HVAC_SceneDisplayReq;
		HVAC_UnlockVentilationSt = _x.HVAC_UnlockVentilationSt;
		HVAC_DrAirCirculationReq = _x.HVAC_DrAirCirculationReq;
		HVAC_PaAirCirculationReq = _x.HVAC_PaAirCirculationReq;
		HVAC_RearDefrostSt = _x.HVAC_RearDefrostSt;
		HVAC_ACSt = _x.HVAC_ACSt;
		HVAC_AutoDefCfgSt = _x.HVAC_AutoDefCfgSt;
		HVAC_DualSyncSt = _x.HVAC_DualSyncSt;
		HVAC_AutoSt = _x.HVAC_AutoSt;
		HVAC_WindExitMode = _x.HVAC_WindExitMode;
		HVAC_AirCirculationSt = _x.HVAC_AirCirculationSt;
		HVAC_ECOSt = _x.HVAC_ECOSt;
		HVAC_WindExitSpd = _x.HVAC_WindExitSpd;
		HVAC_WindExitSpdPercent = _x.HVAC_WindExitSpdPercent;
		HVAC_PTCPwrConsmp = _x.HVAC_PTCPwrConsmp;
		HVAC_DriverTempSelect = _x.HVAC_DriverTempSelect;
		HVAC_PsnTempSelect = _x.HVAC_PsnTempSelect;
		HVAC_EvapratorSelfCleanSt = _x.HVAC_EvapratorSelfCleanSt;
		HVAC_CorrectedExterTemp = _x.HVAC_CorrectedExterTemp;
		HVAC_PTCHeatingReq = _x.HVAC_PTCHeatingReq;
		HVAC_DrAMDoorPostion = _x.HVAC_DrAMDoorPostion;
		HVAC_PaAMDoorPostion = _x.HVAC_PaAMDoorPostion;
		HVAC_HeaterPumpSpdSet = _x.HVAC_HeaterPumpSpdSet;
		HVAC_DualCircuSt = _x.HVAC_DualCircuSt;
		HVAC_AirCompressorReq = _x.HVAC_AirCompressorReq;
		HVAC_ECPTargetDuty = _x.HVAC_ECPTargetDuty;
		HVAC_ECPwrLimit = _x.HVAC_ECPwrLimit;
		HVAC_CoolFanDutyCycleReq = _x.HVAC_CoolFanDutyCycleReq;
		HVAC_CondDefSt = _x.HVAC_CondDefSt;
		HVAC_StsCabinCoolPrioReq = _x.HVAC_StsCabinCoolPrioReq;
		HVAC_StsCabinHeatPrioReq = _x.HVAC_StsCabinHeatPrioReq;
		HVAC_ActGrillDutyCycleReq = _x.HVAC_ActGrillDutyCycleReq;
		HVAC_CorrectedCabinTemp = _x.HVAC_CorrectedCabinTemp;
		HVAC_HeatPumpMode = _x.HVAC_HeatPumpMode;
		HVAC_CabinHeatReq = _x.HVAC_CabinHeatReq;
		HVAC_AirCirculationReq = _x.HVAC_AirCirculationReq;
		return *this;
	}
	BDCHVAC3& operator=(BDCHVAC3 &&_x){
		HVAC_CompHPtemp = std::move(_x.HVAC_CompHPtemp);
		HVAC_CompLPtemp = std::move(_x.HVAC_CompLPtemp);
		HVAC_IconOutTemp = std::move(_x.HVAC_IconOutTemp);
		HVAC_CompLP = std::move(_x.HVAC_CompLP);
		HVAC_OHXoutTemp = std::move(_x.HVAC_OHXoutTemp);
		HVAC_OHXoutPressure = std::move(_x.HVAC_OHXoutPressure);
		HVAC_RefrigerantPr = std::move(_x.HVAC_RefrigerantPr);
		HVAC_EVAoutTemp = std::move(_x.HVAC_EVAoutTemp);
		HVAC_EVAvalveSt = std::move(_x.HVAC_EVAvalveSt);
		HVAC_DehumidifyValveSt = std::move(_x.HVAC_DehumidifyValveSt);
		HVAC_CoolingValveSt = std::move(_x.HVAC_CoolingValveSt);
		HVAC_IconInletValveSt = std::move(_x.HVAC_IconInletValveSt);
		HVAC_HeatValveSt = std::move(_x.HVAC_HeatValveSt);
		HVAC_OHX_EXVCurrentPosition = std::move(_x.HVAC_OHX_EXVCurrentPosition);
		HVAC_CHI_EXVCurrentPosition = std::move(_x.HVAC_CHI_EXVCurrentPosition);
		HVAC_EVA_EXVCurrentPosition = std::move(_x.HVAC_EVA_EXVCurrentPosition);
		HVAC_ECV_PosnSet = std::move(_x.HVAC_ECV_PosnSet);
		HVAC_ECPInputVolt = std::move(_x.HVAC_ECPInputVolt);
		HVAC_ECPInputCurr = std::move(_x.HVAC_ECPInputCurr);
		HVAC_ECPPhaseCurr = std::move(_x.HVAC_ECPPhaseCurr);
		HVAC_ECPSpdDuty = std::move(_x.HVAC_ECPSpdDuty);
		HVAC_PTCHVDCCurrent = std::move(_x.HVAC_PTCHVDCCurrent);
		HVAC_PTCHVVoltage = std::move(_x.HVAC_PTCHVVoltage);
		HVAC_PTCInterWaterTemp1 = std::move(_x.HVAC_PTCInterWaterTemp1);
		HVAC_PTCActDutyCycle = std::move(_x.HVAC_PTCActDutyCycle);
		AQM_AirQualitySnsLevel = std::move(_x.AQM_AirQualitySnsLevel);
		AQM_CO2CleanReq = std::move(_x.AQM_CO2CleanReq);
		AQM_FreshPopReq = std::move(_x.AQM_FreshPopReq);
		AQM_CO2WorkCmd = std::move(_x.AQM_CO2WorkCmd);
		AQM_PM25CleanReq = std::move(_x.AQM_PM25CleanReq);
		AQM_IonModeReq = std::move(_x.AQM_IonModeReq);
		AQM_IonMode = std::move(_x.AQM_IonMode);
		AQM_FraganceTaste = std::move(_x.AQM_FraganceTaste);
		AQM_FraganceConcentration = std::move(_x.AQM_FraganceConcentration);
		AQM_FraganceBoxID = std::move(_x.AQM_FraganceBoxID);
		AQM_FraganceBoxLoad = std::move(_x.AQM_FraganceBoxLoad);
		AQM_UVCSwitch = std::move(_x.AQM_UVCSwitch);
		AQM_BlowerSt = std::move(_x.AQM_BlowerSt);
		AQM_FraganceSwitchSt = std::move(_x.AQM_FraganceSwitchSt);
		HVAC_SceneDisplayReq = std::move(_x.HVAC_SceneDisplayReq);
		HVAC_UnlockVentilationSt = std::move(_x.HVAC_UnlockVentilationSt);
		HVAC_DrAirCirculationReq = std::move(_x.HVAC_DrAirCirculationReq);
		HVAC_PaAirCirculationReq = std::move(_x.HVAC_PaAirCirculationReq);
		HVAC_RearDefrostSt = std::move(_x.HVAC_RearDefrostSt);
		HVAC_ACSt = std::move(_x.HVAC_ACSt);
		HVAC_AutoDefCfgSt = std::move(_x.HVAC_AutoDefCfgSt);
		HVAC_DualSyncSt = std::move(_x.HVAC_DualSyncSt);
		HVAC_AutoSt = std::move(_x.HVAC_AutoSt);
		HVAC_WindExitMode = std::move(_x.HVAC_WindExitMode);
		HVAC_AirCirculationSt = std::move(_x.HVAC_AirCirculationSt);
		HVAC_ECOSt = std::move(_x.HVAC_ECOSt);
		HVAC_WindExitSpd = std::move(_x.HVAC_WindExitSpd);
		HVAC_WindExitSpdPercent = std::move(_x.HVAC_WindExitSpdPercent);
		HVAC_PTCPwrConsmp = std::move(_x.HVAC_PTCPwrConsmp);
		HVAC_DriverTempSelect = std::move(_x.HVAC_DriverTempSelect);
		HVAC_PsnTempSelect = std::move(_x.HVAC_PsnTempSelect);
		HVAC_EvapratorSelfCleanSt = std::move(_x.HVAC_EvapratorSelfCleanSt);
		HVAC_CorrectedExterTemp = std::move(_x.HVAC_CorrectedExterTemp);
		HVAC_PTCHeatingReq = std::move(_x.HVAC_PTCHeatingReq);
		HVAC_DrAMDoorPostion = std::move(_x.HVAC_DrAMDoorPostion);
		HVAC_PaAMDoorPostion = std::move(_x.HVAC_PaAMDoorPostion);
		HVAC_HeaterPumpSpdSet = std::move(_x.HVAC_HeaterPumpSpdSet);
		HVAC_DualCircuSt = std::move(_x.HVAC_DualCircuSt);
		HVAC_AirCompressorReq = std::move(_x.HVAC_AirCompressorReq);
		HVAC_ECPTargetDuty = std::move(_x.HVAC_ECPTargetDuty);
		HVAC_ECPwrLimit = std::move(_x.HVAC_ECPwrLimit);
		HVAC_CoolFanDutyCycleReq = std::move(_x.HVAC_CoolFanDutyCycleReq);
		HVAC_CondDefSt = std::move(_x.HVAC_CondDefSt);
		HVAC_StsCabinCoolPrioReq = std::move(_x.HVAC_StsCabinCoolPrioReq);
		HVAC_StsCabinHeatPrioReq = std::move(_x.HVAC_StsCabinHeatPrioReq);
		HVAC_ActGrillDutyCycleReq = std::move(_x.HVAC_ActGrillDutyCycleReq);
		HVAC_CorrectedCabinTemp = std::move(_x.HVAC_CorrectedCabinTemp);
		HVAC_HeatPumpMode = std::move(_x.HVAC_HeatPumpMode);
		HVAC_CabinHeatReq = std::move(_x.HVAC_CabinHeatReq);
		HVAC_AirCirculationReq = std::move(_x.HVAC_AirCirculationReq);
		return *this;
	}
*/

	using IsEnumerableTag = void;
	template<typename F>
	void enumerate(F& fun) {
		fun(HVAC_CompHPtemp);
		fun(HVAC_CompLPtemp);
		fun(HVAC_IconOutTemp);
		fun(HVAC_CompLP);
		fun(HVAC_OHXoutTemp);
		fun(HVAC_OHXoutPressure);
		fun(HVAC_RefrigerantPr);
		fun(HVAC_EVAoutTemp);
		fun(HVAC_EVAvalveSt);
		fun(HVAC_DehumidifyValveSt);
		fun(HVAC_CoolingValveSt);
		fun(HVAC_IconInletValveSt);
		fun(HVAC_HeatValveSt);
		fun(HVAC_OHX_EXVCurrentPosition);
		fun(HVAC_CHI_EXVCurrentPosition);
		fun(HVAC_EVA_EXVCurrentPosition);
		fun(HVAC_ECV_PosnSet);
		fun(HVAC_ECPInputVolt);
		fun(HVAC_ECPInputCurr);
		fun(HVAC_ECPPhaseCurr);
		fun(HVAC_ECPSpdDuty);
		fun(HVAC_PTCHVDCCurrent);
		fun(HVAC_PTCHVVoltage);
		fun(HVAC_PTCInterWaterTemp1);
		fun(HVAC_PTCActDutyCycle);
		fun(AQM_AirQualitySnsLevel);
		fun(AQM_CO2CleanReq);
		fun(AQM_FreshPopReq);
		fun(AQM_CO2WorkCmd);
		fun(AQM_PM25CleanReq);
		fun(AQM_IonModeReq);
		fun(AQM_IonMode);
		fun(AQM_FraganceTaste);
		fun(AQM_FraganceConcentration);
		fun(AQM_FraganceBoxID);
		fun(AQM_FraganceBoxLoad);
		fun(AQM_UVCSwitch);
		fun(AQM_BlowerSt);
		fun(AQM_FraganceSwitchSt);
		fun(HVAC_SceneDisplayReq);
		fun(HVAC_UnlockVentilationSt);
		fun(HVAC_DrAirCirculationReq);
		fun(HVAC_PaAirCirculationReq);
		fun(HVAC_RearDefrostSt);
		fun(HVAC_ACSt);
		fun(HVAC_AutoDefCfgSt);
		fun(HVAC_DualSyncSt);
		fun(HVAC_AutoSt);
		fun(HVAC_WindExitMode);
		fun(HVAC_AirCirculationSt);
		fun(HVAC_ECOSt);
		fun(HVAC_WindExitSpd);
		fun(HVAC_WindExitSpdPercent);
		fun(HVAC_PTCPwrConsmp);
		fun(HVAC_DriverTempSelect);
		fun(HVAC_PsnTempSelect);
		fun(HVAC_EvapratorSelfCleanSt);
		fun(HVAC_CorrectedExterTemp);
		fun(HVAC_PTCHeatingReq);
		fun(HVAC_DrAMDoorPostion);
		fun(HVAC_PaAMDoorPostion);
		fun(HVAC_HeaterPumpSpdSet);
		fun(HVAC_DualCircuSt);
		fun(HVAC_AirCompressorReq);
		fun(HVAC_ECPTargetDuty);
		fun(HVAC_ECPwrLimit);
		fun(HVAC_CoolFanDutyCycleReq);
		fun(HVAC_CondDefSt);
		fun(HVAC_StsCabinCoolPrioReq);
		fun(HVAC_StsCabinHeatPrioReq);
		fun(HVAC_ActGrillDutyCycleReq);
		fun(HVAC_CorrectedCabinTemp);
		fun(HVAC_HeatPumpMode);
		fun(HVAC_CabinHeatReq);
		fun(HVAC_AirCirculationReq);
	}

	template<typename F>
	void GetSize(F& fun) const{
		fun(HVAC_CompHPtemp);
		fun(HVAC_CompLPtemp);
		fun(HVAC_IconOutTemp);
		fun(HVAC_CompLP);
		fun(HVAC_OHXoutTemp);
		fun(HVAC_OHXoutPressure);
		fun(HVAC_RefrigerantPr);
		fun(HVAC_EVAoutTemp);
		fun(HVAC_EVAvalveSt);
		fun(HVAC_DehumidifyValveSt);
		fun(HVAC_CoolingValveSt);
		fun(HVAC_IconInletValveSt);
		fun(HVAC_HeatValveSt);
		fun(HVAC_OHX_EXVCurrentPosition);
		fun(HVAC_CHI_EXVCurrentPosition);
		fun(HVAC_EVA_EXVCurrentPosition);
		fun(HVAC_ECV_PosnSet);
		fun(HVAC_ECPInputVolt);
		fun(HVAC_ECPInputCurr);
		fun(HVAC_ECPPhaseCurr);
		fun(HVAC_ECPSpdDuty);
		fun(HVAC_PTCHVDCCurrent);
		fun(HVAC_PTCHVVoltage);
		fun(HVAC_PTCInterWaterTemp1);
		fun(HVAC_PTCActDutyCycle);
		fun(AQM_AirQualitySnsLevel);
		fun(AQM_CO2CleanReq);
		fun(AQM_FreshPopReq);
		fun(AQM_CO2WorkCmd);
		fun(AQM_PM25CleanReq);
		fun(AQM_IonModeReq);
		fun(AQM_IonMode);
		fun(AQM_FraganceTaste);
		fun(AQM_FraganceConcentration);
		fun(AQM_FraganceBoxID);
		fun(AQM_FraganceBoxLoad);
		fun(AQM_UVCSwitch);
		fun(AQM_BlowerSt);
		fun(AQM_FraganceSwitchSt);
		fun(HVAC_SceneDisplayReq);
		fun(HVAC_UnlockVentilationSt);
		fun(HVAC_DrAirCirculationReq);
		fun(HVAC_PaAirCirculationReq);
		fun(HVAC_RearDefrostSt);
		fun(HVAC_ACSt);
		fun(HVAC_AutoDefCfgSt);
		fun(HVAC_DualSyncSt);
		fun(HVAC_AutoSt);
		fun(HVAC_WindExitMode);
		fun(HVAC_AirCirculationSt);
		fun(HVAC_ECOSt);
		fun(HVAC_WindExitSpd);
		fun(HVAC_WindExitSpdPercent);
		fun(HVAC_PTCPwrConsmp);
		fun(HVAC_DriverTempSelect);
		fun(HVAC_PsnTempSelect);
		fun(HVAC_EvapratorSelfCleanSt);
		fun(HVAC_CorrectedExterTemp);
		fun(HVAC_PTCHeatingReq);
		fun(HVAC_DrAMDoorPostion);
		fun(HVAC_PaAMDoorPostion);
		fun(HVAC_HeaterPumpSpdSet);
		fun(HVAC_DualCircuSt);
		fun(HVAC_AirCompressorReq);
		fun(HVAC_ECPTargetDuty);
		fun(HVAC_ECPwrLimit);
		fun(HVAC_CoolFanDutyCycleReq);
		fun(HVAC_CondDefSt);
		fun(HVAC_StsCabinCoolPrioReq);
		fun(HVAC_StsCabinHeatPrioReq);
		fun(HVAC_ActGrillDutyCycleReq);
		fun(HVAC_CorrectedCabinTemp);
		fun(HVAC_HeatPumpMode);
		fun(HVAC_CabinHeatReq);
		fun(HVAC_AirCirculationReq);
	}
	template<typename F>
	void serialize(F& fun) const{
		fun << (HVAC_CompHPtemp);
		fun << (HVAC_CompLPtemp);
		fun << (HVAC_IconOutTemp);
		fun << (HVAC_CompLP);
		fun << (HVAC_OHXoutTemp);
		fun << (HVAC_OHXoutPressure);
		fun << (HVAC_RefrigerantPr);
		fun << (HVAC_EVAoutTemp);
		fun << (HVAC_EVAvalveSt);
		fun << (HVAC_DehumidifyValveSt);
		fun << (HVAC_CoolingValveSt);
		fun << (HVAC_IconInletValveSt);
		fun << (HVAC_HeatValveSt);
		fun << (HVAC_OHX_EXVCurrentPosition);
		fun << (HVAC_CHI_EXVCurrentPosition);
		fun << (HVAC_EVA_EXVCurrentPosition);
		fun << (HVAC_ECV_PosnSet);
		fun << (HVAC_ECPInputVolt);
		fun << (HVAC_ECPInputCurr);
		fun << (HVAC_ECPPhaseCurr);
		fun << (HVAC_ECPSpdDuty);
		fun << (HVAC_PTCHVDCCurrent);
		fun << (HVAC_PTCHVVoltage);
		fun << (HVAC_PTCInterWaterTemp1);
		fun << (HVAC_PTCActDutyCycle);
		fun << (AQM_AirQualitySnsLevel);
		fun << (AQM_CO2CleanReq);
		fun << (AQM_FreshPopReq);
		fun << (AQM_CO2WorkCmd);
		fun << (AQM_PM25CleanReq);
		fun << (AQM_IonModeReq);
		fun << (AQM_IonMode);
		fun << (AQM_FraganceTaste);
		fun << (AQM_FraganceConcentration);
		fun << (AQM_FraganceBoxID);
		fun << (AQM_FraganceBoxLoad);
		fun << (AQM_UVCSwitch);
		fun << (AQM_BlowerSt);
		fun << (AQM_FraganceSwitchSt);
		fun << (HVAC_SceneDisplayReq);
		fun << (HVAC_UnlockVentilationSt);
		fun << (HVAC_DrAirCirculationReq);
		fun << (HVAC_PaAirCirculationReq);
		fun << (HVAC_RearDefrostSt);
		fun << (HVAC_ACSt);
		fun << (HVAC_AutoDefCfgSt);
		fun << (HVAC_DualSyncSt);
		fun << (HVAC_AutoSt);
		fun << (HVAC_WindExitMode);
		fun << (HVAC_AirCirculationSt);
		fun << (HVAC_ECOSt);
		fun << (HVAC_WindExitSpd);
		fun << (HVAC_WindExitSpdPercent);
		fun << (HVAC_PTCPwrConsmp);
		fun << (HVAC_DriverTempSelect);
		fun << (HVAC_PsnTempSelect);
		fun << (HVAC_EvapratorSelfCleanSt);
		fun << (HVAC_CorrectedExterTemp);
		fun << (HVAC_PTCHeatingReq);
		fun << (HVAC_DrAMDoorPostion);
		fun << (HVAC_PaAMDoorPostion);
		fun << (HVAC_HeaterPumpSpdSet);
		fun << (HVAC_DualCircuSt);
		fun << (HVAC_AirCompressorReq);
		fun << (HVAC_ECPTargetDuty);
		fun << (HVAC_ECPwrLimit);
		fun << (HVAC_CoolFanDutyCycleReq);
		fun << (HVAC_CondDefSt);
		fun << (HVAC_StsCabinCoolPrioReq);
		fun << (HVAC_StsCabinHeatPrioReq);
		fun << (HVAC_ActGrillDutyCycleReq);
		fun << (HVAC_CorrectedCabinTemp);
		fun << (HVAC_HeatPumpMode);
		fun << (HVAC_CabinHeatReq);
		fun << (HVAC_AirCirculationReq);
	}
	template<typename F>
	void deserialize(F& fun){
		fun >> (HVAC_CompHPtemp);
		fun >> (HVAC_CompLPtemp);
		fun >> (HVAC_IconOutTemp);
		fun >> (HVAC_CompLP);
		fun >> (HVAC_OHXoutTemp);
		fun >> (HVAC_OHXoutPressure);
		fun >> (HVAC_RefrigerantPr);
		fun >> (HVAC_EVAoutTemp);
		fun >> (HVAC_EVAvalveSt);
		fun >> (HVAC_DehumidifyValveSt);
		fun >> (HVAC_CoolingValveSt);
		fun >> (HVAC_IconInletValveSt);
		fun >> (HVAC_HeatValveSt);
		fun >> (HVAC_OHX_EXVCurrentPosition);
		fun >> (HVAC_CHI_EXVCurrentPosition);
		fun >> (HVAC_EVA_EXVCurrentPosition);
		fun >> (HVAC_ECV_PosnSet);
		fun >> (HVAC_ECPInputVolt);
		fun >> (HVAC_ECPInputCurr);
		fun >> (HVAC_ECPPhaseCurr);
		fun >> (HVAC_ECPSpdDuty);
		fun >> (HVAC_PTCHVDCCurrent);
		fun >> (HVAC_PTCHVVoltage);
		fun >> (HVAC_PTCInterWaterTemp1);
		fun >> (HVAC_PTCActDutyCycle);
		fun >> (AQM_AirQualitySnsLevel);
		fun >> (AQM_CO2CleanReq);
		fun >> (AQM_FreshPopReq);
		fun >> (AQM_CO2WorkCmd);
		fun >> (AQM_PM25CleanReq);
		fun >> (AQM_IonModeReq);
		fun >> (AQM_IonMode);
		fun >> (AQM_FraganceTaste);
		fun >> (AQM_FraganceConcentration);
		fun >> (AQM_FraganceBoxID);
		fun >> (AQM_FraganceBoxLoad);
		fun >> (AQM_UVCSwitch);
		fun >> (AQM_BlowerSt);
		fun >> (AQM_FraganceSwitchSt);
		fun >> (HVAC_SceneDisplayReq);
		fun >> (HVAC_UnlockVentilationSt);
		fun >> (HVAC_DrAirCirculationReq);
		fun >> (HVAC_PaAirCirculationReq);
		fun >> (HVAC_RearDefrostSt);
		fun >> (HVAC_ACSt);
		fun >> (HVAC_AutoDefCfgSt);
		fun >> (HVAC_DualSyncSt);
		fun >> (HVAC_AutoSt);
		fun >> (HVAC_WindExitMode);
		fun >> (HVAC_AirCirculationSt);
		fun >> (HVAC_ECOSt);
		fun >> (HVAC_WindExitSpd);
		fun >> (HVAC_WindExitSpdPercent);
		fun >> (HVAC_PTCPwrConsmp);
		fun >> (HVAC_DriverTempSelect);
		fun >> (HVAC_PsnTempSelect);
		fun >> (HVAC_EvapratorSelfCleanSt);
		fun >> (HVAC_CorrectedExterTemp);
		fun >> (HVAC_PTCHeatingReq);
		fun >> (HVAC_DrAMDoorPostion);
		fun >> (HVAC_PaAMDoorPostion);
		fun >> (HVAC_HeaterPumpSpdSet);
		fun >> (HVAC_DualCircuSt);
		fun >> (HVAC_AirCompressorReq);
		fun >> (HVAC_ECPTargetDuty);
		fun >> (HVAC_ECPwrLimit);
		fun >> (HVAC_CoolFanDutyCycleReq);
		fun >> (HVAC_CondDefSt);
		fun >> (HVAC_StsCabinCoolPrioReq);
		fun >> (HVAC_StsCabinHeatPrioReq);
		fun >> (HVAC_ActGrillDutyCycleReq);
		fun >> (HVAC_CorrectedCabinTemp);
		fun >> (HVAC_HeatPumpMode);
		fun >> (HVAC_CabinHeatReq);
		fun >> (HVAC_AirCirculationReq);
	}
};

#endif //____BDCHVAC3_H__
