#ifndef ____BDCBMCAFE_H__
#define ____BDCBMCAFE_H__


#include "cstdint"






struct BDCBMCAFE {
public:
	std::uint8_t BMC_AFEWakeUpState;
	std::uint8_t BMC_ResetByAFESetErr;
	std::uint8_t BMC_NrResetByAFESetErr;
	std::uint8_t BMC_AFE1_WakeUpSrc;
	std::uint8_t BMC_AFE2_WakeUpSrc;
	std::uint8_t BMC_AFE3_WakeUpSrc;
	std::uint8_t BMC_AFE4_WakeUpSrc;
	std::uint8_t BMC_AFE5_WakeUpSrc;
	std::uint8_t BMC_AFE6_WakeUpSrc;
	std::uint8_t BMC_AFE7_WakeUpSrc;
	std::uint8_t BMC_AFE8_WakeUpSrc;
	std::uint8_t BMC_AFE9_WakeUpSrc;
	std::uint8_t BMC_AFE10_WakeUpSrc;
	std::uint8_t BMC_AFE11_WakeUpSrc;
	std::uint8_t BMC_AFE12_WakeUpSrc;
	std::uint8_t BMC_AFE13_WakeUpSrc;
	std::uint8_t BMC_AFE14_WakeUpSrc;
	std::uint8_t BMC_AFE15_WakeUpSrc;
	std::uint8_t BMC_AFE16_WakeUpSrc;
	std::uint8_t BMC_AFE17_WakeUpSrc;
	std::uint8_t BMC_AFE18_WakeUpSrc;
	std::uint8_t BMC_AFE19_WakeUpSrc;
	std::uint8_t BMC_AFE20_WakeUpSrc;
	std::uint8_t BMC_AFE1_OVWakeUp_Enable;
	std::uint8_t BMC_AFE2_OVWakeUp_Enable;
	std::uint8_t BMC_AFE3_OVWakeUp_Enable;
	std::uint8_t BMC_AFE4_OVWakeUp_Enable;
	std::uint8_t BMC_AFE5_OVWakeUp_Enable;
	std::uint8_t BMC_AFE6_OVWakeUp_Enable;
	std::uint8_t BMC_AFE7_OVWakeUp_Enable;
	std::uint8_t BMC_AFE8_OVWakeUp_Enable;
	std::uint8_t BMC_AFE9_OVWakeUp_Enable;
	std::uint8_t BMC_AFE10_OVWakeUp_Enable;
	std::uint8_t BMC_AFE11_OVWakeUp_Enable;
	std::uint8_t BMC_AFE12_OVWakeUp_Enable;
	std::uint8_t BMC_AFE13_OVWakeUp_Enable;
	std::uint8_t BMC_AFE14_OVWakeUp_Enable;
	std::uint8_t BMC_AFE15_OVWakeUp_Enable;
	std::uint8_t BMC_AFE16_OVWakeUp_Enable;
	std::uint8_t BMC_AFE17_OVWakeUp_Enable;
	std::uint8_t BMC_AFE18_OVWakeUp_Enable;
	std::uint8_t BMC_AFE19_OVWakeUp_Enable;
	std::uint8_t BMC_AFE20_OVWakeUp_Enable;
	std::uint8_t BMC_AFE1_UVWakeUp_Enable;
	std::uint8_t BMC_AFE2_UVWakeUp_Enable;
	std::uint8_t BMC_AFE3_UVWakeUp_Enable;
	std::uint8_t BMC_AFE4_UVWakeUp_Enable;
	std::uint8_t BMC_AFE5_UVWakeUp_Enable;
	std::uint8_t BMC_AFE6_UVWakeUp_Enable;
	std::uint8_t BMC_AFE7_UVWakeUp_Enable;
	std::uint8_t BMC_AFE8_UVWakeUp_Enable;
	std::uint8_t BMC_AFE9_UVWakeUp_Enable;
	std::uint8_t BMC_AFE10_UVWakeUp_Enable;
	std::uint8_t BMC_AFE11_UVWakeUp_Enable;
	std::uint8_t BMC_AFE12_UVWakeUp_Enable;
	std::uint8_t BMC_AFE13_UVWakeUp_Enable;
	std::uint8_t BMC_AFE14_UVWakeUp_Enable;
	std::uint8_t BMC_AFE15_UVWakeUp_Enable;
	std::uint8_t BMC_AFE16_UVWakeUp_Enable;
	std::uint8_t BMC_AFE17_UVWakeUp_Enable;
	std::uint8_t BMC_AFE18_UVWakeUp_Enable;
	std::uint8_t BMC_AFE19_UVWakeUp_Enable;
	std::uint8_t BMC_AFE20_UVWakeUp_Enable;
	std::uint8_t BMC_AFE1_OTWakeUp_Enable;
	std::uint8_t BMC_AFE2_OTWakeUp_Enable;
	std::uint8_t BMC_AFE3_OTWakeUp_Enable;
	std::uint8_t BMC_AFE4_OTWakeUp_Enable;
	std::uint8_t BMC_AFE5_OTWakeUp_Enable;
	std::uint8_t BMC_AFE6_OTWakeUp_Enable;
	std::uint8_t BMC_AFE7_OTWakeUp_Enable;
	std::uint8_t BMC_AFE8_OTWakeUp_Enable;
	std::uint8_t BMC_AFE9_OTWakeUp_Enable;
	std::uint8_t BMC_AFE10_OTWakeUp_Enable;
	std::uint8_t BMC_AFE11_OTWakeUp_Enable;
	std::uint8_t BMC_AFE12_OTWakeUp_Enable;
	std::uint8_t BMC_AFE13_OTWakeUp_Enable;
	std::uint8_t BMC_AFE14_OTWakeUp_Enable;
	std::uint8_t BMC_AFE15_OTWakeUp_Enable;
	std::uint8_t BMC_AFE16_OTWakeUp_Enable;
	std::uint8_t BMC_AFE17_OTWakeUp_Enable;
	std::uint8_t BMC_AFE18_OTWakeUp_Enable;
	std::uint8_t BMC_AFE19_OTWakeUp_Enable;
	std::uint8_t BMC_AFE20_OTWakeUp_Enable;
	std::uint8_t BMC_AFE1_OVThreshold;
	std::uint8_t BMC_AFE2_OVThreshold;
	std::uint8_t BMC_AFE3_OVThreshold;
	std::uint8_t BMC_AFE4_OVThreshold;
	std::uint8_t BMC_AFE5_OVThreshold;
	std::uint8_t BMC_AFE6_OVThreshold;
	std::uint8_t BMC_AFE7_OVThreshold;
	std::uint8_t BMC_AFE8_OVThreshold;
	std::uint8_t BMC_AFE9_OVThreshold;
	std::uint8_t BMC_AFE10_OVThreshold;
	std::uint8_t BMC_AFE11_OVThreshold;
	std::uint8_t BMC_AFE12_OVThreshold;
	std::uint8_t BMC_AFE13_OVThreshold;
	std::uint8_t BMC_AFE14_OVThreshold;
	std::uint8_t BMC_AFE15_OVThreshold;
	std::uint8_t BMC_AFE16_OVThreshold;
	std::uint8_t BMC_AFE17_OVThreshold;
	std::uint8_t BMC_AFE18_OVThreshold;
	std::uint8_t BMC_AFE19_OVThreshold;
	std::uint8_t BMC_AFE20_OVThreshold;
	std::uint8_t BMC_AFE1_UVThreshold;
	std::uint8_t BMC_AFE2_UVThreshold;
	std::uint8_t BMC_AFE3_UVThreshold;
	std::uint8_t BMC_AFE4_UVThreshold;
	std::uint8_t BMC_AFE5_UVThreshold;
	std::uint8_t BMC_AFE6_UVThreshold;
	std::uint8_t BMC_AFE7_UVThreshold;
	std::uint8_t BMC_AFE8_UVThreshold;
	std::uint8_t BMC_AFE9_UVThreshold;
	std::uint8_t BMC_AFE10_UVThreshold;
	std::uint8_t BMC_AFE11_UVThreshold;
	std::uint8_t BMC_AFE12_UVThreshold;
	std::uint8_t BMC_AFE13_UVThreshold;
	std::uint8_t BMC_AFE14_UVThreshold;
	std::uint8_t BMC_AFE15_UVThreshold;
	std::uint8_t BMC_AFE16_UVThreshold;
	std::uint8_t BMC_AFE17_UVThreshold;
	std::uint8_t BMC_AFE18_UVThreshold;
	std::uint8_t BMC_AFE19_UVThreshold;
	std::uint8_t BMC_AFE20_UVThreshold;
	std::uint8_t BMC_AFE1_OTThreshold;
	std::uint8_t BMC_AFE2_OTThreshold;
	std::uint8_t BMC_AFE3_OTThreshold;
	std::uint8_t BMC_AFE4_OTThreshold;
	std::uint8_t BMC_AFE5_OTThreshold;
	std::uint8_t BMC_AFE6_OTThreshold;
	std::uint8_t BMC_AFE7_OTThreshold;
	std::uint8_t BMC_AFE8_OTThreshold;
	std::uint8_t BMC_AFE9_OTThreshold;
	std::uint8_t BMC_AFE10_OTThreshold;
	std::uint8_t BMC_AFE11_OTThreshold;
	std::uint8_t BMC_AFE12_OTThreshold;
	std::uint8_t BMC_AFE13_OTThreshold;
	std::uint8_t BMC_AFE14_OTThreshold;
	std::uint8_t BMC_AFE15_OTThreshold;
	std::uint8_t BMC_AFE16_OTThreshold;
	std::uint8_t BMC_AFE17_OTThreshold;
	std::uint8_t BMC_AFE18_OTThreshold;
	std::uint8_t BMC_AFE19_OTThreshold;
	std::uint8_t BMC_AFE20_OTThreshold;
/*
	BDCBMCAFE() {}
	~BDCBMCAFE() {}
	BDCBMCAFE(const std::uint8_t _BMC_AFEWakeUpState,const std::uint8_t _BMC_ResetByAFESetErr,const std::uint8_t _BMC_NrResetByAFESetErr,const std::uint8_t _BMC_AFE1_WakeUpSrc,const std::uint8_t _BMC_AFE2_WakeUpSrc,const std::uint8_t _BMC_AFE3_WakeUpSrc,const std::uint8_t _BMC_AFE4_WakeUpSrc,const std::uint8_t _BMC_AFE5_WakeUpSrc,const std::uint8_t _BMC_AFE6_WakeUpSrc,const std::uint8_t _BMC_AFE7_WakeUpSrc,const std::uint8_t _BMC_AFE8_WakeUpSrc,const std::uint8_t _BMC_AFE9_WakeUpSrc,const std::uint8_t _BMC_AFE10_WakeUpSrc,const std::uint8_t _BMC_AFE11_WakeUpSrc,const std::uint8_t _BMC_AFE12_WakeUpSrc,const std::uint8_t _BMC_AFE13_WakeUpSrc,const std::uint8_t _BMC_AFE14_WakeUpSrc,const std::uint8_t _BMC_AFE15_WakeUpSrc,const std::uint8_t _BMC_AFE16_WakeUpSrc,const std::uint8_t _BMC_AFE17_WakeUpSrc,const std::uint8_t _BMC_AFE18_WakeUpSrc,const std::uint8_t _BMC_AFE19_WakeUpSrc,const std::uint8_t _BMC_AFE20_WakeUpSrc,const std::uint8_t _BMC_AFE1_OVWakeUp_Enable,const std::uint8_t _BMC_AFE2_OVWakeUp_Enable,const std::uint8_t _BMC_AFE3_OVWakeUp_Enable,const std::uint8_t _BMC_AFE4_OVWakeUp_Enable,const std::uint8_t _BMC_AFE5_OVWakeUp_Enable,const std::uint8_t _BMC_AFE6_OVWakeUp_Enable,const std::uint8_t _BMC_AFE7_OVWakeUp_Enable,const std::uint8_t _BMC_AFE8_OVWakeUp_Enable,const std::uint8_t _BMC_AFE9_OVWakeUp_Enable,const std::uint8_t _BMC_AFE10_OVWakeUp_Enable,const std::uint8_t _BMC_AFE11_OVWakeUp_Enable,const std::uint8_t _BMC_AFE12_OVWakeUp_Enable,const std::uint8_t _BMC_AFE13_OVWakeUp_Enable,const std::uint8_t _BMC_AFE14_OVWakeUp_Enable,const std::uint8_t _BMC_AFE15_OVWakeUp_Enable,const std::uint8_t _BMC_AFE16_OVWakeUp_Enable,const std::uint8_t _BMC_AFE17_OVWakeUp_Enable,const std::uint8_t _BMC_AFE18_OVWakeUp_Enable,const std::uint8_t _BMC_AFE19_OVWakeUp_Enable,const std::uint8_t _BMC_AFE20_OVWakeUp_Enable,const std::uint8_t _BMC_AFE1_UVWakeUp_Enable,const std::uint8_t _BMC_AFE2_UVWakeUp_Enable,const std::uint8_t _BMC_AFE3_UVWakeUp_Enable,const std::uint8_t _BMC_AFE4_UVWakeUp_Enable,const std::uint8_t _BMC_AFE5_UVWakeUp_Enable,const std::uint8_t _BMC_AFE6_UVWakeUp_Enable,const std::uint8_t _BMC_AFE7_UVWakeUp_Enable,const std::uint8_t _BMC_AFE8_UVWakeUp_Enable,const std::uint8_t _BMC_AFE9_UVWakeUp_Enable,const std::uint8_t _BMC_AFE10_UVWakeUp_Enable,const std::uint8_t _BMC_AFE11_UVWakeUp_Enable,const std::uint8_t _BMC_AFE12_UVWakeUp_Enable,const std::uint8_t _BMC_AFE13_UVWakeUp_Enable,const std::uint8_t _BMC_AFE14_UVWakeUp_Enable,const std::uint8_t _BMC_AFE15_UVWakeUp_Enable,const std::uint8_t _BMC_AFE16_UVWakeUp_Enable,const std::uint8_t _BMC_AFE17_UVWakeUp_Enable,const std::uint8_t _BMC_AFE18_UVWakeUp_Enable,const std::uint8_t _BMC_AFE19_UVWakeUp_Enable,const std::uint8_t _BMC_AFE20_UVWakeUp_Enable,const std::uint8_t _BMC_AFE1_OTWakeUp_Enable,const std::uint8_t _BMC_AFE2_OTWakeUp_Enable,const std::uint8_t _BMC_AFE3_OTWakeUp_Enable,const std::uint8_t _BMC_AFE4_OTWakeUp_Enable,const std::uint8_t _BMC_AFE5_OTWakeUp_Enable,const std::uint8_t _BMC_AFE6_OTWakeUp_Enable,const std::uint8_t _BMC_AFE7_OTWakeUp_Enable,const std::uint8_t _BMC_AFE8_OTWakeUp_Enable,const std::uint8_t _BMC_AFE9_OTWakeUp_Enable,const std::uint8_t _BMC_AFE10_OTWakeUp_Enable,const std::uint8_t _BMC_AFE11_OTWakeUp_Enable,const std::uint8_t _BMC_AFE12_OTWakeUp_Enable,const std::uint8_t _BMC_AFE13_OTWakeUp_Enable,const std::uint8_t _BMC_AFE14_OTWakeUp_Enable,const std::uint8_t _BMC_AFE15_OTWakeUp_Enable,const std::uint8_t _BMC_AFE16_OTWakeUp_Enable,const std::uint8_t _BMC_AFE17_OTWakeUp_Enable,const std::uint8_t _BMC_AFE18_OTWakeUp_Enable,const std::uint8_t _BMC_AFE19_OTWakeUp_Enable,const std::uint8_t _BMC_AFE20_OTWakeUp_Enable,const std::uint8_t _BMC_AFE1_OVThreshold,const std::uint8_t _BMC_AFE2_OVThreshold,const std::uint8_t _BMC_AFE3_OVThreshold,const std::uint8_t _BMC_AFE4_OVThreshold,const std::uint8_t _BMC_AFE5_OVThreshold,const std::uint8_t _BMC_AFE6_OVThreshold,const std::uint8_t _BMC_AFE7_OVThreshold,const std::uint8_t _BMC_AFE8_OVThreshold,const std::uint8_t _BMC_AFE9_OVThreshold,const std::uint8_t _BMC_AFE10_OVThreshold,const std::uint8_t _BMC_AFE11_OVThreshold,const std::uint8_t _BMC_AFE12_OVThreshold,const std::uint8_t _BMC_AFE13_OVThreshold,const std::uint8_t _BMC_AFE14_OVThreshold,const std::uint8_t _BMC_AFE15_OVThreshold,const std::uint8_t _BMC_AFE16_OVThreshold,const std::uint8_t _BMC_AFE17_OVThreshold,const std::uint8_t _BMC_AFE18_OVThreshold,const std::uint8_t _BMC_AFE19_OVThreshold,const std::uint8_t _BMC_AFE20_OVThreshold,const std::uint8_t _BMC_AFE1_UVThreshold,const std::uint8_t _BMC_AFE2_UVThreshold,const std::uint8_t _BMC_AFE3_UVThreshold,const std::uint8_t _BMC_AFE4_UVThreshold,const std::uint8_t _BMC_AFE5_UVThreshold,const std::uint8_t _BMC_AFE6_UVThreshold,const std::uint8_t _BMC_AFE7_UVThreshold,const std::uint8_t _BMC_AFE8_UVThreshold,const std::uint8_t _BMC_AFE9_UVThreshold,const std::uint8_t _BMC_AFE10_UVThreshold,const std::uint8_t _BMC_AFE11_UVThreshold,const std::uint8_t _BMC_AFE12_UVThreshold,const std::uint8_t _BMC_AFE13_UVThreshold,const std::uint8_t _BMC_AFE14_UVThreshold,const std::uint8_t _BMC_AFE15_UVThreshold,const std::uint8_t _BMC_AFE16_UVThreshold,const std::uint8_t _BMC_AFE17_UVThreshold,const std::uint8_t _BMC_AFE18_UVThreshold,const std::uint8_t _BMC_AFE19_UVThreshold,const std::uint8_t _BMC_AFE20_UVThreshold,const std::uint8_t _BMC_AFE1_OTThreshold,const std::uint8_t _BMC_AFE2_OTThreshold,const std::uint8_t _BMC_AFE3_OTThreshold,const std::uint8_t _BMC_AFE4_OTThreshold,const std::uint8_t _BMC_AFE5_OTThreshold,const std::uint8_t _BMC_AFE6_OTThreshold,const std::uint8_t _BMC_AFE7_OTThreshold,const std::uint8_t _BMC_AFE8_OTThreshold,const std::uint8_t _BMC_AFE9_OTThreshold,const std::uint8_t _BMC_AFE10_OTThreshold,const std::uint8_t _BMC_AFE11_OTThreshold,const std::uint8_t _BMC_AFE12_OTThreshold,const std::uint8_t _BMC_AFE13_OTThreshold,const std::uint8_t _BMC_AFE14_OTThreshold,const std::uint8_t _BMC_AFE15_OTThreshold,const std::uint8_t _BMC_AFE16_OTThreshold,const std::uint8_t _BMC_AFE17_OTThreshold,const std::uint8_t _BMC_AFE18_OTThreshold,const std::uint8_t _BMC_AFE19_OTThreshold,const std::uint8_t _BMC_AFE20_OTThreshold):BMC_AFEWakeUpState(_BMC_AFEWakeUpState),BMC_ResetByAFESetErr(_BMC_ResetByAFESetErr),BMC_NrResetByAFESetErr(_BMC_NrResetByAFESetErr),BMC_AFE1_WakeUpSrc(_BMC_AFE1_WakeUpSrc),BMC_AFE2_WakeUpSrc(_BMC_AFE2_WakeUpSrc),BMC_AFE3_WakeUpSrc(_BMC_AFE3_WakeUpSrc),BMC_AFE4_WakeUpSrc(_BMC_AFE4_WakeUpSrc),BMC_AFE5_WakeUpSrc(_BMC_AFE5_WakeUpSrc),BMC_AFE6_WakeUpSrc(_BMC_AFE6_WakeUpSrc),BMC_AFE7_WakeUpSrc(_BMC_AFE7_WakeUpSrc),BMC_AFE8_WakeUpSrc(_BMC_AFE8_WakeUpSrc),BMC_AFE9_WakeUpSrc(_BMC_AFE9_WakeUpSrc),BMC_AFE10_WakeUpSrc(_BMC_AFE10_WakeUpSrc),BMC_AFE11_WakeUpSrc(_BMC_AFE11_WakeUpSrc),BMC_AFE12_WakeUpSrc(_BMC_AFE12_WakeUpSrc),BMC_AFE13_WakeUpSrc(_BMC_AFE13_WakeUpSrc),BMC_AFE14_WakeUpSrc(_BMC_AFE14_WakeUpSrc),BMC_AFE15_WakeUpSrc(_BMC_AFE15_WakeUpSrc),BMC_AFE16_WakeUpSrc(_BMC_AFE16_WakeUpSrc),BMC_AFE17_WakeUpSrc(_BMC_AFE17_WakeUpSrc),BMC_AFE18_WakeUpSrc(_BMC_AFE18_WakeUpSrc),BMC_AFE19_WakeUpSrc(_BMC_AFE19_WakeUpSrc),BMC_AFE20_WakeUpSrc(_BMC_AFE20_WakeUpSrc),BMC_AFE1_OVWakeUp_Enable(_BMC_AFE1_OVWakeUp_Enable),BMC_AFE2_OVWakeUp_Enable(_BMC_AFE2_OVWakeUp_Enable),BMC_AFE3_OVWakeUp_Enable(_BMC_AFE3_OVWakeUp_Enable),BMC_AFE4_OVWakeUp_Enable(_BMC_AFE4_OVWakeUp_Enable),BMC_AFE5_OVWakeUp_Enable(_BMC_AFE5_OVWakeUp_Enable),BMC_AFE6_OVWakeUp_Enable(_BMC_AFE6_OVWakeUp_Enable),BMC_AFE7_OVWakeUp_Enable(_BMC_AFE7_OVWakeUp_Enable),BMC_AFE8_OVWakeUp_Enable(_BMC_AFE8_OVWakeUp_Enable),BMC_AFE9_OVWakeUp_Enable(_BMC_AFE9_OVWakeUp_Enable),BMC_AFE10_OVWakeUp_Enable(_BMC_AFE10_OVWakeUp_Enable),BMC_AFE11_OVWakeUp_Enable(_BMC_AFE11_OVWakeUp_Enable),BMC_AFE12_OVWakeUp_Enable(_BMC_AFE12_OVWakeUp_Enable),BMC_AFE13_OVWakeUp_Enable(_BMC_AFE13_OVWakeUp_Enable),BMC_AFE14_OVWakeUp_Enable(_BMC_AFE14_OVWakeUp_Enable),BMC_AFE15_OVWakeUp_Enable(_BMC_AFE15_OVWakeUp_Enable),BMC_AFE16_OVWakeUp_Enable(_BMC_AFE16_OVWakeUp_Enable),BMC_AFE17_OVWakeUp_Enable(_BMC_AFE17_OVWakeUp_Enable),BMC_AFE18_OVWakeUp_Enable(_BMC_AFE18_OVWakeUp_Enable),BMC_AFE19_OVWakeUp_Enable(_BMC_AFE19_OVWakeUp_Enable),BMC_AFE20_OVWakeUp_Enable(_BMC_AFE20_OVWakeUp_Enable),BMC_AFE1_UVWakeUp_Enable(_BMC_AFE1_UVWakeUp_Enable),BMC_AFE2_UVWakeUp_Enable(_BMC_AFE2_UVWakeUp_Enable),BMC_AFE3_UVWakeUp_Enable(_BMC_AFE3_UVWakeUp_Enable),BMC_AFE4_UVWakeUp_Enable(_BMC_AFE4_UVWakeUp_Enable),BMC_AFE5_UVWakeUp_Enable(_BMC_AFE5_UVWakeUp_Enable),BMC_AFE6_UVWakeUp_Enable(_BMC_AFE6_UVWakeUp_Enable),BMC_AFE7_UVWakeUp_Enable(_BMC_AFE7_UVWakeUp_Enable),BMC_AFE8_UVWakeUp_Enable(_BMC_AFE8_UVWakeUp_Enable),BMC_AFE9_UVWakeUp_Enable(_BMC_AFE9_UVWakeUp_Enable),BMC_AFE10_UVWakeUp_Enable(_BMC_AFE10_UVWakeUp_Enable),BMC_AFE11_UVWakeUp_Enable(_BMC_AFE11_UVWakeUp_Enable),BMC_AFE12_UVWakeUp_Enable(_BMC_AFE12_UVWakeUp_Enable),BMC_AFE13_UVWakeUp_Enable(_BMC_AFE13_UVWakeUp_Enable),BMC_AFE14_UVWakeUp_Enable(_BMC_AFE14_UVWakeUp_Enable),BMC_AFE15_UVWakeUp_Enable(_BMC_AFE15_UVWakeUp_Enable),BMC_AFE16_UVWakeUp_Enable(_BMC_AFE16_UVWakeUp_Enable),BMC_AFE17_UVWakeUp_Enable(_BMC_AFE17_UVWakeUp_Enable),BMC_AFE18_UVWakeUp_Enable(_BMC_AFE18_UVWakeUp_Enable),BMC_AFE19_UVWakeUp_Enable(_BMC_AFE19_UVWakeUp_Enable),BMC_AFE20_UVWakeUp_Enable(_BMC_AFE20_UVWakeUp_Enable),BMC_AFE1_OTWakeUp_Enable(_BMC_AFE1_OTWakeUp_Enable),BMC_AFE2_OTWakeUp_Enable(_BMC_AFE2_OTWakeUp_Enable),BMC_AFE3_OTWakeUp_Enable(_BMC_AFE3_OTWakeUp_Enable),BMC_AFE4_OTWakeUp_Enable(_BMC_AFE4_OTWakeUp_Enable),BMC_AFE5_OTWakeUp_Enable(_BMC_AFE5_OTWakeUp_Enable),BMC_AFE6_OTWakeUp_Enable(_BMC_AFE6_OTWakeUp_Enable),BMC_AFE7_OTWakeUp_Enable(_BMC_AFE7_OTWakeUp_Enable),BMC_AFE8_OTWakeUp_Enable(_BMC_AFE8_OTWakeUp_Enable),BMC_AFE9_OTWakeUp_Enable(_BMC_AFE9_OTWakeUp_Enable),BMC_AFE10_OTWakeUp_Enable(_BMC_AFE10_OTWakeUp_Enable),BMC_AFE11_OTWakeUp_Enable(_BMC_AFE11_OTWakeUp_Enable),BMC_AFE12_OTWakeUp_Enable(_BMC_AFE12_OTWakeUp_Enable),BMC_AFE13_OTWakeUp_Enable(_BMC_AFE13_OTWakeUp_Enable),BMC_AFE14_OTWakeUp_Enable(_BMC_AFE14_OTWakeUp_Enable),BMC_AFE15_OTWakeUp_Enable(_BMC_AFE15_OTWakeUp_Enable),BMC_AFE16_OTWakeUp_Enable(_BMC_AFE16_OTWakeUp_Enable),BMC_AFE17_OTWakeUp_Enable(_BMC_AFE17_OTWakeUp_Enable),BMC_AFE18_OTWakeUp_Enable(_BMC_AFE18_OTWakeUp_Enable),BMC_AFE19_OTWakeUp_Enable(_BMC_AFE19_OTWakeUp_Enable),BMC_AFE20_OTWakeUp_Enable(_BMC_AFE20_OTWakeUp_Enable),BMC_AFE1_OVThreshold(_BMC_AFE1_OVThreshold),BMC_AFE2_OVThreshold(_BMC_AFE2_OVThreshold),BMC_AFE3_OVThreshold(_BMC_AFE3_OVThreshold),BMC_AFE4_OVThreshold(_BMC_AFE4_OVThreshold),BMC_AFE5_OVThreshold(_BMC_AFE5_OVThreshold),BMC_AFE6_OVThreshold(_BMC_AFE6_OVThreshold),BMC_AFE7_OVThreshold(_BMC_AFE7_OVThreshold),BMC_AFE8_OVThreshold(_BMC_AFE8_OVThreshold),BMC_AFE9_OVThreshold(_BMC_AFE9_OVThreshold),BMC_AFE10_OVThreshold(_BMC_AFE10_OVThreshold),BMC_AFE11_OVThreshold(_BMC_AFE11_OVThreshold),BMC_AFE12_OVThreshold(_BMC_AFE12_OVThreshold),BMC_AFE13_OVThreshold(_BMC_AFE13_OVThreshold),BMC_AFE14_OVThreshold(_BMC_AFE14_OVThreshold),BMC_AFE15_OVThreshold(_BMC_AFE15_OVThreshold),BMC_AFE16_OVThreshold(_BMC_AFE16_OVThreshold),BMC_AFE17_OVThreshold(_BMC_AFE17_OVThreshold),BMC_AFE18_OVThreshold(_BMC_AFE18_OVThreshold),BMC_AFE19_OVThreshold(_BMC_AFE19_OVThreshold),BMC_AFE20_OVThreshold(_BMC_AFE20_OVThreshold),BMC_AFE1_UVThreshold(_BMC_AFE1_UVThreshold),BMC_AFE2_UVThreshold(_BMC_AFE2_UVThreshold),BMC_AFE3_UVThreshold(_BMC_AFE3_UVThreshold),BMC_AFE4_UVThreshold(_BMC_AFE4_UVThreshold),BMC_AFE5_UVThreshold(_BMC_AFE5_UVThreshold),BMC_AFE6_UVThreshold(_BMC_AFE6_UVThreshold),BMC_AFE7_UVThreshold(_BMC_AFE7_UVThreshold),BMC_AFE8_UVThreshold(_BMC_AFE8_UVThreshold),BMC_AFE9_UVThreshold(_BMC_AFE9_UVThreshold),BMC_AFE10_UVThreshold(_BMC_AFE10_UVThreshold),BMC_AFE11_UVThreshold(_BMC_AFE11_UVThreshold),BMC_AFE12_UVThreshold(_BMC_AFE12_UVThreshold),BMC_AFE13_UVThreshold(_BMC_AFE13_UVThreshold),BMC_AFE14_UVThreshold(_BMC_AFE14_UVThreshold),BMC_AFE15_UVThreshold(_BMC_AFE15_UVThreshold),BMC_AFE16_UVThreshold(_BMC_AFE16_UVThreshold),BMC_AFE17_UVThreshold(_BMC_AFE17_UVThreshold),BMC_AFE18_UVThreshold(_BMC_AFE18_UVThreshold),BMC_AFE19_UVThreshold(_BMC_AFE19_UVThreshold),BMC_AFE20_UVThreshold(_BMC_AFE20_UVThreshold),BMC_AFE1_OTThreshold(_BMC_AFE1_OTThreshold),BMC_AFE2_OTThreshold(_BMC_AFE2_OTThreshold),BMC_AFE3_OTThreshold(_BMC_AFE3_OTThreshold),BMC_AFE4_OTThreshold(_BMC_AFE4_OTThreshold),BMC_AFE5_OTThreshold(_BMC_AFE5_OTThreshold),BMC_AFE6_OTThreshold(_BMC_AFE6_OTThreshold),BMC_AFE7_OTThreshold(_BMC_AFE7_OTThreshold),BMC_AFE8_OTThreshold(_BMC_AFE8_OTThreshold),BMC_AFE9_OTThreshold(_BMC_AFE9_OTThreshold),BMC_AFE10_OTThreshold(_BMC_AFE10_OTThreshold),BMC_AFE11_OTThreshold(_BMC_AFE11_OTThreshold),BMC_AFE12_OTThreshold(_BMC_AFE12_OTThreshold),BMC_AFE13_OTThreshold(_BMC_AFE13_OTThreshold),BMC_AFE14_OTThreshold(_BMC_AFE14_OTThreshold),BMC_AFE15_OTThreshold(_BMC_AFE15_OTThreshold),BMC_AFE16_OTThreshold(_BMC_AFE16_OTThreshold),BMC_AFE17_OTThreshold(_BMC_AFE17_OTThreshold),BMC_AFE18_OTThreshold(_BMC_AFE18_OTThreshold),BMC_AFE19_OTThreshold(_BMC_AFE19_OTThreshold),BMC_AFE20_OTThreshold(_BMC_AFE20_OTThreshold) {}
	BDCBMCAFE(const BDCBMCAFE &_x){
		BMC_AFEWakeUpState = _x.BMC_AFEWakeUpState;
		BMC_ResetByAFESetErr = _x.BMC_ResetByAFESetErr;
		BMC_NrResetByAFESetErr = _x.BMC_NrResetByAFESetErr;
		BMC_AFE1_WakeUpSrc = _x.BMC_AFE1_WakeUpSrc;
		BMC_AFE2_WakeUpSrc = _x.BMC_AFE2_WakeUpSrc;
		BMC_AFE3_WakeUpSrc = _x.BMC_AFE3_WakeUpSrc;
		BMC_AFE4_WakeUpSrc = _x.BMC_AFE4_WakeUpSrc;
		BMC_AFE5_WakeUpSrc = _x.BMC_AFE5_WakeUpSrc;
		BMC_AFE6_WakeUpSrc = _x.BMC_AFE6_WakeUpSrc;
		BMC_AFE7_WakeUpSrc = _x.BMC_AFE7_WakeUpSrc;
		BMC_AFE8_WakeUpSrc = _x.BMC_AFE8_WakeUpSrc;
		BMC_AFE9_WakeUpSrc = _x.BMC_AFE9_WakeUpSrc;
		BMC_AFE10_WakeUpSrc = _x.BMC_AFE10_WakeUpSrc;
		BMC_AFE11_WakeUpSrc = _x.BMC_AFE11_WakeUpSrc;
		BMC_AFE12_WakeUpSrc = _x.BMC_AFE12_WakeUpSrc;
		BMC_AFE13_WakeUpSrc = _x.BMC_AFE13_WakeUpSrc;
		BMC_AFE14_WakeUpSrc = _x.BMC_AFE14_WakeUpSrc;
		BMC_AFE15_WakeUpSrc = _x.BMC_AFE15_WakeUpSrc;
		BMC_AFE16_WakeUpSrc = _x.BMC_AFE16_WakeUpSrc;
		BMC_AFE17_WakeUpSrc = _x.BMC_AFE17_WakeUpSrc;
		BMC_AFE18_WakeUpSrc = _x.BMC_AFE18_WakeUpSrc;
		BMC_AFE19_WakeUpSrc = _x.BMC_AFE19_WakeUpSrc;
		BMC_AFE20_WakeUpSrc = _x.BMC_AFE20_WakeUpSrc;
		BMC_AFE1_OVWakeUp_Enable = _x.BMC_AFE1_OVWakeUp_Enable;
		BMC_AFE2_OVWakeUp_Enable = _x.BMC_AFE2_OVWakeUp_Enable;
		BMC_AFE3_OVWakeUp_Enable = _x.BMC_AFE3_OVWakeUp_Enable;
		BMC_AFE4_OVWakeUp_Enable = _x.BMC_AFE4_OVWakeUp_Enable;
		BMC_AFE5_OVWakeUp_Enable = _x.BMC_AFE5_OVWakeUp_Enable;
		BMC_AFE6_OVWakeUp_Enable = _x.BMC_AFE6_OVWakeUp_Enable;
		BMC_AFE7_OVWakeUp_Enable = _x.BMC_AFE7_OVWakeUp_Enable;
		BMC_AFE8_OVWakeUp_Enable = _x.BMC_AFE8_OVWakeUp_Enable;
		BMC_AFE9_OVWakeUp_Enable = _x.BMC_AFE9_OVWakeUp_Enable;
		BMC_AFE10_OVWakeUp_Enable = _x.BMC_AFE10_OVWakeUp_Enable;
		BMC_AFE11_OVWakeUp_Enable = _x.BMC_AFE11_OVWakeUp_Enable;
		BMC_AFE12_OVWakeUp_Enable = _x.BMC_AFE12_OVWakeUp_Enable;
		BMC_AFE13_OVWakeUp_Enable = _x.BMC_AFE13_OVWakeUp_Enable;
		BMC_AFE14_OVWakeUp_Enable = _x.BMC_AFE14_OVWakeUp_Enable;
		BMC_AFE15_OVWakeUp_Enable = _x.BMC_AFE15_OVWakeUp_Enable;
		BMC_AFE16_OVWakeUp_Enable = _x.BMC_AFE16_OVWakeUp_Enable;
		BMC_AFE17_OVWakeUp_Enable = _x.BMC_AFE17_OVWakeUp_Enable;
		BMC_AFE18_OVWakeUp_Enable = _x.BMC_AFE18_OVWakeUp_Enable;
		BMC_AFE19_OVWakeUp_Enable = _x.BMC_AFE19_OVWakeUp_Enable;
		BMC_AFE20_OVWakeUp_Enable = _x.BMC_AFE20_OVWakeUp_Enable;
		BMC_AFE1_UVWakeUp_Enable = _x.BMC_AFE1_UVWakeUp_Enable;
		BMC_AFE2_UVWakeUp_Enable = _x.BMC_AFE2_UVWakeUp_Enable;
		BMC_AFE3_UVWakeUp_Enable = _x.BMC_AFE3_UVWakeUp_Enable;
		BMC_AFE4_UVWakeUp_Enable = _x.BMC_AFE4_UVWakeUp_Enable;
		BMC_AFE5_UVWakeUp_Enable = _x.BMC_AFE5_UVWakeUp_Enable;
		BMC_AFE6_UVWakeUp_Enable = _x.BMC_AFE6_UVWakeUp_Enable;
		BMC_AFE7_UVWakeUp_Enable = _x.BMC_AFE7_UVWakeUp_Enable;
		BMC_AFE8_UVWakeUp_Enable = _x.BMC_AFE8_UVWakeUp_Enable;
		BMC_AFE9_UVWakeUp_Enable = _x.BMC_AFE9_UVWakeUp_Enable;
		BMC_AFE10_UVWakeUp_Enable = _x.BMC_AFE10_UVWakeUp_Enable;
		BMC_AFE11_UVWakeUp_Enable = _x.BMC_AFE11_UVWakeUp_Enable;
		BMC_AFE12_UVWakeUp_Enable = _x.BMC_AFE12_UVWakeUp_Enable;
		BMC_AFE13_UVWakeUp_Enable = _x.BMC_AFE13_UVWakeUp_Enable;
		BMC_AFE14_UVWakeUp_Enable = _x.BMC_AFE14_UVWakeUp_Enable;
		BMC_AFE15_UVWakeUp_Enable = _x.BMC_AFE15_UVWakeUp_Enable;
		BMC_AFE16_UVWakeUp_Enable = _x.BMC_AFE16_UVWakeUp_Enable;
		BMC_AFE17_UVWakeUp_Enable = _x.BMC_AFE17_UVWakeUp_Enable;
		BMC_AFE18_UVWakeUp_Enable = _x.BMC_AFE18_UVWakeUp_Enable;
		BMC_AFE19_UVWakeUp_Enable = _x.BMC_AFE19_UVWakeUp_Enable;
		BMC_AFE20_UVWakeUp_Enable = _x.BMC_AFE20_UVWakeUp_Enable;
		BMC_AFE1_OTWakeUp_Enable = _x.BMC_AFE1_OTWakeUp_Enable;
		BMC_AFE2_OTWakeUp_Enable = _x.BMC_AFE2_OTWakeUp_Enable;
		BMC_AFE3_OTWakeUp_Enable = _x.BMC_AFE3_OTWakeUp_Enable;
		BMC_AFE4_OTWakeUp_Enable = _x.BMC_AFE4_OTWakeUp_Enable;
		BMC_AFE5_OTWakeUp_Enable = _x.BMC_AFE5_OTWakeUp_Enable;
		BMC_AFE6_OTWakeUp_Enable = _x.BMC_AFE6_OTWakeUp_Enable;
		BMC_AFE7_OTWakeUp_Enable = _x.BMC_AFE7_OTWakeUp_Enable;
		BMC_AFE8_OTWakeUp_Enable = _x.BMC_AFE8_OTWakeUp_Enable;
		BMC_AFE9_OTWakeUp_Enable = _x.BMC_AFE9_OTWakeUp_Enable;
		BMC_AFE10_OTWakeUp_Enable = _x.BMC_AFE10_OTWakeUp_Enable;
		BMC_AFE11_OTWakeUp_Enable = _x.BMC_AFE11_OTWakeUp_Enable;
		BMC_AFE12_OTWakeUp_Enable = _x.BMC_AFE12_OTWakeUp_Enable;
		BMC_AFE13_OTWakeUp_Enable = _x.BMC_AFE13_OTWakeUp_Enable;
		BMC_AFE14_OTWakeUp_Enable = _x.BMC_AFE14_OTWakeUp_Enable;
		BMC_AFE15_OTWakeUp_Enable = _x.BMC_AFE15_OTWakeUp_Enable;
		BMC_AFE16_OTWakeUp_Enable = _x.BMC_AFE16_OTWakeUp_Enable;
		BMC_AFE17_OTWakeUp_Enable = _x.BMC_AFE17_OTWakeUp_Enable;
		BMC_AFE18_OTWakeUp_Enable = _x.BMC_AFE18_OTWakeUp_Enable;
		BMC_AFE19_OTWakeUp_Enable = _x.BMC_AFE19_OTWakeUp_Enable;
		BMC_AFE20_OTWakeUp_Enable = _x.BMC_AFE20_OTWakeUp_Enable;
		BMC_AFE1_OVThreshold = _x.BMC_AFE1_OVThreshold;
		BMC_AFE2_OVThreshold = _x.BMC_AFE2_OVThreshold;
		BMC_AFE3_OVThreshold = _x.BMC_AFE3_OVThreshold;
		BMC_AFE4_OVThreshold = _x.BMC_AFE4_OVThreshold;
		BMC_AFE5_OVThreshold = _x.BMC_AFE5_OVThreshold;
		BMC_AFE6_OVThreshold = _x.BMC_AFE6_OVThreshold;
		BMC_AFE7_OVThreshold = _x.BMC_AFE7_OVThreshold;
		BMC_AFE8_OVThreshold = _x.BMC_AFE8_OVThreshold;
		BMC_AFE9_OVThreshold = _x.BMC_AFE9_OVThreshold;
		BMC_AFE10_OVThreshold = _x.BMC_AFE10_OVThreshold;
		BMC_AFE11_OVThreshold = _x.BMC_AFE11_OVThreshold;
		BMC_AFE12_OVThreshold = _x.BMC_AFE12_OVThreshold;
		BMC_AFE13_OVThreshold = _x.BMC_AFE13_OVThreshold;
		BMC_AFE14_OVThreshold = _x.BMC_AFE14_OVThreshold;
		BMC_AFE15_OVThreshold = _x.BMC_AFE15_OVThreshold;
		BMC_AFE16_OVThreshold = _x.BMC_AFE16_OVThreshold;
		BMC_AFE17_OVThreshold = _x.BMC_AFE17_OVThreshold;
		BMC_AFE18_OVThreshold = _x.BMC_AFE18_OVThreshold;
		BMC_AFE19_OVThreshold = _x.BMC_AFE19_OVThreshold;
		BMC_AFE20_OVThreshold = _x.BMC_AFE20_OVThreshold;
		BMC_AFE1_UVThreshold = _x.BMC_AFE1_UVThreshold;
		BMC_AFE2_UVThreshold = _x.BMC_AFE2_UVThreshold;
		BMC_AFE3_UVThreshold = _x.BMC_AFE3_UVThreshold;
		BMC_AFE4_UVThreshold = _x.BMC_AFE4_UVThreshold;
		BMC_AFE5_UVThreshold = _x.BMC_AFE5_UVThreshold;
		BMC_AFE6_UVThreshold = _x.BMC_AFE6_UVThreshold;
		BMC_AFE7_UVThreshold = _x.BMC_AFE7_UVThreshold;
		BMC_AFE8_UVThreshold = _x.BMC_AFE8_UVThreshold;
		BMC_AFE9_UVThreshold = _x.BMC_AFE9_UVThreshold;
		BMC_AFE10_UVThreshold = _x.BMC_AFE10_UVThreshold;
		BMC_AFE11_UVThreshold = _x.BMC_AFE11_UVThreshold;
		BMC_AFE12_UVThreshold = _x.BMC_AFE12_UVThreshold;
		BMC_AFE13_UVThreshold = _x.BMC_AFE13_UVThreshold;
		BMC_AFE14_UVThreshold = _x.BMC_AFE14_UVThreshold;
		BMC_AFE15_UVThreshold = _x.BMC_AFE15_UVThreshold;
		BMC_AFE16_UVThreshold = _x.BMC_AFE16_UVThreshold;
		BMC_AFE17_UVThreshold = _x.BMC_AFE17_UVThreshold;
		BMC_AFE18_UVThreshold = _x.BMC_AFE18_UVThreshold;
		BMC_AFE19_UVThreshold = _x.BMC_AFE19_UVThreshold;
		BMC_AFE20_UVThreshold = _x.BMC_AFE20_UVThreshold;
		BMC_AFE1_OTThreshold = _x.BMC_AFE1_OTThreshold;
		BMC_AFE2_OTThreshold = _x.BMC_AFE2_OTThreshold;
		BMC_AFE3_OTThreshold = _x.BMC_AFE3_OTThreshold;
		BMC_AFE4_OTThreshold = _x.BMC_AFE4_OTThreshold;
		BMC_AFE5_OTThreshold = _x.BMC_AFE5_OTThreshold;
		BMC_AFE6_OTThreshold = _x.BMC_AFE6_OTThreshold;
		BMC_AFE7_OTThreshold = _x.BMC_AFE7_OTThreshold;
		BMC_AFE8_OTThreshold = _x.BMC_AFE8_OTThreshold;
		BMC_AFE9_OTThreshold = _x.BMC_AFE9_OTThreshold;
		BMC_AFE10_OTThreshold = _x.BMC_AFE10_OTThreshold;
		BMC_AFE11_OTThreshold = _x.BMC_AFE11_OTThreshold;
		BMC_AFE12_OTThreshold = _x.BMC_AFE12_OTThreshold;
		BMC_AFE13_OTThreshold = _x.BMC_AFE13_OTThreshold;
		BMC_AFE14_OTThreshold = _x.BMC_AFE14_OTThreshold;
		BMC_AFE15_OTThreshold = _x.BMC_AFE15_OTThreshold;
		BMC_AFE16_OTThreshold = _x.BMC_AFE16_OTThreshold;
		BMC_AFE17_OTThreshold = _x.BMC_AFE17_OTThreshold;
		BMC_AFE18_OTThreshold = _x.BMC_AFE18_OTThreshold;
		BMC_AFE19_OTThreshold = _x.BMC_AFE19_OTThreshold;
		BMC_AFE20_OTThreshold = _x.BMC_AFE20_OTThreshold;
	}
	BDCBMCAFE(BDCBMCAFE &&_x){
		BMC_AFEWakeUpState = std::move(_x.BMC_AFEWakeUpState);
		BMC_ResetByAFESetErr = std::move(_x.BMC_ResetByAFESetErr);
		BMC_NrResetByAFESetErr = std::move(_x.BMC_NrResetByAFESetErr);
		BMC_AFE1_WakeUpSrc = std::move(_x.BMC_AFE1_WakeUpSrc);
		BMC_AFE2_WakeUpSrc = std::move(_x.BMC_AFE2_WakeUpSrc);
		BMC_AFE3_WakeUpSrc = std::move(_x.BMC_AFE3_WakeUpSrc);
		BMC_AFE4_WakeUpSrc = std::move(_x.BMC_AFE4_WakeUpSrc);
		BMC_AFE5_WakeUpSrc = std::move(_x.BMC_AFE5_WakeUpSrc);
		BMC_AFE6_WakeUpSrc = std::move(_x.BMC_AFE6_WakeUpSrc);
		BMC_AFE7_WakeUpSrc = std::move(_x.BMC_AFE7_WakeUpSrc);
		BMC_AFE8_WakeUpSrc = std::move(_x.BMC_AFE8_WakeUpSrc);
		BMC_AFE9_WakeUpSrc = std::move(_x.BMC_AFE9_WakeUpSrc);
		BMC_AFE10_WakeUpSrc = std::move(_x.BMC_AFE10_WakeUpSrc);
		BMC_AFE11_WakeUpSrc = std::move(_x.BMC_AFE11_WakeUpSrc);
		BMC_AFE12_WakeUpSrc = std::move(_x.BMC_AFE12_WakeUpSrc);
		BMC_AFE13_WakeUpSrc = std::move(_x.BMC_AFE13_WakeUpSrc);
		BMC_AFE14_WakeUpSrc = std::move(_x.BMC_AFE14_WakeUpSrc);
		BMC_AFE15_WakeUpSrc = std::move(_x.BMC_AFE15_WakeUpSrc);
		BMC_AFE16_WakeUpSrc = std::move(_x.BMC_AFE16_WakeUpSrc);
		BMC_AFE17_WakeUpSrc = std::move(_x.BMC_AFE17_WakeUpSrc);
		BMC_AFE18_WakeUpSrc = std::move(_x.BMC_AFE18_WakeUpSrc);
		BMC_AFE19_WakeUpSrc = std::move(_x.BMC_AFE19_WakeUpSrc);
		BMC_AFE20_WakeUpSrc = std::move(_x.BMC_AFE20_WakeUpSrc);
		BMC_AFE1_OVWakeUp_Enable = std::move(_x.BMC_AFE1_OVWakeUp_Enable);
		BMC_AFE2_OVWakeUp_Enable = std::move(_x.BMC_AFE2_OVWakeUp_Enable);
		BMC_AFE3_OVWakeUp_Enable = std::move(_x.BMC_AFE3_OVWakeUp_Enable);
		BMC_AFE4_OVWakeUp_Enable = std::move(_x.BMC_AFE4_OVWakeUp_Enable);
		BMC_AFE5_OVWakeUp_Enable = std::move(_x.BMC_AFE5_OVWakeUp_Enable);
		BMC_AFE6_OVWakeUp_Enable = std::move(_x.BMC_AFE6_OVWakeUp_Enable);
		BMC_AFE7_OVWakeUp_Enable = std::move(_x.BMC_AFE7_OVWakeUp_Enable);
		BMC_AFE8_OVWakeUp_Enable = std::move(_x.BMC_AFE8_OVWakeUp_Enable);
		BMC_AFE9_OVWakeUp_Enable = std::move(_x.BMC_AFE9_OVWakeUp_Enable);
		BMC_AFE10_OVWakeUp_Enable = std::move(_x.BMC_AFE10_OVWakeUp_Enable);
		BMC_AFE11_OVWakeUp_Enable = std::move(_x.BMC_AFE11_OVWakeUp_Enable);
		BMC_AFE12_OVWakeUp_Enable = std::move(_x.BMC_AFE12_OVWakeUp_Enable);
		BMC_AFE13_OVWakeUp_Enable = std::move(_x.BMC_AFE13_OVWakeUp_Enable);
		BMC_AFE14_OVWakeUp_Enable = std::move(_x.BMC_AFE14_OVWakeUp_Enable);
		BMC_AFE15_OVWakeUp_Enable = std::move(_x.BMC_AFE15_OVWakeUp_Enable);
		BMC_AFE16_OVWakeUp_Enable = std::move(_x.BMC_AFE16_OVWakeUp_Enable);
		BMC_AFE17_OVWakeUp_Enable = std::move(_x.BMC_AFE17_OVWakeUp_Enable);
		BMC_AFE18_OVWakeUp_Enable = std::move(_x.BMC_AFE18_OVWakeUp_Enable);
		BMC_AFE19_OVWakeUp_Enable = std::move(_x.BMC_AFE19_OVWakeUp_Enable);
		BMC_AFE20_OVWakeUp_Enable = std::move(_x.BMC_AFE20_OVWakeUp_Enable);
		BMC_AFE1_UVWakeUp_Enable = std::move(_x.BMC_AFE1_UVWakeUp_Enable);
		BMC_AFE2_UVWakeUp_Enable = std::move(_x.BMC_AFE2_UVWakeUp_Enable);
		BMC_AFE3_UVWakeUp_Enable = std::move(_x.BMC_AFE3_UVWakeUp_Enable);
		BMC_AFE4_UVWakeUp_Enable = std::move(_x.BMC_AFE4_UVWakeUp_Enable);
		BMC_AFE5_UVWakeUp_Enable = std::move(_x.BMC_AFE5_UVWakeUp_Enable);
		BMC_AFE6_UVWakeUp_Enable = std::move(_x.BMC_AFE6_UVWakeUp_Enable);
		BMC_AFE7_UVWakeUp_Enable = std::move(_x.BMC_AFE7_UVWakeUp_Enable);
		BMC_AFE8_UVWakeUp_Enable = std::move(_x.BMC_AFE8_UVWakeUp_Enable);
		BMC_AFE9_UVWakeUp_Enable = std::move(_x.BMC_AFE9_UVWakeUp_Enable);
		BMC_AFE10_UVWakeUp_Enable = std::move(_x.BMC_AFE10_UVWakeUp_Enable);
		BMC_AFE11_UVWakeUp_Enable = std::move(_x.BMC_AFE11_UVWakeUp_Enable);
		BMC_AFE12_UVWakeUp_Enable = std::move(_x.BMC_AFE12_UVWakeUp_Enable);
		BMC_AFE13_UVWakeUp_Enable = std::move(_x.BMC_AFE13_UVWakeUp_Enable);
		BMC_AFE14_UVWakeUp_Enable = std::move(_x.BMC_AFE14_UVWakeUp_Enable);
		BMC_AFE15_UVWakeUp_Enable = std::move(_x.BMC_AFE15_UVWakeUp_Enable);
		BMC_AFE16_UVWakeUp_Enable = std::move(_x.BMC_AFE16_UVWakeUp_Enable);
		BMC_AFE17_UVWakeUp_Enable = std::move(_x.BMC_AFE17_UVWakeUp_Enable);
		BMC_AFE18_UVWakeUp_Enable = std::move(_x.BMC_AFE18_UVWakeUp_Enable);
		BMC_AFE19_UVWakeUp_Enable = std::move(_x.BMC_AFE19_UVWakeUp_Enable);
		BMC_AFE20_UVWakeUp_Enable = std::move(_x.BMC_AFE20_UVWakeUp_Enable);
		BMC_AFE1_OTWakeUp_Enable = std::move(_x.BMC_AFE1_OTWakeUp_Enable);
		BMC_AFE2_OTWakeUp_Enable = std::move(_x.BMC_AFE2_OTWakeUp_Enable);
		BMC_AFE3_OTWakeUp_Enable = std::move(_x.BMC_AFE3_OTWakeUp_Enable);
		BMC_AFE4_OTWakeUp_Enable = std::move(_x.BMC_AFE4_OTWakeUp_Enable);
		BMC_AFE5_OTWakeUp_Enable = std::move(_x.BMC_AFE5_OTWakeUp_Enable);
		BMC_AFE6_OTWakeUp_Enable = std::move(_x.BMC_AFE6_OTWakeUp_Enable);
		BMC_AFE7_OTWakeUp_Enable = std::move(_x.BMC_AFE7_OTWakeUp_Enable);
		BMC_AFE8_OTWakeUp_Enable = std::move(_x.BMC_AFE8_OTWakeUp_Enable);
		BMC_AFE9_OTWakeUp_Enable = std::move(_x.BMC_AFE9_OTWakeUp_Enable);
		BMC_AFE10_OTWakeUp_Enable = std::move(_x.BMC_AFE10_OTWakeUp_Enable);
		BMC_AFE11_OTWakeUp_Enable = std::move(_x.BMC_AFE11_OTWakeUp_Enable);
		BMC_AFE12_OTWakeUp_Enable = std::move(_x.BMC_AFE12_OTWakeUp_Enable);
		BMC_AFE13_OTWakeUp_Enable = std::move(_x.BMC_AFE13_OTWakeUp_Enable);
		BMC_AFE14_OTWakeUp_Enable = std::move(_x.BMC_AFE14_OTWakeUp_Enable);
		BMC_AFE15_OTWakeUp_Enable = std::move(_x.BMC_AFE15_OTWakeUp_Enable);
		BMC_AFE16_OTWakeUp_Enable = std::move(_x.BMC_AFE16_OTWakeUp_Enable);
		BMC_AFE17_OTWakeUp_Enable = std::move(_x.BMC_AFE17_OTWakeUp_Enable);
		BMC_AFE18_OTWakeUp_Enable = std::move(_x.BMC_AFE18_OTWakeUp_Enable);
		BMC_AFE19_OTWakeUp_Enable = std::move(_x.BMC_AFE19_OTWakeUp_Enable);
		BMC_AFE20_OTWakeUp_Enable = std::move(_x.BMC_AFE20_OTWakeUp_Enable);
		BMC_AFE1_OVThreshold = std::move(_x.BMC_AFE1_OVThreshold);
		BMC_AFE2_OVThreshold = std::move(_x.BMC_AFE2_OVThreshold);
		BMC_AFE3_OVThreshold = std::move(_x.BMC_AFE3_OVThreshold);
		BMC_AFE4_OVThreshold = std::move(_x.BMC_AFE4_OVThreshold);
		BMC_AFE5_OVThreshold = std::move(_x.BMC_AFE5_OVThreshold);
		BMC_AFE6_OVThreshold = std::move(_x.BMC_AFE6_OVThreshold);
		BMC_AFE7_OVThreshold = std::move(_x.BMC_AFE7_OVThreshold);
		BMC_AFE8_OVThreshold = std::move(_x.BMC_AFE8_OVThreshold);
		BMC_AFE9_OVThreshold = std::move(_x.BMC_AFE9_OVThreshold);
		BMC_AFE10_OVThreshold = std::move(_x.BMC_AFE10_OVThreshold);
		BMC_AFE11_OVThreshold = std::move(_x.BMC_AFE11_OVThreshold);
		BMC_AFE12_OVThreshold = std::move(_x.BMC_AFE12_OVThreshold);
		BMC_AFE13_OVThreshold = std::move(_x.BMC_AFE13_OVThreshold);
		BMC_AFE14_OVThreshold = std::move(_x.BMC_AFE14_OVThreshold);
		BMC_AFE15_OVThreshold = std::move(_x.BMC_AFE15_OVThreshold);
		BMC_AFE16_OVThreshold = std::move(_x.BMC_AFE16_OVThreshold);
		BMC_AFE17_OVThreshold = std::move(_x.BMC_AFE17_OVThreshold);
		BMC_AFE18_OVThreshold = std::move(_x.BMC_AFE18_OVThreshold);
		BMC_AFE19_OVThreshold = std::move(_x.BMC_AFE19_OVThreshold);
		BMC_AFE20_OVThreshold = std::move(_x.BMC_AFE20_OVThreshold);
		BMC_AFE1_UVThreshold = std::move(_x.BMC_AFE1_UVThreshold);
		BMC_AFE2_UVThreshold = std::move(_x.BMC_AFE2_UVThreshold);
		BMC_AFE3_UVThreshold = std::move(_x.BMC_AFE3_UVThreshold);
		BMC_AFE4_UVThreshold = std::move(_x.BMC_AFE4_UVThreshold);
		BMC_AFE5_UVThreshold = std::move(_x.BMC_AFE5_UVThreshold);
		BMC_AFE6_UVThreshold = std::move(_x.BMC_AFE6_UVThreshold);
		BMC_AFE7_UVThreshold = std::move(_x.BMC_AFE7_UVThreshold);
		BMC_AFE8_UVThreshold = std::move(_x.BMC_AFE8_UVThreshold);
		BMC_AFE9_UVThreshold = std::move(_x.BMC_AFE9_UVThreshold);
		BMC_AFE10_UVThreshold = std::move(_x.BMC_AFE10_UVThreshold);
		BMC_AFE11_UVThreshold = std::move(_x.BMC_AFE11_UVThreshold);
		BMC_AFE12_UVThreshold = std::move(_x.BMC_AFE12_UVThreshold);
		BMC_AFE13_UVThreshold = std::move(_x.BMC_AFE13_UVThreshold);
		BMC_AFE14_UVThreshold = std::move(_x.BMC_AFE14_UVThreshold);
		BMC_AFE15_UVThreshold = std::move(_x.BMC_AFE15_UVThreshold);
		BMC_AFE16_UVThreshold = std::move(_x.BMC_AFE16_UVThreshold);
		BMC_AFE17_UVThreshold = std::move(_x.BMC_AFE17_UVThreshold);
		BMC_AFE18_UVThreshold = std::move(_x.BMC_AFE18_UVThreshold);
		BMC_AFE19_UVThreshold = std::move(_x.BMC_AFE19_UVThreshold);
		BMC_AFE20_UVThreshold = std::move(_x.BMC_AFE20_UVThreshold);
		BMC_AFE1_OTThreshold = std::move(_x.BMC_AFE1_OTThreshold);
		BMC_AFE2_OTThreshold = std::move(_x.BMC_AFE2_OTThreshold);
		BMC_AFE3_OTThreshold = std::move(_x.BMC_AFE3_OTThreshold);
		BMC_AFE4_OTThreshold = std::move(_x.BMC_AFE4_OTThreshold);
		BMC_AFE5_OTThreshold = std::move(_x.BMC_AFE5_OTThreshold);
		BMC_AFE6_OTThreshold = std::move(_x.BMC_AFE6_OTThreshold);
		BMC_AFE7_OTThreshold = std::move(_x.BMC_AFE7_OTThreshold);
		BMC_AFE8_OTThreshold = std::move(_x.BMC_AFE8_OTThreshold);
		BMC_AFE9_OTThreshold = std::move(_x.BMC_AFE9_OTThreshold);
		BMC_AFE10_OTThreshold = std::move(_x.BMC_AFE10_OTThreshold);
		BMC_AFE11_OTThreshold = std::move(_x.BMC_AFE11_OTThreshold);
		BMC_AFE12_OTThreshold = std::move(_x.BMC_AFE12_OTThreshold);
		BMC_AFE13_OTThreshold = std::move(_x.BMC_AFE13_OTThreshold);
		BMC_AFE14_OTThreshold = std::move(_x.BMC_AFE14_OTThreshold);
		BMC_AFE15_OTThreshold = std::move(_x.BMC_AFE15_OTThreshold);
		BMC_AFE16_OTThreshold = std::move(_x.BMC_AFE16_OTThreshold);
		BMC_AFE17_OTThreshold = std::move(_x.BMC_AFE17_OTThreshold);
		BMC_AFE18_OTThreshold = std::move(_x.BMC_AFE18_OTThreshold);
		BMC_AFE19_OTThreshold = std::move(_x.BMC_AFE19_OTThreshold);
		BMC_AFE20_OTThreshold = std::move(_x.BMC_AFE20_OTThreshold);
	}
	BDCBMCAFE& operator=(const BDCBMCAFE &_x){
		BMC_AFEWakeUpState = _x.BMC_AFEWakeUpState;
		BMC_ResetByAFESetErr = _x.BMC_ResetByAFESetErr;
		BMC_NrResetByAFESetErr = _x.BMC_NrResetByAFESetErr;
		BMC_AFE1_WakeUpSrc = _x.BMC_AFE1_WakeUpSrc;
		BMC_AFE2_WakeUpSrc = _x.BMC_AFE2_WakeUpSrc;
		BMC_AFE3_WakeUpSrc = _x.BMC_AFE3_WakeUpSrc;
		BMC_AFE4_WakeUpSrc = _x.BMC_AFE4_WakeUpSrc;
		BMC_AFE5_WakeUpSrc = _x.BMC_AFE5_WakeUpSrc;
		BMC_AFE6_WakeUpSrc = _x.BMC_AFE6_WakeUpSrc;
		BMC_AFE7_WakeUpSrc = _x.BMC_AFE7_WakeUpSrc;
		BMC_AFE8_WakeUpSrc = _x.BMC_AFE8_WakeUpSrc;
		BMC_AFE9_WakeUpSrc = _x.BMC_AFE9_WakeUpSrc;
		BMC_AFE10_WakeUpSrc = _x.BMC_AFE10_WakeUpSrc;
		BMC_AFE11_WakeUpSrc = _x.BMC_AFE11_WakeUpSrc;
		BMC_AFE12_WakeUpSrc = _x.BMC_AFE12_WakeUpSrc;
		BMC_AFE13_WakeUpSrc = _x.BMC_AFE13_WakeUpSrc;
		BMC_AFE14_WakeUpSrc = _x.BMC_AFE14_WakeUpSrc;
		BMC_AFE15_WakeUpSrc = _x.BMC_AFE15_WakeUpSrc;
		BMC_AFE16_WakeUpSrc = _x.BMC_AFE16_WakeUpSrc;
		BMC_AFE17_WakeUpSrc = _x.BMC_AFE17_WakeUpSrc;
		BMC_AFE18_WakeUpSrc = _x.BMC_AFE18_WakeUpSrc;
		BMC_AFE19_WakeUpSrc = _x.BMC_AFE19_WakeUpSrc;
		BMC_AFE20_WakeUpSrc = _x.BMC_AFE20_WakeUpSrc;
		BMC_AFE1_OVWakeUp_Enable = _x.BMC_AFE1_OVWakeUp_Enable;
		BMC_AFE2_OVWakeUp_Enable = _x.BMC_AFE2_OVWakeUp_Enable;
		BMC_AFE3_OVWakeUp_Enable = _x.BMC_AFE3_OVWakeUp_Enable;
		BMC_AFE4_OVWakeUp_Enable = _x.BMC_AFE4_OVWakeUp_Enable;
		BMC_AFE5_OVWakeUp_Enable = _x.BMC_AFE5_OVWakeUp_Enable;
		BMC_AFE6_OVWakeUp_Enable = _x.BMC_AFE6_OVWakeUp_Enable;
		BMC_AFE7_OVWakeUp_Enable = _x.BMC_AFE7_OVWakeUp_Enable;
		BMC_AFE8_OVWakeUp_Enable = _x.BMC_AFE8_OVWakeUp_Enable;
		BMC_AFE9_OVWakeUp_Enable = _x.BMC_AFE9_OVWakeUp_Enable;
		BMC_AFE10_OVWakeUp_Enable = _x.BMC_AFE10_OVWakeUp_Enable;
		BMC_AFE11_OVWakeUp_Enable = _x.BMC_AFE11_OVWakeUp_Enable;
		BMC_AFE12_OVWakeUp_Enable = _x.BMC_AFE12_OVWakeUp_Enable;
		BMC_AFE13_OVWakeUp_Enable = _x.BMC_AFE13_OVWakeUp_Enable;
		BMC_AFE14_OVWakeUp_Enable = _x.BMC_AFE14_OVWakeUp_Enable;
		BMC_AFE15_OVWakeUp_Enable = _x.BMC_AFE15_OVWakeUp_Enable;
		BMC_AFE16_OVWakeUp_Enable = _x.BMC_AFE16_OVWakeUp_Enable;
		BMC_AFE17_OVWakeUp_Enable = _x.BMC_AFE17_OVWakeUp_Enable;
		BMC_AFE18_OVWakeUp_Enable = _x.BMC_AFE18_OVWakeUp_Enable;
		BMC_AFE19_OVWakeUp_Enable = _x.BMC_AFE19_OVWakeUp_Enable;
		BMC_AFE20_OVWakeUp_Enable = _x.BMC_AFE20_OVWakeUp_Enable;
		BMC_AFE1_UVWakeUp_Enable = _x.BMC_AFE1_UVWakeUp_Enable;
		BMC_AFE2_UVWakeUp_Enable = _x.BMC_AFE2_UVWakeUp_Enable;
		BMC_AFE3_UVWakeUp_Enable = _x.BMC_AFE3_UVWakeUp_Enable;
		BMC_AFE4_UVWakeUp_Enable = _x.BMC_AFE4_UVWakeUp_Enable;
		BMC_AFE5_UVWakeUp_Enable = _x.BMC_AFE5_UVWakeUp_Enable;
		BMC_AFE6_UVWakeUp_Enable = _x.BMC_AFE6_UVWakeUp_Enable;
		BMC_AFE7_UVWakeUp_Enable = _x.BMC_AFE7_UVWakeUp_Enable;
		BMC_AFE8_UVWakeUp_Enable = _x.BMC_AFE8_UVWakeUp_Enable;
		BMC_AFE9_UVWakeUp_Enable = _x.BMC_AFE9_UVWakeUp_Enable;
		BMC_AFE10_UVWakeUp_Enable = _x.BMC_AFE10_UVWakeUp_Enable;
		BMC_AFE11_UVWakeUp_Enable = _x.BMC_AFE11_UVWakeUp_Enable;
		BMC_AFE12_UVWakeUp_Enable = _x.BMC_AFE12_UVWakeUp_Enable;
		BMC_AFE13_UVWakeUp_Enable = _x.BMC_AFE13_UVWakeUp_Enable;
		BMC_AFE14_UVWakeUp_Enable = _x.BMC_AFE14_UVWakeUp_Enable;
		BMC_AFE15_UVWakeUp_Enable = _x.BMC_AFE15_UVWakeUp_Enable;
		BMC_AFE16_UVWakeUp_Enable = _x.BMC_AFE16_UVWakeUp_Enable;
		BMC_AFE17_UVWakeUp_Enable = _x.BMC_AFE17_UVWakeUp_Enable;
		BMC_AFE18_UVWakeUp_Enable = _x.BMC_AFE18_UVWakeUp_Enable;
		BMC_AFE19_UVWakeUp_Enable = _x.BMC_AFE19_UVWakeUp_Enable;
		BMC_AFE20_UVWakeUp_Enable = _x.BMC_AFE20_UVWakeUp_Enable;
		BMC_AFE1_OTWakeUp_Enable = _x.BMC_AFE1_OTWakeUp_Enable;
		BMC_AFE2_OTWakeUp_Enable = _x.BMC_AFE2_OTWakeUp_Enable;
		BMC_AFE3_OTWakeUp_Enable = _x.BMC_AFE3_OTWakeUp_Enable;
		BMC_AFE4_OTWakeUp_Enable = _x.BMC_AFE4_OTWakeUp_Enable;
		BMC_AFE5_OTWakeUp_Enable = _x.BMC_AFE5_OTWakeUp_Enable;
		BMC_AFE6_OTWakeUp_Enable = _x.BMC_AFE6_OTWakeUp_Enable;
		BMC_AFE7_OTWakeUp_Enable = _x.BMC_AFE7_OTWakeUp_Enable;
		BMC_AFE8_OTWakeUp_Enable = _x.BMC_AFE8_OTWakeUp_Enable;
		BMC_AFE9_OTWakeUp_Enable = _x.BMC_AFE9_OTWakeUp_Enable;
		BMC_AFE10_OTWakeUp_Enable = _x.BMC_AFE10_OTWakeUp_Enable;
		BMC_AFE11_OTWakeUp_Enable = _x.BMC_AFE11_OTWakeUp_Enable;
		BMC_AFE12_OTWakeUp_Enable = _x.BMC_AFE12_OTWakeUp_Enable;
		BMC_AFE13_OTWakeUp_Enable = _x.BMC_AFE13_OTWakeUp_Enable;
		BMC_AFE14_OTWakeUp_Enable = _x.BMC_AFE14_OTWakeUp_Enable;
		BMC_AFE15_OTWakeUp_Enable = _x.BMC_AFE15_OTWakeUp_Enable;
		BMC_AFE16_OTWakeUp_Enable = _x.BMC_AFE16_OTWakeUp_Enable;
		BMC_AFE17_OTWakeUp_Enable = _x.BMC_AFE17_OTWakeUp_Enable;
		BMC_AFE18_OTWakeUp_Enable = _x.BMC_AFE18_OTWakeUp_Enable;
		BMC_AFE19_OTWakeUp_Enable = _x.BMC_AFE19_OTWakeUp_Enable;
		BMC_AFE20_OTWakeUp_Enable = _x.BMC_AFE20_OTWakeUp_Enable;
		BMC_AFE1_OVThreshold = _x.BMC_AFE1_OVThreshold;
		BMC_AFE2_OVThreshold = _x.BMC_AFE2_OVThreshold;
		BMC_AFE3_OVThreshold = _x.BMC_AFE3_OVThreshold;
		BMC_AFE4_OVThreshold = _x.BMC_AFE4_OVThreshold;
		BMC_AFE5_OVThreshold = _x.BMC_AFE5_OVThreshold;
		BMC_AFE6_OVThreshold = _x.BMC_AFE6_OVThreshold;
		BMC_AFE7_OVThreshold = _x.BMC_AFE7_OVThreshold;
		BMC_AFE8_OVThreshold = _x.BMC_AFE8_OVThreshold;
		BMC_AFE9_OVThreshold = _x.BMC_AFE9_OVThreshold;
		BMC_AFE10_OVThreshold = _x.BMC_AFE10_OVThreshold;
		BMC_AFE11_OVThreshold = _x.BMC_AFE11_OVThreshold;
		BMC_AFE12_OVThreshold = _x.BMC_AFE12_OVThreshold;
		BMC_AFE13_OVThreshold = _x.BMC_AFE13_OVThreshold;
		BMC_AFE14_OVThreshold = _x.BMC_AFE14_OVThreshold;
		BMC_AFE15_OVThreshold = _x.BMC_AFE15_OVThreshold;
		BMC_AFE16_OVThreshold = _x.BMC_AFE16_OVThreshold;
		BMC_AFE17_OVThreshold = _x.BMC_AFE17_OVThreshold;
		BMC_AFE18_OVThreshold = _x.BMC_AFE18_OVThreshold;
		BMC_AFE19_OVThreshold = _x.BMC_AFE19_OVThreshold;
		BMC_AFE20_OVThreshold = _x.BMC_AFE20_OVThreshold;
		BMC_AFE1_UVThreshold = _x.BMC_AFE1_UVThreshold;
		BMC_AFE2_UVThreshold = _x.BMC_AFE2_UVThreshold;
		BMC_AFE3_UVThreshold = _x.BMC_AFE3_UVThreshold;
		BMC_AFE4_UVThreshold = _x.BMC_AFE4_UVThreshold;
		BMC_AFE5_UVThreshold = _x.BMC_AFE5_UVThreshold;
		BMC_AFE6_UVThreshold = _x.BMC_AFE6_UVThreshold;
		BMC_AFE7_UVThreshold = _x.BMC_AFE7_UVThreshold;
		BMC_AFE8_UVThreshold = _x.BMC_AFE8_UVThreshold;
		BMC_AFE9_UVThreshold = _x.BMC_AFE9_UVThreshold;
		BMC_AFE10_UVThreshold = _x.BMC_AFE10_UVThreshold;
		BMC_AFE11_UVThreshold = _x.BMC_AFE11_UVThreshold;
		BMC_AFE12_UVThreshold = _x.BMC_AFE12_UVThreshold;
		BMC_AFE13_UVThreshold = _x.BMC_AFE13_UVThreshold;
		BMC_AFE14_UVThreshold = _x.BMC_AFE14_UVThreshold;
		BMC_AFE15_UVThreshold = _x.BMC_AFE15_UVThreshold;
		BMC_AFE16_UVThreshold = _x.BMC_AFE16_UVThreshold;
		BMC_AFE17_UVThreshold = _x.BMC_AFE17_UVThreshold;
		BMC_AFE18_UVThreshold = _x.BMC_AFE18_UVThreshold;
		BMC_AFE19_UVThreshold = _x.BMC_AFE19_UVThreshold;
		BMC_AFE20_UVThreshold = _x.BMC_AFE20_UVThreshold;
		BMC_AFE1_OTThreshold = _x.BMC_AFE1_OTThreshold;
		BMC_AFE2_OTThreshold = _x.BMC_AFE2_OTThreshold;
		BMC_AFE3_OTThreshold = _x.BMC_AFE3_OTThreshold;
		BMC_AFE4_OTThreshold = _x.BMC_AFE4_OTThreshold;
		BMC_AFE5_OTThreshold = _x.BMC_AFE5_OTThreshold;
		BMC_AFE6_OTThreshold = _x.BMC_AFE6_OTThreshold;
		BMC_AFE7_OTThreshold = _x.BMC_AFE7_OTThreshold;
		BMC_AFE8_OTThreshold = _x.BMC_AFE8_OTThreshold;
		BMC_AFE9_OTThreshold = _x.BMC_AFE9_OTThreshold;
		BMC_AFE10_OTThreshold = _x.BMC_AFE10_OTThreshold;
		BMC_AFE11_OTThreshold = _x.BMC_AFE11_OTThreshold;
		BMC_AFE12_OTThreshold = _x.BMC_AFE12_OTThreshold;
		BMC_AFE13_OTThreshold = _x.BMC_AFE13_OTThreshold;
		BMC_AFE14_OTThreshold = _x.BMC_AFE14_OTThreshold;
		BMC_AFE15_OTThreshold = _x.BMC_AFE15_OTThreshold;
		BMC_AFE16_OTThreshold = _x.BMC_AFE16_OTThreshold;
		BMC_AFE17_OTThreshold = _x.BMC_AFE17_OTThreshold;
		BMC_AFE18_OTThreshold = _x.BMC_AFE18_OTThreshold;
		BMC_AFE19_OTThreshold = _x.BMC_AFE19_OTThreshold;
		BMC_AFE20_OTThreshold = _x.BMC_AFE20_OTThreshold;
		return *this;
	}
	BDCBMCAFE& operator=(BDCBMCAFE &&_x){
		BMC_AFEWakeUpState = std::move(_x.BMC_AFEWakeUpState);
		BMC_ResetByAFESetErr = std::move(_x.BMC_ResetByAFESetErr);
		BMC_NrResetByAFESetErr = std::move(_x.BMC_NrResetByAFESetErr);
		BMC_AFE1_WakeUpSrc = std::move(_x.BMC_AFE1_WakeUpSrc);
		BMC_AFE2_WakeUpSrc = std::move(_x.BMC_AFE2_WakeUpSrc);
		BMC_AFE3_WakeUpSrc = std::move(_x.BMC_AFE3_WakeUpSrc);
		BMC_AFE4_WakeUpSrc = std::move(_x.BMC_AFE4_WakeUpSrc);
		BMC_AFE5_WakeUpSrc = std::move(_x.BMC_AFE5_WakeUpSrc);
		BMC_AFE6_WakeUpSrc = std::move(_x.BMC_AFE6_WakeUpSrc);
		BMC_AFE7_WakeUpSrc = std::move(_x.BMC_AFE7_WakeUpSrc);
		BMC_AFE8_WakeUpSrc = std::move(_x.BMC_AFE8_WakeUpSrc);
		BMC_AFE9_WakeUpSrc = std::move(_x.BMC_AFE9_WakeUpSrc);
		BMC_AFE10_WakeUpSrc = std::move(_x.BMC_AFE10_WakeUpSrc);
		BMC_AFE11_WakeUpSrc = std::move(_x.BMC_AFE11_WakeUpSrc);
		BMC_AFE12_WakeUpSrc = std::move(_x.BMC_AFE12_WakeUpSrc);
		BMC_AFE13_WakeUpSrc = std::move(_x.BMC_AFE13_WakeUpSrc);
		BMC_AFE14_WakeUpSrc = std::move(_x.BMC_AFE14_WakeUpSrc);
		BMC_AFE15_WakeUpSrc = std::move(_x.BMC_AFE15_WakeUpSrc);
		BMC_AFE16_WakeUpSrc = std::move(_x.BMC_AFE16_WakeUpSrc);
		BMC_AFE17_WakeUpSrc = std::move(_x.BMC_AFE17_WakeUpSrc);
		BMC_AFE18_WakeUpSrc = std::move(_x.BMC_AFE18_WakeUpSrc);
		BMC_AFE19_WakeUpSrc = std::move(_x.BMC_AFE19_WakeUpSrc);
		BMC_AFE20_WakeUpSrc = std::move(_x.BMC_AFE20_WakeUpSrc);
		BMC_AFE1_OVWakeUp_Enable = std::move(_x.BMC_AFE1_OVWakeUp_Enable);
		BMC_AFE2_OVWakeUp_Enable = std::move(_x.BMC_AFE2_OVWakeUp_Enable);
		BMC_AFE3_OVWakeUp_Enable = std::move(_x.BMC_AFE3_OVWakeUp_Enable);
		BMC_AFE4_OVWakeUp_Enable = std::move(_x.BMC_AFE4_OVWakeUp_Enable);
		BMC_AFE5_OVWakeUp_Enable = std::move(_x.BMC_AFE5_OVWakeUp_Enable);
		BMC_AFE6_OVWakeUp_Enable = std::move(_x.BMC_AFE6_OVWakeUp_Enable);
		BMC_AFE7_OVWakeUp_Enable = std::move(_x.BMC_AFE7_OVWakeUp_Enable);
		BMC_AFE8_OVWakeUp_Enable = std::move(_x.BMC_AFE8_OVWakeUp_Enable);
		BMC_AFE9_OVWakeUp_Enable = std::move(_x.BMC_AFE9_OVWakeUp_Enable);
		BMC_AFE10_OVWakeUp_Enable = std::move(_x.BMC_AFE10_OVWakeUp_Enable);
		BMC_AFE11_OVWakeUp_Enable = std::move(_x.BMC_AFE11_OVWakeUp_Enable);
		BMC_AFE12_OVWakeUp_Enable = std::move(_x.BMC_AFE12_OVWakeUp_Enable);
		BMC_AFE13_OVWakeUp_Enable = std::move(_x.BMC_AFE13_OVWakeUp_Enable);
		BMC_AFE14_OVWakeUp_Enable = std::move(_x.BMC_AFE14_OVWakeUp_Enable);
		BMC_AFE15_OVWakeUp_Enable = std::move(_x.BMC_AFE15_OVWakeUp_Enable);
		BMC_AFE16_OVWakeUp_Enable = std::move(_x.BMC_AFE16_OVWakeUp_Enable);
		BMC_AFE17_OVWakeUp_Enable = std::move(_x.BMC_AFE17_OVWakeUp_Enable);
		BMC_AFE18_OVWakeUp_Enable = std::move(_x.BMC_AFE18_OVWakeUp_Enable);
		BMC_AFE19_OVWakeUp_Enable = std::move(_x.BMC_AFE19_OVWakeUp_Enable);
		BMC_AFE20_OVWakeUp_Enable = std::move(_x.BMC_AFE20_OVWakeUp_Enable);
		BMC_AFE1_UVWakeUp_Enable = std::move(_x.BMC_AFE1_UVWakeUp_Enable);
		BMC_AFE2_UVWakeUp_Enable = std::move(_x.BMC_AFE2_UVWakeUp_Enable);
		BMC_AFE3_UVWakeUp_Enable = std::move(_x.BMC_AFE3_UVWakeUp_Enable);
		BMC_AFE4_UVWakeUp_Enable = std::move(_x.BMC_AFE4_UVWakeUp_Enable);
		BMC_AFE5_UVWakeUp_Enable = std::move(_x.BMC_AFE5_UVWakeUp_Enable);
		BMC_AFE6_UVWakeUp_Enable = std::move(_x.BMC_AFE6_UVWakeUp_Enable);
		BMC_AFE7_UVWakeUp_Enable = std::move(_x.BMC_AFE7_UVWakeUp_Enable);
		BMC_AFE8_UVWakeUp_Enable = std::move(_x.BMC_AFE8_UVWakeUp_Enable);
		BMC_AFE9_UVWakeUp_Enable = std::move(_x.BMC_AFE9_UVWakeUp_Enable);
		BMC_AFE10_UVWakeUp_Enable = std::move(_x.BMC_AFE10_UVWakeUp_Enable);
		BMC_AFE11_UVWakeUp_Enable = std::move(_x.BMC_AFE11_UVWakeUp_Enable);
		BMC_AFE12_UVWakeUp_Enable = std::move(_x.BMC_AFE12_UVWakeUp_Enable);
		BMC_AFE13_UVWakeUp_Enable = std::move(_x.BMC_AFE13_UVWakeUp_Enable);
		BMC_AFE14_UVWakeUp_Enable = std::move(_x.BMC_AFE14_UVWakeUp_Enable);
		BMC_AFE15_UVWakeUp_Enable = std::move(_x.BMC_AFE15_UVWakeUp_Enable);
		BMC_AFE16_UVWakeUp_Enable = std::move(_x.BMC_AFE16_UVWakeUp_Enable);
		BMC_AFE17_UVWakeUp_Enable = std::move(_x.BMC_AFE17_UVWakeUp_Enable);
		BMC_AFE18_UVWakeUp_Enable = std::move(_x.BMC_AFE18_UVWakeUp_Enable);
		BMC_AFE19_UVWakeUp_Enable = std::move(_x.BMC_AFE19_UVWakeUp_Enable);
		BMC_AFE20_UVWakeUp_Enable = std::move(_x.BMC_AFE20_UVWakeUp_Enable);
		BMC_AFE1_OTWakeUp_Enable = std::move(_x.BMC_AFE1_OTWakeUp_Enable);
		BMC_AFE2_OTWakeUp_Enable = std::move(_x.BMC_AFE2_OTWakeUp_Enable);
		BMC_AFE3_OTWakeUp_Enable = std::move(_x.BMC_AFE3_OTWakeUp_Enable);
		BMC_AFE4_OTWakeUp_Enable = std::move(_x.BMC_AFE4_OTWakeUp_Enable);
		BMC_AFE5_OTWakeUp_Enable = std::move(_x.BMC_AFE5_OTWakeUp_Enable);
		BMC_AFE6_OTWakeUp_Enable = std::move(_x.BMC_AFE6_OTWakeUp_Enable);
		BMC_AFE7_OTWakeUp_Enable = std::move(_x.BMC_AFE7_OTWakeUp_Enable);
		BMC_AFE8_OTWakeUp_Enable = std::move(_x.BMC_AFE8_OTWakeUp_Enable);
		BMC_AFE9_OTWakeUp_Enable = std::move(_x.BMC_AFE9_OTWakeUp_Enable);
		BMC_AFE10_OTWakeUp_Enable = std::move(_x.BMC_AFE10_OTWakeUp_Enable);
		BMC_AFE11_OTWakeUp_Enable = std::move(_x.BMC_AFE11_OTWakeUp_Enable);
		BMC_AFE12_OTWakeUp_Enable = std::move(_x.BMC_AFE12_OTWakeUp_Enable);
		BMC_AFE13_OTWakeUp_Enable = std::move(_x.BMC_AFE13_OTWakeUp_Enable);
		BMC_AFE14_OTWakeUp_Enable = std::move(_x.BMC_AFE14_OTWakeUp_Enable);
		BMC_AFE15_OTWakeUp_Enable = std::move(_x.BMC_AFE15_OTWakeUp_Enable);
		BMC_AFE16_OTWakeUp_Enable = std::move(_x.BMC_AFE16_OTWakeUp_Enable);
		BMC_AFE17_OTWakeUp_Enable = std::move(_x.BMC_AFE17_OTWakeUp_Enable);
		BMC_AFE18_OTWakeUp_Enable = std::move(_x.BMC_AFE18_OTWakeUp_Enable);
		BMC_AFE19_OTWakeUp_Enable = std::move(_x.BMC_AFE19_OTWakeUp_Enable);
		BMC_AFE20_OTWakeUp_Enable = std::move(_x.BMC_AFE20_OTWakeUp_Enable);
		BMC_AFE1_OVThreshold = std::move(_x.BMC_AFE1_OVThreshold);
		BMC_AFE2_OVThreshold = std::move(_x.BMC_AFE2_OVThreshold);
		BMC_AFE3_OVThreshold = std::move(_x.BMC_AFE3_OVThreshold);
		BMC_AFE4_OVThreshold = std::move(_x.BMC_AFE4_OVThreshold);
		BMC_AFE5_OVThreshold = std::move(_x.BMC_AFE5_OVThreshold);
		BMC_AFE6_OVThreshold = std::move(_x.BMC_AFE6_OVThreshold);
		BMC_AFE7_OVThreshold = std::move(_x.BMC_AFE7_OVThreshold);
		BMC_AFE8_OVThreshold = std::move(_x.BMC_AFE8_OVThreshold);
		BMC_AFE9_OVThreshold = std::move(_x.BMC_AFE9_OVThreshold);
		BMC_AFE10_OVThreshold = std::move(_x.BMC_AFE10_OVThreshold);
		BMC_AFE11_OVThreshold = std::move(_x.BMC_AFE11_OVThreshold);
		BMC_AFE12_OVThreshold = std::move(_x.BMC_AFE12_OVThreshold);
		BMC_AFE13_OVThreshold = std::move(_x.BMC_AFE13_OVThreshold);
		BMC_AFE14_OVThreshold = std::move(_x.BMC_AFE14_OVThreshold);
		BMC_AFE15_OVThreshold = std::move(_x.BMC_AFE15_OVThreshold);
		BMC_AFE16_OVThreshold = std::move(_x.BMC_AFE16_OVThreshold);
		BMC_AFE17_OVThreshold = std::move(_x.BMC_AFE17_OVThreshold);
		BMC_AFE18_OVThreshold = std::move(_x.BMC_AFE18_OVThreshold);
		BMC_AFE19_OVThreshold = std::move(_x.BMC_AFE19_OVThreshold);
		BMC_AFE20_OVThreshold = std::move(_x.BMC_AFE20_OVThreshold);
		BMC_AFE1_UVThreshold = std::move(_x.BMC_AFE1_UVThreshold);
		BMC_AFE2_UVThreshold = std::move(_x.BMC_AFE2_UVThreshold);
		BMC_AFE3_UVThreshold = std::move(_x.BMC_AFE3_UVThreshold);
		BMC_AFE4_UVThreshold = std::move(_x.BMC_AFE4_UVThreshold);
		BMC_AFE5_UVThreshold = std::move(_x.BMC_AFE5_UVThreshold);
		BMC_AFE6_UVThreshold = std::move(_x.BMC_AFE6_UVThreshold);
		BMC_AFE7_UVThreshold = std::move(_x.BMC_AFE7_UVThreshold);
		BMC_AFE8_UVThreshold = std::move(_x.BMC_AFE8_UVThreshold);
		BMC_AFE9_UVThreshold = std::move(_x.BMC_AFE9_UVThreshold);
		BMC_AFE10_UVThreshold = std::move(_x.BMC_AFE10_UVThreshold);
		BMC_AFE11_UVThreshold = std::move(_x.BMC_AFE11_UVThreshold);
		BMC_AFE12_UVThreshold = std::move(_x.BMC_AFE12_UVThreshold);
		BMC_AFE13_UVThreshold = std::move(_x.BMC_AFE13_UVThreshold);
		BMC_AFE14_UVThreshold = std::move(_x.BMC_AFE14_UVThreshold);
		BMC_AFE15_UVThreshold = std::move(_x.BMC_AFE15_UVThreshold);
		BMC_AFE16_UVThreshold = std::move(_x.BMC_AFE16_UVThreshold);
		BMC_AFE17_UVThreshold = std::move(_x.BMC_AFE17_UVThreshold);
		BMC_AFE18_UVThreshold = std::move(_x.BMC_AFE18_UVThreshold);
		BMC_AFE19_UVThreshold = std::move(_x.BMC_AFE19_UVThreshold);
		BMC_AFE20_UVThreshold = std::move(_x.BMC_AFE20_UVThreshold);
		BMC_AFE1_OTThreshold = std::move(_x.BMC_AFE1_OTThreshold);
		BMC_AFE2_OTThreshold = std::move(_x.BMC_AFE2_OTThreshold);
		BMC_AFE3_OTThreshold = std::move(_x.BMC_AFE3_OTThreshold);
		BMC_AFE4_OTThreshold = std::move(_x.BMC_AFE4_OTThreshold);
		BMC_AFE5_OTThreshold = std::move(_x.BMC_AFE5_OTThreshold);
		BMC_AFE6_OTThreshold = std::move(_x.BMC_AFE6_OTThreshold);
		BMC_AFE7_OTThreshold = std::move(_x.BMC_AFE7_OTThreshold);
		BMC_AFE8_OTThreshold = std::move(_x.BMC_AFE8_OTThreshold);
		BMC_AFE9_OTThreshold = std::move(_x.BMC_AFE9_OTThreshold);
		BMC_AFE10_OTThreshold = std::move(_x.BMC_AFE10_OTThreshold);
		BMC_AFE11_OTThreshold = std::move(_x.BMC_AFE11_OTThreshold);
		BMC_AFE12_OTThreshold = std::move(_x.BMC_AFE12_OTThreshold);
		BMC_AFE13_OTThreshold = std::move(_x.BMC_AFE13_OTThreshold);
		BMC_AFE14_OTThreshold = std::move(_x.BMC_AFE14_OTThreshold);
		BMC_AFE15_OTThreshold = std::move(_x.BMC_AFE15_OTThreshold);
		BMC_AFE16_OTThreshold = std::move(_x.BMC_AFE16_OTThreshold);
		BMC_AFE17_OTThreshold = std::move(_x.BMC_AFE17_OTThreshold);
		BMC_AFE18_OTThreshold = std::move(_x.BMC_AFE18_OTThreshold);
		BMC_AFE19_OTThreshold = std::move(_x.BMC_AFE19_OTThreshold);
		BMC_AFE20_OTThreshold = std::move(_x.BMC_AFE20_OTThreshold);
		return *this;
	}
*/

	using IsEnumerableTag = void;
	template<typename F>
	void enumerate(F& fun) {
		fun(BMC_AFEWakeUpState);
		fun(BMC_ResetByAFESetErr);
		fun(BMC_NrResetByAFESetErr);
		fun(BMC_AFE1_WakeUpSrc);
		fun(BMC_AFE2_WakeUpSrc);
		fun(BMC_AFE3_WakeUpSrc);
		fun(BMC_AFE4_WakeUpSrc);
		fun(BMC_AFE5_WakeUpSrc);
		fun(BMC_AFE6_WakeUpSrc);
		fun(BMC_AFE7_WakeUpSrc);
		fun(BMC_AFE8_WakeUpSrc);
		fun(BMC_AFE9_WakeUpSrc);
		fun(BMC_AFE10_WakeUpSrc);
		fun(BMC_AFE11_WakeUpSrc);
		fun(BMC_AFE12_WakeUpSrc);
		fun(BMC_AFE13_WakeUpSrc);
		fun(BMC_AFE14_WakeUpSrc);
		fun(BMC_AFE15_WakeUpSrc);
		fun(BMC_AFE16_WakeUpSrc);
		fun(BMC_AFE17_WakeUpSrc);
		fun(BMC_AFE18_WakeUpSrc);
		fun(BMC_AFE19_WakeUpSrc);
		fun(BMC_AFE20_WakeUpSrc);
		fun(BMC_AFE1_OVWakeUp_Enable);
		fun(BMC_AFE2_OVWakeUp_Enable);
		fun(BMC_AFE3_OVWakeUp_Enable);
		fun(BMC_AFE4_OVWakeUp_Enable);
		fun(BMC_AFE5_OVWakeUp_Enable);
		fun(BMC_AFE6_OVWakeUp_Enable);
		fun(BMC_AFE7_OVWakeUp_Enable);
		fun(BMC_AFE8_OVWakeUp_Enable);
		fun(BMC_AFE9_OVWakeUp_Enable);
		fun(BMC_AFE10_OVWakeUp_Enable);
		fun(BMC_AFE11_OVWakeUp_Enable);
		fun(BMC_AFE12_OVWakeUp_Enable);
		fun(BMC_AFE13_OVWakeUp_Enable);
		fun(BMC_AFE14_OVWakeUp_Enable);
		fun(BMC_AFE15_OVWakeUp_Enable);
		fun(BMC_AFE16_OVWakeUp_Enable);
		fun(BMC_AFE17_OVWakeUp_Enable);
		fun(BMC_AFE18_OVWakeUp_Enable);
		fun(BMC_AFE19_OVWakeUp_Enable);
		fun(BMC_AFE20_OVWakeUp_Enable);
		fun(BMC_AFE1_UVWakeUp_Enable);
		fun(BMC_AFE2_UVWakeUp_Enable);
		fun(BMC_AFE3_UVWakeUp_Enable);
		fun(BMC_AFE4_UVWakeUp_Enable);
		fun(BMC_AFE5_UVWakeUp_Enable);
		fun(BMC_AFE6_UVWakeUp_Enable);
		fun(BMC_AFE7_UVWakeUp_Enable);
		fun(BMC_AFE8_UVWakeUp_Enable);
		fun(BMC_AFE9_UVWakeUp_Enable);
		fun(BMC_AFE10_UVWakeUp_Enable);
		fun(BMC_AFE11_UVWakeUp_Enable);
		fun(BMC_AFE12_UVWakeUp_Enable);
		fun(BMC_AFE13_UVWakeUp_Enable);
		fun(BMC_AFE14_UVWakeUp_Enable);
		fun(BMC_AFE15_UVWakeUp_Enable);
		fun(BMC_AFE16_UVWakeUp_Enable);
		fun(BMC_AFE17_UVWakeUp_Enable);
		fun(BMC_AFE18_UVWakeUp_Enable);
		fun(BMC_AFE19_UVWakeUp_Enable);
		fun(BMC_AFE20_UVWakeUp_Enable);
		fun(BMC_AFE1_OTWakeUp_Enable);
		fun(BMC_AFE2_OTWakeUp_Enable);
		fun(BMC_AFE3_OTWakeUp_Enable);
		fun(BMC_AFE4_OTWakeUp_Enable);
		fun(BMC_AFE5_OTWakeUp_Enable);
		fun(BMC_AFE6_OTWakeUp_Enable);
		fun(BMC_AFE7_OTWakeUp_Enable);
		fun(BMC_AFE8_OTWakeUp_Enable);
		fun(BMC_AFE9_OTWakeUp_Enable);
		fun(BMC_AFE10_OTWakeUp_Enable);
		fun(BMC_AFE11_OTWakeUp_Enable);
		fun(BMC_AFE12_OTWakeUp_Enable);
		fun(BMC_AFE13_OTWakeUp_Enable);
		fun(BMC_AFE14_OTWakeUp_Enable);
		fun(BMC_AFE15_OTWakeUp_Enable);
		fun(BMC_AFE16_OTWakeUp_Enable);
		fun(BMC_AFE17_OTWakeUp_Enable);
		fun(BMC_AFE18_OTWakeUp_Enable);
		fun(BMC_AFE19_OTWakeUp_Enable);
		fun(BMC_AFE20_OTWakeUp_Enable);
		fun(BMC_AFE1_OVThreshold);
		fun(BMC_AFE2_OVThreshold);
		fun(BMC_AFE3_OVThreshold);
		fun(BMC_AFE4_OVThreshold);
		fun(BMC_AFE5_OVThreshold);
		fun(BMC_AFE6_OVThreshold);
		fun(BMC_AFE7_OVThreshold);
		fun(BMC_AFE8_OVThreshold);
		fun(BMC_AFE9_OVThreshold);
		fun(BMC_AFE10_OVThreshold);
		fun(BMC_AFE11_OVThreshold);
		fun(BMC_AFE12_OVThreshold);
		fun(BMC_AFE13_OVThreshold);
		fun(BMC_AFE14_OVThreshold);
		fun(BMC_AFE15_OVThreshold);
		fun(BMC_AFE16_OVThreshold);
		fun(BMC_AFE17_OVThreshold);
		fun(BMC_AFE18_OVThreshold);
		fun(BMC_AFE19_OVThreshold);
		fun(BMC_AFE20_OVThreshold);
		fun(BMC_AFE1_UVThreshold);
		fun(BMC_AFE2_UVThreshold);
		fun(BMC_AFE3_UVThreshold);
		fun(BMC_AFE4_UVThreshold);
		fun(BMC_AFE5_UVThreshold);
		fun(BMC_AFE6_UVThreshold);
		fun(BMC_AFE7_UVThreshold);
		fun(BMC_AFE8_UVThreshold);
		fun(BMC_AFE9_UVThreshold);
		fun(BMC_AFE10_UVThreshold);
		fun(BMC_AFE11_UVThreshold);
		fun(BMC_AFE12_UVThreshold);
		fun(BMC_AFE13_UVThreshold);
		fun(BMC_AFE14_UVThreshold);
		fun(BMC_AFE15_UVThreshold);
		fun(BMC_AFE16_UVThreshold);
		fun(BMC_AFE17_UVThreshold);
		fun(BMC_AFE18_UVThreshold);
		fun(BMC_AFE19_UVThreshold);
		fun(BMC_AFE20_UVThreshold);
		fun(BMC_AFE1_OTThreshold);
		fun(BMC_AFE2_OTThreshold);
		fun(BMC_AFE3_OTThreshold);
		fun(BMC_AFE4_OTThreshold);
		fun(BMC_AFE5_OTThreshold);
		fun(BMC_AFE6_OTThreshold);
		fun(BMC_AFE7_OTThreshold);
		fun(BMC_AFE8_OTThreshold);
		fun(BMC_AFE9_OTThreshold);
		fun(BMC_AFE10_OTThreshold);
		fun(BMC_AFE11_OTThreshold);
		fun(BMC_AFE12_OTThreshold);
		fun(BMC_AFE13_OTThreshold);
		fun(BMC_AFE14_OTThreshold);
		fun(BMC_AFE15_OTThreshold);
		fun(BMC_AFE16_OTThreshold);
		fun(BMC_AFE17_OTThreshold);
		fun(BMC_AFE18_OTThreshold);
		fun(BMC_AFE19_OTThreshold);
		fun(BMC_AFE20_OTThreshold);
	}

	template<typename F>
	void GetSize(F& fun) const{
		fun(BMC_AFEWakeUpState);
		fun(BMC_ResetByAFESetErr);
		fun(BMC_NrResetByAFESetErr);
		fun(BMC_AFE1_WakeUpSrc);
		fun(BMC_AFE2_WakeUpSrc);
		fun(BMC_AFE3_WakeUpSrc);
		fun(BMC_AFE4_WakeUpSrc);
		fun(BMC_AFE5_WakeUpSrc);
		fun(BMC_AFE6_WakeUpSrc);
		fun(BMC_AFE7_WakeUpSrc);
		fun(BMC_AFE8_WakeUpSrc);
		fun(BMC_AFE9_WakeUpSrc);
		fun(BMC_AFE10_WakeUpSrc);
		fun(BMC_AFE11_WakeUpSrc);
		fun(BMC_AFE12_WakeUpSrc);
		fun(BMC_AFE13_WakeUpSrc);
		fun(BMC_AFE14_WakeUpSrc);
		fun(BMC_AFE15_WakeUpSrc);
		fun(BMC_AFE16_WakeUpSrc);
		fun(BMC_AFE17_WakeUpSrc);
		fun(BMC_AFE18_WakeUpSrc);
		fun(BMC_AFE19_WakeUpSrc);
		fun(BMC_AFE20_WakeUpSrc);
		fun(BMC_AFE1_OVWakeUp_Enable);
		fun(BMC_AFE2_OVWakeUp_Enable);
		fun(BMC_AFE3_OVWakeUp_Enable);
		fun(BMC_AFE4_OVWakeUp_Enable);
		fun(BMC_AFE5_OVWakeUp_Enable);
		fun(BMC_AFE6_OVWakeUp_Enable);
		fun(BMC_AFE7_OVWakeUp_Enable);
		fun(BMC_AFE8_OVWakeUp_Enable);
		fun(BMC_AFE9_OVWakeUp_Enable);
		fun(BMC_AFE10_OVWakeUp_Enable);
		fun(BMC_AFE11_OVWakeUp_Enable);
		fun(BMC_AFE12_OVWakeUp_Enable);
		fun(BMC_AFE13_OVWakeUp_Enable);
		fun(BMC_AFE14_OVWakeUp_Enable);
		fun(BMC_AFE15_OVWakeUp_Enable);
		fun(BMC_AFE16_OVWakeUp_Enable);
		fun(BMC_AFE17_OVWakeUp_Enable);
		fun(BMC_AFE18_OVWakeUp_Enable);
		fun(BMC_AFE19_OVWakeUp_Enable);
		fun(BMC_AFE20_OVWakeUp_Enable);
		fun(BMC_AFE1_UVWakeUp_Enable);
		fun(BMC_AFE2_UVWakeUp_Enable);
		fun(BMC_AFE3_UVWakeUp_Enable);
		fun(BMC_AFE4_UVWakeUp_Enable);
		fun(BMC_AFE5_UVWakeUp_Enable);
		fun(BMC_AFE6_UVWakeUp_Enable);
		fun(BMC_AFE7_UVWakeUp_Enable);
		fun(BMC_AFE8_UVWakeUp_Enable);
		fun(BMC_AFE9_UVWakeUp_Enable);
		fun(BMC_AFE10_UVWakeUp_Enable);
		fun(BMC_AFE11_UVWakeUp_Enable);
		fun(BMC_AFE12_UVWakeUp_Enable);
		fun(BMC_AFE13_UVWakeUp_Enable);
		fun(BMC_AFE14_UVWakeUp_Enable);
		fun(BMC_AFE15_UVWakeUp_Enable);
		fun(BMC_AFE16_UVWakeUp_Enable);
		fun(BMC_AFE17_UVWakeUp_Enable);
		fun(BMC_AFE18_UVWakeUp_Enable);
		fun(BMC_AFE19_UVWakeUp_Enable);
		fun(BMC_AFE20_UVWakeUp_Enable);
		fun(BMC_AFE1_OTWakeUp_Enable);
		fun(BMC_AFE2_OTWakeUp_Enable);
		fun(BMC_AFE3_OTWakeUp_Enable);
		fun(BMC_AFE4_OTWakeUp_Enable);
		fun(BMC_AFE5_OTWakeUp_Enable);
		fun(BMC_AFE6_OTWakeUp_Enable);
		fun(BMC_AFE7_OTWakeUp_Enable);
		fun(BMC_AFE8_OTWakeUp_Enable);
		fun(BMC_AFE9_OTWakeUp_Enable);
		fun(BMC_AFE10_OTWakeUp_Enable);
		fun(BMC_AFE11_OTWakeUp_Enable);
		fun(BMC_AFE12_OTWakeUp_Enable);
		fun(BMC_AFE13_OTWakeUp_Enable);
		fun(BMC_AFE14_OTWakeUp_Enable);
		fun(BMC_AFE15_OTWakeUp_Enable);
		fun(BMC_AFE16_OTWakeUp_Enable);
		fun(BMC_AFE17_OTWakeUp_Enable);
		fun(BMC_AFE18_OTWakeUp_Enable);
		fun(BMC_AFE19_OTWakeUp_Enable);
		fun(BMC_AFE20_OTWakeUp_Enable);
		fun(BMC_AFE1_OVThreshold);
		fun(BMC_AFE2_OVThreshold);
		fun(BMC_AFE3_OVThreshold);
		fun(BMC_AFE4_OVThreshold);
		fun(BMC_AFE5_OVThreshold);
		fun(BMC_AFE6_OVThreshold);
		fun(BMC_AFE7_OVThreshold);
		fun(BMC_AFE8_OVThreshold);
		fun(BMC_AFE9_OVThreshold);
		fun(BMC_AFE10_OVThreshold);
		fun(BMC_AFE11_OVThreshold);
		fun(BMC_AFE12_OVThreshold);
		fun(BMC_AFE13_OVThreshold);
		fun(BMC_AFE14_OVThreshold);
		fun(BMC_AFE15_OVThreshold);
		fun(BMC_AFE16_OVThreshold);
		fun(BMC_AFE17_OVThreshold);
		fun(BMC_AFE18_OVThreshold);
		fun(BMC_AFE19_OVThreshold);
		fun(BMC_AFE20_OVThreshold);
		fun(BMC_AFE1_UVThreshold);
		fun(BMC_AFE2_UVThreshold);
		fun(BMC_AFE3_UVThreshold);
		fun(BMC_AFE4_UVThreshold);
		fun(BMC_AFE5_UVThreshold);
		fun(BMC_AFE6_UVThreshold);
		fun(BMC_AFE7_UVThreshold);
		fun(BMC_AFE8_UVThreshold);
		fun(BMC_AFE9_UVThreshold);
		fun(BMC_AFE10_UVThreshold);
		fun(BMC_AFE11_UVThreshold);
		fun(BMC_AFE12_UVThreshold);
		fun(BMC_AFE13_UVThreshold);
		fun(BMC_AFE14_UVThreshold);
		fun(BMC_AFE15_UVThreshold);
		fun(BMC_AFE16_UVThreshold);
		fun(BMC_AFE17_UVThreshold);
		fun(BMC_AFE18_UVThreshold);
		fun(BMC_AFE19_UVThreshold);
		fun(BMC_AFE20_UVThreshold);
		fun(BMC_AFE1_OTThreshold);
		fun(BMC_AFE2_OTThreshold);
		fun(BMC_AFE3_OTThreshold);
		fun(BMC_AFE4_OTThreshold);
		fun(BMC_AFE5_OTThreshold);
		fun(BMC_AFE6_OTThreshold);
		fun(BMC_AFE7_OTThreshold);
		fun(BMC_AFE8_OTThreshold);
		fun(BMC_AFE9_OTThreshold);
		fun(BMC_AFE10_OTThreshold);
		fun(BMC_AFE11_OTThreshold);
		fun(BMC_AFE12_OTThreshold);
		fun(BMC_AFE13_OTThreshold);
		fun(BMC_AFE14_OTThreshold);
		fun(BMC_AFE15_OTThreshold);
		fun(BMC_AFE16_OTThreshold);
		fun(BMC_AFE17_OTThreshold);
		fun(BMC_AFE18_OTThreshold);
		fun(BMC_AFE19_OTThreshold);
		fun(BMC_AFE20_OTThreshold);
	}
	template<typename F>
	void serialize(F& fun) const{
		fun << (BMC_AFEWakeUpState);
		fun << (BMC_ResetByAFESetErr);
		fun << (BMC_NrResetByAFESetErr);
		fun << (BMC_AFE1_WakeUpSrc);
		fun << (BMC_AFE2_WakeUpSrc);
		fun << (BMC_AFE3_WakeUpSrc);
		fun << (BMC_AFE4_WakeUpSrc);
		fun << (BMC_AFE5_WakeUpSrc);
		fun << (BMC_AFE6_WakeUpSrc);
		fun << (BMC_AFE7_WakeUpSrc);
		fun << (BMC_AFE8_WakeUpSrc);
		fun << (BMC_AFE9_WakeUpSrc);
		fun << (BMC_AFE10_WakeUpSrc);
		fun << (BMC_AFE11_WakeUpSrc);
		fun << (BMC_AFE12_WakeUpSrc);
		fun << (BMC_AFE13_WakeUpSrc);
		fun << (BMC_AFE14_WakeUpSrc);
		fun << (BMC_AFE15_WakeUpSrc);
		fun << (BMC_AFE16_WakeUpSrc);
		fun << (BMC_AFE17_WakeUpSrc);
		fun << (BMC_AFE18_WakeUpSrc);
		fun << (BMC_AFE19_WakeUpSrc);
		fun << (BMC_AFE20_WakeUpSrc);
		fun << (BMC_AFE1_OVWakeUp_Enable);
		fun << (BMC_AFE2_OVWakeUp_Enable);
		fun << (BMC_AFE3_OVWakeUp_Enable);
		fun << (BMC_AFE4_OVWakeUp_Enable);
		fun << (BMC_AFE5_OVWakeUp_Enable);
		fun << (BMC_AFE6_OVWakeUp_Enable);
		fun << (BMC_AFE7_OVWakeUp_Enable);
		fun << (BMC_AFE8_OVWakeUp_Enable);
		fun << (BMC_AFE9_OVWakeUp_Enable);
		fun << (BMC_AFE10_OVWakeUp_Enable);
		fun << (BMC_AFE11_OVWakeUp_Enable);
		fun << (BMC_AFE12_OVWakeUp_Enable);
		fun << (BMC_AFE13_OVWakeUp_Enable);
		fun << (BMC_AFE14_OVWakeUp_Enable);
		fun << (BMC_AFE15_OVWakeUp_Enable);
		fun << (BMC_AFE16_OVWakeUp_Enable);
		fun << (BMC_AFE17_OVWakeUp_Enable);
		fun << (BMC_AFE18_OVWakeUp_Enable);
		fun << (BMC_AFE19_OVWakeUp_Enable);
		fun << (BMC_AFE20_OVWakeUp_Enable);
		fun << (BMC_AFE1_UVWakeUp_Enable);
		fun << (BMC_AFE2_UVWakeUp_Enable);
		fun << (BMC_AFE3_UVWakeUp_Enable);
		fun << (BMC_AFE4_UVWakeUp_Enable);
		fun << (BMC_AFE5_UVWakeUp_Enable);
		fun << (BMC_AFE6_UVWakeUp_Enable);
		fun << (BMC_AFE7_UVWakeUp_Enable);
		fun << (BMC_AFE8_UVWakeUp_Enable);
		fun << (BMC_AFE9_UVWakeUp_Enable);
		fun << (BMC_AFE10_UVWakeUp_Enable);
		fun << (BMC_AFE11_UVWakeUp_Enable);
		fun << (BMC_AFE12_UVWakeUp_Enable);
		fun << (BMC_AFE13_UVWakeUp_Enable);
		fun << (BMC_AFE14_UVWakeUp_Enable);
		fun << (BMC_AFE15_UVWakeUp_Enable);
		fun << (BMC_AFE16_UVWakeUp_Enable);
		fun << (BMC_AFE17_UVWakeUp_Enable);
		fun << (BMC_AFE18_UVWakeUp_Enable);
		fun << (BMC_AFE19_UVWakeUp_Enable);
		fun << (BMC_AFE20_UVWakeUp_Enable);
		fun << (BMC_AFE1_OTWakeUp_Enable);
		fun << (BMC_AFE2_OTWakeUp_Enable);
		fun << (BMC_AFE3_OTWakeUp_Enable);
		fun << (BMC_AFE4_OTWakeUp_Enable);
		fun << (BMC_AFE5_OTWakeUp_Enable);
		fun << (BMC_AFE6_OTWakeUp_Enable);
		fun << (BMC_AFE7_OTWakeUp_Enable);
		fun << (BMC_AFE8_OTWakeUp_Enable);
		fun << (BMC_AFE9_OTWakeUp_Enable);
		fun << (BMC_AFE10_OTWakeUp_Enable);
		fun << (BMC_AFE11_OTWakeUp_Enable);
		fun << (BMC_AFE12_OTWakeUp_Enable);
		fun << (BMC_AFE13_OTWakeUp_Enable);
		fun << (BMC_AFE14_OTWakeUp_Enable);
		fun << (BMC_AFE15_OTWakeUp_Enable);
		fun << (BMC_AFE16_OTWakeUp_Enable);
		fun << (BMC_AFE17_OTWakeUp_Enable);
		fun << (BMC_AFE18_OTWakeUp_Enable);
		fun << (BMC_AFE19_OTWakeUp_Enable);
		fun << (BMC_AFE20_OTWakeUp_Enable);
		fun << (BMC_AFE1_OVThreshold);
		fun << (BMC_AFE2_OVThreshold);
		fun << (BMC_AFE3_OVThreshold);
		fun << (BMC_AFE4_OVThreshold);
		fun << (BMC_AFE5_OVThreshold);
		fun << (BMC_AFE6_OVThreshold);
		fun << (BMC_AFE7_OVThreshold);
		fun << (BMC_AFE8_OVThreshold);
		fun << (BMC_AFE9_OVThreshold);
		fun << (BMC_AFE10_OVThreshold);
		fun << (BMC_AFE11_OVThreshold);
		fun << (BMC_AFE12_OVThreshold);
		fun << (BMC_AFE13_OVThreshold);
		fun << (BMC_AFE14_OVThreshold);
		fun << (BMC_AFE15_OVThreshold);
		fun << (BMC_AFE16_OVThreshold);
		fun << (BMC_AFE17_OVThreshold);
		fun << (BMC_AFE18_OVThreshold);
		fun << (BMC_AFE19_OVThreshold);
		fun << (BMC_AFE20_OVThreshold);
		fun << (BMC_AFE1_UVThreshold);
		fun << (BMC_AFE2_UVThreshold);
		fun << (BMC_AFE3_UVThreshold);
		fun << (BMC_AFE4_UVThreshold);
		fun << (BMC_AFE5_UVThreshold);
		fun << (BMC_AFE6_UVThreshold);
		fun << (BMC_AFE7_UVThreshold);
		fun << (BMC_AFE8_UVThreshold);
		fun << (BMC_AFE9_UVThreshold);
		fun << (BMC_AFE10_UVThreshold);
		fun << (BMC_AFE11_UVThreshold);
		fun << (BMC_AFE12_UVThreshold);
		fun << (BMC_AFE13_UVThreshold);
		fun << (BMC_AFE14_UVThreshold);
		fun << (BMC_AFE15_UVThreshold);
		fun << (BMC_AFE16_UVThreshold);
		fun << (BMC_AFE17_UVThreshold);
		fun << (BMC_AFE18_UVThreshold);
		fun << (BMC_AFE19_UVThreshold);
		fun << (BMC_AFE20_UVThreshold);
		fun << (BMC_AFE1_OTThreshold);
		fun << (BMC_AFE2_OTThreshold);
		fun << (BMC_AFE3_OTThreshold);
		fun << (BMC_AFE4_OTThreshold);
		fun << (BMC_AFE5_OTThreshold);
		fun << (BMC_AFE6_OTThreshold);
		fun << (BMC_AFE7_OTThreshold);
		fun << (BMC_AFE8_OTThreshold);
		fun << (BMC_AFE9_OTThreshold);
		fun << (BMC_AFE10_OTThreshold);
		fun << (BMC_AFE11_OTThreshold);
		fun << (BMC_AFE12_OTThreshold);
		fun << (BMC_AFE13_OTThreshold);
		fun << (BMC_AFE14_OTThreshold);
		fun << (BMC_AFE15_OTThreshold);
		fun << (BMC_AFE16_OTThreshold);
		fun << (BMC_AFE17_OTThreshold);
		fun << (BMC_AFE18_OTThreshold);
		fun << (BMC_AFE19_OTThreshold);
		fun << (BMC_AFE20_OTThreshold);
	}
	template<typename F>
	void deserialize(F& fun){
		fun >> (BMC_AFEWakeUpState);
		fun >> (BMC_ResetByAFESetErr);
		fun >> (BMC_NrResetByAFESetErr);
		fun >> (BMC_AFE1_WakeUpSrc);
		fun >> (BMC_AFE2_WakeUpSrc);
		fun >> (BMC_AFE3_WakeUpSrc);
		fun >> (BMC_AFE4_WakeUpSrc);
		fun >> (BMC_AFE5_WakeUpSrc);
		fun >> (BMC_AFE6_WakeUpSrc);
		fun >> (BMC_AFE7_WakeUpSrc);
		fun >> (BMC_AFE8_WakeUpSrc);
		fun >> (BMC_AFE9_WakeUpSrc);
		fun >> (BMC_AFE10_WakeUpSrc);
		fun >> (BMC_AFE11_WakeUpSrc);
		fun >> (BMC_AFE12_WakeUpSrc);
		fun >> (BMC_AFE13_WakeUpSrc);
		fun >> (BMC_AFE14_WakeUpSrc);
		fun >> (BMC_AFE15_WakeUpSrc);
		fun >> (BMC_AFE16_WakeUpSrc);
		fun >> (BMC_AFE17_WakeUpSrc);
		fun >> (BMC_AFE18_WakeUpSrc);
		fun >> (BMC_AFE19_WakeUpSrc);
		fun >> (BMC_AFE20_WakeUpSrc);
		fun >> (BMC_AFE1_OVWakeUp_Enable);
		fun >> (BMC_AFE2_OVWakeUp_Enable);
		fun >> (BMC_AFE3_OVWakeUp_Enable);
		fun >> (BMC_AFE4_OVWakeUp_Enable);
		fun >> (BMC_AFE5_OVWakeUp_Enable);
		fun >> (BMC_AFE6_OVWakeUp_Enable);
		fun >> (BMC_AFE7_OVWakeUp_Enable);
		fun >> (BMC_AFE8_OVWakeUp_Enable);
		fun >> (BMC_AFE9_OVWakeUp_Enable);
		fun >> (BMC_AFE10_OVWakeUp_Enable);
		fun >> (BMC_AFE11_OVWakeUp_Enable);
		fun >> (BMC_AFE12_OVWakeUp_Enable);
		fun >> (BMC_AFE13_OVWakeUp_Enable);
		fun >> (BMC_AFE14_OVWakeUp_Enable);
		fun >> (BMC_AFE15_OVWakeUp_Enable);
		fun >> (BMC_AFE16_OVWakeUp_Enable);
		fun >> (BMC_AFE17_OVWakeUp_Enable);
		fun >> (BMC_AFE18_OVWakeUp_Enable);
		fun >> (BMC_AFE19_OVWakeUp_Enable);
		fun >> (BMC_AFE20_OVWakeUp_Enable);
		fun >> (BMC_AFE1_UVWakeUp_Enable);
		fun >> (BMC_AFE2_UVWakeUp_Enable);
		fun >> (BMC_AFE3_UVWakeUp_Enable);
		fun >> (BMC_AFE4_UVWakeUp_Enable);
		fun >> (BMC_AFE5_UVWakeUp_Enable);
		fun >> (BMC_AFE6_UVWakeUp_Enable);
		fun >> (BMC_AFE7_UVWakeUp_Enable);
		fun >> (BMC_AFE8_UVWakeUp_Enable);
		fun >> (BMC_AFE9_UVWakeUp_Enable);
		fun >> (BMC_AFE10_UVWakeUp_Enable);
		fun >> (BMC_AFE11_UVWakeUp_Enable);
		fun >> (BMC_AFE12_UVWakeUp_Enable);
		fun >> (BMC_AFE13_UVWakeUp_Enable);
		fun >> (BMC_AFE14_UVWakeUp_Enable);
		fun >> (BMC_AFE15_UVWakeUp_Enable);
		fun >> (BMC_AFE16_UVWakeUp_Enable);
		fun >> (BMC_AFE17_UVWakeUp_Enable);
		fun >> (BMC_AFE18_UVWakeUp_Enable);
		fun >> (BMC_AFE19_UVWakeUp_Enable);
		fun >> (BMC_AFE20_UVWakeUp_Enable);
		fun >> (BMC_AFE1_OTWakeUp_Enable);
		fun >> (BMC_AFE2_OTWakeUp_Enable);
		fun >> (BMC_AFE3_OTWakeUp_Enable);
		fun >> (BMC_AFE4_OTWakeUp_Enable);
		fun >> (BMC_AFE5_OTWakeUp_Enable);
		fun >> (BMC_AFE6_OTWakeUp_Enable);
		fun >> (BMC_AFE7_OTWakeUp_Enable);
		fun >> (BMC_AFE8_OTWakeUp_Enable);
		fun >> (BMC_AFE9_OTWakeUp_Enable);
		fun >> (BMC_AFE10_OTWakeUp_Enable);
		fun >> (BMC_AFE11_OTWakeUp_Enable);
		fun >> (BMC_AFE12_OTWakeUp_Enable);
		fun >> (BMC_AFE13_OTWakeUp_Enable);
		fun >> (BMC_AFE14_OTWakeUp_Enable);
		fun >> (BMC_AFE15_OTWakeUp_Enable);
		fun >> (BMC_AFE16_OTWakeUp_Enable);
		fun >> (BMC_AFE17_OTWakeUp_Enable);
		fun >> (BMC_AFE18_OTWakeUp_Enable);
		fun >> (BMC_AFE19_OTWakeUp_Enable);
		fun >> (BMC_AFE20_OTWakeUp_Enable);
		fun >> (BMC_AFE1_OVThreshold);
		fun >> (BMC_AFE2_OVThreshold);
		fun >> (BMC_AFE3_OVThreshold);
		fun >> (BMC_AFE4_OVThreshold);
		fun >> (BMC_AFE5_OVThreshold);
		fun >> (BMC_AFE6_OVThreshold);
		fun >> (BMC_AFE7_OVThreshold);
		fun >> (BMC_AFE8_OVThreshold);
		fun >> (BMC_AFE9_OVThreshold);
		fun >> (BMC_AFE10_OVThreshold);
		fun >> (BMC_AFE11_OVThreshold);
		fun >> (BMC_AFE12_OVThreshold);
		fun >> (BMC_AFE13_OVThreshold);
		fun >> (BMC_AFE14_OVThreshold);
		fun >> (BMC_AFE15_OVThreshold);
		fun >> (BMC_AFE16_OVThreshold);
		fun >> (BMC_AFE17_OVThreshold);
		fun >> (BMC_AFE18_OVThreshold);
		fun >> (BMC_AFE19_OVThreshold);
		fun >> (BMC_AFE20_OVThreshold);
		fun >> (BMC_AFE1_UVThreshold);
		fun >> (BMC_AFE2_UVThreshold);
		fun >> (BMC_AFE3_UVThreshold);
		fun >> (BMC_AFE4_UVThreshold);
		fun >> (BMC_AFE5_UVThreshold);
		fun >> (BMC_AFE6_UVThreshold);
		fun >> (BMC_AFE7_UVThreshold);
		fun >> (BMC_AFE8_UVThreshold);
		fun >> (BMC_AFE9_UVThreshold);
		fun >> (BMC_AFE10_UVThreshold);
		fun >> (BMC_AFE11_UVThreshold);
		fun >> (BMC_AFE12_UVThreshold);
		fun >> (BMC_AFE13_UVThreshold);
		fun >> (BMC_AFE14_UVThreshold);
		fun >> (BMC_AFE15_UVThreshold);
		fun >> (BMC_AFE16_UVThreshold);
		fun >> (BMC_AFE17_UVThreshold);
		fun >> (BMC_AFE18_UVThreshold);
		fun >> (BMC_AFE19_UVThreshold);
		fun >> (BMC_AFE20_UVThreshold);
		fun >> (BMC_AFE1_OTThreshold);
		fun >> (BMC_AFE2_OTThreshold);
		fun >> (BMC_AFE3_OTThreshold);
		fun >> (BMC_AFE4_OTThreshold);
		fun >> (BMC_AFE5_OTThreshold);
		fun >> (BMC_AFE6_OTThreshold);
		fun >> (BMC_AFE7_OTThreshold);
		fun >> (BMC_AFE8_OTThreshold);
		fun >> (BMC_AFE9_OTThreshold);
		fun >> (BMC_AFE10_OTThreshold);
		fun >> (BMC_AFE11_OTThreshold);
		fun >> (BMC_AFE12_OTThreshold);
		fun >> (BMC_AFE13_OTThreshold);
		fun >> (BMC_AFE14_OTThreshold);
		fun >> (BMC_AFE15_OTThreshold);
		fun >> (BMC_AFE16_OTThreshold);
		fun >> (BMC_AFE17_OTThreshold);
		fun >> (BMC_AFE18_OTThreshold);
		fun >> (BMC_AFE19_OTThreshold);
		fun >> (BMC_AFE20_OTThreshold);
	}
};

#endif //____BDCBMCAFE_H__
