#ifndef ____BDCIPDS3_H__
#define ____BDCIPDS3_H__


#include "cstdint"






struct BDCIPDS3 {
public:
	std::uint8_t IPDS_AMPPowerFaultSt;
	std::uint8_t IPDS_RearEOPPowerFaultSt;
	std::uint8_t IPDS_RearRadarPowerFaultSt;
	std::uint8_t IPDS_RLALampCtlUnitPowerFaultSt;
	std::uint8_t IPDS_RRALampCtlUnitPowerFaultSt;
	std::uint8_t IPDS_RLBLampCtlUnitPowerFaultSt;
	std::uint8_t IPDS_RRBLampCtlUnitPowerFaultSt;
	std::uint8_t IPDS_EXVPowerFaultSt;
	std::uint8_t IPDS_PASPowerFaultSt;
	std::uint8_t IPDS_GSMPowerFaultSt;
	std::uint8_t IPDS_DSMPowerFaultSt;
	std::uint8_t IPDS_KL15T2PowerFaultSt;
	std::uint8_t IPDS_KL15T1PowerFaultSt;
	std::uint8_t IPDS_KL15F1PowerFaultSt;
	std::uint8_t IPDS_IPSPowerFaultSt;
	std::uint8_t IPDS_BMSPowerFaultSt;
	std::uint8_t IPDS_OBDPowerFaultSt;
	std::uint8_t IPDS_RLSPowerFaultSt;
	std::uint8_t IPDS_DVRPowerFaultSt;
	std::uint8_t IPDS_ADCMain1PowerFaultSt;
	std::uint8_t IPDS_ADCMain2PowerFaultSt;
	std::uint8_t IPDS_BrakeSwNormalOpenPowerFaultSt;
	std::uint8_t IPDS_SAMPowerFaultSt;
	std::uint8_t IPDS_TBoxPowerFaultSt;
	std::uint8_t IPDS_FrontIDCPowerFaultSt;
	std::uint8_t IPDS_RearDCDCPowerFaultSt;
	std::uint8_t IPDS_ADCBackup1PowerFaultSt;
	std::uint8_t IPDS_ADCBackup2PowerFaultSt;
	std::uint8_t IPDS_FLLampCtlUnitPowerSt;
	std::uint8_t IPDS_FRLampCtlUnitPowerSt;
	std::uint8_t IPDS_HVHPowerSt;
	std::uint8_t IPDS_IPUEOP1PowerSt;
	std::uint8_t IPDS_IPUEOP2PowerSt;
	std::uint8_t IPDS_IPUPowerSt;
	std::uint8_t IPDS_FrontRadarPowerSt;
	std::uint8_t IPDS_FLRadarPowerSt;
	std::uint8_t IPDS_FRRadarPowerSt;
	std::uint8_t IPDS_AGSPowerSt;
	std::uint8_t IPDS_ECPPowerSt;
	std::uint8_t IPDS_AVASPowerSt;
	std::uint8_t IPDS_BrakeSwNormalClosePowerSt;
	std::uint8_t IPDS_AQSPowerSt;
	std::uint8_t IPDS_DriverLumbarMotorPowerSt;
	std::uint8_t IPDS_RoofDevicePowerSt;
	std::uint8_t IPDS_ETCPowerSt;
	std::uint8_t IPDS_ClusterDisplayPowerSt;
	std::uint8_t IPDS_PassDisplayPowerSt;
	std::uint8_t IPDS_IDCDisplayPowerSt;
	std::uint8_t IPDS_CigarLigterPowerSt;
	std::uint8_t IPDS_HDMapPowerSt;
	std::uint8_t IPDS_Lidar1PowerSt;
	std::uint8_t IPDS_Lidar2PowerSt;
	std::uint8_t IPDS_Lidar3PowerSt;
	std::uint8_t IPDS_HODPowerSt;
	std::uint8_t IPDS_ESCLPowerSt;
	std::uint8_t IPDS_ISRVMPowerSt;
	std::uint8_t IPDS_SRSECUPowerSt;
	std::uint8_t IPDS_KL15L1PowerSt;
	std::uint8_t IPDS_KL15L2PowerSt;
	std::uint8_t IPDS_HUDPowerSt;
	std::uint8_t IPDS_ClusterPowerSt;
	std::uint8_t IPDS_WCMPowerSt;
	std::uint8_t IPDS_FrontUSBChargerPowerSt;
	std::uint8_t IPDS_PM25PowerSt;
	std::uint8_t IPDS_PassLumbarMotorPowerSt;
	std::uint8_t IPDS_FrontBlowerPowerSt;
	std::uint8_t IPDS_UWBSensorPowerSt;
	std::uint8_t IPDS_KL15R1PowerSt;
	std::uint8_t IPDS_KL15R2PowerSt;
	std::uint8_t IPDS_RMPowerSt;
	std::uint8_t IPDS_RearCtrlPanelPowerSt;
	std::uint8_t IPDS_Rear12VPowerSt;
	std::uint8_t IPDS_InverterPowerSt;
	std::uint8_t IPDS_RearMotorPowerSt;
	std::uint8_t IPDS_AMPPowerSt;
	std::uint8_t IPDS_RearEOPPowerSt;
	std::uint8_t IPDS_RearRadarPowerSt;
	std::uint8_t IPDS_RLALampCtlUnitPowerSt;
	std::uint8_t IPDS_RRALampCtlUnitPowerSt;
	std::uint8_t IPDS_RLBLampCtlUnitPowerSt;
	std::uint8_t IPDS_RRBLampCtlUnitPowerSt;
	std::uint8_t IPDS_EXVPowerSt;
	std::uint8_t IPDS_PASPowerSt;
	std::uint8_t IPDS_GSMPowerSt;
	std::uint8_t IPDS_DSMPowerSt;
	std::uint8_t IPDS_KL15T2PowerSt;
	std::uint8_t IPDS_KL15T1PowerSt;
	std::uint8_t IPDS_KL15F1PowerSt;
	std::uint8_t IPDS_IPSPowerSt;
	std::uint8_t IPDS_BMSPowerSt;
	std::uint8_t IPDS_OBDPowerSt;
	std::uint8_t IPDS_RLSPowerSt;
	std::uint8_t IPDS_DVRPowerSt;
	std::uint8_t IPDS_ADCMain1PowerSt;
	std::uint8_t IPDS_ADCMain2PowerSt;
	std::uint8_t IPDS_BrakeNormalOpenSwPowerSt;
	std::uint8_t IPDS_SAMPowerSt;
	std::uint8_t IPDS_TBoxPowerSt;
	std::uint8_t IPDS_FrontIDCPowerSt;
	std::uint8_t IPDS_RearDCDCPowerSt;
	std::uint8_t IPDS_ADCBackup1PowerSt;
	std::uint8_t IPDS_ADCBackup2PowerSt;
/*
	BDCIPDS3() {}
	~BDCIPDS3() {}
	BDCIPDS3(const std::uint8_t _IPDS_AMPPowerFaultSt,const std::uint8_t _IPDS_RearEOPPowerFaultSt,const std::uint8_t _IPDS_RearRadarPowerFaultSt,const std::uint8_t _IPDS_RLALampCtlUnitPowerFaultSt,const std::uint8_t _IPDS_RRALampCtlUnitPowerFaultSt,const std::uint8_t _IPDS_RLBLampCtlUnitPowerFaultSt,const std::uint8_t _IPDS_RRBLampCtlUnitPowerFaultSt,const std::uint8_t _IPDS_EXVPowerFaultSt,const std::uint8_t _IPDS_PASPowerFaultSt,const std::uint8_t _IPDS_GSMPowerFaultSt,const std::uint8_t _IPDS_DSMPowerFaultSt,const std::uint8_t _IPDS_KL15T2PowerFaultSt,const std::uint8_t _IPDS_KL15T1PowerFaultSt,const std::uint8_t _IPDS_KL15F1PowerFaultSt,const std::uint8_t _IPDS_IPSPowerFaultSt,const std::uint8_t _IPDS_BMSPowerFaultSt,const std::uint8_t _IPDS_OBDPowerFaultSt,const std::uint8_t _IPDS_RLSPowerFaultSt,const std::uint8_t _IPDS_DVRPowerFaultSt,const std::uint8_t _IPDS_ADCMain1PowerFaultSt,const std::uint8_t _IPDS_ADCMain2PowerFaultSt,const std::uint8_t _IPDS_BrakeSwNormalOpenPowerFaultSt,const std::uint8_t _IPDS_SAMPowerFaultSt,const std::uint8_t _IPDS_TBoxPowerFaultSt,const std::uint8_t _IPDS_FrontIDCPowerFaultSt,const std::uint8_t _IPDS_RearDCDCPowerFaultSt,const std::uint8_t _IPDS_ADCBackup1PowerFaultSt,const std::uint8_t _IPDS_ADCBackup2PowerFaultSt,const std::uint8_t _IPDS_FLLampCtlUnitPowerSt,const std::uint8_t _IPDS_FRLampCtlUnitPowerSt,const std::uint8_t _IPDS_HVHPowerSt,const std::uint8_t _IPDS_IPUEOP1PowerSt,const std::uint8_t _IPDS_IPUEOP2PowerSt,const std::uint8_t _IPDS_IPUPowerSt,const std::uint8_t _IPDS_FrontRadarPowerSt,const std::uint8_t _IPDS_FLRadarPowerSt,const std::uint8_t _IPDS_FRRadarPowerSt,const std::uint8_t _IPDS_AGSPowerSt,const std::uint8_t _IPDS_ECPPowerSt,const std::uint8_t _IPDS_AVASPowerSt,const std::uint8_t _IPDS_BrakeSwNormalClosePowerSt,const std::uint8_t _IPDS_AQSPowerSt,const std::uint8_t _IPDS_DriverLumbarMotorPowerSt,const std::uint8_t _IPDS_RoofDevicePowerSt,const std::uint8_t _IPDS_ETCPowerSt,const std::uint8_t _IPDS_ClusterDisplayPowerSt,const std::uint8_t _IPDS_PassDisplayPowerSt,const std::uint8_t _IPDS_IDCDisplayPowerSt,const std::uint8_t _IPDS_CigarLigterPowerSt,const std::uint8_t _IPDS_HDMapPowerSt,const std::uint8_t _IPDS_Lidar1PowerSt,const std::uint8_t _IPDS_Lidar2PowerSt,const std::uint8_t _IPDS_Lidar3PowerSt,const std::uint8_t _IPDS_HODPowerSt,const std::uint8_t _IPDS_ESCLPowerSt,const std::uint8_t _IPDS_ISRVMPowerSt,const std::uint8_t _IPDS_SRSECUPowerSt,const std::uint8_t _IPDS_KL15L1PowerSt,const std::uint8_t _IPDS_KL15L2PowerSt,const std::uint8_t _IPDS_HUDPowerSt,const std::uint8_t _IPDS_ClusterPowerSt,const std::uint8_t _IPDS_WCMPowerSt,const std::uint8_t _IPDS_FrontUSBChargerPowerSt,const std::uint8_t _IPDS_PM25PowerSt,const std::uint8_t _IPDS_PassLumbarMotorPowerSt,const std::uint8_t _IPDS_FrontBlowerPowerSt,const std::uint8_t _IPDS_UWBSensorPowerSt,const std::uint8_t _IPDS_KL15R1PowerSt,const std::uint8_t _IPDS_KL15R2PowerSt,const std::uint8_t _IPDS_RMPowerSt,const std::uint8_t _IPDS_RearCtrlPanelPowerSt,const std::uint8_t _IPDS_Rear12VPowerSt,const std::uint8_t _IPDS_InverterPowerSt,const std::uint8_t _IPDS_RearMotorPowerSt,const std::uint8_t _IPDS_AMPPowerSt,const std::uint8_t _IPDS_RearEOPPowerSt,const std::uint8_t _IPDS_RearRadarPowerSt,const std::uint8_t _IPDS_RLALampCtlUnitPowerSt,const std::uint8_t _IPDS_RRALampCtlUnitPowerSt,const std::uint8_t _IPDS_RLBLampCtlUnitPowerSt,const std::uint8_t _IPDS_RRBLampCtlUnitPowerSt,const std::uint8_t _IPDS_EXVPowerSt,const std::uint8_t _IPDS_PASPowerSt,const std::uint8_t _IPDS_GSMPowerSt,const std::uint8_t _IPDS_DSMPowerSt,const std::uint8_t _IPDS_KL15T2PowerSt,const std::uint8_t _IPDS_KL15T1PowerSt,const std::uint8_t _IPDS_KL15F1PowerSt,const std::uint8_t _IPDS_IPSPowerSt,const std::uint8_t _IPDS_BMSPowerSt,const std::uint8_t _IPDS_OBDPowerSt,const std::uint8_t _IPDS_RLSPowerSt,const std::uint8_t _IPDS_DVRPowerSt,const std::uint8_t _IPDS_ADCMain1PowerSt,const std::uint8_t _IPDS_ADCMain2PowerSt,const std::uint8_t _IPDS_BrakeNormalOpenSwPowerSt,const std::uint8_t _IPDS_SAMPowerSt,const std::uint8_t _IPDS_TBoxPowerSt,const std::uint8_t _IPDS_FrontIDCPowerSt,const std::uint8_t _IPDS_RearDCDCPowerSt,const std::uint8_t _IPDS_ADCBackup1PowerSt,const std::uint8_t _IPDS_ADCBackup2PowerSt):IPDS_AMPPowerFaultSt(_IPDS_AMPPowerFaultSt),IPDS_RearEOPPowerFaultSt(_IPDS_RearEOPPowerFaultSt),IPDS_RearRadarPowerFaultSt(_IPDS_RearRadarPowerFaultSt),IPDS_RLALampCtlUnitPowerFaultSt(_IPDS_RLALampCtlUnitPowerFaultSt),IPDS_RRALampCtlUnitPowerFaultSt(_IPDS_RRALampCtlUnitPowerFaultSt),IPDS_RLBLampCtlUnitPowerFaultSt(_IPDS_RLBLampCtlUnitPowerFaultSt),IPDS_RRBLampCtlUnitPowerFaultSt(_IPDS_RRBLampCtlUnitPowerFaultSt),IPDS_EXVPowerFaultSt(_IPDS_EXVPowerFaultSt),IPDS_PASPowerFaultSt(_IPDS_PASPowerFaultSt),IPDS_GSMPowerFaultSt(_IPDS_GSMPowerFaultSt),IPDS_DSMPowerFaultSt(_IPDS_DSMPowerFaultSt),IPDS_KL15T2PowerFaultSt(_IPDS_KL15T2PowerFaultSt),IPDS_KL15T1PowerFaultSt(_IPDS_KL15T1PowerFaultSt),IPDS_KL15F1PowerFaultSt(_IPDS_KL15F1PowerFaultSt),IPDS_IPSPowerFaultSt(_IPDS_IPSPowerFaultSt),IPDS_BMSPowerFaultSt(_IPDS_BMSPowerFaultSt),IPDS_OBDPowerFaultSt(_IPDS_OBDPowerFaultSt),IPDS_RLSPowerFaultSt(_IPDS_RLSPowerFaultSt),IPDS_DVRPowerFaultSt(_IPDS_DVRPowerFaultSt),IPDS_ADCMain1PowerFaultSt(_IPDS_ADCMain1PowerFaultSt),IPDS_ADCMain2PowerFaultSt(_IPDS_ADCMain2PowerFaultSt),IPDS_BrakeSwNormalOpenPowerFaultSt(_IPDS_BrakeSwNormalOpenPowerFaultSt),IPDS_SAMPowerFaultSt(_IPDS_SAMPowerFaultSt),IPDS_TBoxPowerFaultSt(_IPDS_TBoxPowerFaultSt),IPDS_FrontIDCPowerFaultSt(_IPDS_FrontIDCPowerFaultSt),IPDS_RearDCDCPowerFaultSt(_IPDS_RearDCDCPowerFaultSt),IPDS_ADCBackup1PowerFaultSt(_IPDS_ADCBackup1PowerFaultSt),IPDS_ADCBackup2PowerFaultSt(_IPDS_ADCBackup2PowerFaultSt),IPDS_FLLampCtlUnitPowerSt(_IPDS_FLLampCtlUnitPowerSt),IPDS_FRLampCtlUnitPowerSt(_IPDS_FRLampCtlUnitPowerSt),IPDS_HVHPowerSt(_IPDS_HVHPowerSt),IPDS_IPUEOP1PowerSt(_IPDS_IPUEOP1PowerSt),IPDS_IPUEOP2PowerSt(_IPDS_IPUEOP2PowerSt),IPDS_IPUPowerSt(_IPDS_IPUPowerSt),IPDS_FrontRadarPowerSt(_IPDS_FrontRadarPowerSt),IPDS_FLRadarPowerSt(_IPDS_FLRadarPowerSt),IPDS_FRRadarPowerSt(_IPDS_FRRadarPowerSt),IPDS_AGSPowerSt(_IPDS_AGSPowerSt),IPDS_ECPPowerSt(_IPDS_ECPPowerSt),IPDS_AVASPowerSt(_IPDS_AVASPowerSt),IPDS_BrakeSwNormalClosePowerSt(_IPDS_BrakeSwNormalClosePowerSt),IPDS_AQSPowerSt(_IPDS_AQSPowerSt),IPDS_DriverLumbarMotorPowerSt(_IPDS_DriverLumbarMotorPowerSt),IPDS_RoofDevicePowerSt(_IPDS_RoofDevicePowerSt),IPDS_ETCPowerSt(_IPDS_ETCPowerSt),IPDS_ClusterDisplayPowerSt(_IPDS_ClusterDisplayPowerSt),IPDS_PassDisplayPowerSt(_IPDS_PassDisplayPowerSt),IPDS_IDCDisplayPowerSt(_IPDS_IDCDisplayPowerSt),IPDS_CigarLigterPowerSt(_IPDS_CigarLigterPowerSt),IPDS_HDMapPowerSt(_IPDS_HDMapPowerSt),IPDS_Lidar1PowerSt(_IPDS_Lidar1PowerSt),IPDS_Lidar2PowerSt(_IPDS_Lidar2PowerSt),IPDS_Lidar3PowerSt(_IPDS_Lidar3PowerSt),IPDS_HODPowerSt(_IPDS_HODPowerSt),IPDS_ESCLPowerSt(_IPDS_ESCLPowerSt),IPDS_ISRVMPowerSt(_IPDS_ISRVMPowerSt),IPDS_SRSECUPowerSt(_IPDS_SRSECUPowerSt),IPDS_KL15L1PowerSt(_IPDS_KL15L1PowerSt),IPDS_KL15L2PowerSt(_IPDS_KL15L2PowerSt),IPDS_HUDPowerSt(_IPDS_HUDPowerSt),IPDS_ClusterPowerSt(_IPDS_ClusterPowerSt),IPDS_WCMPowerSt(_IPDS_WCMPowerSt),IPDS_FrontUSBChargerPowerSt(_IPDS_FrontUSBChargerPowerSt),IPDS_PM25PowerSt(_IPDS_PM25PowerSt),IPDS_PassLumbarMotorPowerSt(_IPDS_PassLumbarMotorPowerSt),IPDS_FrontBlowerPowerSt(_IPDS_FrontBlowerPowerSt),IPDS_UWBSensorPowerSt(_IPDS_UWBSensorPowerSt),IPDS_KL15R1PowerSt(_IPDS_KL15R1PowerSt),IPDS_KL15R2PowerSt(_IPDS_KL15R2PowerSt),IPDS_RMPowerSt(_IPDS_RMPowerSt),IPDS_RearCtrlPanelPowerSt(_IPDS_RearCtrlPanelPowerSt),IPDS_Rear12VPowerSt(_IPDS_Rear12VPowerSt),IPDS_InverterPowerSt(_IPDS_InverterPowerSt),IPDS_RearMotorPowerSt(_IPDS_RearMotorPowerSt),IPDS_AMPPowerSt(_IPDS_AMPPowerSt),IPDS_RearEOPPowerSt(_IPDS_RearEOPPowerSt),IPDS_RearRadarPowerSt(_IPDS_RearRadarPowerSt),IPDS_RLALampCtlUnitPowerSt(_IPDS_RLALampCtlUnitPowerSt),IPDS_RRALampCtlUnitPowerSt(_IPDS_RRALampCtlUnitPowerSt),IPDS_RLBLampCtlUnitPowerSt(_IPDS_RLBLampCtlUnitPowerSt),IPDS_RRBLampCtlUnitPowerSt(_IPDS_RRBLampCtlUnitPowerSt),IPDS_EXVPowerSt(_IPDS_EXVPowerSt),IPDS_PASPowerSt(_IPDS_PASPowerSt),IPDS_GSMPowerSt(_IPDS_GSMPowerSt),IPDS_DSMPowerSt(_IPDS_DSMPowerSt),IPDS_KL15T2PowerSt(_IPDS_KL15T2PowerSt),IPDS_KL15T1PowerSt(_IPDS_KL15T1PowerSt),IPDS_KL15F1PowerSt(_IPDS_KL15F1PowerSt),IPDS_IPSPowerSt(_IPDS_IPSPowerSt),IPDS_BMSPowerSt(_IPDS_BMSPowerSt),IPDS_OBDPowerSt(_IPDS_OBDPowerSt),IPDS_RLSPowerSt(_IPDS_RLSPowerSt),IPDS_DVRPowerSt(_IPDS_DVRPowerSt),IPDS_ADCMain1PowerSt(_IPDS_ADCMain1PowerSt),IPDS_ADCMain2PowerSt(_IPDS_ADCMain2PowerSt),IPDS_BrakeNormalOpenSwPowerSt(_IPDS_BrakeNormalOpenSwPowerSt),IPDS_SAMPowerSt(_IPDS_SAMPowerSt),IPDS_TBoxPowerSt(_IPDS_TBoxPowerSt),IPDS_FrontIDCPowerSt(_IPDS_FrontIDCPowerSt),IPDS_RearDCDCPowerSt(_IPDS_RearDCDCPowerSt),IPDS_ADCBackup1PowerSt(_IPDS_ADCBackup1PowerSt),IPDS_ADCBackup2PowerSt(_IPDS_ADCBackup2PowerSt) {}
	BDCIPDS3(const BDCIPDS3 &_x){
		IPDS_AMPPowerFaultSt = _x.IPDS_AMPPowerFaultSt;
		IPDS_RearEOPPowerFaultSt = _x.IPDS_RearEOPPowerFaultSt;
		IPDS_RearRadarPowerFaultSt = _x.IPDS_RearRadarPowerFaultSt;
		IPDS_RLALampCtlUnitPowerFaultSt = _x.IPDS_RLALampCtlUnitPowerFaultSt;
		IPDS_RRALampCtlUnitPowerFaultSt = _x.IPDS_RRALampCtlUnitPowerFaultSt;
		IPDS_RLBLampCtlUnitPowerFaultSt = _x.IPDS_RLBLampCtlUnitPowerFaultSt;
		IPDS_RRBLampCtlUnitPowerFaultSt = _x.IPDS_RRBLampCtlUnitPowerFaultSt;
		IPDS_EXVPowerFaultSt = _x.IPDS_EXVPowerFaultSt;
		IPDS_PASPowerFaultSt = _x.IPDS_PASPowerFaultSt;
		IPDS_GSMPowerFaultSt = _x.IPDS_GSMPowerFaultSt;
		IPDS_DSMPowerFaultSt = _x.IPDS_DSMPowerFaultSt;
		IPDS_KL15T2PowerFaultSt = _x.IPDS_KL15T2PowerFaultSt;
		IPDS_KL15T1PowerFaultSt = _x.IPDS_KL15T1PowerFaultSt;
		IPDS_KL15F1PowerFaultSt = _x.IPDS_KL15F1PowerFaultSt;
		IPDS_IPSPowerFaultSt = _x.IPDS_IPSPowerFaultSt;
		IPDS_BMSPowerFaultSt = _x.IPDS_BMSPowerFaultSt;
		IPDS_OBDPowerFaultSt = _x.IPDS_OBDPowerFaultSt;
		IPDS_RLSPowerFaultSt = _x.IPDS_RLSPowerFaultSt;
		IPDS_DVRPowerFaultSt = _x.IPDS_DVRPowerFaultSt;
		IPDS_ADCMain1PowerFaultSt = _x.IPDS_ADCMain1PowerFaultSt;
		IPDS_ADCMain2PowerFaultSt = _x.IPDS_ADCMain2PowerFaultSt;
		IPDS_BrakeSwNormalOpenPowerFaultSt = _x.IPDS_BrakeSwNormalOpenPowerFaultSt;
		IPDS_SAMPowerFaultSt = _x.IPDS_SAMPowerFaultSt;
		IPDS_TBoxPowerFaultSt = _x.IPDS_TBoxPowerFaultSt;
		IPDS_FrontIDCPowerFaultSt = _x.IPDS_FrontIDCPowerFaultSt;
		IPDS_RearDCDCPowerFaultSt = _x.IPDS_RearDCDCPowerFaultSt;
		IPDS_ADCBackup1PowerFaultSt = _x.IPDS_ADCBackup1PowerFaultSt;
		IPDS_ADCBackup2PowerFaultSt = _x.IPDS_ADCBackup2PowerFaultSt;
		IPDS_FLLampCtlUnitPowerSt = _x.IPDS_FLLampCtlUnitPowerSt;
		IPDS_FRLampCtlUnitPowerSt = _x.IPDS_FRLampCtlUnitPowerSt;
		IPDS_HVHPowerSt = _x.IPDS_HVHPowerSt;
		IPDS_IPUEOP1PowerSt = _x.IPDS_IPUEOP1PowerSt;
		IPDS_IPUEOP2PowerSt = _x.IPDS_IPUEOP2PowerSt;
		IPDS_IPUPowerSt = _x.IPDS_IPUPowerSt;
		IPDS_FrontRadarPowerSt = _x.IPDS_FrontRadarPowerSt;
		IPDS_FLRadarPowerSt = _x.IPDS_FLRadarPowerSt;
		IPDS_FRRadarPowerSt = _x.IPDS_FRRadarPowerSt;
		IPDS_AGSPowerSt = _x.IPDS_AGSPowerSt;
		IPDS_ECPPowerSt = _x.IPDS_ECPPowerSt;
		IPDS_AVASPowerSt = _x.IPDS_AVASPowerSt;
		IPDS_BrakeSwNormalClosePowerSt = _x.IPDS_BrakeSwNormalClosePowerSt;
		IPDS_AQSPowerSt = _x.IPDS_AQSPowerSt;
		IPDS_DriverLumbarMotorPowerSt = _x.IPDS_DriverLumbarMotorPowerSt;
		IPDS_RoofDevicePowerSt = _x.IPDS_RoofDevicePowerSt;
		IPDS_ETCPowerSt = _x.IPDS_ETCPowerSt;
		IPDS_ClusterDisplayPowerSt = _x.IPDS_ClusterDisplayPowerSt;
		IPDS_PassDisplayPowerSt = _x.IPDS_PassDisplayPowerSt;
		IPDS_IDCDisplayPowerSt = _x.IPDS_IDCDisplayPowerSt;
		IPDS_CigarLigterPowerSt = _x.IPDS_CigarLigterPowerSt;
		IPDS_HDMapPowerSt = _x.IPDS_HDMapPowerSt;
		IPDS_Lidar1PowerSt = _x.IPDS_Lidar1PowerSt;
		IPDS_Lidar2PowerSt = _x.IPDS_Lidar2PowerSt;
		IPDS_Lidar3PowerSt = _x.IPDS_Lidar3PowerSt;
		IPDS_HODPowerSt = _x.IPDS_HODPowerSt;
		IPDS_ESCLPowerSt = _x.IPDS_ESCLPowerSt;
		IPDS_ISRVMPowerSt = _x.IPDS_ISRVMPowerSt;
		IPDS_SRSECUPowerSt = _x.IPDS_SRSECUPowerSt;
		IPDS_KL15L1PowerSt = _x.IPDS_KL15L1PowerSt;
		IPDS_KL15L2PowerSt = _x.IPDS_KL15L2PowerSt;
		IPDS_HUDPowerSt = _x.IPDS_HUDPowerSt;
		IPDS_ClusterPowerSt = _x.IPDS_ClusterPowerSt;
		IPDS_WCMPowerSt = _x.IPDS_WCMPowerSt;
		IPDS_FrontUSBChargerPowerSt = _x.IPDS_FrontUSBChargerPowerSt;
		IPDS_PM25PowerSt = _x.IPDS_PM25PowerSt;
		IPDS_PassLumbarMotorPowerSt = _x.IPDS_PassLumbarMotorPowerSt;
		IPDS_FrontBlowerPowerSt = _x.IPDS_FrontBlowerPowerSt;
		IPDS_UWBSensorPowerSt = _x.IPDS_UWBSensorPowerSt;
		IPDS_KL15R1PowerSt = _x.IPDS_KL15R1PowerSt;
		IPDS_KL15R2PowerSt = _x.IPDS_KL15R2PowerSt;
		IPDS_RMPowerSt = _x.IPDS_RMPowerSt;
		IPDS_RearCtrlPanelPowerSt = _x.IPDS_RearCtrlPanelPowerSt;
		IPDS_Rear12VPowerSt = _x.IPDS_Rear12VPowerSt;
		IPDS_InverterPowerSt = _x.IPDS_InverterPowerSt;
		IPDS_RearMotorPowerSt = _x.IPDS_RearMotorPowerSt;
		IPDS_AMPPowerSt = _x.IPDS_AMPPowerSt;
		IPDS_RearEOPPowerSt = _x.IPDS_RearEOPPowerSt;
		IPDS_RearRadarPowerSt = _x.IPDS_RearRadarPowerSt;
		IPDS_RLALampCtlUnitPowerSt = _x.IPDS_RLALampCtlUnitPowerSt;
		IPDS_RRALampCtlUnitPowerSt = _x.IPDS_RRALampCtlUnitPowerSt;
		IPDS_RLBLampCtlUnitPowerSt = _x.IPDS_RLBLampCtlUnitPowerSt;
		IPDS_RRBLampCtlUnitPowerSt = _x.IPDS_RRBLampCtlUnitPowerSt;
		IPDS_EXVPowerSt = _x.IPDS_EXVPowerSt;
		IPDS_PASPowerSt = _x.IPDS_PASPowerSt;
		IPDS_GSMPowerSt = _x.IPDS_GSMPowerSt;
		IPDS_DSMPowerSt = _x.IPDS_DSMPowerSt;
		IPDS_KL15T2PowerSt = _x.IPDS_KL15T2PowerSt;
		IPDS_KL15T1PowerSt = _x.IPDS_KL15T1PowerSt;
		IPDS_KL15F1PowerSt = _x.IPDS_KL15F1PowerSt;
		IPDS_IPSPowerSt = _x.IPDS_IPSPowerSt;
		IPDS_BMSPowerSt = _x.IPDS_BMSPowerSt;
		IPDS_OBDPowerSt = _x.IPDS_OBDPowerSt;
		IPDS_RLSPowerSt = _x.IPDS_RLSPowerSt;
		IPDS_DVRPowerSt = _x.IPDS_DVRPowerSt;
		IPDS_ADCMain1PowerSt = _x.IPDS_ADCMain1PowerSt;
		IPDS_ADCMain2PowerSt = _x.IPDS_ADCMain2PowerSt;
		IPDS_BrakeNormalOpenSwPowerSt = _x.IPDS_BrakeNormalOpenSwPowerSt;
		IPDS_SAMPowerSt = _x.IPDS_SAMPowerSt;
		IPDS_TBoxPowerSt = _x.IPDS_TBoxPowerSt;
		IPDS_FrontIDCPowerSt = _x.IPDS_FrontIDCPowerSt;
		IPDS_RearDCDCPowerSt = _x.IPDS_RearDCDCPowerSt;
		IPDS_ADCBackup1PowerSt = _x.IPDS_ADCBackup1PowerSt;
		IPDS_ADCBackup2PowerSt = _x.IPDS_ADCBackup2PowerSt;
	}
	BDCIPDS3(BDCIPDS3 &&_x){
		IPDS_AMPPowerFaultSt = std::move(_x.IPDS_AMPPowerFaultSt);
		IPDS_RearEOPPowerFaultSt = std::move(_x.IPDS_RearEOPPowerFaultSt);
		IPDS_RearRadarPowerFaultSt = std::move(_x.IPDS_RearRadarPowerFaultSt);
		IPDS_RLALampCtlUnitPowerFaultSt = std::move(_x.IPDS_RLALampCtlUnitPowerFaultSt);
		IPDS_RRALampCtlUnitPowerFaultSt = std::move(_x.IPDS_RRALampCtlUnitPowerFaultSt);
		IPDS_RLBLampCtlUnitPowerFaultSt = std::move(_x.IPDS_RLBLampCtlUnitPowerFaultSt);
		IPDS_RRBLampCtlUnitPowerFaultSt = std::move(_x.IPDS_RRBLampCtlUnitPowerFaultSt);
		IPDS_EXVPowerFaultSt = std::move(_x.IPDS_EXVPowerFaultSt);
		IPDS_PASPowerFaultSt = std::move(_x.IPDS_PASPowerFaultSt);
		IPDS_GSMPowerFaultSt = std::move(_x.IPDS_GSMPowerFaultSt);
		IPDS_DSMPowerFaultSt = std::move(_x.IPDS_DSMPowerFaultSt);
		IPDS_KL15T2PowerFaultSt = std::move(_x.IPDS_KL15T2PowerFaultSt);
		IPDS_KL15T1PowerFaultSt = std::move(_x.IPDS_KL15T1PowerFaultSt);
		IPDS_KL15F1PowerFaultSt = std::move(_x.IPDS_KL15F1PowerFaultSt);
		IPDS_IPSPowerFaultSt = std::move(_x.IPDS_IPSPowerFaultSt);
		IPDS_BMSPowerFaultSt = std::move(_x.IPDS_BMSPowerFaultSt);
		IPDS_OBDPowerFaultSt = std::move(_x.IPDS_OBDPowerFaultSt);
		IPDS_RLSPowerFaultSt = std::move(_x.IPDS_RLSPowerFaultSt);
		IPDS_DVRPowerFaultSt = std::move(_x.IPDS_DVRPowerFaultSt);
		IPDS_ADCMain1PowerFaultSt = std::move(_x.IPDS_ADCMain1PowerFaultSt);
		IPDS_ADCMain2PowerFaultSt = std::move(_x.IPDS_ADCMain2PowerFaultSt);
		IPDS_BrakeSwNormalOpenPowerFaultSt = std::move(_x.IPDS_BrakeSwNormalOpenPowerFaultSt);
		IPDS_SAMPowerFaultSt = std::move(_x.IPDS_SAMPowerFaultSt);
		IPDS_TBoxPowerFaultSt = std::move(_x.IPDS_TBoxPowerFaultSt);
		IPDS_FrontIDCPowerFaultSt = std::move(_x.IPDS_FrontIDCPowerFaultSt);
		IPDS_RearDCDCPowerFaultSt = std::move(_x.IPDS_RearDCDCPowerFaultSt);
		IPDS_ADCBackup1PowerFaultSt = std::move(_x.IPDS_ADCBackup1PowerFaultSt);
		IPDS_ADCBackup2PowerFaultSt = std::move(_x.IPDS_ADCBackup2PowerFaultSt);
		IPDS_FLLampCtlUnitPowerSt = std::move(_x.IPDS_FLLampCtlUnitPowerSt);
		IPDS_FRLampCtlUnitPowerSt = std::move(_x.IPDS_FRLampCtlUnitPowerSt);
		IPDS_HVHPowerSt = std::move(_x.IPDS_HVHPowerSt);
		IPDS_IPUEOP1PowerSt = std::move(_x.IPDS_IPUEOP1PowerSt);
		IPDS_IPUEOP2PowerSt = std::move(_x.IPDS_IPUEOP2PowerSt);
		IPDS_IPUPowerSt = std::move(_x.IPDS_IPUPowerSt);
		IPDS_FrontRadarPowerSt = std::move(_x.IPDS_FrontRadarPowerSt);
		IPDS_FLRadarPowerSt = std::move(_x.IPDS_FLRadarPowerSt);
		IPDS_FRRadarPowerSt = std::move(_x.IPDS_FRRadarPowerSt);
		IPDS_AGSPowerSt = std::move(_x.IPDS_AGSPowerSt);
		IPDS_ECPPowerSt = std::move(_x.IPDS_ECPPowerSt);
		IPDS_AVASPowerSt = std::move(_x.IPDS_AVASPowerSt);
		IPDS_BrakeSwNormalClosePowerSt = std::move(_x.IPDS_BrakeSwNormalClosePowerSt);
		IPDS_AQSPowerSt = std::move(_x.IPDS_AQSPowerSt);
		IPDS_DriverLumbarMotorPowerSt = std::move(_x.IPDS_DriverLumbarMotorPowerSt);
		IPDS_RoofDevicePowerSt = std::move(_x.IPDS_RoofDevicePowerSt);
		IPDS_ETCPowerSt = std::move(_x.IPDS_ETCPowerSt);
		IPDS_ClusterDisplayPowerSt = std::move(_x.IPDS_ClusterDisplayPowerSt);
		IPDS_PassDisplayPowerSt = std::move(_x.IPDS_PassDisplayPowerSt);
		IPDS_IDCDisplayPowerSt = std::move(_x.IPDS_IDCDisplayPowerSt);
		IPDS_CigarLigterPowerSt = std::move(_x.IPDS_CigarLigterPowerSt);
		IPDS_HDMapPowerSt = std::move(_x.IPDS_HDMapPowerSt);
		IPDS_Lidar1PowerSt = std::move(_x.IPDS_Lidar1PowerSt);
		IPDS_Lidar2PowerSt = std::move(_x.IPDS_Lidar2PowerSt);
		IPDS_Lidar3PowerSt = std::move(_x.IPDS_Lidar3PowerSt);
		IPDS_HODPowerSt = std::move(_x.IPDS_HODPowerSt);
		IPDS_ESCLPowerSt = std::move(_x.IPDS_ESCLPowerSt);
		IPDS_ISRVMPowerSt = std::move(_x.IPDS_ISRVMPowerSt);
		IPDS_SRSECUPowerSt = std::move(_x.IPDS_SRSECUPowerSt);
		IPDS_KL15L1PowerSt = std::move(_x.IPDS_KL15L1PowerSt);
		IPDS_KL15L2PowerSt = std::move(_x.IPDS_KL15L2PowerSt);
		IPDS_HUDPowerSt = std::move(_x.IPDS_HUDPowerSt);
		IPDS_ClusterPowerSt = std::move(_x.IPDS_ClusterPowerSt);
		IPDS_WCMPowerSt = std::move(_x.IPDS_WCMPowerSt);
		IPDS_FrontUSBChargerPowerSt = std::move(_x.IPDS_FrontUSBChargerPowerSt);
		IPDS_PM25PowerSt = std::move(_x.IPDS_PM25PowerSt);
		IPDS_PassLumbarMotorPowerSt = std::move(_x.IPDS_PassLumbarMotorPowerSt);
		IPDS_FrontBlowerPowerSt = std::move(_x.IPDS_FrontBlowerPowerSt);
		IPDS_UWBSensorPowerSt = std::move(_x.IPDS_UWBSensorPowerSt);
		IPDS_KL15R1PowerSt = std::move(_x.IPDS_KL15R1PowerSt);
		IPDS_KL15R2PowerSt = std::move(_x.IPDS_KL15R2PowerSt);
		IPDS_RMPowerSt = std::move(_x.IPDS_RMPowerSt);
		IPDS_RearCtrlPanelPowerSt = std::move(_x.IPDS_RearCtrlPanelPowerSt);
		IPDS_Rear12VPowerSt = std::move(_x.IPDS_Rear12VPowerSt);
		IPDS_InverterPowerSt = std::move(_x.IPDS_InverterPowerSt);
		IPDS_RearMotorPowerSt = std::move(_x.IPDS_RearMotorPowerSt);
		IPDS_AMPPowerSt = std::move(_x.IPDS_AMPPowerSt);
		IPDS_RearEOPPowerSt = std::move(_x.IPDS_RearEOPPowerSt);
		IPDS_RearRadarPowerSt = std::move(_x.IPDS_RearRadarPowerSt);
		IPDS_RLALampCtlUnitPowerSt = std::move(_x.IPDS_RLALampCtlUnitPowerSt);
		IPDS_RRALampCtlUnitPowerSt = std::move(_x.IPDS_RRALampCtlUnitPowerSt);
		IPDS_RLBLampCtlUnitPowerSt = std::move(_x.IPDS_RLBLampCtlUnitPowerSt);
		IPDS_RRBLampCtlUnitPowerSt = std::move(_x.IPDS_RRBLampCtlUnitPowerSt);
		IPDS_EXVPowerSt = std::move(_x.IPDS_EXVPowerSt);
		IPDS_PASPowerSt = std::move(_x.IPDS_PASPowerSt);
		IPDS_GSMPowerSt = std::move(_x.IPDS_GSMPowerSt);
		IPDS_DSMPowerSt = std::move(_x.IPDS_DSMPowerSt);
		IPDS_KL15T2PowerSt = std::move(_x.IPDS_KL15T2PowerSt);
		IPDS_KL15T1PowerSt = std::move(_x.IPDS_KL15T1PowerSt);
		IPDS_KL15F1PowerSt = std::move(_x.IPDS_KL15F1PowerSt);
		IPDS_IPSPowerSt = std::move(_x.IPDS_IPSPowerSt);
		IPDS_BMSPowerSt = std::move(_x.IPDS_BMSPowerSt);
		IPDS_OBDPowerSt = std::move(_x.IPDS_OBDPowerSt);
		IPDS_RLSPowerSt = std::move(_x.IPDS_RLSPowerSt);
		IPDS_DVRPowerSt = std::move(_x.IPDS_DVRPowerSt);
		IPDS_ADCMain1PowerSt = std::move(_x.IPDS_ADCMain1PowerSt);
		IPDS_ADCMain2PowerSt = std::move(_x.IPDS_ADCMain2PowerSt);
		IPDS_BrakeNormalOpenSwPowerSt = std::move(_x.IPDS_BrakeNormalOpenSwPowerSt);
		IPDS_SAMPowerSt = std::move(_x.IPDS_SAMPowerSt);
		IPDS_TBoxPowerSt = std::move(_x.IPDS_TBoxPowerSt);
		IPDS_FrontIDCPowerSt = std::move(_x.IPDS_FrontIDCPowerSt);
		IPDS_RearDCDCPowerSt = std::move(_x.IPDS_RearDCDCPowerSt);
		IPDS_ADCBackup1PowerSt = std::move(_x.IPDS_ADCBackup1PowerSt);
		IPDS_ADCBackup2PowerSt = std::move(_x.IPDS_ADCBackup2PowerSt);
	}
	BDCIPDS3& operator=(const BDCIPDS3 &_x){
		IPDS_AMPPowerFaultSt = _x.IPDS_AMPPowerFaultSt;
		IPDS_RearEOPPowerFaultSt = _x.IPDS_RearEOPPowerFaultSt;
		IPDS_RearRadarPowerFaultSt = _x.IPDS_RearRadarPowerFaultSt;
		IPDS_RLALampCtlUnitPowerFaultSt = _x.IPDS_RLALampCtlUnitPowerFaultSt;
		IPDS_RRALampCtlUnitPowerFaultSt = _x.IPDS_RRALampCtlUnitPowerFaultSt;
		IPDS_RLBLampCtlUnitPowerFaultSt = _x.IPDS_RLBLampCtlUnitPowerFaultSt;
		IPDS_RRBLampCtlUnitPowerFaultSt = _x.IPDS_RRBLampCtlUnitPowerFaultSt;
		IPDS_EXVPowerFaultSt = _x.IPDS_EXVPowerFaultSt;
		IPDS_PASPowerFaultSt = _x.IPDS_PASPowerFaultSt;
		IPDS_GSMPowerFaultSt = _x.IPDS_GSMPowerFaultSt;
		IPDS_DSMPowerFaultSt = _x.IPDS_DSMPowerFaultSt;
		IPDS_KL15T2PowerFaultSt = _x.IPDS_KL15T2PowerFaultSt;
		IPDS_KL15T1PowerFaultSt = _x.IPDS_KL15T1PowerFaultSt;
		IPDS_KL15F1PowerFaultSt = _x.IPDS_KL15F1PowerFaultSt;
		IPDS_IPSPowerFaultSt = _x.IPDS_IPSPowerFaultSt;
		IPDS_BMSPowerFaultSt = _x.IPDS_BMSPowerFaultSt;
		IPDS_OBDPowerFaultSt = _x.IPDS_OBDPowerFaultSt;
		IPDS_RLSPowerFaultSt = _x.IPDS_RLSPowerFaultSt;
		IPDS_DVRPowerFaultSt = _x.IPDS_DVRPowerFaultSt;
		IPDS_ADCMain1PowerFaultSt = _x.IPDS_ADCMain1PowerFaultSt;
		IPDS_ADCMain2PowerFaultSt = _x.IPDS_ADCMain2PowerFaultSt;
		IPDS_BrakeSwNormalOpenPowerFaultSt = _x.IPDS_BrakeSwNormalOpenPowerFaultSt;
		IPDS_SAMPowerFaultSt = _x.IPDS_SAMPowerFaultSt;
		IPDS_TBoxPowerFaultSt = _x.IPDS_TBoxPowerFaultSt;
		IPDS_FrontIDCPowerFaultSt = _x.IPDS_FrontIDCPowerFaultSt;
		IPDS_RearDCDCPowerFaultSt = _x.IPDS_RearDCDCPowerFaultSt;
		IPDS_ADCBackup1PowerFaultSt = _x.IPDS_ADCBackup1PowerFaultSt;
		IPDS_ADCBackup2PowerFaultSt = _x.IPDS_ADCBackup2PowerFaultSt;
		IPDS_FLLampCtlUnitPowerSt = _x.IPDS_FLLampCtlUnitPowerSt;
		IPDS_FRLampCtlUnitPowerSt = _x.IPDS_FRLampCtlUnitPowerSt;
		IPDS_HVHPowerSt = _x.IPDS_HVHPowerSt;
		IPDS_IPUEOP1PowerSt = _x.IPDS_IPUEOP1PowerSt;
		IPDS_IPUEOP2PowerSt = _x.IPDS_IPUEOP2PowerSt;
		IPDS_IPUPowerSt = _x.IPDS_IPUPowerSt;
		IPDS_FrontRadarPowerSt = _x.IPDS_FrontRadarPowerSt;
		IPDS_FLRadarPowerSt = _x.IPDS_FLRadarPowerSt;
		IPDS_FRRadarPowerSt = _x.IPDS_FRRadarPowerSt;
		IPDS_AGSPowerSt = _x.IPDS_AGSPowerSt;
		IPDS_ECPPowerSt = _x.IPDS_ECPPowerSt;
		IPDS_AVASPowerSt = _x.IPDS_AVASPowerSt;
		IPDS_BrakeSwNormalClosePowerSt = _x.IPDS_BrakeSwNormalClosePowerSt;
		IPDS_AQSPowerSt = _x.IPDS_AQSPowerSt;
		IPDS_DriverLumbarMotorPowerSt = _x.IPDS_DriverLumbarMotorPowerSt;
		IPDS_RoofDevicePowerSt = _x.IPDS_RoofDevicePowerSt;
		IPDS_ETCPowerSt = _x.IPDS_ETCPowerSt;
		IPDS_ClusterDisplayPowerSt = _x.IPDS_ClusterDisplayPowerSt;
		IPDS_PassDisplayPowerSt = _x.IPDS_PassDisplayPowerSt;
		IPDS_IDCDisplayPowerSt = _x.IPDS_IDCDisplayPowerSt;
		IPDS_CigarLigterPowerSt = _x.IPDS_CigarLigterPowerSt;
		IPDS_HDMapPowerSt = _x.IPDS_HDMapPowerSt;
		IPDS_Lidar1PowerSt = _x.IPDS_Lidar1PowerSt;
		IPDS_Lidar2PowerSt = _x.IPDS_Lidar2PowerSt;
		IPDS_Lidar3PowerSt = _x.IPDS_Lidar3PowerSt;
		IPDS_HODPowerSt = _x.IPDS_HODPowerSt;
		IPDS_ESCLPowerSt = _x.IPDS_ESCLPowerSt;
		IPDS_ISRVMPowerSt = _x.IPDS_ISRVMPowerSt;
		IPDS_SRSECUPowerSt = _x.IPDS_SRSECUPowerSt;
		IPDS_KL15L1PowerSt = _x.IPDS_KL15L1PowerSt;
		IPDS_KL15L2PowerSt = _x.IPDS_KL15L2PowerSt;
		IPDS_HUDPowerSt = _x.IPDS_HUDPowerSt;
		IPDS_ClusterPowerSt = _x.IPDS_ClusterPowerSt;
		IPDS_WCMPowerSt = _x.IPDS_WCMPowerSt;
		IPDS_FrontUSBChargerPowerSt = _x.IPDS_FrontUSBChargerPowerSt;
		IPDS_PM25PowerSt = _x.IPDS_PM25PowerSt;
		IPDS_PassLumbarMotorPowerSt = _x.IPDS_PassLumbarMotorPowerSt;
		IPDS_FrontBlowerPowerSt = _x.IPDS_FrontBlowerPowerSt;
		IPDS_UWBSensorPowerSt = _x.IPDS_UWBSensorPowerSt;
		IPDS_KL15R1PowerSt = _x.IPDS_KL15R1PowerSt;
		IPDS_KL15R2PowerSt = _x.IPDS_KL15R2PowerSt;
		IPDS_RMPowerSt = _x.IPDS_RMPowerSt;
		IPDS_RearCtrlPanelPowerSt = _x.IPDS_RearCtrlPanelPowerSt;
		IPDS_Rear12VPowerSt = _x.IPDS_Rear12VPowerSt;
		IPDS_InverterPowerSt = _x.IPDS_InverterPowerSt;
		IPDS_RearMotorPowerSt = _x.IPDS_RearMotorPowerSt;
		IPDS_AMPPowerSt = _x.IPDS_AMPPowerSt;
		IPDS_RearEOPPowerSt = _x.IPDS_RearEOPPowerSt;
		IPDS_RearRadarPowerSt = _x.IPDS_RearRadarPowerSt;
		IPDS_RLALampCtlUnitPowerSt = _x.IPDS_RLALampCtlUnitPowerSt;
		IPDS_RRALampCtlUnitPowerSt = _x.IPDS_RRALampCtlUnitPowerSt;
		IPDS_RLBLampCtlUnitPowerSt = _x.IPDS_RLBLampCtlUnitPowerSt;
		IPDS_RRBLampCtlUnitPowerSt = _x.IPDS_RRBLampCtlUnitPowerSt;
		IPDS_EXVPowerSt = _x.IPDS_EXVPowerSt;
		IPDS_PASPowerSt = _x.IPDS_PASPowerSt;
		IPDS_GSMPowerSt = _x.IPDS_GSMPowerSt;
		IPDS_DSMPowerSt = _x.IPDS_DSMPowerSt;
		IPDS_KL15T2PowerSt = _x.IPDS_KL15T2PowerSt;
		IPDS_KL15T1PowerSt = _x.IPDS_KL15T1PowerSt;
		IPDS_KL15F1PowerSt = _x.IPDS_KL15F1PowerSt;
		IPDS_IPSPowerSt = _x.IPDS_IPSPowerSt;
		IPDS_BMSPowerSt = _x.IPDS_BMSPowerSt;
		IPDS_OBDPowerSt = _x.IPDS_OBDPowerSt;
		IPDS_RLSPowerSt = _x.IPDS_RLSPowerSt;
		IPDS_DVRPowerSt = _x.IPDS_DVRPowerSt;
		IPDS_ADCMain1PowerSt = _x.IPDS_ADCMain1PowerSt;
		IPDS_ADCMain2PowerSt = _x.IPDS_ADCMain2PowerSt;
		IPDS_BrakeNormalOpenSwPowerSt = _x.IPDS_BrakeNormalOpenSwPowerSt;
		IPDS_SAMPowerSt = _x.IPDS_SAMPowerSt;
		IPDS_TBoxPowerSt = _x.IPDS_TBoxPowerSt;
		IPDS_FrontIDCPowerSt = _x.IPDS_FrontIDCPowerSt;
		IPDS_RearDCDCPowerSt = _x.IPDS_RearDCDCPowerSt;
		IPDS_ADCBackup1PowerSt = _x.IPDS_ADCBackup1PowerSt;
		IPDS_ADCBackup2PowerSt = _x.IPDS_ADCBackup2PowerSt;
		return *this;
	}
	BDCIPDS3& operator=(BDCIPDS3 &&_x){
		IPDS_AMPPowerFaultSt = std::move(_x.IPDS_AMPPowerFaultSt);
		IPDS_RearEOPPowerFaultSt = std::move(_x.IPDS_RearEOPPowerFaultSt);
		IPDS_RearRadarPowerFaultSt = std::move(_x.IPDS_RearRadarPowerFaultSt);
		IPDS_RLALampCtlUnitPowerFaultSt = std::move(_x.IPDS_RLALampCtlUnitPowerFaultSt);
		IPDS_RRALampCtlUnitPowerFaultSt = std::move(_x.IPDS_RRALampCtlUnitPowerFaultSt);
		IPDS_RLBLampCtlUnitPowerFaultSt = std::move(_x.IPDS_RLBLampCtlUnitPowerFaultSt);
		IPDS_RRBLampCtlUnitPowerFaultSt = std::move(_x.IPDS_RRBLampCtlUnitPowerFaultSt);
		IPDS_EXVPowerFaultSt = std::move(_x.IPDS_EXVPowerFaultSt);
		IPDS_PASPowerFaultSt = std::move(_x.IPDS_PASPowerFaultSt);
		IPDS_GSMPowerFaultSt = std::move(_x.IPDS_GSMPowerFaultSt);
		IPDS_DSMPowerFaultSt = std::move(_x.IPDS_DSMPowerFaultSt);
		IPDS_KL15T2PowerFaultSt = std::move(_x.IPDS_KL15T2PowerFaultSt);
		IPDS_KL15T1PowerFaultSt = std::move(_x.IPDS_KL15T1PowerFaultSt);
		IPDS_KL15F1PowerFaultSt = std::move(_x.IPDS_KL15F1PowerFaultSt);
		IPDS_IPSPowerFaultSt = std::move(_x.IPDS_IPSPowerFaultSt);
		IPDS_BMSPowerFaultSt = std::move(_x.IPDS_BMSPowerFaultSt);
		IPDS_OBDPowerFaultSt = std::move(_x.IPDS_OBDPowerFaultSt);
		IPDS_RLSPowerFaultSt = std::move(_x.IPDS_RLSPowerFaultSt);
		IPDS_DVRPowerFaultSt = std::move(_x.IPDS_DVRPowerFaultSt);
		IPDS_ADCMain1PowerFaultSt = std::move(_x.IPDS_ADCMain1PowerFaultSt);
		IPDS_ADCMain2PowerFaultSt = std::move(_x.IPDS_ADCMain2PowerFaultSt);
		IPDS_BrakeSwNormalOpenPowerFaultSt = std::move(_x.IPDS_BrakeSwNormalOpenPowerFaultSt);
		IPDS_SAMPowerFaultSt = std::move(_x.IPDS_SAMPowerFaultSt);
		IPDS_TBoxPowerFaultSt = std::move(_x.IPDS_TBoxPowerFaultSt);
		IPDS_FrontIDCPowerFaultSt = std::move(_x.IPDS_FrontIDCPowerFaultSt);
		IPDS_RearDCDCPowerFaultSt = std::move(_x.IPDS_RearDCDCPowerFaultSt);
		IPDS_ADCBackup1PowerFaultSt = std::move(_x.IPDS_ADCBackup1PowerFaultSt);
		IPDS_ADCBackup2PowerFaultSt = std::move(_x.IPDS_ADCBackup2PowerFaultSt);
		IPDS_FLLampCtlUnitPowerSt = std::move(_x.IPDS_FLLampCtlUnitPowerSt);
		IPDS_FRLampCtlUnitPowerSt = std::move(_x.IPDS_FRLampCtlUnitPowerSt);
		IPDS_HVHPowerSt = std::move(_x.IPDS_HVHPowerSt);
		IPDS_IPUEOP1PowerSt = std::move(_x.IPDS_IPUEOP1PowerSt);
		IPDS_IPUEOP2PowerSt = std::move(_x.IPDS_IPUEOP2PowerSt);
		IPDS_IPUPowerSt = std::move(_x.IPDS_IPUPowerSt);
		IPDS_FrontRadarPowerSt = std::move(_x.IPDS_FrontRadarPowerSt);
		IPDS_FLRadarPowerSt = std::move(_x.IPDS_FLRadarPowerSt);
		IPDS_FRRadarPowerSt = std::move(_x.IPDS_FRRadarPowerSt);
		IPDS_AGSPowerSt = std::move(_x.IPDS_AGSPowerSt);
		IPDS_ECPPowerSt = std::move(_x.IPDS_ECPPowerSt);
		IPDS_AVASPowerSt = std::move(_x.IPDS_AVASPowerSt);
		IPDS_BrakeSwNormalClosePowerSt = std::move(_x.IPDS_BrakeSwNormalClosePowerSt);
		IPDS_AQSPowerSt = std::move(_x.IPDS_AQSPowerSt);
		IPDS_DriverLumbarMotorPowerSt = std::move(_x.IPDS_DriverLumbarMotorPowerSt);
		IPDS_RoofDevicePowerSt = std::move(_x.IPDS_RoofDevicePowerSt);
		IPDS_ETCPowerSt = std::move(_x.IPDS_ETCPowerSt);
		IPDS_ClusterDisplayPowerSt = std::move(_x.IPDS_ClusterDisplayPowerSt);
		IPDS_PassDisplayPowerSt = std::move(_x.IPDS_PassDisplayPowerSt);
		IPDS_IDCDisplayPowerSt = std::move(_x.IPDS_IDCDisplayPowerSt);
		IPDS_CigarLigterPowerSt = std::move(_x.IPDS_CigarLigterPowerSt);
		IPDS_HDMapPowerSt = std::move(_x.IPDS_HDMapPowerSt);
		IPDS_Lidar1PowerSt = std::move(_x.IPDS_Lidar1PowerSt);
		IPDS_Lidar2PowerSt = std::move(_x.IPDS_Lidar2PowerSt);
		IPDS_Lidar3PowerSt = std::move(_x.IPDS_Lidar3PowerSt);
		IPDS_HODPowerSt = std::move(_x.IPDS_HODPowerSt);
		IPDS_ESCLPowerSt = std::move(_x.IPDS_ESCLPowerSt);
		IPDS_ISRVMPowerSt = std::move(_x.IPDS_ISRVMPowerSt);
		IPDS_SRSECUPowerSt = std::move(_x.IPDS_SRSECUPowerSt);
		IPDS_KL15L1PowerSt = std::move(_x.IPDS_KL15L1PowerSt);
		IPDS_KL15L2PowerSt = std::move(_x.IPDS_KL15L2PowerSt);
		IPDS_HUDPowerSt = std::move(_x.IPDS_HUDPowerSt);
		IPDS_ClusterPowerSt = std::move(_x.IPDS_ClusterPowerSt);
		IPDS_WCMPowerSt = std::move(_x.IPDS_WCMPowerSt);
		IPDS_FrontUSBChargerPowerSt = std::move(_x.IPDS_FrontUSBChargerPowerSt);
		IPDS_PM25PowerSt = std::move(_x.IPDS_PM25PowerSt);
		IPDS_PassLumbarMotorPowerSt = std::move(_x.IPDS_PassLumbarMotorPowerSt);
		IPDS_FrontBlowerPowerSt = std::move(_x.IPDS_FrontBlowerPowerSt);
		IPDS_UWBSensorPowerSt = std::move(_x.IPDS_UWBSensorPowerSt);
		IPDS_KL15R1PowerSt = std::move(_x.IPDS_KL15R1PowerSt);
		IPDS_KL15R2PowerSt = std::move(_x.IPDS_KL15R2PowerSt);
		IPDS_RMPowerSt = std::move(_x.IPDS_RMPowerSt);
		IPDS_RearCtrlPanelPowerSt = std::move(_x.IPDS_RearCtrlPanelPowerSt);
		IPDS_Rear12VPowerSt = std::move(_x.IPDS_Rear12VPowerSt);
		IPDS_InverterPowerSt = std::move(_x.IPDS_InverterPowerSt);
		IPDS_RearMotorPowerSt = std::move(_x.IPDS_RearMotorPowerSt);
		IPDS_AMPPowerSt = std::move(_x.IPDS_AMPPowerSt);
		IPDS_RearEOPPowerSt = std::move(_x.IPDS_RearEOPPowerSt);
		IPDS_RearRadarPowerSt = std::move(_x.IPDS_RearRadarPowerSt);
		IPDS_RLALampCtlUnitPowerSt = std::move(_x.IPDS_RLALampCtlUnitPowerSt);
		IPDS_RRALampCtlUnitPowerSt = std::move(_x.IPDS_RRALampCtlUnitPowerSt);
		IPDS_RLBLampCtlUnitPowerSt = std::move(_x.IPDS_RLBLampCtlUnitPowerSt);
		IPDS_RRBLampCtlUnitPowerSt = std::move(_x.IPDS_RRBLampCtlUnitPowerSt);
		IPDS_EXVPowerSt = std::move(_x.IPDS_EXVPowerSt);
		IPDS_PASPowerSt = std::move(_x.IPDS_PASPowerSt);
		IPDS_GSMPowerSt = std::move(_x.IPDS_GSMPowerSt);
		IPDS_DSMPowerSt = std::move(_x.IPDS_DSMPowerSt);
		IPDS_KL15T2PowerSt = std::move(_x.IPDS_KL15T2PowerSt);
		IPDS_KL15T1PowerSt = std::move(_x.IPDS_KL15T1PowerSt);
		IPDS_KL15F1PowerSt = std::move(_x.IPDS_KL15F1PowerSt);
		IPDS_IPSPowerSt = std::move(_x.IPDS_IPSPowerSt);
		IPDS_BMSPowerSt = std::move(_x.IPDS_BMSPowerSt);
		IPDS_OBDPowerSt = std::move(_x.IPDS_OBDPowerSt);
		IPDS_RLSPowerSt = std::move(_x.IPDS_RLSPowerSt);
		IPDS_DVRPowerSt = std::move(_x.IPDS_DVRPowerSt);
		IPDS_ADCMain1PowerSt = std::move(_x.IPDS_ADCMain1PowerSt);
		IPDS_ADCMain2PowerSt = std::move(_x.IPDS_ADCMain2PowerSt);
		IPDS_BrakeNormalOpenSwPowerSt = std::move(_x.IPDS_BrakeNormalOpenSwPowerSt);
		IPDS_SAMPowerSt = std::move(_x.IPDS_SAMPowerSt);
		IPDS_TBoxPowerSt = std::move(_x.IPDS_TBoxPowerSt);
		IPDS_FrontIDCPowerSt = std::move(_x.IPDS_FrontIDCPowerSt);
		IPDS_RearDCDCPowerSt = std::move(_x.IPDS_RearDCDCPowerSt);
		IPDS_ADCBackup1PowerSt = std::move(_x.IPDS_ADCBackup1PowerSt);
		IPDS_ADCBackup2PowerSt = std::move(_x.IPDS_ADCBackup2PowerSt);
		return *this;
	}
*/

	using IsEnumerableTag = void;
	template<typename F>
	void enumerate(F& fun) {
		fun(IPDS_AMPPowerFaultSt);
		fun(IPDS_RearEOPPowerFaultSt);
		fun(IPDS_RearRadarPowerFaultSt);
		fun(IPDS_RLALampCtlUnitPowerFaultSt);
		fun(IPDS_RRALampCtlUnitPowerFaultSt);
		fun(IPDS_RLBLampCtlUnitPowerFaultSt);
		fun(IPDS_RRBLampCtlUnitPowerFaultSt);
		fun(IPDS_EXVPowerFaultSt);
		fun(IPDS_PASPowerFaultSt);
		fun(IPDS_GSMPowerFaultSt);
		fun(IPDS_DSMPowerFaultSt);
		fun(IPDS_KL15T2PowerFaultSt);
		fun(IPDS_KL15T1PowerFaultSt);
		fun(IPDS_KL15F1PowerFaultSt);
		fun(IPDS_IPSPowerFaultSt);
		fun(IPDS_BMSPowerFaultSt);
		fun(IPDS_OBDPowerFaultSt);
		fun(IPDS_RLSPowerFaultSt);
		fun(IPDS_DVRPowerFaultSt);
		fun(IPDS_ADCMain1PowerFaultSt);
		fun(IPDS_ADCMain2PowerFaultSt);
		fun(IPDS_BrakeSwNormalOpenPowerFaultSt);
		fun(IPDS_SAMPowerFaultSt);
		fun(IPDS_TBoxPowerFaultSt);
		fun(IPDS_FrontIDCPowerFaultSt);
		fun(IPDS_RearDCDCPowerFaultSt);
		fun(IPDS_ADCBackup1PowerFaultSt);
		fun(IPDS_ADCBackup2PowerFaultSt);
		fun(IPDS_FLLampCtlUnitPowerSt);
		fun(IPDS_FRLampCtlUnitPowerSt);
		fun(IPDS_HVHPowerSt);
		fun(IPDS_IPUEOP1PowerSt);
		fun(IPDS_IPUEOP2PowerSt);
		fun(IPDS_IPUPowerSt);
		fun(IPDS_FrontRadarPowerSt);
		fun(IPDS_FLRadarPowerSt);
		fun(IPDS_FRRadarPowerSt);
		fun(IPDS_AGSPowerSt);
		fun(IPDS_ECPPowerSt);
		fun(IPDS_AVASPowerSt);
		fun(IPDS_BrakeSwNormalClosePowerSt);
		fun(IPDS_AQSPowerSt);
		fun(IPDS_DriverLumbarMotorPowerSt);
		fun(IPDS_RoofDevicePowerSt);
		fun(IPDS_ETCPowerSt);
		fun(IPDS_ClusterDisplayPowerSt);
		fun(IPDS_PassDisplayPowerSt);
		fun(IPDS_IDCDisplayPowerSt);
		fun(IPDS_CigarLigterPowerSt);
		fun(IPDS_HDMapPowerSt);
		fun(IPDS_Lidar1PowerSt);
		fun(IPDS_Lidar2PowerSt);
		fun(IPDS_Lidar3PowerSt);
		fun(IPDS_HODPowerSt);
		fun(IPDS_ESCLPowerSt);
		fun(IPDS_ISRVMPowerSt);
		fun(IPDS_SRSECUPowerSt);
		fun(IPDS_KL15L1PowerSt);
		fun(IPDS_KL15L2PowerSt);
		fun(IPDS_HUDPowerSt);
		fun(IPDS_ClusterPowerSt);
		fun(IPDS_WCMPowerSt);
		fun(IPDS_FrontUSBChargerPowerSt);
		fun(IPDS_PM25PowerSt);
		fun(IPDS_PassLumbarMotorPowerSt);
		fun(IPDS_FrontBlowerPowerSt);
		fun(IPDS_UWBSensorPowerSt);
		fun(IPDS_KL15R1PowerSt);
		fun(IPDS_KL15R2PowerSt);
		fun(IPDS_RMPowerSt);
		fun(IPDS_RearCtrlPanelPowerSt);
		fun(IPDS_Rear12VPowerSt);
		fun(IPDS_InverterPowerSt);
		fun(IPDS_RearMotorPowerSt);
		fun(IPDS_AMPPowerSt);
		fun(IPDS_RearEOPPowerSt);
		fun(IPDS_RearRadarPowerSt);
		fun(IPDS_RLALampCtlUnitPowerSt);
		fun(IPDS_RRALampCtlUnitPowerSt);
		fun(IPDS_RLBLampCtlUnitPowerSt);
		fun(IPDS_RRBLampCtlUnitPowerSt);
		fun(IPDS_EXVPowerSt);
		fun(IPDS_PASPowerSt);
		fun(IPDS_GSMPowerSt);
		fun(IPDS_DSMPowerSt);
		fun(IPDS_KL15T2PowerSt);
		fun(IPDS_KL15T1PowerSt);
		fun(IPDS_KL15F1PowerSt);
		fun(IPDS_IPSPowerSt);
		fun(IPDS_BMSPowerSt);
		fun(IPDS_OBDPowerSt);
		fun(IPDS_RLSPowerSt);
		fun(IPDS_DVRPowerSt);
		fun(IPDS_ADCMain1PowerSt);
		fun(IPDS_ADCMain2PowerSt);
		fun(IPDS_BrakeNormalOpenSwPowerSt);
		fun(IPDS_SAMPowerSt);
		fun(IPDS_TBoxPowerSt);
		fun(IPDS_FrontIDCPowerSt);
		fun(IPDS_RearDCDCPowerSt);
		fun(IPDS_ADCBackup1PowerSt);
		fun(IPDS_ADCBackup2PowerSt);
	}

	template<typename F>
	void GetSize(F& fun) const{
		fun(IPDS_AMPPowerFaultSt);
		fun(IPDS_RearEOPPowerFaultSt);
		fun(IPDS_RearRadarPowerFaultSt);
		fun(IPDS_RLALampCtlUnitPowerFaultSt);
		fun(IPDS_RRALampCtlUnitPowerFaultSt);
		fun(IPDS_RLBLampCtlUnitPowerFaultSt);
		fun(IPDS_RRBLampCtlUnitPowerFaultSt);
		fun(IPDS_EXVPowerFaultSt);
		fun(IPDS_PASPowerFaultSt);
		fun(IPDS_GSMPowerFaultSt);
		fun(IPDS_DSMPowerFaultSt);
		fun(IPDS_KL15T2PowerFaultSt);
		fun(IPDS_KL15T1PowerFaultSt);
		fun(IPDS_KL15F1PowerFaultSt);
		fun(IPDS_IPSPowerFaultSt);
		fun(IPDS_BMSPowerFaultSt);
		fun(IPDS_OBDPowerFaultSt);
		fun(IPDS_RLSPowerFaultSt);
		fun(IPDS_DVRPowerFaultSt);
		fun(IPDS_ADCMain1PowerFaultSt);
		fun(IPDS_ADCMain2PowerFaultSt);
		fun(IPDS_BrakeSwNormalOpenPowerFaultSt);
		fun(IPDS_SAMPowerFaultSt);
		fun(IPDS_TBoxPowerFaultSt);
		fun(IPDS_FrontIDCPowerFaultSt);
		fun(IPDS_RearDCDCPowerFaultSt);
		fun(IPDS_ADCBackup1PowerFaultSt);
		fun(IPDS_ADCBackup2PowerFaultSt);
		fun(IPDS_FLLampCtlUnitPowerSt);
		fun(IPDS_FRLampCtlUnitPowerSt);
		fun(IPDS_HVHPowerSt);
		fun(IPDS_IPUEOP1PowerSt);
		fun(IPDS_IPUEOP2PowerSt);
		fun(IPDS_IPUPowerSt);
		fun(IPDS_FrontRadarPowerSt);
		fun(IPDS_FLRadarPowerSt);
		fun(IPDS_FRRadarPowerSt);
		fun(IPDS_AGSPowerSt);
		fun(IPDS_ECPPowerSt);
		fun(IPDS_AVASPowerSt);
		fun(IPDS_BrakeSwNormalClosePowerSt);
		fun(IPDS_AQSPowerSt);
		fun(IPDS_DriverLumbarMotorPowerSt);
		fun(IPDS_RoofDevicePowerSt);
		fun(IPDS_ETCPowerSt);
		fun(IPDS_ClusterDisplayPowerSt);
		fun(IPDS_PassDisplayPowerSt);
		fun(IPDS_IDCDisplayPowerSt);
		fun(IPDS_CigarLigterPowerSt);
		fun(IPDS_HDMapPowerSt);
		fun(IPDS_Lidar1PowerSt);
		fun(IPDS_Lidar2PowerSt);
		fun(IPDS_Lidar3PowerSt);
		fun(IPDS_HODPowerSt);
		fun(IPDS_ESCLPowerSt);
		fun(IPDS_ISRVMPowerSt);
		fun(IPDS_SRSECUPowerSt);
		fun(IPDS_KL15L1PowerSt);
		fun(IPDS_KL15L2PowerSt);
		fun(IPDS_HUDPowerSt);
		fun(IPDS_ClusterPowerSt);
		fun(IPDS_WCMPowerSt);
		fun(IPDS_FrontUSBChargerPowerSt);
		fun(IPDS_PM25PowerSt);
		fun(IPDS_PassLumbarMotorPowerSt);
		fun(IPDS_FrontBlowerPowerSt);
		fun(IPDS_UWBSensorPowerSt);
		fun(IPDS_KL15R1PowerSt);
		fun(IPDS_KL15R2PowerSt);
		fun(IPDS_RMPowerSt);
		fun(IPDS_RearCtrlPanelPowerSt);
		fun(IPDS_Rear12VPowerSt);
		fun(IPDS_InverterPowerSt);
		fun(IPDS_RearMotorPowerSt);
		fun(IPDS_AMPPowerSt);
		fun(IPDS_RearEOPPowerSt);
		fun(IPDS_RearRadarPowerSt);
		fun(IPDS_RLALampCtlUnitPowerSt);
		fun(IPDS_RRALampCtlUnitPowerSt);
		fun(IPDS_RLBLampCtlUnitPowerSt);
		fun(IPDS_RRBLampCtlUnitPowerSt);
		fun(IPDS_EXVPowerSt);
		fun(IPDS_PASPowerSt);
		fun(IPDS_GSMPowerSt);
		fun(IPDS_DSMPowerSt);
		fun(IPDS_KL15T2PowerSt);
		fun(IPDS_KL15T1PowerSt);
		fun(IPDS_KL15F1PowerSt);
		fun(IPDS_IPSPowerSt);
		fun(IPDS_BMSPowerSt);
		fun(IPDS_OBDPowerSt);
		fun(IPDS_RLSPowerSt);
		fun(IPDS_DVRPowerSt);
		fun(IPDS_ADCMain1PowerSt);
		fun(IPDS_ADCMain2PowerSt);
		fun(IPDS_BrakeNormalOpenSwPowerSt);
		fun(IPDS_SAMPowerSt);
		fun(IPDS_TBoxPowerSt);
		fun(IPDS_FrontIDCPowerSt);
		fun(IPDS_RearDCDCPowerSt);
		fun(IPDS_ADCBackup1PowerSt);
		fun(IPDS_ADCBackup2PowerSt);
	}
	template<typename F>
	void serialize(F& fun) const{
		fun << (IPDS_AMPPowerFaultSt);
		fun << (IPDS_RearEOPPowerFaultSt);
		fun << (IPDS_RearRadarPowerFaultSt);
		fun << (IPDS_RLALampCtlUnitPowerFaultSt);
		fun << (IPDS_RRALampCtlUnitPowerFaultSt);
		fun << (IPDS_RLBLampCtlUnitPowerFaultSt);
		fun << (IPDS_RRBLampCtlUnitPowerFaultSt);
		fun << (IPDS_EXVPowerFaultSt);
		fun << (IPDS_PASPowerFaultSt);
		fun << (IPDS_GSMPowerFaultSt);
		fun << (IPDS_DSMPowerFaultSt);
		fun << (IPDS_KL15T2PowerFaultSt);
		fun << (IPDS_KL15T1PowerFaultSt);
		fun << (IPDS_KL15F1PowerFaultSt);
		fun << (IPDS_IPSPowerFaultSt);
		fun << (IPDS_BMSPowerFaultSt);
		fun << (IPDS_OBDPowerFaultSt);
		fun << (IPDS_RLSPowerFaultSt);
		fun << (IPDS_DVRPowerFaultSt);
		fun << (IPDS_ADCMain1PowerFaultSt);
		fun << (IPDS_ADCMain2PowerFaultSt);
		fun << (IPDS_BrakeSwNormalOpenPowerFaultSt);
		fun << (IPDS_SAMPowerFaultSt);
		fun << (IPDS_TBoxPowerFaultSt);
		fun << (IPDS_FrontIDCPowerFaultSt);
		fun << (IPDS_RearDCDCPowerFaultSt);
		fun << (IPDS_ADCBackup1PowerFaultSt);
		fun << (IPDS_ADCBackup2PowerFaultSt);
		fun << (IPDS_FLLampCtlUnitPowerSt);
		fun << (IPDS_FRLampCtlUnitPowerSt);
		fun << (IPDS_HVHPowerSt);
		fun << (IPDS_IPUEOP1PowerSt);
		fun << (IPDS_IPUEOP2PowerSt);
		fun << (IPDS_IPUPowerSt);
		fun << (IPDS_FrontRadarPowerSt);
		fun << (IPDS_FLRadarPowerSt);
		fun << (IPDS_FRRadarPowerSt);
		fun << (IPDS_AGSPowerSt);
		fun << (IPDS_ECPPowerSt);
		fun << (IPDS_AVASPowerSt);
		fun << (IPDS_BrakeSwNormalClosePowerSt);
		fun << (IPDS_AQSPowerSt);
		fun << (IPDS_DriverLumbarMotorPowerSt);
		fun << (IPDS_RoofDevicePowerSt);
		fun << (IPDS_ETCPowerSt);
		fun << (IPDS_ClusterDisplayPowerSt);
		fun << (IPDS_PassDisplayPowerSt);
		fun << (IPDS_IDCDisplayPowerSt);
		fun << (IPDS_CigarLigterPowerSt);
		fun << (IPDS_HDMapPowerSt);
		fun << (IPDS_Lidar1PowerSt);
		fun << (IPDS_Lidar2PowerSt);
		fun << (IPDS_Lidar3PowerSt);
		fun << (IPDS_HODPowerSt);
		fun << (IPDS_ESCLPowerSt);
		fun << (IPDS_ISRVMPowerSt);
		fun << (IPDS_SRSECUPowerSt);
		fun << (IPDS_KL15L1PowerSt);
		fun << (IPDS_KL15L2PowerSt);
		fun << (IPDS_HUDPowerSt);
		fun << (IPDS_ClusterPowerSt);
		fun << (IPDS_WCMPowerSt);
		fun << (IPDS_FrontUSBChargerPowerSt);
		fun << (IPDS_PM25PowerSt);
		fun << (IPDS_PassLumbarMotorPowerSt);
		fun << (IPDS_FrontBlowerPowerSt);
		fun << (IPDS_UWBSensorPowerSt);
		fun << (IPDS_KL15R1PowerSt);
		fun << (IPDS_KL15R2PowerSt);
		fun << (IPDS_RMPowerSt);
		fun << (IPDS_RearCtrlPanelPowerSt);
		fun << (IPDS_Rear12VPowerSt);
		fun << (IPDS_InverterPowerSt);
		fun << (IPDS_RearMotorPowerSt);
		fun << (IPDS_AMPPowerSt);
		fun << (IPDS_RearEOPPowerSt);
		fun << (IPDS_RearRadarPowerSt);
		fun << (IPDS_RLALampCtlUnitPowerSt);
		fun << (IPDS_RRALampCtlUnitPowerSt);
		fun << (IPDS_RLBLampCtlUnitPowerSt);
		fun << (IPDS_RRBLampCtlUnitPowerSt);
		fun << (IPDS_EXVPowerSt);
		fun << (IPDS_PASPowerSt);
		fun << (IPDS_GSMPowerSt);
		fun << (IPDS_DSMPowerSt);
		fun << (IPDS_KL15T2PowerSt);
		fun << (IPDS_KL15T1PowerSt);
		fun << (IPDS_KL15F1PowerSt);
		fun << (IPDS_IPSPowerSt);
		fun << (IPDS_BMSPowerSt);
		fun << (IPDS_OBDPowerSt);
		fun << (IPDS_RLSPowerSt);
		fun << (IPDS_DVRPowerSt);
		fun << (IPDS_ADCMain1PowerSt);
		fun << (IPDS_ADCMain2PowerSt);
		fun << (IPDS_BrakeNormalOpenSwPowerSt);
		fun << (IPDS_SAMPowerSt);
		fun << (IPDS_TBoxPowerSt);
		fun << (IPDS_FrontIDCPowerSt);
		fun << (IPDS_RearDCDCPowerSt);
		fun << (IPDS_ADCBackup1PowerSt);
		fun << (IPDS_ADCBackup2PowerSt);
	}
	template<typename F>
	void deserialize(F& fun){
		fun >> (IPDS_AMPPowerFaultSt);
		fun >> (IPDS_RearEOPPowerFaultSt);
		fun >> (IPDS_RearRadarPowerFaultSt);
		fun >> (IPDS_RLALampCtlUnitPowerFaultSt);
		fun >> (IPDS_RRALampCtlUnitPowerFaultSt);
		fun >> (IPDS_RLBLampCtlUnitPowerFaultSt);
		fun >> (IPDS_RRBLampCtlUnitPowerFaultSt);
		fun >> (IPDS_EXVPowerFaultSt);
		fun >> (IPDS_PASPowerFaultSt);
		fun >> (IPDS_GSMPowerFaultSt);
		fun >> (IPDS_DSMPowerFaultSt);
		fun >> (IPDS_KL15T2PowerFaultSt);
		fun >> (IPDS_KL15T1PowerFaultSt);
		fun >> (IPDS_KL15F1PowerFaultSt);
		fun >> (IPDS_IPSPowerFaultSt);
		fun >> (IPDS_BMSPowerFaultSt);
		fun >> (IPDS_OBDPowerFaultSt);
		fun >> (IPDS_RLSPowerFaultSt);
		fun >> (IPDS_DVRPowerFaultSt);
		fun >> (IPDS_ADCMain1PowerFaultSt);
		fun >> (IPDS_ADCMain2PowerFaultSt);
		fun >> (IPDS_BrakeSwNormalOpenPowerFaultSt);
		fun >> (IPDS_SAMPowerFaultSt);
		fun >> (IPDS_TBoxPowerFaultSt);
		fun >> (IPDS_FrontIDCPowerFaultSt);
		fun >> (IPDS_RearDCDCPowerFaultSt);
		fun >> (IPDS_ADCBackup1PowerFaultSt);
		fun >> (IPDS_ADCBackup2PowerFaultSt);
		fun >> (IPDS_FLLampCtlUnitPowerSt);
		fun >> (IPDS_FRLampCtlUnitPowerSt);
		fun >> (IPDS_HVHPowerSt);
		fun >> (IPDS_IPUEOP1PowerSt);
		fun >> (IPDS_IPUEOP2PowerSt);
		fun >> (IPDS_IPUPowerSt);
		fun >> (IPDS_FrontRadarPowerSt);
		fun >> (IPDS_FLRadarPowerSt);
		fun >> (IPDS_FRRadarPowerSt);
		fun >> (IPDS_AGSPowerSt);
		fun >> (IPDS_ECPPowerSt);
		fun >> (IPDS_AVASPowerSt);
		fun >> (IPDS_BrakeSwNormalClosePowerSt);
		fun >> (IPDS_AQSPowerSt);
		fun >> (IPDS_DriverLumbarMotorPowerSt);
		fun >> (IPDS_RoofDevicePowerSt);
		fun >> (IPDS_ETCPowerSt);
		fun >> (IPDS_ClusterDisplayPowerSt);
		fun >> (IPDS_PassDisplayPowerSt);
		fun >> (IPDS_IDCDisplayPowerSt);
		fun >> (IPDS_CigarLigterPowerSt);
		fun >> (IPDS_HDMapPowerSt);
		fun >> (IPDS_Lidar1PowerSt);
		fun >> (IPDS_Lidar2PowerSt);
		fun >> (IPDS_Lidar3PowerSt);
		fun >> (IPDS_HODPowerSt);
		fun >> (IPDS_ESCLPowerSt);
		fun >> (IPDS_ISRVMPowerSt);
		fun >> (IPDS_SRSECUPowerSt);
		fun >> (IPDS_KL15L1PowerSt);
		fun >> (IPDS_KL15L2PowerSt);
		fun >> (IPDS_HUDPowerSt);
		fun >> (IPDS_ClusterPowerSt);
		fun >> (IPDS_WCMPowerSt);
		fun >> (IPDS_FrontUSBChargerPowerSt);
		fun >> (IPDS_PM25PowerSt);
		fun >> (IPDS_PassLumbarMotorPowerSt);
		fun >> (IPDS_FrontBlowerPowerSt);
		fun >> (IPDS_UWBSensorPowerSt);
		fun >> (IPDS_KL15R1PowerSt);
		fun >> (IPDS_KL15R2PowerSt);
		fun >> (IPDS_RMPowerSt);
		fun >> (IPDS_RearCtrlPanelPowerSt);
		fun >> (IPDS_Rear12VPowerSt);
		fun >> (IPDS_InverterPowerSt);
		fun >> (IPDS_RearMotorPowerSt);
		fun >> (IPDS_AMPPowerSt);
		fun >> (IPDS_RearEOPPowerSt);
		fun >> (IPDS_RearRadarPowerSt);
		fun >> (IPDS_RLALampCtlUnitPowerSt);
		fun >> (IPDS_RRALampCtlUnitPowerSt);
		fun >> (IPDS_RLBLampCtlUnitPowerSt);
		fun >> (IPDS_RRBLampCtlUnitPowerSt);
		fun >> (IPDS_EXVPowerSt);
		fun >> (IPDS_PASPowerSt);
		fun >> (IPDS_GSMPowerSt);
		fun >> (IPDS_DSMPowerSt);
		fun >> (IPDS_KL15T2PowerSt);
		fun >> (IPDS_KL15T1PowerSt);
		fun >> (IPDS_KL15F1PowerSt);
		fun >> (IPDS_IPSPowerSt);
		fun >> (IPDS_BMSPowerSt);
		fun >> (IPDS_OBDPowerSt);
		fun >> (IPDS_RLSPowerSt);
		fun >> (IPDS_DVRPowerSt);
		fun >> (IPDS_ADCMain1PowerSt);
		fun >> (IPDS_ADCMain2PowerSt);
		fun >> (IPDS_BrakeNormalOpenSwPowerSt);
		fun >> (IPDS_SAMPowerSt);
		fun >> (IPDS_TBoxPowerSt);
		fun >> (IPDS_FrontIDCPowerSt);
		fun >> (IPDS_RearDCDCPowerSt);
		fun >> (IPDS_ADCBackup1PowerSt);
		fun >> (IPDS_ADCBackup2PowerSt);
	}
};

#endif //____BDCIPDS3_H__
