#ifndef ____BDCTESTGVS_H__
#define ____BDCTESTGVS_H__


#include "cstdint"






struct BDCTestGVS {
public:
	std::uint16_t BSGChrgTorq;
	std::uint16_t CrpTorqReq;
	std::uint16_t MasFlwThrAirCtoffDes;
	std::uint16_t TcuIdlSpdReq;
	std::uint8_t ThrCtrlActv;
	std::uint16_t TorqTraLos;
	std::uint8_t TraTOStReq;
	std::uint8_t VehSrvLmp;
	std::uint16_t TorqPTRsvReq;
	std::uint16_t IdlSpdWOTcuReq;
	std::uint16_t TorqDesAcs;
	std::uint8_t RefuleSwSt;
	std::uint8_t PWMFanDtyCylAct;
	std::uint8_t EMS_GVS_CatHtgActv;
	std::uint8_t EMS_GVS_CatHtgReq;
	std::uint8_t EMS_GVS_CylFuelCutSt;
	std::uint16_t EMS_GVS_CnvsFacFmiToTorq;
	std::uint16_t EMS_GVS_DutyCylLamdaHtr;
	std::uint8_t EMS_GVS_EngSpdFcoEna;
	std::uint16_t EMS_GVS_EngSpdFcoOffs;
	std::uint8_t EMS_GVS_EngAutoStopEna;
	std::uint8_t EMS_GVS_EngLimpActv;
	std::uint16_t EMS_GVS_EngSpdFlCtIn;
	std::uint8_t EMS_GVS_EngOilEstmd;
	std::uint8_t EMS_GVS_EngTempStrt;
	std::uint8_t EMS_GVS_EnvTemp;
	std::uint8_t EMS_GVS_EngIdleGovTgtSlwTrqVD;
	std::uint16_t EMS_GVS_EngIdleGovTgtSlwTrq;
	std::uint16_t EMS_GVS_EngIdleGovTgtFstTrq;
	std::uint8_t EMS_GVS_EngIdleGovTgtFstTrqVD;
	std::uint16_t EMS_GVS_EngClthMaxSlwTrq;
	std::uint8_t EMS_GVS_EngClthMaxSlwTrqVD;
	std::uint8_t EMS_GVS_EngClthMaxFstTrqVD;
	std::uint16_t EMS_GVS_EngClthMaxFstTrq;
	std::uint16_t EMS_GVS_EngAccFricTrqWOM;
	std::uint16_t EMS_GVS_EngStrtTime;
	std::uint16_t EMS_GVS_EngIdleRefSpdWoTCU;
	std::uint8_t EMS_GVS_EngIdleActvPreCtrl;
	std::uint16_t EMS_GVS_EngClthDragTorq;
	std::uint8_t EMS_GVS_EngClthDragTorqVD;
	std::uint8_t EMS_GVS_FRErrReact;
	std::uint8_t EMS_GVS_FaultrankSig;
	std::uint16_t EMS_GVS_MassFlwThrAirDesWoHcu;
	std::uint16_t EMS_GVS_MassFlwThrAirUGD;
	std::uint16_t EMS_GVS_PwtLosTorq;
	std::uint8_t EMS_GVS_PwtLosTorqVD;
	std::uint8_t EMS_GVS_PTGrip;
	std::uint8_t EMS_GVS_SftyFulCutOff;
	std::uint8_t EMS_GVS_ThtlBackUpModActv;
	std::uint8_t EMS_GVS_TrqCrepEngPrcssVD;
	std::uint8_t EMS_GVS_TrqCrepEngPrcss;
	std::uint16_t EMS_GVS_trnGearRatio;
	std::uint16_t EMS_GVS_VlFlwEngFuelInj;
	std::uint8_t EMS_GVS_ACClgDemReq;
	std::uint8_t EMS_GVS_CmprEnabl;
	std::uint8_t EMS_GVS_ThrVlvSensErr;
	std::uint8_t EMS_CompressorSt;
	std::uint8_t EMS_GVS_CoolFanDutyCycleReq;
	std::uint8_t EMS_GVS_CoolFanDutyCycleReqVD;
	std::uint8_t EMS_GVS_AccPedalPst;
	std::uint8_t EMS_GVS_AccPedalPstVD;
	std::uint8_t EMS_GVS_AccPedalPstProtValue;
	std::uint8_t EMS_GVS_EngSpd10msVD;
	std::uint16_t EMS_GVS_EngSpd10ms;
	std::uint8_t EMS_GVS_EMSSubSt;
	std::uint8_t EMS_GVS_FuelPressureReleaseStDis;
	std::uint8_t EMS_GVS_KL15St;
	std::uint8_t EMS_GVS_FuelCapLockReq;
	std::uint8_t EMS_GVS_FuelCapUnLockReq;
	std::uint8_t EMS_GVS_BrkPlausChkErr;
	std::uint8_t EMS_GVS_AccPedalErr;
	std::uint8_t EMS_GVS_CCConfg;
	std::uint8_t EMS_GVS_ACCConfg;
	std::uint16_t EMS_GVS_EngOffTimeCt;
/*
	BDCTestGVS() {}
	~BDCTestGVS() {}
	BDCTestGVS(const std::uint16_t _BSGChrgTorq,const std::uint16_t _CrpTorqReq,const std::uint16_t _MasFlwThrAirCtoffDes,const std::uint16_t _TcuIdlSpdReq,const std::uint8_t _ThrCtrlActv,const std::uint16_t _TorqTraLos,const std::uint8_t _TraTOStReq,const std::uint8_t _VehSrvLmp,const std::uint16_t _TorqPTRsvReq,const std::uint16_t _IdlSpdWOTcuReq,const std::uint16_t _TorqDesAcs,const std::uint8_t _RefuleSwSt,const std::uint8_t _PWMFanDtyCylAct,const std::uint8_t _EMS_GVS_CatHtgActv,const std::uint8_t _EMS_GVS_CatHtgReq,const std::uint8_t _EMS_GVS_CylFuelCutSt,const std::uint16_t _EMS_GVS_CnvsFacFmiToTorq,const std::uint16_t _EMS_GVS_DutyCylLamdaHtr,const std::uint8_t _EMS_GVS_EngSpdFcoEna,const std::uint16_t _EMS_GVS_EngSpdFcoOffs,const std::uint8_t _EMS_GVS_EngAutoStopEna,const std::uint8_t _EMS_GVS_EngLimpActv,const std::uint16_t _EMS_GVS_EngSpdFlCtIn,const std::uint8_t _EMS_GVS_EngOilEstmd,const std::uint8_t _EMS_GVS_EngTempStrt,const std::uint8_t _EMS_GVS_EnvTemp,const std::uint8_t _EMS_GVS_EngIdleGovTgtSlwTrqVD,const std::uint16_t _EMS_GVS_EngIdleGovTgtSlwTrq,const std::uint16_t _EMS_GVS_EngIdleGovTgtFstTrq,const std::uint8_t _EMS_GVS_EngIdleGovTgtFstTrqVD,const std::uint16_t _EMS_GVS_EngClthMaxSlwTrq,const std::uint8_t _EMS_GVS_EngClthMaxSlwTrqVD,const std::uint8_t _EMS_GVS_EngClthMaxFstTrqVD,const std::uint16_t _EMS_GVS_EngClthMaxFstTrq,const std::uint16_t _EMS_GVS_EngAccFricTrqWOM,const std::uint16_t _EMS_GVS_EngStrtTime,const std::uint16_t _EMS_GVS_EngIdleRefSpdWoTCU,const std::uint8_t _EMS_GVS_EngIdleActvPreCtrl,const std::uint16_t _EMS_GVS_EngClthDragTorq,const std::uint8_t _EMS_GVS_EngClthDragTorqVD,const std::uint8_t _EMS_GVS_FRErrReact,const std::uint8_t _EMS_GVS_FaultrankSig,const std::uint16_t _EMS_GVS_MassFlwThrAirDesWoHcu,const std::uint16_t _EMS_GVS_MassFlwThrAirUGD,const std::uint16_t _EMS_GVS_PwtLosTorq,const std::uint8_t _EMS_GVS_PwtLosTorqVD,const std::uint8_t _EMS_GVS_PTGrip,const std::uint8_t _EMS_GVS_SftyFulCutOff,const std::uint8_t _EMS_GVS_ThtlBackUpModActv,const std::uint8_t _EMS_GVS_TrqCrepEngPrcssVD,const std::uint8_t _EMS_GVS_TrqCrepEngPrcss,const std::uint16_t _EMS_GVS_trnGearRatio,const std::uint16_t _EMS_GVS_VlFlwEngFuelInj,const std::uint8_t _EMS_GVS_ACClgDemReq,const std::uint8_t _EMS_GVS_CmprEnabl,const std::uint8_t _EMS_GVS_ThrVlvSensErr,const std::uint8_t _EMS_CompressorSt,const std::uint8_t _EMS_GVS_CoolFanDutyCycleReq,const std::uint8_t _EMS_GVS_CoolFanDutyCycleReqVD,const std::uint8_t _EMS_GVS_AccPedalPst,const std::uint8_t _EMS_GVS_AccPedalPstVD,const std::uint8_t _EMS_GVS_AccPedalPstProtValue,const std::uint8_t _EMS_GVS_EngSpd10msVD,const std::uint16_t _EMS_GVS_EngSpd10ms,const std::uint8_t _EMS_GVS_EMSSubSt,const std::uint8_t _EMS_GVS_FuelPressureReleaseStDis,const std::uint8_t _EMS_GVS_KL15St,const std::uint8_t _EMS_GVS_FuelCapLockReq,const std::uint8_t _EMS_GVS_FuelCapUnLockReq,const std::uint8_t _EMS_GVS_BrkPlausChkErr,const std::uint8_t _EMS_GVS_AccPedalErr,const std::uint8_t _EMS_GVS_CCConfg,const std::uint8_t _EMS_GVS_ACCConfg,const std::uint16_t _EMS_GVS_EngOffTimeCt):BSGChrgTorq(_BSGChrgTorq),CrpTorqReq(_CrpTorqReq),MasFlwThrAirCtoffDes(_MasFlwThrAirCtoffDes),TcuIdlSpdReq(_TcuIdlSpdReq),ThrCtrlActv(_ThrCtrlActv),TorqTraLos(_TorqTraLos),TraTOStReq(_TraTOStReq),VehSrvLmp(_VehSrvLmp),TorqPTRsvReq(_TorqPTRsvReq),IdlSpdWOTcuReq(_IdlSpdWOTcuReq),TorqDesAcs(_TorqDesAcs),RefuleSwSt(_RefuleSwSt),PWMFanDtyCylAct(_PWMFanDtyCylAct),EMS_GVS_CatHtgActv(_EMS_GVS_CatHtgActv),EMS_GVS_CatHtgReq(_EMS_GVS_CatHtgReq),EMS_GVS_CylFuelCutSt(_EMS_GVS_CylFuelCutSt),EMS_GVS_CnvsFacFmiToTorq(_EMS_GVS_CnvsFacFmiToTorq),EMS_GVS_DutyCylLamdaHtr(_EMS_GVS_DutyCylLamdaHtr),EMS_GVS_EngSpdFcoEna(_EMS_GVS_EngSpdFcoEna),EMS_GVS_EngSpdFcoOffs(_EMS_GVS_EngSpdFcoOffs),EMS_GVS_EngAutoStopEna(_EMS_GVS_EngAutoStopEna),EMS_GVS_EngLimpActv(_EMS_GVS_EngLimpActv),EMS_GVS_EngSpdFlCtIn(_EMS_GVS_EngSpdFlCtIn),EMS_GVS_EngOilEstmd(_EMS_GVS_EngOilEstmd),EMS_GVS_EngTempStrt(_EMS_GVS_EngTempStrt),EMS_GVS_EnvTemp(_EMS_GVS_EnvTemp),EMS_GVS_EngIdleGovTgtSlwTrqVD(_EMS_GVS_EngIdleGovTgtSlwTrqVD),EMS_GVS_EngIdleGovTgtSlwTrq(_EMS_GVS_EngIdleGovTgtSlwTrq),EMS_GVS_EngIdleGovTgtFstTrq(_EMS_GVS_EngIdleGovTgtFstTrq),EMS_GVS_EngIdleGovTgtFstTrqVD(_EMS_GVS_EngIdleGovTgtFstTrqVD),EMS_GVS_EngClthMaxSlwTrq(_EMS_GVS_EngClthMaxSlwTrq),EMS_GVS_EngClthMaxSlwTrqVD(_EMS_GVS_EngClthMaxSlwTrqVD),EMS_GVS_EngClthMaxFstTrqVD(_EMS_GVS_EngClthMaxFstTrqVD),EMS_GVS_EngClthMaxFstTrq(_EMS_GVS_EngClthMaxFstTrq),EMS_GVS_EngAccFricTrqWOM(_EMS_GVS_EngAccFricTrqWOM),EMS_GVS_EngStrtTime(_EMS_GVS_EngStrtTime),EMS_GVS_EngIdleRefSpdWoTCU(_EMS_GVS_EngIdleRefSpdWoTCU),EMS_GVS_EngIdleActvPreCtrl(_EMS_GVS_EngIdleActvPreCtrl),EMS_GVS_EngClthDragTorq(_EMS_GVS_EngClthDragTorq),EMS_GVS_EngClthDragTorqVD(_EMS_GVS_EngClthDragTorqVD),EMS_GVS_FRErrReact(_EMS_GVS_FRErrReact),EMS_GVS_FaultrankSig(_EMS_GVS_FaultrankSig),EMS_GVS_MassFlwThrAirDesWoHcu(_EMS_GVS_MassFlwThrAirDesWoHcu),EMS_GVS_MassFlwThrAirUGD(_EMS_GVS_MassFlwThrAirUGD),EMS_GVS_PwtLosTorq(_EMS_GVS_PwtLosTorq),EMS_GVS_PwtLosTorqVD(_EMS_GVS_PwtLosTorqVD),EMS_GVS_PTGrip(_EMS_GVS_PTGrip),EMS_GVS_SftyFulCutOff(_EMS_GVS_SftyFulCutOff),EMS_GVS_ThtlBackUpModActv(_EMS_GVS_ThtlBackUpModActv),EMS_GVS_TrqCrepEngPrcssVD(_EMS_GVS_TrqCrepEngPrcssVD),EMS_GVS_TrqCrepEngPrcss(_EMS_GVS_TrqCrepEngPrcss),EMS_GVS_trnGearRatio(_EMS_GVS_trnGearRatio),EMS_GVS_VlFlwEngFuelInj(_EMS_GVS_VlFlwEngFuelInj),EMS_GVS_ACClgDemReq(_EMS_GVS_ACClgDemReq),EMS_GVS_CmprEnabl(_EMS_GVS_CmprEnabl),EMS_GVS_ThrVlvSensErr(_EMS_GVS_ThrVlvSensErr),EMS_CompressorSt(_EMS_CompressorSt),EMS_GVS_CoolFanDutyCycleReq(_EMS_GVS_CoolFanDutyCycleReq),EMS_GVS_CoolFanDutyCycleReqVD(_EMS_GVS_CoolFanDutyCycleReqVD),EMS_GVS_AccPedalPst(_EMS_GVS_AccPedalPst),EMS_GVS_AccPedalPstVD(_EMS_GVS_AccPedalPstVD),EMS_GVS_AccPedalPstProtValue(_EMS_GVS_AccPedalPstProtValue),EMS_GVS_EngSpd10msVD(_EMS_GVS_EngSpd10msVD),EMS_GVS_EngSpd10ms(_EMS_GVS_EngSpd10ms),EMS_GVS_EMSSubSt(_EMS_GVS_EMSSubSt),EMS_GVS_FuelPressureReleaseStDis(_EMS_GVS_FuelPressureReleaseStDis),EMS_GVS_KL15St(_EMS_GVS_KL15St),EMS_GVS_FuelCapLockReq(_EMS_GVS_FuelCapLockReq),EMS_GVS_FuelCapUnLockReq(_EMS_GVS_FuelCapUnLockReq),EMS_GVS_BrkPlausChkErr(_EMS_GVS_BrkPlausChkErr),EMS_GVS_AccPedalErr(_EMS_GVS_AccPedalErr),EMS_GVS_CCConfg(_EMS_GVS_CCConfg),EMS_GVS_ACCConfg(_EMS_GVS_ACCConfg),EMS_GVS_EngOffTimeCt(_EMS_GVS_EngOffTimeCt) {}
	BDCTestGVS(const BDCTestGVS &_x){
		BSGChrgTorq = _x.BSGChrgTorq;
		CrpTorqReq = _x.CrpTorqReq;
		MasFlwThrAirCtoffDes = _x.MasFlwThrAirCtoffDes;
		TcuIdlSpdReq = _x.TcuIdlSpdReq;
		ThrCtrlActv = _x.ThrCtrlActv;
		TorqTraLos = _x.TorqTraLos;
		TraTOStReq = _x.TraTOStReq;
		VehSrvLmp = _x.VehSrvLmp;
		TorqPTRsvReq = _x.TorqPTRsvReq;
		IdlSpdWOTcuReq = _x.IdlSpdWOTcuReq;
		TorqDesAcs = _x.TorqDesAcs;
		RefuleSwSt = _x.RefuleSwSt;
		PWMFanDtyCylAct = _x.PWMFanDtyCylAct;
		EMS_GVS_CatHtgActv = _x.EMS_GVS_CatHtgActv;
		EMS_GVS_CatHtgReq = _x.EMS_GVS_CatHtgReq;
		EMS_GVS_CylFuelCutSt = _x.EMS_GVS_CylFuelCutSt;
		EMS_GVS_CnvsFacFmiToTorq = _x.EMS_GVS_CnvsFacFmiToTorq;
		EMS_GVS_DutyCylLamdaHtr = _x.EMS_GVS_DutyCylLamdaHtr;
		EMS_GVS_EngSpdFcoEna = _x.EMS_GVS_EngSpdFcoEna;
		EMS_GVS_EngSpdFcoOffs = _x.EMS_GVS_EngSpdFcoOffs;
		EMS_GVS_EngAutoStopEna = _x.EMS_GVS_EngAutoStopEna;
		EMS_GVS_EngLimpActv = _x.EMS_GVS_EngLimpActv;
		EMS_GVS_EngSpdFlCtIn = _x.EMS_GVS_EngSpdFlCtIn;
		EMS_GVS_EngOilEstmd = _x.EMS_GVS_EngOilEstmd;
		EMS_GVS_EngTempStrt = _x.EMS_GVS_EngTempStrt;
		EMS_GVS_EnvTemp = _x.EMS_GVS_EnvTemp;
		EMS_GVS_EngIdleGovTgtSlwTrqVD = _x.EMS_GVS_EngIdleGovTgtSlwTrqVD;
		EMS_GVS_EngIdleGovTgtSlwTrq = _x.EMS_GVS_EngIdleGovTgtSlwTrq;
		EMS_GVS_EngIdleGovTgtFstTrq = _x.EMS_GVS_EngIdleGovTgtFstTrq;
		EMS_GVS_EngIdleGovTgtFstTrqVD = _x.EMS_GVS_EngIdleGovTgtFstTrqVD;
		EMS_GVS_EngClthMaxSlwTrq = _x.EMS_GVS_EngClthMaxSlwTrq;
		EMS_GVS_EngClthMaxSlwTrqVD = _x.EMS_GVS_EngClthMaxSlwTrqVD;
		EMS_GVS_EngClthMaxFstTrqVD = _x.EMS_GVS_EngClthMaxFstTrqVD;
		EMS_GVS_EngClthMaxFstTrq = _x.EMS_GVS_EngClthMaxFstTrq;
		EMS_GVS_EngAccFricTrqWOM = _x.EMS_GVS_EngAccFricTrqWOM;
		EMS_GVS_EngStrtTime = _x.EMS_GVS_EngStrtTime;
		EMS_GVS_EngIdleRefSpdWoTCU = _x.EMS_GVS_EngIdleRefSpdWoTCU;
		EMS_GVS_EngIdleActvPreCtrl = _x.EMS_GVS_EngIdleActvPreCtrl;
		EMS_GVS_EngClthDragTorq = _x.EMS_GVS_EngClthDragTorq;
		EMS_GVS_EngClthDragTorqVD = _x.EMS_GVS_EngClthDragTorqVD;
		EMS_GVS_FRErrReact = _x.EMS_GVS_FRErrReact;
		EMS_GVS_FaultrankSig = _x.EMS_GVS_FaultrankSig;
		EMS_GVS_MassFlwThrAirDesWoHcu = _x.EMS_GVS_MassFlwThrAirDesWoHcu;
		EMS_GVS_MassFlwThrAirUGD = _x.EMS_GVS_MassFlwThrAirUGD;
		EMS_GVS_PwtLosTorq = _x.EMS_GVS_PwtLosTorq;
		EMS_GVS_PwtLosTorqVD = _x.EMS_GVS_PwtLosTorqVD;
		EMS_GVS_PTGrip = _x.EMS_GVS_PTGrip;
		EMS_GVS_SftyFulCutOff = _x.EMS_GVS_SftyFulCutOff;
		EMS_GVS_ThtlBackUpModActv = _x.EMS_GVS_ThtlBackUpModActv;
		EMS_GVS_TrqCrepEngPrcssVD = _x.EMS_GVS_TrqCrepEngPrcssVD;
		EMS_GVS_TrqCrepEngPrcss = _x.EMS_GVS_TrqCrepEngPrcss;
		EMS_GVS_trnGearRatio = _x.EMS_GVS_trnGearRatio;
		EMS_GVS_VlFlwEngFuelInj = _x.EMS_GVS_VlFlwEngFuelInj;
		EMS_GVS_ACClgDemReq = _x.EMS_GVS_ACClgDemReq;
		EMS_GVS_CmprEnabl = _x.EMS_GVS_CmprEnabl;
		EMS_GVS_ThrVlvSensErr = _x.EMS_GVS_ThrVlvSensErr;
		EMS_CompressorSt = _x.EMS_CompressorSt;
		EMS_GVS_CoolFanDutyCycleReq = _x.EMS_GVS_CoolFanDutyCycleReq;
		EMS_GVS_CoolFanDutyCycleReqVD = _x.EMS_GVS_CoolFanDutyCycleReqVD;
		EMS_GVS_AccPedalPst = _x.EMS_GVS_AccPedalPst;
		EMS_GVS_AccPedalPstVD = _x.EMS_GVS_AccPedalPstVD;
		EMS_GVS_AccPedalPstProtValue = _x.EMS_GVS_AccPedalPstProtValue;
		EMS_GVS_EngSpd10msVD = _x.EMS_GVS_EngSpd10msVD;
		EMS_GVS_EngSpd10ms = _x.EMS_GVS_EngSpd10ms;
		EMS_GVS_EMSSubSt = _x.EMS_GVS_EMSSubSt;
		EMS_GVS_FuelPressureReleaseStDis = _x.EMS_GVS_FuelPressureReleaseStDis;
		EMS_GVS_KL15St = _x.EMS_GVS_KL15St;
		EMS_GVS_FuelCapLockReq = _x.EMS_GVS_FuelCapLockReq;
		EMS_GVS_FuelCapUnLockReq = _x.EMS_GVS_FuelCapUnLockReq;
		EMS_GVS_BrkPlausChkErr = _x.EMS_GVS_BrkPlausChkErr;
		EMS_GVS_AccPedalErr = _x.EMS_GVS_AccPedalErr;
		EMS_GVS_CCConfg = _x.EMS_GVS_CCConfg;
		EMS_GVS_ACCConfg = _x.EMS_GVS_ACCConfg;
		EMS_GVS_EngOffTimeCt = _x.EMS_GVS_EngOffTimeCt;
	}
	BDCTestGVS(BDCTestGVS &&_x){
		BSGChrgTorq = std::move(_x.BSGChrgTorq);
		CrpTorqReq = std::move(_x.CrpTorqReq);
		MasFlwThrAirCtoffDes = std::move(_x.MasFlwThrAirCtoffDes);
		TcuIdlSpdReq = std::move(_x.TcuIdlSpdReq);
		ThrCtrlActv = std::move(_x.ThrCtrlActv);
		TorqTraLos = std::move(_x.TorqTraLos);
		TraTOStReq = std::move(_x.TraTOStReq);
		VehSrvLmp = std::move(_x.VehSrvLmp);
		TorqPTRsvReq = std::move(_x.TorqPTRsvReq);
		IdlSpdWOTcuReq = std::move(_x.IdlSpdWOTcuReq);
		TorqDesAcs = std::move(_x.TorqDesAcs);
		RefuleSwSt = std::move(_x.RefuleSwSt);
		PWMFanDtyCylAct = std::move(_x.PWMFanDtyCylAct);
		EMS_GVS_CatHtgActv = std::move(_x.EMS_GVS_CatHtgActv);
		EMS_GVS_CatHtgReq = std::move(_x.EMS_GVS_CatHtgReq);
		EMS_GVS_CylFuelCutSt = std::move(_x.EMS_GVS_CylFuelCutSt);
		EMS_GVS_CnvsFacFmiToTorq = std::move(_x.EMS_GVS_CnvsFacFmiToTorq);
		EMS_GVS_DutyCylLamdaHtr = std::move(_x.EMS_GVS_DutyCylLamdaHtr);
		EMS_GVS_EngSpdFcoEna = std::move(_x.EMS_GVS_EngSpdFcoEna);
		EMS_GVS_EngSpdFcoOffs = std::move(_x.EMS_GVS_EngSpdFcoOffs);
		EMS_GVS_EngAutoStopEna = std::move(_x.EMS_GVS_EngAutoStopEna);
		EMS_GVS_EngLimpActv = std::move(_x.EMS_GVS_EngLimpActv);
		EMS_GVS_EngSpdFlCtIn = std::move(_x.EMS_GVS_EngSpdFlCtIn);
		EMS_GVS_EngOilEstmd = std::move(_x.EMS_GVS_EngOilEstmd);
		EMS_GVS_EngTempStrt = std::move(_x.EMS_GVS_EngTempStrt);
		EMS_GVS_EnvTemp = std::move(_x.EMS_GVS_EnvTemp);
		EMS_GVS_EngIdleGovTgtSlwTrqVD = std::move(_x.EMS_GVS_EngIdleGovTgtSlwTrqVD);
		EMS_GVS_EngIdleGovTgtSlwTrq = std::move(_x.EMS_GVS_EngIdleGovTgtSlwTrq);
		EMS_GVS_EngIdleGovTgtFstTrq = std::move(_x.EMS_GVS_EngIdleGovTgtFstTrq);
		EMS_GVS_EngIdleGovTgtFstTrqVD = std::move(_x.EMS_GVS_EngIdleGovTgtFstTrqVD);
		EMS_GVS_EngClthMaxSlwTrq = std::move(_x.EMS_GVS_EngClthMaxSlwTrq);
		EMS_GVS_EngClthMaxSlwTrqVD = std::move(_x.EMS_GVS_EngClthMaxSlwTrqVD);
		EMS_GVS_EngClthMaxFstTrqVD = std::move(_x.EMS_GVS_EngClthMaxFstTrqVD);
		EMS_GVS_EngClthMaxFstTrq = std::move(_x.EMS_GVS_EngClthMaxFstTrq);
		EMS_GVS_EngAccFricTrqWOM = std::move(_x.EMS_GVS_EngAccFricTrqWOM);
		EMS_GVS_EngStrtTime = std::move(_x.EMS_GVS_EngStrtTime);
		EMS_GVS_EngIdleRefSpdWoTCU = std::move(_x.EMS_GVS_EngIdleRefSpdWoTCU);
		EMS_GVS_EngIdleActvPreCtrl = std::move(_x.EMS_GVS_EngIdleActvPreCtrl);
		EMS_GVS_EngClthDragTorq = std::move(_x.EMS_GVS_EngClthDragTorq);
		EMS_GVS_EngClthDragTorqVD = std::move(_x.EMS_GVS_EngClthDragTorqVD);
		EMS_GVS_FRErrReact = std::move(_x.EMS_GVS_FRErrReact);
		EMS_GVS_FaultrankSig = std::move(_x.EMS_GVS_FaultrankSig);
		EMS_GVS_MassFlwThrAirDesWoHcu = std::move(_x.EMS_GVS_MassFlwThrAirDesWoHcu);
		EMS_GVS_MassFlwThrAirUGD = std::move(_x.EMS_GVS_MassFlwThrAirUGD);
		EMS_GVS_PwtLosTorq = std::move(_x.EMS_GVS_PwtLosTorq);
		EMS_GVS_PwtLosTorqVD = std::move(_x.EMS_GVS_PwtLosTorqVD);
		EMS_GVS_PTGrip = std::move(_x.EMS_GVS_PTGrip);
		EMS_GVS_SftyFulCutOff = std::move(_x.EMS_GVS_SftyFulCutOff);
		EMS_GVS_ThtlBackUpModActv = std::move(_x.EMS_GVS_ThtlBackUpModActv);
		EMS_GVS_TrqCrepEngPrcssVD = std::move(_x.EMS_GVS_TrqCrepEngPrcssVD);
		EMS_GVS_TrqCrepEngPrcss = std::move(_x.EMS_GVS_TrqCrepEngPrcss);
		EMS_GVS_trnGearRatio = std::move(_x.EMS_GVS_trnGearRatio);
		EMS_GVS_VlFlwEngFuelInj = std::move(_x.EMS_GVS_VlFlwEngFuelInj);
		EMS_GVS_ACClgDemReq = std::move(_x.EMS_GVS_ACClgDemReq);
		EMS_GVS_CmprEnabl = std::move(_x.EMS_GVS_CmprEnabl);
		EMS_GVS_ThrVlvSensErr = std::move(_x.EMS_GVS_ThrVlvSensErr);
		EMS_CompressorSt = std::move(_x.EMS_CompressorSt);
		EMS_GVS_CoolFanDutyCycleReq = std::move(_x.EMS_GVS_CoolFanDutyCycleReq);
		EMS_GVS_CoolFanDutyCycleReqVD = std::move(_x.EMS_GVS_CoolFanDutyCycleReqVD);
		EMS_GVS_AccPedalPst = std::move(_x.EMS_GVS_AccPedalPst);
		EMS_GVS_AccPedalPstVD = std::move(_x.EMS_GVS_AccPedalPstVD);
		EMS_GVS_AccPedalPstProtValue = std::move(_x.EMS_GVS_AccPedalPstProtValue);
		EMS_GVS_EngSpd10msVD = std::move(_x.EMS_GVS_EngSpd10msVD);
		EMS_GVS_EngSpd10ms = std::move(_x.EMS_GVS_EngSpd10ms);
		EMS_GVS_EMSSubSt = std::move(_x.EMS_GVS_EMSSubSt);
		EMS_GVS_FuelPressureReleaseStDis = std::move(_x.EMS_GVS_FuelPressureReleaseStDis);
		EMS_GVS_KL15St = std::move(_x.EMS_GVS_KL15St);
		EMS_GVS_FuelCapLockReq = std::move(_x.EMS_GVS_FuelCapLockReq);
		EMS_GVS_FuelCapUnLockReq = std::move(_x.EMS_GVS_FuelCapUnLockReq);
		EMS_GVS_BrkPlausChkErr = std::move(_x.EMS_GVS_BrkPlausChkErr);
		EMS_GVS_AccPedalErr = std::move(_x.EMS_GVS_AccPedalErr);
		EMS_GVS_CCConfg = std::move(_x.EMS_GVS_CCConfg);
		EMS_GVS_ACCConfg = std::move(_x.EMS_GVS_ACCConfg);
		EMS_GVS_EngOffTimeCt = std::move(_x.EMS_GVS_EngOffTimeCt);
	}
	BDCTestGVS& operator=(const BDCTestGVS &_x){
		BSGChrgTorq = _x.BSGChrgTorq;
		CrpTorqReq = _x.CrpTorqReq;
		MasFlwThrAirCtoffDes = _x.MasFlwThrAirCtoffDes;
		TcuIdlSpdReq = _x.TcuIdlSpdReq;
		ThrCtrlActv = _x.ThrCtrlActv;
		TorqTraLos = _x.TorqTraLos;
		TraTOStReq = _x.TraTOStReq;
		VehSrvLmp = _x.VehSrvLmp;
		TorqPTRsvReq = _x.TorqPTRsvReq;
		IdlSpdWOTcuReq = _x.IdlSpdWOTcuReq;
		TorqDesAcs = _x.TorqDesAcs;
		RefuleSwSt = _x.RefuleSwSt;
		PWMFanDtyCylAct = _x.PWMFanDtyCylAct;
		EMS_GVS_CatHtgActv = _x.EMS_GVS_CatHtgActv;
		EMS_GVS_CatHtgReq = _x.EMS_GVS_CatHtgReq;
		EMS_GVS_CylFuelCutSt = _x.EMS_GVS_CylFuelCutSt;
		EMS_GVS_CnvsFacFmiToTorq = _x.EMS_GVS_CnvsFacFmiToTorq;
		EMS_GVS_DutyCylLamdaHtr = _x.EMS_GVS_DutyCylLamdaHtr;
		EMS_GVS_EngSpdFcoEna = _x.EMS_GVS_EngSpdFcoEna;
		EMS_GVS_EngSpdFcoOffs = _x.EMS_GVS_EngSpdFcoOffs;
		EMS_GVS_EngAutoStopEna = _x.EMS_GVS_EngAutoStopEna;
		EMS_GVS_EngLimpActv = _x.EMS_GVS_EngLimpActv;
		EMS_GVS_EngSpdFlCtIn = _x.EMS_GVS_EngSpdFlCtIn;
		EMS_GVS_EngOilEstmd = _x.EMS_GVS_EngOilEstmd;
		EMS_GVS_EngTempStrt = _x.EMS_GVS_EngTempStrt;
		EMS_GVS_EnvTemp = _x.EMS_GVS_EnvTemp;
		EMS_GVS_EngIdleGovTgtSlwTrqVD = _x.EMS_GVS_EngIdleGovTgtSlwTrqVD;
		EMS_GVS_EngIdleGovTgtSlwTrq = _x.EMS_GVS_EngIdleGovTgtSlwTrq;
		EMS_GVS_EngIdleGovTgtFstTrq = _x.EMS_GVS_EngIdleGovTgtFstTrq;
		EMS_GVS_EngIdleGovTgtFstTrqVD = _x.EMS_GVS_EngIdleGovTgtFstTrqVD;
		EMS_GVS_EngClthMaxSlwTrq = _x.EMS_GVS_EngClthMaxSlwTrq;
		EMS_GVS_EngClthMaxSlwTrqVD = _x.EMS_GVS_EngClthMaxSlwTrqVD;
		EMS_GVS_EngClthMaxFstTrqVD = _x.EMS_GVS_EngClthMaxFstTrqVD;
		EMS_GVS_EngClthMaxFstTrq = _x.EMS_GVS_EngClthMaxFstTrq;
		EMS_GVS_EngAccFricTrqWOM = _x.EMS_GVS_EngAccFricTrqWOM;
		EMS_GVS_EngStrtTime = _x.EMS_GVS_EngStrtTime;
		EMS_GVS_EngIdleRefSpdWoTCU = _x.EMS_GVS_EngIdleRefSpdWoTCU;
		EMS_GVS_EngIdleActvPreCtrl = _x.EMS_GVS_EngIdleActvPreCtrl;
		EMS_GVS_EngClthDragTorq = _x.EMS_GVS_EngClthDragTorq;
		EMS_GVS_EngClthDragTorqVD = _x.EMS_GVS_EngClthDragTorqVD;
		EMS_GVS_FRErrReact = _x.EMS_GVS_FRErrReact;
		EMS_GVS_FaultrankSig = _x.EMS_GVS_FaultrankSig;
		EMS_GVS_MassFlwThrAirDesWoHcu = _x.EMS_GVS_MassFlwThrAirDesWoHcu;
		EMS_GVS_MassFlwThrAirUGD = _x.EMS_GVS_MassFlwThrAirUGD;
		EMS_GVS_PwtLosTorq = _x.EMS_GVS_PwtLosTorq;
		EMS_GVS_PwtLosTorqVD = _x.EMS_GVS_PwtLosTorqVD;
		EMS_GVS_PTGrip = _x.EMS_GVS_PTGrip;
		EMS_GVS_SftyFulCutOff = _x.EMS_GVS_SftyFulCutOff;
		EMS_GVS_ThtlBackUpModActv = _x.EMS_GVS_ThtlBackUpModActv;
		EMS_GVS_TrqCrepEngPrcssVD = _x.EMS_GVS_TrqCrepEngPrcssVD;
		EMS_GVS_TrqCrepEngPrcss = _x.EMS_GVS_TrqCrepEngPrcss;
		EMS_GVS_trnGearRatio = _x.EMS_GVS_trnGearRatio;
		EMS_GVS_VlFlwEngFuelInj = _x.EMS_GVS_VlFlwEngFuelInj;
		EMS_GVS_ACClgDemReq = _x.EMS_GVS_ACClgDemReq;
		EMS_GVS_CmprEnabl = _x.EMS_GVS_CmprEnabl;
		EMS_GVS_ThrVlvSensErr = _x.EMS_GVS_ThrVlvSensErr;
		EMS_CompressorSt = _x.EMS_CompressorSt;
		EMS_GVS_CoolFanDutyCycleReq = _x.EMS_GVS_CoolFanDutyCycleReq;
		EMS_GVS_CoolFanDutyCycleReqVD = _x.EMS_GVS_CoolFanDutyCycleReqVD;
		EMS_GVS_AccPedalPst = _x.EMS_GVS_AccPedalPst;
		EMS_GVS_AccPedalPstVD = _x.EMS_GVS_AccPedalPstVD;
		EMS_GVS_AccPedalPstProtValue = _x.EMS_GVS_AccPedalPstProtValue;
		EMS_GVS_EngSpd10msVD = _x.EMS_GVS_EngSpd10msVD;
		EMS_GVS_EngSpd10ms = _x.EMS_GVS_EngSpd10ms;
		EMS_GVS_EMSSubSt = _x.EMS_GVS_EMSSubSt;
		EMS_GVS_FuelPressureReleaseStDis = _x.EMS_GVS_FuelPressureReleaseStDis;
		EMS_GVS_KL15St = _x.EMS_GVS_KL15St;
		EMS_GVS_FuelCapLockReq = _x.EMS_GVS_FuelCapLockReq;
		EMS_GVS_FuelCapUnLockReq = _x.EMS_GVS_FuelCapUnLockReq;
		EMS_GVS_BrkPlausChkErr = _x.EMS_GVS_BrkPlausChkErr;
		EMS_GVS_AccPedalErr = _x.EMS_GVS_AccPedalErr;
		EMS_GVS_CCConfg = _x.EMS_GVS_CCConfg;
		EMS_GVS_ACCConfg = _x.EMS_GVS_ACCConfg;
		EMS_GVS_EngOffTimeCt = _x.EMS_GVS_EngOffTimeCt;
		return *this;
	}
	BDCTestGVS& operator=(BDCTestGVS &&_x){
		BSGChrgTorq = std::move(_x.BSGChrgTorq);
		CrpTorqReq = std::move(_x.CrpTorqReq);
		MasFlwThrAirCtoffDes = std::move(_x.MasFlwThrAirCtoffDes);
		TcuIdlSpdReq = std::move(_x.TcuIdlSpdReq);
		ThrCtrlActv = std::move(_x.ThrCtrlActv);
		TorqTraLos = std::move(_x.TorqTraLos);
		TraTOStReq = std::move(_x.TraTOStReq);
		VehSrvLmp = std::move(_x.VehSrvLmp);
		TorqPTRsvReq = std::move(_x.TorqPTRsvReq);
		IdlSpdWOTcuReq = std::move(_x.IdlSpdWOTcuReq);
		TorqDesAcs = std::move(_x.TorqDesAcs);
		RefuleSwSt = std::move(_x.RefuleSwSt);
		PWMFanDtyCylAct = std::move(_x.PWMFanDtyCylAct);
		EMS_GVS_CatHtgActv = std::move(_x.EMS_GVS_CatHtgActv);
		EMS_GVS_CatHtgReq = std::move(_x.EMS_GVS_CatHtgReq);
		EMS_GVS_CylFuelCutSt = std::move(_x.EMS_GVS_CylFuelCutSt);
		EMS_GVS_CnvsFacFmiToTorq = std::move(_x.EMS_GVS_CnvsFacFmiToTorq);
		EMS_GVS_DutyCylLamdaHtr = std::move(_x.EMS_GVS_DutyCylLamdaHtr);
		EMS_GVS_EngSpdFcoEna = std::move(_x.EMS_GVS_EngSpdFcoEna);
		EMS_GVS_EngSpdFcoOffs = std::move(_x.EMS_GVS_EngSpdFcoOffs);
		EMS_GVS_EngAutoStopEna = std::move(_x.EMS_GVS_EngAutoStopEna);
		EMS_GVS_EngLimpActv = std::move(_x.EMS_GVS_EngLimpActv);
		EMS_GVS_EngSpdFlCtIn = std::move(_x.EMS_GVS_EngSpdFlCtIn);
		EMS_GVS_EngOilEstmd = std::move(_x.EMS_GVS_EngOilEstmd);
		EMS_GVS_EngTempStrt = std::move(_x.EMS_GVS_EngTempStrt);
		EMS_GVS_EnvTemp = std::move(_x.EMS_GVS_EnvTemp);
		EMS_GVS_EngIdleGovTgtSlwTrqVD = std::move(_x.EMS_GVS_EngIdleGovTgtSlwTrqVD);
		EMS_GVS_EngIdleGovTgtSlwTrq = std::move(_x.EMS_GVS_EngIdleGovTgtSlwTrq);
		EMS_GVS_EngIdleGovTgtFstTrq = std::move(_x.EMS_GVS_EngIdleGovTgtFstTrq);
		EMS_GVS_EngIdleGovTgtFstTrqVD = std::move(_x.EMS_GVS_EngIdleGovTgtFstTrqVD);
		EMS_GVS_EngClthMaxSlwTrq = std::move(_x.EMS_GVS_EngClthMaxSlwTrq);
		EMS_GVS_EngClthMaxSlwTrqVD = std::move(_x.EMS_GVS_EngClthMaxSlwTrqVD);
		EMS_GVS_EngClthMaxFstTrqVD = std::move(_x.EMS_GVS_EngClthMaxFstTrqVD);
		EMS_GVS_EngClthMaxFstTrq = std::move(_x.EMS_GVS_EngClthMaxFstTrq);
		EMS_GVS_EngAccFricTrqWOM = std::move(_x.EMS_GVS_EngAccFricTrqWOM);
		EMS_GVS_EngStrtTime = std::move(_x.EMS_GVS_EngStrtTime);
		EMS_GVS_EngIdleRefSpdWoTCU = std::move(_x.EMS_GVS_EngIdleRefSpdWoTCU);
		EMS_GVS_EngIdleActvPreCtrl = std::move(_x.EMS_GVS_EngIdleActvPreCtrl);
		EMS_GVS_EngClthDragTorq = std::move(_x.EMS_GVS_EngClthDragTorq);
		EMS_GVS_EngClthDragTorqVD = std::move(_x.EMS_GVS_EngClthDragTorqVD);
		EMS_GVS_FRErrReact = std::move(_x.EMS_GVS_FRErrReact);
		EMS_GVS_FaultrankSig = std::move(_x.EMS_GVS_FaultrankSig);
		EMS_GVS_MassFlwThrAirDesWoHcu = std::move(_x.EMS_GVS_MassFlwThrAirDesWoHcu);
		EMS_GVS_MassFlwThrAirUGD = std::move(_x.EMS_GVS_MassFlwThrAirUGD);
		EMS_GVS_PwtLosTorq = std::move(_x.EMS_GVS_PwtLosTorq);
		EMS_GVS_PwtLosTorqVD = std::move(_x.EMS_GVS_PwtLosTorqVD);
		EMS_GVS_PTGrip = std::move(_x.EMS_GVS_PTGrip);
		EMS_GVS_SftyFulCutOff = std::move(_x.EMS_GVS_SftyFulCutOff);
		EMS_GVS_ThtlBackUpModActv = std::move(_x.EMS_GVS_ThtlBackUpModActv);
		EMS_GVS_TrqCrepEngPrcssVD = std::move(_x.EMS_GVS_TrqCrepEngPrcssVD);
		EMS_GVS_TrqCrepEngPrcss = std::move(_x.EMS_GVS_TrqCrepEngPrcss);
		EMS_GVS_trnGearRatio = std::move(_x.EMS_GVS_trnGearRatio);
		EMS_GVS_VlFlwEngFuelInj = std::move(_x.EMS_GVS_VlFlwEngFuelInj);
		EMS_GVS_ACClgDemReq = std::move(_x.EMS_GVS_ACClgDemReq);
		EMS_GVS_CmprEnabl = std::move(_x.EMS_GVS_CmprEnabl);
		EMS_GVS_ThrVlvSensErr = std::move(_x.EMS_GVS_ThrVlvSensErr);
		EMS_CompressorSt = std::move(_x.EMS_CompressorSt);
		EMS_GVS_CoolFanDutyCycleReq = std::move(_x.EMS_GVS_CoolFanDutyCycleReq);
		EMS_GVS_CoolFanDutyCycleReqVD = std::move(_x.EMS_GVS_CoolFanDutyCycleReqVD);
		EMS_GVS_AccPedalPst = std::move(_x.EMS_GVS_AccPedalPst);
		EMS_GVS_AccPedalPstVD = std::move(_x.EMS_GVS_AccPedalPstVD);
		EMS_GVS_AccPedalPstProtValue = std::move(_x.EMS_GVS_AccPedalPstProtValue);
		EMS_GVS_EngSpd10msVD = std::move(_x.EMS_GVS_EngSpd10msVD);
		EMS_GVS_EngSpd10ms = std::move(_x.EMS_GVS_EngSpd10ms);
		EMS_GVS_EMSSubSt = std::move(_x.EMS_GVS_EMSSubSt);
		EMS_GVS_FuelPressureReleaseStDis = std::move(_x.EMS_GVS_FuelPressureReleaseStDis);
		EMS_GVS_KL15St = std::move(_x.EMS_GVS_KL15St);
		EMS_GVS_FuelCapLockReq = std::move(_x.EMS_GVS_FuelCapLockReq);
		EMS_GVS_FuelCapUnLockReq = std::move(_x.EMS_GVS_FuelCapUnLockReq);
		EMS_GVS_BrkPlausChkErr = std::move(_x.EMS_GVS_BrkPlausChkErr);
		EMS_GVS_AccPedalErr = std::move(_x.EMS_GVS_AccPedalErr);
		EMS_GVS_CCConfg = std::move(_x.EMS_GVS_CCConfg);
		EMS_GVS_ACCConfg = std::move(_x.EMS_GVS_ACCConfg);
		EMS_GVS_EngOffTimeCt = std::move(_x.EMS_GVS_EngOffTimeCt);
		return *this;
	}
*/

	using IsEnumerableTag = void;
	template<typename F>
	void enumerate(F& fun) {
		fun(BSGChrgTorq);
		fun(CrpTorqReq);
		fun(MasFlwThrAirCtoffDes);
		fun(TcuIdlSpdReq);
		fun(ThrCtrlActv);
		fun(TorqTraLos);
		fun(TraTOStReq);
		fun(VehSrvLmp);
		fun(TorqPTRsvReq);
		fun(IdlSpdWOTcuReq);
		fun(TorqDesAcs);
		fun(RefuleSwSt);
		fun(PWMFanDtyCylAct);
		fun(EMS_GVS_CatHtgActv);
		fun(EMS_GVS_CatHtgReq);
		fun(EMS_GVS_CylFuelCutSt);
		fun(EMS_GVS_CnvsFacFmiToTorq);
		fun(EMS_GVS_DutyCylLamdaHtr);
		fun(EMS_GVS_EngSpdFcoEna);
		fun(EMS_GVS_EngSpdFcoOffs);
		fun(EMS_GVS_EngAutoStopEna);
		fun(EMS_GVS_EngLimpActv);
		fun(EMS_GVS_EngSpdFlCtIn);
		fun(EMS_GVS_EngOilEstmd);
		fun(EMS_GVS_EngTempStrt);
		fun(EMS_GVS_EnvTemp);
		fun(EMS_GVS_EngIdleGovTgtSlwTrqVD);
		fun(EMS_GVS_EngIdleGovTgtSlwTrq);
		fun(EMS_GVS_EngIdleGovTgtFstTrq);
		fun(EMS_GVS_EngIdleGovTgtFstTrqVD);
		fun(EMS_GVS_EngClthMaxSlwTrq);
		fun(EMS_GVS_EngClthMaxSlwTrqVD);
		fun(EMS_GVS_EngClthMaxFstTrqVD);
		fun(EMS_GVS_EngClthMaxFstTrq);
		fun(EMS_GVS_EngAccFricTrqWOM);
		fun(EMS_GVS_EngStrtTime);
		fun(EMS_GVS_EngIdleRefSpdWoTCU);
		fun(EMS_GVS_EngIdleActvPreCtrl);
		fun(EMS_GVS_EngClthDragTorq);
		fun(EMS_GVS_EngClthDragTorqVD);
		fun(EMS_GVS_FRErrReact);
		fun(EMS_GVS_FaultrankSig);
		fun(EMS_GVS_MassFlwThrAirDesWoHcu);
		fun(EMS_GVS_MassFlwThrAirUGD);
		fun(EMS_GVS_PwtLosTorq);
		fun(EMS_GVS_PwtLosTorqVD);
		fun(EMS_GVS_PTGrip);
		fun(EMS_GVS_SftyFulCutOff);
		fun(EMS_GVS_ThtlBackUpModActv);
		fun(EMS_GVS_TrqCrepEngPrcssVD);
		fun(EMS_GVS_TrqCrepEngPrcss);
		fun(EMS_GVS_trnGearRatio);
		fun(EMS_GVS_VlFlwEngFuelInj);
		fun(EMS_GVS_ACClgDemReq);
		fun(EMS_GVS_CmprEnabl);
		fun(EMS_GVS_ThrVlvSensErr);
		fun(EMS_CompressorSt);
		fun(EMS_GVS_CoolFanDutyCycleReq);
		fun(EMS_GVS_CoolFanDutyCycleReqVD);
		fun(EMS_GVS_AccPedalPst);
		fun(EMS_GVS_AccPedalPstVD);
		fun(EMS_GVS_AccPedalPstProtValue);
		fun(EMS_GVS_EngSpd10msVD);
		fun(EMS_GVS_EngSpd10ms);
		fun(EMS_GVS_EMSSubSt);
		fun(EMS_GVS_FuelPressureReleaseStDis);
		fun(EMS_GVS_KL15St);
		fun(EMS_GVS_FuelCapLockReq);
		fun(EMS_GVS_FuelCapUnLockReq);
		fun(EMS_GVS_BrkPlausChkErr);
		fun(EMS_GVS_AccPedalErr);
		fun(EMS_GVS_CCConfg);
		fun(EMS_GVS_ACCConfg);
		fun(EMS_GVS_EngOffTimeCt);
	}

	template<typename F>
	void GetSize(F& fun) const{
		fun(BSGChrgTorq);
		fun(CrpTorqReq);
		fun(MasFlwThrAirCtoffDes);
		fun(TcuIdlSpdReq);
		fun(ThrCtrlActv);
		fun(TorqTraLos);
		fun(TraTOStReq);
		fun(VehSrvLmp);
		fun(TorqPTRsvReq);
		fun(IdlSpdWOTcuReq);
		fun(TorqDesAcs);
		fun(RefuleSwSt);
		fun(PWMFanDtyCylAct);
		fun(EMS_GVS_CatHtgActv);
		fun(EMS_GVS_CatHtgReq);
		fun(EMS_GVS_CylFuelCutSt);
		fun(EMS_GVS_CnvsFacFmiToTorq);
		fun(EMS_GVS_DutyCylLamdaHtr);
		fun(EMS_GVS_EngSpdFcoEna);
		fun(EMS_GVS_EngSpdFcoOffs);
		fun(EMS_GVS_EngAutoStopEna);
		fun(EMS_GVS_EngLimpActv);
		fun(EMS_GVS_EngSpdFlCtIn);
		fun(EMS_GVS_EngOilEstmd);
		fun(EMS_GVS_EngTempStrt);
		fun(EMS_GVS_EnvTemp);
		fun(EMS_GVS_EngIdleGovTgtSlwTrqVD);
		fun(EMS_GVS_EngIdleGovTgtSlwTrq);
		fun(EMS_GVS_EngIdleGovTgtFstTrq);
		fun(EMS_GVS_EngIdleGovTgtFstTrqVD);
		fun(EMS_GVS_EngClthMaxSlwTrq);
		fun(EMS_GVS_EngClthMaxSlwTrqVD);
		fun(EMS_GVS_EngClthMaxFstTrqVD);
		fun(EMS_GVS_EngClthMaxFstTrq);
		fun(EMS_GVS_EngAccFricTrqWOM);
		fun(EMS_GVS_EngStrtTime);
		fun(EMS_GVS_EngIdleRefSpdWoTCU);
		fun(EMS_GVS_EngIdleActvPreCtrl);
		fun(EMS_GVS_EngClthDragTorq);
		fun(EMS_GVS_EngClthDragTorqVD);
		fun(EMS_GVS_FRErrReact);
		fun(EMS_GVS_FaultrankSig);
		fun(EMS_GVS_MassFlwThrAirDesWoHcu);
		fun(EMS_GVS_MassFlwThrAirUGD);
		fun(EMS_GVS_PwtLosTorq);
		fun(EMS_GVS_PwtLosTorqVD);
		fun(EMS_GVS_PTGrip);
		fun(EMS_GVS_SftyFulCutOff);
		fun(EMS_GVS_ThtlBackUpModActv);
		fun(EMS_GVS_TrqCrepEngPrcssVD);
		fun(EMS_GVS_TrqCrepEngPrcss);
		fun(EMS_GVS_trnGearRatio);
		fun(EMS_GVS_VlFlwEngFuelInj);
		fun(EMS_GVS_ACClgDemReq);
		fun(EMS_GVS_CmprEnabl);
		fun(EMS_GVS_ThrVlvSensErr);
		fun(EMS_CompressorSt);
		fun(EMS_GVS_CoolFanDutyCycleReq);
		fun(EMS_GVS_CoolFanDutyCycleReqVD);
		fun(EMS_GVS_AccPedalPst);
		fun(EMS_GVS_AccPedalPstVD);
		fun(EMS_GVS_AccPedalPstProtValue);
		fun(EMS_GVS_EngSpd10msVD);
		fun(EMS_GVS_EngSpd10ms);
		fun(EMS_GVS_EMSSubSt);
		fun(EMS_GVS_FuelPressureReleaseStDis);
		fun(EMS_GVS_KL15St);
		fun(EMS_GVS_FuelCapLockReq);
		fun(EMS_GVS_FuelCapUnLockReq);
		fun(EMS_GVS_BrkPlausChkErr);
		fun(EMS_GVS_AccPedalErr);
		fun(EMS_GVS_CCConfg);
		fun(EMS_GVS_ACCConfg);
		fun(EMS_GVS_EngOffTimeCt);
	}
	template<typename F>
	void serialize(F& fun) const{
		fun << (BSGChrgTorq);
		fun << (CrpTorqReq);
		fun << (MasFlwThrAirCtoffDes);
		fun << (TcuIdlSpdReq);
		fun << (ThrCtrlActv);
		fun << (TorqTraLos);
		fun << (TraTOStReq);
		fun << (VehSrvLmp);
		fun << (TorqPTRsvReq);
		fun << (IdlSpdWOTcuReq);
		fun << (TorqDesAcs);
		fun << (RefuleSwSt);
		fun << (PWMFanDtyCylAct);
		fun << (EMS_GVS_CatHtgActv);
		fun << (EMS_GVS_CatHtgReq);
		fun << (EMS_GVS_CylFuelCutSt);
		fun << (EMS_GVS_CnvsFacFmiToTorq);
		fun << (EMS_GVS_DutyCylLamdaHtr);
		fun << (EMS_GVS_EngSpdFcoEna);
		fun << (EMS_GVS_EngSpdFcoOffs);
		fun << (EMS_GVS_EngAutoStopEna);
		fun << (EMS_GVS_EngLimpActv);
		fun << (EMS_GVS_EngSpdFlCtIn);
		fun << (EMS_GVS_EngOilEstmd);
		fun << (EMS_GVS_EngTempStrt);
		fun << (EMS_GVS_EnvTemp);
		fun << (EMS_GVS_EngIdleGovTgtSlwTrqVD);
		fun << (EMS_GVS_EngIdleGovTgtSlwTrq);
		fun << (EMS_GVS_EngIdleGovTgtFstTrq);
		fun << (EMS_GVS_EngIdleGovTgtFstTrqVD);
		fun << (EMS_GVS_EngClthMaxSlwTrq);
		fun << (EMS_GVS_EngClthMaxSlwTrqVD);
		fun << (EMS_GVS_EngClthMaxFstTrqVD);
		fun << (EMS_GVS_EngClthMaxFstTrq);
		fun << (EMS_GVS_EngAccFricTrqWOM);
		fun << (EMS_GVS_EngStrtTime);
		fun << (EMS_GVS_EngIdleRefSpdWoTCU);
		fun << (EMS_GVS_EngIdleActvPreCtrl);
		fun << (EMS_GVS_EngClthDragTorq);
		fun << (EMS_GVS_EngClthDragTorqVD);
		fun << (EMS_GVS_FRErrReact);
		fun << (EMS_GVS_FaultrankSig);
		fun << (EMS_GVS_MassFlwThrAirDesWoHcu);
		fun << (EMS_GVS_MassFlwThrAirUGD);
		fun << (EMS_GVS_PwtLosTorq);
		fun << (EMS_GVS_PwtLosTorqVD);
		fun << (EMS_GVS_PTGrip);
		fun << (EMS_GVS_SftyFulCutOff);
		fun << (EMS_GVS_ThtlBackUpModActv);
		fun << (EMS_GVS_TrqCrepEngPrcssVD);
		fun << (EMS_GVS_TrqCrepEngPrcss);
		fun << (EMS_GVS_trnGearRatio);
		fun << (EMS_GVS_VlFlwEngFuelInj);
		fun << (EMS_GVS_ACClgDemReq);
		fun << (EMS_GVS_CmprEnabl);
		fun << (EMS_GVS_ThrVlvSensErr);
		fun << (EMS_CompressorSt);
		fun << (EMS_GVS_CoolFanDutyCycleReq);
		fun << (EMS_GVS_CoolFanDutyCycleReqVD);
		fun << (EMS_GVS_AccPedalPst);
		fun << (EMS_GVS_AccPedalPstVD);
		fun << (EMS_GVS_AccPedalPstProtValue);
		fun << (EMS_GVS_EngSpd10msVD);
		fun << (EMS_GVS_EngSpd10ms);
		fun << (EMS_GVS_EMSSubSt);
		fun << (EMS_GVS_FuelPressureReleaseStDis);
		fun << (EMS_GVS_KL15St);
		fun << (EMS_GVS_FuelCapLockReq);
		fun << (EMS_GVS_FuelCapUnLockReq);
		fun << (EMS_GVS_BrkPlausChkErr);
		fun << (EMS_GVS_AccPedalErr);
		fun << (EMS_GVS_CCConfg);
		fun << (EMS_GVS_ACCConfg);
		fun << (EMS_GVS_EngOffTimeCt);
	}
	template<typename F>
	void deserialize(F& fun){
		fun >> (BSGChrgTorq);
		fun >> (CrpTorqReq);
		fun >> (MasFlwThrAirCtoffDes);
		fun >> (TcuIdlSpdReq);
		fun >> (ThrCtrlActv);
		fun >> (TorqTraLos);
		fun >> (TraTOStReq);
		fun >> (VehSrvLmp);
		fun >> (TorqPTRsvReq);
		fun >> (IdlSpdWOTcuReq);
		fun >> (TorqDesAcs);
		fun >> (RefuleSwSt);
		fun >> (PWMFanDtyCylAct);
		fun >> (EMS_GVS_CatHtgActv);
		fun >> (EMS_GVS_CatHtgReq);
		fun >> (EMS_GVS_CylFuelCutSt);
		fun >> (EMS_GVS_CnvsFacFmiToTorq);
		fun >> (EMS_GVS_DutyCylLamdaHtr);
		fun >> (EMS_GVS_EngSpdFcoEna);
		fun >> (EMS_GVS_EngSpdFcoOffs);
		fun >> (EMS_GVS_EngAutoStopEna);
		fun >> (EMS_GVS_EngLimpActv);
		fun >> (EMS_GVS_EngSpdFlCtIn);
		fun >> (EMS_GVS_EngOilEstmd);
		fun >> (EMS_GVS_EngTempStrt);
		fun >> (EMS_GVS_EnvTemp);
		fun >> (EMS_GVS_EngIdleGovTgtSlwTrqVD);
		fun >> (EMS_GVS_EngIdleGovTgtSlwTrq);
		fun >> (EMS_GVS_EngIdleGovTgtFstTrq);
		fun >> (EMS_GVS_EngIdleGovTgtFstTrqVD);
		fun >> (EMS_GVS_EngClthMaxSlwTrq);
		fun >> (EMS_GVS_EngClthMaxSlwTrqVD);
		fun >> (EMS_GVS_EngClthMaxFstTrqVD);
		fun >> (EMS_GVS_EngClthMaxFstTrq);
		fun >> (EMS_GVS_EngAccFricTrqWOM);
		fun >> (EMS_GVS_EngStrtTime);
		fun >> (EMS_GVS_EngIdleRefSpdWoTCU);
		fun >> (EMS_GVS_EngIdleActvPreCtrl);
		fun >> (EMS_GVS_EngClthDragTorq);
		fun >> (EMS_GVS_EngClthDragTorqVD);
		fun >> (EMS_GVS_FRErrReact);
		fun >> (EMS_GVS_FaultrankSig);
		fun >> (EMS_GVS_MassFlwThrAirDesWoHcu);
		fun >> (EMS_GVS_MassFlwThrAirUGD);
		fun >> (EMS_GVS_PwtLosTorq);
		fun >> (EMS_GVS_PwtLosTorqVD);
		fun >> (EMS_GVS_PTGrip);
		fun >> (EMS_GVS_SftyFulCutOff);
		fun >> (EMS_GVS_ThtlBackUpModActv);
		fun >> (EMS_GVS_TrqCrepEngPrcssVD);
		fun >> (EMS_GVS_TrqCrepEngPrcss);
		fun >> (EMS_GVS_trnGearRatio);
		fun >> (EMS_GVS_VlFlwEngFuelInj);
		fun >> (EMS_GVS_ACClgDemReq);
		fun >> (EMS_GVS_CmprEnabl);
		fun >> (EMS_GVS_ThrVlvSensErr);
		fun >> (EMS_CompressorSt);
		fun >> (EMS_GVS_CoolFanDutyCycleReq);
		fun >> (EMS_GVS_CoolFanDutyCycleReqVD);
		fun >> (EMS_GVS_AccPedalPst);
		fun >> (EMS_GVS_AccPedalPstVD);
		fun >> (EMS_GVS_AccPedalPstProtValue);
		fun >> (EMS_GVS_EngSpd10msVD);
		fun >> (EMS_GVS_EngSpd10ms);
		fun >> (EMS_GVS_EMSSubSt);
		fun >> (EMS_GVS_FuelPressureReleaseStDis);
		fun >> (EMS_GVS_KL15St);
		fun >> (EMS_GVS_FuelCapLockReq);
		fun >> (EMS_GVS_FuelCapUnLockReq);
		fun >> (EMS_GVS_BrkPlausChkErr);
		fun >> (EMS_GVS_AccPedalErr);
		fun >> (EMS_GVS_CCConfg);
		fun >> (EMS_GVS_ACCConfg);
		fun >> (EMS_GVS_EngOffTimeCt);
	}
};

#endif //____BDCTESTGVS_H__
