#ifndef ____BDCTESTBMS4_H__
#define ____BDCTESTBMS4_H__


#include "cstdint"






struct BDCTestBMS4 {
public:
	std::uint16_t BMS_CellVoltNo1;
	std::uint16_t BMS_CellVoltNo2;
	std::uint16_t BMS_CellVoltNo3;
	std::uint16_t BMS_CellVoltNo4;
	std::uint16_t BMS_CellVoltNo5;
	std::uint16_t BMS_CellVoltNo6;
	std::uint16_t BMS_CellVoltNo7;
	std::uint16_t BMS_CellVoltNo8;
	std::uint16_t BMS_CellVoltNo9;
	std::uint16_t BMS_CellVoltNo10;
	std::uint16_t BMS_CellVoltNo11;
	std::uint16_t BMS_CellVoltNo12;
	std::uint16_t BMS_CellVoltNo13;
	std::uint16_t BMS_CellVoltNo14;
	std::uint16_t BMS_CellVoltNo15;
	std::uint16_t BMS_CellVoltNo16;
	std::uint16_t BMS_CellVoltNo17;
	std::uint16_t BMS_CellVoltNo18;
	std::uint16_t BMS_CellVoltNo19;
	std::uint16_t BMS_CellVoltNo20;
	std::uint16_t BMS_CellVoltNo21;
	std::uint16_t BMS_CellVoltNo22;
	std::uint16_t BMS_CellVoltNo23;
	std::uint16_t BMS_CellVoltNo24;
	std::uint16_t BMS_CellVoltNo25;
	std::uint16_t BMS_CellVoltNo26;
	std::uint16_t BMS_CellVoltNo27;
	std::uint16_t BMS_CellVoltNo28;
	std::uint16_t BMS_CellVoltNo29;
	std::uint16_t BMS_CellVoltNo30;
	std::uint16_t BMS_CellVoltNo31;
	std::uint16_t BMS_CellVoltNo32;
	std::uint16_t BMS_CellVoltNo33;
	std::uint16_t BMS_CellVoltNo34;
	std::uint16_t BMS_CellVoltNo35;
	std::uint16_t BMS_CellVoltNo36;
	std::uint16_t BMS_CellVoltNo37;
	std::uint16_t BMS_CellVoltNo38;
	std::uint16_t BMS_CellVoltNo39;
	std::uint16_t BMS_CellVoltNo40;
	std::uint16_t BMS_CellVoltNo41;
	std::uint16_t BMS_CellVoltNo42;
	std::uint16_t BMS_CellVoltNo43;
	std::uint16_t BMS_CellVoltNo44;
	std::uint16_t BMS_CellVoltNo45;
	std::uint16_t BMS_CellVoltNo46;
	std::uint16_t BMS_CellVoltNo47;
	std::uint16_t BMS_CellVoltNo48;
	std::uint16_t BMS_CellVoltNo49;
	std::uint16_t BMS_CellVoltNo50;
	std::uint16_t BMS_CellVoltNo51;
	std::uint16_t BMS_CellVoltNo52;
	std::uint16_t BMS_CellVoltNo53;
	std::uint16_t BMS_CellVoltNo54;
	std::uint16_t BMS_CellVoltNo55;
	std::uint16_t BMS_CellVoltNo56;
	std::uint16_t BMS_CellVoltNo57;
	std::uint16_t BMS_CellVoltNo58;
	std::uint16_t BMS_CellVoltNo59;
	std::uint16_t BMS_CellVoltNo60;
	std::uint16_t BMS_CellVoltNo61;
	std::uint16_t BMS_CellVoltNo62;
	std::uint16_t BMS_CellVoltNo63;
	std::uint16_t BMS_CellVoltNo64;
	std::uint16_t BMS_CellVoltNo65;
	std::uint16_t BMS_CellVoltNo66;
	std::uint16_t BMS_CellVoltNo67;
	std::uint16_t BMS_CellVoltNo68;
	std::uint16_t BMS_CellVoltNo69;
	std::uint16_t BMS_CellVoltNo70;
	std::uint16_t BMS_CellVoltNo71;
	std::uint16_t BMS_CellVoltNo72;
	std::uint16_t BMS_CellVoltNo73;
	std::uint16_t BMS_CellVoltNo74;
	std::uint16_t BMS_CellVoltNo75;
	std::uint16_t BMS_CellVoltNo76;
	std::uint16_t BMS_CellVoltNo77;
	std::uint16_t BMS_CellVoltNo78;
	std::uint16_t BMS_CellVoltNo79;
	std::uint16_t BMS_CellVoltNo80;
	std::uint16_t BMS_CellVoltNo81;
	std::uint16_t BMS_CellVoltNo82;
	std::uint16_t BMS_CellVoltNo83;
	std::uint16_t BMS_CellVoltNo84;
	std::uint16_t BMS_CellVoltNo85;
	std::uint16_t BMS_CellVoltNo86;
	std::uint16_t BMS_CellVoltNo87;
	std::uint16_t BMS_CellVoltNo88;
	std::uint16_t BMS_CellVoltNo89;
	std::uint16_t BMS_CellVoltNo90;
	std::uint16_t BMS_CellVoltNo91;
	std::uint16_t BMS_CellVoltNo92;
	std::uint16_t BMS_CellVoltNo93;
	std::uint16_t BMS_CellVoltNo94;
	std::uint16_t BMS_CellVoltNo95;
	std::uint16_t BMS_CellVoltNo96;
/*
	BDCTestBMS4() {}
	~BDCTestBMS4() {}
	BDCTestBMS4(const std::uint16_t _BMS_CellVoltNo1,const std::uint16_t _BMS_CellVoltNo2,const std::uint16_t _BMS_CellVoltNo3,const std::uint16_t _BMS_CellVoltNo4,const std::uint16_t _BMS_CellVoltNo5,const std::uint16_t _BMS_CellVoltNo6,const std::uint16_t _BMS_CellVoltNo7,const std::uint16_t _BMS_CellVoltNo8,const std::uint16_t _BMS_CellVoltNo9,const std::uint16_t _BMS_CellVoltNo10,const std::uint16_t _BMS_CellVoltNo11,const std::uint16_t _BMS_CellVoltNo12,const std::uint16_t _BMS_CellVoltNo13,const std::uint16_t _BMS_CellVoltNo14,const std::uint16_t _BMS_CellVoltNo15,const std::uint16_t _BMS_CellVoltNo16,const std::uint16_t _BMS_CellVoltNo17,const std::uint16_t _BMS_CellVoltNo18,const std::uint16_t _BMS_CellVoltNo19,const std::uint16_t _BMS_CellVoltNo20,const std::uint16_t _BMS_CellVoltNo21,const std::uint16_t _BMS_CellVoltNo22,const std::uint16_t _BMS_CellVoltNo23,const std::uint16_t _BMS_CellVoltNo24,const std::uint16_t _BMS_CellVoltNo25,const std::uint16_t _BMS_CellVoltNo26,const std::uint16_t _BMS_CellVoltNo27,const std::uint16_t _BMS_CellVoltNo28,const std::uint16_t _BMS_CellVoltNo29,const std::uint16_t _BMS_CellVoltNo30,const std::uint16_t _BMS_CellVoltNo31,const std::uint16_t _BMS_CellVoltNo32,const std::uint16_t _BMS_CellVoltNo33,const std::uint16_t _BMS_CellVoltNo34,const std::uint16_t _BMS_CellVoltNo35,const std::uint16_t _BMS_CellVoltNo36,const std::uint16_t _BMS_CellVoltNo37,const std::uint16_t _BMS_CellVoltNo38,const std::uint16_t _BMS_CellVoltNo39,const std::uint16_t _BMS_CellVoltNo40,const std::uint16_t _BMS_CellVoltNo41,const std::uint16_t _BMS_CellVoltNo42,const std::uint16_t _BMS_CellVoltNo43,const std::uint16_t _BMS_CellVoltNo44,const std::uint16_t _BMS_CellVoltNo45,const std::uint16_t _BMS_CellVoltNo46,const std::uint16_t _BMS_CellVoltNo47,const std::uint16_t _BMS_CellVoltNo48,const std::uint16_t _BMS_CellVoltNo49,const std::uint16_t _BMS_CellVoltNo50,const std::uint16_t _BMS_CellVoltNo51,const std::uint16_t _BMS_CellVoltNo52,const std::uint16_t _BMS_CellVoltNo53,const std::uint16_t _BMS_CellVoltNo54,const std::uint16_t _BMS_CellVoltNo55,const std::uint16_t _BMS_CellVoltNo56,const std::uint16_t _BMS_CellVoltNo57,const std::uint16_t _BMS_CellVoltNo58,const std::uint16_t _BMS_CellVoltNo59,const std::uint16_t _BMS_CellVoltNo60,const std::uint16_t _BMS_CellVoltNo61,const std::uint16_t _BMS_CellVoltNo62,const std::uint16_t _BMS_CellVoltNo63,const std::uint16_t _BMS_CellVoltNo64,const std::uint16_t _BMS_CellVoltNo65,const std::uint16_t _BMS_CellVoltNo66,const std::uint16_t _BMS_CellVoltNo67,const std::uint16_t _BMS_CellVoltNo68,const std::uint16_t _BMS_CellVoltNo69,const std::uint16_t _BMS_CellVoltNo70,const std::uint16_t _BMS_CellVoltNo71,const std::uint16_t _BMS_CellVoltNo72,const std::uint16_t _BMS_CellVoltNo73,const std::uint16_t _BMS_CellVoltNo74,const std::uint16_t _BMS_CellVoltNo75,const std::uint16_t _BMS_CellVoltNo76,const std::uint16_t _BMS_CellVoltNo77,const std::uint16_t _BMS_CellVoltNo78,const std::uint16_t _BMS_CellVoltNo79,const std::uint16_t _BMS_CellVoltNo80,const std::uint16_t _BMS_CellVoltNo81,const std::uint16_t _BMS_CellVoltNo82,const std::uint16_t _BMS_CellVoltNo83,const std::uint16_t _BMS_CellVoltNo84,const std::uint16_t _BMS_CellVoltNo85,const std::uint16_t _BMS_CellVoltNo86,const std::uint16_t _BMS_CellVoltNo87,const std::uint16_t _BMS_CellVoltNo88,const std::uint16_t _BMS_CellVoltNo89,const std::uint16_t _BMS_CellVoltNo90,const std::uint16_t _BMS_CellVoltNo91,const std::uint16_t _BMS_CellVoltNo92,const std::uint16_t _BMS_CellVoltNo93,const std::uint16_t _BMS_CellVoltNo94,const std::uint16_t _BMS_CellVoltNo95,const std::uint16_t _BMS_CellVoltNo96):BMS_CellVoltNo1(_BMS_CellVoltNo1),BMS_CellVoltNo2(_BMS_CellVoltNo2),BMS_CellVoltNo3(_BMS_CellVoltNo3),BMS_CellVoltNo4(_BMS_CellVoltNo4),BMS_CellVoltNo5(_BMS_CellVoltNo5),BMS_CellVoltNo6(_BMS_CellVoltNo6),BMS_CellVoltNo7(_BMS_CellVoltNo7),BMS_CellVoltNo8(_BMS_CellVoltNo8),BMS_CellVoltNo9(_BMS_CellVoltNo9),BMS_CellVoltNo10(_BMS_CellVoltNo10),BMS_CellVoltNo11(_BMS_CellVoltNo11),BMS_CellVoltNo12(_BMS_CellVoltNo12),BMS_CellVoltNo13(_BMS_CellVoltNo13),BMS_CellVoltNo14(_BMS_CellVoltNo14),BMS_CellVoltNo15(_BMS_CellVoltNo15),BMS_CellVoltNo16(_BMS_CellVoltNo16),BMS_CellVoltNo17(_BMS_CellVoltNo17),BMS_CellVoltNo18(_BMS_CellVoltNo18),BMS_CellVoltNo19(_BMS_CellVoltNo19),BMS_CellVoltNo20(_BMS_CellVoltNo20),BMS_CellVoltNo21(_BMS_CellVoltNo21),BMS_CellVoltNo22(_BMS_CellVoltNo22),BMS_CellVoltNo23(_BMS_CellVoltNo23),BMS_CellVoltNo24(_BMS_CellVoltNo24),BMS_CellVoltNo25(_BMS_CellVoltNo25),BMS_CellVoltNo26(_BMS_CellVoltNo26),BMS_CellVoltNo27(_BMS_CellVoltNo27),BMS_CellVoltNo28(_BMS_CellVoltNo28),BMS_CellVoltNo29(_BMS_CellVoltNo29),BMS_CellVoltNo30(_BMS_CellVoltNo30),BMS_CellVoltNo31(_BMS_CellVoltNo31),BMS_CellVoltNo32(_BMS_CellVoltNo32),BMS_CellVoltNo33(_BMS_CellVoltNo33),BMS_CellVoltNo34(_BMS_CellVoltNo34),BMS_CellVoltNo35(_BMS_CellVoltNo35),BMS_CellVoltNo36(_BMS_CellVoltNo36),BMS_CellVoltNo37(_BMS_CellVoltNo37),BMS_CellVoltNo38(_BMS_CellVoltNo38),BMS_CellVoltNo39(_BMS_CellVoltNo39),BMS_CellVoltNo40(_BMS_CellVoltNo40),BMS_CellVoltNo41(_BMS_CellVoltNo41),BMS_CellVoltNo42(_BMS_CellVoltNo42),BMS_CellVoltNo43(_BMS_CellVoltNo43),BMS_CellVoltNo44(_BMS_CellVoltNo44),BMS_CellVoltNo45(_BMS_CellVoltNo45),BMS_CellVoltNo46(_BMS_CellVoltNo46),BMS_CellVoltNo47(_BMS_CellVoltNo47),BMS_CellVoltNo48(_BMS_CellVoltNo48),BMS_CellVoltNo49(_BMS_CellVoltNo49),BMS_CellVoltNo50(_BMS_CellVoltNo50),BMS_CellVoltNo51(_BMS_CellVoltNo51),BMS_CellVoltNo52(_BMS_CellVoltNo52),BMS_CellVoltNo53(_BMS_CellVoltNo53),BMS_CellVoltNo54(_BMS_CellVoltNo54),BMS_CellVoltNo55(_BMS_CellVoltNo55),BMS_CellVoltNo56(_BMS_CellVoltNo56),BMS_CellVoltNo57(_BMS_CellVoltNo57),BMS_CellVoltNo58(_BMS_CellVoltNo58),BMS_CellVoltNo59(_BMS_CellVoltNo59),BMS_CellVoltNo60(_BMS_CellVoltNo60),BMS_CellVoltNo61(_BMS_CellVoltNo61),BMS_CellVoltNo62(_BMS_CellVoltNo62),BMS_CellVoltNo63(_BMS_CellVoltNo63),BMS_CellVoltNo64(_BMS_CellVoltNo64),BMS_CellVoltNo65(_BMS_CellVoltNo65),BMS_CellVoltNo66(_BMS_CellVoltNo66),BMS_CellVoltNo67(_BMS_CellVoltNo67),BMS_CellVoltNo68(_BMS_CellVoltNo68),BMS_CellVoltNo69(_BMS_CellVoltNo69),BMS_CellVoltNo70(_BMS_CellVoltNo70),BMS_CellVoltNo71(_BMS_CellVoltNo71),BMS_CellVoltNo72(_BMS_CellVoltNo72),BMS_CellVoltNo73(_BMS_CellVoltNo73),BMS_CellVoltNo74(_BMS_CellVoltNo74),BMS_CellVoltNo75(_BMS_CellVoltNo75),BMS_CellVoltNo76(_BMS_CellVoltNo76),BMS_CellVoltNo77(_BMS_CellVoltNo77),BMS_CellVoltNo78(_BMS_CellVoltNo78),BMS_CellVoltNo79(_BMS_CellVoltNo79),BMS_CellVoltNo80(_BMS_CellVoltNo80),BMS_CellVoltNo81(_BMS_CellVoltNo81),BMS_CellVoltNo82(_BMS_CellVoltNo82),BMS_CellVoltNo83(_BMS_CellVoltNo83),BMS_CellVoltNo84(_BMS_CellVoltNo84),BMS_CellVoltNo85(_BMS_CellVoltNo85),BMS_CellVoltNo86(_BMS_CellVoltNo86),BMS_CellVoltNo87(_BMS_CellVoltNo87),BMS_CellVoltNo88(_BMS_CellVoltNo88),BMS_CellVoltNo89(_BMS_CellVoltNo89),BMS_CellVoltNo90(_BMS_CellVoltNo90),BMS_CellVoltNo91(_BMS_CellVoltNo91),BMS_CellVoltNo92(_BMS_CellVoltNo92),BMS_CellVoltNo93(_BMS_CellVoltNo93),BMS_CellVoltNo94(_BMS_CellVoltNo94),BMS_CellVoltNo95(_BMS_CellVoltNo95),BMS_CellVoltNo96(_BMS_CellVoltNo96) {}
	BDCTestBMS4(const BDCTestBMS4 &_x){
		BMS_CellVoltNo1 = _x.BMS_CellVoltNo1;
		BMS_CellVoltNo2 = _x.BMS_CellVoltNo2;
		BMS_CellVoltNo3 = _x.BMS_CellVoltNo3;
		BMS_CellVoltNo4 = _x.BMS_CellVoltNo4;
		BMS_CellVoltNo5 = _x.BMS_CellVoltNo5;
		BMS_CellVoltNo6 = _x.BMS_CellVoltNo6;
		BMS_CellVoltNo7 = _x.BMS_CellVoltNo7;
		BMS_CellVoltNo8 = _x.BMS_CellVoltNo8;
		BMS_CellVoltNo9 = _x.BMS_CellVoltNo9;
		BMS_CellVoltNo10 = _x.BMS_CellVoltNo10;
		BMS_CellVoltNo11 = _x.BMS_CellVoltNo11;
		BMS_CellVoltNo12 = _x.BMS_CellVoltNo12;
		BMS_CellVoltNo13 = _x.BMS_CellVoltNo13;
		BMS_CellVoltNo14 = _x.BMS_CellVoltNo14;
		BMS_CellVoltNo15 = _x.BMS_CellVoltNo15;
		BMS_CellVoltNo16 = _x.BMS_CellVoltNo16;
		BMS_CellVoltNo17 = _x.BMS_CellVoltNo17;
		BMS_CellVoltNo18 = _x.BMS_CellVoltNo18;
		BMS_CellVoltNo19 = _x.BMS_CellVoltNo19;
		BMS_CellVoltNo20 = _x.BMS_CellVoltNo20;
		BMS_CellVoltNo21 = _x.BMS_CellVoltNo21;
		BMS_CellVoltNo22 = _x.BMS_CellVoltNo22;
		BMS_CellVoltNo23 = _x.BMS_CellVoltNo23;
		BMS_CellVoltNo24 = _x.BMS_CellVoltNo24;
		BMS_CellVoltNo25 = _x.BMS_CellVoltNo25;
		BMS_CellVoltNo26 = _x.BMS_CellVoltNo26;
		BMS_CellVoltNo27 = _x.BMS_CellVoltNo27;
		BMS_CellVoltNo28 = _x.BMS_CellVoltNo28;
		BMS_CellVoltNo29 = _x.BMS_CellVoltNo29;
		BMS_CellVoltNo30 = _x.BMS_CellVoltNo30;
		BMS_CellVoltNo31 = _x.BMS_CellVoltNo31;
		BMS_CellVoltNo32 = _x.BMS_CellVoltNo32;
		BMS_CellVoltNo33 = _x.BMS_CellVoltNo33;
		BMS_CellVoltNo34 = _x.BMS_CellVoltNo34;
		BMS_CellVoltNo35 = _x.BMS_CellVoltNo35;
		BMS_CellVoltNo36 = _x.BMS_CellVoltNo36;
		BMS_CellVoltNo37 = _x.BMS_CellVoltNo37;
		BMS_CellVoltNo38 = _x.BMS_CellVoltNo38;
		BMS_CellVoltNo39 = _x.BMS_CellVoltNo39;
		BMS_CellVoltNo40 = _x.BMS_CellVoltNo40;
		BMS_CellVoltNo41 = _x.BMS_CellVoltNo41;
		BMS_CellVoltNo42 = _x.BMS_CellVoltNo42;
		BMS_CellVoltNo43 = _x.BMS_CellVoltNo43;
		BMS_CellVoltNo44 = _x.BMS_CellVoltNo44;
		BMS_CellVoltNo45 = _x.BMS_CellVoltNo45;
		BMS_CellVoltNo46 = _x.BMS_CellVoltNo46;
		BMS_CellVoltNo47 = _x.BMS_CellVoltNo47;
		BMS_CellVoltNo48 = _x.BMS_CellVoltNo48;
		BMS_CellVoltNo49 = _x.BMS_CellVoltNo49;
		BMS_CellVoltNo50 = _x.BMS_CellVoltNo50;
		BMS_CellVoltNo51 = _x.BMS_CellVoltNo51;
		BMS_CellVoltNo52 = _x.BMS_CellVoltNo52;
		BMS_CellVoltNo53 = _x.BMS_CellVoltNo53;
		BMS_CellVoltNo54 = _x.BMS_CellVoltNo54;
		BMS_CellVoltNo55 = _x.BMS_CellVoltNo55;
		BMS_CellVoltNo56 = _x.BMS_CellVoltNo56;
		BMS_CellVoltNo57 = _x.BMS_CellVoltNo57;
		BMS_CellVoltNo58 = _x.BMS_CellVoltNo58;
		BMS_CellVoltNo59 = _x.BMS_CellVoltNo59;
		BMS_CellVoltNo60 = _x.BMS_CellVoltNo60;
		BMS_CellVoltNo61 = _x.BMS_CellVoltNo61;
		BMS_CellVoltNo62 = _x.BMS_CellVoltNo62;
		BMS_CellVoltNo63 = _x.BMS_CellVoltNo63;
		BMS_CellVoltNo64 = _x.BMS_CellVoltNo64;
		BMS_CellVoltNo65 = _x.BMS_CellVoltNo65;
		BMS_CellVoltNo66 = _x.BMS_CellVoltNo66;
		BMS_CellVoltNo67 = _x.BMS_CellVoltNo67;
		BMS_CellVoltNo68 = _x.BMS_CellVoltNo68;
		BMS_CellVoltNo69 = _x.BMS_CellVoltNo69;
		BMS_CellVoltNo70 = _x.BMS_CellVoltNo70;
		BMS_CellVoltNo71 = _x.BMS_CellVoltNo71;
		BMS_CellVoltNo72 = _x.BMS_CellVoltNo72;
		BMS_CellVoltNo73 = _x.BMS_CellVoltNo73;
		BMS_CellVoltNo74 = _x.BMS_CellVoltNo74;
		BMS_CellVoltNo75 = _x.BMS_CellVoltNo75;
		BMS_CellVoltNo76 = _x.BMS_CellVoltNo76;
		BMS_CellVoltNo77 = _x.BMS_CellVoltNo77;
		BMS_CellVoltNo78 = _x.BMS_CellVoltNo78;
		BMS_CellVoltNo79 = _x.BMS_CellVoltNo79;
		BMS_CellVoltNo80 = _x.BMS_CellVoltNo80;
		BMS_CellVoltNo81 = _x.BMS_CellVoltNo81;
		BMS_CellVoltNo82 = _x.BMS_CellVoltNo82;
		BMS_CellVoltNo83 = _x.BMS_CellVoltNo83;
		BMS_CellVoltNo84 = _x.BMS_CellVoltNo84;
		BMS_CellVoltNo85 = _x.BMS_CellVoltNo85;
		BMS_CellVoltNo86 = _x.BMS_CellVoltNo86;
		BMS_CellVoltNo87 = _x.BMS_CellVoltNo87;
		BMS_CellVoltNo88 = _x.BMS_CellVoltNo88;
		BMS_CellVoltNo89 = _x.BMS_CellVoltNo89;
		BMS_CellVoltNo90 = _x.BMS_CellVoltNo90;
		BMS_CellVoltNo91 = _x.BMS_CellVoltNo91;
		BMS_CellVoltNo92 = _x.BMS_CellVoltNo92;
		BMS_CellVoltNo93 = _x.BMS_CellVoltNo93;
		BMS_CellVoltNo94 = _x.BMS_CellVoltNo94;
		BMS_CellVoltNo95 = _x.BMS_CellVoltNo95;
		BMS_CellVoltNo96 = _x.BMS_CellVoltNo96;
	}
	BDCTestBMS4(BDCTestBMS4 &&_x){
		BMS_CellVoltNo1 = std::move(_x.BMS_CellVoltNo1);
		BMS_CellVoltNo2 = std::move(_x.BMS_CellVoltNo2);
		BMS_CellVoltNo3 = std::move(_x.BMS_CellVoltNo3);
		BMS_CellVoltNo4 = std::move(_x.BMS_CellVoltNo4);
		BMS_CellVoltNo5 = std::move(_x.BMS_CellVoltNo5);
		BMS_CellVoltNo6 = std::move(_x.BMS_CellVoltNo6);
		BMS_CellVoltNo7 = std::move(_x.BMS_CellVoltNo7);
		BMS_CellVoltNo8 = std::move(_x.BMS_CellVoltNo8);
		BMS_CellVoltNo9 = std::move(_x.BMS_CellVoltNo9);
		BMS_CellVoltNo10 = std::move(_x.BMS_CellVoltNo10);
		BMS_CellVoltNo11 = std::move(_x.BMS_CellVoltNo11);
		BMS_CellVoltNo12 = std::move(_x.BMS_CellVoltNo12);
		BMS_CellVoltNo13 = std::move(_x.BMS_CellVoltNo13);
		BMS_CellVoltNo14 = std::move(_x.BMS_CellVoltNo14);
		BMS_CellVoltNo15 = std::move(_x.BMS_CellVoltNo15);
		BMS_CellVoltNo16 = std::move(_x.BMS_CellVoltNo16);
		BMS_CellVoltNo17 = std::move(_x.BMS_CellVoltNo17);
		BMS_CellVoltNo18 = std::move(_x.BMS_CellVoltNo18);
		BMS_CellVoltNo19 = std::move(_x.BMS_CellVoltNo19);
		BMS_CellVoltNo20 = std::move(_x.BMS_CellVoltNo20);
		BMS_CellVoltNo21 = std::move(_x.BMS_CellVoltNo21);
		BMS_CellVoltNo22 = std::move(_x.BMS_CellVoltNo22);
		BMS_CellVoltNo23 = std::move(_x.BMS_CellVoltNo23);
		BMS_CellVoltNo24 = std::move(_x.BMS_CellVoltNo24);
		BMS_CellVoltNo25 = std::move(_x.BMS_CellVoltNo25);
		BMS_CellVoltNo26 = std::move(_x.BMS_CellVoltNo26);
		BMS_CellVoltNo27 = std::move(_x.BMS_CellVoltNo27);
		BMS_CellVoltNo28 = std::move(_x.BMS_CellVoltNo28);
		BMS_CellVoltNo29 = std::move(_x.BMS_CellVoltNo29);
		BMS_CellVoltNo30 = std::move(_x.BMS_CellVoltNo30);
		BMS_CellVoltNo31 = std::move(_x.BMS_CellVoltNo31);
		BMS_CellVoltNo32 = std::move(_x.BMS_CellVoltNo32);
		BMS_CellVoltNo33 = std::move(_x.BMS_CellVoltNo33);
		BMS_CellVoltNo34 = std::move(_x.BMS_CellVoltNo34);
		BMS_CellVoltNo35 = std::move(_x.BMS_CellVoltNo35);
		BMS_CellVoltNo36 = std::move(_x.BMS_CellVoltNo36);
		BMS_CellVoltNo37 = std::move(_x.BMS_CellVoltNo37);
		BMS_CellVoltNo38 = std::move(_x.BMS_CellVoltNo38);
		BMS_CellVoltNo39 = std::move(_x.BMS_CellVoltNo39);
		BMS_CellVoltNo40 = std::move(_x.BMS_CellVoltNo40);
		BMS_CellVoltNo41 = std::move(_x.BMS_CellVoltNo41);
		BMS_CellVoltNo42 = std::move(_x.BMS_CellVoltNo42);
		BMS_CellVoltNo43 = std::move(_x.BMS_CellVoltNo43);
		BMS_CellVoltNo44 = std::move(_x.BMS_CellVoltNo44);
		BMS_CellVoltNo45 = std::move(_x.BMS_CellVoltNo45);
		BMS_CellVoltNo46 = std::move(_x.BMS_CellVoltNo46);
		BMS_CellVoltNo47 = std::move(_x.BMS_CellVoltNo47);
		BMS_CellVoltNo48 = std::move(_x.BMS_CellVoltNo48);
		BMS_CellVoltNo49 = std::move(_x.BMS_CellVoltNo49);
		BMS_CellVoltNo50 = std::move(_x.BMS_CellVoltNo50);
		BMS_CellVoltNo51 = std::move(_x.BMS_CellVoltNo51);
		BMS_CellVoltNo52 = std::move(_x.BMS_CellVoltNo52);
		BMS_CellVoltNo53 = std::move(_x.BMS_CellVoltNo53);
		BMS_CellVoltNo54 = std::move(_x.BMS_CellVoltNo54);
		BMS_CellVoltNo55 = std::move(_x.BMS_CellVoltNo55);
		BMS_CellVoltNo56 = std::move(_x.BMS_CellVoltNo56);
		BMS_CellVoltNo57 = std::move(_x.BMS_CellVoltNo57);
		BMS_CellVoltNo58 = std::move(_x.BMS_CellVoltNo58);
		BMS_CellVoltNo59 = std::move(_x.BMS_CellVoltNo59);
		BMS_CellVoltNo60 = std::move(_x.BMS_CellVoltNo60);
		BMS_CellVoltNo61 = std::move(_x.BMS_CellVoltNo61);
		BMS_CellVoltNo62 = std::move(_x.BMS_CellVoltNo62);
		BMS_CellVoltNo63 = std::move(_x.BMS_CellVoltNo63);
		BMS_CellVoltNo64 = std::move(_x.BMS_CellVoltNo64);
		BMS_CellVoltNo65 = std::move(_x.BMS_CellVoltNo65);
		BMS_CellVoltNo66 = std::move(_x.BMS_CellVoltNo66);
		BMS_CellVoltNo67 = std::move(_x.BMS_CellVoltNo67);
		BMS_CellVoltNo68 = std::move(_x.BMS_CellVoltNo68);
		BMS_CellVoltNo69 = std::move(_x.BMS_CellVoltNo69);
		BMS_CellVoltNo70 = std::move(_x.BMS_CellVoltNo70);
		BMS_CellVoltNo71 = std::move(_x.BMS_CellVoltNo71);
		BMS_CellVoltNo72 = std::move(_x.BMS_CellVoltNo72);
		BMS_CellVoltNo73 = std::move(_x.BMS_CellVoltNo73);
		BMS_CellVoltNo74 = std::move(_x.BMS_CellVoltNo74);
		BMS_CellVoltNo75 = std::move(_x.BMS_CellVoltNo75);
		BMS_CellVoltNo76 = std::move(_x.BMS_CellVoltNo76);
		BMS_CellVoltNo77 = std::move(_x.BMS_CellVoltNo77);
		BMS_CellVoltNo78 = std::move(_x.BMS_CellVoltNo78);
		BMS_CellVoltNo79 = std::move(_x.BMS_CellVoltNo79);
		BMS_CellVoltNo80 = std::move(_x.BMS_CellVoltNo80);
		BMS_CellVoltNo81 = std::move(_x.BMS_CellVoltNo81);
		BMS_CellVoltNo82 = std::move(_x.BMS_CellVoltNo82);
		BMS_CellVoltNo83 = std::move(_x.BMS_CellVoltNo83);
		BMS_CellVoltNo84 = std::move(_x.BMS_CellVoltNo84);
		BMS_CellVoltNo85 = std::move(_x.BMS_CellVoltNo85);
		BMS_CellVoltNo86 = std::move(_x.BMS_CellVoltNo86);
		BMS_CellVoltNo87 = std::move(_x.BMS_CellVoltNo87);
		BMS_CellVoltNo88 = std::move(_x.BMS_CellVoltNo88);
		BMS_CellVoltNo89 = std::move(_x.BMS_CellVoltNo89);
		BMS_CellVoltNo90 = std::move(_x.BMS_CellVoltNo90);
		BMS_CellVoltNo91 = std::move(_x.BMS_CellVoltNo91);
		BMS_CellVoltNo92 = std::move(_x.BMS_CellVoltNo92);
		BMS_CellVoltNo93 = std::move(_x.BMS_CellVoltNo93);
		BMS_CellVoltNo94 = std::move(_x.BMS_CellVoltNo94);
		BMS_CellVoltNo95 = std::move(_x.BMS_CellVoltNo95);
		BMS_CellVoltNo96 = std::move(_x.BMS_CellVoltNo96);
	}
	BDCTestBMS4& operator=(const BDCTestBMS4 &_x){
		BMS_CellVoltNo1 = _x.BMS_CellVoltNo1;
		BMS_CellVoltNo2 = _x.BMS_CellVoltNo2;
		BMS_CellVoltNo3 = _x.BMS_CellVoltNo3;
		BMS_CellVoltNo4 = _x.BMS_CellVoltNo4;
		BMS_CellVoltNo5 = _x.BMS_CellVoltNo5;
		BMS_CellVoltNo6 = _x.BMS_CellVoltNo6;
		BMS_CellVoltNo7 = _x.BMS_CellVoltNo7;
		BMS_CellVoltNo8 = _x.BMS_CellVoltNo8;
		BMS_CellVoltNo9 = _x.BMS_CellVoltNo9;
		BMS_CellVoltNo10 = _x.BMS_CellVoltNo10;
		BMS_CellVoltNo11 = _x.BMS_CellVoltNo11;
		BMS_CellVoltNo12 = _x.BMS_CellVoltNo12;
		BMS_CellVoltNo13 = _x.BMS_CellVoltNo13;
		BMS_CellVoltNo14 = _x.BMS_CellVoltNo14;
		BMS_CellVoltNo15 = _x.BMS_CellVoltNo15;
		BMS_CellVoltNo16 = _x.BMS_CellVoltNo16;
		BMS_CellVoltNo17 = _x.BMS_CellVoltNo17;
		BMS_CellVoltNo18 = _x.BMS_CellVoltNo18;
		BMS_CellVoltNo19 = _x.BMS_CellVoltNo19;
		BMS_CellVoltNo20 = _x.BMS_CellVoltNo20;
		BMS_CellVoltNo21 = _x.BMS_CellVoltNo21;
		BMS_CellVoltNo22 = _x.BMS_CellVoltNo22;
		BMS_CellVoltNo23 = _x.BMS_CellVoltNo23;
		BMS_CellVoltNo24 = _x.BMS_CellVoltNo24;
		BMS_CellVoltNo25 = _x.BMS_CellVoltNo25;
		BMS_CellVoltNo26 = _x.BMS_CellVoltNo26;
		BMS_CellVoltNo27 = _x.BMS_CellVoltNo27;
		BMS_CellVoltNo28 = _x.BMS_CellVoltNo28;
		BMS_CellVoltNo29 = _x.BMS_CellVoltNo29;
		BMS_CellVoltNo30 = _x.BMS_CellVoltNo30;
		BMS_CellVoltNo31 = _x.BMS_CellVoltNo31;
		BMS_CellVoltNo32 = _x.BMS_CellVoltNo32;
		BMS_CellVoltNo33 = _x.BMS_CellVoltNo33;
		BMS_CellVoltNo34 = _x.BMS_CellVoltNo34;
		BMS_CellVoltNo35 = _x.BMS_CellVoltNo35;
		BMS_CellVoltNo36 = _x.BMS_CellVoltNo36;
		BMS_CellVoltNo37 = _x.BMS_CellVoltNo37;
		BMS_CellVoltNo38 = _x.BMS_CellVoltNo38;
		BMS_CellVoltNo39 = _x.BMS_CellVoltNo39;
		BMS_CellVoltNo40 = _x.BMS_CellVoltNo40;
		BMS_CellVoltNo41 = _x.BMS_CellVoltNo41;
		BMS_CellVoltNo42 = _x.BMS_CellVoltNo42;
		BMS_CellVoltNo43 = _x.BMS_CellVoltNo43;
		BMS_CellVoltNo44 = _x.BMS_CellVoltNo44;
		BMS_CellVoltNo45 = _x.BMS_CellVoltNo45;
		BMS_CellVoltNo46 = _x.BMS_CellVoltNo46;
		BMS_CellVoltNo47 = _x.BMS_CellVoltNo47;
		BMS_CellVoltNo48 = _x.BMS_CellVoltNo48;
		BMS_CellVoltNo49 = _x.BMS_CellVoltNo49;
		BMS_CellVoltNo50 = _x.BMS_CellVoltNo50;
		BMS_CellVoltNo51 = _x.BMS_CellVoltNo51;
		BMS_CellVoltNo52 = _x.BMS_CellVoltNo52;
		BMS_CellVoltNo53 = _x.BMS_CellVoltNo53;
		BMS_CellVoltNo54 = _x.BMS_CellVoltNo54;
		BMS_CellVoltNo55 = _x.BMS_CellVoltNo55;
		BMS_CellVoltNo56 = _x.BMS_CellVoltNo56;
		BMS_CellVoltNo57 = _x.BMS_CellVoltNo57;
		BMS_CellVoltNo58 = _x.BMS_CellVoltNo58;
		BMS_CellVoltNo59 = _x.BMS_CellVoltNo59;
		BMS_CellVoltNo60 = _x.BMS_CellVoltNo60;
		BMS_CellVoltNo61 = _x.BMS_CellVoltNo61;
		BMS_CellVoltNo62 = _x.BMS_CellVoltNo62;
		BMS_CellVoltNo63 = _x.BMS_CellVoltNo63;
		BMS_CellVoltNo64 = _x.BMS_CellVoltNo64;
		BMS_CellVoltNo65 = _x.BMS_CellVoltNo65;
		BMS_CellVoltNo66 = _x.BMS_CellVoltNo66;
		BMS_CellVoltNo67 = _x.BMS_CellVoltNo67;
		BMS_CellVoltNo68 = _x.BMS_CellVoltNo68;
		BMS_CellVoltNo69 = _x.BMS_CellVoltNo69;
		BMS_CellVoltNo70 = _x.BMS_CellVoltNo70;
		BMS_CellVoltNo71 = _x.BMS_CellVoltNo71;
		BMS_CellVoltNo72 = _x.BMS_CellVoltNo72;
		BMS_CellVoltNo73 = _x.BMS_CellVoltNo73;
		BMS_CellVoltNo74 = _x.BMS_CellVoltNo74;
		BMS_CellVoltNo75 = _x.BMS_CellVoltNo75;
		BMS_CellVoltNo76 = _x.BMS_CellVoltNo76;
		BMS_CellVoltNo77 = _x.BMS_CellVoltNo77;
		BMS_CellVoltNo78 = _x.BMS_CellVoltNo78;
		BMS_CellVoltNo79 = _x.BMS_CellVoltNo79;
		BMS_CellVoltNo80 = _x.BMS_CellVoltNo80;
		BMS_CellVoltNo81 = _x.BMS_CellVoltNo81;
		BMS_CellVoltNo82 = _x.BMS_CellVoltNo82;
		BMS_CellVoltNo83 = _x.BMS_CellVoltNo83;
		BMS_CellVoltNo84 = _x.BMS_CellVoltNo84;
		BMS_CellVoltNo85 = _x.BMS_CellVoltNo85;
		BMS_CellVoltNo86 = _x.BMS_CellVoltNo86;
		BMS_CellVoltNo87 = _x.BMS_CellVoltNo87;
		BMS_CellVoltNo88 = _x.BMS_CellVoltNo88;
		BMS_CellVoltNo89 = _x.BMS_CellVoltNo89;
		BMS_CellVoltNo90 = _x.BMS_CellVoltNo90;
		BMS_CellVoltNo91 = _x.BMS_CellVoltNo91;
		BMS_CellVoltNo92 = _x.BMS_CellVoltNo92;
		BMS_CellVoltNo93 = _x.BMS_CellVoltNo93;
		BMS_CellVoltNo94 = _x.BMS_CellVoltNo94;
		BMS_CellVoltNo95 = _x.BMS_CellVoltNo95;
		BMS_CellVoltNo96 = _x.BMS_CellVoltNo96;
		return *this;
	}
	BDCTestBMS4& operator=(BDCTestBMS4 &&_x){
		BMS_CellVoltNo1 = std::move(_x.BMS_CellVoltNo1);
		BMS_CellVoltNo2 = std::move(_x.BMS_CellVoltNo2);
		BMS_CellVoltNo3 = std::move(_x.BMS_CellVoltNo3);
		BMS_CellVoltNo4 = std::move(_x.BMS_CellVoltNo4);
		BMS_CellVoltNo5 = std::move(_x.BMS_CellVoltNo5);
		BMS_CellVoltNo6 = std::move(_x.BMS_CellVoltNo6);
		BMS_CellVoltNo7 = std::move(_x.BMS_CellVoltNo7);
		BMS_CellVoltNo8 = std::move(_x.BMS_CellVoltNo8);
		BMS_CellVoltNo9 = std::move(_x.BMS_CellVoltNo9);
		BMS_CellVoltNo10 = std::move(_x.BMS_CellVoltNo10);
		BMS_CellVoltNo11 = std::move(_x.BMS_CellVoltNo11);
		BMS_CellVoltNo12 = std::move(_x.BMS_CellVoltNo12);
		BMS_CellVoltNo13 = std::move(_x.BMS_CellVoltNo13);
		BMS_CellVoltNo14 = std::move(_x.BMS_CellVoltNo14);
		BMS_CellVoltNo15 = std::move(_x.BMS_CellVoltNo15);
		BMS_CellVoltNo16 = std::move(_x.BMS_CellVoltNo16);
		BMS_CellVoltNo17 = std::move(_x.BMS_CellVoltNo17);
		BMS_CellVoltNo18 = std::move(_x.BMS_CellVoltNo18);
		BMS_CellVoltNo19 = std::move(_x.BMS_CellVoltNo19);
		BMS_CellVoltNo20 = std::move(_x.BMS_CellVoltNo20);
		BMS_CellVoltNo21 = std::move(_x.BMS_CellVoltNo21);
		BMS_CellVoltNo22 = std::move(_x.BMS_CellVoltNo22);
		BMS_CellVoltNo23 = std::move(_x.BMS_CellVoltNo23);
		BMS_CellVoltNo24 = std::move(_x.BMS_CellVoltNo24);
		BMS_CellVoltNo25 = std::move(_x.BMS_CellVoltNo25);
		BMS_CellVoltNo26 = std::move(_x.BMS_CellVoltNo26);
		BMS_CellVoltNo27 = std::move(_x.BMS_CellVoltNo27);
		BMS_CellVoltNo28 = std::move(_x.BMS_CellVoltNo28);
		BMS_CellVoltNo29 = std::move(_x.BMS_CellVoltNo29);
		BMS_CellVoltNo30 = std::move(_x.BMS_CellVoltNo30);
		BMS_CellVoltNo31 = std::move(_x.BMS_CellVoltNo31);
		BMS_CellVoltNo32 = std::move(_x.BMS_CellVoltNo32);
		BMS_CellVoltNo33 = std::move(_x.BMS_CellVoltNo33);
		BMS_CellVoltNo34 = std::move(_x.BMS_CellVoltNo34);
		BMS_CellVoltNo35 = std::move(_x.BMS_CellVoltNo35);
		BMS_CellVoltNo36 = std::move(_x.BMS_CellVoltNo36);
		BMS_CellVoltNo37 = std::move(_x.BMS_CellVoltNo37);
		BMS_CellVoltNo38 = std::move(_x.BMS_CellVoltNo38);
		BMS_CellVoltNo39 = std::move(_x.BMS_CellVoltNo39);
		BMS_CellVoltNo40 = std::move(_x.BMS_CellVoltNo40);
		BMS_CellVoltNo41 = std::move(_x.BMS_CellVoltNo41);
		BMS_CellVoltNo42 = std::move(_x.BMS_CellVoltNo42);
		BMS_CellVoltNo43 = std::move(_x.BMS_CellVoltNo43);
		BMS_CellVoltNo44 = std::move(_x.BMS_CellVoltNo44);
		BMS_CellVoltNo45 = std::move(_x.BMS_CellVoltNo45);
		BMS_CellVoltNo46 = std::move(_x.BMS_CellVoltNo46);
		BMS_CellVoltNo47 = std::move(_x.BMS_CellVoltNo47);
		BMS_CellVoltNo48 = std::move(_x.BMS_CellVoltNo48);
		BMS_CellVoltNo49 = std::move(_x.BMS_CellVoltNo49);
		BMS_CellVoltNo50 = std::move(_x.BMS_CellVoltNo50);
		BMS_CellVoltNo51 = std::move(_x.BMS_CellVoltNo51);
		BMS_CellVoltNo52 = std::move(_x.BMS_CellVoltNo52);
		BMS_CellVoltNo53 = std::move(_x.BMS_CellVoltNo53);
		BMS_CellVoltNo54 = std::move(_x.BMS_CellVoltNo54);
		BMS_CellVoltNo55 = std::move(_x.BMS_CellVoltNo55);
		BMS_CellVoltNo56 = std::move(_x.BMS_CellVoltNo56);
		BMS_CellVoltNo57 = std::move(_x.BMS_CellVoltNo57);
		BMS_CellVoltNo58 = std::move(_x.BMS_CellVoltNo58);
		BMS_CellVoltNo59 = std::move(_x.BMS_CellVoltNo59);
		BMS_CellVoltNo60 = std::move(_x.BMS_CellVoltNo60);
		BMS_CellVoltNo61 = std::move(_x.BMS_CellVoltNo61);
		BMS_CellVoltNo62 = std::move(_x.BMS_CellVoltNo62);
		BMS_CellVoltNo63 = std::move(_x.BMS_CellVoltNo63);
		BMS_CellVoltNo64 = std::move(_x.BMS_CellVoltNo64);
		BMS_CellVoltNo65 = std::move(_x.BMS_CellVoltNo65);
		BMS_CellVoltNo66 = std::move(_x.BMS_CellVoltNo66);
		BMS_CellVoltNo67 = std::move(_x.BMS_CellVoltNo67);
		BMS_CellVoltNo68 = std::move(_x.BMS_CellVoltNo68);
		BMS_CellVoltNo69 = std::move(_x.BMS_CellVoltNo69);
		BMS_CellVoltNo70 = std::move(_x.BMS_CellVoltNo70);
		BMS_CellVoltNo71 = std::move(_x.BMS_CellVoltNo71);
		BMS_CellVoltNo72 = std::move(_x.BMS_CellVoltNo72);
		BMS_CellVoltNo73 = std::move(_x.BMS_CellVoltNo73);
		BMS_CellVoltNo74 = std::move(_x.BMS_CellVoltNo74);
		BMS_CellVoltNo75 = std::move(_x.BMS_CellVoltNo75);
		BMS_CellVoltNo76 = std::move(_x.BMS_CellVoltNo76);
		BMS_CellVoltNo77 = std::move(_x.BMS_CellVoltNo77);
		BMS_CellVoltNo78 = std::move(_x.BMS_CellVoltNo78);
		BMS_CellVoltNo79 = std::move(_x.BMS_CellVoltNo79);
		BMS_CellVoltNo80 = std::move(_x.BMS_CellVoltNo80);
		BMS_CellVoltNo81 = std::move(_x.BMS_CellVoltNo81);
		BMS_CellVoltNo82 = std::move(_x.BMS_CellVoltNo82);
		BMS_CellVoltNo83 = std::move(_x.BMS_CellVoltNo83);
		BMS_CellVoltNo84 = std::move(_x.BMS_CellVoltNo84);
		BMS_CellVoltNo85 = std::move(_x.BMS_CellVoltNo85);
		BMS_CellVoltNo86 = std::move(_x.BMS_CellVoltNo86);
		BMS_CellVoltNo87 = std::move(_x.BMS_CellVoltNo87);
		BMS_CellVoltNo88 = std::move(_x.BMS_CellVoltNo88);
		BMS_CellVoltNo89 = std::move(_x.BMS_CellVoltNo89);
		BMS_CellVoltNo90 = std::move(_x.BMS_CellVoltNo90);
		BMS_CellVoltNo91 = std::move(_x.BMS_CellVoltNo91);
		BMS_CellVoltNo92 = std::move(_x.BMS_CellVoltNo92);
		BMS_CellVoltNo93 = std::move(_x.BMS_CellVoltNo93);
		BMS_CellVoltNo94 = std::move(_x.BMS_CellVoltNo94);
		BMS_CellVoltNo95 = std::move(_x.BMS_CellVoltNo95);
		BMS_CellVoltNo96 = std::move(_x.BMS_CellVoltNo96);
		return *this;
	}
*/

	using IsEnumerableTag = void;
	template<typename F>
	void enumerate(F& fun) {
		fun(BMS_CellVoltNo1);
		fun(BMS_CellVoltNo2);
		fun(BMS_CellVoltNo3);
		fun(BMS_CellVoltNo4);
		fun(BMS_CellVoltNo5);
		fun(BMS_CellVoltNo6);
		fun(BMS_CellVoltNo7);
		fun(BMS_CellVoltNo8);
		fun(BMS_CellVoltNo9);
		fun(BMS_CellVoltNo10);
		fun(BMS_CellVoltNo11);
		fun(BMS_CellVoltNo12);
		fun(BMS_CellVoltNo13);
		fun(BMS_CellVoltNo14);
		fun(BMS_CellVoltNo15);
		fun(BMS_CellVoltNo16);
		fun(BMS_CellVoltNo17);
		fun(BMS_CellVoltNo18);
		fun(BMS_CellVoltNo19);
		fun(BMS_CellVoltNo20);
		fun(BMS_CellVoltNo21);
		fun(BMS_CellVoltNo22);
		fun(BMS_CellVoltNo23);
		fun(BMS_CellVoltNo24);
		fun(BMS_CellVoltNo25);
		fun(BMS_CellVoltNo26);
		fun(BMS_CellVoltNo27);
		fun(BMS_CellVoltNo28);
		fun(BMS_CellVoltNo29);
		fun(BMS_CellVoltNo30);
		fun(BMS_CellVoltNo31);
		fun(BMS_CellVoltNo32);
		fun(BMS_CellVoltNo33);
		fun(BMS_CellVoltNo34);
		fun(BMS_CellVoltNo35);
		fun(BMS_CellVoltNo36);
		fun(BMS_CellVoltNo37);
		fun(BMS_CellVoltNo38);
		fun(BMS_CellVoltNo39);
		fun(BMS_CellVoltNo40);
		fun(BMS_CellVoltNo41);
		fun(BMS_CellVoltNo42);
		fun(BMS_CellVoltNo43);
		fun(BMS_CellVoltNo44);
		fun(BMS_CellVoltNo45);
		fun(BMS_CellVoltNo46);
		fun(BMS_CellVoltNo47);
		fun(BMS_CellVoltNo48);
		fun(BMS_CellVoltNo49);
		fun(BMS_CellVoltNo50);
		fun(BMS_CellVoltNo51);
		fun(BMS_CellVoltNo52);
		fun(BMS_CellVoltNo53);
		fun(BMS_CellVoltNo54);
		fun(BMS_CellVoltNo55);
		fun(BMS_CellVoltNo56);
		fun(BMS_CellVoltNo57);
		fun(BMS_CellVoltNo58);
		fun(BMS_CellVoltNo59);
		fun(BMS_CellVoltNo60);
		fun(BMS_CellVoltNo61);
		fun(BMS_CellVoltNo62);
		fun(BMS_CellVoltNo63);
		fun(BMS_CellVoltNo64);
		fun(BMS_CellVoltNo65);
		fun(BMS_CellVoltNo66);
		fun(BMS_CellVoltNo67);
		fun(BMS_CellVoltNo68);
		fun(BMS_CellVoltNo69);
		fun(BMS_CellVoltNo70);
		fun(BMS_CellVoltNo71);
		fun(BMS_CellVoltNo72);
		fun(BMS_CellVoltNo73);
		fun(BMS_CellVoltNo74);
		fun(BMS_CellVoltNo75);
		fun(BMS_CellVoltNo76);
		fun(BMS_CellVoltNo77);
		fun(BMS_CellVoltNo78);
		fun(BMS_CellVoltNo79);
		fun(BMS_CellVoltNo80);
		fun(BMS_CellVoltNo81);
		fun(BMS_CellVoltNo82);
		fun(BMS_CellVoltNo83);
		fun(BMS_CellVoltNo84);
		fun(BMS_CellVoltNo85);
		fun(BMS_CellVoltNo86);
		fun(BMS_CellVoltNo87);
		fun(BMS_CellVoltNo88);
		fun(BMS_CellVoltNo89);
		fun(BMS_CellVoltNo90);
		fun(BMS_CellVoltNo91);
		fun(BMS_CellVoltNo92);
		fun(BMS_CellVoltNo93);
		fun(BMS_CellVoltNo94);
		fun(BMS_CellVoltNo95);
		fun(BMS_CellVoltNo96);
	}

	template<typename F>
	void GetSize(F& fun) const{
		fun(BMS_CellVoltNo1);
		fun(BMS_CellVoltNo2);
		fun(BMS_CellVoltNo3);
		fun(BMS_CellVoltNo4);
		fun(BMS_CellVoltNo5);
		fun(BMS_CellVoltNo6);
		fun(BMS_CellVoltNo7);
		fun(BMS_CellVoltNo8);
		fun(BMS_CellVoltNo9);
		fun(BMS_CellVoltNo10);
		fun(BMS_CellVoltNo11);
		fun(BMS_CellVoltNo12);
		fun(BMS_CellVoltNo13);
		fun(BMS_CellVoltNo14);
		fun(BMS_CellVoltNo15);
		fun(BMS_CellVoltNo16);
		fun(BMS_CellVoltNo17);
		fun(BMS_CellVoltNo18);
		fun(BMS_CellVoltNo19);
		fun(BMS_CellVoltNo20);
		fun(BMS_CellVoltNo21);
		fun(BMS_CellVoltNo22);
		fun(BMS_CellVoltNo23);
		fun(BMS_CellVoltNo24);
		fun(BMS_CellVoltNo25);
		fun(BMS_CellVoltNo26);
		fun(BMS_CellVoltNo27);
		fun(BMS_CellVoltNo28);
		fun(BMS_CellVoltNo29);
		fun(BMS_CellVoltNo30);
		fun(BMS_CellVoltNo31);
		fun(BMS_CellVoltNo32);
		fun(BMS_CellVoltNo33);
		fun(BMS_CellVoltNo34);
		fun(BMS_CellVoltNo35);
		fun(BMS_CellVoltNo36);
		fun(BMS_CellVoltNo37);
		fun(BMS_CellVoltNo38);
		fun(BMS_CellVoltNo39);
		fun(BMS_CellVoltNo40);
		fun(BMS_CellVoltNo41);
		fun(BMS_CellVoltNo42);
		fun(BMS_CellVoltNo43);
		fun(BMS_CellVoltNo44);
		fun(BMS_CellVoltNo45);
		fun(BMS_CellVoltNo46);
		fun(BMS_CellVoltNo47);
		fun(BMS_CellVoltNo48);
		fun(BMS_CellVoltNo49);
		fun(BMS_CellVoltNo50);
		fun(BMS_CellVoltNo51);
		fun(BMS_CellVoltNo52);
		fun(BMS_CellVoltNo53);
		fun(BMS_CellVoltNo54);
		fun(BMS_CellVoltNo55);
		fun(BMS_CellVoltNo56);
		fun(BMS_CellVoltNo57);
		fun(BMS_CellVoltNo58);
		fun(BMS_CellVoltNo59);
		fun(BMS_CellVoltNo60);
		fun(BMS_CellVoltNo61);
		fun(BMS_CellVoltNo62);
		fun(BMS_CellVoltNo63);
		fun(BMS_CellVoltNo64);
		fun(BMS_CellVoltNo65);
		fun(BMS_CellVoltNo66);
		fun(BMS_CellVoltNo67);
		fun(BMS_CellVoltNo68);
		fun(BMS_CellVoltNo69);
		fun(BMS_CellVoltNo70);
		fun(BMS_CellVoltNo71);
		fun(BMS_CellVoltNo72);
		fun(BMS_CellVoltNo73);
		fun(BMS_CellVoltNo74);
		fun(BMS_CellVoltNo75);
		fun(BMS_CellVoltNo76);
		fun(BMS_CellVoltNo77);
		fun(BMS_CellVoltNo78);
		fun(BMS_CellVoltNo79);
		fun(BMS_CellVoltNo80);
		fun(BMS_CellVoltNo81);
		fun(BMS_CellVoltNo82);
		fun(BMS_CellVoltNo83);
		fun(BMS_CellVoltNo84);
		fun(BMS_CellVoltNo85);
		fun(BMS_CellVoltNo86);
		fun(BMS_CellVoltNo87);
		fun(BMS_CellVoltNo88);
		fun(BMS_CellVoltNo89);
		fun(BMS_CellVoltNo90);
		fun(BMS_CellVoltNo91);
		fun(BMS_CellVoltNo92);
		fun(BMS_CellVoltNo93);
		fun(BMS_CellVoltNo94);
		fun(BMS_CellVoltNo95);
		fun(BMS_CellVoltNo96);
	}
	template<typename F>
	void serialize(F& fun) const{
		fun << (BMS_CellVoltNo1);
		fun << (BMS_CellVoltNo2);
		fun << (BMS_CellVoltNo3);
		fun << (BMS_CellVoltNo4);
		fun << (BMS_CellVoltNo5);
		fun << (BMS_CellVoltNo6);
		fun << (BMS_CellVoltNo7);
		fun << (BMS_CellVoltNo8);
		fun << (BMS_CellVoltNo9);
		fun << (BMS_CellVoltNo10);
		fun << (BMS_CellVoltNo11);
		fun << (BMS_CellVoltNo12);
		fun << (BMS_CellVoltNo13);
		fun << (BMS_CellVoltNo14);
		fun << (BMS_CellVoltNo15);
		fun << (BMS_CellVoltNo16);
		fun << (BMS_CellVoltNo17);
		fun << (BMS_CellVoltNo18);
		fun << (BMS_CellVoltNo19);
		fun << (BMS_CellVoltNo20);
		fun << (BMS_CellVoltNo21);
		fun << (BMS_CellVoltNo22);
		fun << (BMS_CellVoltNo23);
		fun << (BMS_CellVoltNo24);
		fun << (BMS_CellVoltNo25);
		fun << (BMS_CellVoltNo26);
		fun << (BMS_CellVoltNo27);
		fun << (BMS_CellVoltNo28);
		fun << (BMS_CellVoltNo29);
		fun << (BMS_CellVoltNo30);
		fun << (BMS_CellVoltNo31);
		fun << (BMS_CellVoltNo32);
		fun << (BMS_CellVoltNo33);
		fun << (BMS_CellVoltNo34);
		fun << (BMS_CellVoltNo35);
		fun << (BMS_CellVoltNo36);
		fun << (BMS_CellVoltNo37);
		fun << (BMS_CellVoltNo38);
		fun << (BMS_CellVoltNo39);
		fun << (BMS_CellVoltNo40);
		fun << (BMS_CellVoltNo41);
		fun << (BMS_CellVoltNo42);
		fun << (BMS_CellVoltNo43);
		fun << (BMS_CellVoltNo44);
		fun << (BMS_CellVoltNo45);
		fun << (BMS_CellVoltNo46);
		fun << (BMS_CellVoltNo47);
		fun << (BMS_CellVoltNo48);
		fun << (BMS_CellVoltNo49);
		fun << (BMS_CellVoltNo50);
		fun << (BMS_CellVoltNo51);
		fun << (BMS_CellVoltNo52);
		fun << (BMS_CellVoltNo53);
		fun << (BMS_CellVoltNo54);
		fun << (BMS_CellVoltNo55);
		fun << (BMS_CellVoltNo56);
		fun << (BMS_CellVoltNo57);
		fun << (BMS_CellVoltNo58);
		fun << (BMS_CellVoltNo59);
		fun << (BMS_CellVoltNo60);
		fun << (BMS_CellVoltNo61);
		fun << (BMS_CellVoltNo62);
		fun << (BMS_CellVoltNo63);
		fun << (BMS_CellVoltNo64);
		fun << (BMS_CellVoltNo65);
		fun << (BMS_CellVoltNo66);
		fun << (BMS_CellVoltNo67);
		fun << (BMS_CellVoltNo68);
		fun << (BMS_CellVoltNo69);
		fun << (BMS_CellVoltNo70);
		fun << (BMS_CellVoltNo71);
		fun << (BMS_CellVoltNo72);
		fun << (BMS_CellVoltNo73);
		fun << (BMS_CellVoltNo74);
		fun << (BMS_CellVoltNo75);
		fun << (BMS_CellVoltNo76);
		fun << (BMS_CellVoltNo77);
		fun << (BMS_CellVoltNo78);
		fun << (BMS_CellVoltNo79);
		fun << (BMS_CellVoltNo80);
		fun << (BMS_CellVoltNo81);
		fun << (BMS_CellVoltNo82);
		fun << (BMS_CellVoltNo83);
		fun << (BMS_CellVoltNo84);
		fun << (BMS_CellVoltNo85);
		fun << (BMS_CellVoltNo86);
		fun << (BMS_CellVoltNo87);
		fun << (BMS_CellVoltNo88);
		fun << (BMS_CellVoltNo89);
		fun << (BMS_CellVoltNo90);
		fun << (BMS_CellVoltNo91);
		fun << (BMS_CellVoltNo92);
		fun << (BMS_CellVoltNo93);
		fun << (BMS_CellVoltNo94);
		fun << (BMS_CellVoltNo95);
		fun << (BMS_CellVoltNo96);
	}
	template<typename F>
	void deserialize(F& fun){
		fun >> (BMS_CellVoltNo1);
		fun >> (BMS_CellVoltNo2);
		fun >> (BMS_CellVoltNo3);
		fun >> (BMS_CellVoltNo4);
		fun >> (BMS_CellVoltNo5);
		fun >> (BMS_CellVoltNo6);
		fun >> (BMS_CellVoltNo7);
		fun >> (BMS_CellVoltNo8);
		fun >> (BMS_CellVoltNo9);
		fun >> (BMS_CellVoltNo10);
		fun >> (BMS_CellVoltNo11);
		fun >> (BMS_CellVoltNo12);
		fun >> (BMS_CellVoltNo13);
		fun >> (BMS_CellVoltNo14);
		fun >> (BMS_CellVoltNo15);
		fun >> (BMS_CellVoltNo16);
		fun >> (BMS_CellVoltNo17);
		fun >> (BMS_CellVoltNo18);
		fun >> (BMS_CellVoltNo19);
		fun >> (BMS_CellVoltNo20);
		fun >> (BMS_CellVoltNo21);
		fun >> (BMS_CellVoltNo22);
		fun >> (BMS_CellVoltNo23);
		fun >> (BMS_CellVoltNo24);
		fun >> (BMS_CellVoltNo25);
		fun >> (BMS_CellVoltNo26);
		fun >> (BMS_CellVoltNo27);
		fun >> (BMS_CellVoltNo28);
		fun >> (BMS_CellVoltNo29);
		fun >> (BMS_CellVoltNo30);
		fun >> (BMS_CellVoltNo31);
		fun >> (BMS_CellVoltNo32);
		fun >> (BMS_CellVoltNo33);
		fun >> (BMS_CellVoltNo34);
		fun >> (BMS_CellVoltNo35);
		fun >> (BMS_CellVoltNo36);
		fun >> (BMS_CellVoltNo37);
		fun >> (BMS_CellVoltNo38);
		fun >> (BMS_CellVoltNo39);
		fun >> (BMS_CellVoltNo40);
		fun >> (BMS_CellVoltNo41);
		fun >> (BMS_CellVoltNo42);
		fun >> (BMS_CellVoltNo43);
		fun >> (BMS_CellVoltNo44);
		fun >> (BMS_CellVoltNo45);
		fun >> (BMS_CellVoltNo46);
		fun >> (BMS_CellVoltNo47);
		fun >> (BMS_CellVoltNo48);
		fun >> (BMS_CellVoltNo49);
		fun >> (BMS_CellVoltNo50);
		fun >> (BMS_CellVoltNo51);
		fun >> (BMS_CellVoltNo52);
		fun >> (BMS_CellVoltNo53);
		fun >> (BMS_CellVoltNo54);
		fun >> (BMS_CellVoltNo55);
		fun >> (BMS_CellVoltNo56);
		fun >> (BMS_CellVoltNo57);
		fun >> (BMS_CellVoltNo58);
		fun >> (BMS_CellVoltNo59);
		fun >> (BMS_CellVoltNo60);
		fun >> (BMS_CellVoltNo61);
		fun >> (BMS_CellVoltNo62);
		fun >> (BMS_CellVoltNo63);
		fun >> (BMS_CellVoltNo64);
		fun >> (BMS_CellVoltNo65);
		fun >> (BMS_CellVoltNo66);
		fun >> (BMS_CellVoltNo67);
		fun >> (BMS_CellVoltNo68);
		fun >> (BMS_CellVoltNo69);
		fun >> (BMS_CellVoltNo70);
		fun >> (BMS_CellVoltNo71);
		fun >> (BMS_CellVoltNo72);
		fun >> (BMS_CellVoltNo73);
		fun >> (BMS_CellVoltNo74);
		fun >> (BMS_CellVoltNo75);
		fun >> (BMS_CellVoltNo76);
		fun >> (BMS_CellVoltNo77);
		fun >> (BMS_CellVoltNo78);
		fun >> (BMS_CellVoltNo79);
		fun >> (BMS_CellVoltNo80);
		fun >> (BMS_CellVoltNo81);
		fun >> (BMS_CellVoltNo82);
		fun >> (BMS_CellVoltNo83);
		fun >> (BMS_CellVoltNo84);
		fun >> (BMS_CellVoltNo85);
		fun >> (BMS_CellVoltNo86);
		fun >> (BMS_CellVoltNo87);
		fun >> (BMS_CellVoltNo88);
		fun >> (BMS_CellVoltNo89);
		fun >> (BMS_CellVoltNo90);
		fun >> (BMS_CellVoltNo91);
		fun >> (BMS_CellVoltNo92);
		fun >> (BMS_CellVoltNo93);
		fun >> (BMS_CellVoltNo94);
		fun >> (BMS_CellVoltNo95);
		fun >> (BMS_CellVoltNo96);
	}
};

#endif //____BDCTESTBMS4_H__
