#ifndef ____BDCTESTHVAC_H__
#define ____BDCTESTHVAC_H__


#include "cstdint"






struct BDCTestHVAC {
public:
	std::uint8_t HVAC_CoolFanDutyCycleReqVD;
	std::uint8_t HVAC_CoolFanDutyCycleReq;
	std::uint8_t HVAC_HighSpdFanReqVD;
	std::uint8_t HVAC_HighSpdFanReq;
	std::uint8_t HVAC_WarmupReq;
	std::uint8_t HVAC_AirCompressorReqVD;
	std::uint8_t HVAC_EngTorqReqVD;
	std::uint8_t HVAC_EngTorqReq;
	std::uint8_t HVAC_HeaterReqVD;
	std::uint8_t HVAC_HeaterReq;
	std::uint8_t HVAC_RefrigerantPrFault;
	std::uint16_t HVAC_RawExterTemp;
	std::uint16_t HVAC_RefrigerantPr;
	std::uint8_t HVAC_RawExterTempFault;
	std::uint8_t IPDS_EMSHSDSt;
	std::uint8_t IPDS_MainRelay1PowerSt;
	std::uint8_t IPDS_MainRelay2PowerSt;
	std::uint8_t IPDS_MainRelay3PowerSt;
	std::uint8_t IPDS_MainRelay4PowerSt;
	std::uint8_t STRLPowerSt;
	std::uint8_t IPDS_MainRelay1PowerFaultSt;
	std::uint8_t IPDS_MainRelay2PowerFaultSt;
	std::uint8_t IPDS_MainRelay3PowerFaultSt;
	std::uint8_t IPDS_MainRelay4PowerFaultSt;
	std::uint8_t STRLPowerFaultSt;
	std::uint8_t PCVHSDSt;
	std::uint8_t PCVHSDStVD;
	std::uint8_t PCVHSDFaultSt;
	std::uint8_t PCVHSDVolt;
	std::uint8_t ACPwrStgCtlAct;
	std::uint8_t ACPerStgErrSt;
	std::uint8_t ACPwrStgEnaCond;
	std::uint8_t FanRly1RlyPwrStgErrSt;
	std::uint8_t FanRly2RlyPwrStgErrSt;
	std::uint8_t FanPWMPwrStgErrSt;
	std::uint8_t FanPWMFaultSt;
	std::uint8_t FanPwrStgEnaCond;
	std::uint8_t FanRlyPwrStgCtlAct;
	std::uint8_t FanPwmPwrStgCtlAct;
	std::uint8_t FuelPumpSt;
	std::uint8_t FuelPumpVolt;
	std::uint8_t FuelPumpFaultSt;
	std::uint8_t UINM_HVAC_RrOffSWSt;
	std::uint8_t AQM_FragTasteRemanentRatio;
	std::uint8_t AQM_FraganceRatioWarn;
/*
	BDCTestHVAC() {}
	~BDCTestHVAC() {}
	BDCTestHVAC(const std::uint8_t _HVAC_CoolFanDutyCycleReqVD,const std::uint8_t _HVAC_CoolFanDutyCycleReq,const std::uint8_t _HVAC_HighSpdFanReqVD,const std::uint8_t _HVAC_HighSpdFanReq,const std::uint8_t _HVAC_WarmupReq,const std::uint8_t _HVAC_AirCompressorReqVD,const std::uint8_t _HVAC_EngTorqReqVD,const std::uint8_t _HVAC_EngTorqReq,const std::uint8_t _HVAC_HeaterReqVD,const std::uint8_t _HVAC_HeaterReq,const std::uint8_t _HVAC_RefrigerantPrFault,const std::uint16_t _HVAC_RawExterTemp,const std::uint16_t _HVAC_RefrigerantPr,const std::uint8_t _HVAC_RawExterTempFault,const std::uint8_t _IPDS_EMSHSDSt,const std::uint8_t _IPDS_MainRelay1PowerSt,const std::uint8_t _IPDS_MainRelay2PowerSt,const std::uint8_t _IPDS_MainRelay3PowerSt,const std::uint8_t _IPDS_MainRelay4PowerSt,const std::uint8_t _STRLPowerSt,const std::uint8_t _IPDS_MainRelay1PowerFaultSt,const std::uint8_t _IPDS_MainRelay2PowerFaultSt,const std::uint8_t _IPDS_MainRelay3PowerFaultSt,const std::uint8_t _IPDS_MainRelay4PowerFaultSt,const std::uint8_t _STRLPowerFaultSt,const std::uint8_t _PCVHSDSt,const std::uint8_t _PCVHSDStVD,const std::uint8_t _PCVHSDFaultSt,const std::uint8_t _PCVHSDVolt,const std::uint8_t _ACPwrStgCtlAct,const std::uint8_t _ACPerStgErrSt,const std::uint8_t _ACPwrStgEnaCond,const std::uint8_t _FanRly1RlyPwrStgErrSt,const std::uint8_t _FanRly2RlyPwrStgErrSt,const std::uint8_t _FanPWMPwrStgErrSt,const std::uint8_t _FanPWMFaultSt,const std::uint8_t _FanPwrStgEnaCond,const std::uint8_t _FanRlyPwrStgCtlAct,const std::uint8_t _FanPwmPwrStgCtlAct,const std::uint8_t _FuelPumpSt,const std::uint8_t _FuelPumpVolt,const std::uint8_t _FuelPumpFaultSt,const std::uint8_t _UINM_HVAC_RrOffSWSt,const std::uint8_t _AQM_FragTasteRemanentRatio,const std::uint8_t _AQM_FraganceRatioWarn):HVAC_CoolFanDutyCycleReqVD(_HVAC_CoolFanDutyCycleReqVD),HVAC_CoolFanDutyCycleReq(_HVAC_CoolFanDutyCycleReq),HVAC_HighSpdFanReqVD(_HVAC_HighSpdFanReqVD),HVAC_HighSpdFanReq(_HVAC_HighSpdFanReq),HVAC_WarmupReq(_HVAC_WarmupReq),HVAC_AirCompressorReqVD(_HVAC_AirCompressorReqVD),HVAC_EngTorqReqVD(_HVAC_EngTorqReqVD),HVAC_EngTorqReq(_HVAC_EngTorqReq),HVAC_HeaterReqVD(_HVAC_HeaterReqVD),HVAC_HeaterReq(_HVAC_HeaterReq),HVAC_RefrigerantPrFault(_HVAC_RefrigerantPrFault),HVAC_RawExterTemp(_HVAC_RawExterTemp),HVAC_RefrigerantPr(_HVAC_RefrigerantPr),HVAC_RawExterTempFault(_HVAC_RawExterTempFault),IPDS_EMSHSDSt(_IPDS_EMSHSDSt),IPDS_MainRelay1PowerSt(_IPDS_MainRelay1PowerSt),IPDS_MainRelay2PowerSt(_IPDS_MainRelay2PowerSt),IPDS_MainRelay3PowerSt(_IPDS_MainRelay3PowerSt),IPDS_MainRelay4PowerSt(_IPDS_MainRelay4PowerSt),STRLPowerSt(_STRLPowerSt),IPDS_MainRelay1PowerFaultSt(_IPDS_MainRelay1PowerFaultSt),IPDS_MainRelay2PowerFaultSt(_IPDS_MainRelay2PowerFaultSt),IPDS_MainRelay3PowerFaultSt(_IPDS_MainRelay3PowerFaultSt),IPDS_MainRelay4PowerFaultSt(_IPDS_MainRelay4PowerFaultSt),STRLPowerFaultSt(_STRLPowerFaultSt),PCVHSDSt(_PCVHSDSt),PCVHSDStVD(_PCVHSDStVD),PCVHSDFaultSt(_PCVHSDFaultSt),PCVHSDVolt(_PCVHSDVolt),ACPwrStgCtlAct(_ACPwrStgCtlAct),ACPerStgErrSt(_ACPerStgErrSt),ACPwrStgEnaCond(_ACPwrStgEnaCond),FanRly1RlyPwrStgErrSt(_FanRly1RlyPwrStgErrSt),FanRly2RlyPwrStgErrSt(_FanRly2RlyPwrStgErrSt),FanPWMPwrStgErrSt(_FanPWMPwrStgErrSt),FanPWMFaultSt(_FanPWMFaultSt),FanPwrStgEnaCond(_FanPwrStgEnaCond),FanRlyPwrStgCtlAct(_FanRlyPwrStgCtlAct),FanPwmPwrStgCtlAct(_FanPwmPwrStgCtlAct),FuelPumpSt(_FuelPumpSt),FuelPumpVolt(_FuelPumpVolt),FuelPumpFaultSt(_FuelPumpFaultSt),UINM_HVAC_RrOffSWSt(_UINM_HVAC_RrOffSWSt),AQM_FragTasteRemanentRatio(_AQM_FragTasteRemanentRatio),AQM_FraganceRatioWarn(_AQM_FraganceRatioWarn) {}
	BDCTestHVAC(const BDCTestHVAC &_x){
		HVAC_CoolFanDutyCycleReqVD = _x.HVAC_CoolFanDutyCycleReqVD;
		HVAC_CoolFanDutyCycleReq = _x.HVAC_CoolFanDutyCycleReq;
		HVAC_HighSpdFanReqVD = _x.HVAC_HighSpdFanReqVD;
		HVAC_HighSpdFanReq = _x.HVAC_HighSpdFanReq;
		HVAC_WarmupReq = _x.HVAC_WarmupReq;
		HVAC_AirCompressorReqVD = _x.HVAC_AirCompressorReqVD;
		HVAC_EngTorqReqVD = _x.HVAC_EngTorqReqVD;
		HVAC_EngTorqReq = _x.HVAC_EngTorqReq;
		HVAC_HeaterReqVD = _x.HVAC_HeaterReqVD;
		HVAC_HeaterReq = _x.HVAC_HeaterReq;
		HVAC_RefrigerantPrFault = _x.HVAC_RefrigerantPrFault;
		HVAC_RawExterTemp = _x.HVAC_RawExterTemp;
		HVAC_RefrigerantPr = _x.HVAC_RefrigerantPr;
		HVAC_RawExterTempFault = _x.HVAC_RawExterTempFault;
		IPDS_EMSHSDSt = _x.IPDS_EMSHSDSt;
		IPDS_MainRelay1PowerSt = _x.IPDS_MainRelay1PowerSt;
		IPDS_MainRelay2PowerSt = _x.IPDS_MainRelay2PowerSt;
		IPDS_MainRelay3PowerSt = _x.IPDS_MainRelay3PowerSt;
		IPDS_MainRelay4PowerSt = _x.IPDS_MainRelay4PowerSt;
		STRLPowerSt = _x.STRLPowerSt;
		IPDS_MainRelay1PowerFaultSt = _x.IPDS_MainRelay1PowerFaultSt;
		IPDS_MainRelay2PowerFaultSt = _x.IPDS_MainRelay2PowerFaultSt;
		IPDS_MainRelay3PowerFaultSt = _x.IPDS_MainRelay3PowerFaultSt;
		IPDS_MainRelay4PowerFaultSt = _x.IPDS_MainRelay4PowerFaultSt;
		STRLPowerFaultSt = _x.STRLPowerFaultSt;
		PCVHSDSt = _x.PCVHSDSt;
		PCVHSDStVD = _x.PCVHSDStVD;
		PCVHSDFaultSt = _x.PCVHSDFaultSt;
		PCVHSDVolt = _x.PCVHSDVolt;
		ACPwrStgCtlAct = _x.ACPwrStgCtlAct;
		ACPerStgErrSt = _x.ACPerStgErrSt;
		ACPwrStgEnaCond = _x.ACPwrStgEnaCond;
		FanRly1RlyPwrStgErrSt = _x.FanRly1RlyPwrStgErrSt;
		FanRly2RlyPwrStgErrSt = _x.FanRly2RlyPwrStgErrSt;
		FanPWMPwrStgErrSt = _x.FanPWMPwrStgErrSt;
		FanPWMFaultSt = _x.FanPWMFaultSt;
		FanPwrStgEnaCond = _x.FanPwrStgEnaCond;
		FanRlyPwrStgCtlAct = _x.FanRlyPwrStgCtlAct;
		FanPwmPwrStgCtlAct = _x.FanPwmPwrStgCtlAct;
		FuelPumpSt = _x.FuelPumpSt;
		FuelPumpVolt = _x.FuelPumpVolt;
		FuelPumpFaultSt = _x.FuelPumpFaultSt;
		UINM_HVAC_RrOffSWSt = _x.UINM_HVAC_RrOffSWSt;
		AQM_FragTasteRemanentRatio = _x.AQM_FragTasteRemanentRatio;
		AQM_FraganceRatioWarn = _x.AQM_FraganceRatioWarn;
	}
	BDCTestHVAC(BDCTestHVAC &&_x){
		HVAC_CoolFanDutyCycleReqVD = std::move(_x.HVAC_CoolFanDutyCycleReqVD);
		HVAC_CoolFanDutyCycleReq = std::move(_x.HVAC_CoolFanDutyCycleReq);
		HVAC_HighSpdFanReqVD = std::move(_x.HVAC_HighSpdFanReqVD);
		HVAC_HighSpdFanReq = std::move(_x.HVAC_HighSpdFanReq);
		HVAC_WarmupReq = std::move(_x.HVAC_WarmupReq);
		HVAC_AirCompressorReqVD = std::move(_x.HVAC_AirCompressorReqVD);
		HVAC_EngTorqReqVD = std::move(_x.HVAC_EngTorqReqVD);
		HVAC_EngTorqReq = std::move(_x.HVAC_EngTorqReq);
		HVAC_HeaterReqVD = std::move(_x.HVAC_HeaterReqVD);
		HVAC_HeaterReq = std::move(_x.HVAC_HeaterReq);
		HVAC_RefrigerantPrFault = std::move(_x.HVAC_RefrigerantPrFault);
		HVAC_RawExterTemp = std::move(_x.HVAC_RawExterTemp);
		HVAC_RefrigerantPr = std::move(_x.HVAC_RefrigerantPr);
		HVAC_RawExterTempFault = std::move(_x.HVAC_RawExterTempFault);
		IPDS_EMSHSDSt = std::move(_x.IPDS_EMSHSDSt);
		IPDS_MainRelay1PowerSt = std::move(_x.IPDS_MainRelay1PowerSt);
		IPDS_MainRelay2PowerSt = std::move(_x.IPDS_MainRelay2PowerSt);
		IPDS_MainRelay3PowerSt = std::move(_x.IPDS_MainRelay3PowerSt);
		IPDS_MainRelay4PowerSt = std::move(_x.IPDS_MainRelay4PowerSt);
		STRLPowerSt = std::move(_x.STRLPowerSt);
		IPDS_MainRelay1PowerFaultSt = std::move(_x.IPDS_MainRelay1PowerFaultSt);
		IPDS_MainRelay2PowerFaultSt = std::move(_x.IPDS_MainRelay2PowerFaultSt);
		IPDS_MainRelay3PowerFaultSt = std::move(_x.IPDS_MainRelay3PowerFaultSt);
		IPDS_MainRelay4PowerFaultSt = std::move(_x.IPDS_MainRelay4PowerFaultSt);
		STRLPowerFaultSt = std::move(_x.STRLPowerFaultSt);
		PCVHSDSt = std::move(_x.PCVHSDSt);
		PCVHSDStVD = std::move(_x.PCVHSDStVD);
		PCVHSDFaultSt = std::move(_x.PCVHSDFaultSt);
		PCVHSDVolt = std::move(_x.PCVHSDVolt);
		ACPwrStgCtlAct = std::move(_x.ACPwrStgCtlAct);
		ACPerStgErrSt = std::move(_x.ACPerStgErrSt);
		ACPwrStgEnaCond = std::move(_x.ACPwrStgEnaCond);
		FanRly1RlyPwrStgErrSt = std::move(_x.FanRly1RlyPwrStgErrSt);
		FanRly2RlyPwrStgErrSt = std::move(_x.FanRly2RlyPwrStgErrSt);
		FanPWMPwrStgErrSt = std::move(_x.FanPWMPwrStgErrSt);
		FanPWMFaultSt = std::move(_x.FanPWMFaultSt);
		FanPwrStgEnaCond = std::move(_x.FanPwrStgEnaCond);
		FanRlyPwrStgCtlAct = std::move(_x.FanRlyPwrStgCtlAct);
		FanPwmPwrStgCtlAct = std::move(_x.FanPwmPwrStgCtlAct);
		FuelPumpSt = std::move(_x.FuelPumpSt);
		FuelPumpVolt = std::move(_x.FuelPumpVolt);
		FuelPumpFaultSt = std::move(_x.FuelPumpFaultSt);
		UINM_HVAC_RrOffSWSt = std::move(_x.UINM_HVAC_RrOffSWSt);
		AQM_FragTasteRemanentRatio = std::move(_x.AQM_FragTasteRemanentRatio);
		AQM_FraganceRatioWarn = std::move(_x.AQM_FraganceRatioWarn);
	}
	BDCTestHVAC& operator=(const BDCTestHVAC &_x){
		HVAC_CoolFanDutyCycleReqVD = _x.HVAC_CoolFanDutyCycleReqVD;
		HVAC_CoolFanDutyCycleReq = _x.HVAC_CoolFanDutyCycleReq;
		HVAC_HighSpdFanReqVD = _x.HVAC_HighSpdFanReqVD;
		HVAC_HighSpdFanReq = _x.HVAC_HighSpdFanReq;
		HVAC_WarmupReq = _x.HVAC_WarmupReq;
		HVAC_AirCompressorReqVD = _x.HVAC_AirCompressorReqVD;
		HVAC_EngTorqReqVD = _x.HVAC_EngTorqReqVD;
		HVAC_EngTorqReq = _x.HVAC_EngTorqReq;
		HVAC_HeaterReqVD = _x.HVAC_HeaterReqVD;
		HVAC_HeaterReq = _x.HVAC_HeaterReq;
		HVAC_RefrigerantPrFault = _x.HVAC_RefrigerantPrFault;
		HVAC_RawExterTemp = _x.HVAC_RawExterTemp;
		HVAC_RefrigerantPr = _x.HVAC_RefrigerantPr;
		HVAC_RawExterTempFault = _x.HVAC_RawExterTempFault;
		IPDS_EMSHSDSt = _x.IPDS_EMSHSDSt;
		IPDS_MainRelay1PowerSt = _x.IPDS_MainRelay1PowerSt;
		IPDS_MainRelay2PowerSt = _x.IPDS_MainRelay2PowerSt;
		IPDS_MainRelay3PowerSt = _x.IPDS_MainRelay3PowerSt;
		IPDS_MainRelay4PowerSt = _x.IPDS_MainRelay4PowerSt;
		STRLPowerSt = _x.STRLPowerSt;
		IPDS_MainRelay1PowerFaultSt = _x.IPDS_MainRelay1PowerFaultSt;
		IPDS_MainRelay2PowerFaultSt = _x.IPDS_MainRelay2PowerFaultSt;
		IPDS_MainRelay3PowerFaultSt = _x.IPDS_MainRelay3PowerFaultSt;
		IPDS_MainRelay4PowerFaultSt = _x.IPDS_MainRelay4PowerFaultSt;
		STRLPowerFaultSt = _x.STRLPowerFaultSt;
		PCVHSDSt = _x.PCVHSDSt;
		PCVHSDStVD = _x.PCVHSDStVD;
		PCVHSDFaultSt = _x.PCVHSDFaultSt;
		PCVHSDVolt = _x.PCVHSDVolt;
		ACPwrStgCtlAct = _x.ACPwrStgCtlAct;
		ACPerStgErrSt = _x.ACPerStgErrSt;
		ACPwrStgEnaCond = _x.ACPwrStgEnaCond;
		FanRly1RlyPwrStgErrSt = _x.FanRly1RlyPwrStgErrSt;
		FanRly2RlyPwrStgErrSt = _x.FanRly2RlyPwrStgErrSt;
		FanPWMPwrStgErrSt = _x.FanPWMPwrStgErrSt;
		FanPWMFaultSt = _x.FanPWMFaultSt;
		FanPwrStgEnaCond = _x.FanPwrStgEnaCond;
		FanRlyPwrStgCtlAct = _x.FanRlyPwrStgCtlAct;
		FanPwmPwrStgCtlAct = _x.FanPwmPwrStgCtlAct;
		FuelPumpSt = _x.FuelPumpSt;
		FuelPumpVolt = _x.FuelPumpVolt;
		FuelPumpFaultSt = _x.FuelPumpFaultSt;
		UINM_HVAC_RrOffSWSt = _x.UINM_HVAC_RrOffSWSt;
		AQM_FragTasteRemanentRatio = _x.AQM_FragTasteRemanentRatio;
		AQM_FraganceRatioWarn = _x.AQM_FraganceRatioWarn;
		return *this;
	}
	BDCTestHVAC& operator=(BDCTestHVAC &&_x){
		HVAC_CoolFanDutyCycleReqVD = std::move(_x.HVAC_CoolFanDutyCycleReqVD);
		HVAC_CoolFanDutyCycleReq = std::move(_x.HVAC_CoolFanDutyCycleReq);
		HVAC_HighSpdFanReqVD = std::move(_x.HVAC_HighSpdFanReqVD);
		HVAC_HighSpdFanReq = std::move(_x.HVAC_HighSpdFanReq);
		HVAC_WarmupReq = std::move(_x.HVAC_WarmupReq);
		HVAC_AirCompressorReqVD = std::move(_x.HVAC_AirCompressorReqVD);
		HVAC_EngTorqReqVD = std::move(_x.HVAC_EngTorqReqVD);
		HVAC_EngTorqReq = std::move(_x.HVAC_EngTorqReq);
		HVAC_HeaterReqVD = std::move(_x.HVAC_HeaterReqVD);
		HVAC_HeaterReq = std::move(_x.HVAC_HeaterReq);
		HVAC_RefrigerantPrFault = std::move(_x.HVAC_RefrigerantPrFault);
		HVAC_RawExterTemp = std::move(_x.HVAC_RawExterTemp);
		HVAC_RefrigerantPr = std::move(_x.HVAC_RefrigerantPr);
		HVAC_RawExterTempFault = std::move(_x.HVAC_RawExterTempFault);
		IPDS_EMSHSDSt = std::move(_x.IPDS_EMSHSDSt);
		IPDS_MainRelay1PowerSt = std::move(_x.IPDS_MainRelay1PowerSt);
		IPDS_MainRelay2PowerSt = std::move(_x.IPDS_MainRelay2PowerSt);
		IPDS_MainRelay3PowerSt = std::move(_x.IPDS_MainRelay3PowerSt);
		IPDS_MainRelay4PowerSt = std::move(_x.IPDS_MainRelay4PowerSt);
		STRLPowerSt = std::move(_x.STRLPowerSt);
		IPDS_MainRelay1PowerFaultSt = std::move(_x.IPDS_MainRelay1PowerFaultSt);
		IPDS_MainRelay2PowerFaultSt = std::move(_x.IPDS_MainRelay2PowerFaultSt);
		IPDS_MainRelay3PowerFaultSt = std::move(_x.IPDS_MainRelay3PowerFaultSt);
		IPDS_MainRelay4PowerFaultSt = std::move(_x.IPDS_MainRelay4PowerFaultSt);
		STRLPowerFaultSt = std::move(_x.STRLPowerFaultSt);
		PCVHSDSt = std::move(_x.PCVHSDSt);
		PCVHSDStVD = std::move(_x.PCVHSDStVD);
		PCVHSDFaultSt = std::move(_x.PCVHSDFaultSt);
		PCVHSDVolt = std::move(_x.PCVHSDVolt);
		ACPwrStgCtlAct = std::move(_x.ACPwrStgCtlAct);
		ACPerStgErrSt = std::move(_x.ACPerStgErrSt);
		ACPwrStgEnaCond = std::move(_x.ACPwrStgEnaCond);
		FanRly1RlyPwrStgErrSt = std::move(_x.FanRly1RlyPwrStgErrSt);
		FanRly2RlyPwrStgErrSt = std::move(_x.FanRly2RlyPwrStgErrSt);
		FanPWMPwrStgErrSt = std::move(_x.FanPWMPwrStgErrSt);
		FanPWMFaultSt = std::move(_x.FanPWMFaultSt);
		FanPwrStgEnaCond = std::move(_x.FanPwrStgEnaCond);
		FanRlyPwrStgCtlAct = std::move(_x.FanRlyPwrStgCtlAct);
		FanPwmPwrStgCtlAct = std::move(_x.FanPwmPwrStgCtlAct);
		FuelPumpSt = std::move(_x.FuelPumpSt);
		FuelPumpVolt = std::move(_x.FuelPumpVolt);
		FuelPumpFaultSt = std::move(_x.FuelPumpFaultSt);
		UINM_HVAC_RrOffSWSt = std::move(_x.UINM_HVAC_RrOffSWSt);
		AQM_FragTasteRemanentRatio = std::move(_x.AQM_FragTasteRemanentRatio);
		AQM_FraganceRatioWarn = std::move(_x.AQM_FraganceRatioWarn);
		return *this;
	}
*/

	using IsEnumerableTag = void;
	template<typename F>
	void enumerate(F& fun) {
		fun(HVAC_CoolFanDutyCycleReqVD);
		fun(HVAC_CoolFanDutyCycleReq);
		fun(HVAC_HighSpdFanReqVD);
		fun(HVAC_HighSpdFanReq);
		fun(HVAC_WarmupReq);
		fun(HVAC_AirCompressorReqVD);
		fun(HVAC_EngTorqReqVD);
		fun(HVAC_EngTorqReq);
		fun(HVAC_HeaterReqVD);
		fun(HVAC_HeaterReq);
		fun(HVAC_RefrigerantPrFault);
		fun(HVAC_RawExterTemp);
		fun(HVAC_RefrigerantPr);
		fun(HVAC_RawExterTempFault);
		fun(IPDS_EMSHSDSt);
		fun(IPDS_MainRelay1PowerSt);
		fun(IPDS_MainRelay2PowerSt);
		fun(IPDS_MainRelay3PowerSt);
		fun(IPDS_MainRelay4PowerSt);
		fun(STRLPowerSt);
		fun(IPDS_MainRelay1PowerFaultSt);
		fun(IPDS_MainRelay2PowerFaultSt);
		fun(IPDS_MainRelay3PowerFaultSt);
		fun(IPDS_MainRelay4PowerFaultSt);
		fun(STRLPowerFaultSt);
		fun(PCVHSDSt);
		fun(PCVHSDStVD);
		fun(PCVHSDFaultSt);
		fun(PCVHSDVolt);
		fun(ACPwrStgCtlAct);
		fun(ACPerStgErrSt);
		fun(ACPwrStgEnaCond);
		fun(FanRly1RlyPwrStgErrSt);
		fun(FanRly2RlyPwrStgErrSt);
		fun(FanPWMPwrStgErrSt);
		fun(FanPWMFaultSt);
		fun(FanPwrStgEnaCond);
		fun(FanRlyPwrStgCtlAct);
		fun(FanPwmPwrStgCtlAct);
		fun(FuelPumpSt);
		fun(FuelPumpVolt);
		fun(FuelPumpFaultSt);
		fun(UINM_HVAC_RrOffSWSt);
		fun(AQM_FragTasteRemanentRatio);
		fun(AQM_FraganceRatioWarn);
	}

	template<typename F>
	void GetSize(F& fun) const{
		fun(HVAC_CoolFanDutyCycleReqVD);
		fun(HVAC_CoolFanDutyCycleReq);
		fun(HVAC_HighSpdFanReqVD);
		fun(HVAC_HighSpdFanReq);
		fun(HVAC_WarmupReq);
		fun(HVAC_AirCompressorReqVD);
		fun(HVAC_EngTorqReqVD);
		fun(HVAC_EngTorqReq);
		fun(HVAC_HeaterReqVD);
		fun(HVAC_HeaterReq);
		fun(HVAC_RefrigerantPrFault);
		fun(HVAC_RawExterTemp);
		fun(HVAC_RefrigerantPr);
		fun(HVAC_RawExterTempFault);
		fun(IPDS_EMSHSDSt);
		fun(IPDS_MainRelay1PowerSt);
		fun(IPDS_MainRelay2PowerSt);
		fun(IPDS_MainRelay3PowerSt);
		fun(IPDS_MainRelay4PowerSt);
		fun(STRLPowerSt);
		fun(IPDS_MainRelay1PowerFaultSt);
		fun(IPDS_MainRelay2PowerFaultSt);
		fun(IPDS_MainRelay3PowerFaultSt);
		fun(IPDS_MainRelay4PowerFaultSt);
		fun(STRLPowerFaultSt);
		fun(PCVHSDSt);
		fun(PCVHSDStVD);
		fun(PCVHSDFaultSt);
		fun(PCVHSDVolt);
		fun(ACPwrStgCtlAct);
		fun(ACPerStgErrSt);
		fun(ACPwrStgEnaCond);
		fun(FanRly1RlyPwrStgErrSt);
		fun(FanRly2RlyPwrStgErrSt);
		fun(FanPWMPwrStgErrSt);
		fun(FanPWMFaultSt);
		fun(FanPwrStgEnaCond);
		fun(FanRlyPwrStgCtlAct);
		fun(FanPwmPwrStgCtlAct);
		fun(FuelPumpSt);
		fun(FuelPumpVolt);
		fun(FuelPumpFaultSt);
		fun(UINM_HVAC_RrOffSWSt);
		fun(AQM_FragTasteRemanentRatio);
		fun(AQM_FraganceRatioWarn);
	}
	template<typename F>
	void serialize(F& fun) const{
		fun << (HVAC_CoolFanDutyCycleReqVD);
		fun << (HVAC_CoolFanDutyCycleReq);
		fun << (HVAC_HighSpdFanReqVD);
		fun << (HVAC_HighSpdFanReq);
		fun << (HVAC_WarmupReq);
		fun << (HVAC_AirCompressorReqVD);
		fun << (HVAC_EngTorqReqVD);
		fun << (HVAC_EngTorqReq);
		fun << (HVAC_HeaterReqVD);
		fun << (HVAC_HeaterReq);
		fun << (HVAC_RefrigerantPrFault);
		fun << (HVAC_RawExterTemp);
		fun << (HVAC_RefrigerantPr);
		fun << (HVAC_RawExterTempFault);
		fun << (IPDS_EMSHSDSt);
		fun << (IPDS_MainRelay1PowerSt);
		fun << (IPDS_MainRelay2PowerSt);
		fun << (IPDS_MainRelay3PowerSt);
		fun << (IPDS_MainRelay4PowerSt);
		fun << (STRLPowerSt);
		fun << (IPDS_MainRelay1PowerFaultSt);
		fun << (IPDS_MainRelay2PowerFaultSt);
		fun << (IPDS_MainRelay3PowerFaultSt);
		fun << (IPDS_MainRelay4PowerFaultSt);
		fun << (STRLPowerFaultSt);
		fun << (PCVHSDSt);
		fun << (PCVHSDStVD);
		fun << (PCVHSDFaultSt);
		fun << (PCVHSDVolt);
		fun << (ACPwrStgCtlAct);
		fun << (ACPerStgErrSt);
		fun << (ACPwrStgEnaCond);
		fun << (FanRly1RlyPwrStgErrSt);
		fun << (FanRly2RlyPwrStgErrSt);
		fun << (FanPWMPwrStgErrSt);
		fun << (FanPWMFaultSt);
		fun << (FanPwrStgEnaCond);
		fun << (FanRlyPwrStgCtlAct);
		fun << (FanPwmPwrStgCtlAct);
		fun << (FuelPumpSt);
		fun << (FuelPumpVolt);
		fun << (FuelPumpFaultSt);
		fun << (UINM_HVAC_RrOffSWSt);
		fun << (AQM_FragTasteRemanentRatio);
		fun << (AQM_FraganceRatioWarn);
	}
	template<typename F>
	void deserialize(F& fun){
		fun >> (HVAC_CoolFanDutyCycleReqVD);
		fun >> (HVAC_CoolFanDutyCycleReq);
		fun >> (HVAC_HighSpdFanReqVD);
		fun >> (HVAC_HighSpdFanReq);
		fun >> (HVAC_WarmupReq);
		fun >> (HVAC_AirCompressorReqVD);
		fun >> (HVAC_EngTorqReqVD);
		fun >> (HVAC_EngTorqReq);
		fun >> (HVAC_HeaterReqVD);
		fun >> (HVAC_HeaterReq);
		fun >> (HVAC_RefrigerantPrFault);
		fun >> (HVAC_RawExterTemp);
		fun >> (HVAC_RefrigerantPr);
		fun >> (HVAC_RawExterTempFault);
		fun >> (IPDS_EMSHSDSt);
		fun >> (IPDS_MainRelay1PowerSt);
		fun >> (IPDS_MainRelay2PowerSt);
		fun >> (IPDS_MainRelay3PowerSt);
		fun >> (IPDS_MainRelay4PowerSt);
		fun >> (STRLPowerSt);
		fun >> (IPDS_MainRelay1PowerFaultSt);
		fun >> (IPDS_MainRelay2PowerFaultSt);
		fun >> (IPDS_MainRelay3PowerFaultSt);
		fun >> (IPDS_MainRelay4PowerFaultSt);
		fun >> (STRLPowerFaultSt);
		fun >> (PCVHSDSt);
		fun >> (PCVHSDStVD);
		fun >> (PCVHSDFaultSt);
		fun >> (PCVHSDVolt);
		fun >> (ACPwrStgCtlAct);
		fun >> (ACPerStgErrSt);
		fun >> (ACPwrStgEnaCond);
		fun >> (FanRly1RlyPwrStgErrSt);
		fun >> (FanRly2RlyPwrStgErrSt);
		fun >> (FanPWMPwrStgErrSt);
		fun >> (FanPWMFaultSt);
		fun >> (FanPwrStgEnaCond);
		fun >> (FanRlyPwrStgCtlAct);
		fun >> (FanPwmPwrStgCtlAct);
		fun >> (FuelPumpSt);
		fun >> (FuelPumpVolt);
		fun >> (FuelPumpFaultSt);
		fun >> (UINM_HVAC_RrOffSWSt);
		fun >> (AQM_FragTasteRemanentRatio);
		fun >> (AQM_FraganceRatioWarn);
	}
};

#endif //____BDCTESTHVAC_H__
