#ifndef ____BDCBMSAFE_H__
#define ____BDCBMSAFE_H__


#include "cstdint"






struct BDCBMSAFE {
public:
	std::uint16_t BMS_AFEWakeUpState;
	std::uint16_t BMS_ResetByAFESetErr;
	std::uint16_t BMS_NrResetByAFESetErr;
	std::uint16_t BMS_AFE1_OVThreshold;
	std::uint16_t BMS_AFE2_OVThreshold;
	std::uint16_t BMS_AFE3_OVThreshold;
	std::uint16_t BMS_AFE4_OVThreshold;
	std::uint16_t BMS_AFE5_OVThreshold;
	std::uint16_t BMS_AFE6_OVThreshold;
	std::uint16_t BMS_AFE7_OVThreshold;
	std::uint16_t BMS_AFE8_OVThreshold;
	std::uint16_t BMS_AFE9_OVThreshold;
	std::uint16_t BMS_AFE10_OVThreshold;
	std::uint16_t BMS_AFE11_OVThreshold;
	std::uint16_t BMS_AFE12_OVThreshold;
	std::uint16_t BMS_AFE13_OVThreshold;
	std::uint16_t BMS_AFE14_OVThreshold;
	std::uint16_t BMS_AFE15_OVThreshold;
	std::uint16_t BMS_AFE16_OVThreshold;
	std::uint16_t BMS_AFE17_OVThreshold;
	std::uint16_t BMS_AFE18_OVThreshold;
	std::uint16_t BMS_AFE19_OVThreshold;
	std::uint16_t BMS_AFE20_OVThreshold;
	std::uint16_t BMS_AFE1_WakeUpSrc;
	std::uint16_t BMS_AFE2_WakeUpSrc;
	std::uint16_t BMS_AFE3_WakeUpSrc;
	std::uint16_t BMS_AFE4_WakeUpSrc;
	std::uint16_t BMS_AFE5_WakeUpSrc;
	std::uint16_t BMS_AFE6_WakeUpSrc;
	std::uint16_t BMS_AFE7_WakeUpSrc;
	std::uint16_t BMS_AFE8_WakeUpSrc;
	std::uint16_t BMS_AFE9_WakeUpSrc;
	std::uint16_t BMS_AFE10_WakeUpSrc;
	std::uint16_t BMS_AFE11_WakeUpSrc;
	std::uint16_t BMS_AFE12_WakeUpSrc;
	std::uint16_t BMS_AFE13_WakeUpSrc;
	std::uint16_t BMS_AFE14_WakeUpSrc;
	std::uint16_t BMS_AFE15_WakeUpSrc;
	std::uint16_t BMS_AFE16_WakeUpSrc;
	std::uint16_t BMS_AFE17_WakeUpSrc;
	std::uint16_t BMS_AFE18_WakeUpSrc;
	std::uint16_t BMS_AFE19_WakeUpSrc;
	std::uint16_t BMS_AFE20_WakeUpSrc;
	std::uint16_t BMS_AFE1_UVThreshold;
	std::uint16_t BMS_AFE2_UVThreshold;
	std::uint16_t BMS_AFE3_UVThreshold;
	std::uint16_t BMS_AFE4_UVThreshold;
	std::uint16_t BMS_AFE5_UVThreshold;
	std::uint16_t BMS_AFE6_UVThreshold;
	std::uint16_t BMS_AFE7_UVThreshold;
	std::uint16_t BMS_AFE8_UVThreshold;
	std::uint16_t BMS_AFE9_UVThreshold;
	std::uint16_t BMS_AFE10_UVThreshold;
	std::uint16_t BMS_AFE11_UVThreshold;
	std::uint16_t BMS_AFE12_UVThreshold;
	std::uint16_t BMS_AFE13_UVThreshold;
	std::uint16_t BMS_AFE14_UVThreshold;
	std::uint16_t BMS_AFE15_UVThreshold;
	std::uint16_t BMS_AFE16_UVThreshold;
	std::uint16_t BMS_AFE17_UVThreshold;
	std::uint16_t BMS_AFE18_UVThreshold;
	std::uint16_t BMS_AFE19_UVThreshold;
	std::uint16_t BMS_AFE20_UVThreshold;
	std::uint16_t BMS_AFE1_OTThreshold;
	std::uint16_t BMS_AFE2_OTThreshold;
	std::uint16_t BMS_AFE3_OTThreshold;
	std::uint16_t BMS_AFE4_OTThreshold;
	std::uint16_t BMS_AFE5_OTThreshold;
	std::uint16_t BMS_AFE6_OTThreshold;
	std::uint16_t BMS_AFE7_OTThreshold;
	std::uint16_t BMS_AFE8_OTThreshold;
	std::uint16_t BMS_AFE9_OTThreshold;
	std::uint16_t BMS_AFE10_OTThreshold;
	std::uint16_t BMS_AFE11_OTThreshold;
	std::uint16_t BMS_AFE12_OTThreshold;
	std::uint16_t BMS_AFE13_OTThreshold;
	std::uint16_t BMS_AFE14_OTThreshold;
	std::uint16_t BMS_AFE15_OTThreshold;
	std::uint16_t BMS_AFE16_OTThreshold;
	std::uint16_t BMS_AFE17_OTThreshold;
	std::uint16_t BMS_AFE18_OTThreshold;
	std::uint16_t BMS_AFE19_OTThreshold;
	std::uint16_t BMS_AFE20_OTThreshold;
	std::uint8_t BMS_AFE1_OTWakeUp_Enable;
	std::uint8_t BMS_AFE2_OTWakeUp_Enable;
	std::uint8_t BMS_AFE3_OTWakeUp_Enable;
	std::uint8_t BMS_AFE4_OTWakeUp_Enable;
	std::uint8_t BMS_AFE5_OTWakeUp_Enable;
	std::uint8_t BMS_AFE6_OTWakeUp_Enable;
	std::uint8_t BMS_AFE7_OTWakeUp_Enable;
	std::uint8_t BMS_AFE8_OTWakeUp_Enable;
	std::uint8_t BMS_AFE9_OTWakeUp_Enable;
	std::uint8_t BMS_AFE10_OTWakeUp_Enable;
	std::uint8_t BMS_AFE11_OTWakeUp_Enable;
	std::uint8_t BMS_AFE12_OTWakeUp_Enable;
	std::uint8_t BMS_AFE13_OTWakeUp_Enable;
	std::uint8_t BMS_AFE14_OTWakeUp_Enable;
	std::uint8_t BMS_AFE15_OTWakeUp_Enable;
	std::uint8_t BMS_AFE16_OTWakeUp_Enable;
	std::uint8_t BMS_AFE17_OTWakeUp_Enable;
	std::uint8_t BMS_AFE18_OTWakeUp_Enable;
	std::uint8_t BMS_AFE19_OTWakeUp_Enable;
	std::uint8_t BMS_AFE20_OTWakeUp_Enable;
	std::uint8_t BMS_AFE1_OVWakeUp_Enable;
	std::uint8_t BMS_AFE2_OVWakeUp_Enable;
	std::uint8_t BMS_AFE3_OVWakeUp_Enable;
	std::uint8_t BMS_AFE4_OVWakeUp_Enable;
	std::uint8_t BMS_AFE5_OVWakeUp_Enable;
	std::uint8_t BMS_AFE6_OVWakeUp_Enable;
	std::uint8_t BMS_AFE7_OVWakeUp_Enable;
	std::uint8_t BMS_AFE8_OVWakeUp_Enable;
	std::uint8_t BMS_AFE9_OVWakeUp_Enable;
	std::uint8_t BMS_AFE10_OVWakeUp_Enable;
	std::uint8_t BMS_AFE11_OVWakeUp_Enable;
	std::uint8_t BMS_AFE12_OVWakeUp_Enable;
	std::uint8_t BMS_AFE13_OVWakeUp_Enable;
	std::uint8_t BMS_AFE14_OVWakeUp_Enable;
	std::uint8_t BMS_AFE15_OVWakeUp_Enable;
	std::uint8_t BMS_AFE16_OVWakeUp_Enable;
	std::uint8_t BMS_AFE17_OVWakeUp_Enable;
	std::uint8_t BMS_AFE18_OVWakeUp_Enable;
	std::uint8_t BMS_AFE19_OVWakeUp_Enable;
	std::uint8_t BMS_AFE20_OVWakeUp_Enable;
	std::uint8_t BMS_AFE1_UVWakeUp_Enable;
	std::uint8_t BMS_AFE2_UVWakeUp_Enable;
	std::uint8_t BMS_AFE3_UVWakeUp_Enable;
	std::uint8_t BMS_AFE4_UVWakeUp_Enable;
	std::uint8_t BMS_AFE5_UVWakeUp_Enable;
	std::uint8_t BMS_AFE6_UVWakeUp_Enable;
	std::uint8_t BMS_AFE7_UVWakeUp_Enable;
	std::uint8_t BMS_AFE8_UVWakeUp_Enable;
	std::uint8_t BMS_AFE9_UVWakeUp_Enable;
	std::uint8_t BMS_AFE10_UVWakeUp_Enable;
	std::uint8_t BMS_AFE11_UVWakeUp_Enable;
	std::uint8_t BMS_AFE12_UVWakeUp_Enable;
	std::uint8_t BMS_AFE13_UVWakeUp_Enable;
	std::uint8_t BMS_AFE14_UVWakeUp_Enable;
	std::uint8_t BMS_AFE15_UVWakeUp_Enable;
	std::uint8_t BMS_AFE16_UVWakeUp_Enable;
	std::uint8_t BMS_AFE17_UVWakeUp_Enable;
	std::uint8_t BMS_AFE18_UVWakeUp_Enable;
	std::uint8_t BMS_AFE19_UVWakeUp_Enable;
	std::uint8_t BMS_AFE20_UVWakeUp_Enable;
/*
	BDCBMSAFE() {}
	~BDCBMSAFE() {}
	BDCBMSAFE(const std::uint16_t _BMS_AFEWakeUpState,const std::uint16_t _BMS_ResetByAFESetErr,const std::uint16_t _BMS_NrResetByAFESetErr,const std::uint16_t _BMS_AFE1_OVThreshold,const std::uint16_t _BMS_AFE2_OVThreshold,const std::uint16_t _BMS_AFE3_OVThreshold,const std::uint16_t _BMS_AFE4_OVThreshold,const std::uint16_t _BMS_AFE5_OVThreshold,const std::uint16_t _BMS_AFE6_OVThreshold,const std::uint16_t _BMS_AFE7_OVThreshold,const std::uint16_t _BMS_AFE8_OVThreshold,const std::uint16_t _BMS_AFE9_OVThreshold,const std::uint16_t _BMS_AFE10_OVThreshold,const std::uint16_t _BMS_AFE11_OVThreshold,const std::uint16_t _BMS_AFE12_OVThreshold,const std::uint16_t _BMS_AFE13_OVThreshold,const std::uint16_t _BMS_AFE14_OVThreshold,const std::uint16_t _BMS_AFE15_OVThreshold,const std::uint16_t _BMS_AFE16_OVThreshold,const std::uint16_t _BMS_AFE17_OVThreshold,const std::uint16_t _BMS_AFE18_OVThreshold,const std::uint16_t _BMS_AFE19_OVThreshold,const std::uint16_t _BMS_AFE20_OVThreshold,const std::uint16_t _BMS_AFE1_WakeUpSrc,const std::uint16_t _BMS_AFE2_WakeUpSrc,const std::uint16_t _BMS_AFE3_WakeUpSrc,const std::uint16_t _BMS_AFE4_WakeUpSrc,const std::uint16_t _BMS_AFE5_WakeUpSrc,const std::uint16_t _BMS_AFE6_WakeUpSrc,const std::uint16_t _BMS_AFE7_WakeUpSrc,const std::uint16_t _BMS_AFE8_WakeUpSrc,const std::uint16_t _BMS_AFE9_WakeUpSrc,const std::uint16_t _BMS_AFE10_WakeUpSrc,const std::uint16_t _BMS_AFE11_WakeUpSrc,const std::uint16_t _BMS_AFE12_WakeUpSrc,const std::uint16_t _BMS_AFE13_WakeUpSrc,const std::uint16_t _BMS_AFE14_WakeUpSrc,const std::uint16_t _BMS_AFE15_WakeUpSrc,const std::uint16_t _BMS_AFE16_WakeUpSrc,const std::uint16_t _BMS_AFE17_WakeUpSrc,const std::uint16_t _BMS_AFE18_WakeUpSrc,const std::uint16_t _BMS_AFE19_WakeUpSrc,const std::uint16_t _BMS_AFE20_WakeUpSrc,const std::uint16_t _BMS_AFE1_UVThreshold,const std::uint16_t _BMS_AFE2_UVThreshold,const std::uint16_t _BMS_AFE3_UVThreshold,const std::uint16_t _BMS_AFE4_UVThreshold,const std::uint16_t _BMS_AFE5_UVThreshold,const std::uint16_t _BMS_AFE6_UVThreshold,const std::uint16_t _BMS_AFE7_UVThreshold,const std::uint16_t _BMS_AFE8_UVThreshold,const std::uint16_t _BMS_AFE9_UVThreshold,const std::uint16_t _BMS_AFE10_UVThreshold,const std::uint16_t _BMS_AFE11_UVThreshold,const std::uint16_t _BMS_AFE12_UVThreshold,const std::uint16_t _BMS_AFE13_UVThreshold,const std::uint16_t _BMS_AFE14_UVThreshold,const std::uint16_t _BMS_AFE15_UVThreshold,const std::uint16_t _BMS_AFE16_UVThreshold,const std::uint16_t _BMS_AFE17_UVThreshold,const std::uint16_t _BMS_AFE18_UVThreshold,const std::uint16_t _BMS_AFE19_UVThreshold,const std::uint16_t _BMS_AFE20_UVThreshold,const std::uint16_t _BMS_AFE1_OTThreshold,const std::uint16_t _BMS_AFE2_OTThreshold,const std::uint16_t _BMS_AFE3_OTThreshold,const std::uint16_t _BMS_AFE4_OTThreshold,const std::uint16_t _BMS_AFE5_OTThreshold,const std::uint16_t _BMS_AFE6_OTThreshold,const std::uint16_t _BMS_AFE7_OTThreshold,const std::uint16_t _BMS_AFE8_OTThreshold,const std::uint16_t _BMS_AFE9_OTThreshold,const std::uint16_t _BMS_AFE10_OTThreshold,const std::uint16_t _BMS_AFE11_OTThreshold,const std::uint16_t _BMS_AFE12_OTThreshold,const std::uint16_t _BMS_AFE13_OTThreshold,const std::uint16_t _BMS_AFE14_OTThreshold,const std::uint16_t _BMS_AFE15_OTThreshold,const std::uint16_t _BMS_AFE16_OTThreshold,const std::uint16_t _BMS_AFE17_OTThreshold,const std::uint16_t _BMS_AFE18_OTThreshold,const std::uint16_t _BMS_AFE19_OTThreshold,const std::uint16_t _BMS_AFE20_OTThreshold,const std::uint8_t _BMS_AFE1_OTWakeUp_Enable,const std::uint8_t _BMS_AFE2_OTWakeUp_Enable,const std::uint8_t _BMS_AFE3_OTWakeUp_Enable,const std::uint8_t _BMS_AFE4_OTWakeUp_Enable,const std::uint8_t _BMS_AFE5_OTWakeUp_Enable,const std::uint8_t _BMS_AFE6_OTWakeUp_Enable,const std::uint8_t _BMS_AFE7_OTWakeUp_Enable,const std::uint8_t _BMS_AFE8_OTWakeUp_Enable,const std::uint8_t _BMS_AFE9_OTWakeUp_Enable,const std::uint8_t _BMS_AFE10_OTWakeUp_Enable,const std::uint8_t _BMS_AFE11_OTWakeUp_Enable,const std::uint8_t _BMS_AFE12_OTWakeUp_Enable,const std::uint8_t _BMS_AFE13_OTWakeUp_Enable,const std::uint8_t _BMS_AFE14_OTWakeUp_Enable,const std::uint8_t _BMS_AFE15_OTWakeUp_Enable,const std::uint8_t _BMS_AFE16_OTWakeUp_Enable,const std::uint8_t _BMS_AFE17_OTWakeUp_Enable,const std::uint8_t _BMS_AFE18_OTWakeUp_Enable,const std::uint8_t _BMS_AFE19_OTWakeUp_Enable,const std::uint8_t _BMS_AFE20_OTWakeUp_Enable,const std::uint8_t _BMS_AFE1_OVWakeUp_Enable,const std::uint8_t _BMS_AFE2_OVWakeUp_Enable,const std::uint8_t _BMS_AFE3_OVWakeUp_Enable,const std::uint8_t _BMS_AFE4_OVWakeUp_Enable,const std::uint8_t _BMS_AFE5_OVWakeUp_Enable,const std::uint8_t _BMS_AFE6_OVWakeUp_Enable,const std::uint8_t _BMS_AFE7_OVWakeUp_Enable,const std::uint8_t _BMS_AFE8_OVWakeUp_Enable,const std::uint8_t _BMS_AFE9_OVWakeUp_Enable,const std::uint8_t _BMS_AFE10_OVWakeUp_Enable,const std::uint8_t _BMS_AFE11_OVWakeUp_Enable,const std::uint8_t _BMS_AFE12_OVWakeUp_Enable,const std::uint8_t _BMS_AFE13_OVWakeUp_Enable,const std::uint8_t _BMS_AFE14_OVWakeUp_Enable,const std::uint8_t _BMS_AFE15_OVWakeUp_Enable,const std::uint8_t _BMS_AFE16_OVWakeUp_Enable,const std::uint8_t _BMS_AFE17_OVWakeUp_Enable,const std::uint8_t _BMS_AFE18_OVWakeUp_Enable,const std::uint8_t _BMS_AFE19_OVWakeUp_Enable,const std::uint8_t _BMS_AFE20_OVWakeUp_Enable,const std::uint8_t _BMS_AFE1_UVWakeUp_Enable,const std::uint8_t _BMS_AFE2_UVWakeUp_Enable,const std::uint8_t _BMS_AFE3_UVWakeUp_Enable,const std::uint8_t _BMS_AFE4_UVWakeUp_Enable,const std::uint8_t _BMS_AFE5_UVWakeUp_Enable,const std::uint8_t _BMS_AFE6_UVWakeUp_Enable,const std::uint8_t _BMS_AFE7_UVWakeUp_Enable,const std::uint8_t _BMS_AFE8_UVWakeUp_Enable,const std::uint8_t _BMS_AFE9_UVWakeUp_Enable,const std::uint8_t _BMS_AFE10_UVWakeUp_Enable,const std::uint8_t _BMS_AFE11_UVWakeUp_Enable,const std::uint8_t _BMS_AFE12_UVWakeUp_Enable,const std::uint8_t _BMS_AFE13_UVWakeUp_Enable,const std::uint8_t _BMS_AFE14_UVWakeUp_Enable,const std::uint8_t _BMS_AFE15_UVWakeUp_Enable,const std::uint8_t _BMS_AFE16_UVWakeUp_Enable,const std::uint8_t _BMS_AFE17_UVWakeUp_Enable,const std::uint8_t _BMS_AFE18_UVWakeUp_Enable,const std::uint8_t _BMS_AFE19_UVWakeUp_Enable,const std::uint8_t _BMS_AFE20_UVWakeUp_Enable):BMS_AFEWakeUpState(_BMS_AFEWakeUpState),BMS_ResetByAFESetErr(_BMS_ResetByAFESetErr),BMS_NrResetByAFESetErr(_BMS_NrResetByAFESetErr),BMS_AFE1_OVThreshold(_BMS_AFE1_OVThreshold),BMS_AFE2_OVThreshold(_BMS_AFE2_OVThreshold),BMS_AFE3_OVThreshold(_BMS_AFE3_OVThreshold),BMS_AFE4_OVThreshold(_BMS_AFE4_OVThreshold),BMS_AFE5_OVThreshold(_BMS_AFE5_OVThreshold),BMS_AFE6_OVThreshold(_BMS_AFE6_OVThreshold),BMS_AFE7_OVThreshold(_BMS_AFE7_OVThreshold),BMS_AFE8_OVThreshold(_BMS_AFE8_OVThreshold),BMS_AFE9_OVThreshold(_BMS_AFE9_OVThreshold),BMS_AFE10_OVThreshold(_BMS_AFE10_OVThreshold),BMS_AFE11_OVThreshold(_BMS_AFE11_OVThreshold),BMS_AFE12_OVThreshold(_BMS_AFE12_OVThreshold),BMS_AFE13_OVThreshold(_BMS_AFE13_OVThreshold),BMS_AFE14_OVThreshold(_BMS_AFE14_OVThreshold),BMS_AFE15_OVThreshold(_BMS_AFE15_OVThreshold),BMS_AFE16_OVThreshold(_BMS_AFE16_OVThreshold),BMS_AFE17_OVThreshold(_BMS_AFE17_OVThreshold),BMS_AFE18_OVThreshold(_BMS_AFE18_OVThreshold),BMS_AFE19_OVThreshold(_BMS_AFE19_OVThreshold),BMS_AFE20_OVThreshold(_BMS_AFE20_OVThreshold),BMS_AFE1_WakeUpSrc(_BMS_AFE1_WakeUpSrc),BMS_AFE2_WakeUpSrc(_BMS_AFE2_WakeUpSrc),BMS_AFE3_WakeUpSrc(_BMS_AFE3_WakeUpSrc),BMS_AFE4_WakeUpSrc(_BMS_AFE4_WakeUpSrc),BMS_AFE5_WakeUpSrc(_BMS_AFE5_WakeUpSrc),BMS_AFE6_WakeUpSrc(_BMS_AFE6_WakeUpSrc),BMS_AFE7_WakeUpSrc(_BMS_AFE7_WakeUpSrc),BMS_AFE8_WakeUpSrc(_BMS_AFE8_WakeUpSrc),BMS_AFE9_WakeUpSrc(_BMS_AFE9_WakeUpSrc),BMS_AFE10_WakeUpSrc(_BMS_AFE10_WakeUpSrc),BMS_AFE11_WakeUpSrc(_BMS_AFE11_WakeUpSrc),BMS_AFE12_WakeUpSrc(_BMS_AFE12_WakeUpSrc),BMS_AFE13_WakeUpSrc(_BMS_AFE13_WakeUpSrc),BMS_AFE14_WakeUpSrc(_BMS_AFE14_WakeUpSrc),BMS_AFE15_WakeUpSrc(_BMS_AFE15_WakeUpSrc),BMS_AFE16_WakeUpSrc(_BMS_AFE16_WakeUpSrc),BMS_AFE17_WakeUpSrc(_BMS_AFE17_WakeUpSrc),BMS_AFE18_WakeUpSrc(_BMS_AFE18_WakeUpSrc),BMS_AFE19_WakeUpSrc(_BMS_AFE19_WakeUpSrc),BMS_AFE20_WakeUpSrc(_BMS_AFE20_WakeUpSrc),BMS_AFE1_UVThreshold(_BMS_AFE1_UVThreshold),BMS_AFE2_UVThreshold(_BMS_AFE2_UVThreshold),BMS_AFE3_UVThreshold(_BMS_AFE3_UVThreshold),BMS_AFE4_UVThreshold(_BMS_AFE4_UVThreshold),BMS_AFE5_UVThreshold(_BMS_AFE5_UVThreshold),BMS_AFE6_UVThreshold(_BMS_AFE6_UVThreshold),BMS_AFE7_UVThreshold(_BMS_AFE7_UVThreshold),BMS_AFE8_UVThreshold(_BMS_AFE8_UVThreshold),BMS_AFE9_UVThreshold(_BMS_AFE9_UVThreshold),BMS_AFE10_UVThreshold(_BMS_AFE10_UVThreshold),BMS_AFE11_UVThreshold(_BMS_AFE11_UVThreshold),BMS_AFE12_UVThreshold(_BMS_AFE12_UVThreshold),BMS_AFE13_UVThreshold(_BMS_AFE13_UVThreshold),BMS_AFE14_UVThreshold(_BMS_AFE14_UVThreshold),BMS_AFE15_UVThreshold(_BMS_AFE15_UVThreshold),BMS_AFE16_UVThreshold(_BMS_AFE16_UVThreshold),BMS_AFE17_UVThreshold(_BMS_AFE17_UVThreshold),BMS_AFE18_UVThreshold(_BMS_AFE18_UVThreshold),BMS_AFE19_UVThreshold(_BMS_AFE19_UVThreshold),BMS_AFE20_UVThreshold(_BMS_AFE20_UVThreshold),BMS_AFE1_OTThreshold(_BMS_AFE1_OTThreshold),BMS_AFE2_OTThreshold(_BMS_AFE2_OTThreshold),BMS_AFE3_OTThreshold(_BMS_AFE3_OTThreshold),BMS_AFE4_OTThreshold(_BMS_AFE4_OTThreshold),BMS_AFE5_OTThreshold(_BMS_AFE5_OTThreshold),BMS_AFE6_OTThreshold(_BMS_AFE6_OTThreshold),BMS_AFE7_OTThreshold(_BMS_AFE7_OTThreshold),BMS_AFE8_OTThreshold(_BMS_AFE8_OTThreshold),BMS_AFE9_OTThreshold(_BMS_AFE9_OTThreshold),BMS_AFE10_OTThreshold(_BMS_AFE10_OTThreshold),BMS_AFE11_OTThreshold(_BMS_AFE11_OTThreshold),BMS_AFE12_OTThreshold(_BMS_AFE12_OTThreshold),BMS_AFE13_OTThreshold(_BMS_AFE13_OTThreshold),BMS_AFE14_OTThreshold(_BMS_AFE14_OTThreshold),BMS_AFE15_OTThreshold(_BMS_AFE15_OTThreshold),BMS_AFE16_OTThreshold(_BMS_AFE16_OTThreshold),BMS_AFE17_OTThreshold(_BMS_AFE17_OTThreshold),BMS_AFE18_OTThreshold(_BMS_AFE18_OTThreshold),BMS_AFE19_OTThreshold(_BMS_AFE19_OTThreshold),BMS_AFE20_OTThreshold(_BMS_AFE20_OTThreshold),BMS_AFE1_OTWakeUp_Enable(_BMS_AFE1_OTWakeUp_Enable),BMS_AFE2_OTWakeUp_Enable(_BMS_AFE2_OTWakeUp_Enable),BMS_AFE3_OTWakeUp_Enable(_BMS_AFE3_OTWakeUp_Enable),BMS_AFE4_OTWakeUp_Enable(_BMS_AFE4_OTWakeUp_Enable),BMS_AFE5_OTWakeUp_Enable(_BMS_AFE5_OTWakeUp_Enable),BMS_AFE6_OTWakeUp_Enable(_BMS_AFE6_OTWakeUp_Enable),BMS_AFE7_OTWakeUp_Enable(_BMS_AFE7_OTWakeUp_Enable),BMS_AFE8_OTWakeUp_Enable(_BMS_AFE8_OTWakeUp_Enable),BMS_AFE9_OTWakeUp_Enable(_BMS_AFE9_OTWakeUp_Enable),BMS_AFE10_OTWakeUp_Enable(_BMS_AFE10_OTWakeUp_Enable),BMS_AFE11_OTWakeUp_Enable(_BMS_AFE11_OTWakeUp_Enable),BMS_AFE12_OTWakeUp_Enable(_BMS_AFE12_OTWakeUp_Enable),BMS_AFE13_OTWakeUp_Enable(_BMS_AFE13_OTWakeUp_Enable),BMS_AFE14_OTWakeUp_Enable(_BMS_AFE14_OTWakeUp_Enable),BMS_AFE15_OTWakeUp_Enable(_BMS_AFE15_OTWakeUp_Enable),BMS_AFE16_OTWakeUp_Enable(_BMS_AFE16_OTWakeUp_Enable),BMS_AFE17_OTWakeUp_Enable(_BMS_AFE17_OTWakeUp_Enable),BMS_AFE18_OTWakeUp_Enable(_BMS_AFE18_OTWakeUp_Enable),BMS_AFE19_OTWakeUp_Enable(_BMS_AFE19_OTWakeUp_Enable),BMS_AFE20_OTWakeUp_Enable(_BMS_AFE20_OTWakeUp_Enable),BMS_AFE1_OVWakeUp_Enable(_BMS_AFE1_OVWakeUp_Enable),BMS_AFE2_OVWakeUp_Enable(_BMS_AFE2_OVWakeUp_Enable),BMS_AFE3_OVWakeUp_Enable(_BMS_AFE3_OVWakeUp_Enable),BMS_AFE4_OVWakeUp_Enable(_BMS_AFE4_OVWakeUp_Enable),BMS_AFE5_OVWakeUp_Enable(_BMS_AFE5_OVWakeUp_Enable),BMS_AFE6_OVWakeUp_Enable(_BMS_AFE6_OVWakeUp_Enable),BMS_AFE7_OVWakeUp_Enable(_BMS_AFE7_OVWakeUp_Enable),BMS_AFE8_OVWakeUp_Enable(_BMS_AFE8_OVWakeUp_Enable),BMS_AFE9_OVWakeUp_Enable(_BMS_AFE9_OVWakeUp_Enable),BMS_AFE10_OVWakeUp_Enable(_BMS_AFE10_OVWakeUp_Enable),BMS_AFE11_OVWakeUp_Enable(_BMS_AFE11_OVWakeUp_Enable),BMS_AFE12_OVWakeUp_Enable(_BMS_AFE12_OVWakeUp_Enable),BMS_AFE13_OVWakeUp_Enable(_BMS_AFE13_OVWakeUp_Enable),BMS_AFE14_OVWakeUp_Enable(_BMS_AFE14_OVWakeUp_Enable),BMS_AFE15_OVWakeUp_Enable(_BMS_AFE15_OVWakeUp_Enable),BMS_AFE16_OVWakeUp_Enable(_BMS_AFE16_OVWakeUp_Enable),BMS_AFE17_OVWakeUp_Enable(_BMS_AFE17_OVWakeUp_Enable),BMS_AFE18_OVWakeUp_Enable(_BMS_AFE18_OVWakeUp_Enable),BMS_AFE19_OVWakeUp_Enable(_BMS_AFE19_OVWakeUp_Enable),BMS_AFE20_OVWakeUp_Enable(_BMS_AFE20_OVWakeUp_Enable),BMS_AFE1_UVWakeUp_Enable(_BMS_AFE1_UVWakeUp_Enable),BMS_AFE2_UVWakeUp_Enable(_BMS_AFE2_UVWakeUp_Enable),BMS_AFE3_UVWakeUp_Enable(_BMS_AFE3_UVWakeUp_Enable),BMS_AFE4_UVWakeUp_Enable(_BMS_AFE4_UVWakeUp_Enable),BMS_AFE5_UVWakeUp_Enable(_BMS_AFE5_UVWakeUp_Enable),BMS_AFE6_UVWakeUp_Enable(_BMS_AFE6_UVWakeUp_Enable),BMS_AFE7_UVWakeUp_Enable(_BMS_AFE7_UVWakeUp_Enable),BMS_AFE8_UVWakeUp_Enable(_BMS_AFE8_UVWakeUp_Enable),BMS_AFE9_UVWakeUp_Enable(_BMS_AFE9_UVWakeUp_Enable),BMS_AFE10_UVWakeUp_Enable(_BMS_AFE10_UVWakeUp_Enable),BMS_AFE11_UVWakeUp_Enable(_BMS_AFE11_UVWakeUp_Enable),BMS_AFE12_UVWakeUp_Enable(_BMS_AFE12_UVWakeUp_Enable),BMS_AFE13_UVWakeUp_Enable(_BMS_AFE13_UVWakeUp_Enable),BMS_AFE14_UVWakeUp_Enable(_BMS_AFE14_UVWakeUp_Enable),BMS_AFE15_UVWakeUp_Enable(_BMS_AFE15_UVWakeUp_Enable),BMS_AFE16_UVWakeUp_Enable(_BMS_AFE16_UVWakeUp_Enable),BMS_AFE17_UVWakeUp_Enable(_BMS_AFE17_UVWakeUp_Enable),BMS_AFE18_UVWakeUp_Enable(_BMS_AFE18_UVWakeUp_Enable),BMS_AFE19_UVWakeUp_Enable(_BMS_AFE19_UVWakeUp_Enable),BMS_AFE20_UVWakeUp_Enable(_BMS_AFE20_UVWakeUp_Enable) {}
	BDCBMSAFE(const BDCBMSAFE &_x){
		BMS_AFEWakeUpState = _x.BMS_AFEWakeUpState;
		BMS_ResetByAFESetErr = _x.BMS_ResetByAFESetErr;
		BMS_NrResetByAFESetErr = _x.BMS_NrResetByAFESetErr;
		BMS_AFE1_OVThreshold = _x.BMS_AFE1_OVThreshold;
		BMS_AFE2_OVThreshold = _x.BMS_AFE2_OVThreshold;
		BMS_AFE3_OVThreshold = _x.BMS_AFE3_OVThreshold;
		BMS_AFE4_OVThreshold = _x.BMS_AFE4_OVThreshold;
		BMS_AFE5_OVThreshold = _x.BMS_AFE5_OVThreshold;
		BMS_AFE6_OVThreshold = _x.BMS_AFE6_OVThreshold;
		BMS_AFE7_OVThreshold = _x.BMS_AFE7_OVThreshold;
		BMS_AFE8_OVThreshold = _x.BMS_AFE8_OVThreshold;
		BMS_AFE9_OVThreshold = _x.BMS_AFE9_OVThreshold;
		BMS_AFE10_OVThreshold = _x.BMS_AFE10_OVThreshold;
		BMS_AFE11_OVThreshold = _x.BMS_AFE11_OVThreshold;
		BMS_AFE12_OVThreshold = _x.BMS_AFE12_OVThreshold;
		BMS_AFE13_OVThreshold = _x.BMS_AFE13_OVThreshold;
		BMS_AFE14_OVThreshold = _x.BMS_AFE14_OVThreshold;
		BMS_AFE15_OVThreshold = _x.BMS_AFE15_OVThreshold;
		BMS_AFE16_OVThreshold = _x.BMS_AFE16_OVThreshold;
		BMS_AFE17_OVThreshold = _x.BMS_AFE17_OVThreshold;
		BMS_AFE18_OVThreshold = _x.BMS_AFE18_OVThreshold;
		BMS_AFE19_OVThreshold = _x.BMS_AFE19_OVThreshold;
		BMS_AFE20_OVThreshold = _x.BMS_AFE20_OVThreshold;
		BMS_AFE1_WakeUpSrc = _x.BMS_AFE1_WakeUpSrc;
		BMS_AFE2_WakeUpSrc = _x.BMS_AFE2_WakeUpSrc;
		BMS_AFE3_WakeUpSrc = _x.BMS_AFE3_WakeUpSrc;
		BMS_AFE4_WakeUpSrc = _x.BMS_AFE4_WakeUpSrc;
		BMS_AFE5_WakeUpSrc = _x.BMS_AFE5_WakeUpSrc;
		BMS_AFE6_WakeUpSrc = _x.BMS_AFE6_WakeUpSrc;
		BMS_AFE7_WakeUpSrc = _x.BMS_AFE7_WakeUpSrc;
		BMS_AFE8_WakeUpSrc = _x.BMS_AFE8_WakeUpSrc;
		BMS_AFE9_WakeUpSrc = _x.BMS_AFE9_WakeUpSrc;
		BMS_AFE10_WakeUpSrc = _x.BMS_AFE10_WakeUpSrc;
		BMS_AFE11_WakeUpSrc = _x.BMS_AFE11_WakeUpSrc;
		BMS_AFE12_WakeUpSrc = _x.BMS_AFE12_WakeUpSrc;
		BMS_AFE13_WakeUpSrc = _x.BMS_AFE13_WakeUpSrc;
		BMS_AFE14_WakeUpSrc = _x.BMS_AFE14_WakeUpSrc;
		BMS_AFE15_WakeUpSrc = _x.BMS_AFE15_WakeUpSrc;
		BMS_AFE16_WakeUpSrc = _x.BMS_AFE16_WakeUpSrc;
		BMS_AFE17_WakeUpSrc = _x.BMS_AFE17_WakeUpSrc;
		BMS_AFE18_WakeUpSrc = _x.BMS_AFE18_WakeUpSrc;
		BMS_AFE19_WakeUpSrc = _x.BMS_AFE19_WakeUpSrc;
		BMS_AFE20_WakeUpSrc = _x.BMS_AFE20_WakeUpSrc;
		BMS_AFE1_UVThreshold = _x.BMS_AFE1_UVThreshold;
		BMS_AFE2_UVThreshold = _x.BMS_AFE2_UVThreshold;
		BMS_AFE3_UVThreshold = _x.BMS_AFE3_UVThreshold;
		BMS_AFE4_UVThreshold = _x.BMS_AFE4_UVThreshold;
		BMS_AFE5_UVThreshold = _x.BMS_AFE5_UVThreshold;
		BMS_AFE6_UVThreshold = _x.BMS_AFE6_UVThreshold;
		BMS_AFE7_UVThreshold = _x.BMS_AFE7_UVThreshold;
		BMS_AFE8_UVThreshold = _x.BMS_AFE8_UVThreshold;
		BMS_AFE9_UVThreshold = _x.BMS_AFE9_UVThreshold;
		BMS_AFE10_UVThreshold = _x.BMS_AFE10_UVThreshold;
		BMS_AFE11_UVThreshold = _x.BMS_AFE11_UVThreshold;
		BMS_AFE12_UVThreshold = _x.BMS_AFE12_UVThreshold;
		BMS_AFE13_UVThreshold = _x.BMS_AFE13_UVThreshold;
		BMS_AFE14_UVThreshold = _x.BMS_AFE14_UVThreshold;
		BMS_AFE15_UVThreshold = _x.BMS_AFE15_UVThreshold;
		BMS_AFE16_UVThreshold = _x.BMS_AFE16_UVThreshold;
		BMS_AFE17_UVThreshold = _x.BMS_AFE17_UVThreshold;
		BMS_AFE18_UVThreshold = _x.BMS_AFE18_UVThreshold;
		BMS_AFE19_UVThreshold = _x.BMS_AFE19_UVThreshold;
		BMS_AFE20_UVThreshold = _x.BMS_AFE20_UVThreshold;
		BMS_AFE1_OTThreshold = _x.BMS_AFE1_OTThreshold;
		BMS_AFE2_OTThreshold = _x.BMS_AFE2_OTThreshold;
		BMS_AFE3_OTThreshold = _x.BMS_AFE3_OTThreshold;
		BMS_AFE4_OTThreshold = _x.BMS_AFE4_OTThreshold;
		BMS_AFE5_OTThreshold = _x.BMS_AFE5_OTThreshold;
		BMS_AFE6_OTThreshold = _x.BMS_AFE6_OTThreshold;
		BMS_AFE7_OTThreshold = _x.BMS_AFE7_OTThreshold;
		BMS_AFE8_OTThreshold = _x.BMS_AFE8_OTThreshold;
		BMS_AFE9_OTThreshold = _x.BMS_AFE9_OTThreshold;
		BMS_AFE10_OTThreshold = _x.BMS_AFE10_OTThreshold;
		BMS_AFE11_OTThreshold = _x.BMS_AFE11_OTThreshold;
		BMS_AFE12_OTThreshold = _x.BMS_AFE12_OTThreshold;
		BMS_AFE13_OTThreshold = _x.BMS_AFE13_OTThreshold;
		BMS_AFE14_OTThreshold = _x.BMS_AFE14_OTThreshold;
		BMS_AFE15_OTThreshold = _x.BMS_AFE15_OTThreshold;
		BMS_AFE16_OTThreshold = _x.BMS_AFE16_OTThreshold;
		BMS_AFE17_OTThreshold = _x.BMS_AFE17_OTThreshold;
		BMS_AFE18_OTThreshold = _x.BMS_AFE18_OTThreshold;
		BMS_AFE19_OTThreshold = _x.BMS_AFE19_OTThreshold;
		BMS_AFE20_OTThreshold = _x.BMS_AFE20_OTThreshold;
		BMS_AFE1_OTWakeUp_Enable = _x.BMS_AFE1_OTWakeUp_Enable;
		BMS_AFE2_OTWakeUp_Enable = _x.BMS_AFE2_OTWakeUp_Enable;
		BMS_AFE3_OTWakeUp_Enable = _x.BMS_AFE3_OTWakeUp_Enable;
		BMS_AFE4_OTWakeUp_Enable = _x.BMS_AFE4_OTWakeUp_Enable;
		BMS_AFE5_OTWakeUp_Enable = _x.BMS_AFE5_OTWakeUp_Enable;
		BMS_AFE6_OTWakeUp_Enable = _x.BMS_AFE6_OTWakeUp_Enable;
		BMS_AFE7_OTWakeUp_Enable = _x.BMS_AFE7_OTWakeUp_Enable;
		BMS_AFE8_OTWakeUp_Enable = _x.BMS_AFE8_OTWakeUp_Enable;
		BMS_AFE9_OTWakeUp_Enable = _x.BMS_AFE9_OTWakeUp_Enable;
		BMS_AFE10_OTWakeUp_Enable = _x.BMS_AFE10_OTWakeUp_Enable;
		BMS_AFE11_OTWakeUp_Enable = _x.BMS_AFE11_OTWakeUp_Enable;
		BMS_AFE12_OTWakeUp_Enable = _x.BMS_AFE12_OTWakeUp_Enable;
		BMS_AFE13_OTWakeUp_Enable = _x.BMS_AFE13_OTWakeUp_Enable;
		BMS_AFE14_OTWakeUp_Enable = _x.BMS_AFE14_OTWakeUp_Enable;
		BMS_AFE15_OTWakeUp_Enable = _x.BMS_AFE15_OTWakeUp_Enable;
		BMS_AFE16_OTWakeUp_Enable = _x.BMS_AFE16_OTWakeUp_Enable;
		BMS_AFE17_OTWakeUp_Enable = _x.BMS_AFE17_OTWakeUp_Enable;
		BMS_AFE18_OTWakeUp_Enable = _x.BMS_AFE18_OTWakeUp_Enable;
		BMS_AFE19_OTWakeUp_Enable = _x.BMS_AFE19_OTWakeUp_Enable;
		BMS_AFE20_OTWakeUp_Enable = _x.BMS_AFE20_OTWakeUp_Enable;
		BMS_AFE1_OVWakeUp_Enable = _x.BMS_AFE1_OVWakeUp_Enable;
		BMS_AFE2_OVWakeUp_Enable = _x.BMS_AFE2_OVWakeUp_Enable;
		BMS_AFE3_OVWakeUp_Enable = _x.BMS_AFE3_OVWakeUp_Enable;
		BMS_AFE4_OVWakeUp_Enable = _x.BMS_AFE4_OVWakeUp_Enable;
		BMS_AFE5_OVWakeUp_Enable = _x.BMS_AFE5_OVWakeUp_Enable;
		BMS_AFE6_OVWakeUp_Enable = _x.BMS_AFE6_OVWakeUp_Enable;
		BMS_AFE7_OVWakeUp_Enable = _x.BMS_AFE7_OVWakeUp_Enable;
		BMS_AFE8_OVWakeUp_Enable = _x.BMS_AFE8_OVWakeUp_Enable;
		BMS_AFE9_OVWakeUp_Enable = _x.BMS_AFE9_OVWakeUp_Enable;
		BMS_AFE10_OVWakeUp_Enable = _x.BMS_AFE10_OVWakeUp_Enable;
		BMS_AFE11_OVWakeUp_Enable = _x.BMS_AFE11_OVWakeUp_Enable;
		BMS_AFE12_OVWakeUp_Enable = _x.BMS_AFE12_OVWakeUp_Enable;
		BMS_AFE13_OVWakeUp_Enable = _x.BMS_AFE13_OVWakeUp_Enable;
		BMS_AFE14_OVWakeUp_Enable = _x.BMS_AFE14_OVWakeUp_Enable;
		BMS_AFE15_OVWakeUp_Enable = _x.BMS_AFE15_OVWakeUp_Enable;
		BMS_AFE16_OVWakeUp_Enable = _x.BMS_AFE16_OVWakeUp_Enable;
		BMS_AFE17_OVWakeUp_Enable = _x.BMS_AFE17_OVWakeUp_Enable;
		BMS_AFE18_OVWakeUp_Enable = _x.BMS_AFE18_OVWakeUp_Enable;
		BMS_AFE19_OVWakeUp_Enable = _x.BMS_AFE19_OVWakeUp_Enable;
		BMS_AFE20_OVWakeUp_Enable = _x.BMS_AFE20_OVWakeUp_Enable;
		BMS_AFE1_UVWakeUp_Enable = _x.BMS_AFE1_UVWakeUp_Enable;
		BMS_AFE2_UVWakeUp_Enable = _x.BMS_AFE2_UVWakeUp_Enable;
		BMS_AFE3_UVWakeUp_Enable = _x.BMS_AFE3_UVWakeUp_Enable;
		BMS_AFE4_UVWakeUp_Enable = _x.BMS_AFE4_UVWakeUp_Enable;
		BMS_AFE5_UVWakeUp_Enable = _x.BMS_AFE5_UVWakeUp_Enable;
		BMS_AFE6_UVWakeUp_Enable = _x.BMS_AFE6_UVWakeUp_Enable;
		BMS_AFE7_UVWakeUp_Enable = _x.BMS_AFE7_UVWakeUp_Enable;
		BMS_AFE8_UVWakeUp_Enable = _x.BMS_AFE8_UVWakeUp_Enable;
		BMS_AFE9_UVWakeUp_Enable = _x.BMS_AFE9_UVWakeUp_Enable;
		BMS_AFE10_UVWakeUp_Enable = _x.BMS_AFE10_UVWakeUp_Enable;
		BMS_AFE11_UVWakeUp_Enable = _x.BMS_AFE11_UVWakeUp_Enable;
		BMS_AFE12_UVWakeUp_Enable = _x.BMS_AFE12_UVWakeUp_Enable;
		BMS_AFE13_UVWakeUp_Enable = _x.BMS_AFE13_UVWakeUp_Enable;
		BMS_AFE14_UVWakeUp_Enable = _x.BMS_AFE14_UVWakeUp_Enable;
		BMS_AFE15_UVWakeUp_Enable = _x.BMS_AFE15_UVWakeUp_Enable;
		BMS_AFE16_UVWakeUp_Enable = _x.BMS_AFE16_UVWakeUp_Enable;
		BMS_AFE17_UVWakeUp_Enable = _x.BMS_AFE17_UVWakeUp_Enable;
		BMS_AFE18_UVWakeUp_Enable = _x.BMS_AFE18_UVWakeUp_Enable;
		BMS_AFE19_UVWakeUp_Enable = _x.BMS_AFE19_UVWakeUp_Enable;
		BMS_AFE20_UVWakeUp_Enable = _x.BMS_AFE20_UVWakeUp_Enable;
	}
	BDCBMSAFE(BDCBMSAFE &&_x){
		BMS_AFEWakeUpState = std::move(_x.BMS_AFEWakeUpState);
		BMS_ResetByAFESetErr = std::move(_x.BMS_ResetByAFESetErr);
		BMS_NrResetByAFESetErr = std::move(_x.BMS_NrResetByAFESetErr);
		BMS_AFE1_OVThreshold = std::move(_x.BMS_AFE1_OVThreshold);
		BMS_AFE2_OVThreshold = std::move(_x.BMS_AFE2_OVThreshold);
		BMS_AFE3_OVThreshold = std::move(_x.BMS_AFE3_OVThreshold);
		BMS_AFE4_OVThreshold = std::move(_x.BMS_AFE4_OVThreshold);
		BMS_AFE5_OVThreshold = std::move(_x.BMS_AFE5_OVThreshold);
		BMS_AFE6_OVThreshold = std::move(_x.BMS_AFE6_OVThreshold);
		BMS_AFE7_OVThreshold = std::move(_x.BMS_AFE7_OVThreshold);
		BMS_AFE8_OVThreshold = std::move(_x.BMS_AFE8_OVThreshold);
		BMS_AFE9_OVThreshold = std::move(_x.BMS_AFE9_OVThreshold);
		BMS_AFE10_OVThreshold = std::move(_x.BMS_AFE10_OVThreshold);
		BMS_AFE11_OVThreshold = std::move(_x.BMS_AFE11_OVThreshold);
		BMS_AFE12_OVThreshold = std::move(_x.BMS_AFE12_OVThreshold);
		BMS_AFE13_OVThreshold = std::move(_x.BMS_AFE13_OVThreshold);
		BMS_AFE14_OVThreshold = std::move(_x.BMS_AFE14_OVThreshold);
		BMS_AFE15_OVThreshold = std::move(_x.BMS_AFE15_OVThreshold);
		BMS_AFE16_OVThreshold = std::move(_x.BMS_AFE16_OVThreshold);
		BMS_AFE17_OVThreshold = std::move(_x.BMS_AFE17_OVThreshold);
		BMS_AFE18_OVThreshold = std::move(_x.BMS_AFE18_OVThreshold);
		BMS_AFE19_OVThreshold = std::move(_x.BMS_AFE19_OVThreshold);
		BMS_AFE20_OVThreshold = std::move(_x.BMS_AFE20_OVThreshold);
		BMS_AFE1_WakeUpSrc = std::move(_x.BMS_AFE1_WakeUpSrc);
		BMS_AFE2_WakeUpSrc = std::move(_x.BMS_AFE2_WakeUpSrc);
		BMS_AFE3_WakeUpSrc = std::move(_x.BMS_AFE3_WakeUpSrc);
		BMS_AFE4_WakeUpSrc = std::move(_x.BMS_AFE4_WakeUpSrc);
		BMS_AFE5_WakeUpSrc = std::move(_x.BMS_AFE5_WakeUpSrc);
		BMS_AFE6_WakeUpSrc = std::move(_x.BMS_AFE6_WakeUpSrc);
		BMS_AFE7_WakeUpSrc = std::move(_x.BMS_AFE7_WakeUpSrc);
		BMS_AFE8_WakeUpSrc = std::move(_x.BMS_AFE8_WakeUpSrc);
		BMS_AFE9_WakeUpSrc = std::move(_x.BMS_AFE9_WakeUpSrc);
		BMS_AFE10_WakeUpSrc = std::move(_x.BMS_AFE10_WakeUpSrc);
		BMS_AFE11_WakeUpSrc = std::move(_x.BMS_AFE11_WakeUpSrc);
		BMS_AFE12_WakeUpSrc = std::move(_x.BMS_AFE12_WakeUpSrc);
		BMS_AFE13_WakeUpSrc = std::move(_x.BMS_AFE13_WakeUpSrc);
		BMS_AFE14_WakeUpSrc = std::move(_x.BMS_AFE14_WakeUpSrc);
		BMS_AFE15_WakeUpSrc = std::move(_x.BMS_AFE15_WakeUpSrc);
		BMS_AFE16_WakeUpSrc = std::move(_x.BMS_AFE16_WakeUpSrc);
		BMS_AFE17_WakeUpSrc = std::move(_x.BMS_AFE17_WakeUpSrc);
		BMS_AFE18_WakeUpSrc = std::move(_x.BMS_AFE18_WakeUpSrc);
		BMS_AFE19_WakeUpSrc = std::move(_x.BMS_AFE19_WakeUpSrc);
		BMS_AFE20_WakeUpSrc = std::move(_x.BMS_AFE20_WakeUpSrc);
		BMS_AFE1_UVThreshold = std::move(_x.BMS_AFE1_UVThreshold);
		BMS_AFE2_UVThreshold = std::move(_x.BMS_AFE2_UVThreshold);
		BMS_AFE3_UVThreshold = std::move(_x.BMS_AFE3_UVThreshold);
		BMS_AFE4_UVThreshold = std::move(_x.BMS_AFE4_UVThreshold);
		BMS_AFE5_UVThreshold = std::move(_x.BMS_AFE5_UVThreshold);
		BMS_AFE6_UVThreshold = std::move(_x.BMS_AFE6_UVThreshold);
		BMS_AFE7_UVThreshold = std::move(_x.BMS_AFE7_UVThreshold);
		BMS_AFE8_UVThreshold = std::move(_x.BMS_AFE8_UVThreshold);
		BMS_AFE9_UVThreshold = std::move(_x.BMS_AFE9_UVThreshold);
		BMS_AFE10_UVThreshold = std::move(_x.BMS_AFE10_UVThreshold);
		BMS_AFE11_UVThreshold = std::move(_x.BMS_AFE11_UVThreshold);
		BMS_AFE12_UVThreshold = std::move(_x.BMS_AFE12_UVThreshold);
		BMS_AFE13_UVThreshold = std::move(_x.BMS_AFE13_UVThreshold);
		BMS_AFE14_UVThreshold = std::move(_x.BMS_AFE14_UVThreshold);
		BMS_AFE15_UVThreshold = std::move(_x.BMS_AFE15_UVThreshold);
		BMS_AFE16_UVThreshold = std::move(_x.BMS_AFE16_UVThreshold);
		BMS_AFE17_UVThreshold = std::move(_x.BMS_AFE17_UVThreshold);
		BMS_AFE18_UVThreshold = std::move(_x.BMS_AFE18_UVThreshold);
		BMS_AFE19_UVThreshold = std::move(_x.BMS_AFE19_UVThreshold);
		BMS_AFE20_UVThreshold = std::move(_x.BMS_AFE20_UVThreshold);
		BMS_AFE1_OTThreshold = std::move(_x.BMS_AFE1_OTThreshold);
		BMS_AFE2_OTThreshold = std::move(_x.BMS_AFE2_OTThreshold);
		BMS_AFE3_OTThreshold = std::move(_x.BMS_AFE3_OTThreshold);
		BMS_AFE4_OTThreshold = std::move(_x.BMS_AFE4_OTThreshold);
		BMS_AFE5_OTThreshold = std::move(_x.BMS_AFE5_OTThreshold);
		BMS_AFE6_OTThreshold = std::move(_x.BMS_AFE6_OTThreshold);
		BMS_AFE7_OTThreshold = std::move(_x.BMS_AFE7_OTThreshold);
		BMS_AFE8_OTThreshold = std::move(_x.BMS_AFE8_OTThreshold);
		BMS_AFE9_OTThreshold = std::move(_x.BMS_AFE9_OTThreshold);
		BMS_AFE10_OTThreshold = std::move(_x.BMS_AFE10_OTThreshold);
		BMS_AFE11_OTThreshold = std::move(_x.BMS_AFE11_OTThreshold);
		BMS_AFE12_OTThreshold = std::move(_x.BMS_AFE12_OTThreshold);
		BMS_AFE13_OTThreshold = std::move(_x.BMS_AFE13_OTThreshold);
		BMS_AFE14_OTThreshold = std::move(_x.BMS_AFE14_OTThreshold);
		BMS_AFE15_OTThreshold = std::move(_x.BMS_AFE15_OTThreshold);
		BMS_AFE16_OTThreshold = std::move(_x.BMS_AFE16_OTThreshold);
		BMS_AFE17_OTThreshold = std::move(_x.BMS_AFE17_OTThreshold);
		BMS_AFE18_OTThreshold = std::move(_x.BMS_AFE18_OTThreshold);
		BMS_AFE19_OTThreshold = std::move(_x.BMS_AFE19_OTThreshold);
		BMS_AFE20_OTThreshold = std::move(_x.BMS_AFE20_OTThreshold);
		BMS_AFE1_OTWakeUp_Enable = std::move(_x.BMS_AFE1_OTWakeUp_Enable);
		BMS_AFE2_OTWakeUp_Enable = std::move(_x.BMS_AFE2_OTWakeUp_Enable);
		BMS_AFE3_OTWakeUp_Enable = std::move(_x.BMS_AFE3_OTWakeUp_Enable);
		BMS_AFE4_OTWakeUp_Enable = std::move(_x.BMS_AFE4_OTWakeUp_Enable);
		BMS_AFE5_OTWakeUp_Enable = std::move(_x.BMS_AFE5_OTWakeUp_Enable);
		BMS_AFE6_OTWakeUp_Enable = std::move(_x.BMS_AFE6_OTWakeUp_Enable);
		BMS_AFE7_OTWakeUp_Enable = std::move(_x.BMS_AFE7_OTWakeUp_Enable);
		BMS_AFE8_OTWakeUp_Enable = std::move(_x.BMS_AFE8_OTWakeUp_Enable);
		BMS_AFE9_OTWakeUp_Enable = std::move(_x.BMS_AFE9_OTWakeUp_Enable);
		BMS_AFE10_OTWakeUp_Enable = std::move(_x.BMS_AFE10_OTWakeUp_Enable);
		BMS_AFE11_OTWakeUp_Enable = std::move(_x.BMS_AFE11_OTWakeUp_Enable);
		BMS_AFE12_OTWakeUp_Enable = std::move(_x.BMS_AFE12_OTWakeUp_Enable);
		BMS_AFE13_OTWakeUp_Enable = std::move(_x.BMS_AFE13_OTWakeUp_Enable);
		BMS_AFE14_OTWakeUp_Enable = std::move(_x.BMS_AFE14_OTWakeUp_Enable);
		BMS_AFE15_OTWakeUp_Enable = std::move(_x.BMS_AFE15_OTWakeUp_Enable);
		BMS_AFE16_OTWakeUp_Enable = std::move(_x.BMS_AFE16_OTWakeUp_Enable);
		BMS_AFE17_OTWakeUp_Enable = std::move(_x.BMS_AFE17_OTWakeUp_Enable);
		BMS_AFE18_OTWakeUp_Enable = std::move(_x.BMS_AFE18_OTWakeUp_Enable);
		BMS_AFE19_OTWakeUp_Enable = std::move(_x.BMS_AFE19_OTWakeUp_Enable);
		BMS_AFE20_OTWakeUp_Enable = std::move(_x.BMS_AFE20_OTWakeUp_Enable);
		BMS_AFE1_OVWakeUp_Enable = std::move(_x.BMS_AFE1_OVWakeUp_Enable);
		BMS_AFE2_OVWakeUp_Enable = std::move(_x.BMS_AFE2_OVWakeUp_Enable);
		BMS_AFE3_OVWakeUp_Enable = std::move(_x.BMS_AFE3_OVWakeUp_Enable);
		BMS_AFE4_OVWakeUp_Enable = std::move(_x.BMS_AFE4_OVWakeUp_Enable);
		BMS_AFE5_OVWakeUp_Enable = std::move(_x.BMS_AFE5_OVWakeUp_Enable);
		BMS_AFE6_OVWakeUp_Enable = std::move(_x.BMS_AFE6_OVWakeUp_Enable);
		BMS_AFE7_OVWakeUp_Enable = std::move(_x.BMS_AFE7_OVWakeUp_Enable);
		BMS_AFE8_OVWakeUp_Enable = std::move(_x.BMS_AFE8_OVWakeUp_Enable);
		BMS_AFE9_OVWakeUp_Enable = std::move(_x.BMS_AFE9_OVWakeUp_Enable);
		BMS_AFE10_OVWakeUp_Enable = std::move(_x.BMS_AFE10_OVWakeUp_Enable);
		BMS_AFE11_OVWakeUp_Enable = std::move(_x.BMS_AFE11_OVWakeUp_Enable);
		BMS_AFE12_OVWakeUp_Enable = std::move(_x.BMS_AFE12_OVWakeUp_Enable);
		BMS_AFE13_OVWakeUp_Enable = std::move(_x.BMS_AFE13_OVWakeUp_Enable);
		BMS_AFE14_OVWakeUp_Enable = std::move(_x.BMS_AFE14_OVWakeUp_Enable);
		BMS_AFE15_OVWakeUp_Enable = std::move(_x.BMS_AFE15_OVWakeUp_Enable);
		BMS_AFE16_OVWakeUp_Enable = std::move(_x.BMS_AFE16_OVWakeUp_Enable);
		BMS_AFE17_OVWakeUp_Enable = std::move(_x.BMS_AFE17_OVWakeUp_Enable);
		BMS_AFE18_OVWakeUp_Enable = std::move(_x.BMS_AFE18_OVWakeUp_Enable);
		BMS_AFE19_OVWakeUp_Enable = std::move(_x.BMS_AFE19_OVWakeUp_Enable);
		BMS_AFE20_OVWakeUp_Enable = std::move(_x.BMS_AFE20_OVWakeUp_Enable);
		BMS_AFE1_UVWakeUp_Enable = std::move(_x.BMS_AFE1_UVWakeUp_Enable);
		BMS_AFE2_UVWakeUp_Enable = std::move(_x.BMS_AFE2_UVWakeUp_Enable);
		BMS_AFE3_UVWakeUp_Enable = std::move(_x.BMS_AFE3_UVWakeUp_Enable);
		BMS_AFE4_UVWakeUp_Enable = std::move(_x.BMS_AFE4_UVWakeUp_Enable);
		BMS_AFE5_UVWakeUp_Enable = std::move(_x.BMS_AFE5_UVWakeUp_Enable);
		BMS_AFE6_UVWakeUp_Enable = std::move(_x.BMS_AFE6_UVWakeUp_Enable);
		BMS_AFE7_UVWakeUp_Enable = std::move(_x.BMS_AFE7_UVWakeUp_Enable);
		BMS_AFE8_UVWakeUp_Enable = std::move(_x.BMS_AFE8_UVWakeUp_Enable);
		BMS_AFE9_UVWakeUp_Enable = std::move(_x.BMS_AFE9_UVWakeUp_Enable);
		BMS_AFE10_UVWakeUp_Enable = std::move(_x.BMS_AFE10_UVWakeUp_Enable);
		BMS_AFE11_UVWakeUp_Enable = std::move(_x.BMS_AFE11_UVWakeUp_Enable);
		BMS_AFE12_UVWakeUp_Enable = std::move(_x.BMS_AFE12_UVWakeUp_Enable);
		BMS_AFE13_UVWakeUp_Enable = std::move(_x.BMS_AFE13_UVWakeUp_Enable);
		BMS_AFE14_UVWakeUp_Enable = std::move(_x.BMS_AFE14_UVWakeUp_Enable);
		BMS_AFE15_UVWakeUp_Enable = std::move(_x.BMS_AFE15_UVWakeUp_Enable);
		BMS_AFE16_UVWakeUp_Enable = std::move(_x.BMS_AFE16_UVWakeUp_Enable);
		BMS_AFE17_UVWakeUp_Enable = std::move(_x.BMS_AFE17_UVWakeUp_Enable);
		BMS_AFE18_UVWakeUp_Enable = std::move(_x.BMS_AFE18_UVWakeUp_Enable);
		BMS_AFE19_UVWakeUp_Enable = std::move(_x.BMS_AFE19_UVWakeUp_Enable);
		BMS_AFE20_UVWakeUp_Enable = std::move(_x.BMS_AFE20_UVWakeUp_Enable);
	}
	BDCBMSAFE& operator=(const BDCBMSAFE &_x){
		BMS_AFEWakeUpState = _x.BMS_AFEWakeUpState;
		BMS_ResetByAFESetErr = _x.BMS_ResetByAFESetErr;
		BMS_NrResetByAFESetErr = _x.BMS_NrResetByAFESetErr;
		BMS_AFE1_OVThreshold = _x.BMS_AFE1_OVThreshold;
		BMS_AFE2_OVThreshold = _x.BMS_AFE2_OVThreshold;
		BMS_AFE3_OVThreshold = _x.BMS_AFE3_OVThreshold;
		BMS_AFE4_OVThreshold = _x.BMS_AFE4_OVThreshold;
		BMS_AFE5_OVThreshold = _x.BMS_AFE5_OVThreshold;
		BMS_AFE6_OVThreshold = _x.BMS_AFE6_OVThreshold;
		BMS_AFE7_OVThreshold = _x.BMS_AFE7_OVThreshold;
		BMS_AFE8_OVThreshold = _x.BMS_AFE8_OVThreshold;
		BMS_AFE9_OVThreshold = _x.BMS_AFE9_OVThreshold;
		BMS_AFE10_OVThreshold = _x.BMS_AFE10_OVThreshold;
		BMS_AFE11_OVThreshold = _x.BMS_AFE11_OVThreshold;
		BMS_AFE12_OVThreshold = _x.BMS_AFE12_OVThreshold;
		BMS_AFE13_OVThreshold = _x.BMS_AFE13_OVThreshold;
		BMS_AFE14_OVThreshold = _x.BMS_AFE14_OVThreshold;
		BMS_AFE15_OVThreshold = _x.BMS_AFE15_OVThreshold;
		BMS_AFE16_OVThreshold = _x.BMS_AFE16_OVThreshold;
		BMS_AFE17_OVThreshold = _x.BMS_AFE17_OVThreshold;
		BMS_AFE18_OVThreshold = _x.BMS_AFE18_OVThreshold;
		BMS_AFE19_OVThreshold = _x.BMS_AFE19_OVThreshold;
		BMS_AFE20_OVThreshold = _x.BMS_AFE20_OVThreshold;
		BMS_AFE1_WakeUpSrc = _x.BMS_AFE1_WakeUpSrc;
		BMS_AFE2_WakeUpSrc = _x.BMS_AFE2_WakeUpSrc;
		BMS_AFE3_WakeUpSrc = _x.BMS_AFE3_WakeUpSrc;
		BMS_AFE4_WakeUpSrc = _x.BMS_AFE4_WakeUpSrc;
		BMS_AFE5_WakeUpSrc = _x.BMS_AFE5_WakeUpSrc;
		BMS_AFE6_WakeUpSrc = _x.BMS_AFE6_WakeUpSrc;
		BMS_AFE7_WakeUpSrc = _x.BMS_AFE7_WakeUpSrc;
		BMS_AFE8_WakeUpSrc = _x.BMS_AFE8_WakeUpSrc;
		BMS_AFE9_WakeUpSrc = _x.BMS_AFE9_WakeUpSrc;
		BMS_AFE10_WakeUpSrc = _x.BMS_AFE10_WakeUpSrc;
		BMS_AFE11_WakeUpSrc = _x.BMS_AFE11_WakeUpSrc;
		BMS_AFE12_WakeUpSrc = _x.BMS_AFE12_WakeUpSrc;
		BMS_AFE13_WakeUpSrc = _x.BMS_AFE13_WakeUpSrc;
		BMS_AFE14_WakeUpSrc = _x.BMS_AFE14_WakeUpSrc;
		BMS_AFE15_WakeUpSrc = _x.BMS_AFE15_WakeUpSrc;
		BMS_AFE16_WakeUpSrc = _x.BMS_AFE16_WakeUpSrc;
		BMS_AFE17_WakeUpSrc = _x.BMS_AFE17_WakeUpSrc;
		BMS_AFE18_WakeUpSrc = _x.BMS_AFE18_WakeUpSrc;
		BMS_AFE19_WakeUpSrc = _x.BMS_AFE19_WakeUpSrc;
		BMS_AFE20_WakeUpSrc = _x.BMS_AFE20_WakeUpSrc;
		BMS_AFE1_UVThreshold = _x.BMS_AFE1_UVThreshold;
		BMS_AFE2_UVThreshold = _x.BMS_AFE2_UVThreshold;
		BMS_AFE3_UVThreshold = _x.BMS_AFE3_UVThreshold;
		BMS_AFE4_UVThreshold = _x.BMS_AFE4_UVThreshold;
		BMS_AFE5_UVThreshold = _x.BMS_AFE5_UVThreshold;
		BMS_AFE6_UVThreshold = _x.BMS_AFE6_UVThreshold;
		BMS_AFE7_UVThreshold = _x.BMS_AFE7_UVThreshold;
		BMS_AFE8_UVThreshold = _x.BMS_AFE8_UVThreshold;
		BMS_AFE9_UVThreshold = _x.BMS_AFE9_UVThreshold;
		BMS_AFE10_UVThreshold = _x.BMS_AFE10_UVThreshold;
		BMS_AFE11_UVThreshold = _x.BMS_AFE11_UVThreshold;
		BMS_AFE12_UVThreshold = _x.BMS_AFE12_UVThreshold;
		BMS_AFE13_UVThreshold = _x.BMS_AFE13_UVThreshold;
		BMS_AFE14_UVThreshold = _x.BMS_AFE14_UVThreshold;
		BMS_AFE15_UVThreshold = _x.BMS_AFE15_UVThreshold;
		BMS_AFE16_UVThreshold = _x.BMS_AFE16_UVThreshold;
		BMS_AFE17_UVThreshold = _x.BMS_AFE17_UVThreshold;
		BMS_AFE18_UVThreshold = _x.BMS_AFE18_UVThreshold;
		BMS_AFE19_UVThreshold = _x.BMS_AFE19_UVThreshold;
		BMS_AFE20_UVThreshold = _x.BMS_AFE20_UVThreshold;
		BMS_AFE1_OTThreshold = _x.BMS_AFE1_OTThreshold;
		BMS_AFE2_OTThreshold = _x.BMS_AFE2_OTThreshold;
		BMS_AFE3_OTThreshold = _x.BMS_AFE3_OTThreshold;
		BMS_AFE4_OTThreshold = _x.BMS_AFE4_OTThreshold;
		BMS_AFE5_OTThreshold = _x.BMS_AFE5_OTThreshold;
		BMS_AFE6_OTThreshold = _x.BMS_AFE6_OTThreshold;
		BMS_AFE7_OTThreshold = _x.BMS_AFE7_OTThreshold;
		BMS_AFE8_OTThreshold = _x.BMS_AFE8_OTThreshold;
		BMS_AFE9_OTThreshold = _x.BMS_AFE9_OTThreshold;
		BMS_AFE10_OTThreshold = _x.BMS_AFE10_OTThreshold;
		BMS_AFE11_OTThreshold = _x.BMS_AFE11_OTThreshold;
		BMS_AFE12_OTThreshold = _x.BMS_AFE12_OTThreshold;
		BMS_AFE13_OTThreshold = _x.BMS_AFE13_OTThreshold;
		BMS_AFE14_OTThreshold = _x.BMS_AFE14_OTThreshold;
		BMS_AFE15_OTThreshold = _x.BMS_AFE15_OTThreshold;
		BMS_AFE16_OTThreshold = _x.BMS_AFE16_OTThreshold;
		BMS_AFE17_OTThreshold = _x.BMS_AFE17_OTThreshold;
		BMS_AFE18_OTThreshold = _x.BMS_AFE18_OTThreshold;
		BMS_AFE19_OTThreshold = _x.BMS_AFE19_OTThreshold;
		BMS_AFE20_OTThreshold = _x.BMS_AFE20_OTThreshold;
		BMS_AFE1_OTWakeUp_Enable = _x.BMS_AFE1_OTWakeUp_Enable;
		BMS_AFE2_OTWakeUp_Enable = _x.BMS_AFE2_OTWakeUp_Enable;
		BMS_AFE3_OTWakeUp_Enable = _x.BMS_AFE3_OTWakeUp_Enable;
		BMS_AFE4_OTWakeUp_Enable = _x.BMS_AFE4_OTWakeUp_Enable;
		BMS_AFE5_OTWakeUp_Enable = _x.BMS_AFE5_OTWakeUp_Enable;
		BMS_AFE6_OTWakeUp_Enable = _x.BMS_AFE6_OTWakeUp_Enable;
		BMS_AFE7_OTWakeUp_Enable = _x.BMS_AFE7_OTWakeUp_Enable;
		BMS_AFE8_OTWakeUp_Enable = _x.BMS_AFE8_OTWakeUp_Enable;
		BMS_AFE9_OTWakeUp_Enable = _x.BMS_AFE9_OTWakeUp_Enable;
		BMS_AFE10_OTWakeUp_Enable = _x.BMS_AFE10_OTWakeUp_Enable;
		BMS_AFE11_OTWakeUp_Enable = _x.BMS_AFE11_OTWakeUp_Enable;
		BMS_AFE12_OTWakeUp_Enable = _x.BMS_AFE12_OTWakeUp_Enable;
		BMS_AFE13_OTWakeUp_Enable = _x.BMS_AFE13_OTWakeUp_Enable;
		BMS_AFE14_OTWakeUp_Enable = _x.BMS_AFE14_OTWakeUp_Enable;
		BMS_AFE15_OTWakeUp_Enable = _x.BMS_AFE15_OTWakeUp_Enable;
		BMS_AFE16_OTWakeUp_Enable = _x.BMS_AFE16_OTWakeUp_Enable;
		BMS_AFE17_OTWakeUp_Enable = _x.BMS_AFE17_OTWakeUp_Enable;
		BMS_AFE18_OTWakeUp_Enable = _x.BMS_AFE18_OTWakeUp_Enable;
		BMS_AFE19_OTWakeUp_Enable = _x.BMS_AFE19_OTWakeUp_Enable;
		BMS_AFE20_OTWakeUp_Enable = _x.BMS_AFE20_OTWakeUp_Enable;
		BMS_AFE1_OVWakeUp_Enable = _x.BMS_AFE1_OVWakeUp_Enable;
		BMS_AFE2_OVWakeUp_Enable = _x.BMS_AFE2_OVWakeUp_Enable;
		BMS_AFE3_OVWakeUp_Enable = _x.BMS_AFE3_OVWakeUp_Enable;
		BMS_AFE4_OVWakeUp_Enable = _x.BMS_AFE4_OVWakeUp_Enable;
		BMS_AFE5_OVWakeUp_Enable = _x.BMS_AFE5_OVWakeUp_Enable;
		BMS_AFE6_OVWakeUp_Enable = _x.BMS_AFE6_OVWakeUp_Enable;
		BMS_AFE7_OVWakeUp_Enable = _x.BMS_AFE7_OVWakeUp_Enable;
		BMS_AFE8_OVWakeUp_Enable = _x.BMS_AFE8_OVWakeUp_Enable;
		BMS_AFE9_OVWakeUp_Enable = _x.BMS_AFE9_OVWakeUp_Enable;
		BMS_AFE10_OVWakeUp_Enable = _x.BMS_AFE10_OVWakeUp_Enable;
		BMS_AFE11_OVWakeUp_Enable = _x.BMS_AFE11_OVWakeUp_Enable;
		BMS_AFE12_OVWakeUp_Enable = _x.BMS_AFE12_OVWakeUp_Enable;
		BMS_AFE13_OVWakeUp_Enable = _x.BMS_AFE13_OVWakeUp_Enable;
		BMS_AFE14_OVWakeUp_Enable = _x.BMS_AFE14_OVWakeUp_Enable;
		BMS_AFE15_OVWakeUp_Enable = _x.BMS_AFE15_OVWakeUp_Enable;
		BMS_AFE16_OVWakeUp_Enable = _x.BMS_AFE16_OVWakeUp_Enable;
		BMS_AFE17_OVWakeUp_Enable = _x.BMS_AFE17_OVWakeUp_Enable;
		BMS_AFE18_OVWakeUp_Enable = _x.BMS_AFE18_OVWakeUp_Enable;
		BMS_AFE19_OVWakeUp_Enable = _x.BMS_AFE19_OVWakeUp_Enable;
		BMS_AFE20_OVWakeUp_Enable = _x.BMS_AFE20_OVWakeUp_Enable;
		BMS_AFE1_UVWakeUp_Enable = _x.BMS_AFE1_UVWakeUp_Enable;
		BMS_AFE2_UVWakeUp_Enable = _x.BMS_AFE2_UVWakeUp_Enable;
		BMS_AFE3_UVWakeUp_Enable = _x.BMS_AFE3_UVWakeUp_Enable;
		BMS_AFE4_UVWakeUp_Enable = _x.BMS_AFE4_UVWakeUp_Enable;
		BMS_AFE5_UVWakeUp_Enable = _x.BMS_AFE5_UVWakeUp_Enable;
		BMS_AFE6_UVWakeUp_Enable = _x.BMS_AFE6_UVWakeUp_Enable;
		BMS_AFE7_UVWakeUp_Enable = _x.BMS_AFE7_UVWakeUp_Enable;
		BMS_AFE8_UVWakeUp_Enable = _x.BMS_AFE8_UVWakeUp_Enable;
		BMS_AFE9_UVWakeUp_Enable = _x.BMS_AFE9_UVWakeUp_Enable;
		BMS_AFE10_UVWakeUp_Enable = _x.BMS_AFE10_UVWakeUp_Enable;
		BMS_AFE11_UVWakeUp_Enable = _x.BMS_AFE11_UVWakeUp_Enable;
		BMS_AFE12_UVWakeUp_Enable = _x.BMS_AFE12_UVWakeUp_Enable;
		BMS_AFE13_UVWakeUp_Enable = _x.BMS_AFE13_UVWakeUp_Enable;
		BMS_AFE14_UVWakeUp_Enable = _x.BMS_AFE14_UVWakeUp_Enable;
		BMS_AFE15_UVWakeUp_Enable = _x.BMS_AFE15_UVWakeUp_Enable;
		BMS_AFE16_UVWakeUp_Enable = _x.BMS_AFE16_UVWakeUp_Enable;
		BMS_AFE17_UVWakeUp_Enable = _x.BMS_AFE17_UVWakeUp_Enable;
		BMS_AFE18_UVWakeUp_Enable = _x.BMS_AFE18_UVWakeUp_Enable;
		BMS_AFE19_UVWakeUp_Enable = _x.BMS_AFE19_UVWakeUp_Enable;
		BMS_AFE20_UVWakeUp_Enable = _x.BMS_AFE20_UVWakeUp_Enable;
		return *this;
	}
	BDCBMSAFE& operator=(BDCBMSAFE &&_x){
		BMS_AFEWakeUpState = std::move(_x.BMS_AFEWakeUpState);
		BMS_ResetByAFESetErr = std::move(_x.BMS_ResetByAFESetErr);
		BMS_NrResetByAFESetErr = std::move(_x.BMS_NrResetByAFESetErr);
		BMS_AFE1_OVThreshold = std::move(_x.BMS_AFE1_OVThreshold);
		BMS_AFE2_OVThreshold = std::move(_x.BMS_AFE2_OVThreshold);
		BMS_AFE3_OVThreshold = std::move(_x.BMS_AFE3_OVThreshold);
		BMS_AFE4_OVThreshold = std::move(_x.BMS_AFE4_OVThreshold);
		BMS_AFE5_OVThreshold = std::move(_x.BMS_AFE5_OVThreshold);
		BMS_AFE6_OVThreshold = std::move(_x.BMS_AFE6_OVThreshold);
		BMS_AFE7_OVThreshold = std::move(_x.BMS_AFE7_OVThreshold);
		BMS_AFE8_OVThreshold = std::move(_x.BMS_AFE8_OVThreshold);
		BMS_AFE9_OVThreshold = std::move(_x.BMS_AFE9_OVThreshold);
		BMS_AFE10_OVThreshold = std::move(_x.BMS_AFE10_OVThreshold);
		BMS_AFE11_OVThreshold = std::move(_x.BMS_AFE11_OVThreshold);
		BMS_AFE12_OVThreshold = std::move(_x.BMS_AFE12_OVThreshold);
		BMS_AFE13_OVThreshold = std::move(_x.BMS_AFE13_OVThreshold);
		BMS_AFE14_OVThreshold = std::move(_x.BMS_AFE14_OVThreshold);
		BMS_AFE15_OVThreshold = std::move(_x.BMS_AFE15_OVThreshold);
		BMS_AFE16_OVThreshold = std::move(_x.BMS_AFE16_OVThreshold);
		BMS_AFE17_OVThreshold = std::move(_x.BMS_AFE17_OVThreshold);
		BMS_AFE18_OVThreshold = std::move(_x.BMS_AFE18_OVThreshold);
		BMS_AFE19_OVThreshold = std::move(_x.BMS_AFE19_OVThreshold);
		BMS_AFE20_OVThreshold = std::move(_x.BMS_AFE20_OVThreshold);
		BMS_AFE1_WakeUpSrc = std::move(_x.BMS_AFE1_WakeUpSrc);
		BMS_AFE2_WakeUpSrc = std::move(_x.BMS_AFE2_WakeUpSrc);
		BMS_AFE3_WakeUpSrc = std::move(_x.BMS_AFE3_WakeUpSrc);
		BMS_AFE4_WakeUpSrc = std::move(_x.BMS_AFE4_WakeUpSrc);
		BMS_AFE5_WakeUpSrc = std::move(_x.BMS_AFE5_WakeUpSrc);
		BMS_AFE6_WakeUpSrc = std::move(_x.BMS_AFE6_WakeUpSrc);
		BMS_AFE7_WakeUpSrc = std::move(_x.BMS_AFE7_WakeUpSrc);
		BMS_AFE8_WakeUpSrc = std::move(_x.BMS_AFE8_WakeUpSrc);
		BMS_AFE9_WakeUpSrc = std::move(_x.BMS_AFE9_WakeUpSrc);
		BMS_AFE10_WakeUpSrc = std::move(_x.BMS_AFE10_WakeUpSrc);
		BMS_AFE11_WakeUpSrc = std::move(_x.BMS_AFE11_WakeUpSrc);
		BMS_AFE12_WakeUpSrc = std::move(_x.BMS_AFE12_WakeUpSrc);
		BMS_AFE13_WakeUpSrc = std::move(_x.BMS_AFE13_WakeUpSrc);
		BMS_AFE14_WakeUpSrc = std::move(_x.BMS_AFE14_WakeUpSrc);
		BMS_AFE15_WakeUpSrc = std::move(_x.BMS_AFE15_WakeUpSrc);
		BMS_AFE16_WakeUpSrc = std::move(_x.BMS_AFE16_WakeUpSrc);
		BMS_AFE17_WakeUpSrc = std::move(_x.BMS_AFE17_WakeUpSrc);
		BMS_AFE18_WakeUpSrc = std::move(_x.BMS_AFE18_WakeUpSrc);
		BMS_AFE19_WakeUpSrc = std::move(_x.BMS_AFE19_WakeUpSrc);
		BMS_AFE20_WakeUpSrc = std::move(_x.BMS_AFE20_WakeUpSrc);
		BMS_AFE1_UVThreshold = std::move(_x.BMS_AFE1_UVThreshold);
		BMS_AFE2_UVThreshold = std::move(_x.BMS_AFE2_UVThreshold);
		BMS_AFE3_UVThreshold = std::move(_x.BMS_AFE3_UVThreshold);
		BMS_AFE4_UVThreshold = std::move(_x.BMS_AFE4_UVThreshold);
		BMS_AFE5_UVThreshold = std::move(_x.BMS_AFE5_UVThreshold);
		BMS_AFE6_UVThreshold = std::move(_x.BMS_AFE6_UVThreshold);
		BMS_AFE7_UVThreshold = std::move(_x.BMS_AFE7_UVThreshold);
		BMS_AFE8_UVThreshold = std::move(_x.BMS_AFE8_UVThreshold);
		BMS_AFE9_UVThreshold = std::move(_x.BMS_AFE9_UVThreshold);
		BMS_AFE10_UVThreshold = std::move(_x.BMS_AFE10_UVThreshold);
		BMS_AFE11_UVThreshold = std::move(_x.BMS_AFE11_UVThreshold);
		BMS_AFE12_UVThreshold = std::move(_x.BMS_AFE12_UVThreshold);
		BMS_AFE13_UVThreshold = std::move(_x.BMS_AFE13_UVThreshold);
		BMS_AFE14_UVThreshold = std::move(_x.BMS_AFE14_UVThreshold);
		BMS_AFE15_UVThreshold = std::move(_x.BMS_AFE15_UVThreshold);
		BMS_AFE16_UVThreshold = std::move(_x.BMS_AFE16_UVThreshold);
		BMS_AFE17_UVThreshold = std::move(_x.BMS_AFE17_UVThreshold);
		BMS_AFE18_UVThreshold = std::move(_x.BMS_AFE18_UVThreshold);
		BMS_AFE19_UVThreshold = std::move(_x.BMS_AFE19_UVThreshold);
		BMS_AFE20_UVThreshold = std::move(_x.BMS_AFE20_UVThreshold);
		BMS_AFE1_OTThreshold = std::move(_x.BMS_AFE1_OTThreshold);
		BMS_AFE2_OTThreshold = std::move(_x.BMS_AFE2_OTThreshold);
		BMS_AFE3_OTThreshold = std::move(_x.BMS_AFE3_OTThreshold);
		BMS_AFE4_OTThreshold = std::move(_x.BMS_AFE4_OTThreshold);
		BMS_AFE5_OTThreshold = std::move(_x.BMS_AFE5_OTThreshold);
		BMS_AFE6_OTThreshold = std::move(_x.BMS_AFE6_OTThreshold);
		BMS_AFE7_OTThreshold = std::move(_x.BMS_AFE7_OTThreshold);
		BMS_AFE8_OTThreshold = std::move(_x.BMS_AFE8_OTThreshold);
		BMS_AFE9_OTThreshold = std::move(_x.BMS_AFE9_OTThreshold);
		BMS_AFE10_OTThreshold = std::move(_x.BMS_AFE10_OTThreshold);
		BMS_AFE11_OTThreshold = std::move(_x.BMS_AFE11_OTThreshold);
		BMS_AFE12_OTThreshold = std::move(_x.BMS_AFE12_OTThreshold);
		BMS_AFE13_OTThreshold = std::move(_x.BMS_AFE13_OTThreshold);
		BMS_AFE14_OTThreshold = std::move(_x.BMS_AFE14_OTThreshold);
		BMS_AFE15_OTThreshold = std::move(_x.BMS_AFE15_OTThreshold);
		BMS_AFE16_OTThreshold = std::move(_x.BMS_AFE16_OTThreshold);
		BMS_AFE17_OTThreshold = std::move(_x.BMS_AFE17_OTThreshold);
		BMS_AFE18_OTThreshold = std::move(_x.BMS_AFE18_OTThreshold);
		BMS_AFE19_OTThreshold = std::move(_x.BMS_AFE19_OTThreshold);
		BMS_AFE20_OTThreshold = std::move(_x.BMS_AFE20_OTThreshold);
		BMS_AFE1_OTWakeUp_Enable = std::move(_x.BMS_AFE1_OTWakeUp_Enable);
		BMS_AFE2_OTWakeUp_Enable = std::move(_x.BMS_AFE2_OTWakeUp_Enable);
		BMS_AFE3_OTWakeUp_Enable = std::move(_x.BMS_AFE3_OTWakeUp_Enable);
		BMS_AFE4_OTWakeUp_Enable = std::move(_x.BMS_AFE4_OTWakeUp_Enable);
		BMS_AFE5_OTWakeUp_Enable = std::move(_x.BMS_AFE5_OTWakeUp_Enable);
		BMS_AFE6_OTWakeUp_Enable = std::move(_x.BMS_AFE6_OTWakeUp_Enable);
		BMS_AFE7_OTWakeUp_Enable = std::move(_x.BMS_AFE7_OTWakeUp_Enable);
		BMS_AFE8_OTWakeUp_Enable = std::move(_x.BMS_AFE8_OTWakeUp_Enable);
		BMS_AFE9_OTWakeUp_Enable = std::move(_x.BMS_AFE9_OTWakeUp_Enable);
		BMS_AFE10_OTWakeUp_Enable = std::move(_x.BMS_AFE10_OTWakeUp_Enable);
		BMS_AFE11_OTWakeUp_Enable = std::move(_x.BMS_AFE11_OTWakeUp_Enable);
		BMS_AFE12_OTWakeUp_Enable = std::move(_x.BMS_AFE12_OTWakeUp_Enable);
		BMS_AFE13_OTWakeUp_Enable = std::move(_x.BMS_AFE13_OTWakeUp_Enable);
		BMS_AFE14_OTWakeUp_Enable = std::move(_x.BMS_AFE14_OTWakeUp_Enable);
		BMS_AFE15_OTWakeUp_Enable = std::move(_x.BMS_AFE15_OTWakeUp_Enable);
		BMS_AFE16_OTWakeUp_Enable = std::move(_x.BMS_AFE16_OTWakeUp_Enable);
		BMS_AFE17_OTWakeUp_Enable = std::move(_x.BMS_AFE17_OTWakeUp_Enable);
		BMS_AFE18_OTWakeUp_Enable = std::move(_x.BMS_AFE18_OTWakeUp_Enable);
		BMS_AFE19_OTWakeUp_Enable = std::move(_x.BMS_AFE19_OTWakeUp_Enable);
		BMS_AFE20_OTWakeUp_Enable = std::move(_x.BMS_AFE20_OTWakeUp_Enable);
		BMS_AFE1_OVWakeUp_Enable = std::move(_x.BMS_AFE1_OVWakeUp_Enable);
		BMS_AFE2_OVWakeUp_Enable = std::move(_x.BMS_AFE2_OVWakeUp_Enable);
		BMS_AFE3_OVWakeUp_Enable = std::move(_x.BMS_AFE3_OVWakeUp_Enable);
		BMS_AFE4_OVWakeUp_Enable = std::move(_x.BMS_AFE4_OVWakeUp_Enable);
		BMS_AFE5_OVWakeUp_Enable = std::move(_x.BMS_AFE5_OVWakeUp_Enable);
		BMS_AFE6_OVWakeUp_Enable = std::move(_x.BMS_AFE6_OVWakeUp_Enable);
		BMS_AFE7_OVWakeUp_Enable = std::move(_x.BMS_AFE7_OVWakeUp_Enable);
		BMS_AFE8_OVWakeUp_Enable = std::move(_x.BMS_AFE8_OVWakeUp_Enable);
		BMS_AFE9_OVWakeUp_Enable = std::move(_x.BMS_AFE9_OVWakeUp_Enable);
		BMS_AFE10_OVWakeUp_Enable = std::move(_x.BMS_AFE10_OVWakeUp_Enable);
		BMS_AFE11_OVWakeUp_Enable = std::move(_x.BMS_AFE11_OVWakeUp_Enable);
		BMS_AFE12_OVWakeUp_Enable = std::move(_x.BMS_AFE12_OVWakeUp_Enable);
		BMS_AFE13_OVWakeUp_Enable = std::move(_x.BMS_AFE13_OVWakeUp_Enable);
		BMS_AFE14_OVWakeUp_Enable = std::move(_x.BMS_AFE14_OVWakeUp_Enable);
		BMS_AFE15_OVWakeUp_Enable = std::move(_x.BMS_AFE15_OVWakeUp_Enable);
		BMS_AFE16_OVWakeUp_Enable = std::move(_x.BMS_AFE16_OVWakeUp_Enable);
		BMS_AFE17_OVWakeUp_Enable = std::move(_x.BMS_AFE17_OVWakeUp_Enable);
		BMS_AFE18_OVWakeUp_Enable = std::move(_x.BMS_AFE18_OVWakeUp_Enable);
		BMS_AFE19_OVWakeUp_Enable = std::move(_x.BMS_AFE19_OVWakeUp_Enable);
		BMS_AFE20_OVWakeUp_Enable = std::move(_x.BMS_AFE20_OVWakeUp_Enable);
		BMS_AFE1_UVWakeUp_Enable = std::move(_x.BMS_AFE1_UVWakeUp_Enable);
		BMS_AFE2_UVWakeUp_Enable = std::move(_x.BMS_AFE2_UVWakeUp_Enable);
		BMS_AFE3_UVWakeUp_Enable = std::move(_x.BMS_AFE3_UVWakeUp_Enable);
		BMS_AFE4_UVWakeUp_Enable = std::move(_x.BMS_AFE4_UVWakeUp_Enable);
		BMS_AFE5_UVWakeUp_Enable = std::move(_x.BMS_AFE5_UVWakeUp_Enable);
		BMS_AFE6_UVWakeUp_Enable = std::move(_x.BMS_AFE6_UVWakeUp_Enable);
		BMS_AFE7_UVWakeUp_Enable = std::move(_x.BMS_AFE7_UVWakeUp_Enable);
		BMS_AFE8_UVWakeUp_Enable = std::move(_x.BMS_AFE8_UVWakeUp_Enable);
		BMS_AFE9_UVWakeUp_Enable = std::move(_x.BMS_AFE9_UVWakeUp_Enable);
		BMS_AFE10_UVWakeUp_Enable = std::move(_x.BMS_AFE10_UVWakeUp_Enable);
		BMS_AFE11_UVWakeUp_Enable = std::move(_x.BMS_AFE11_UVWakeUp_Enable);
		BMS_AFE12_UVWakeUp_Enable = std::move(_x.BMS_AFE12_UVWakeUp_Enable);
		BMS_AFE13_UVWakeUp_Enable = std::move(_x.BMS_AFE13_UVWakeUp_Enable);
		BMS_AFE14_UVWakeUp_Enable = std::move(_x.BMS_AFE14_UVWakeUp_Enable);
		BMS_AFE15_UVWakeUp_Enable = std::move(_x.BMS_AFE15_UVWakeUp_Enable);
		BMS_AFE16_UVWakeUp_Enable = std::move(_x.BMS_AFE16_UVWakeUp_Enable);
		BMS_AFE17_UVWakeUp_Enable = std::move(_x.BMS_AFE17_UVWakeUp_Enable);
		BMS_AFE18_UVWakeUp_Enable = std::move(_x.BMS_AFE18_UVWakeUp_Enable);
		BMS_AFE19_UVWakeUp_Enable = std::move(_x.BMS_AFE19_UVWakeUp_Enable);
		BMS_AFE20_UVWakeUp_Enable = std::move(_x.BMS_AFE20_UVWakeUp_Enable);
		return *this;
	}
*/

	using IsEnumerableTag = void;
	template<typename F>
	void enumerate(F& fun) {
		fun(BMS_AFEWakeUpState);
		fun(BMS_ResetByAFESetErr);
		fun(BMS_NrResetByAFESetErr);
		fun(BMS_AFE1_OVThreshold);
		fun(BMS_AFE2_OVThreshold);
		fun(BMS_AFE3_OVThreshold);
		fun(BMS_AFE4_OVThreshold);
		fun(BMS_AFE5_OVThreshold);
		fun(BMS_AFE6_OVThreshold);
		fun(BMS_AFE7_OVThreshold);
		fun(BMS_AFE8_OVThreshold);
		fun(BMS_AFE9_OVThreshold);
		fun(BMS_AFE10_OVThreshold);
		fun(BMS_AFE11_OVThreshold);
		fun(BMS_AFE12_OVThreshold);
		fun(BMS_AFE13_OVThreshold);
		fun(BMS_AFE14_OVThreshold);
		fun(BMS_AFE15_OVThreshold);
		fun(BMS_AFE16_OVThreshold);
		fun(BMS_AFE17_OVThreshold);
		fun(BMS_AFE18_OVThreshold);
		fun(BMS_AFE19_OVThreshold);
		fun(BMS_AFE20_OVThreshold);
		fun(BMS_AFE1_WakeUpSrc);
		fun(BMS_AFE2_WakeUpSrc);
		fun(BMS_AFE3_WakeUpSrc);
		fun(BMS_AFE4_WakeUpSrc);
		fun(BMS_AFE5_WakeUpSrc);
		fun(BMS_AFE6_WakeUpSrc);
		fun(BMS_AFE7_WakeUpSrc);
		fun(BMS_AFE8_WakeUpSrc);
		fun(BMS_AFE9_WakeUpSrc);
		fun(BMS_AFE10_WakeUpSrc);
		fun(BMS_AFE11_WakeUpSrc);
		fun(BMS_AFE12_WakeUpSrc);
		fun(BMS_AFE13_WakeUpSrc);
		fun(BMS_AFE14_WakeUpSrc);
		fun(BMS_AFE15_WakeUpSrc);
		fun(BMS_AFE16_WakeUpSrc);
		fun(BMS_AFE17_WakeUpSrc);
		fun(BMS_AFE18_WakeUpSrc);
		fun(BMS_AFE19_WakeUpSrc);
		fun(BMS_AFE20_WakeUpSrc);
		fun(BMS_AFE1_UVThreshold);
		fun(BMS_AFE2_UVThreshold);
		fun(BMS_AFE3_UVThreshold);
		fun(BMS_AFE4_UVThreshold);
		fun(BMS_AFE5_UVThreshold);
		fun(BMS_AFE6_UVThreshold);
		fun(BMS_AFE7_UVThreshold);
		fun(BMS_AFE8_UVThreshold);
		fun(BMS_AFE9_UVThreshold);
		fun(BMS_AFE10_UVThreshold);
		fun(BMS_AFE11_UVThreshold);
		fun(BMS_AFE12_UVThreshold);
		fun(BMS_AFE13_UVThreshold);
		fun(BMS_AFE14_UVThreshold);
		fun(BMS_AFE15_UVThreshold);
		fun(BMS_AFE16_UVThreshold);
		fun(BMS_AFE17_UVThreshold);
		fun(BMS_AFE18_UVThreshold);
		fun(BMS_AFE19_UVThreshold);
		fun(BMS_AFE20_UVThreshold);
		fun(BMS_AFE1_OTThreshold);
		fun(BMS_AFE2_OTThreshold);
		fun(BMS_AFE3_OTThreshold);
		fun(BMS_AFE4_OTThreshold);
		fun(BMS_AFE5_OTThreshold);
		fun(BMS_AFE6_OTThreshold);
		fun(BMS_AFE7_OTThreshold);
		fun(BMS_AFE8_OTThreshold);
		fun(BMS_AFE9_OTThreshold);
		fun(BMS_AFE10_OTThreshold);
		fun(BMS_AFE11_OTThreshold);
		fun(BMS_AFE12_OTThreshold);
		fun(BMS_AFE13_OTThreshold);
		fun(BMS_AFE14_OTThreshold);
		fun(BMS_AFE15_OTThreshold);
		fun(BMS_AFE16_OTThreshold);
		fun(BMS_AFE17_OTThreshold);
		fun(BMS_AFE18_OTThreshold);
		fun(BMS_AFE19_OTThreshold);
		fun(BMS_AFE20_OTThreshold);
		fun(BMS_AFE1_OTWakeUp_Enable);
		fun(BMS_AFE2_OTWakeUp_Enable);
		fun(BMS_AFE3_OTWakeUp_Enable);
		fun(BMS_AFE4_OTWakeUp_Enable);
		fun(BMS_AFE5_OTWakeUp_Enable);
		fun(BMS_AFE6_OTWakeUp_Enable);
		fun(BMS_AFE7_OTWakeUp_Enable);
		fun(BMS_AFE8_OTWakeUp_Enable);
		fun(BMS_AFE9_OTWakeUp_Enable);
		fun(BMS_AFE10_OTWakeUp_Enable);
		fun(BMS_AFE11_OTWakeUp_Enable);
		fun(BMS_AFE12_OTWakeUp_Enable);
		fun(BMS_AFE13_OTWakeUp_Enable);
		fun(BMS_AFE14_OTWakeUp_Enable);
		fun(BMS_AFE15_OTWakeUp_Enable);
		fun(BMS_AFE16_OTWakeUp_Enable);
		fun(BMS_AFE17_OTWakeUp_Enable);
		fun(BMS_AFE18_OTWakeUp_Enable);
		fun(BMS_AFE19_OTWakeUp_Enable);
		fun(BMS_AFE20_OTWakeUp_Enable);
		fun(BMS_AFE1_OVWakeUp_Enable);
		fun(BMS_AFE2_OVWakeUp_Enable);
		fun(BMS_AFE3_OVWakeUp_Enable);
		fun(BMS_AFE4_OVWakeUp_Enable);
		fun(BMS_AFE5_OVWakeUp_Enable);
		fun(BMS_AFE6_OVWakeUp_Enable);
		fun(BMS_AFE7_OVWakeUp_Enable);
		fun(BMS_AFE8_OVWakeUp_Enable);
		fun(BMS_AFE9_OVWakeUp_Enable);
		fun(BMS_AFE10_OVWakeUp_Enable);
		fun(BMS_AFE11_OVWakeUp_Enable);
		fun(BMS_AFE12_OVWakeUp_Enable);
		fun(BMS_AFE13_OVWakeUp_Enable);
		fun(BMS_AFE14_OVWakeUp_Enable);
		fun(BMS_AFE15_OVWakeUp_Enable);
		fun(BMS_AFE16_OVWakeUp_Enable);
		fun(BMS_AFE17_OVWakeUp_Enable);
		fun(BMS_AFE18_OVWakeUp_Enable);
		fun(BMS_AFE19_OVWakeUp_Enable);
		fun(BMS_AFE20_OVWakeUp_Enable);
		fun(BMS_AFE1_UVWakeUp_Enable);
		fun(BMS_AFE2_UVWakeUp_Enable);
		fun(BMS_AFE3_UVWakeUp_Enable);
		fun(BMS_AFE4_UVWakeUp_Enable);
		fun(BMS_AFE5_UVWakeUp_Enable);
		fun(BMS_AFE6_UVWakeUp_Enable);
		fun(BMS_AFE7_UVWakeUp_Enable);
		fun(BMS_AFE8_UVWakeUp_Enable);
		fun(BMS_AFE9_UVWakeUp_Enable);
		fun(BMS_AFE10_UVWakeUp_Enable);
		fun(BMS_AFE11_UVWakeUp_Enable);
		fun(BMS_AFE12_UVWakeUp_Enable);
		fun(BMS_AFE13_UVWakeUp_Enable);
		fun(BMS_AFE14_UVWakeUp_Enable);
		fun(BMS_AFE15_UVWakeUp_Enable);
		fun(BMS_AFE16_UVWakeUp_Enable);
		fun(BMS_AFE17_UVWakeUp_Enable);
		fun(BMS_AFE18_UVWakeUp_Enable);
		fun(BMS_AFE19_UVWakeUp_Enable);
		fun(BMS_AFE20_UVWakeUp_Enable);
	}

	template<typename F>
	void GetSize(F& fun) const{
		fun(BMS_AFEWakeUpState);
		fun(BMS_ResetByAFESetErr);
		fun(BMS_NrResetByAFESetErr);
		fun(BMS_AFE1_OVThreshold);
		fun(BMS_AFE2_OVThreshold);
		fun(BMS_AFE3_OVThreshold);
		fun(BMS_AFE4_OVThreshold);
		fun(BMS_AFE5_OVThreshold);
		fun(BMS_AFE6_OVThreshold);
		fun(BMS_AFE7_OVThreshold);
		fun(BMS_AFE8_OVThreshold);
		fun(BMS_AFE9_OVThreshold);
		fun(BMS_AFE10_OVThreshold);
		fun(BMS_AFE11_OVThreshold);
		fun(BMS_AFE12_OVThreshold);
		fun(BMS_AFE13_OVThreshold);
		fun(BMS_AFE14_OVThreshold);
		fun(BMS_AFE15_OVThreshold);
		fun(BMS_AFE16_OVThreshold);
		fun(BMS_AFE17_OVThreshold);
		fun(BMS_AFE18_OVThreshold);
		fun(BMS_AFE19_OVThreshold);
		fun(BMS_AFE20_OVThreshold);
		fun(BMS_AFE1_WakeUpSrc);
		fun(BMS_AFE2_WakeUpSrc);
		fun(BMS_AFE3_WakeUpSrc);
		fun(BMS_AFE4_WakeUpSrc);
		fun(BMS_AFE5_WakeUpSrc);
		fun(BMS_AFE6_WakeUpSrc);
		fun(BMS_AFE7_WakeUpSrc);
		fun(BMS_AFE8_WakeUpSrc);
		fun(BMS_AFE9_WakeUpSrc);
		fun(BMS_AFE10_WakeUpSrc);
		fun(BMS_AFE11_WakeUpSrc);
		fun(BMS_AFE12_WakeUpSrc);
		fun(BMS_AFE13_WakeUpSrc);
		fun(BMS_AFE14_WakeUpSrc);
		fun(BMS_AFE15_WakeUpSrc);
		fun(BMS_AFE16_WakeUpSrc);
		fun(BMS_AFE17_WakeUpSrc);
		fun(BMS_AFE18_WakeUpSrc);
		fun(BMS_AFE19_WakeUpSrc);
		fun(BMS_AFE20_WakeUpSrc);
		fun(BMS_AFE1_UVThreshold);
		fun(BMS_AFE2_UVThreshold);
		fun(BMS_AFE3_UVThreshold);
		fun(BMS_AFE4_UVThreshold);
		fun(BMS_AFE5_UVThreshold);
		fun(BMS_AFE6_UVThreshold);
		fun(BMS_AFE7_UVThreshold);
		fun(BMS_AFE8_UVThreshold);
		fun(BMS_AFE9_UVThreshold);
		fun(BMS_AFE10_UVThreshold);
		fun(BMS_AFE11_UVThreshold);
		fun(BMS_AFE12_UVThreshold);
		fun(BMS_AFE13_UVThreshold);
		fun(BMS_AFE14_UVThreshold);
		fun(BMS_AFE15_UVThreshold);
		fun(BMS_AFE16_UVThreshold);
		fun(BMS_AFE17_UVThreshold);
		fun(BMS_AFE18_UVThreshold);
		fun(BMS_AFE19_UVThreshold);
		fun(BMS_AFE20_UVThreshold);
		fun(BMS_AFE1_OTThreshold);
		fun(BMS_AFE2_OTThreshold);
		fun(BMS_AFE3_OTThreshold);
		fun(BMS_AFE4_OTThreshold);
		fun(BMS_AFE5_OTThreshold);
		fun(BMS_AFE6_OTThreshold);
		fun(BMS_AFE7_OTThreshold);
		fun(BMS_AFE8_OTThreshold);
		fun(BMS_AFE9_OTThreshold);
		fun(BMS_AFE10_OTThreshold);
		fun(BMS_AFE11_OTThreshold);
		fun(BMS_AFE12_OTThreshold);
		fun(BMS_AFE13_OTThreshold);
		fun(BMS_AFE14_OTThreshold);
		fun(BMS_AFE15_OTThreshold);
		fun(BMS_AFE16_OTThreshold);
		fun(BMS_AFE17_OTThreshold);
		fun(BMS_AFE18_OTThreshold);
		fun(BMS_AFE19_OTThreshold);
		fun(BMS_AFE20_OTThreshold);
		fun(BMS_AFE1_OTWakeUp_Enable);
		fun(BMS_AFE2_OTWakeUp_Enable);
		fun(BMS_AFE3_OTWakeUp_Enable);
		fun(BMS_AFE4_OTWakeUp_Enable);
		fun(BMS_AFE5_OTWakeUp_Enable);
		fun(BMS_AFE6_OTWakeUp_Enable);
		fun(BMS_AFE7_OTWakeUp_Enable);
		fun(BMS_AFE8_OTWakeUp_Enable);
		fun(BMS_AFE9_OTWakeUp_Enable);
		fun(BMS_AFE10_OTWakeUp_Enable);
		fun(BMS_AFE11_OTWakeUp_Enable);
		fun(BMS_AFE12_OTWakeUp_Enable);
		fun(BMS_AFE13_OTWakeUp_Enable);
		fun(BMS_AFE14_OTWakeUp_Enable);
		fun(BMS_AFE15_OTWakeUp_Enable);
		fun(BMS_AFE16_OTWakeUp_Enable);
		fun(BMS_AFE17_OTWakeUp_Enable);
		fun(BMS_AFE18_OTWakeUp_Enable);
		fun(BMS_AFE19_OTWakeUp_Enable);
		fun(BMS_AFE20_OTWakeUp_Enable);
		fun(BMS_AFE1_OVWakeUp_Enable);
		fun(BMS_AFE2_OVWakeUp_Enable);
		fun(BMS_AFE3_OVWakeUp_Enable);
		fun(BMS_AFE4_OVWakeUp_Enable);
		fun(BMS_AFE5_OVWakeUp_Enable);
		fun(BMS_AFE6_OVWakeUp_Enable);
		fun(BMS_AFE7_OVWakeUp_Enable);
		fun(BMS_AFE8_OVWakeUp_Enable);
		fun(BMS_AFE9_OVWakeUp_Enable);
		fun(BMS_AFE10_OVWakeUp_Enable);
		fun(BMS_AFE11_OVWakeUp_Enable);
		fun(BMS_AFE12_OVWakeUp_Enable);
		fun(BMS_AFE13_OVWakeUp_Enable);
		fun(BMS_AFE14_OVWakeUp_Enable);
		fun(BMS_AFE15_OVWakeUp_Enable);
		fun(BMS_AFE16_OVWakeUp_Enable);
		fun(BMS_AFE17_OVWakeUp_Enable);
		fun(BMS_AFE18_OVWakeUp_Enable);
		fun(BMS_AFE19_OVWakeUp_Enable);
		fun(BMS_AFE20_OVWakeUp_Enable);
		fun(BMS_AFE1_UVWakeUp_Enable);
		fun(BMS_AFE2_UVWakeUp_Enable);
		fun(BMS_AFE3_UVWakeUp_Enable);
		fun(BMS_AFE4_UVWakeUp_Enable);
		fun(BMS_AFE5_UVWakeUp_Enable);
		fun(BMS_AFE6_UVWakeUp_Enable);
		fun(BMS_AFE7_UVWakeUp_Enable);
		fun(BMS_AFE8_UVWakeUp_Enable);
		fun(BMS_AFE9_UVWakeUp_Enable);
		fun(BMS_AFE10_UVWakeUp_Enable);
		fun(BMS_AFE11_UVWakeUp_Enable);
		fun(BMS_AFE12_UVWakeUp_Enable);
		fun(BMS_AFE13_UVWakeUp_Enable);
		fun(BMS_AFE14_UVWakeUp_Enable);
		fun(BMS_AFE15_UVWakeUp_Enable);
		fun(BMS_AFE16_UVWakeUp_Enable);
		fun(BMS_AFE17_UVWakeUp_Enable);
		fun(BMS_AFE18_UVWakeUp_Enable);
		fun(BMS_AFE19_UVWakeUp_Enable);
		fun(BMS_AFE20_UVWakeUp_Enable);
	}
	template<typename F>
	void serialize(F& fun) const{
		fun << (BMS_AFEWakeUpState);
		fun << (BMS_ResetByAFESetErr);
		fun << (BMS_NrResetByAFESetErr);
		fun << (BMS_AFE1_OVThreshold);
		fun << (BMS_AFE2_OVThreshold);
		fun << (BMS_AFE3_OVThreshold);
		fun << (BMS_AFE4_OVThreshold);
		fun << (BMS_AFE5_OVThreshold);
		fun << (BMS_AFE6_OVThreshold);
		fun << (BMS_AFE7_OVThreshold);
		fun << (BMS_AFE8_OVThreshold);
		fun << (BMS_AFE9_OVThreshold);
		fun << (BMS_AFE10_OVThreshold);
		fun << (BMS_AFE11_OVThreshold);
		fun << (BMS_AFE12_OVThreshold);
		fun << (BMS_AFE13_OVThreshold);
		fun << (BMS_AFE14_OVThreshold);
		fun << (BMS_AFE15_OVThreshold);
		fun << (BMS_AFE16_OVThreshold);
		fun << (BMS_AFE17_OVThreshold);
		fun << (BMS_AFE18_OVThreshold);
		fun << (BMS_AFE19_OVThreshold);
		fun << (BMS_AFE20_OVThreshold);
		fun << (BMS_AFE1_WakeUpSrc);
		fun << (BMS_AFE2_WakeUpSrc);
		fun << (BMS_AFE3_WakeUpSrc);
		fun << (BMS_AFE4_WakeUpSrc);
		fun << (BMS_AFE5_WakeUpSrc);
		fun << (BMS_AFE6_WakeUpSrc);
		fun << (BMS_AFE7_WakeUpSrc);
		fun << (BMS_AFE8_WakeUpSrc);
		fun << (BMS_AFE9_WakeUpSrc);
		fun << (BMS_AFE10_WakeUpSrc);
		fun << (BMS_AFE11_WakeUpSrc);
		fun << (BMS_AFE12_WakeUpSrc);
		fun << (BMS_AFE13_WakeUpSrc);
		fun << (BMS_AFE14_WakeUpSrc);
		fun << (BMS_AFE15_WakeUpSrc);
		fun << (BMS_AFE16_WakeUpSrc);
		fun << (BMS_AFE17_WakeUpSrc);
		fun << (BMS_AFE18_WakeUpSrc);
		fun << (BMS_AFE19_WakeUpSrc);
		fun << (BMS_AFE20_WakeUpSrc);
		fun << (BMS_AFE1_UVThreshold);
		fun << (BMS_AFE2_UVThreshold);
		fun << (BMS_AFE3_UVThreshold);
		fun << (BMS_AFE4_UVThreshold);
		fun << (BMS_AFE5_UVThreshold);
		fun << (BMS_AFE6_UVThreshold);
		fun << (BMS_AFE7_UVThreshold);
		fun << (BMS_AFE8_UVThreshold);
		fun << (BMS_AFE9_UVThreshold);
		fun << (BMS_AFE10_UVThreshold);
		fun << (BMS_AFE11_UVThreshold);
		fun << (BMS_AFE12_UVThreshold);
		fun << (BMS_AFE13_UVThreshold);
		fun << (BMS_AFE14_UVThreshold);
		fun << (BMS_AFE15_UVThreshold);
		fun << (BMS_AFE16_UVThreshold);
		fun << (BMS_AFE17_UVThreshold);
		fun << (BMS_AFE18_UVThreshold);
		fun << (BMS_AFE19_UVThreshold);
		fun << (BMS_AFE20_UVThreshold);
		fun << (BMS_AFE1_OTThreshold);
		fun << (BMS_AFE2_OTThreshold);
		fun << (BMS_AFE3_OTThreshold);
		fun << (BMS_AFE4_OTThreshold);
		fun << (BMS_AFE5_OTThreshold);
		fun << (BMS_AFE6_OTThreshold);
		fun << (BMS_AFE7_OTThreshold);
		fun << (BMS_AFE8_OTThreshold);
		fun << (BMS_AFE9_OTThreshold);
		fun << (BMS_AFE10_OTThreshold);
		fun << (BMS_AFE11_OTThreshold);
		fun << (BMS_AFE12_OTThreshold);
		fun << (BMS_AFE13_OTThreshold);
		fun << (BMS_AFE14_OTThreshold);
		fun << (BMS_AFE15_OTThreshold);
		fun << (BMS_AFE16_OTThreshold);
		fun << (BMS_AFE17_OTThreshold);
		fun << (BMS_AFE18_OTThreshold);
		fun << (BMS_AFE19_OTThreshold);
		fun << (BMS_AFE20_OTThreshold);
		fun << (BMS_AFE1_OTWakeUp_Enable);
		fun << (BMS_AFE2_OTWakeUp_Enable);
		fun << (BMS_AFE3_OTWakeUp_Enable);
		fun << (BMS_AFE4_OTWakeUp_Enable);
		fun << (BMS_AFE5_OTWakeUp_Enable);
		fun << (BMS_AFE6_OTWakeUp_Enable);
		fun << (BMS_AFE7_OTWakeUp_Enable);
		fun << (BMS_AFE8_OTWakeUp_Enable);
		fun << (BMS_AFE9_OTWakeUp_Enable);
		fun << (BMS_AFE10_OTWakeUp_Enable);
		fun << (BMS_AFE11_OTWakeUp_Enable);
		fun << (BMS_AFE12_OTWakeUp_Enable);
		fun << (BMS_AFE13_OTWakeUp_Enable);
		fun << (BMS_AFE14_OTWakeUp_Enable);
		fun << (BMS_AFE15_OTWakeUp_Enable);
		fun << (BMS_AFE16_OTWakeUp_Enable);
		fun << (BMS_AFE17_OTWakeUp_Enable);
		fun << (BMS_AFE18_OTWakeUp_Enable);
		fun << (BMS_AFE19_OTWakeUp_Enable);
		fun << (BMS_AFE20_OTWakeUp_Enable);
		fun << (BMS_AFE1_OVWakeUp_Enable);
		fun << (BMS_AFE2_OVWakeUp_Enable);
		fun << (BMS_AFE3_OVWakeUp_Enable);
		fun << (BMS_AFE4_OVWakeUp_Enable);
		fun << (BMS_AFE5_OVWakeUp_Enable);
		fun << (BMS_AFE6_OVWakeUp_Enable);
		fun << (BMS_AFE7_OVWakeUp_Enable);
		fun << (BMS_AFE8_OVWakeUp_Enable);
		fun << (BMS_AFE9_OVWakeUp_Enable);
		fun << (BMS_AFE10_OVWakeUp_Enable);
		fun << (BMS_AFE11_OVWakeUp_Enable);
		fun << (BMS_AFE12_OVWakeUp_Enable);
		fun << (BMS_AFE13_OVWakeUp_Enable);
		fun << (BMS_AFE14_OVWakeUp_Enable);
		fun << (BMS_AFE15_OVWakeUp_Enable);
		fun << (BMS_AFE16_OVWakeUp_Enable);
		fun << (BMS_AFE17_OVWakeUp_Enable);
		fun << (BMS_AFE18_OVWakeUp_Enable);
		fun << (BMS_AFE19_OVWakeUp_Enable);
		fun << (BMS_AFE20_OVWakeUp_Enable);
		fun << (BMS_AFE1_UVWakeUp_Enable);
		fun << (BMS_AFE2_UVWakeUp_Enable);
		fun << (BMS_AFE3_UVWakeUp_Enable);
		fun << (BMS_AFE4_UVWakeUp_Enable);
		fun << (BMS_AFE5_UVWakeUp_Enable);
		fun << (BMS_AFE6_UVWakeUp_Enable);
		fun << (BMS_AFE7_UVWakeUp_Enable);
		fun << (BMS_AFE8_UVWakeUp_Enable);
		fun << (BMS_AFE9_UVWakeUp_Enable);
		fun << (BMS_AFE10_UVWakeUp_Enable);
		fun << (BMS_AFE11_UVWakeUp_Enable);
		fun << (BMS_AFE12_UVWakeUp_Enable);
		fun << (BMS_AFE13_UVWakeUp_Enable);
		fun << (BMS_AFE14_UVWakeUp_Enable);
		fun << (BMS_AFE15_UVWakeUp_Enable);
		fun << (BMS_AFE16_UVWakeUp_Enable);
		fun << (BMS_AFE17_UVWakeUp_Enable);
		fun << (BMS_AFE18_UVWakeUp_Enable);
		fun << (BMS_AFE19_UVWakeUp_Enable);
		fun << (BMS_AFE20_UVWakeUp_Enable);
	}
	template<typename F>
	void deserialize(F& fun){
		fun >> (BMS_AFEWakeUpState);
		fun >> (BMS_ResetByAFESetErr);
		fun >> (BMS_NrResetByAFESetErr);
		fun >> (BMS_AFE1_OVThreshold);
		fun >> (BMS_AFE2_OVThreshold);
		fun >> (BMS_AFE3_OVThreshold);
		fun >> (BMS_AFE4_OVThreshold);
		fun >> (BMS_AFE5_OVThreshold);
		fun >> (BMS_AFE6_OVThreshold);
		fun >> (BMS_AFE7_OVThreshold);
		fun >> (BMS_AFE8_OVThreshold);
		fun >> (BMS_AFE9_OVThreshold);
		fun >> (BMS_AFE10_OVThreshold);
		fun >> (BMS_AFE11_OVThreshold);
		fun >> (BMS_AFE12_OVThreshold);
		fun >> (BMS_AFE13_OVThreshold);
		fun >> (BMS_AFE14_OVThreshold);
		fun >> (BMS_AFE15_OVThreshold);
		fun >> (BMS_AFE16_OVThreshold);
		fun >> (BMS_AFE17_OVThreshold);
		fun >> (BMS_AFE18_OVThreshold);
		fun >> (BMS_AFE19_OVThreshold);
		fun >> (BMS_AFE20_OVThreshold);
		fun >> (BMS_AFE1_WakeUpSrc);
		fun >> (BMS_AFE2_WakeUpSrc);
		fun >> (BMS_AFE3_WakeUpSrc);
		fun >> (BMS_AFE4_WakeUpSrc);
		fun >> (BMS_AFE5_WakeUpSrc);
		fun >> (BMS_AFE6_WakeUpSrc);
		fun >> (BMS_AFE7_WakeUpSrc);
		fun >> (BMS_AFE8_WakeUpSrc);
		fun >> (BMS_AFE9_WakeUpSrc);
		fun >> (BMS_AFE10_WakeUpSrc);
		fun >> (BMS_AFE11_WakeUpSrc);
		fun >> (BMS_AFE12_WakeUpSrc);
		fun >> (BMS_AFE13_WakeUpSrc);
		fun >> (BMS_AFE14_WakeUpSrc);
		fun >> (BMS_AFE15_WakeUpSrc);
		fun >> (BMS_AFE16_WakeUpSrc);
		fun >> (BMS_AFE17_WakeUpSrc);
		fun >> (BMS_AFE18_WakeUpSrc);
		fun >> (BMS_AFE19_WakeUpSrc);
		fun >> (BMS_AFE20_WakeUpSrc);
		fun >> (BMS_AFE1_UVThreshold);
		fun >> (BMS_AFE2_UVThreshold);
		fun >> (BMS_AFE3_UVThreshold);
		fun >> (BMS_AFE4_UVThreshold);
		fun >> (BMS_AFE5_UVThreshold);
		fun >> (BMS_AFE6_UVThreshold);
		fun >> (BMS_AFE7_UVThreshold);
		fun >> (BMS_AFE8_UVThreshold);
		fun >> (BMS_AFE9_UVThreshold);
		fun >> (BMS_AFE10_UVThreshold);
		fun >> (BMS_AFE11_UVThreshold);
		fun >> (BMS_AFE12_UVThreshold);
		fun >> (BMS_AFE13_UVThreshold);
		fun >> (BMS_AFE14_UVThreshold);
		fun >> (BMS_AFE15_UVThreshold);
		fun >> (BMS_AFE16_UVThreshold);
		fun >> (BMS_AFE17_UVThreshold);
		fun >> (BMS_AFE18_UVThreshold);
		fun >> (BMS_AFE19_UVThreshold);
		fun >> (BMS_AFE20_UVThreshold);
		fun >> (BMS_AFE1_OTThreshold);
		fun >> (BMS_AFE2_OTThreshold);
		fun >> (BMS_AFE3_OTThreshold);
		fun >> (BMS_AFE4_OTThreshold);
		fun >> (BMS_AFE5_OTThreshold);
		fun >> (BMS_AFE6_OTThreshold);
		fun >> (BMS_AFE7_OTThreshold);
		fun >> (BMS_AFE8_OTThreshold);
		fun >> (BMS_AFE9_OTThreshold);
		fun >> (BMS_AFE10_OTThreshold);
		fun >> (BMS_AFE11_OTThreshold);
		fun >> (BMS_AFE12_OTThreshold);
		fun >> (BMS_AFE13_OTThreshold);
		fun >> (BMS_AFE14_OTThreshold);
		fun >> (BMS_AFE15_OTThreshold);
		fun >> (BMS_AFE16_OTThreshold);
		fun >> (BMS_AFE17_OTThreshold);
		fun >> (BMS_AFE18_OTThreshold);
		fun >> (BMS_AFE19_OTThreshold);
		fun >> (BMS_AFE20_OTThreshold);
		fun >> (BMS_AFE1_OTWakeUp_Enable);
		fun >> (BMS_AFE2_OTWakeUp_Enable);
		fun >> (BMS_AFE3_OTWakeUp_Enable);
		fun >> (BMS_AFE4_OTWakeUp_Enable);
		fun >> (BMS_AFE5_OTWakeUp_Enable);
		fun >> (BMS_AFE6_OTWakeUp_Enable);
		fun >> (BMS_AFE7_OTWakeUp_Enable);
		fun >> (BMS_AFE8_OTWakeUp_Enable);
		fun >> (BMS_AFE9_OTWakeUp_Enable);
		fun >> (BMS_AFE10_OTWakeUp_Enable);
		fun >> (BMS_AFE11_OTWakeUp_Enable);
		fun >> (BMS_AFE12_OTWakeUp_Enable);
		fun >> (BMS_AFE13_OTWakeUp_Enable);
		fun >> (BMS_AFE14_OTWakeUp_Enable);
		fun >> (BMS_AFE15_OTWakeUp_Enable);
		fun >> (BMS_AFE16_OTWakeUp_Enable);
		fun >> (BMS_AFE17_OTWakeUp_Enable);
		fun >> (BMS_AFE18_OTWakeUp_Enable);
		fun >> (BMS_AFE19_OTWakeUp_Enable);
		fun >> (BMS_AFE20_OTWakeUp_Enable);
		fun >> (BMS_AFE1_OVWakeUp_Enable);
		fun >> (BMS_AFE2_OVWakeUp_Enable);
		fun >> (BMS_AFE3_OVWakeUp_Enable);
		fun >> (BMS_AFE4_OVWakeUp_Enable);
		fun >> (BMS_AFE5_OVWakeUp_Enable);
		fun >> (BMS_AFE6_OVWakeUp_Enable);
		fun >> (BMS_AFE7_OVWakeUp_Enable);
		fun >> (BMS_AFE8_OVWakeUp_Enable);
		fun >> (BMS_AFE9_OVWakeUp_Enable);
		fun >> (BMS_AFE10_OVWakeUp_Enable);
		fun >> (BMS_AFE11_OVWakeUp_Enable);
		fun >> (BMS_AFE12_OVWakeUp_Enable);
		fun >> (BMS_AFE13_OVWakeUp_Enable);
		fun >> (BMS_AFE14_OVWakeUp_Enable);
		fun >> (BMS_AFE15_OVWakeUp_Enable);
		fun >> (BMS_AFE16_OVWakeUp_Enable);
		fun >> (BMS_AFE17_OVWakeUp_Enable);
		fun >> (BMS_AFE18_OVWakeUp_Enable);
		fun >> (BMS_AFE19_OVWakeUp_Enable);
		fun >> (BMS_AFE20_OVWakeUp_Enable);
		fun >> (BMS_AFE1_UVWakeUp_Enable);
		fun >> (BMS_AFE2_UVWakeUp_Enable);
		fun >> (BMS_AFE3_UVWakeUp_Enable);
		fun >> (BMS_AFE4_UVWakeUp_Enable);
		fun >> (BMS_AFE5_UVWakeUp_Enable);
		fun >> (BMS_AFE6_UVWakeUp_Enable);
		fun >> (BMS_AFE7_UVWakeUp_Enable);
		fun >> (BMS_AFE8_UVWakeUp_Enable);
		fun >> (BMS_AFE9_UVWakeUp_Enable);
		fun >> (BMS_AFE10_UVWakeUp_Enable);
		fun >> (BMS_AFE11_UVWakeUp_Enable);
		fun >> (BMS_AFE12_UVWakeUp_Enable);
		fun >> (BMS_AFE13_UVWakeUp_Enable);
		fun >> (BMS_AFE14_UVWakeUp_Enable);
		fun >> (BMS_AFE15_UVWakeUp_Enable);
		fun >> (BMS_AFE16_UVWakeUp_Enable);
		fun >> (BMS_AFE17_UVWakeUp_Enable);
		fun >> (BMS_AFE18_UVWakeUp_Enable);
		fun >> (BMS_AFE19_UVWakeUp_Enable);
		fun >> (BMS_AFE20_UVWakeUp_Enable);
	}
};

#endif //____BDCBMSAFE_H__
