#ifndef ____BDCITSDATA1_H__
#define ____BDCITSDATA1_H__


#include "cstdint"






struct BDCITSData1 {
public:
	std::uint16_t HVAC_RawCabinTemp;
	std::uint16_t HVAC_RawEvaTemp;
	std::uint8_t HVAC_RawCabinTempFault;
	std::uint8_t HVAC_RawEvaTempFault;
	std::uint8_t HVAC_CompLPtempFault;
	std::uint16_t HVAC_RefrigerantPr;
	std::uint8_t HVAC_RefrigerantPrFault;
	std::uint8_t HVAC_PTCInterWaterTemp1;
	std::uint8_t IPDS_AGSPowerSt;
	std::uint8_t IPDS_AGSPowerFaultSt;
	std::uint8_t IPDS_ECPPowerSt;
	std::uint8_t IPDS_EXVPowerSt;
	std::uint8_t AGS1_ActualPosition;
	std::uint8_t AGS1_ActTorqueBoost;
	std::uint8_t AGS1_HldTrqActive;
	std::uint8_t AGS1_MoveActive;
	std::uint8_t AGS1_CalibActive;
	std::uint8_t AGS1_CalibState;
	std::uint8_t AGS1_Sta_Overtravel;
	std::uint8_t AGS1_Sta_Blockage;
	std::uint8_t AGS1_Err_Electrical;
	std::uint8_t AGS1_Sta_UnderVolt;
	std::uint8_t AGS1_Sta_OverVolt;
	std::uint8_t AGS1_Sta_OverTemp;
	std::uint8_t AGS1_Sta_LINResp;
	std::uint8_t AGS2_ActualPosition;
	std::uint8_t AGS2_ActTorqueBoost;
	std::uint8_t AGS2_HldTrqActive;
	std::uint8_t AGS2_MoveActive;
	std::uint8_t AGS2_CalibActive;
	std::uint8_t AGS2_CalibState;
	std::uint8_t AGS2_Sta_Overtravel;
	std::uint8_t AGS2_Sta_Blockage;
	std::uint8_t AGS2_Err_Electrical;
	std::uint8_t AGS2_Sta_UnderVolt;
	std::uint8_t AGS2_Sta_OverVolt;
	std::uint8_t AGS2_Sta_OverTemp;
	std::uint8_t AGS2_Sta_LINResp;
	std::uint16_t DCU_AHF_ActPwr;
	std::uint8_t VCU_HvBattFastCoolingSt;
	std::uint8_t VCU_HVAC_CabinHeatOffReq;
	std::uint16_t VCU_AHF_TarPwr;
	std::uint8_t VCU_MotorLoopEstimatedFlow;
	std::uint8_t VCU_MotorLoopEstimatedFlowVD;
	std::uint16_t VCU_HVAPUTotalPwrAct;
	std::uint8_t VCU_BatKeepWarmSt;
	std::uint8_t VCU_stTempManageBD;
/*
	BDCITSData1() {}
	~BDCITSData1() {}
	BDCITSData1(const std::uint16_t _HVAC_RawCabinTemp,const std::uint16_t _HVAC_RawEvaTemp,const std::uint8_t _HVAC_RawCabinTempFault,const std::uint8_t _HVAC_RawEvaTempFault,const std::uint8_t _HVAC_CompLPtempFault,const std::uint16_t _HVAC_RefrigerantPr,const std::uint8_t _HVAC_RefrigerantPrFault,const std::uint8_t _HVAC_PTCInterWaterTemp1,const std::uint8_t _IPDS_AGSPowerSt,const std::uint8_t _IPDS_AGSPowerFaultSt,const std::uint8_t _IPDS_ECPPowerSt,const std::uint8_t _IPDS_EXVPowerSt,const std::uint8_t _AGS1_ActualPosition,const std::uint8_t _AGS1_ActTorqueBoost,const std::uint8_t _AGS1_HldTrqActive,const std::uint8_t _AGS1_MoveActive,const std::uint8_t _AGS1_CalibActive,const std::uint8_t _AGS1_CalibState,const std::uint8_t _AGS1_Sta_Overtravel,const std::uint8_t _AGS1_Sta_Blockage,const std::uint8_t _AGS1_Err_Electrical,const std::uint8_t _AGS1_Sta_UnderVolt,const std::uint8_t _AGS1_Sta_OverVolt,const std::uint8_t _AGS1_Sta_OverTemp,const std::uint8_t _AGS1_Sta_LINResp,const std::uint8_t _AGS2_ActualPosition,const std::uint8_t _AGS2_ActTorqueBoost,const std::uint8_t _AGS2_HldTrqActive,const std::uint8_t _AGS2_MoveActive,const std::uint8_t _AGS2_CalibActive,const std::uint8_t _AGS2_CalibState,const std::uint8_t _AGS2_Sta_Overtravel,const std::uint8_t _AGS2_Sta_Blockage,const std::uint8_t _AGS2_Err_Electrical,const std::uint8_t _AGS2_Sta_UnderVolt,const std::uint8_t _AGS2_Sta_OverVolt,const std::uint8_t _AGS2_Sta_OverTemp,const std::uint8_t _AGS2_Sta_LINResp,const std::uint16_t _DCU_AHF_ActPwr,const std::uint8_t _VCU_HvBattFastCoolingSt,const std::uint8_t _VCU_HVAC_CabinHeatOffReq,const std::uint16_t _VCU_AHF_TarPwr,const std::uint8_t _VCU_MotorLoopEstimatedFlow,const std::uint8_t _VCU_MotorLoopEstimatedFlowVD,const std::uint16_t _VCU_HVAPUTotalPwrAct,const std::uint8_t _VCU_BatKeepWarmSt,const std::uint8_t _VCU_stTempManageBD):HVAC_RawCabinTemp(_HVAC_RawCabinTemp),HVAC_RawEvaTemp(_HVAC_RawEvaTemp),HVAC_RawCabinTempFault(_HVAC_RawCabinTempFault),HVAC_RawEvaTempFault(_HVAC_RawEvaTempFault),HVAC_CompLPtempFault(_HVAC_CompLPtempFault),HVAC_RefrigerantPr(_HVAC_RefrigerantPr),HVAC_RefrigerantPrFault(_HVAC_RefrigerantPrFault),HVAC_PTCInterWaterTemp1(_HVAC_PTCInterWaterTemp1),IPDS_AGSPowerSt(_IPDS_AGSPowerSt),IPDS_AGSPowerFaultSt(_IPDS_AGSPowerFaultSt),IPDS_ECPPowerSt(_IPDS_ECPPowerSt),IPDS_EXVPowerSt(_IPDS_EXVPowerSt),AGS1_ActualPosition(_AGS1_ActualPosition),AGS1_ActTorqueBoost(_AGS1_ActTorqueBoost),AGS1_HldTrqActive(_AGS1_HldTrqActive),AGS1_MoveActive(_AGS1_MoveActive),AGS1_CalibActive(_AGS1_CalibActive),AGS1_CalibState(_AGS1_CalibState),AGS1_Sta_Overtravel(_AGS1_Sta_Overtravel),AGS1_Sta_Blockage(_AGS1_Sta_Blockage),AGS1_Err_Electrical(_AGS1_Err_Electrical),AGS1_Sta_UnderVolt(_AGS1_Sta_UnderVolt),AGS1_Sta_OverVolt(_AGS1_Sta_OverVolt),AGS1_Sta_OverTemp(_AGS1_Sta_OverTemp),AGS1_Sta_LINResp(_AGS1_Sta_LINResp),AGS2_ActualPosition(_AGS2_ActualPosition),AGS2_ActTorqueBoost(_AGS2_ActTorqueBoost),AGS2_HldTrqActive(_AGS2_HldTrqActive),AGS2_MoveActive(_AGS2_MoveActive),AGS2_CalibActive(_AGS2_CalibActive),AGS2_CalibState(_AGS2_CalibState),AGS2_Sta_Overtravel(_AGS2_Sta_Overtravel),AGS2_Sta_Blockage(_AGS2_Sta_Blockage),AGS2_Err_Electrical(_AGS2_Err_Electrical),AGS2_Sta_UnderVolt(_AGS2_Sta_UnderVolt),AGS2_Sta_OverVolt(_AGS2_Sta_OverVolt),AGS2_Sta_OverTemp(_AGS2_Sta_OverTemp),AGS2_Sta_LINResp(_AGS2_Sta_LINResp),DCU_AHF_ActPwr(_DCU_AHF_ActPwr),VCU_HvBattFastCoolingSt(_VCU_HvBattFastCoolingSt),VCU_HVAC_CabinHeatOffReq(_VCU_HVAC_CabinHeatOffReq),VCU_AHF_TarPwr(_VCU_AHF_TarPwr),VCU_MotorLoopEstimatedFlow(_VCU_MotorLoopEstimatedFlow),VCU_MotorLoopEstimatedFlowVD(_VCU_MotorLoopEstimatedFlowVD),VCU_HVAPUTotalPwrAct(_VCU_HVAPUTotalPwrAct),VCU_BatKeepWarmSt(_VCU_BatKeepWarmSt),VCU_stTempManageBD(_VCU_stTempManageBD) {}
	BDCITSData1(const BDCITSData1 &_x){
		HVAC_RawCabinTemp = _x.HVAC_RawCabinTemp;
		HVAC_RawEvaTemp = _x.HVAC_RawEvaTemp;
		HVAC_RawCabinTempFault = _x.HVAC_RawCabinTempFault;
		HVAC_RawEvaTempFault = _x.HVAC_RawEvaTempFault;
		HVAC_CompLPtempFault = _x.HVAC_CompLPtempFault;
		HVAC_RefrigerantPr = _x.HVAC_RefrigerantPr;
		HVAC_RefrigerantPrFault = _x.HVAC_RefrigerantPrFault;
		HVAC_PTCInterWaterTemp1 = _x.HVAC_PTCInterWaterTemp1;
		IPDS_AGSPowerSt = _x.IPDS_AGSPowerSt;
		IPDS_AGSPowerFaultSt = _x.IPDS_AGSPowerFaultSt;
		IPDS_ECPPowerSt = _x.IPDS_ECPPowerSt;
		IPDS_EXVPowerSt = _x.IPDS_EXVPowerSt;
		AGS1_ActualPosition = _x.AGS1_ActualPosition;
		AGS1_ActTorqueBoost = _x.AGS1_ActTorqueBoost;
		AGS1_HldTrqActive = _x.AGS1_HldTrqActive;
		AGS1_MoveActive = _x.AGS1_MoveActive;
		AGS1_CalibActive = _x.AGS1_CalibActive;
		AGS1_CalibState = _x.AGS1_CalibState;
		AGS1_Sta_Overtravel = _x.AGS1_Sta_Overtravel;
		AGS1_Sta_Blockage = _x.AGS1_Sta_Blockage;
		AGS1_Err_Electrical = _x.AGS1_Err_Electrical;
		AGS1_Sta_UnderVolt = _x.AGS1_Sta_UnderVolt;
		AGS1_Sta_OverVolt = _x.AGS1_Sta_OverVolt;
		AGS1_Sta_OverTemp = _x.AGS1_Sta_OverTemp;
		AGS1_Sta_LINResp = _x.AGS1_Sta_LINResp;
		AGS2_ActualPosition = _x.AGS2_ActualPosition;
		AGS2_ActTorqueBoost = _x.AGS2_ActTorqueBoost;
		AGS2_HldTrqActive = _x.AGS2_HldTrqActive;
		AGS2_MoveActive = _x.AGS2_MoveActive;
		AGS2_CalibActive = _x.AGS2_CalibActive;
		AGS2_CalibState = _x.AGS2_CalibState;
		AGS2_Sta_Overtravel = _x.AGS2_Sta_Overtravel;
		AGS2_Sta_Blockage = _x.AGS2_Sta_Blockage;
		AGS2_Err_Electrical = _x.AGS2_Err_Electrical;
		AGS2_Sta_UnderVolt = _x.AGS2_Sta_UnderVolt;
		AGS2_Sta_OverVolt = _x.AGS2_Sta_OverVolt;
		AGS2_Sta_OverTemp = _x.AGS2_Sta_OverTemp;
		AGS2_Sta_LINResp = _x.AGS2_Sta_LINResp;
		DCU_AHF_ActPwr = _x.DCU_AHF_ActPwr;
		VCU_HvBattFastCoolingSt = _x.VCU_HvBattFastCoolingSt;
		VCU_HVAC_CabinHeatOffReq = _x.VCU_HVAC_CabinHeatOffReq;
		VCU_AHF_TarPwr = _x.VCU_AHF_TarPwr;
		VCU_MotorLoopEstimatedFlow = _x.VCU_MotorLoopEstimatedFlow;
		VCU_MotorLoopEstimatedFlowVD = _x.VCU_MotorLoopEstimatedFlowVD;
		VCU_HVAPUTotalPwrAct = _x.VCU_HVAPUTotalPwrAct;
		VCU_BatKeepWarmSt = _x.VCU_BatKeepWarmSt;
		VCU_stTempManageBD = _x.VCU_stTempManageBD;
	}
	BDCITSData1(BDCITSData1 &&_x){
		HVAC_RawCabinTemp = std::move(_x.HVAC_RawCabinTemp);
		HVAC_RawEvaTemp = std::move(_x.HVAC_RawEvaTemp);
		HVAC_RawCabinTempFault = std::move(_x.HVAC_RawCabinTempFault);
		HVAC_RawEvaTempFault = std::move(_x.HVAC_RawEvaTempFault);
		HVAC_CompLPtempFault = std::move(_x.HVAC_CompLPtempFault);
		HVAC_RefrigerantPr = std::move(_x.HVAC_RefrigerantPr);
		HVAC_RefrigerantPrFault = std::move(_x.HVAC_RefrigerantPrFault);
		HVAC_PTCInterWaterTemp1 = std::move(_x.HVAC_PTCInterWaterTemp1);
		IPDS_AGSPowerSt = std::move(_x.IPDS_AGSPowerSt);
		IPDS_AGSPowerFaultSt = std::move(_x.IPDS_AGSPowerFaultSt);
		IPDS_ECPPowerSt = std::move(_x.IPDS_ECPPowerSt);
		IPDS_EXVPowerSt = std::move(_x.IPDS_EXVPowerSt);
		AGS1_ActualPosition = std::move(_x.AGS1_ActualPosition);
		AGS1_ActTorqueBoost = std::move(_x.AGS1_ActTorqueBoost);
		AGS1_HldTrqActive = std::move(_x.AGS1_HldTrqActive);
		AGS1_MoveActive = std::move(_x.AGS1_MoveActive);
		AGS1_CalibActive = std::move(_x.AGS1_CalibActive);
		AGS1_CalibState = std::move(_x.AGS1_CalibState);
		AGS1_Sta_Overtravel = std::move(_x.AGS1_Sta_Overtravel);
		AGS1_Sta_Blockage = std::move(_x.AGS1_Sta_Blockage);
		AGS1_Err_Electrical = std::move(_x.AGS1_Err_Electrical);
		AGS1_Sta_UnderVolt = std::move(_x.AGS1_Sta_UnderVolt);
		AGS1_Sta_OverVolt = std::move(_x.AGS1_Sta_OverVolt);
		AGS1_Sta_OverTemp = std::move(_x.AGS1_Sta_OverTemp);
		AGS1_Sta_LINResp = std::move(_x.AGS1_Sta_LINResp);
		AGS2_ActualPosition = std::move(_x.AGS2_ActualPosition);
		AGS2_ActTorqueBoost = std::move(_x.AGS2_ActTorqueBoost);
		AGS2_HldTrqActive = std::move(_x.AGS2_HldTrqActive);
		AGS2_MoveActive = std::move(_x.AGS2_MoveActive);
		AGS2_CalibActive = std::move(_x.AGS2_CalibActive);
		AGS2_CalibState = std::move(_x.AGS2_CalibState);
		AGS2_Sta_Overtravel = std::move(_x.AGS2_Sta_Overtravel);
		AGS2_Sta_Blockage = std::move(_x.AGS2_Sta_Blockage);
		AGS2_Err_Electrical = std::move(_x.AGS2_Err_Electrical);
		AGS2_Sta_UnderVolt = std::move(_x.AGS2_Sta_UnderVolt);
		AGS2_Sta_OverVolt = std::move(_x.AGS2_Sta_OverVolt);
		AGS2_Sta_OverTemp = std::move(_x.AGS2_Sta_OverTemp);
		AGS2_Sta_LINResp = std::move(_x.AGS2_Sta_LINResp);
		DCU_AHF_ActPwr = std::move(_x.DCU_AHF_ActPwr);
		VCU_HvBattFastCoolingSt = std::move(_x.VCU_HvBattFastCoolingSt);
		VCU_HVAC_CabinHeatOffReq = std::move(_x.VCU_HVAC_CabinHeatOffReq);
		VCU_AHF_TarPwr = std::move(_x.VCU_AHF_TarPwr);
		VCU_MotorLoopEstimatedFlow = std::move(_x.VCU_MotorLoopEstimatedFlow);
		VCU_MotorLoopEstimatedFlowVD = std::move(_x.VCU_MotorLoopEstimatedFlowVD);
		VCU_HVAPUTotalPwrAct = std::move(_x.VCU_HVAPUTotalPwrAct);
		VCU_BatKeepWarmSt = std::move(_x.VCU_BatKeepWarmSt);
		VCU_stTempManageBD = std::move(_x.VCU_stTempManageBD);
	}
	BDCITSData1& operator=(const BDCITSData1 &_x){
		HVAC_RawCabinTemp = _x.HVAC_RawCabinTemp;
		HVAC_RawEvaTemp = _x.HVAC_RawEvaTemp;
		HVAC_RawCabinTempFault = _x.HVAC_RawCabinTempFault;
		HVAC_RawEvaTempFault = _x.HVAC_RawEvaTempFault;
		HVAC_CompLPtempFault = _x.HVAC_CompLPtempFault;
		HVAC_RefrigerantPr = _x.HVAC_RefrigerantPr;
		HVAC_RefrigerantPrFault = _x.HVAC_RefrigerantPrFault;
		HVAC_PTCInterWaterTemp1 = _x.HVAC_PTCInterWaterTemp1;
		IPDS_AGSPowerSt = _x.IPDS_AGSPowerSt;
		IPDS_AGSPowerFaultSt = _x.IPDS_AGSPowerFaultSt;
		IPDS_ECPPowerSt = _x.IPDS_ECPPowerSt;
		IPDS_EXVPowerSt = _x.IPDS_EXVPowerSt;
		AGS1_ActualPosition = _x.AGS1_ActualPosition;
		AGS1_ActTorqueBoost = _x.AGS1_ActTorqueBoost;
		AGS1_HldTrqActive = _x.AGS1_HldTrqActive;
		AGS1_MoveActive = _x.AGS1_MoveActive;
		AGS1_CalibActive = _x.AGS1_CalibActive;
		AGS1_CalibState = _x.AGS1_CalibState;
		AGS1_Sta_Overtravel = _x.AGS1_Sta_Overtravel;
		AGS1_Sta_Blockage = _x.AGS1_Sta_Blockage;
		AGS1_Err_Electrical = _x.AGS1_Err_Electrical;
		AGS1_Sta_UnderVolt = _x.AGS1_Sta_UnderVolt;
		AGS1_Sta_OverVolt = _x.AGS1_Sta_OverVolt;
		AGS1_Sta_OverTemp = _x.AGS1_Sta_OverTemp;
		AGS1_Sta_LINResp = _x.AGS1_Sta_LINResp;
		AGS2_ActualPosition = _x.AGS2_ActualPosition;
		AGS2_ActTorqueBoost = _x.AGS2_ActTorqueBoost;
		AGS2_HldTrqActive = _x.AGS2_HldTrqActive;
		AGS2_MoveActive = _x.AGS2_MoveActive;
		AGS2_CalibActive = _x.AGS2_CalibActive;
		AGS2_CalibState = _x.AGS2_CalibState;
		AGS2_Sta_Overtravel = _x.AGS2_Sta_Overtravel;
		AGS2_Sta_Blockage = _x.AGS2_Sta_Blockage;
		AGS2_Err_Electrical = _x.AGS2_Err_Electrical;
		AGS2_Sta_UnderVolt = _x.AGS2_Sta_UnderVolt;
		AGS2_Sta_OverVolt = _x.AGS2_Sta_OverVolt;
		AGS2_Sta_OverTemp = _x.AGS2_Sta_OverTemp;
		AGS2_Sta_LINResp = _x.AGS2_Sta_LINResp;
		DCU_AHF_ActPwr = _x.DCU_AHF_ActPwr;
		VCU_HvBattFastCoolingSt = _x.VCU_HvBattFastCoolingSt;
		VCU_HVAC_CabinHeatOffReq = _x.VCU_HVAC_CabinHeatOffReq;
		VCU_AHF_TarPwr = _x.VCU_AHF_TarPwr;
		VCU_MotorLoopEstimatedFlow = _x.VCU_MotorLoopEstimatedFlow;
		VCU_MotorLoopEstimatedFlowVD = _x.VCU_MotorLoopEstimatedFlowVD;
		VCU_HVAPUTotalPwrAct = _x.VCU_HVAPUTotalPwrAct;
		VCU_BatKeepWarmSt = _x.VCU_BatKeepWarmSt;
		VCU_stTempManageBD = _x.VCU_stTempManageBD;
		return *this;
	}
	BDCITSData1& operator=(BDCITSData1 &&_x){
		HVAC_RawCabinTemp = std::move(_x.HVAC_RawCabinTemp);
		HVAC_RawEvaTemp = std::move(_x.HVAC_RawEvaTemp);
		HVAC_RawCabinTempFault = std::move(_x.HVAC_RawCabinTempFault);
		HVAC_RawEvaTempFault = std::move(_x.HVAC_RawEvaTempFault);
		HVAC_CompLPtempFault = std::move(_x.HVAC_CompLPtempFault);
		HVAC_RefrigerantPr = std::move(_x.HVAC_RefrigerantPr);
		HVAC_RefrigerantPrFault = std::move(_x.HVAC_RefrigerantPrFault);
		HVAC_PTCInterWaterTemp1 = std::move(_x.HVAC_PTCInterWaterTemp1);
		IPDS_AGSPowerSt = std::move(_x.IPDS_AGSPowerSt);
		IPDS_AGSPowerFaultSt = std::move(_x.IPDS_AGSPowerFaultSt);
		IPDS_ECPPowerSt = std::move(_x.IPDS_ECPPowerSt);
		IPDS_EXVPowerSt = std::move(_x.IPDS_EXVPowerSt);
		AGS1_ActualPosition = std::move(_x.AGS1_ActualPosition);
		AGS1_ActTorqueBoost = std::move(_x.AGS1_ActTorqueBoost);
		AGS1_HldTrqActive = std::move(_x.AGS1_HldTrqActive);
		AGS1_MoveActive = std::move(_x.AGS1_MoveActive);
		AGS1_CalibActive = std::move(_x.AGS1_CalibActive);
		AGS1_CalibState = std::move(_x.AGS1_CalibState);
		AGS1_Sta_Overtravel = std::move(_x.AGS1_Sta_Overtravel);
		AGS1_Sta_Blockage = std::move(_x.AGS1_Sta_Blockage);
		AGS1_Err_Electrical = std::move(_x.AGS1_Err_Electrical);
		AGS1_Sta_UnderVolt = std::move(_x.AGS1_Sta_UnderVolt);
		AGS1_Sta_OverVolt = std::move(_x.AGS1_Sta_OverVolt);
		AGS1_Sta_OverTemp = std::move(_x.AGS1_Sta_OverTemp);
		AGS1_Sta_LINResp = std::move(_x.AGS1_Sta_LINResp);
		AGS2_ActualPosition = std::move(_x.AGS2_ActualPosition);
		AGS2_ActTorqueBoost = std::move(_x.AGS2_ActTorqueBoost);
		AGS2_HldTrqActive = std::move(_x.AGS2_HldTrqActive);
		AGS2_MoveActive = std::move(_x.AGS2_MoveActive);
		AGS2_CalibActive = std::move(_x.AGS2_CalibActive);
		AGS2_CalibState = std::move(_x.AGS2_CalibState);
		AGS2_Sta_Overtravel = std::move(_x.AGS2_Sta_Overtravel);
		AGS2_Sta_Blockage = std::move(_x.AGS2_Sta_Blockage);
		AGS2_Err_Electrical = std::move(_x.AGS2_Err_Electrical);
		AGS2_Sta_UnderVolt = std::move(_x.AGS2_Sta_UnderVolt);
		AGS2_Sta_OverVolt = std::move(_x.AGS2_Sta_OverVolt);
		AGS2_Sta_OverTemp = std::move(_x.AGS2_Sta_OverTemp);
		AGS2_Sta_LINResp = std::move(_x.AGS2_Sta_LINResp);
		DCU_AHF_ActPwr = std::move(_x.DCU_AHF_ActPwr);
		VCU_HvBattFastCoolingSt = std::move(_x.VCU_HvBattFastCoolingSt);
		VCU_HVAC_CabinHeatOffReq = std::move(_x.VCU_HVAC_CabinHeatOffReq);
		VCU_AHF_TarPwr = std::move(_x.VCU_AHF_TarPwr);
		VCU_MotorLoopEstimatedFlow = std::move(_x.VCU_MotorLoopEstimatedFlow);
		VCU_MotorLoopEstimatedFlowVD = std::move(_x.VCU_MotorLoopEstimatedFlowVD);
		VCU_HVAPUTotalPwrAct = std::move(_x.VCU_HVAPUTotalPwrAct);
		VCU_BatKeepWarmSt = std::move(_x.VCU_BatKeepWarmSt);
		VCU_stTempManageBD = std::move(_x.VCU_stTempManageBD);
		return *this;
	}
*/

	using IsEnumerableTag = void;
	template<typename F>
	void enumerate(F& fun) {
		fun(HVAC_RawCabinTemp);
		fun(HVAC_RawEvaTemp);
		fun(HVAC_RawCabinTempFault);
		fun(HVAC_RawEvaTempFault);
		fun(HVAC_CompLPtempFault);
		fun(HVAC_RefrigerantPr);
		fun(HVAC_RefrigerantPrFault);
		fun(HVAC_PTCInterWaterTemp1);
		fun(IPDS_AGSPowerSt);
		fun(IPDS_AGSPowerFaultSt);
		fun(IPDS_ECPPowerSt);
		fun(IPDS_EXVPowerSt);
		fun(AGS1_ActualPosition);
		fun(AGS1_ActTorqueBoost);
		fun(AGS1_HldTrqActive);
		fun(AGS1_MoveActive);
		fun(AGS1_CalibActive);
		fun(AGS1_CalibState);
		fun(AGS1_Sta_Overtravel);
		fun(AGS1_Sta_Blockage);
		fun(AGS1_Err_Electrical);
		fun(AGS1_Sta_UnderVolt);
		fun(AGS1_Sta_OverVolt);
		fun(AGS1_Sta_OverTemp);
		fun(AGS1_Sta_LINResp);
		fun(AGS2_ActualPosition);
		fun(AGS2_ActTorqueBoost);
		fun(AGS2_HldTrqActive);
		fun(AGS2_MoveActive);
		fun(AGS2_CalibActive);
		fun(AGS2_CalibState);
		fun(AGS2_Sta_Overtravel);
		fun(AGS2_Sta_Blockage);
		fun(AGS2_Err_Electrical);
		fun(AGS2_Sta_UnderVolt);
		fun(AGS2_Sta_OverVolt);
		fun(AGS2_Sta_OverTemp);
		fun(AGS2_Sta_LINResp);
		fun(DCU_AHF_ActPwr);
		fun(VCU_HvBattFastCoolingSt);
		fun(VCU_HVAC_CabinHeatOffReq);
		fun(VCU_AHF_TarPwr);
		fun(VCU_MotorLoopEstimatedFlow);
		fun(VCU_MotorLoopEstimatedFlowVD);
		fun(VCU_HVAPUTotalPwrAct);
		fun(VCU_BatKeepWarmSt);
		fun(VCU_stTempManageBD);
	}

	template<typename F>
	void GetSize(F& fun) const{
		fun(HVAC_RawCabinTemp);
		fun(HVAC_RawEvaTemp);
		fun(HVAC_RawCabinTempFault);
		fun(HVAC_RawEvaTempFault);
		fun(HVAC_CompLPtempFault);
		fun(HVAC_RefrigerantPr);
		fun(HVAC_RefrigerantPrFault);
		fun(HVAC_PTCInterWaterTemp1);
		fun(IPDS_AGSPowerSt);
		fun(IPDS_AGSPowerFaultSt);
		fun(IPDS_ECPPowerSt);
		fun(IPDS_EXVPowerSt);
		fun(AGS1_ActualPosition);
		fun(AGS1_ActTorqueBoost);
		fun(AGS1_HldTrqActive);
		fun(AGS1_MoveActive);
		fun(AGS1_CalibActive);
		fun(AGS1_CalibState);
		fun(AGS1_Sta_Overtravel);
		fun(AGS1_Sta_Blockage);
		fun(AGS1_Err_Electrical);
		fun(AGS1_Sta_UnderVolt);
		fun(AGS1_Sta_OverVolt);
		fun(AGS1_Sta_OverTemp);
		fun(AGS1_Sta_LINResp);
		fun(AGS2_ActualPosition);
		fun(AGS2_ActTorqueBoost);
		fun(AGS2_HldTrqActive);
		fun(AGS2_MoveActive);
		fun(AGS2_CalibActive);
		fun(AGS2_CalibState);
		fun(AGS2_Sta_Overtravel);
		fun(AGS2_Sta_Blockage);
		fun(AGS2_Err_Electrical);
		fun(AGS2_Sta_UnderVolt);
		fun(AGS2_Sta_OverVolt);
		fun(AGS2_Sta_OverTemp);
		fun(AGS2_Sta_LINResp);
		fun(DCU_AHF_ActPwr);
		fun(VCU_HvBattFastCoolingSt);
		fun(VCU_HVAC_CabinHeatOffReq);
		fun(VCU_AHF_TarPwr);
		fun(VCU_MotorLoopEstimatedFlow);
		fun(VCU_MotorLoopEstimatedFlowVD);
		fun(VCU_HVAPUTotalPwrAct);
		fun(VCU_BatKeepWarmSt);
		fun(VCU_stTempManageBD);
	}
	template<typename F>
	void serialize(F& fun) const{
		fun << (HVAC_RawCabinTemp);
		fun << (HVAC_RawEvaTemp);
		fun << (HVAC_RawCabinTempFault);
		fun << (HVAC_RawEvaTempFault);
		fun << (HVAC_CompLPtempFault);
		fun << (HVAC_RefrigerantPr);
		fun << (HVAC_RefrigerantPrFault);
		fun << (HVAC_PTCInterWaterTemp1);
		fun << (IPDS_AGSPowerSt);
		fun << (IPDS_AGSPowerFaultSt);
		fun << (IPDS_ECPPowerSt);
		fun << (IPDS_EXVPowerSt);
		fun << (AGS1_ActualPosition);
		fun << (AGS1_ActTorqueBoost);
		fun << (AGS1_HldTrqActive);
		fun << (AGS1_MoveActive);
		fun << (AGS1_CalibActive);
		fun << (AGS1_CalibState);
		fun << (AGS1_Sta_Overtravel);
		fun << (AGS1_Sta_Blockage);
		fun << (AGS1_Err_Electrical);
		fun << (AGS1_Sta_UnderVolt);
		fun << (AGS1_Sta_OverVolt);
		fun << (AGS1_Sta_OverTemp);
		fun << (AGS1_Sta_LINResp);
		fun << (AGS2_ActualPosition);
		fun << (AGS2_ActTorqueBoost);
		fun << (AGS2_HldTrqActive);
		fun << (AGS2_MoveActive);
		fun << (AGS2_CalibActive);
		fun << (AGS2_CalibState);
		fun << (AGS2_Sta_Overtravel);
		fun << (AGS2_Sta_Blockage);
		fun << (AGS2_Err_Electrical);
		fun << (AGS2_Sta_UnderVolt);
		fun << (AGS2_Sta_OverVolt);
		fun << (AGS2_Sta_OverTemp);
		fun << (AGS2_Sta_LINResp);
		fun << (DCU_AHF_ActPwr);
		fun << (VCU_HvBattFastCoolingSt);
		fun << (VCU_HVAC_CabinHeatOffReq);
		fun << (VCU_AHF_TarPwr);
		fun << (VCU_MotorLoopEstimatedFlow);
		fun << (VCU_MotorLoopEstimatedFlowVD);
		fun << (VCU_HVAPUTotalPwrAct);
		fun << (VCU_BatKeepWarmSt);
		fun << (VCU_stTempManageBD);
	}
	template<typename F>
	void deserialize(F& fun){
		fun >> (HVAC_RawCabinTemp);
		fun >> (HVAC_RawEvaTemp);
		fun >> (HVAC_RawCabinTempFault);
		fun >> (HVAC_RawEvaTempFault);
		fun >> (HVAC_CompLPtempFault);
		fun >> (HVAC_RefrigerantPr);
		fun >> (HVAC_RefrigerantPrFault);
		fun >> (HVAC_PTCInterWaterTemp1);
		fun >> (IPDS_AGSPowerSt);
		fun >> (IPDS_AGSPowerFaultSt);
		fun >> (IPDS_ECPPowerSt);
		fun >> (IPDS_EXVPowerSt);
		fun >> (AGS1_ActualPosition);
		fun >> (AGS1_ActTorqueBoost);
		fun >> (AGS1_HldTrqActive);
		fun >> (AGS1_MoveActive);
		fun >> (AGS1_CalibActive);
		fun >> (AGS1_CalibState);
		fun >> (AGS1_Sta_Overtravel);
		fun >> (AGS1_Sta_Blockage);
		fun >> (AGS1_Err_Electrical);
		fun >> (AGS1_Sta_UnderVolt);
		fun >> (AGS1_Sta_OverVolt);
		fun >> (AGS1_Sta_OverTemp);
		fun >> (AGS1_Sta_LINResp);
		fun >> (AGS2_ActualPosition);
		fun >> (AGS2_ActTorqueBoost);
		fun >> (AGS2_HldTrqActive);
		fun >> (AGS2_MoveActive);
		fun >> (AGS2_CalibActive);
		fun >> (AGS2_CalibState);
		fun >> (AGS2_Sta_Overtravel);
		fun >> (AGS2_Sta_Blockage);
		fun >> (AGS2_Err_Electrical);
		fun >> (AGS2_Sta_UnderVolt);
		fun >> (AGS2_Sta_OverVolt);
		fun >> (AGS2_Sta_OverTemp);
		fun >> (AGS2_Sta_LINResp);
		fun >> (DCU_AHF_ActPwr);
		fun >> (VCU_HvBattFastCoolingSt);
		fun >> (VCU_HVAC_CabinHeatOffReq);
		fun >> (VCU_AHF_TarPwr);
		fun >> (VCU_MotorLoopEstimatedFlow);
		fun >> (VCU_MotorLoopEstimatedFlowVD);
		fun >> (VCU_HVAPUTotalPwrAct);
		fun >> (VCU_BatKeepWarmSt);
		fun >> (VCU_stTempManageBD);
	}
};

#endif //____BDCITSDATA1_H__
